bots/po-refresh

In 0cda3d2a bots learned how to add and drop languages with updating
manifest and LINGUAS. However these are very specific just for
c-p/cockpit but not used for other projects.
This commit teaches Mr. po-refresh not to try to update files that are
not present.

[no-test] bots: Make po-refresh bot more universal

---

pkg/machines/libvirt-common.js

getElementsByTagName method from DOMParser has slightly different
behaviour on Edge compared to other browsers that cockpit supports.
Specifically, when there are elements from different namespaces with
the same tag, getElementsByTagName will include them in the result array
when called inside Edge, but when called in other browsers it won't.
In our case, the <os> element actually exists in another namespace apart
from the empty one. It's the <libosinfo:os> which is containing the
installation media of a VM.
Adjust the calling of getElementsByTagName to getElementsByTagNameNS to
fix this issue.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1692707

machines: fix oops in main machines page when using Edge browser

---

pkg/storaged/client.js
pkg/storaged/content-views.jsx
pkg/storaged/lvol-tabs.jsx
pkg/storaged/warnings.jsx
test/verify/check-storage-resize

When resizing a logical volume, Cockpit resizes the content
accordingly.  But if the content doesn't initially fills the whole
volume, it's not clear what the expected behavior is.  Thus, we want
to force people to first bring the content and volume sizes into
agreement.
This is achieved by moving the "unused-space" warning to the "Volume"
tab and making it a strict alternative to the Shrink/Grow buttons.
Either you can shrink/grow the volume, or you have to deal with the
unused space.

storage: Don't allow resizing of volumes with unused space

---

test/verify/check-networking-firewall

testNetworkingPage was sometimes failing because of journal messages containing
the following line:
The name org.fedoraproject.FirewallD1 was not provided by any .service files
This is suprisingly an error coming from libvirtd, which is complaining
that firewalld was stopped while libvirtd was running. For more info
see, https://bugzilla.redhat.com/show_bug.cgi?id=1348434
Since this is harmless for us, and as mentioned in the BZ is an WONTFIX
issue, let's ignore it in the test's teardown checks.

Fix testNetworkingPage flake

---

pkg/networkmanager/interfaces.js
test/verify/check-networking-checkpoints

This helps when the browser is on Windows.
Fixes #7859

networking: Reduce checkpoint rollback time to 7 seconds

---

bots/make-checkout

Use api.repo that is initialised with opts.repo. If opts.repo was not
provided then repo from current origin is deduced.

[no-test] bots: Default repo to origin if not provided

---

pkg/machines/components/create-vm-dialog/autoDetectOS.py
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/create-vm-dialog/createVmDialogUtils.js
pkg/machines/getOSList.py
pkg/machines/libvirt-common.js
pkg/machines/scripts/get_os_list.sh
tools/cockpit.spec
tools/debian/control

Instead of calling libosinfo tools, let's rely on libosinfo APIs in
order to avoid doing a lot of parsing to match the detected OS from a
media or a tree.
In order to do so, the code in libvirt-common.js has been expanded to
also store the (unique) OS ID and, when detecting some media or tree,
then just use this ID when filtering the OS list in autodetectOS().
With the changes, two new python scripts have been added:
- autoDetectOS.py, which does the media/tree detection and returns the
OS ID;
- getOSList.py, which gets exactly the same information (and in the same
format) returned by osinfo-query, plus the OS ID.
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

machines: Use libosinfo APIs instead of calling its tools

---

pkg/systemd/logs.js
test/verify/check-journal

Calling `didnt_reach_start` without any arguments results in calling
`journalctl -r`, which fetches all logs from newest instead of
continuing from the last log that is displayed.
This is reproducible with selecting some time filter (like 'Current
boot`, scrolling down and clicking `Load earlier entries` which will
log the same entries that we already have (starting from the newest one).
There is even test for this but it was testing this problem (expecting
that "After boot" is gonna be twice, which is incorrect behaviour.

logs: Correctly show older entries

---

pkg/systemd/logs.html
pkg/systemd/logs.js
test/verify/check-journal

Add option to show logs from previous boot which makes it easier to
debug why a system crashed.
Fixes #11662

logs: Show previous boot

---

bots/image-customize
test/verify/check-bots-api

Allow resizing an image from image-customize. This is tricky to do from
the outside, because the image might not yet be downloaded.

bots/image-customize: Add --resize

---

doc/guide/cockpit-dbus.xml

This gets an `event` argument first. (We don't use that anywhere in the
code.)

doc: Fix arguments for cockpit.dbus().proxy() [no-test]

---

pkg/systemd/terminal.jsx

Some shells like tlog-rec-session don't have an `-i` option, which
breaks the Terminal page. Shells should be interactive if their stdio is
a PTY and there are no further options, which is the case for the
terminal.
See https://bugzilla.redhat.com/show_bug.cgi?id=1631905

systemd: Drop -i shell option in Terminal

---

bots/tests-policy

WHen opening the flake data fails, provide a byte array instead of a
string as fallback, so that the subsequent `.decode()` call doesn't fail
on an `AttributeError`.

bots: Fix data type

---

test/verify/check-storage-resize

While the resize happens and isn't complete, Cockpit will briefly show
a warning about mismatching sizes.  We now wait for that warning to be
gone and the regular buttons to reappear.
Without this, the test might hit the "Shrink Volume" button when it
aims for the "Shrink" button.  This happens because it clicks on any
button that _contains_ the string "Shrink" somewhere, instead of
hitting one that has _exactly_ "Shrink" as the text, which is a bug by
itself.

test: Wait for Cockpit to catch up after resize

---

pkg/systemd/host.js
test/verify/check-system-info

Waiting for timedated to become ready in the test is not enough: We need
to wait until Cockpit's host.js initializes the proxy and updates the
properties, which takes a little longer. Thus the dialog was still often
opened too early, before `CanNTP` was initialized.
Now set a `data-timedated-initialized` attribute to the page's time
information once the proxy is ready, and let the test wait for it.

test: Fix race condition in TestSystemInfo.testTimeServers

---

pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

Otherwise the Machines page crashes with
TypeError: Method Promise.prototype.then called on incompatible receiver #<Object>
when running against cockpit-system 185 (in RHEL 8.0). As we don't
enforce this through versioned dependencies, and don't want to, go back
to `cockpit.all()` for `ListNodeDevices()`, as some other parts of the code already do.

machines: Use cockpit.all() instead of Promise.all()

---

bots/images/scripts/rhel-8-0-distropkg.install
test/verify/check-accounts
test/verify/check-active-pages
test/verify/check-connection
test/verify/check-dashboard
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-journal
test/verify/check-kdump
test/verify/check-kubernetes
test/verify/check-machines-dbus
test/verify/check-machines-virsh
test/verify/check-multi-machine
test/verify/check-networking-firewall
test/verify/check-openshift
test/verify/check-ovirt
test/verify/check-pages
test/verify/check-realms
test/verify/check-services
test/verify/check-session
test/verify/check-sosreport
test/verify/check-storage-format
test/verify/check-storage-luks
test/verify/check-storage-resize
test/verify/check-subscriptions
test/verify/check-system-info
test/verify/check-terminal
test/verify/packagelib.py

We will use this to test the rhel-8-appstream branch as well as z-stream
updates.

bots, test: Introduce rhel-8-0-distropkg mode

---

doc/man/cockpit-desktop.xml
src/ws/cockpit-desktop.in
test/verify/check-connection

Add support for short page names like 'users' or 'network/firewall'
directly on the commandline.
Closes #10809

cockpit-desktop: support simple arguments

---

bots/tests-scan

On Cockpit master, run it instead of verify/rhel-8-0. It's the more
relevant target now, as 8.0 is pretty much done and now being maintained
in the rhel-8.0 branch.
Same for the rhel-8-appstream branch -- this definitively needs to work
against the current version in RHEL BaseOS, so move the test there, too.

bots: Enable verify/rhel-8-0-distropkg test [no-test]

---

bots/naughty/rhel-8/10908-packagekit-dumps-core

PackageKit often dumps core on current rhel-8
Fixes #10908

naughty: Close 10908: PackageKit often dumps core on current rhel-8

---

pkg/storaged/content-views.jsx
pkg/storaged/crypto-tab.jsx
pkg/storaged/format-dialog.jsx
pkg/storaged/fsys-tab.jsx
pkg/storaged/pvol-tabs.jsx
pkg/storaged/swap-tab.jsx
pkg/storaged/unrecognized-tab.jsx
test/verify/check-storage-format
test/verify/check-storage-hidden
test/verify/check-storage-iscsi
test/verify/check-storage-luks
test/verify/check-storage-lvm2
test/verify/check-storage-mounting
test/verify/check-storage-msdos
test/verify/check-storage-resize
test/verify/check-storage-used
test/verify/check-storage-vdo

Fixes #10014
Release Notes
---------------
The button to format a block device used to be in the tab that describes the current content of the device, such as in the "Filesytem" or "Physical Volume" tab.  Now it is in the header row where it should be easier to find.

storage: Move "Format" button to row header

---

bots/images/rhel-atomic
bots/images/scripts/atomic.bootstrap

Now (since https://github.com/cockpit-project/cockpituous/commit/0fd4962c78a006dd22b628c84ce8bc95a51cf10e) tasks are run on F30, which does not support `python` binary anymore. To see if it works, lets refresh `rhel-atomic` - based on https://github.com/cockpit-project/cockpit/issues/11731

bots: Use python3 in bootstrap script

---

pkg/users/index.html

accounts: change position of tooltips because they were hiding help text

---

pkg/machines/components/deleteDialog.jsx
test/verify/machineslib.py

Previously we were executing the virDomainDestroy API only against
running VMs. This resulted in paused VMs to keep appearing in the list
after deletion.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1706678

machines: always shut off the VMs before deletion

---

bots/naughty/debian-testing/11032-udisks2-fails-with-thin-snapshots-2
bots/naughty/fedora-29/11032-udisks2-fails-with-thin-snapshots-2
bots/naughty/rhel-7/11032-udisks2-fails-with-thin-snapshots-2
bots/naughty/rhel-8/11032-udisks2-fails-with-thin-snapshots-2
bots/naughty/ubuntu-1804/11032-udisks2-fails-with-thin-snapshots
bots/naughty/ubuntu-1804/11032-udisks2-fails-with-thin-snapshots-2
pkg/storaged/content-views.jsx
pkg/storaged/lvol-tabs.jsx
test/verify/check-storage-lvm2

Cockpit does not really account for the idiosyncrasies of traditional
snapshots, including:
- Deleting the origin will delete all snapshots.
- Activating/deactivating the origin will do the same to all
snapshots, and vice versa.
- The size of a snaphot does not correspond to the size of its block
device, and resizing a snapshot does not resize the block device.
- Writing to the origin might cause the snapshot to run out of space,
but Cockpit doesn't allow to monitor this.
Snapshots of thin volumes are different as they are truly independent
of their origin after creation and function just like any other thin
volume.  To emphasize this, we call the action of creating them
"cloning".

storage: Ignore traditional LVM2 snapshots

---

pkg/machines/components/vm/bootOrderModal.jsx

Previously the label names where wrapped with <output> html element.
output elements is supposed to be containing results of calculations, I
don't see the purpose of wrapping label strings.
This change also fixed the misallignment of the above labels.
Fixes #11751

machines: fix misalligned labels in boot order modal dialog

---

test/avocado/selenium-sosreport.py

`waitforsosreport()` finishes fairly quickly, so 30 attempts only result
in a ~ 1 minute wait. sosreport needs much longer than that, so increase
the timeout.

test: Wait longer for sosreport to finish [no-test]

---

bots/images/continuous-atomic
bots/images/scripts/continuous-atomic.bootstrap
bots/naughty/continuous-atomic/8831-selinux-rhsmd-subscription_manager
test/verify/check-multi-machine

The file name dropped the "-7". Also move to https:// URL.
Fixes #9971
Closes #11765

[no-test] bots: Update CentOS Atomic cloud image download

---

Makefile.am
configure.ac

Valgrind can't deal with the space-saving optimisations in GLib 2.60.
Add a workaround.
Fixes #11766

tests: Workaround valgrind limitations with ghash [no-test]

---

tools/glib.supp

Reported upstream: https://gitlab.gnome.org/GNOME/glib/issues/1774

tools/glib.supp: ignore known GSocketClient leak [no-test]

---

bots/image-create
bots/image-trigger
bots/images/openshift-prerelease
bots/images/scripts/openshift-prerelease.bootstrap
bots/images/scripts/openshift-prerelease.install
bots/images/scripts/openshift-prerelease.setup
bots/images/scripts/openshift.setup
test/verify/check-openshift

It's currently at exactly the same OpenShift version 3.11alpha as the
"openshift" image, so this doesn't test anything different. Also, with
cockpit-kubernetes being phased out, and OpenShift concentrating on 4.0
now, this image has outlived its purpose. Let's remove it to speed up
our tests.

bots: Drop openshift-prerelease image [no-test]

---

test/avocado/run-tests

The windows-10 VM is really slow, and tests often time out. Give it two
hours instead of one.

test: Double timeout for selenium/edge test [no-test]

---

bots/image-download

The output directory for image-download --state doesn't
create the right directory for outputting the images. This
results in failures when doing test data training.

bots: Create download for image-download doesn't create dir

---

bots/image-download

When used with --state the image-download only downloads files
if it is newer than the existing file. However the recent changes
for continuing a partial download unfortunately regressed this
behavior.
This commit should fix it. #11457 removes the use of tempfile
which created a zero length file. This restores that behavior.

bots: Fix image-download --state when file is skipped

---

test/verify/check-networking-firewall

When removing a service, the button is initially disabled, until reading
the zones is complete.

test: Wait for non-disabled button in TestFirewall.testAddServices

---

test/common/test-functions.js
test/common/testlib.py
test/verify/check-active-pages
test/verify/check-kdump
test/verify/check-networking-vlan
test/verify/kubelib.py

`mouse` function had option `force` which made it possible to click on
invisible buttons. However this is a bad practice.
This was in the code mostly because in `check-active-pages` the dropdown
menu was needed to be opened while holding `alt` key down.
This commit teaches the mouse function to also simulate holding down
special keys.
In three other tests `force` was used pointlessly.
I just grepd where `click` with force was used. Possibly I missed some other places - but full test run should show me what I forgot.

tests: Stop allowing to click on invisible buttons

---

package.json

This reverts commit 55f71b8c65143223f3b08a9ecd65edaf4cf88f29.
The reverted commit was introduced in #11797 but later on was noticed
that sometimes xterm can crash. Reported to https://github.com/xtermjs/xterm.js/issues/2082

Revert "package.json: Update xterm package dependency"

---

test/common/testlib.py

This fixes tests randomly failing with
File "test/common/testlib.py", line 779, in tearDown
self.check_journal_messages()
File "test/common/testlib.py", line 956, in check_journal_messages
raise Error(first)
testlib.Error: /base1/fonts/fontawesome.woff: external channel failed: terminated

test: Add another expected restart message

---

pkg/kdump/kdump-view.jsx
pkg/lib/cockpit-components-onoff.css
pkg/lib/cockpit-components-onoff.jsx
pkg/lib/cockpit-components-onoff.less
pkg/networkmanager/firewall.jsx
pkg/networkmanager/interfaces.js
pkg/networkmanager/networking.css
pkg/packagekit/autoupdates.jsx
pkg/playground/react-demo-onoff.jsx
pkg/selinux/setroubleshoot.css
pkg/shell/credentials.js
pkg/storaged/storage-controls.jsx
pkg/systemd/host.js
test/verify/check-kdump
test/verify/check-keys
test/verify/check-networking-bond
test/verify/check-networking-firewall
test/verify/check-packagekit
test/verify/check-setroubleshoot
test/verify/check-storage-vdo
test/verify/check-system-info
test/verify/netlib.py

Update the On/Off switch redesign to how PatternFly 4's Switch looks
like [1]. This makes the button more accessible, easier to click (as the
full button area can be clicked, not just half of it), and drops all
translatable text, thereby avoiding the overflow in translations.
While at it, invert the "enabled" property into the standard "disabled"
one. As the PF4 design differs between switches with and without extra
text, add a new "text" property. This isn't being used anywhere except
the "React Patterns" page right now, but may be in the future.
CSS (the hard part) is all credit to Garrett LeSage.
[1] https://pf4.patternfly.org/components/Switch/
Fixes #9408
Fixes #11225
Fixes #11226
Fixes #11814
https://bugzilla.redhat.com/show_bug.cgi?id=1650942
TODO:

lib: Redesign On/Off switch

---

test/avocado/testlib_avocado/cockpit.py

When avocado starts its own browser it never closes it.
Since avocado tests spawn this process and it does not get cleaned up, the main
process holds stdout/err "busy" and therefore the test hangs
indefinitely.
Possibly related https://bugzilla.mindrot.org/show_bug.cgi?id=2071

[no-test] test: Close browser when avocado finishes

---

pkg/lib/cockpit-components-onoff.less

lib/onoff: Use Chrome blue focus by default; dots for Firefox

---

bots/machine/machine_core/ssh_connection.py

should fix issue within avocado test, in case ``sys.stderr/stdout`` are redirected to logger so that attribute ``fileno`` does not exist

ssh execute, write to stdout and stderr of sys in case it is not redirected

---

bots/machine/machine_core/machine.py
doc/man/cockpit-ws.xml
src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/test-webserver.c
src/ws/cockpitchannelsocket.c
src/ws/cockpitchannelsocket.h
src/ws/cockpithandlers.c
src/ws/cockpitwebservice.c
src/ws/cockpitwebservice.h
src/ws/main.c
src/ws/test-handlers.c
src/ws/test-server.c
src/ws/test-webservice.c
test/verify/check-connection

If cockpit-ws runs behind a reverse proxy that does the TLS termination,
it rejects non-GnuTLS connections with a https:// origin with
received request from bad Origin: https://localhost:9090
This previously required setting `Origins` in cockpit.conf to make this
work. Introduce a new `--for-tls-proxy` option to cockpit-ws which
switches the default Origin checking to https-only. With that, no
cockpit.conf modifications are required for local proxies.
This is implemented by a new `for-tls-proxy` property in
`CockpitWebServer`, which gets plumbed through the Origins check in
`cockpit_web_service_create_socket()`.
This is mostly intended for the upcoming external "cockpit-tls" proxy
which externalizes TLS termination, so that this does not have to modify
cockpit.conf or inspect/modify the …

ws: Add --for-tls-proxy option

---

pkg/networkmanager/firewall.jsx

Change the "Add services to the following zones" label to "ports" to
reflect the user's choice of the "Custom ports" option in the same way
that the dialog title is changed.
Fixes #11834

firewall: make the "Add ... to zone" label dynamic

---

pkg/kubernetes/styles/image-widgets.css

This symlink has been broken since we stopped using Bowie.  With npm,
the packages are now under node_modules/.

kubernetes: fix a broken symlink

---

pkg/networkmanager/firewall.jsx

Previously we were showing zone IDs here, which was inconsistent with
what we show in the Zones list on the main firewall page.  Show the
human-friendly name instead.
Fixes #11836

firewall: show zone names in "Add services" dialog

---

pkg/lib/form-layout.less
pkg/storaged/dialog.jsx
pkg/storaged/format-dialog.jsx
pkg/storaged/storage.css
test/verify/check-storage-hidden
test/verify/check-storage-luks
test/verify/check-storage-mounting
test/verify/check-storage-msdos
test/verify/check-storage-resize

This way, people can easily make encrypted block devices without
filesystems in them.
This also opens the avenue to adding more encryption technologies,
like "LUKSv2".
Fixes #11482
Release notes:
-------------
Previously, Cockpit has offered encryption for only two types of filesystems, xfs and ext4.  Now you can select the filesystem type and the encrpytion technology separately.

storage: Factor encryption out of filesystem type when formatting

---

bots/tests-scan

This is being prepared in https://github.com/weldr/lorax/pull/689. Once
a test on a particular OS works, it can be moved over to `'master'`.

bots: Enable manual tests for weldr/lorax [no-test]

---

bots/push-rewrite
bots/task/__init__.py
bots/tests-scan

The labels_of_pull() function was returning a map, but in some cases the
return value was being evaluated more than once.  The first evaluation
would be fine, but all evaluations after the first would just see an
empty list (since the values had already been consumed).
Let's just return a list here to avoid the problem.
We can also take the chance to simplify code in a few other places since
we now have a list.

bots: fix 'no-test' label [no-test]

---

pkg/machines/actions/store-actions.js
pkg/machines/libvirt-dbus.js
pkg/machines/reducers.js
test/verify/check-machines-dbus

This test was failing from time to time because virsh was returning 'no' for
the active property even though we already received a signal that the
Network got active from the DBus API.
I haven't figured out why virsh might return wrong data the first time,
and I can't reproduce locally either. So, let's give it some time to react to
the event by waiting for the answer to be correct.

tests: robustify testNetworkState for cockpit-machines

---

bots/machine/machine_core/machine_virtual.py

With parallel tests, this would sometimes crash with
FileExistsError: [Errno 17] File exists: '/tmp/.cockpit-test-resources'

bots: Fix TOCTOU race in machine network setup

---

test/verify/machineslib.py

When creating the new VM to test the deletion of paused VMs, I forgot to
get the new args variable, and I kept checking the args from the
previous VM run, which made the test fail inconsistently.

tests: fix testDelete from machineslib which was checking wrong console file

---

bots/tests-scan

https://github.com/weldr/lorax/pull/689 landed now.

bots: Enable automatic weldr/lorax tests on fedora-30

---

bots/tests-invoke

Current weldr/lorax tests take slightly over 90 minutes. They will be
sped up soon, but let's not block on that.

bots: Bump external test timeout to 2 hours

---

pkg/machines/components/diskRemove.jsx
test/verify/check-machines-dbus

Live detaching disks needs the cooperation of the operating system of
the guest to succeed. When trying to live detach disks from paused VMs
the DetachDevice API will timeout and an error will appear in the
cockpit-machines notification list right after.
Let's disable the detach button for VMs that are neither stopped nor
running since the detach operation on these is not likely to succeed.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1708515

machines: Allow detaching disks only of either running or shut off VMs

---

src/common/cockpitpipe.c

When asynchronously connecting and evaluating the
result (via getsockopt) make sure to try again
if the initial read doesn't work. By returning FALSE
here the caller will not process this as an
actual readable socket.
This is split out from #11872
I could not find a way to test this since on AF_UNIX or local connections it seems that connect() is hard to make fail during an async connection.

common: Return correct value in async connection

---

configure.ac
pkg/systemd/hwinfo.jsx
pkg/systemd/kernelopt.sh
src/bridge/bridge.c
src/bridge/cockpitpcp.c
src/bridge/mock-bridge.c
src/bridge/stub.c
src/bridge/test-httpstream.c
src/bridge/test-packages.c
src/bridge/test-setup.c
src/common/cockpittest.c
src/ssh/ssh.c
src/websocket/test-websocket.c
src/ws/main.c
src/ws/remotectl.c
src/ws/test-channelresponse.c
src/ws/test-server.c
test/avocado/run-tests
test/avocado/selenium-base.py
test/avocado/testlib_avocado/cockpit.py
test/common/testlib.py
test/verify/check-login
test/verify/check-multi-machine
test/verify/check-networking-bridge
test/verify/check-packagekit
test/verify/check-subscriptions
test/verify/check-system-info
test/verify/netlib.py

Cherry-picked from master commits 16c7c8e8f, 2e82a200, and de2dc4f6.
https://bugzilla.redhat.com/show_bug.cgi?id=1678956
(FIXME: use bug clone for 8.0.1)

system: Add CPU security mitigations dialog

---

src/common/test-webserver.c

An actual host resolving happens in
`gio/gthreadedresolver.c:do_lookup_by_name` by calling the `getaddrinfo`
function with ai_flags=AI_ADDRCONFIG.
According to getaddrinfo(3):
```
If hints.ai_flags includes the AI_ADDRCONFIG flag, then IPv4
addresses are returned in the list pointed to by res only if the
local system has at least one IPv4 address configured, and IPv6
addresses are returned only if the local system has at least one IPv6
address configured.  The loopback address is not considered for this
case as valid as a configured address.
```
Our build tool (https://en.altlinux.org/Hasher) has only loopback interfaces.
Thus, `localhost` resolving results in
EAI_NONAME /* NAME or SERVICE is unknown. */
A simple workaround is to use the IPv4 address instead.
Fixes: …

tests: Don't resolve ``localhost`` for mocked systems

---

containers/unit-tests/run.sh

Add an option to skip running the tests.  This is useful in combination
with 'make unit-tests-container-shell' to prepare and build the tree, in
preparation for manual testing.

containers: add --build option to run.sh

---

bots/naughty/fedora-30/11902-podman-no-env-parameter

This reverts commit ef456ad8067cf68f1a00954508e58deb96831d92.
This was fixed in https://github.com/cockpit-project/cockpit-podman/pull/105
Closes #11902

[no-test] Revert "bots: Add naughty for podman missing parameter"

---

configure.ac
doc/protocol.md
src/bridge/Makefile.am
src/bridge/bridge.c
src/bridge/cockpitpacketchannel.c
src/bridge/cockpitpacketchannel.h
src/bridge/test-packet-channel.c
src/common/cockpitpipe.c

This is for SeqPacket Unix sockets and SCTP connections.
It relays messages with the same framing as sent over
the connections. There is a maximum size above which the
messages are truncated.

bridge: Implement 'packet' payload

---

test/verify/check-storage-mdraid
test/verify/storagelib.py

Adding a disk might fail temporarily but pressing "Apply" a couple of
times should eventually succeed.
Additionally, the code for retrying the "Stop" action didn't work
anymore with the new dialog code and sometimes no error dialog will
open at all.

test: Retry more in check-storage-mdraid

---

test/avocado/selenium-hwinfo.py
test/avocado/selenium-kdump.py

This commit fixes following warnings: (introduced in #11837)
test/avocado/selenium-kdump.py:4: 'time' imported but unused
test/avocado/selenium-hwinfo.py:9:1: E402 module level import not at top of file
test/avocado/selenium-kdump.py:9:1: E402 module level import not at top of file
test/avocado/selenium-kdump.py:10:1: E402 module level import not at top of file
test/avocado/selenium-kdump.py:24:5: E303 too many blank lines (2)

test: Fix pyflakes warnings

---

pkg/storaged/org.cockpit-project.cockpit-storaged.metainfo.xml

The page and manifest is called "storage" is far as Cockpit is
concerned, "storaged" is just the package and directory name.

storage: Fix name of manifest in AppStream data

---

src/ssh/mock-sshd.c
tools/libssh.supp

Here's a branch from Sanne to fix the libssh failures.
Upstream bug: https://bugs.libssh.org/T151
Closes #11910

ssh: Set key exchange algorithms in mock-sshd

---

test/avocado/run-tests

With the default 1 GiB RAM/1 CPU, the selenium/edge test is just too
slow.

test: Give more resources to windows-10 VM

---

bots/image-refresh
bots/task/__init__.py

As the rename and force push are not synchronous, if run_tests=False,
never remove the [no-test] from the title, thus eliminating the race entirely.
---
Refresh leaves [no-test] in title:
https://github.com/Gundersanne/cockpit/pull/27
Other tasks remove the [no-test] after:
https://github.com/Gundersanne/cockpit/pull/30

Fix no test race [no-test]

---

test/verify/check-subscriptions

The condition was backwards, but it passed anyway since there is a
short time after expanding the list where the contents isn't in there
yet.

test/check-subscriptions: Fix check for "Not Subscribed"

---

src/ws/cockpitauth.c
src/ws/cockpitws.h
src/ws/test-auth.c

This allows us to lower the timeout in out-of-process tests.
---
I need this for writing cockpit-tls unit tests. I have that commit in my branch, and it works fine there.

ws: Introduce env var for changing process timeout

---

tools/cockpituous-release

Fedora 30 has been stable long enough now.

cockpituous-release: Drop Fedora 29

---

tools/cockpit.spec
tools/debian/control
tools/debian/rules

We moved to doing upstream point releases for stable branches a while
ago, and since then haven't used this complicated and brittle patch
application mechanism.
For patching bugs in the C code, distros can use their standard patch
mechanisms, and we won't go back to the mess of patching webpack and
autotools files.

tools: Drop custom patch application

---

bots/naughty/fedora-30/11660-module-request

Known issue which has not occurred in 23 days
SELinux is preventing pmdalinux from module_request access on the system labeled kernel_t
Fixes #11660

naughty: Close 11660: SELinux is preventing pmdalinux from module_request access on the system labeled kernel_t

---

bots/naughty/rhel-8/11566-kvdo-missing

kvdo broken on current rhel-8-1: kernel version mismatch
Fixes #11566

naughty: Close 11566: kvdo broken on current rhel-8-1: kernel version mismatch

---

test/verify/check-machines-dbus

There is currently a race condition making this test fail often. It
looks like that destroying and undefining the network right after emits
almost concurrent events, and the UI state is not updated correctly.
Although this deserves an actual fix let's robustify this tests by
waiting for the networks to get deactivated before detaching.
Some cleanup in the singal handlers will come as a followup.

Robustify testNetworkSettings by waiting for the networks to get inactive before undefining

---

bots/tests-scan

This is for testing and demonstration.  The ultimate goal is to
replace this with candlepin/subscription-manager.

bots: Add mvollmer/subscription-manager to tests-scan

---

bots/tests-scan

```
File "bots/tests-scan", line 511, in <module>
sys.exit(main())
File "bots/tests-scan", line 169, in main
results = scan_for_pull_tasks(api, policy, opts, opts.repo)
File "bots/tests-scan", line 490, in scan_for_pull_tasks
results = cockpit_tasks(api, not opts.dry, policy, repo, opts.pull_data, opts.pull_number, opts.sha, opts.amqp)
File "bots/tests-scan", line 469, in cockpit_tasks
for context in REPO_BRANCH_CONTEXT[proj_repo]["master"]:
KeyError: 'master'
```

bots: Fix tests-scan crash if a project doesn't have master tests

---

pkg/apps/utils.jsx
pkg/machines/components/vnc.jsx
pkg/playground/speed.js
pkg/sosreport/index.js
test/common/testlib.py
test/containers/check-kubernetes-openshift
test/verify/check-apps
test/verify/check-sosreport
test/verify/machineslib.py

When a UrlRoot was in use, almost all URLs for external channels would
forget to include it.
The effect was that diagnostic reports can't be downloaded,
applications don't have icons, and virtual machine consoles don't
work.

all: Make external channels work with a UrlRoot

---

tools/cockpit.spec

It previously was a dependency of git, which got dropped in commit 84ba3c821041.

tools: Add missing ssh-agent build dependency

---

bots/image-create
bots/image-customize
bots/image-download
bots/image-prepare
bots/image-prune
bots/image-upload
bots/images/scripts/atomic.bootstrap
bots/learn-tests
bots/machine/machine_core/constants.py
bots/machine/machine_core/directories.py
bots/machine/machine_core/machine_virtual.py
bots/machine/testvm.py
bots/task/cache.py
bots/task/github.py
bots/tests-data
bots/tests-invoke
bots/tests-policy
pkg/storaged/nfs-mounts.py
test/README.md
test/avocado/run-tests
test/common/testlib.py
test/vm-run

Consider this pull request as a request for comments.
I hate setting `TEST_DATA`, so I added a new git-config variable, `cockpit.bots.images-data-dir` to determine the directory to store the images.  I think this is even better than `TEST_DATA` because (in addition to not being an unnamespaced global environment variable), it only stores the image files, allowing some of the other tree-specific stuff to be kept in its default locations.
It turns out that the code to figure out the various ways in which we use `TEST_DATA` was copied around quite a lot.  This cleans up nearly everything except for a single use in `task/github.py` which I'm not really sure what to do about...

Add another option for determining where to store images

---

bots/tests-scan

so they are executed faster and appear as separate statuses on
GitHub.

Specify test scenarios for lorax

---

bots/README.md

bots/github-trigger doesn't exist

Fix typo in README

---

bots/naughty/rhel-7/11477-selinux-ipa-submit-getattr

joining IPA domain causes SELinux violation: avc: denied { getattr } for comm="ipa-submit"
Fixes #11477

naughty: Close 11477: joining IPA domain causes SELinux violation: avc: denied { getattr } for comm="ipa-submit"

---

Makefile.am

Revert commit 1379a9ee9d3. It's still useful to have the integration
tests in the release, as they always match the shipped code and thus
it's not (or less) necessary to maintain stable branches just for
running the tests downstream.

build: Ship integration tests in release tarballs again

---

src/ws/session.c
test/verify/check-login

session: Circumvent user shell stdout noise
Commit a9375441df7 caused Cockpit logins to fail if the user's ~/.bashrc
or ~/.profile writes anything to stdout. That interferes with the
protocol and causes an error like
incorrect protocol: received invalid length prefix
To avoid this, route the shell's stdout to stderr (so that we can still
see it in the logs) and pass session's stdout to cockpit-bridge through
fd 3. This assumes that the shell supports `>&3` input redirection,
which is the case for any POSIX shell (ash, bash, ksh, dash, zsh) and at
least tcsh.
https://bugzilla.redhat.com/show_bug.cgi?id=1710604

session: Circumvent user shell stdout noise

---

pkg/storaged/nfs-mounts.py
test/avocado/run-tests
test/avocado/selenium-kdump.py
test/avocado/testlib_avocado/seleniumlib.py

Revert this part of commit a61672abcbe so that it continues to work on
RHEL 7, i. e. with Python 2.

storage: Fix makedirs() invocation for Python 2

---

bots/tests-scan

These don't release to Fedora 29 any more, and we want to remove the
image at some point.
This includes containers/kubernetes, as cockpit-kubernetes was only
built for Fedora ≤ 29.

bots:  Drop most fedora-29 tests

---

Makefile.am
src/base1/Makefile.am
src/base1/patternfly-overrides.less
tools/patternfly.sed

Don't use the precompiled *.css files, but build them ourselves. This
will allow us to modify PF variables for tweaking the design globally in
the new file src/base1/patternfly-overrides.less.  See issue #11913 for
details.
Keep the post-lessc seddery of font paths. While there are some PF
variables for them, like `@font-path`, we don't ship all fonts in the
same directory (or even package), so this can't be expressed with just
variables.

base1: Build PatternFly from less files, add overrides

---

bots/image-refresh
bots/task/__init__.py
bots/task/test-task

Depending on the tests-external label inside of the image-refresh task
would depend on a race: it would expect that the task finishes and
removes no-test from the title before the webhook has called all of its
tests-scans on the direct triggers. And as the status events do not
include the pull data, this would be a race.
To avoid this race, poll for the updated head after force-pushing,
trigger all the external tests manually, and then poll that all those
statuses are present before letting the task finish and removing the
no-test from the title.
---

bots: Mitigate fundamental race condition in image-refresh

---

bots/tests-invoke

It very often is the number of tests that have failed, but not always.

bots: Don't make assumption about the exit code of the test runner

---

pkg/networkmanager/index.html
pkg/networkmanager/interfaces.js

The man pages of nmcli use the terminology 'master interface' and 'slave
interfaces', so using 'interfaces' instead of 'members' should not be
misleading for people familiar with the CLI options.
Fixes #12017

networking: replace 'Members' with 'Interfaces' when refering to slave ifaces in bonding dialog

---

bots/image-refresh

This was dropped in commit 499c0cb7e.

bots: Drop verify/fedora-29 test from image-refresh

---

src/ssh/cockpitsshknownhosts.c

This function could fail if glib doesn't support HMAC or SHA1, e. g.
because it is in FIPS mode.
This only affects building against libssh 0.7, i. e. RHEL/CentOS 7 and
Debian 9. In newer operating systems with libssh 0.8, this entire file
is not built.
Fixes #12016
https://gitlab.gnome.org/GNOME/glib/merge_requests/897

ssh: Gracefully handle failing g_hmac_new()

---

pkg/machines/libvirt-common.js

Let's take into consideration that format element in storage volume's xml may be optional.
Closes: #11983

machines: Fix volume's xml parsing of format element

---

bots/naughty/fedora-30/11724-selinux-denies-iscsid-from-map
bots/naughty/rhel-8/11724-selinux-denies-iscsid-from-map

Known issue which has not occurred in 22 days
SELinux is preventing iscsid from 'map' accesses
Fixes #11724

naughty: Close 11724: SELinux is preventing iscsid from 'map' accesses

---

bots/tests-trigger

This re-triggers pending (but not yet running) test requests so that
they get put into the test AMQP queue again. This can be used to work
around the current bug of sometimes missing the webhook events or not
processing them fast enough. This can be reverted once the webhook works
reliably.

bots: Add tests-trigger --requeue option

---

bots/naughty/rhel-8/12057-selinux-dhclient-tmpfs

Related to PR #12056
Known issue #12057
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1720070

bots: Add naughty for SELinux dhclient regression on RHEL 8.1

---

pkg/machines/components/dropdownButtons.jsx
pkg/machines/components/vm/vmActions.jsx

Previously install, shutoff, force shutoff, restart, force restart
buttons had btn-danger class.
These operation should not be marked a dangerous, there are normal
operations.

machines: remove btn-danger class from all lifecycle operation buttons

---

pkg/machines/components/storagePools/createStoragePoolDialog.jsx

There is not lvm2 partition table type. (See man parted)
This list was copied from https://libvirt.org/storage.html which has
lvm2 listed incorrectly as partition table type.

machines: remove lvm2 from supported disk pool format types

---

src/ssh/test-sshbridge.c

The code already asserts `fixture != NULL` and accesses fixture further
above. Quiesces coverity's REVERSE_NULL error.

ssh: Drop always-true check in test-sshbridge

---

containers/unit-tests/Dockerfile

Follow-up for commit b3c8a69dc986.

containers: Add GnuTLS devel build dependency to unit-tests

---

bots/image-refresh

OpenShift tests don't run on fedora-30 any more, as cockpit-kubernetes
is not packaged there. Run rhel-7-7 instead.

bots: Fix triggered tests for openshift image refreshes

---

src/common/cockpitconf.c
src/common/cockpitconf.h
src/common/cockpitmemory.c
src/common/cockpitmemory.h
src/common/test-config.c
src/ws/cockpitauth.c
src/ws/mock-config/cockpit/cockpit.conf

This makes it possible to share with the upcoming cockpit-tls, which
must not use GLib/GObject.
Rename cockpit_conf_guint() to cockpit_conf_uint() to reflect the data
type changes.
For simplicity this uses a single linked list for storing the data
instead of a hashtable of hashtable. These are being called so rarely,
and cockpit.conf files are so small that it's not worth all this
overhead.
Also, stop supporting parsing the same key strv with different
delimiters. This is unrealistic to happen in practice (and doesn't), and
it would significantly complicate the caching.

common: Drop glib usage from cockpitconf

---

pkg/machines/components/vm/vm.jsx

Not keeping it mounted will allow for the IPs to be re-fetched each time
that a user switches away and back to that tab.

Don't keep the Network Tab component mounted if it's not active

---

src/ws/cockpitauth.c
src/ws/cockpitauth.h
src/ws/main.c
src/ws/test-auth.c
src/ws/test-authssh.c
src/ws/test-handlers.c
src/ws/test-kerberos.c
test/verify/check-connection

We expect the login cookie to be marked as "Secure" if ws is running
behind a TLS proxy. So introduce flags to CockpitAuth as well, similar
to commit 5c865ad8 and commit 34a8913.

ws: Fix "Secure" cookie flag with --for-tls-proxy

---

test/verify/check-connection

Ensure that cockpit redirects http requests on non-localhost IP to https
by default, and that the `AllowUnencrypted` config option disables this.

test: Check http → https redirection

---

pkg/networkmanager/firewall.jsx

Similar condition exists for the modal dialog title.

firewall: make the "Failed to add service" error message dynamic

---

src/bridge/cockpitinternalmetrics.c
src/bridge/cockpitpacketchannel.c
src/bridge/cockpitsamples.c
src/bridge/cockpitsamples.h
src/bridge/cockpitstream.c
src/common/cockpitchannel.c
src/common/cockpitchannel.h
src/common/cockpitflow.c
src/common/cockpitflow.h
src/common/cockpitloopback.c
src/common/cockpitloopback.h
src/common/cockpitpipe.c
src/common/cockpitpipe.h
src/common/cockpitpipetransport.c
src/common/cockpitpipetransport.h
src/common/cockpittransport.c
src/common/cockpittransport.h
src/common/cockpitwebfilter.c
src/common/cockpitwebfilter.h
src/common/cockpitwebinject.c
src/common/cockpitwebinject.h
src/common/cockpitwebresponse.c
src/common/cockpitwebresponse.h
src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/mock-pressure.c
src/websocket/websocketconnection.c
src/ws/main.c

Update our classes to make use of the G_DECLARE_DERIVABLE_TYPE() and
G_DECLARE_FINAL_TYPE() macros.
In addition to being a net reduction in code size, we gain support for
some nice additional features, such as g_autoptr().
Closes #12092

common: use the GObject type declaration macros

---

bots/naughty/fedora-30/11614-selinux-denying-iscsi_tcp-module-load
bots/naughty/rhel-8/11614-selinux-denying-iscsi_tcp-module-load

SELinux denies iscsid { read } for modules.dep.bin and modules.softdep
Fixes #11614

naughty: Close 11614: SELinux denies iscsid { read } for modules.dep.bin and modules.softdep

---

bots/naughty/fedora-30/12098-podman-image-deletion-listing-crash

Reported issue on libpod repository https://github.com/containers/libpod/issues/3316

bots: add naughty for podman crash on fedora-30

---

pkg/machines/components/storagePools/storagePool.jsx
test/verify/check-machines-dbus

Sometimes it takes some time to activate a pool; don't allow the user to
re-click the activate button in case the previous operation is still in
progress.
Same for deactivate button.

machines: disable activate/deactivate buttons for pools when operation is in progress

---

bots/image-refresh
bots/tests-scan

Because we finally can! (High time..)

bots: Test cockpit-podman on RHEL 8.1

---

bots/image-refresh
bots/tests-scan

7.7 was the last RHEL release where we did a full rebase, from now on it
will just be bug fixes. These releases are now being maintained from the
rhel-7.* branches.
So drop the centos-7, rhel-7-6-distropkg, rhel-7-7, and rhel-atomic
branches from cockpit master PRs.

bots: Stop testing Cockpit master on RHEL/CentOS 7

---

bots/learn-tests

The directory is called "machine" not "machines".
I noticed this while looking into bots logs.

bots: Use correct import

---

test/common/testlib.py

When calling this method with `tls=true`, it only configured cockpit-ws
for TLS, but still opened the requested page with http://. This only
ended up as https:// due to cockpit-ws' automatic TLS redirection. But
that is tested separately, and not in these parts of check-connection
TestConnection.testTls that cover TLS cookie handling.
Add a tls parameter to Browser.login_and_go() and Browser.open() as
well, and pass it through appropriately, so that these use https://
right away.

test: Fix Machine.login_and_go() TLS mode

---

bots/image-prune

It may happen that after open PRs are scanned it references commits that
are not locally available and therefore `git ls-tree` fails.
This commit gives it two chances, if first fails with tree error, it
tries to fetch the commit and then tries again.
I hope that "origin" is right and thats how whatever runs prune has upstream set up.

bots: Fetch tree in prune if refs is not found

---

bots/task/sink.py

We are going to deploy the sink as a kubernetes service. Until we fix
that to have a known and static host key, disable host key checking.
This is a bit ugly, but with our existing sinks being both broken,
finding a replacement is urgent.

bots: Temporarily disable host key checking for the sink

---

bots/task/sink.py

This was a thinko -- this can be handled in the ssh config in the secrets.
Reverts cockpit-project/cockpit#12124

Revert "bots: Temporarily disable host key checking for the sink"

---

pkg/machines/components/storagePools/createStoragePoolDialog.jsx

Libvirt support for these types is genuinely broken and marked as not fix.
See https://bugzilla.redhat.com/show_bug.cgi?id=980349
They are indeed not common so I just drop the from the UI, I don't think
it worths to ask support for these from libvirt.

machines: drop bsd, pc98 and sun format types for disk type pools

---

package.json

7.14.0 has a grave bug which breaks our build:
https://github.com/yannickcr/eslint-plugin-react/issues/2319
Until the fix is released, pin down to the previous version.

package.json: Pin down eslint-plugin-react to avoid 7.14.0

---

src/bridge/cockpitdbusmachines.c
test/verify/check-dashboard

This was introduced in Cockpit 132 (commit eae85c6b), and thus way
before any version that we currently support.

bridge: Drop obsolete machines.json migration from /var

---

bots/run-queue

bots/run-queue:114: local variable 'declare_webhook_result' is assigned to but never used

bots: Fix pyflakes error in run-queue

---

bots/tests-invoke

The windows-10 VM is really slow, and tests often time out. Give it two
hours instead of one. This was already intended in commit 26bbe032f28,
but the tests-invoke wrapper cut that off after an hour anyway.

bots: Double timeout for selenium/edge test

---

bots/tap.py
bots/test-bots

tap.py lives in cockpit's tests, and the symlink from bots/ is ugly as
we want bots/ to be standalone. It's only being used by test-bots, where
we really don't care about TAP output. Use the plain unittest runner
instead.

bots: Eliminate tap.py symlink

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

Won't allow user to input 0 as memory value and use round calculated
memory available downwards.
There are 2 reason why round memory available downwards:
- Spinner in input field rounds maxValue downwards, so this will
bring consistenci into value inputted by spinner vs value inputted
by text input field.
- If we use round, value might be rounded upwards, thus value exceeding
actual memory available might be shown.

machines: Alter memory available helpblock

---

bots/tests-scan

All of them have been backported and now PASS, see:
https://github.com/weldr/lorax/pull/765

Automatically start tests for lorax on RHEL 7

---

pkg/machines/components/diskAdd.jsx
pkg/machines/libvirt-virsh.js
pkg/machines/xmlCreator.js
test/verify/machineslib.py

The testAddDisk was refactored to be modular and two tests where added for testing adding disks on nfs and iscsi.
Ideally all pools types should be tested but since we are adding the disks with pool-volume in the XML attributes,  there is not difference on  how we handle different pool types.

machines: stop filtering out non 'dir' type pools from add disk dialog

---

test/verify/check-realms

When joining a domain while sssd is running, it often takes ages until
the remote NSS information gets picked up. This causes check-realms
tests to take very long and often time out.
Massively speed this up by resetting sssd during the waiting loop. This
is a bit ugly, but unrelated to what we do in Cockpit as that's all just
manual setup code in the tests.

test: Avoid long sssd timeouts in realm join

---

pkg/docker/manifest.json.in
test/avocado/selenium-docker.py
test/verify/check-docker

To disambiguate it from "Podman Containers" from cockpit-podman, and
also to point out that this does not handle LXC, nspawn, or other
container technologies.

docker: Change menu label to "Docker Containers"

---

doc/man/cockpit-ws.xml
src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/test-webserver.c
src/ws/main.c
test/verify/check-connection

See individual commits for details. This is groundwork for PR #12068.
cockpit-ws now supports redirecting unencrypted http to https (TLS) even when running in `--no-tls` mode. Use this when running <command>cockpit-ws</command> behind a reverse http proxy that also supports https, but does no redirection from http to https by itself. This is enabled with the new `--proxy-tls-redirect` option.

Add support for http → https redirection in proxy mode

---

pkg/machines/libvirt-dbus.js
pkg/machines/libvirt-virsh.js
test/verify/machineslib.py

There are places in cockpit-machines codebase which asume that
storagePool.volumes is always an array.
Such example was the code showing the VM Disks tab.
Inactive pools don't have volume information however, which resulted in
the relevant code to crash when the involved pool was inactive.
Make sure to have an empty array as value to 'volumes' key to avoid such
issues.

machines: fix inspecting VM Disks tab when the disk resides on an inactive pool

---

bots/naughty/fedora-29/8871-selinux-rpcbind
bots/naughty/rhel-8/8871-selinux-rpcbind

Known issue which has not occurred in 24 days
Fedora 28: SELinux denies port binding to rpcbind.service
Fixes #8871

naughty: Close 8871: Fedora 28: SELinux denies port binding to rpcbind.service

---

tools/git-version-gen
tools/test-static-code

git worktrees have a .git file instead of a directory. Relax the file
type tests in our tools to get along with these.

tools: Fix for git worktree

---

test/avocado/selenium-kdump.py
test/avocado/testlib_avocado/seleniumlib.py

Fix the typo in `_driver_excecute()` and make the method public as we
now use it outside of seleniumlib.py. Rename it to `execute_script()` to
mirror the Selenium webdriver method, to clarify what it does.

test: Add public method for executing JS through Selenium

---

HACKING.md
Makefile.am
doc/guide/Makefile-guide.am

This makes the build tree's dist/static/ directory look like the
installed /usr/share/cockpit/static/. This allows a developer to
bind-mount the former onto the latter, to test changes to the login page
or other web server resources without having to modify their system.
Explain in HACKING.md how to do that.

build: Build fonts into dist/static/fonts

---

po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/fr.po
po/it.po
po/ja.po
po/ko.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

A lot of translatable strings got dropped with the kubernetes and ovirt
removals. Clean these up so that translators who only look at the .po
files don't do unnecessary work.

po: Refresh all files

---

bots/run-queue

Assign the repo first, then check if it's been overwritten.

bots: Assign repo first in run-queue

---

pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

Right now user can configure only one settings which takes effect after
shutting down a VM (e.g. vcpus, bootorder, network interface) at a time.
Every change gets lost if user changes another configuration.
**Example**: Have a running VM, change vcpus settings, then change
boot order setting, vcpus new configuration gets lost.
This is caused because we use non-updated active XML to change configuration
and update VM.
So instead we should use inactive XML for these changes.

machines: Fix configuration of multiple settings on running VM

---

pkg/machines/libvirtUtils.js
test/verify/check-machines-dbus
test/verify/machineslib.py

Currently we can provide virt-install only with file-type disks's
path. Implement path getter also for: block, dir, network disk type.
https://bugzilla.redhat.com/show_bug.cgi?id=1719535
https://bugzilla.redhat.com/show_bug.cgi?id=1719550

machines: Implement VM installation of additional disk types

---

pkg/kdump/kdump.css
pkg/lib/page.css
pkg/lib/patterns.js
pkg/playground/jquery-patterns.html
pkg/shell/shell.less
src/base1/cockpit.css

All our On/Off switches got dropped in commit a2b0d7d386. Drop the
.onoff() pattern function and CSS for good now.

lib: Drop btn-onoff-ct leftovers

---

bots/run-queue

Tasks that fail should still be acked. Only when an exception is thrown
the message should not be acked, as that indiciates an error somewhere
in the task.

bots: Ack AMQP message on failed tasks in run-queue

---

bots/image-prune

The `targets` set is supposed to contain file names without path. That's
what our bots/images/<name> symlinks point to and what get_image_links()
returns.
However, the targets from the current checkout were added as full paths.
When running with `--checkout-only` this would then cause  all current
images to be removed, as the plain file name was never found after
commit d12fe778a1c9cf (that commit was correct for the other cases,
though).

bots: Fix image-prune --checkout-only

---

bots/issue-scan

When calling issue-scan with `--issue-data` for PRs, they only get the
`..["pull_request"]` portion and thus testing if that has a
`pull_request` key fails.
As a quick fix, check if the data has a "commits" key, which matches
that case and lets issue-scan accept both formats.
This should eventually be cleaned up by passing the full info to
issue-scan.

bots: Fix image rebuilds in pull requests

---

bots/run-queue

Tested this locally with an amqp instance. 
Used as input:
- issues event 'edited' with FAIL in body
- issues event 'edited' with FAIL removal
- issues event 'edited' with only title changes
- PR event 'edited' with FAIL in body
- PR event 'edited' with FAIL removal
- PR event 'edited' with only title changes

bots: Only issue-scan edited issues if the body was changed

---

tools/cockpit.spec

The guard for that was unintendedly dropped in commit 70158d0f20.

tools: Re-drop subscription-manager-cockpit dependency on Fedora

---

bots/run-queue

This should be the cause of the image refreshes failing to trigger.

bots: Correct extra whitespace in action check in run-queue

---

bots/naughty/debian-testing/12250-apparmor-libvirt-rawio

Known issue #12250
Downstream bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931470

bots: Add naughty for libvirt CAP_SYS_RAWIO denial on Debian

---

bots/naughty/ubuntu-1804/12250-apparmor-libvirt-rawio
bots/naughty/ubuntu-stable/12250-apparmor-libvirt-rawio

Known issue #12250 affects the Ubuntu images as well.

bots: Add naughty for libvirt CAP_SYS_RAWIO denial to Ubuntu images

---

HACKING.md

Drop the obsolete Python 2 bits, and trim unnecessary packages.
libvirt-daemon-kvm is enough for Cockpit testing, we don't need the full
glory of all libvirt plugins.
Split out virt-install and guestfs into a new paragraph for creating
images. Most developers don't need this.

HACKING: Update test and image build dependencies

---

tools/patternfly.sed

A little bit of CSS is injected into the font files, as to prevent displaying the text until the font has loaded.
Ordinarily, this can be considered a not-so-great practice for document websites, but for apps, it is (arguably) less jarring than showing the text with the improper font and then re-rendering the text with a new font. This is especially the case for icons.
End result? Delaying the text rendering until the appropriate font is available makes the UI feel a bit less jump and a bit more more polished.
This affects initial loads. After the first load, the font should be cached.
More information available @ https://css-tricks.com/almanac/properties/f/font-display/

tools: Prevent flash of text while loading fonts

---

pkg/lib/cockpit-components-modifications.css
pkg/lib/cockpit-components-modifications.jsx
pkg/selinux/selinux-client.js
pkg/selinux/setroubleshoot-view.jsx
test/verify/check-setroubleshoot

Mostly Fixes #8657
There is no ansible script, this is gonna be follow up for sure.
This PR for now only shows booleans in normal readable form, others are just dumped from `semange export`. Each type needs to have its own parsing function and then just add this function into the map of functions. Some of these types could be introduced in this PR, but I also expect most of them as follow up.
@andreasn could you take a look and let me know if design is right or you would change something?
Thank you!

selinux: Show local modifications

---

containers/Makefile.am
containers/unit-tests/Dockerfile
containers/unit-tests/README.md
containers/unit-tests/build
containers/unit-tests/exec
containers/unit-tests/run.sh
containers/unit-tests/setup.sh
containers/unit-tests/start

This tests on a less ancient toolchain, more recent libssh, and gives us
a more recent pyflakes which is able to spot a lot more errors.
The main repo -dbg packages are mostly gone now, so enable the dbgsym
repository (as per https://wiki.ubuntu.com/DebuggingProgramCrash) and
install the corresponding -dbgsym packages instead.
Stop installing and using the "g" npm module, the distro's nodejs is now
recent enough.
Use eatmydata to install the bulk of packages for faster container
creation.

containers: Bump unit-tests to Ubuntu 19.04 [no-test]

---

containers/unit-tests/exec

`docker exec` ignores /entrypoint, but we want to make sure our shell
ends up running as the right architecture, so explicitly add it to all
of our commandlines.

containers: Use /entrypoint for unit-tests/exec

---

pkg/networkmanager/firewall.jsx

The default zone text is included inside the icon, which makes it use the FontAwesome icon font, which doesn't have coverage for letters, which means it falls back to a default font (sometimes even a serif font). Therefore, text should be outside of elements with an icon class.

firewall: Move "default" zone text outside of icon

---

src/bridge/test-httpstream.c

glib-networking 2.61.1 breaks `G_TLS_AUTHENTICATION_REQUESTED`, see
<https://gitlab.gnome.org/GNOME/glib-networking/issues/92>.
It is basically impossible to check the glib-networking version in an
upstream compatible way. Also, client certificates are off by default,
so it is fair to run tests that don't provide a client certificate
against a web server that doesn't request one.

test: Only request client certificate when needed in test-httpstream

---

tools/build-debian-copyright

As per https://flaviocopes.com/package-json/#author it's possible to
list the author either as a dict (with 'name', 'email', etc. fields) or
as a string.  We only supported the dict format, but now one of our
packages is using the string format, so support that one too.

tools: support string "author" fields in package.json files

---

Makefile.am
src/common/cockpittest.c
src/common/cockpittest.h
src/ssh/test-sshbridge.c

Add a mechanism for skipping slow tests when requested by an environment
variable (which we set, by default, when running tests under valgrind).
Use this new API from the /ssh-bridge/echo-large test.  For some reason,
it's extremely slow under valgrind, particularly on i386 — slow enough
that we're regularly hitting the alarm() timeout of 120 seconds on
semaphore.

tests: skip slow tests under valgrind

---

src/common/test-webserver.c

This reverts commit 9f22c8ce37ddd3b943ea319586f1aa4caa7675a1.
This was always meant to be a temporary workaround.
Closes #11909

Revert "tests: Don't resolve ``localhost`` for mocked systems"

---

Makefile.am
containers/unit-tests/run.sh

In the course of 'make distcheck', we end up building two tarballs,
twice (for a total of 4) and compressing them with 'xz --extreme', which
is really slow.
We can substantially speed things up using -0.  This is actually even
faster than gzip, but let's leave the i386 gzip case in place anyway,
because it tests a different path.
Measured locally on my unloaded laptop, this results in a speedup of a
bit over 2m30s, which is a ~30% improvement on a unit-tests run (ie:
`containers/unit-tests/start`).  On Semaphore, under load, the change is
probably even larger.
Closes #12289

containers: don't use xz --extreme for unit-tests

---

pkg/lib/page.css

Overflowing truncates the kebab menu tails.
We need to choose to scroll for _many_ menu items or allow (pseudo-)elements to visually "escape" the `.dropdown-menu` container.
In the case of most dropdowns, they don't need children to display outside of their boundaries. For kebabs, however, they do. And the kebab menus also _should_ be short in the # of items anyway.

lib/page: Fix kebab menu pointers

---

HACKING.md

The npm/nodejs versions from these distributions are an endless source
of trouble.  Recommend using "n" instead.
Closes #12301

HACKING.md: Update instructions for Debian/Ubuntu

---

package.json

This package was giving a very large deprecation warning when running
npm, and it looks like nothing is actually using it anymore, so let's
remove it.
Closes #12300

package.json: remove @babel/polyfill

---

pkg/lib/cockpit-components-modifications.jsx
pkg/selinux/selinux-client.js
pkg/selinux/setroubleshoot-view.jsx

@garrett reported in  #12284 that `semanage` failes on his system. There is not much we can do about broken systems. However we can at least stop the spinner with message `Loading sys mods` and show that it failed. There is opened always alert message that shows more info.
@garrett can you verify that on your system it shows "Failed to load system modifications"? I've created some artificial crash but it would be great if you could ack that it also catches your problem. Thanks.
Fixes  #12284

selinux: Inform user that reading of system mods failed

---

src/bridge/Makefile.am
src/common/Makefile-common.am
src/common/cockpitmemory.c
src/common/cockpitmemory.h
src/ssh/Makefile-ssh.am
src/ws/Makefile-ws.am

Some parts of libcockpit-common.a don't have any dependencies other than
libc. We need this subset for security critical/minimal bits like
cockpit-session, and for various tests.
Instead of building these sources up to four times, build them into a
libcockpit-common-nodeps.a and use it where needed.

build: Split out library without external dependencies

---

pkg/shell/shell.less

Overflow was previously used for containing floats. Since then, we
switched to grid-based layout, so it is no longer needed.
In fact, overflow of hidden was truncating the shutdown selector.
Fixes #12309
Closes #12330

shell: Remove overview `overflow: hidden`

---

pkg/lib/journal.css
pkg/lib/journal.js
test/verify/check-services

Fixes #12328
Tests are going to conflict with #12265, but then I rebase either one lands second.

logs: Show empty message when no logs available

---

pkg/lib/journal.css

- Remove dark background for the headers (as it was too contrasty with the rest of the pages where logs are located)
- Adjust heading spacing
- Add a separater border for date headings, except for the first heading

journal: Restyle logs across all of Cockpit

---

pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

Add a warning as well that adding a custom service will reload
firewalld, resulting in a loss of runtime-only configuration.
This addresses https://bugzilla.redhat.com/show_bug.cgi?id=1725094 as
well.

firewall: Only reload firewall when adding custom services

---

bots/image-refresh

master does not support RHEL 7 builds any more, so don't trigger these
tests on openshift or ipa images any more.

bots: Stop testing obsolete rhel-7* images on master

---

pkg/systemd/init.js
pkg/systemd/services.css
pkg/systemd/services.html
pkg/systemd/services.jsx
test/verify/check-pages
test/verify/check-services

This change makes the tabs accessible. Also it moves a small bit of services page into React. Upon this can be build and other parts of services page can be moved into React. This is gonna conflict with #12265, but both conflicts are going to be easy to resolve, so does not matter which lands first.

services: Use PF tabs

---

pkg/machines/components/diskAdd.jsx
pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

This commit calls the poolRefresh API everytime when fetching the list storage
pools. This will trigger the refresh event to get emited, which will
call the GET_STORAGE_POOL for each refreshed pool.
Inactive pools don't have events, so call directly the GET_STORAGE_POOL
method for those.
This commit will allow the user to refresh pool data by reloading the browser page.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1680293

machines: when fetching storage pools refresh them first if they are active

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx

Example: https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12068-20190714-155252-187e2b57-verify-fedora-30/log.html#204
@KKoukiou : Can you please check if this makes sense? I. e. do we actually have a test that tries an invalid number, or is that pointing out some race condition?

fix "input is not a number" error in machines tests

---

pkg/systemd/host.css
pkg/systemd/init.js
pkg/systemd/service-details.css
pkg/systemd/service-details.jsx
pkg/systemd/services.css
pkg/systemd/services.html
test/common/test-functions.js
test/common/testlib.py
test/verify/check-networking-basic
test/verify/check-pages
test/verify/check-realms
test/verify/check-services

Redesign and rewrite (part of) service details into react. (Only the panel marked with red is in React as I wanted to make as little changes as possible, moving other things into React should be follow ups).
Follows [this](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/services/service-details.png) design.
No need for code review, I plan to polish that anyway. Firstly I would like to get design review by @garrett as he created the design. Can you please take a look, thanks. If you have some small styling fixes feel free to push them here (ideally as separate commit(s)). Also @andreasn if you have time I would like to hear your feedback as well, it is different to use it than to see mock-up and you can maybe find some rough edges that could be fixed. Thanks. 
Only …

services: Redesign details page

---

pkg/networkmanager/interfaces.js
test/verify/check-networking-settings

Fix typo that caused the prefix length to be duplicated into the metric
route field.
https://bugzilla.redhat.com/show_bug.cgi?id=1719575

networkmanager: Show correct IPv6 route metric in dialog

---

.gitignore
test/run
tools/test-static-code

External projects use this script to run tests. Let's do the same in
Cockpit so `tests/invoke` does not have to differentiate between cockpit
and external projects.
This is not yet used. It is going to be enabled a bit later on, see #12367

tests: Introduce `test/run` script for Cockpit

---

bots/naughty/fedora-29/11579-podman-pull-non-existing-tag-crash-no-coredump-available
bots/naughty/fedora-29/11579-podman-pull-nonexisting-tag-crash
bots/naughty/fedora-30/11579-podman-pull-non-existing-tag-crash-no-coredump-available
bots/naughty/fedora-30/11579-podman-pull-nonexisting-tag-crash

Known issue which has not occurred in 28 days
podman PullImage varlink API broken on fedora-29 when the tag specified does not exist
Fixes #11579

naughty: Close 11579: podman PullImage varlink API broken on fedora-29 when the tag specified does not exist

---

bots/tests-invoke

I have question about this and I am opening this PR to discuss it.
The test project (for now) in the tests-invoke is used just for building up name for publishing. I am not sure what this all affects, I've changed it in this PR to always use project name. If this has unwanted effect then I am ready to change it to `if self.test_project != "cockpit-project/cockpit`.
@Gundersanne @martinpitt

bots: Distinguish context only when repo is different to PR target

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/getOSList.py
test/verify/machineslib.py

Also add a helpblock indicating the suggested memory if an operating
system was detected but the selected memory is less than recommended.
Ideally we would like to prefill the memory values with the suggested
ram size from libosinfo, but this should be part of bigger refactoring of
the 'Create VM' dialog.
The text-danger class was removed from the memory helpblock because it
created extra spacing between the helpblocks.
The red color for failed validation comes from the wrapper formgroup
element anyway.

machines: introduce check for VM memory to be above allowed minimum

---

tools/cockpit.spec

Fedora Packaging Guidelines allow dependencies only on files/directories
from /usr/bin, /usr/sbin and /etc directories[0], so replace the
docker.service dependency with the package alternatives that provide it
in current Fedora.
[0] https://docs.fedoraproject.org/en-US/packaging-guidelines/#_file_and_directory_dependencies
https://bugzilla.redhat.com/show_bug.cgi?id=1731686

spec: Avoid file dependency in cockpit-docker

---

bots/task/testmap.py
bots/tests-scan

We need to use this map on other places as well.
Also it could become one day a library that would provide this
information by collecting it from external projects (so cockpit wouldn't
have to hold this info for everyone).

bots: Move contexts map into own file

---

pkg/networkmanager/interfaces.js
pkg/networkmanager/test-utils.js
pkg/networkmanager/utils.js

Initializing the endianess in parallel meant that a lot of IP addresses
in the UI got rendered with `byteorder === undefined`, and thus being in
reverse order on big-endian machines.
Make these errors apparent also on LE machines by asserting that the
value is set correctly. In the UI, initialize byte order first and defer
everything else until that finished, via a new "preinit" promise.
https://bugzilla.redhat.com/show_bug.cgi?id=1728213

networkmanager: Ensure that endianess is always set

---

pkg/machines/libvirt-dbus.js

This could lead to race conditions, where a pool gets added twice.
This probably fixes the StoragePools test flake.
See here: https://209.132.184.41:8493/logs/pull-12331-20190722-144646-ccefb0d2-cockpit-project-cockpit-verify-fedora-30/log.html#229

machines: do not add a new pool entry into the global state with 'Started' signal

---

bots/tests-invoke

Fedora-30 in https://github.com/cockpit-project/cockpit/pull/12331 does not produce `.html` logs. Now it should. I'll run it here to check if it really fixes it.
And sorry for such stupid mistake :(

bots: Fix typo in cockpit-project naming

---

pkg/lib/cockpit-components-select.jsx
pkg/machines/components/diskAdd.jsx
test/verify/machineslib.py

Show them in the dropdown list but disable the pools for which the
CreateVol API is not supported.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1731849

machines: handle pools which don't support CreateVol API in add disk dialog

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1731803

machines: disable pxe booting when a user selected session connection

---

src/bridge/cockpitpacketchannel.c

On some architectures at least, send(2) can fail with `ENOBUFS` on
congestion. Accept that as a transient error condition as well.
Also fix the broken check for EAGAIN/EINTR.
Fixes #12414

bridge: Handle ENOBUFS in packet channel

---

pkg/systemd/init.js
pkg/systemd/services.html
test/selenium/selenium-base.py
test/verify/check-services

However show `.target`, `.socket` etc.
There are also templates, which have form `name@.service`, which now ends up as `name@`. Is that fine or should we keep `.service` for templates? You can see that in this screenshot:

services: Do not show `.service` in service overview table

---

bots/machine/machine_core/ssh_connection.py

When running our tests or other VM operations in toolbox, ssh'ing via
the connection sharing socket does not work: connect() just gets a
`ECONNREFUSED`. There is something about podman's/toolbox'es /tmp that
it doesn't like.
Place the socket in our own VM temp dir, which works fine and is
harmless for CI and non-toolbox use.

bots: Put ssh control socket into our VM temp dir instead of /tmp

---

bots/machine/machine_core/ssh_connection.py

Apparently this broke the selenium tests.
This reverts commit 45d4fa0311753ebac5b1e41b47dc0cb4711ba6b3.

Revert "bots: Put ssh control socket into our VM temp dir instead of /tmp"

---

pkg/packagekit/updates.jsx
pkg/systemd/host.js

The PackageKit `GetUpdates()` call is apparently fairly expensive on
embedded systems like the RasPi (taking several seconds, as opposed to ~
0.3 s on laptop/server class hardware).
Now check at most once per hour, and after refreshing package indexes or
applying updates on the Software Updates page. Remember the state
through a sessionStorage variable.
This is a trade-off: This will now present out of date information if
software updates are being applied outside of Cockpit, or in the
Terminal.
Fixes #12413

sytemd: Dial down checking for available software updates

---

pkg/systemd/service-details.jsx
test/verify/check-services

"is an instanced from" is ungrammatical, and one can't concatenate parts
of a sentence like this, as it's not translatable.

systemd: Fix template instance link

---

containers/unit-tests/README.md
containers/unit-tests/build
containers/unit-tests/exec
containers/unit-tests/start

Detect if we have podman installed and use that in preference to docker.
If we have only docker, make sure to run it under sudo.
This commit is a little bit ugly, particularly in the 'exec' script: we
can end up running sudo more than once for the normal case where we
detect the ID.  I have some weird ideas about how to work around that,
but they're pretty evil.
The sed thing is also pretty nasty.
...

containers: use 'podman' or 'sudo docker' in unit-tests scripts

---

pkg/lib/plot.css
pkg/systemd/host.js

The tick labels of the y-axis were frequently overlapping the graph
itself, for two reasons:
- There was not enough space for very long labels like "0.500".
- One needs to call plot.resize() explicitly whenever the size of a
graph has changed.  This doesn't always happen, such as when then
column with the graphs gets narrower because the info column gets
wider when the machine id is inserted into it.

system: Fix graph tick labels

---

pkg/networkmanager/interfaces.js
test/verify/check-networking-bond
test/verify/check-networking-bridge
test/verify/check-networking-team

This seems to be necessary to have NetworkManager act on those
changes.
This also causes the former slaves to be active after deleting a
bond (etc).  This used to be the case in the unknown past but recently
NM would deactivate them with a reason of "dependency-failed".  See
https://bugzilla.redhat.com/show_bug.cgi?id=1724163

networking: Activate a connection after clearing master/slave fields

---

tools/cockpituous-release

This PPA hasn't existed for a while now and uploading failed.

cockpituous-release: Don't upload to ubuntu ppa

---

bots/inspect-queue

The AMQP queue contains binary data. Decode it to avoid prefixing
everything with `b''`.

bots: Fix printing in inspect-queue

---

bots/tests-invoke

But fall back to the old "test/run" if necessary.

bots: Use .cockpit-ci/run as entry point in tests-invoke

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/create-vm-dialog/createVmDialogUtils.js
pkg/machines/scripts/create_machine.sh
pkg/machines/scripts/install_machine.sh
src/base1/patternfly-overrides.less
test/selenium/testlib_avocado/machineslib.py
test/verify/machineslib.py

 machines: replace os-vendor/os dropdowns with TypeAheadSelect component from PF-react

---

pkg/machines/components/diskAdd.jsx
pkg/machines/libvirt-virsh.js
pkg/machines/xmlCreator.js
test/verify/machineslib.py

Don't try to set the disk driver type to something which is neither of
qcow2 or raw.
Volumes on some pool types, can have different format types though.
In that case, just omit settings the disk driver type, and let QEMU
autoset the default.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1732303

machines: fix setting of volume format when adding new disks to VMs

---

pkg/lib/packagekit.js
test/verify/check-packagekit

Check yum configuration (or dnf -- on RHEL 8 it's a symlink) if
subscription-manager is enabled for package manager, before checking if
the system is subscribed. This avoids showing "This system is not
subscribed" on the System and Software Updates pages on non-RHEL systems
like CentOS 7 or Fedora. Merely installing subscription-manager there
(which is sometimes pulled in through dependencies) should not break
these.
This was spotted by our Fedora/CentOS tests. Remove the workaround on
Fedora, to make sure the pages work out of the box with
subscription-maanger installed.
Fixes #12359

systemd, packagekit: Check for subscription only if enabled in package manager

---

pkg/storaged/client.js

storage: Use standard $PATH when checking for mount.nfs

---

pkg/lib/cockpit-components-listing.jsx
pkg/lib/listing.less
pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css
test/verify/check-networking-firewall

~~blocked on:~~
~~- [ ] https://bugzilla.redhat.com/show_bug.cgi?id=1737045~~
using `org.fedoraproject.FirewallD1.config.service.getSettings2()`
---
Fixes rhbz#1721548.
In the image below, the DNS service doesn't have any included services, freeipa4 does.

firewall: Show any included services on a service

---

src/tls/connection.c
src/tls/connection.h
src/tls/server.c
src/tls/test-connection.c

Also move from a single global data buffer in Server to a per-connection
buffer pair (once for each data direction).
This paves the way for asynchronous write handling in the server, and
makes the data housekeeping easier to audit and unit-test.

tls: Move data reading/writing into Connection

---

pkg/machines/components/diskAdd.jsx
pkg/machines/xmlCreator.js

If you attach existing volume as a disk, default storage pool format
would be used as disk format. That's however not correct, as we should
use volume's format type as a disk's format type.
Pool's default format type should be used only as a fallback when volume's
format type is not present.

machines: Fix incorrect disk format when attaching existing volume

---

src/tls/test-wsinstance.c

`gnutls_datum_t`'s size field is an unsigned int, while
`g_file_get_contents()` writes the length into a gsize. Apparently gsize
is bigger on s390x, so the size ended up being 0.
This caused gnutls_x509_crt_import() to fail.

tls: Fix test-tls-wsinstance on s390x

---

bots/vm-run

On non-usrmerged Debian systems, virsh is found in /usr/bin (and not in
/bin).  Stop hardcoding the path to /bin and just use the normal PATH
mechanics to find it.

test: use PATH for virsh in vm-run

---

src/tls/server.c

We currently use a a mix of the fd and ptr fields, which means that in
some cases we're writing a ptr into the struct and reading out a fd (as
the lower 32bits of the pointer value).  This could easily get us in
trouble, so use pointers consistently.

tls: use epoll_data ptr field consistently

---

src/ws/cockpitcertificate.c

This was a by-product of something that we don't actually need. This is a tiny cleanup that's useful by itself.

ws: Simplify cockpitcertificate.c with g_autofree

---

src/tls/README.md
src/tls/test-wsinstance.c
src/tls/wsinstance.c
src/tls/wsinstance.h

These get written into `$RUNTIME_DIRECTORY/ws.<ws_pid>.crt`, so that
authentication programs like cockpit-session can find it via their
parent pid (which is cockpit-ws). This is a property that a
hacked/malicious cockpit-ws cannot forge, other than losing the link to
the certificate by quitting itself.
This functionality is not yet accessible, so only unit-test this.

tls: Write client certificate to runtime directory

---

src/tls/server.c
src/tls/test-server.c

We shouldn't be making unsafe calls from a unix signal handler, so
instead of handling the exit immediately use an eventfd to signal the
mainloop to handle it on the next iteration.

cockpit-tls: use eventfd from SIGCHLD handler

---

Makefile.am
autogen.sh

autogen.sh contains an unsafe invocation of find|xargs to iterate over
the node_modules and delete all test directories that it finds (with the
goal of reducing the size of the cache tarball by removing unit tests).
This is a pretty strange thing to do to the node_modules directory,
particularly when you contemplate incremental invocations of 'npm
install'.  The same effect can be accomplished by using tar --exclude
when creating the tarball.  Do that instead.

build: don't delete test/ directories in autogen

---

autogen.sh

There is a category of failure of 'npm install' that leaves
node_modules/ in a corrupt state and won't be fixed by just running 'npm
install' again.  Try harder.

autogen.sh: make npm install *more* robust

---

bots/images/scripts/windows-10.bootstrap

- Switch to `wget --continue` so that it's possible to resume
interrupted downloads, and avoid accidentally running the build with
partial downloads.
- Make the script idempotent by destroying the libvirt domain first
before (re-)creating it.
- Avoid the expensive unzip if it already run before.
- Avoid virt-copy-in (libguestfs), it's a very expensive dependency
that doesn't work in containers. Instead, just attach virtio-win.iso
as a second CD-ROM drive and directly run from there, which also
simplifies the setup script.
- Add URLs from where to get the downloads.
- Drop the `--os-type` option from virt-install. It has been deprecated
and ignored for a while.

bots: windows-10.bootstrap improvements

---

bots/naughty/debian-stable/12250-apparmor-libvirt-rawio
bots/naughty/debian-testing/12250-apparmor-libvirt-rawio
bots/naughty/ubuntu-1804/12250-apparmor-libvirt-rawio
bots/naughty/ubuntu-stable/12250-apparmor-libvirt-rawio

apparmor denies sys_rawio capability from libvirtd which happens when using scsi disks
Fixes #12250

naughty: Close 12250: apparmor denies sys_rawio capability from libvirtd which happens when using scsi disks

---

bots/task/testmap.py

It was out of date, and isn't necessary right now.
Also use a consistent formatting for all the entries.

bots: Drop obsolete cockpit-composer/rhel-8.1 branch

---

bots/tests-invoke
bots/tests-scan

While on it, unify how we deal with statuses and contexts.
Now it works something like this:
1) Get all existing statuses from github and verify them
2) If there are no valid statuses get the default ones
3) Of change in bots/ append all external contexts
4) Go through all generated contexts:
4.1) If test name contains project (and branch) use those instead of
default ones
Other things work the same.
**This is in testing, opening PR to see how bots deal with it. Failing to prepare tests is expected.**
There is still one thing I work on - the fact that image-refresh is opened against master, but we want to test it in stable branch. We need to do:
1) Checkout the stable branch
2) Pick bots from correct ref
I think we don't do this anywhere, so make-checkout needs to be edited as well
(If we …

 bots: Enable passing test branch in test name

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/getOSList.py
pkg/machines/scripts/create_machine.sh
test/verify/machineslib.py

User cannot input storage size lesser than is minimum required by
VM's OS (provided by libosinfo).
Also when user inputted 0 as storage size, VM without any storage
would get created. Since we have "No Storage" option already,
get rid of this hacky way.

machines: Limit storage size input field of VM Create dialog

---

po/Makefile.am
po/manifest2po

This stopped working when `manifest.json` was moved into
`manifest.json.in`. We do not generate any translations from manifests
now. Most of menu items are translated, but only thanks to the fact that
those strings appear on other places as well.
For example `Docker Containers` do not appear anywhere and therefore
cannot be translated now.

po: Generate translations from manifests again

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/selenium/selenium-machines-basic.py
test/selenium/testlib_avocado/machineslib.py
test/verify/machineslib.py

When possible, the OS is auto-detected. However, for PXE boots, or in
cases where libosinfo didn't manage to return some result, the user
should insert the Operating System information, because without that,
they will end up with guest that severely underperforms.

machines: make Operating System input mandatory field when creating new VMs

---

pkg/systemd/service-details.jsx
test/verify/check-services

Disabling or masking a service means that the user is done with a
service, and any lingering "failed" state is distracting noise.

services: Reset "failed" status when disabling and masking

---

bots/machine/machine_core/cli.py
bots/machine/machine_core/machine_virtual.py
bots/vm-run
test/common/testlib.py
test/selenium/run-tests
test/verify/check-bots-api

All our images support virtio-net now, but e. g. Debian cloud images
don't support the ancient rtl8139 any more. Let's use virtio which is
faster.
Pass the image to VirtNetwork(), so that it can decide which image
supports which virtual hardware.

bots: Use virtio-net instead of rtl8139 network cards for our VMs

---

.gitignore
bots/issue-scan
bots/make-checkout
bots/tests-invoke
bots/tests-scan

This should coincide with some changes in cockpituous as well, which provides XDG_CACHE_HOME and the needed checkouts.
---
Differences should be limited to: 
- `WORKDIR`
-  `--remote=...` as it's now always `origin`
- `GITHUB_BASE` should now be present on external projects against a cockpit PR
- `GITHUB_BASE` should now be absent from tests of external repos as origin is the external repo
5 cases:
seems ok
master
```
PRIORITY=0004 bots/make-checkout --verbose --base=master --repo=cockpit-project/cockpit pull/12426/head ca64bfc97921952290e09b7d58bf16189a57baae && GITHUB_BASE=cockpit-project/cockpit TEST_PROJECT=cockpit-project/cockpit TEST_NAME=pull-12426-20190816-122929 TEST_REVISION=ca64bfc97921952290e09b7d58bf16189a57baae bots/tests-invoke --pull-number=12426  --rebase=master fedora-30 …
```

Let make-checkout produce a "standalone" directory

---

bots/image-prune

We don't need to keep image that is only on old not-rebased image.
Also from PRs that changed any image just keep the changed image(s), not all others that were present in the time when the image was changed.

bots: Only keep images from PRs that actually changed in the PR

---

pkg/systemd/host.js
pkg/systemd/hw-detect.js
pkg/systemd/hwinfo.jsx
test/verify/check-system-info

When `sys_vendor` is undefined try `board_vendor`.
When `product_name` is undefined try `board_name`.
When either of vendor or name is not defined by neither of those
options, then just show `Details`.
Fixes #12593

hwinfo: Never show 'undefined' in HW field

---

po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/ja.po
po/manifest2po
po/pl.po
po/pt_BR.po
po/uk.po
po/zh_CN.po

`html2po` does the same.
Noticed on #12617, from logs it executes `bots/make-source update-po`
Works both with : 
- `bots/make-source update-po` (how bots do it on refresh)
- `./autogen && make po-update` (how normally one would do it locally)
Hopefully this can be tests:

po: Fix file reading in manifest2po

---

bots/naughty/rhel-8/12086-firewall-addservice-fails

rhel-8-1 Adding service into permanent configuration via DBus api suddenly requires 9 values
Fixes #12086

naughty: Close 12086: rhel-8-1 Adding service into permanent configuration via DBus api suddenly requires 9 values

---

.eslintrc.json
bots/README.md

Eslint shimmies up directories looking for more eslintrcs. As
make-checkout now clones projects in a subdirectory, this can result in
some strange interactions.
Each subproject using eslint should enable this as well.
https://eslint.org/docs/user-guide/configuring

eslintrc: Set "root" to true

---

pkg/machines/components/storagePools/storagePool.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/libvirt-dbus.js
pkg/machines/xmlCreator.js
test/verify/machineslib.py

**Refresh pool after volume has been created during disk attachment**
When user creates a new disk in Add Disk dialog, pool would not get refreshed. In order to show new volume in pool's volume list in Storage Pools page, user has to reload the page. Fix this by refreshing pool after creating volume.
￼
**Fix size units confusion for storage pools and volumes**
When creating disk, we incorrectly label size as MB instead of MiB, which leads libvirt to create volume of incorrect size. (e.g. when user inputted 1GiB as disk size, disk of 0.95GiB would get created). Also we incorrectly show GB value for storage pool size and storage
volume in Storage Pools page.

machines: Some small fixes related to storage pools

---

bots/tests-scan

Fixes #12633
@Gundersanne can you think of any usecase where we want all contexts when the branch does not exist in our map? I have small voice in back of my head saying something about external projects, but I cannot find any usecase where this would be true.

bots: When unknown branch do not trigger any contexts

---

src/bridge/Makefile.am
src/bridge/mock-client-expired.crt
src/tls/server.c
src/tls/test-server.c

cockpit-tls is supposed to not validate the trust of client
certificates, this is delegated to sssd. However, it should still reject
expired, unsafe, or otherwise invalid certificates. Add a custom peer
certificate verify function for this.
The unit test needs some tweaking to work with TLS 1.3 and earlier. The
former uses a reduced handshake so that `gnutls_handshake()` on the
client side does not fail on a failing certificate validation, only on
the first I/O operation. See
https://nikmav.blogspot.com/2018/05/gnutls-and-tls-13.html for details.

tls: Reject invalid client TLS certificates

---

pkg/machines/components/networks/createNetworkDialog.jsx

The original selector got broken by change made in fc251d376f. Fix by removing label from CreateNetworkModal component.

machines: Fix connection selector in Create Virtual Network dialog

---

bots/task/testmap.py

if this needs disabling we should use @skip decorator inside
weldr/lorax repository so it will be easier to see!
CC  @larskarlitski

Re-enable Azure test for weldr/lorax. Refs #12059

---

pkg/storaged/client.js
pkg/storaged/drives-panel.jsx
pkg/storaged/mdraids-panel.jsx
pkg/storaged/others-panel.jsx
pkg/storaged/overview.jsx
pkg/storaged/storage.css
pkg/storaged/vdos-panel.jsx
pkg/storaged/vgroups-panel.jsx
test/selenium/selenium-storage.py

The name now uses the whole width of the row.
- Use a flexbox instead of a table (but keep the table for easy
borders and highlighting).
- Remove the icon since every row in a panel has the same icon anyway.
- Add the filename of the block device.
The side panel of the Storage page does not truncate names anymore and shows names in `/dev`.

storage: Polish interior layout of the side panels

---

tools/release-guide

check-git-rw moved to cockpituous release/ many years ago. It's
installed into $PATH in the release container.

tools: Fix release-guide test mode

---

bots/run-queue

This is currently causing trouble, because I'm simulating standalone-bots still. This should fix the issue.

bots: Drop hack in run-queue, always specify repo

---

package.json
pkg/lib/notifications.js
pkg/playground/manifest.json.in
pkg/playground/notifications-receiver.html
pkg/playground/notifications-receiver.js
pkg/playground/notifications.html
pkg/playground/notifications.js
pkg/shell/base_index.js
pkg/shell/indexes.js
pkg/shell/shell.less
src/base1/test-http.js
test/verify/check-pages
webpack.config.js

shell: Page status notifications

---

pkg/machines/components/networks/networkList.jsx
pkg/machines/components/storagePools/storagePoolList.jsx
pkg/machines/libvirt-dbus.js
pkg/machines/reducers.js
test/verify/check-machines-dbus

This will prevent the race condition, where the VIR_STORAGE_POOL_EVENT_UNDEFINED
signal will get handled before VIR_STORAGE_POOL_EVENT_DEFINED resulting
in the pool whose creation failed to appear in the UI anyway.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1715388

machines: When receiving *EVENT_DEFINED add a minimal representation of the resource to the state

---

bots/image-prune

Previously we did `read(4000)` on [this](https://patch-diff.githubusercontent.com/raw/cockpit-project/cockpit/pull/12669.patch) kind of URLs. The problem is that it is commit by commit (and not overview first as I wrongly thought) and therefore it could not sees commits that really do those image refreshes.
This new approach is cleaner, it uses `pulls/<number>/files` API for getting list of changed files. (yes, it considers also those that PR is deleting for keeping, which is fine I think). Also it goes away with regex which is nice.
When I run it now it says for scanning of PRs: (it also considers then branches of course)
```
Keeping bots/images/fedora-atomic from 12687
Keeping bots/images/continuous-atomic from 12686
Keeping bots/images/debian-stable from 12669
Keeping …
```

bots: Get list of changed files for pruning

---

test/verify/check-journal

Setting the time to year 2038 will not persist across reboots if the
testbed kernel does not have RTC enabled. This is the case on e. g. the
Debian cloud kernel.
Thus set the time back to the expected time after rebooting the test VM.

test: Stop assuming RTC module in testbed kernel

---

src/tls/server.c

The manpage says this about error returns from accept():
Linux accept() (and accept4()) passes already-pending network  er‐
rors  on  the new socket as an error code from accept().  This be‐
havior differs from other BSD socket implementations.   For  reli‐
able  operation  the  application should detect the network errors
defined for the protocol after accept() and treat them like EAGAIN
by  retrying.   In the case of TCP/IP, these are ENETDOWN, EPROTO,
ENOPROTOOPT, EHOSTDOWN, ENONET, EHOSTUNREACH, EOPNOTSUPP, and ENE‐
TUNREACH.
As such, we shouldn't be treating failure to accept() as a fatal error
and terminating the server.

tls: make accept() errors non-fatal

---

bots/image-refresh
bots/task/testmap.py

There is no way to run fedora-30/container-kubernetes any more, as that
package was dropped after Fedora 29. So drop it from the rhel-7.{7,8}
tests.
Test rhel-7-8 on openshift refreshes as well.

bots: Adjust tests for openshift images

---

src/tls/server.c
src/tls/test-wsinstance.c
src/tls/wsinstance.c
src/tls/wsinstance.h

After waitpid() has returned a pid to us, it has been freed up for
reuse.  We shouldn't be calling kill() on it in this case.
This removes a strange condition on `if (ws->pid)` which was always
true.  We could also have set ws->pid to 0 in the case of SIGCHLD, but
this would have disrupted debugging output.

tls: don't kill() a pid we just got from waitpid()

---

bots/image-refresh

As it's always no-test now and the webhook interprets the status events,
we don't need to wait until the correct set of statuses have been reported.
The PR will have [no-test] in the title for any of the PR events, and the [no-test] label will prevent excess externals on status events.
---
I think  I could even test this image refresh here, since issue-scan now produces a command with make-checkout:

bots: Make image-refresh PRs always no-test

---

bots/image-refresh
bots/images/scripts/selenium.bootstrap
bots/images/scripts/selenium.setup
bots/images/selenium

Use CentOS 7 as a base image, so that we don't need to upgrade it to
latest Fedora twice a year.
Move to virt-install-fedora to get rid of the libguestfs dependency and
be able to build this image in an unprivileged podman container.

bots: Move selenium image to CentOS-7 and virt-install

---

test/common/testlib.py
test/verify/kubelib.py

PR #12693 changes our openshift image from Fedora 28 to CentOS 7. A
failed ssh login takes very long there, triggering a timeout in
cockpit-ssh and thus a different error dialog. Adjust the test to that.

test: Adjust TestOpenshift.testNodeNavigation check for updated openshift image

---

bots/image-prune
bots/image-refresh

Spotted by tools/test-static-code on current Fedora 30:
```
bots/image-prune:28: 'urllib' imported but unused
bots/image-prune:29: 're' imported but unused
bots/image-refresh:23: 'time' imported but unused
```

bots: Fix pyflakes errors

---

pkg/machines/libvirt-common.js

Call `parseOsInfoList()` with a valid empty list JSON instead of an
empty string; the latter causes
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Log the error before this, to make sure it can be seen even if the
`parseOsInfoList()` dispatch fails.

machines: Fix handling of getOSList.py failures

---

src/common/test-webserver.c

This is essentially commit 9f22c8ce37 again, but now because this has
kept failing in COPR fedora-30 build environments for a while (Fedora
proper or local builds are fine, and so is the COPR rhel-8 environment).
There is no obvious mis-configuration of /etc/hosts or nsswitch.conf
there, so this will take some more time to debug. Until then, stop
breaking our releases due to that.
See issue #12423

tests: Don't rely on resolving "localhost" in test-webserver

---

src/tls/test-server.c

TLS 1.3 was really introduced into 3.6.4 (see
https://gitlab.com/gnutls/gnutls/blob/master/NEWS), not 3.6.5 (as the
referenced blog entry in commit e5a6366f3cf4 says).
Correct the version check, so that the test works properly in the
`rhelbeta-8-x86_64` mock environment. This fixes a build failure on
COPR.

tls: Fix GnuTLS version check for TLS 1.3 in test

---

test/verify/check-packagekit

When disabling /usr/libexec/rhsmd (on RHEL images), re-enable it at the
end of the test. This unbreaks running more than one check-packagekit
test on an external testbed.

test: Fix rhsmd cleanup in check-packagekit

---

bots/images/scripts/lib/debian.install
test/verify/packagelib.py

When trying `pkcon refresh` or similar operations, PackageKit fails with
Fatal error: Cannot refresh cache whilst offline
while NetworkManager is still busy with setting up connections.
Wait until NetworkManager's connectivity is at least
`NM_CONNECTIVITY_LIMITED` [1], so that PackageKit is happy. (This is
unfortunately not what `nm-online` does.)
This is supposed to replace the ubuntu-stable specific hack with setting
a fake manual route. But this does not work because
/etc/NetworkManager/conf.d/noauto.conf is somehow missing from that
image, so that NetworkManager still forever tries to connect to the
disconnected eth1. Until this is fixed on the image, keep the hack in
place, but update its documentation.
[1] https://developer.gnome.org/NetworkManager/unstable/nm-dbus-types.html#NMConne …

test: Wait for NetworkManager to be online before PackageKit operations

---

src/tls/server.c
src/tls/test-server.c

This uses GnuTLS 3.3.x, which does not yet know about
`GNUTLS_E_CERTIFICATE_VERIFICATION_ERROR` yet (this was introduced in
3.4.3).
With this GnuTLS version our validation function also does not actually
cause the connection to fail, so that /server/tls/client-cert-expired
fails. As we don't support master on these old releases, just skip the
test there. Nothing is using the validation in practice yet, and once we
do, sssd will validate the certificate by itself anyway, so this is
safe.
Fixes #12713

tls: Fix building on RHEL/CentOS 7

---

pkg/apps/application.css
pkg/kdump/kdump.css
pkg/selinux/setroubleshoot.css
pkg/sosreport/sosreport.css
pkg/systemd/host.css
pkg/systemd/hwinfo.css
pkg/users/users.css

This was no longer correct after https://github.com/cockpit-project/cockpit/commit/dabebcab
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1749586
Please can someone test this? Please don't forget to do it VM or clean your current builds.

Fix paths in .css files that import from pkg/lib

---

pkg/lib/service.js

This makes the proxies useful for other kinds, such as timers.

lib: Expose type-specific systemd unit details

---

pkg/shell/index.html
pkg/shell/indexes.js
src/base1/cockpit.js
src/ws/cockpitcertificate.c
src/ws/cockpitcertificate.h
src/ws/cockpithandlers.c
src/ws/cockpithandlers.h
src/ws/login.js
src/ws/main.c
test/common/testlib.py
test/verify/check-connection
test/verify/check-login

It is possible to misconfigure Cockpit or a proxy so that websockets
connection can not be established.  Show a error message in this case
instead of a blank page.

shell: Display message when websocket fails early

---

bots/naughty/fedora-30/11441-listing-timezones-fail

Listing timezones fails on Fedora 30
Fixes #11441

naughty: Close 11441: Listing timezones fails on Fedora 30

---

src/tls/server.c
test/verify/check-connection

In cockpit.socket it's possible to specify `ListenStream=` multiple
times, which will result in multiple listening fds being passed via
systemd. We even document that in our guide.
Support up to 10 fds now and handle them in an array. The epoll data.ptr
is a bit clunky, but as epoll does not return the actual fd for an
event, this saves us from introducing yet another housekeeping
structure.
Fixes #12627

tls: Support multiple listening ports

---

bots/naughty/rhel-8/12405-selinux-qemu-kvm-tcg

SELinux is preventing qemu-kvm to access /proc when running in tcg mode
Fixes #12405

naughty: Close 12405: SELinux is preventing qemu-kvm to access /proc when running in tcg mode

---

pkg/systemd/host.js
pkg/systemd/index.html
test/verify/check-system-info

The warning will only appear when the Subscriptions page announces in
its manifest that it actually supports connecting to Insights.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1745964

RHEL 8 - systemd: Warn if not connected to Insights

---

bots/images/scripts/lib/fedora.install

First copy the the script into the chroot, then execute it.

bots: Fix rpmlint script in fedora installs

---

package.json
pkg/packagekit/updates.jsx

This npm module has not been updated in two years, and is using an old
version of remarkable that pulls in deprecated stuff:
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
It's also not really giving us much aside from not making the
`dangerouslySetInnerHTML` explicit. So use the current version of
remarkable directly instead.

packagekit: Eliminiate react-remarkable

---

bots/flakes-refresh
bots/learn-tests
bots/tests-policy
bots/tests-score

This should solve the SSL errors in test logs, we already do this for the learn-tests task

bots: Specify cafile for requests to learn-cockpit

---

po/Makefile.am

Since dropping registry-image-widgets npm module in commit 42cf3774,
building po/cockpit.pot has failed with
find: ‘node_modules/registry-image-widgets/’: No such file or directory
Drop it from the list of directories to translate.

po: Fix building PO template

---

test/verify/check-machines-dbus

The stable state of the card is "1 Network", but while loading it
briefly shows "0 Networks".
Thus, waiting for it to contain "Networks" is a race: most of the time
we catch it while it still shows "0 Networks" and the test continues,
but sometimes it already shows "1 Network" and the test fails.
In some cases, waiting for "Networks" is correct, since we know that
the title is "2 Networks".

test: Be happy with "Network" title in the networks card

---

pkg/systemd/host.js
pkg/systemd/index.html
test/verify/check-system-info

The warning will only appear when the Subscriptions page announces in
its manifest that it actually supports connecting to Insights.

systemd: Warn if not connected to Insights

---

bots/naughty/fedora-30/12228-selinux-mdadm-read

SELinux is preventing mdadm from 'read' 
Fixes #12228

naughty: Close 12228: SELinux is preventing mdadm from 'read' 

---

bots/naughty/rhel-8/12355-selinux-search-krb5
bots/naughty/rhel-8/12355-selinux-search-krb5-2

SELinux is preventing sssd_be and cockpit_ssh from search access to krb5
Fixes #12355

naughty: Close 12355: SELinux is preventing sssd_be and cockpit_ssh from search access to krb5

---

test/verify/check-storage-mdraid

The actual text includes quotes around the device name and wouldn't
match.  Let's not look for that part of the sentence at all.

test: Fix expected error message when failing to stop a MDRAID

---

test/verify/check-metrics

We can't guarantee that the traffic graph is otherwise idle.

test: Don't test that loopback network traffic is ignored

---

tools/test-static-code

` is a valid string delimiter in JS, but xgettext does not recognize
this. Let's fail on these similarly to single quotes.
Related to issue #12835

tools: Fail on untranslatable `` strings

---

package.json

Brought by `(patternfly-react >) patternfly > bootstrap-select` chain.
It brought version `1.12.2` which has at least two XSS vulnerabilities.
Fixes #12818
Checked manually and selects work just fine. I'll let bots check it and will see if they agree :)

package.json: Enforce version on transitively dependant bootstrap-select

---

bots/task/testmap.py

All of the pieces on the lorax side have been merged so enabling these now.

Enable several lorax checks

---

bots/images/fedora-testing
bots/images/scripts/fedora.setup

Fedora 31 needs this cache, Fedora testing needs it so soon also
Fedora-30 will need it. I think it is just more maintainable to always
keep it.
Fixes #12836

bots: Always keep mock cache for Fedora images

---

pkg/systemd/host.css
pkg/systemd/host.js
pkg/systemd/index.html
pkg/systemd/init.js
pkg/systemd/manifest.json.in
pkg/systemd/page-status.jsx
pkg/systemd/services.css
pkg/systemd/services.jsx
test/verify/check-active-pages
test/verify/check-services

- Move them to the top of the list.
- Put a warning icon into section header when it has a failed unit.
- List them on the host overview page.
- Set the page status to "warning" if there are failed units.
Screenshot:

 systemd: Highlight failed services

---

pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/libvirt-virsh.js
pkg/machines/manifest.json.in
pkg/networkmanager/firewall-client.js
pkg/networkmanager/interfaces.js
pkg/networkmanager/manifest.json.in
pkg/networkmanager/utils.js
pkg/packagekit/manifest.json.in
pkg/packagekit/updates.jsx
pkg/storaged/manifest.json.in
pkg/storaged/mdraid-details.jsx
pkg/storaged/mdraids-panel.jsx
pkg/storaged/utils.js
pkg/storaged/vdos-panel.jsx
pkg/storaged/vgroup-details.jsx
pkg/storaged/vgroups-panel.jsx

This was fixed properly in Cockpit 186. The earliest version that we
still support anywhere (RHEL 7.7) is 195, so it is safe to use
Promise.all() now. To ensure this, bump the manifest's cockpit
dependencies accordingly.
This still leaves some cases where `cockpit.all()` is being used to
deliver promises with a progress() method. These need to wait until the
pages get ported to React.

Use Promise.all() instead of cockpit.all()

---

pkg/machines/actions/provider-actions.js
test/README.md
test/verify/check-active-pages
test/verify/check-connection
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-journal
test/verify/check-kdump
test/verify/check-networking-firewall
test/verify/check-storage-format
test/verify/check-storage-luks
test/verify/check-storage-resize
test/verify/check-system-info
test/verify/packagelib.py

This missing parameter was causing TestMachines.testStoragePools to fail
sometimes since deleting a pool sometimes didn't remove the entry from the UI.
This reflects a real race condition when deleting an active resource, since
'Stopped' and 'Undefined' events get emited close to each other, which
makes state updates a bit cumbersome.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1715388
Cherry-picked from maste commit afae77.
Closes #12848

backport: machines: add missing updateOnly parameter in getStoragePool action

---

po/Makefile.am
po/cs.po
po/pl.po
po/ru.po
po/sv.po
po/uk.po

We don't have en_US.UTF-8 locale on our task bot and it breaks
translations.
Fixes #12856
Closes #12865

po: Use C.UTF-8 locale for Zanata cli

---

bots/naughty/rhel-8/12597-kdump-fails-to-start

kexec: failed to load kdump kernel in 4.18.0-131 
Fixes #12597

naughty: Close 12597: kexec: failed to load kdump kernel in 4.18.0-131 

---

pkg/systemd/init.js

Logging in and out of Cockpit during integration testing seems to
sometimes make the proxy invalid, and since this page is now
pre-loaded the JavaScript exception that would result previously would
cause unrelated tests to fail.

systemd: Don't crash when the systemd proxy is invalid

---

test/verify/check-networking-firewall

After the "pop3" service appears, all services for the default zone
are listed, but not all zones are always listed, apparently.  So we
just wait until they are all there.
The error was
testlib.Error: eval_js(ph_count_check("#services-listing tbody",9)):
found 5 #services-listing tbody not 9
and the screenshot shows that the 5 services are from the "public"
zone.  There are four more in the "libvirt" zone, but that zone isn't
yet included in the display.

test: Don't expect all firewall services to be listed immediately

---

test/selenium/run-tests

Since PR #12573 (PatternFly 4 Tables), the Machines page crashes on the
old Edge 42 on our windows-10 image. Edge refuses to update on that test
image, so we currently have no way of testing with 44 (where this crash
does not happen). See issue #12864 for details.
Until we have a better fix for that, skip the Machines page tests on
Edge. We've ignored the Edge test for some weeks now, it's too dangerous
to introduce regressions to other pages now.

test: Skip Machines selenium tests on Edge for now

---

package.json

Version 7.15.0 causes regression and all builds fail.

package.json: Pin down eslint-plugin-react

---

Makefile.am
autogen.sh

Commit cea63000a was a thinko -- for our CI we *don't* want our test to
clobber a pre-existing bots/ checkout, as we often use this to run tests
against an updated image or to validate a changes to the bots project.
On developer machines, bots may also be a symlink to an actual bots
directory in development, so don't clobber that.

build: Don't clobber an existing bots checkout

---

pkg/machines/actions/provider-actions.js
pkg/machines/components/diskAdd.jsx
pkg/machines/components/diskEdit.jsx
pkg/machines/components/diskRemove.jsx
pkg/machines/components/vm/vm.jsx
pkg/machines/components/vmDisksTab.jsx
pkg/machines/components/vmDisksTabLibvirt.jsx
pkg/machines/helpers.js
pkg/machines/hostvmslist.jsx
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/machines.less
pkg/machines/xmlCreator.js
test/common/test-functions.js
test/common/testlib.py
test/verify/check-machines-dbus

Allow multiple running VMs share a single disk.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1684304
Closes #12314

machines: Make readonly and shareable disk options configurable

---

Makefile.am
autogen.sh

* If `$COCKPIT_BOTS_REF` is set, check out that bots version instead of
master.
* Use git cache in $XDG_CACHE_HOME if available. Our CI uses that to
save downloads, and it does not get in the way for local developers.
* Stop duplicating code in autogen.sh, just call `make bots`. The tree
is configured at this point.
Ported from https://github.com/cockpit-project/starter-kit/pull/233

build: Support CI testing against a bots project PR

---

pkg/lib/page.css

See https://github.com/patternfly/patternfly-next/issues/2325 for details.

lib/page: Override PF4 to (temporarily) fix wrapping

---

Makefile.am
autogen.sh
tools/make-bots

Projects should be able to prepare bots on their own without running
`./configure` first. Therefore introduce this tool which can do exactly
that.

tools: Introduce make-bots script

---

test/run

Image preparing needs bots to be present.
`tools/make-bots` does nothing when `bots/` exists.

tests: Always prepare bots

---

package.json

Regression from 7.15.0 was fixed.
Please feel free to review but don't merge. I need this PR for testing of some changes in bots. I'll self-land once I won't need it anymore.

package.json: Unpin eslint-plugin-react

---

pkg/machines/components/diskAdd.jsx

Quick fix of bug introduced by me in https://github.com/cockpit-project/cockpit/pull/12314
How to reproduce:
Go to Vm -> Disks -> Add Disk -> Use Existing 
Choose any volume which is not used by any VM, text saying 'disk used by: .' is shown.

machines: Fix 'disk used by:' showing when it's not used

---

pkg/packagekit/manifest.json.in
pkg/packagekit/updates.jsx
pkg/systemd/host.css
pkg/systemd/host.js
pkg/systemd/index.html
test/verify/check-active-pages
test/verify/check-dashboard
test/verify/check-multi-machine-key
test/verify/check-packagekit

Now the host overview page gets all information about available
software updates from the "Software Updates" page itself, via page
status notifications.

packagekit, systemd: Use notifications for available updates info

---

pkg/lib/cockpit-components-context-menu.jsx
pkg/lib/cockpit-components-terminal.jsx
pkg/machines/components/consoles.css
pkg/machines/components/serialConsole.jsx
pkg/systemd/terminal.jsx
test/selenium/selenium-machines-consoles.py
test/verify/machineslib.py

Our console:
1. Is accessible
2. Does not use deprecated react methods
3. Supports copy and paste
4. Does not depend on old xterm.js
5. Is simpler to use
This would also hopefully unblock https://github.com/cockpit-project/cockpit/pull/12736 (hopefully because I hope that webpack is smart enough not to get dirty with serialConsole when we don't import it, but we import other components from the same package).
EDIT: - no, it does not unblock #12736 : 
```
ERROR in ./node_modules/@patternfly/react-console/dist/esm/SerialConsole/XTerm.js
Module not found: Error: Can't resolve 'xterm/lib/addons/fit/fit' in '/home/mmarusak/cockpit/cockpit1/node_modules/@patternfly/react-console/dist/esm/SerialConsole'
```
is there way how to stop compiling SerialConsole?

Use our terminal implementation in vms

---

Makefile.am

This allows users who build the source tarballs to reconstruct the exact node_modules/ as it
was on release time, as an alternative of downloading cockpit-cache-XXX.tar.gz.

build: Distribute package-lock.json in release tarballs

---

pkg/storaged/client.js
pkg/storaged/devices.jsx
pkg/storaged/dialog.jsx
pkg/storaged/storage-controls.jsx

Some actions are composed of multiple actions and while they were
running, the page used to follow along flickeringly as well as it
could.
For example, resizing an encrypted filesystem in a logical volume does
a number individual resizes one after the other.  The intermediate
states are inconsistent, and Cockpit would warn about them briefly.
Now, we suspend page updates during all actions triggered by
StorageButtons and dialogs.  Also, we try to stop the user from
aborting the composite action by unloading the page.

storage: Improve composite actions

---

src/base1/Makefile.am

Commit 3e697de5ed got broken after updating it to not include the
original base.css as a rule dependency (which does not work in released
tarballs). Fix the input of sed to be the actual file instead of the now
non-existing rule dependency.

build: Fix building of react-core-base.css

---

pkg/storaged/dialog.jsx
test/verify/check-storage-nfs

While fixing rule in #12854, I got to this component about which the linter said is not accessible and was right - you can just navigate into the input, but you cannot access the button to open the dropdown (once you open it by mouse you can use tab to move through these items but still cannot use enter to select this items).
With this component I can access it by keyboard, use arrows to navigate though items, use enter to select these items... so it is very nicely accessible by keyboard.
It is PF3 component - we use it on two another places, so I think it is fine to use this version. Or @KKoukiou do you have some idea about this component in PF3 vs PF4?

storage: Use TypeAheadSelect instead of our implementation of ComboBox

---

doc/guide/packages.xml
pkg/apps/manifest.json.in
pkg/kdump/manifest.json.in
pkg/machines/manifest.json.in
pkg/networkmanager/manifest.json.in
pkg/packagekit/manifest.json.in
pkg/selinux/manifest.json.in
pkg/shell/base_index.js
pkg/shell/index.html
pkg/shell/indexes.js
pkg/shell/switcher.less
pkg/sosreport/manifest.json.in
pkg/storaged/manifest.json.in
pkg/systemd/manifest.json.in
pkg/users/manifest.json.in
po/manifest2po
test/verify/check-pages

Uses page name and keywords to search. Later on pages will also provide what they contain (like names of services or names of users). Also works with translated pages names and translated keywords. Navigable with arrows, possible to visit page with enter and clean the search with escape.
TODOs:
Followups:

Searching with keywords

---

.eslintrc.json
package.json
pkg/lib/cockpit-components-context-menu.jsx
pkg/lib/context-menu.css
pkg/machines/components/vmnetworktab.jsx
pkg/packagekit/updates.jsx
pkg/systemd/page-status.jsx
pkg/tuned/change-profile.jsx
test/verify/check-packagekit

I found this eslint plugin which can check accessibility in jsx elements.
I thought it could be useful for us - I know it can only check react components, but as we write new things in react and also slowly port some older stuff into react as well, in a long run it could be able to check bigger and bigger part of Cockpit accessibility.
~Currently it found 121 issues in 11 rules:~ (some fixed in #12879)
Currently it found 62 issues in 10 rules:
`jsx-a11y/click-events-have-key-events` 16 times 
`jsx-a11y/anchor-is-valid` 13 times                                                                                
`jsx-a11y/no-static-element-interactions` 11 times                            
`jsx-a11y/alt-text` 8 times   
`jsx-a11y/label-has-associated-control` 5 times 
`jsx-a11y/no-autofocus` 3 …

eslint: Introduce jsx-a11y plugin

---

test/verify/check-dashboard
test/verify/check-multi-machine
test/verify/check-multi-machine-key
test/verify/check-shutdown-restart
test/verify/hacklib.py

Otherwise, the CDP protocol might just hang and cause the test run to
timeout globally.

test: Disable packagekit preloading in some more cases

---

pkg/lib/journal.css

So that things like "12:01 PM" will fit without wrapping.
Before:
After:

lib: Give more space to cockpit-log-time columns

---

pkg/machines/components/diskEdit.jsx

React sometimes recreates the components inside Table rows, and then
showModal will revert to false, causing the dialog to close.
By keeping the state outside of the components themselves, we can rely
on the dialog staying open.

machines: Don't rely on state of EditDiskAction

---

test/verify/check-subscriptions

Our rhel-atomic image does not have insights-client installed.
PR #12694 was not tested against rhel-atomic, thus we did not notice the
failure there.

test: Fix check-subscriptions for rhel-atomic

---

test/common/cdp.py

Otherwise the layout of the storage page (for exmaple) now goes to its
broken single column layout and we can't see the state of sidebar
panels.

test: Make bigger screenhots

---

test/verify/check-shutdown-restart
test/verify/hacklib.py

This machine is also accessed via SSH, which seems to be a factor in
triggering the CDP breakage.

test: Disable packagekit pre-loading on one more machine

---

test/verify/check-docker-storage

This is part of https://github.com/cockpit-project/bots/pull/104 where it should fix 2 out of 3 failing tests.
`testNodeNavigation (check_openshift.TestOpenshift)` still needs fixing. I'll push it here once I find the solution (draft for now - I am opening it so I won't forget about it ;) )

tests: CentOS can manage docker storage

---

test/verify/machineslib.py

Since it is Fedora 30 with updates-testing repos.
Fixes https://github.com/cockpit-project/bots/pull/127

tests: Fedora testing does not support `Download an OS`

---

pkg/storaged/storage-controls.jsx

They always filled the whole row, which is wrong.  Te text was left
aligned, which made it look correct.  Now the text is centered, and it
also looks wrong.
Wrapping them all in a extra `<div>` seems to magically fix the layout.

storage: Fix layout of StorageLink:s in content tabs

---

.gitignore
.travis.yml
configure.ac
containers/unit-tests/setup.sh
po/Makefile.am
po/its/polkit.its
po/its/polkit.loc
src/bridge/Makefile.am
src/bridge/org.cockpit-project.cockpit-bridge.policy.in
src/ws/Makefile-ws.am
src/ws/cockpit.appdata.xml.in
tools/cockpit.spec
tools/debian/control

intltool has been deprecated for a while [1], in favor of gettext being
able to handle XML and other files natively.
Use xgettext/msgfmt for extracting/merging translations of our AppStream
metadata and polkit policy. Use W3C ITS [2] files instead of the
intltool-specific `<_tag>` format. gettext ships appstream ITS files by
default; copy the polkit ones from gettext 0.20 for now to avoid having
to build-depend on policykit-1 just for these on Debian/Ubuntu.
This avoids having to build intermediate files, copy the original files
around, and keep their format valid (without mutilated tags). It also
drops the intltool dependency. Add an explicity gettext build dependency
(which previously was transitive through intltool).
This also drops the post-processing seddery of the polkit file; …

ws, bridge: Move AppStream metadata and polkit i18n from intltool to gettext

---

src/ws/login.js

When using two factor authentication (Google Authenticator) I noticed that the verification code field wasn't focused although code existed to do that precisely. Tested in Chrome/Firefox in Windows and Debian, focus didn't work properly.
The issue is that the code to focus the element is executed before the element appears on screen, which from experience and testing proved to not work at all. I removed this line of code and placed one that focuses the element immediately after it appears. Tested to work in the same systems.

"Autofocus" on "Verification Code / Conversation Input"

---

src/tls/connection.c

gnutls returns a negative error code as a return value from its _send()
and _recv() calls.  Check for negative values instead of comparing to
-1.

tls: handle gnutls error codes correctly

---

src/base1/Makefile.am

It can happen that dist/base1/ does not yet exist when
react-core-base.css gets built.

base1: Fix race condition in building dist/base1/react-core-base.css

---

doc/branding.md
src/branding/centos/branding.css
src/branding/debian/branding.css
src/branding/default/branding.css
src/branding/fedora/branding.css
src/branding/kubernetes/branding.css
src/branding/registry/branding.css
src/branding/rhel/branding.css
src/branding/scientific/branding.css
src/branding/ubuntu/branding.css

Fixes #12984
@garrett @andreasn you know better what would be the right solution. I just picked the most obvious one - comments?
@iokaravas  can you verify it fixes your issue?
Before:
After:

branding: Cover login page with background image

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

This should also fix a flake in our tests:
```
File "/usr/lib64/python3.7/unittest/case.py", line 59, in testPartExecutor
yield
File "/usr/lib64/python3.7/unittest/case.py", line 628, in run
testMethod()
File "/home/skobyda/Work/cockpit/test/verify/machineslib.py", line 1340., in testCreate
self.browser.wait_visible("#create-new-vm:disabled")
File "/home/skobyda/Work/cockpit/test/common/testlib.py", line 361, in wait_visible
self.wait_present(selector)
File "/home/skobyda/Work/cockpit/test/common/testlib.py", line 352, in wait_present
self.wait_js_func('ph_is_present', selector)
File "/home/skobyda/Work/cockpit/test/common/testlib.py", line 346, in wait_js_func
self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
File …
```

machines: Fix disabling of Create VM button

---

src/tls/test-server.c

The tls unit tests often fail under valgrind. Quadruple the timeout so
that they work more reliably.

tls: Increase timeout in HTTPS response test

---

pkg/systemd/services.html

systemd: Specify context for `After`

---

src/tls/connection.c

This doesn't initialize the ws instance, it's done in
connection_thread_main().

tls: Fix comment on connection_handshake()

---

test/verify/check-system-info

Our new Ubuntu 19.10 test image now also has chrony installed through a
transitive Recommends:, like on Debian. This makes timesyncd not start,
so remove chrony for the timesyncd tests.
See https://github.com/cockpit-project/bots/pull/151

test: Fix NTP tests on Ubuntu 19.10

---

pkg/machines/app.jsx
pkg/machines/components/libvirtSlate.jsx
pkg/machines/helpers.js
pkg/machines/index.js
pkg/machines/libvirt-dbus.js
pkg/machines/reducers.js

Should fix several race conditions in our tests.
Increasingly we began to encounter errors in our tests when not all libvirt resources (like storage pools, interfaces...) were loaded but our tests already tried to use them. This resulted in test failure.
Waiting for loading of libvirt resource does not take more than a few fractions of second (no matter number of resources or network speed).

machines: Wait until all libvirt resources are loaded

---

src/ws/cockpit-wsinstance-http-redirect.service.in
src/ws/cockpit-wsinstance-http-redirect.socket.in
src/ws/cockpit-wsinstance-http.service.in
src/ws/cockpit-wsinstance-http.socket.in
src/ws/cockpit-wsinstance-https.service.in
src/ws/cockpit-wsinstance-https.socket.in
test/verify/check-connection

Use the stronger `BindsTo=` for the wsinstance units towards
cockpit.service. With that, these units get stopped also when
cockpit-tls exits by itself (idle timeout, crash, etc.), and not just
with an explicit `systemctl stop cockpit.service`.
Spotted in PR #12972

ws: Stop ws instance socket when cockpit.service stops by itself

---

src/bridge/test-httpstream.c

The tests don't need a system SSL database, but if it's not present,
they fail with
(test-httpstream:12379): GLib-Net-WARNING **: 08:40:04.701: couldn't load TLS file database:
Failed to open file ?/etc/ssl/certs/ca-certificates.crt?: No such file or directory
Trace/breakpoint trap (core dumped)
Ignore the warning, to avoid a build dependency on ca-certificates.

bridge: Ignore missing system SSL cert database in unit tests

---

pkg/systemd/host.js
test/verify/check-system-info

This is often being used for ASCII art or other indentation, and Cockpit
shows it in a `<pre>` for that reason. Do what the shell does and leave
leading whitespace intact.
Fixes #11680

systemd: Don't trim initial motd whitespace

---

test/common/testlib.py

Previously the "Unexpected journal messages" message appeared above all
unexpected messages and the stack trace, which makes it visually hard to
spot when just looking at the end. Change it to become part of the
actual exception message and clarify it a bit.
Fixes #11726

test: Clarify test failures on unexpected journal messages

---

src/ws/cockpitauth.c

Split out from #11421. This is super-trivial, but let's get it out of the way.

ws: Use g_auto in cockpit_auth_login_async()

---

test/verify/machineslib.py

There was a beautiful race condition in tests:
First the file permissions of /run/libvirt/libvirt-socked were
changed and then we checked (and waited) if libvirtd service was
started.
In some cases however this would lead to situation where we changed
permissions before libvirtd was started, and the start of libvirtd
would overwrite our file permission change.
This should fix ubuntu-stable specific flake:
https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12988-20191016-130101-8ccb0965-cockpit-project-cockpit--ubuntu-stable/log.html#230-2

machines: Fix ubuntu-stable race condition in tests

---

po/Makefile.am

po/POTFILES.{appstream.polkit}.in contain file names relative to the
source directory. With a separated build dir (used by bots/po-refresh)
these rules failed to find their input files.
Change to the source directory so that xgettext can find them, but still
put the output into the build directory.

po: Fix update-po for separate build dir

---

test/selenium/selenium-firewalld.py

After enabling the firewall, there is often "1 Active Zone". Adjust the
expected string to work for that, too.
Follow-up to commit 24879ab5.

test: Fix selenium firewall tests

---

src/websocket/test-websocket.c
src/websocket/websocket.c
src/websocket/websocketconnection.c
src/ws/cockpitauth.c
src/ws/test-auth.c

The headers we look at should all be fine with plain ASCII values. But
it can happen that reverse proxies add extra headers with non-ASCII
values. UTF-8 should be safe with our code also for the headers Cockpit
looks at by itself, so allow these.
Fixes #12192

websocket: Allow UTF-8 header values

---

test/verify/check-realms

freeipa-client got removed from debian-testing image for the time being.
See https://github.com/cockpit-project/bots/pull/186 for details.

test: Skip FreeIPA tests on debian-testing

---

test/selenium/testlib_avocado/seleniumlib.py

Wait until the key actually got added, instead of immediately tearing
down the browser. The latter does not get far enough to actually add the
key (at least when running under Edge).
-----
Example: https://209.132.184.41:8493/logs/pull-12972-20191027-104444-8ed348fd-cockpit-project-cockpit--fedora-30-selenium-edge/log.html#2  → this happens in *every* current Edge test, and is trivial to reproduce locally

test: Fix race condition in test15BaseSSHKeyAdded

---

pkg/lib/cockpit-components-listing.jsx
pkg/lib/listing.less
pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css
test/selenium/selenium-firewalld-zones.py
test/selenium/selenium-firewalld.py
test/verify/check-networking-firewall

For zones:
For zones with cockpit:
For services (button moved to expander):
For the cockpit service (expander + confirmation):

firewall: more clicks before deleting a zone or service

---

webpack.config.js

The `const expandedRow` in the ES6 variant of PF4's collapsible.js
upsets Edge 16, it cashes with
SCRIPT1003: Expected ':'
Our build system seems to favor dist/esm (where PF4 ships its ES6
modules) over dist/js (where they ship pre-babelled ES5, which works),
but we generally skip running babel on node_modules. Add react-table to
the whitelist so that we avoid the problematic arrow function in our
generated webpacks that trigger the Edge bug.
Fixes #12864
---
Split out from PR #13052, as fixing the selenium tests takes way more work than anticipated.

build: Fix Edge crash on PF4's collapsible decorator

---

pkg/machines/actions/provider-actions.js
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/deleteDialog.jsx
pkg/machines/components/vm/vm.jsx
pkg/machines/components/vm/vmActions.jsx
pkg/machines/libvirt-dbus.js

If user deletes a VM and also decides to remove it's associated
storages, storage pools containing these storages are not refreshed,
thus deletion is not reflected in the UI.
Also if user creates a new VM with it's own new storage, this storage
change is not represented in the UI.
Fix this.

machines: Refresh default storage pool after VM creation or deletion

---

configure.ac
tools/cockpit.spec
tools/debian/control

We don't support building against libssh 0.7 (or older) any more. We
just barely support 0.8.0 on Ubuntu 18.04 (which already has some
serious deficiencies)
Fixes #11052

Bump libssh dependency to >= 0.8

---

pkg/machines/actions/provider-actions.js
pkg/machines/components/libvirtSlate.jsx
pkg/machines/libvirt-common.js
pkg/machines/selectors.js

After libvirtd service is stopped, we call startEventMonitorLibvirtd() which in turn calls delayPolling(). This delays polling of libvirt resources by 10 seconds. However if libvirtd service is not started in next 10 seconds, polling of libvirt resources is called nevertheless, which will result in a failure.
This created a bug: when user turned off libvirtd service and didn't start it in next 10 seconds, they would never get resource polled. It was also causing a flake in tests if libvird service took longer than 10 seconds to start.
Fix this by making delayPolling recursively call itself until libvirtd service is running again. Thus it will loop until it can poll libvirt resources.
This should fix LibvirtTest flakes:
https://209.132.184.41:8493/logs/pull-12972-20191014-130202-133aef01-co …

machines: Fix libvirtd service restart bug/flake

---

po/Makefile.am
po/cs.po
po/ko.po
po/pl.po
po/uk.po

This is provided by `python3-zanata-client`.
Needs https://github.com/cockpit-project/cockpituous/pull/298
(no `bots` label for now, since I need to deploy new task container first)

po: Use `zanata` instead of `zanata-cli`.

---

test/verify/check-services

In particular, the "sssd" service seems to fail sometimes on Debian,
which would take the first row.
aachen (v) - Seinen Namen ändern, um eher dranzukommen.

test: Aachen the failing service so that it is first

---

pkg/lib/cockpit-components-empty-state.css
pkg/lib/cockpit-components-empty-state.jsx
pkg/systemd/host.css
pkg/systemd/logs.html
pkg/systemd/logs.js
test/verify/check-journal

I wanted to do implement https://github.com/cockpit-project/cockpit/issues/8271 but there is problem that if someone jumps to logs from service which did not log anything, only empty page was shown.
@andreasn can you please review design-wise? And @KKoukiou can you please check the code?
I did new component, because I was implementing this `empty state` a few times already and we still miss it on many places, so I hope it makes it easier to use on other places as well.
No tests yet, I'll adjust them in meantime.
This PR implements:
Showing that something is loading: (before it was just one line of text saying `Loading...` on the top left)
Properly showing that there are no logs: (before it was just blank screen)
When there are no logs, but there are more to be loaded: (Before it shown …

logs: Show empty state when no logs found

---

pkg/machines/libvirt-dbus.js

How to reproduce:
1. Attach NIC of type which doesn't require source (e.g. NIC type 'user' for
session connection VM)
2. Go to NIC Edit dialog, change NIC type to something which requires
source
Expected result: NIC configuration is changed
Actual result: Oops, Cannot read property 'remove' of undefined

machines: Fix NIC edit for NICs without source

---

test/selenium/run-tests
test/selenium/selenium-machines-basic.py
test/selenium/selenium-machines-storage-pool.py

These work again since fixing issue #12864 in commit 6cee1e455.
Skip two tests which fail very often with Edge, with issue references.
This reverts commit fcdca949ef26ad5ea8c67fda19f4662194a30e4c.

Revert "test: Skip Machines selenium tests on Edge for now"

---

pkg/systemd/init.js
pkg/systemd/services.jsx
test/verify/check-services

If a unit fails that we don't show in any of the tabs, such as
foo.mount, we should also ignore that it has failed.  Otherwise, we
warn people about things that they can't find.

systemd: Ignore failures of hidden units

---

test/common/testlib.py
test/verify/check-login

Check that users with a SELinux role other than unconfined_u (in
particular, user_u and sysadm_u) can log into Cockpit. This validates
the various bug dependencies of
https://bugzilla.redhat.com/show_bug.cgi?id=1727382
and ensures that they stay fixed in the future.

test: Check cockpit login with SELinux restricted user

---

pkg/systemd/init.js
pkg/systemd/service-details.jsx

Not all unit files that contain a "@" character are templates.  The
systemd-cryptsetup-generator writes those, for example.

systemd: More robust detection of template unit files

---

src/common/cockpitmachinesjson.c

This got obsoleted in commit 3986d994f, and commit eae85c6b1d12e
migrated the old file into /etc/cockpit/machines.d/. That commit has
been in all supported OS releases for a long time now.
Commit a1e7a09 already removed the migration.

common: Stop reading /var/lib/cockpit/machines.json

---

.gitignore
src/tls/Makefile-tls.am
src/tls/connection.c
src/tls/main.c
src/tls/server.c
src/tls/server.h
src/tls/socket-activation-helper.c
src/tls/socket-io.c
src/tls/socket-io.h
src/tls/test-server.c
src/tls/test-socket-activation-helper.sh
src/tls/testing.h
src/tls/utils.h
src/tls/wsinstance-factory.c
src/tls/wsinstance-start.c
src/ws/Makefile-ws.am
src/ws/cockpit-wsinstance-https-factory.socket.in
src/ws/cockpit-wsinstance-https-factory@.service.in
src/ws/cockpit-wsinstance-https.socket.in
src/ws/cockpit-wsinstance-https@.service.in
src/ws/cockpit-wsinstance-https@.socket.in
src/ws/cockpit.service.in
src/ws/system-cockpithttps.slice
test/verify/check-connection
tools/cockpit.spec
tools/debian/cockpit-ws.install

tls: Run separate cockpit-ws instance for each client certificate

---

test/common/testlib.py
test/verify/check-machines-dbus

Lets see what tests have to say to this.
This is very likely culprit why testCreate in Firefox is failing - the input is blured before the last character is set up. It is just timing thing.
My thinking is that user also would not blur output, so we should not rely on that.
Introduced [here](https://github.com/cockpit-project/cockpit/commit/18f54c12422a90108d932d3ae33e1ce1719c106d)

test: Do not blur input after setting up text

---

test/verify/check-docker

This has been replaced with abrt-journal-core since Fedora 26, and does
not work any more since
https://github.com/abrt/abrt/commit/77653d7a367a756e796f5b820d9bea3c8feb117e

test: Stop using obsolete abrt-ccpp

---

test/README.md
test/verify/check-multi-os

Testing against one ancient Fedora is enough for ensuring protocol
backwards compatibility; there is no need to drag around yet another
1.5 GB image.
Fedora 23's cockpit frames structure changed quite a bit, update the
tests accordingly.
Since Fedora ≥ 23's cockpit, the `.curtains-ct` is only present in the
topmost (shell) iframe of the host, not any more in the system iframe.
Drop that check.
Drop some obsolete expected messages, they don't seem to happen on
Fedora 23 any more.
----
After this lands, and gets backported to stable branches, we can drop the "stock-fedora" image from bots.

test: Use only fedora-23-stock in check-multi-os

---

src/tls/test-server.c

I have seen this error, but I guess returning sizeof(buf)-1 bytes is alright.
```
ERROR:src/tls/test-server.c:228:assert_https_outcome: assertion failed (len < sizeof (buf) - 1): (4095 < 4095)
```
(The test did hang at this point.  That's not expected, right?)

tls: Allow full buffer read in test.

---

pkg/lib/cockpit-components-install-dialog.jsx
pkg/storaged/mdraids-panel.jsx
pkg/storaged/overview.jsx
pkg/storaged/storage-controls.jsx
pkg/storaged/storage.css
pkg/storaged/things-panel.jsx
pkg/storaged/utilsx.jsx
pkg/storaged/vdos-panel.jsx
pkg/storaged/vgroups-panel.jsx
test/verify/check-storage-basic
test/verify/check-storage-hidden
test/verify/check-storage-lvm2
test/verify/check-storage-mdraid
test/verify/check-storage-multipath
test/verify/check-storage-raid1
test/verify/check-storage-resize
test/verify/check-storage-unused
test/verify/check-storage-vdo
test/verify/storagelib.py

The reasons for doing this is to remove clutter from the UI for things that people don't have and don't care about.  For example, if you are not interested in VDO, the empty VDO panel is just distracting and uses space. With this, adding one more entry to the "Create" menu has little cost, and to show this, I have added "Create Loop Device", which is not something that we would want to have a dedicated panel for, I guess.

storage: Collect all software devices into one panel

---

test/README.md
test/verify/check-multi-os

Testing against one ancient Fedora is enough for ensuring protocol
backwards compatibility; there is no need to drag around yet another
1.5 GB image.
Fedora 23's cockpit frames structure changed quite a bit, update the
tests accordingly.
Since Fedora ≥ 23's cockpit, the `.curtains-ct` is only present in the
topmost (shell) iframe of the host, not any more in the system iframe.
Drop that check.
Drop some obsolete expected messages, they don't seem to happen on
Fedora 23 any more.
Cherry-picked from master commit f9836425e6.

test: Use only fedora-23-stock in check-multi-os [rhel-8.1]

---

test/common/cdp.py
test/common/chromium-cdp-driver.js
test/common/firefox-cdp-driver.js
test/common/testlib.py
test/run
test/verify/check-connection
test/verify/check-dashboard
test/verify/check-embed
test/verify/check-keys
test/verify/check-login
test/verify/check-multi-machine-key
test/verify/check-multi-os
test/verify/check-realms
test/verify/check-setroubleshoot
test/verify/check-sosreport
test/verify/check-terminal
test/verify/run-tests

Firefox CDP is only partially implemented and some major features are missing. Also `chrome-remote-interface` misses some features on Firefox. Therefore I've created new cdp-driver which contains some hacks and workarounds. Since it uses very small subset of cdp protocol, it could be used for chrome as well, but lets keep also the proper driver and hopefully one day we can use that one for all browsers.
How to run this: (see note below)
prerequisite: Firefox browser (tested with current F31 Firefox build `69.0.1-3`)
`TEST_BROWSER=firefox ./test/verify/check-pages TestPages.testBasic -vt`
TODO:
[1](https://209.132.184.41:8493/logs/pull-12971-20191029-135353-b0973c96-cockpit-project-cockpit--fedora-30-firefox/log.html#105-2) [2](https://209.132.184.41:8493/logs/pull-12971-20191105-091919-295 …

test: Implement Firefox testing with CDP

---

test/verify/check-keys

In #13038 alerts were changed from PF3 component to PF4 but this test
was forgotten and not updated.

test: Fix wrong alert selector

---

test/README.md
test/verify/check-multi-os

Testing against one ancient Fedora is enough for ensuring protocol
backwards compatibility; there is no need to drag around yet another
1.5 GB image.
Fedora 23's cockpit frames structure changed quite a bit, update the
tests accordingly.
Since Fedora ≥ 23's cockpit, the `.curtains-ct` is only present in the
topmost (shell) iframe of the host, not any more in the system iframe.
Drop that check.
Drop some obsolete expected messages, they don't seem to happen on
Fedora 23 any more.
Cherry-picked from master commit f983642.

test: Use only fedora-23-stock in check-multi-os [rhel-8-appstream]

---

test/README.md
test/verify/check-multi-os

Testing against one ancient Fedora is enough for ensuring protocol
backwards compatibility; there is no need to drag around yet another
1.5 GB image.
Fedora 23's cockpit frames structure changed quite a bit, update the
tests accordingly.
Since Fedora ≥ 23's cockpit, the `.curtains-ct` is only present in the
topmost (shell) iframe of the host, not any more in the system iframe.
Drop that check.
Drop some obsolete expected messages, they don't seem to happen on
Fedora 23 any more.
Cherry-picked from master commit f9836425.

test: Use only fedora-23-stock in check-multi-os [rhel-7.8]

---

test/verify/check-journal

Fedora CoreOS does not have Python installed. Use logger(1) instead,
which also makes things simpler.

test: Drop python3 requirement in check-journal

---

pkg/playground/preloaded.js

It does not exist on e. g. Fedora CoreOS. Just call the `hostname`
program both in the playground page and in the corresponding test
(`testShellPreload`), to ensure they will be identical.

playground: Don't rely on /etc/hostname

---

test/verify/check-system-info

All our supported OSes have a much newer systemd version, so ensure that
hostnamed behaves as intended.

test: Drop obsolete hostnamed hack

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

When user creates a new VM and spends some time filling in all the details, after clicking Create, modal is closed with error message from libvirt "this vm name is already used" resulting in them loosing all the data they have filled into the modal.
We can check this in the UI.

machines: Don't create VM with name which is already used

---

pkg/selinux/setroubleshoot-view.jsx
pkg/selinux/setroubleshoot.css

Fixes #11602
@garrett what do you think? I put it into flex - the text is one box and the button (or the text `Unable to apply this solution automatically`) another. Would it be better if only the first line of the text and the button would be in flex? (Sounds silly, but when you check the source code, the first line and the second line are two separate elements)
On wide screen:
On phone:

selinux: Do not wrap text around button on small screens

---

pkg/machines/machines.less

This got introduced in 687b83ac7e.

machines: fix typo in CSS which broke ToastNotifications

---

doc/guide/authentication.xml

* Project Atomic was superseded by Fedora CoreOS.
* It's not a "docker" container, it's just a container.
* Speaking about "the default" is misleading, as the container isn't
installed by default. But we only support the container there, not
trying to squeeze the web server into an OSTree overlay.

doc: Update cockpit/ws documentation

---

test/common/testlib.py

Drop a debugging leftover from the firefox CDP introduction.

test: Reenable screenshots on failures

---

src/bridge/cockpitfslist.c
src/bridge/cockpitfswatch.c

When GFileMonitor uses inotify, it asynchronously cancels the monitor on
disposing. This races with creating a new monitor somewhere else, and
frequently runs into deadlocks when the cancellation of the old and the
creation of the new monitor both try to acquire their internal mutex.
See https://gitlab.gnome.org/GNOME/glib/issues/1941 for details.
Interestingly there was a related bug in 2017
(https://bugzilla.gnome.org/show_bug.cgi?id=740491) for which we still
had a workaround in fslist. That exact same workaround applies to this
fswatch  deadlock as well.
Fixes #13146

bridge: Explicitly cancel fswatch GFileMonitor before unreffing

---

src/tls/test-server.c

This may help with coverity's NEGATIVE_RETURNS complaints.

tls: Assert successful open() in test-tls-server

---

pkg/storaged/client.js
pkg/storaged/content-views.jsx
pkg/storaged/dialog.jsx
pkg/storaged/format-dialog.jsx
pkg/storaged/fsys-panel.jsx
pkg/storaged/fsys-tab.jsx
pkg/storaged/lvol-tabs.jsx
pkg/storaged/storage-controls.jsx
pkg/storaged/utils.js
pkg/storaged/vdo-details.jsx
pkg/storaged/warnings.jsx
src/bridge/cockpitdbuscache.c
test/verify/check-storage-format
test/verify/check-storage-hidden
test/verify/check-storage-iscsi
test/verify/check-storage-luks
test/verify/check-storage-lvm2
test/verify/check-storage-mdraid
test/verify/check-storage-mounting
test/verify/check-storage-msdos
test/verify/check-storage-partitions
test/verify/check-storage-resize
test/verify/check-storage-used
test/verify/check-storage-vdo
test/verify/storagelib.py

Demo: https://www.youtube.com/watch?v=g8_zFpi9Cz0
Demo of "Format" dialog: https://youtu.be/FjgB9SFCR4g
Cockpit no longer offers the confusing "Default" choice when mounting a filesystem.  Now every new filesystem requires the specification of a mount point.  Additionally, Cockpit hides the distinction between configuration (/etc/fstab) and run-time state (/proc/mounts).  Changes made in Cockpit always apply to both the configuration and run-time state.  When configuration and run-time state differ from each other, Cockpit will warn about that and will let you bring them back in sync.

storage: No default mounting

---

pkg/machines/components/storagePools/storagePoolDelete.jsx

Remove duplication of list of VMs using storage pool in a deletion tooltip.

machines: Fix duplication in a list of VMs using a pool

---

pkg/systemd/host.css
pkg/systemd/logs.html
pkg/systemd/logs.js
pkg/systemd/reporting.jsx
test/verify/check-docker
test/verify/check-journal
test/verify/files/mock-bugzilla-server.py
test/verify/files/mock-faf-server.py
tools/cockpit.spec

The current problem reporting workflow only supports sending micro-reports to FAF (now ABRT Analytics) using a CLI utility. ABRT itself can send reports to more places: Bugzilla (Red Hat), MantisBT (CentOS), and whatever new shiny places that might be added in the future. Moreover, with ABRT, the user can send core dumps to a remote retracing server, to make stack traces in reports more useful.
Aside from not supporting all the different reporting workflows, running reporting commands directly might result in prompts being shown in the shell with no way for a remote user to respond to those.
Cue reportd, a D-Bus service that allows reporting plugins and the end user to communicate. The goal of this PR is to integrate it into Cockpit for more complete reporting capabilities.
Some basic …

systemd: logs: Use reportd for reporting problems

---

pkg/systemd/hwinfo.jsx
test/verify/check-system-info

systemd: Support `mitigations=` kernel parameter to disable SMT

---

pkg/systemd/kernelopt.sh
test/verify/check-system-info

On Fedora CoreOS and other rpm-ostree based OSes, the kernel config is
inside the image, and not directly accessible through editing files,
calling grubby, or similar. Instead, `rpm-ostree kargs` creates a new
overlay with the changed arguments.
Add this to kernelopt.sh and enable the full SMT mitigation test case on
fedora-coreos.

systemd: Add rpm-ostree backend to CPU mitigations

---

pkg/storaged/fsys-tab.jsx
test/verify/check-storage-mounting

We should ignore the clear text device when formatting a crypto
backing device when looking for existing duplicate mount points.

storage: Fix duplicate mount point handling with encryption

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/storagePools/storagePool.jsx
pkg/machines/components/storagePools/storageVolumeCreate.jsx
pkg/networkmanager/firewall.jsx
pkg/storaged/storage-controls.jsx

If you put OverlayTrigger over a DISABLED button, then overlay tooltip
won't show up. The Reason is probably that a disabled button doesn't
have a pointer event, therefore OverlayTrigger doesn't know when
to showa  tooltip.
Fix this by setting pointerEvents to "none", which will "trigger event
listeners on parent element".

Fix broken OverlayTrigger tooltips

---

pkg/machines/components/networks/network.jsx
pkg/machines/components/networks/networkOverviewTab.jsx
pkg/machines/components/storagePools/storagePoolDelete.jsx
pkg/machines/components/storagePools/storagePoolOverviewTab.jsx
pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

Transient resources are resources which exist only while they are running and cease to exists once they stop running/are deactivated.
Disable or hide functionalities which would result in error for transient resources:
- Autostart
- Deletion
@andreasn @garrett WDYT about these design changes?
Heres screenshot of **persistent** virtual network:
And **transient** virtual network
(changes shown in screenshot for virtual network are the same also for storage pools).

machines: Support transient virtual networks and storage pools

---

pkg/realmd/operation.html
pkg/realmd/operation.js

realm: Don't show error alert on an freshly open 'Join Domain' dialog

---

pkg/selinux/org.cockpit-project.cockpit-selinux.metainfo.xml

I didn't test this locally since I am not sure how to.
Anyhow, if you go to Applications and click SELinux it tries to go to `/setroubleshoot` but it should be `/selinux/setroubleshoot`. Thus rendering a Not Found page.

Fix SELinux launchable link

---

src/base1/cockpit.js
src/ws/login.css
src/ws/login.html
src/ws/login.js

I was working on session timeout and I needed to show a info alert on the login page. We had only support for error alerts. So I decided we could just use the same style of alerts on the login page as we do in the rest of the Cockpit.
Before:
Now:
Also I am sending here showing of info messages. Nothing uses it yet, but I think it is simple enough to review. Looks like this:
no-test since it needs Closes and very likely breaks tests anyway. So running F30 just to get list of what I need to fix.
@garrett WDYT? The css is mostly stolen from PF4 alerts with tiny tweaks. I guess that part of it is not needed?

Standard alerts on login page

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/memorySelectRow.css
pkg/machines/components/memorySelectRow.jsx
pkg/machines/components/vm/memoryModal.css
pkg/machines/components/vm/memoryModal.jsx
src/base1/patternfly-overrides.less
test/verify/check-machines-dbus
test/verify/machineslib.py

This allows us to remove the text bellow the input fields for
recommended and minumum values, since the slider incorporates these
information.
The tests had to be adjusted to ensured that the limits on the sliders
are respected.

machines: add sliders in Create VM dialog for memory and disk size

---

tools/cockpit.spec

Fix error like:
Installed (but unpackaged) file(s) found: /usr/libexec/cockpit-wsinstance-factory

spec: Remove cockpit-wsinstance-factory in specfile

---

test/verify/machineslib.py

I noticed that almost all `fedora-30/firefox` tests failed on `testCreate` lately. ([example](https://209.132.184.41:8493/logs/pull-13218-20191129-165151-c6218999-cockpit-project-cockpit--fedora-30-firefox/log.html#74-2))
This is due to race in Firefox, that input is blurred before the
last character is written.
In this specific test there was `value_check=False` because if user
inputs value that is bigger than maximum possible value it is rounded
down. This however happens on blur.

test: Check for value in input before blurring it

---

pkg/packagekit/autoupdates.jsx
test/verify/check-packagekit

RHEL 8.2's dnf-automatic defaults to `OnCalendar=*-*-* 06:00` now,
recognize this.
-----
This blocks https://github.com/cockpit-project/bots/pull/292

packagekit: Recognize "daily" OnCalendar= specification for dnf-automatic  timer

---

src/tls/connection.c
src/tls/connection.h
src/tls/main.c
src/tls/server.c
src/tls/server.h
src/tls/socket-activation-helper.c
src/tls/socket-io.c
src/tls/socket-io.h
src/tls/test-server.c
src/tls/wsinstance-start.c

This lets us remove all sockaddr_un handling from the code and avoids an
issue when the pasted-together paths overrun the (relatively small)
buffer.
Comments welcome.  Note that bindat_printf() is never used because we only bind to static example paths (ie: hardcoded key fingerprints) from the socket activation helper.
Fixes #13220

tls: add connectat() and bindat()-style wrappers

---

src/base1/test-dbus.js
src/base1/test-machines.js
src/base1/test-permissions.js
src/bridge/Makefile.am
src/bridge/bridge.c
src/bridge/cockpitdbusconfig.c
src/bridge/cockpitdbusinternal.h
src/common/cockpitmachinesjson.c
src/ws/test-server.c

Add a new cockpit.Config.Get{String,UInt}() methods on the internal
bridge D-Bus server that provides an interface to
`cockpit_conf_{string,uint}()` for JavaScript.
This will be used for implementing the customization of the automatic
logout on idle.

bridge: Add internal D-Bus API to read cockpit.conf

---

doc/guide/cert-authentication.xml
test/verify/check-realms

Firefox recently started to require the "Key Usage" extension for TLS
client certificate authentication. Update the example in the
documentation accordingly. Also update the test -- while curl does not
require this, it's useful to have a "proper" certificate for interactive
testing.
Doc preview: https://piware.de/tmp/cockpit-certauth/cert-authentication.html

test, doc: Set Key Usage extension for client cert authentication

---

src/ws/session.c

The remote IP is not a reliable piece of information.  NAT, VPNs, or
reverse proxies all destroy the actual IP of the browser's machine.
Since we use a reverse proxy (cockpit-tls) by default, the "remote peer
address" has lost all meaning, so let's just stop exporting it.
Also, `pam_rhosts` isn't in any PAM stack by default (particularly not
in cockpit's), and the whole concept of /etc/hosts.equiv is just
painfully insecure these days; so almost nobody should actually notice
the difference. For those people who actually *do* use `pam_rhosts`,
this fixes the wrong/dangerous information that every cockpit session
originates from localhost. It's better to not set this field at all to
point out that it's not available/not reliable.
There are some ideas how to recover the concept of "remote …

ws: Stop setting PAM_RHOST

---

src/tls/test-server.c

It might be possible that one of the exiting threads hasn't deleted the
certificate file yet by the time the loop runs (causing the loop to
successfully exit) but erases it by the time of the assert, while all
the while the final thread hasn't created it again yet.
This extremely unlikely race was found after 30 minutes of grinding on
my laptop vs. 10 webpack threads.
Avoid the issue by just using the loop itself as the verification.
If we hit the retry limit we've failed, but if we see the file at any
point before, then we're successful.
The "alternate" approach doesn't suffer this race.

tls: fix another race in the test-server unit test

---

src/ws/session-utils.c
test/verify/check-login

`LOGIN_PROCESS` seems to be intended to be used for login(1)-style
processes that are showing a login prompt on a given tty.  One can see
this from the current code in the output of `who -a`.
Use `LOGIN_USER` instead.
Additionally, set the "line" field to "web console" to provide a hint
about the nature of the login.

cockpit-session: correct utmp entry writing

---

src/tls/test-server.c

This testcase is having a lot of spurious failures, but apparently only
while running under valgrind.

tls: skip parallel client-cert test under valgrind

---

containers/ws/atomic-install

docker does not set the `$container` env variable.

containers/ws: Unbreak for docker

---

pkg/lib/cockpit-components-dialog.css
pkg/lib/cockpit-components-dialog.jsx
test/verify/check-journal
test/verify/check-networking-firewall
test/verify/check-realms
test/verify/check-system-info

This will make them scroll properly.
Not that with this change, the ".modal" DOM element is no longer a
child of the #cockpit_modal_dialog div.
Fixes #13193

lib: Use patternfly-react Modal components to construct our dialogs

---

pkg/dashboard/index.html
pkg/docker/index.html
pkg/lib/machine-change-auth.html
pkg/networkmanager/index.html
pkg/playground/jquery-patterns.html
pkg/shell/index.html
pkg/systemd/logs.html
pkg/systemd/services.html
pkg/users/index.html

React was complaining about links without href having tabindex; adding a role to the link of link fixes the issue.
I decided to replicate that across our HTML files too.
This change affects all of the instances where we have `<a tabindex=0>` in our HTML files, with the exception of the system overview page. That has been dealt with in the overview PR @ https://github.com/cockpit-project/cockpit/pull/13186/commits/9ebb2c1a2a097b6944f9c1d04f55b43c66ee6e18.

a11y: Add role=link to links without href

---

test/verify/check-realms

Terminating the session is not synchronous. Wait until it is gone before
starting the next test, to avoid do_test() still catching the session
from the previous call.
Fixes #13267

test: Fix race condition in testClientCertAuthentication

---

test/verify/check-machines-dbus
test/verify/machineslib.py

There is no vm-[VM_NAME]-disks-[TARGET]-target element. Thus checking
if it's not present would always result in check passing and not guard
against any bugs.
Check for existing vm-[VM_NAME]-disks-[TARGET]-device instead.

tests: Fix machines testDetachDisk test

---

test/verify/check-networking-team

The NetworkManager-team package is not present any more in current
Fedora CoreOS images.

test: Skip NetworkManager-team tests on fedora-coreos

---

doc/man/cockpit.conf.xml
src/ws/cockpithandlers.c
src/ws/login.css
src/ws/login.html
src/ws/login.js
test/verify/check-login

This is very WIP, there are still missing features, needs cleaning up... but opening so we can get some styling done.
We need bell icon and not info icon as now is present. Also there is border around the alert body and I haven't yet figure out how to fix it and it also needs to float in the middle of page with some margins.
(for some reason I cannot open draft PR)

login: Show content of /etc/issue on login screen

---

doc/man/cockpit.conf.xml
pkg/shell/base_index.js
pkg/shell/index.html
src/ws/login.js
test/verify/check-menu

Settable in `cockpit.conf`.
Default is 15 minutes. Disable by setting to 0.
For last 30 seconds a dialog is opened that does counting down. Session can be kept only by clicking the 'Continue Session' in this stage. Otherwise session is kept alive by user doing either of `mousemove`, `mousedown`, `keypress`, `touchmove`, `onscroll`.
When logged out, you are shown message why you were logged out:
When you did not use password to log in (SSO or so) then you would never be logged out.
@garrett had idea that we should somehow notify user that there are only 30s remaining in the session even if the user is in different tab. There were 2 ideas:
1. **Play some sound** - I did not do it for two reasons - Firstly any page that does any sounds is super annoying and I believe users hate it - lets not …

Session timeout

---

pkg/apps/application.jsx
pkg/sosreport/index.html
pkg/sosreport/sosreport.css

Tag `<center>` has been deprecated for a while (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center), instead just rely on `text-center` class. Found these while checking the hidden attributes.

Replace center tag with text-center class

---

tools/cockpit.spec

Latest selinux-policy in Fedora 30 and 31 now has this fixed in
selinux-policy proper:
- https://bodhi.fedoraproject.org/updates/FEDORA-2019-e9d8868185
- https://bodhi.fedoraproject.org/updates/FEDORA-2019-fefda9dd5e

tools: Drop SELinux policy hack on Fedora

---

test/README.md
test/common/cdp.py
test/common/testlib.py

When I was working on Firefox CDP I got used to starting browser in !headless mode. So I though we could have it as option.
SO you can run `TEST_SHOW_BROWSER=True ./test/verify/check-menu` and it starts new browser and it is visible. So when you do sit, or even when it fails and you used `-s`, the browser stays opened and you can interact with it.
It needed just one hack, as we first checked for headless chrome executable. And then I switched order in which things are cleaned, so we don't close browser before final sit is running.
And I noticed that I forgot to document TEST_BROWSER so I did that as well.
Running a few tests to see that the browser starts correctly in tasks.

Run browser visibly

---

pkg/systemd/overview-cards/motdCard.jsx

- Use state variable instead of querying the text from the widget.
- Drop the unused data-stable attribute.
- Use arrow instead of function() to eliminate the `self = this` dance.

systemd: Eliminate jQuery from motd card

---

test/verify/check-metrics

With the update to Fedora 31, current fedora-coreos image lost netcat;
see <https://github.com/cockpit-project/bots/pull/305>.
socat is available everywhere, so change the test case to use that
instead of nc. As the current fedora-coreos image does not yet have
socat, disable the network traffic test on fedora-coreos until the above
PR lands.

test: Move network graph load test to socat

---

test/verify/check-connection
test/verify/check-metrics

Now that https://github.com/cockpit-project/bots/pull/305 landed, our
fedora-coreos image has socat installed, so we can re-enable the network
load test in check-metrics (temporarily disabled in commit f3c331c).
Also adjust the comment in check-connection, as the reason for skipping
that is not the missing socat.

test: Enable socat metrics test on fedora-coreos

---

pkg/machines/libvirt-dbus.js

When getting host memory use `VIR_NODE_MEMORY_STATS_ALL_CELLS` instead of 0.

Use all cells when getting Host Max Memory

---

test/common/testlib.py

With this small patch it is possible to change `restrict` with `provision` map.
I noticed that when VM is started with `restrict=True` (which is the same as doing `./bots/vm-run --no-network`) then `composer-lorax` never initializes. I could not figure out why, so I came with this workaround. I am of course happy to close this, if someone can figure out why is this happening or if it is not a good practice to run VMs in CI with `restrict=False`.
@larskarlitski This is the last missing step and then I have working demo of testing cockpit-composer with cockpit tests :)

test: Enable selecting if machines' network should be restricted

---

pkg/systemd/overview.less

So I played with browser to see why we sometimes show too wide cards on the overview page.
I noticed that this is happening in range of widths from 874 to 1071 when dashboard is not available and from 973 to 1170 when dashboard is available. When I changed `max-width` to 800, the range where it was broken was much smaller. That way I got to 851. I figured out that 11 stands for width of scrollbar. When scrollbar is not present, then 840 would do. 851 works with and without scrollbar. The rest 200 (640 from what it used to be) is magic number for me and I haven't figured out why 840 is the number we want. I recorded video where I show it for every width in all 4 cases.
1024x768:
See video: https://youtu.be/ljXWngxtdSw (easily one of the most boring videos ever)
Fixes: …

Optimize Overview page for narrow screens around 1024 px

---

pkg/systemd/overview-cards/configurationCard.jsx
test/verify/check-system-info

testTimeServers [fails](https://209.132.184.41:8493/logs/pull-13306-20191217-174646-5648bf62-cockpit-project-cockpit--ubuntu-stable/log.html#245-2) very often, particularly on ubuntu-stable. There's something wrong with waiting properly for timedated to initialize, and the "custom NTP" options is sometimes not available even after `data-timedated-initialized` gets set.
I have some trouble reproducing this locally, so trying on the infra in parallel.

Fix testTimeServers flake

---

pkg/lib/cockpit-components-modifications.css
pkg/lib/cockpit-components-modifications.jsx
pkg/selinux/selinux-client.js
pkg/selinux/setroubleshoot-view.jsx
test/verify/check-setroubleshoot

This needs mostly to decide what exactly we want to output. Currently it outputs list of tasks, so when you take it and add
```
- hosts: localhost
tasks:
``` 
before it into file, it works just fine. But this does not seem like best practice for ansible. I should talk to someone who knows ansible and see what would be best to generate.
Also, parsing all rules is rather a lot of work, so this introduces structure and boolean parser and then we can add parser for another classes.
Looks like this: (I also switched from PF3 tabs to PF4 tabs as PF3 tabs were misbehaving a bit)
Generates script like this:
```
- name: Clean all existing selinux rules
shell: |
semanage boolean -D
semanage login -D
semanage interface -D
semanage user -D
semanage port -D
semanage node -D
semanage fcontext -D …
```

selinux: Generate ansible script

---

test/verify/check-realms

This demonstrates how to set up FreeIPA to enable two-factor
authentication. On RHEL, this is the only supported method, as there is
no google-authenticator package.
Use HOTP instead of the default TOTP as that's more predictable for an
automated test.
This has worked for a long time already, but let's make sure it stays
that way.

test: Test OTP 2FA login with FreeIPA

---

pkg/selinux/selinux-client.js
test/verify/check-setroubleshoot

Every boolean rule description has form `Allow sth to do sth`.
It however does not describe if this rule is on or off. I think it makes
sense to change `Allow` to `Disallow` when the rule is turned off.
Two boolean rules are on and one is off.

selinux: Describe state of boolean with Allow/Disallow

---

pkg/users/local.js
test/verify/check-accounts

When there is default shell set up, use that instead of always using
`/bin/bash`.
Fixes #13071
Using cockpit promise as standard promise was not playing along with `chain()`.

users: Create user with default shell if defined

---

test/verify/check-menu

I have seen a few time that this test failed with condition `20 > 20`.
Checking the test, it makes perfect sense this can happen. We reset
timer every 5 seconds and we sleep in test for 35 seconds, which in worst
case adds up to 40 seconds and in one minute timeout it indeed is 20
remaining seconds.
So it should be good enough to replace `20` with `19`, but assuming there
can be some delay while tests read the value, I dropped it down to 15.
It still safely asserts that moving mouse resets the timer, as we do
`sleep(20)` and `sleep(35)` which adds up to 55 seconds and in worst
case would still have only 10 seconds remaining.
Example failure: https://209.132.184.41:8493/logs/pull-13329-20191222-070505-798acd37-cockpit-project-cockpit--fedora-30/log.html#109-2

test: Make session timeout test a bit more robust

---

pkg/machines/components/diskAdd.jsx
test/verify/machineslib.py

Previously we were correctly calling the getDefaultVolumeFormat when
opening the dialog, thus the default format for the preselected pool was
correctly detected. However, when a user changed so some other pool,
we didn't re-detect the default format, which was problematic if the
user didn't change the preseleted format afterwards.
This commit also adjusts the relevant test which didn't fail before
because the problematic pool was first on the list so the
getDefaultVolumeFormat was correctly called in the dialog constructor.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1784304

machines: Fix default volume format detection in Disk Add dialog

---

test/common/testlib.py

We did not check naughties on last retry, which meant that if first two
runs of test failed in normal way and third failed with something that
naughty would caught, we would not catch that.
This is what is happening in https://github.com/cockpit-project/bots/pull/349

tests: Check naughties also on third retry

---

test/verify/check-services

systemd timers don't like it when the time jumps backwards, which
happens now that we actually have 2020. To avoid this problem in the
future, set an initial fixed date and cleanly boot the machine with it.
Fixes #13346

test: Avoid time going backwards in check-services timer test

---

test/verify/check-machines-dbus

We need to wait until libvirt Networks are loaded into the state before
expecting to find them in the list of available sources in the NIC edit
dialog.

test: fix testNetworkingSettings flake from Virtual Machines tests

---

pkg/systemd/overview-cards/usageCard.jsx
test/verify/check-metrics

Use a metrics1 channel to get the CPU usage information. As we have that
now anyway, replace the /proc/meminfo polling with a memory.used metric
as well.

systemd: Add CPU usage to Overview Usage card

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/libvirt-common.js
pkg/machines/libvirtUtils.js
pkg/machines/scripts/install_machine.sh
test/verify/check-machines-dbus

If user tries to configure memory params, vcpus, bootorder, autostart
or vNICs param before installing VM, they would loose changes after
installation.
The reason is that we pass all the important VM's settings to
virt-install script. We were not passing all of the mentioned options,
virt-install would default them.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1780449

machines: Fix lost of configuration changes made before installation

---

pkg/machines/components/networks/createNetworkDialog.jsx
test/verify/check-machines-dbus

After creating a new virtual network, IPv4 configuration would be
present even when "IPv6 Only" was chosen.

machines: Fix undesirable IPv4 configuration for IPv6 only network

---

pkg/machines/components/nicAdd.jsx

We would not allow vNIC creation if no network source is specified.
However 'user' network type doesn't require source.
Fix this.

machines: Fix NIC creation for 'user' network type

---

pkg/machines/actions/provider-actions.js
pkg/machines/components/diskAdd.jsx
pkg/machines/components/diskEdit.jsx
pkg/machines/components/vcpuModal.css
pkg/machines/helpers.js
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/machines.less
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus
test/verify/machineslib.py

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1671144
Explanation of disk bus from libvirt documentation:
`The optional bus attribute specifies the type of disk device to emulate`
I also changed Show/Hide Performance Options -> Show/Hide Additional Options. People who want to change cache options do not need to be told that it's "Performance" option, and I think having it as Additinal Options makes more sense.

machines: Support bus type configuration for disks

---

pkg/packagekit/updates.jsx

String returned from moment was not localized at all which meant we were
combining localized string with English text.
Fixes: #13367

packagekit: Properly localize timestamps

---

pkg/users/local.js
test/verify/check-accounts

Apparently some users have /etc/passwd entries without a 7th field for
the shell. This actually works, and uses /bin/sh as default.
But it caused the Accounts page to crash due to account.shell being
`undefined`. Provide empty string defaults to prevent that.
Fixes #13111
Closes #13384

users: Fix crash on incomplete /etc/passwd entries

---

pkg/machines/libvirt-common.js

machines: NIC model is not a mandatory NIC attribute

---

src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/test-webserver.c
test/verify/check-connection

(1) With a GTlsServerConnection, the GSource callback is not called
again if there is still pending data in GnuTLS'es buffer [1]. I. e. if
the input buffer had more than 4 KiB of pending data,
`on_request_input()` previously only read the first 4 KiB of data, and
then never tried again as there was no further callback.
(2) Also, there are legitimate HTTP requests (observed in the wild with
Kerberos SSO logins) which are slightly bigger than 4 KiB, so
considering that as a maximum request size is not enough.
Incidentally, larger requests up to 8 KiB happen to work because the
support for request pipelining leaves buffer space for up to 2 requests,
and it really only tests the buffer size instead of the individual
request size. But combined with the Gio bug above, they only worked for
plain …

common: Fix large requests with TLS

---

test/verify/check-metrics

On loaded machines, the Memory usage bar sometimes does not drop below
the initial usage afer 8s, but it takes a little longer. Robustify this
by waiting for the usage to drop, instead of expecting a fixed point in
time.
Fixes #13370

test: Fix testOverview flake

---

test/verify/check-connection

Commit 8a0edfbc4afa introduced an integration test for doing large
requests directly to cockpit-ws. Add another pair through cockpit-tls.
Buffer handling in cockpit-tls is totally independent, but let's cover
all bases.
This will still fail on rhel-8-1-distropkg: While cockpit-tls is not
affected by the Gio bug, RHEL 8.1's cockpit does not yet have
cockpit-tls.

test: Test large requests through cockpit-tls as well

---

pkg/machines/components/networks/utils.js
test/verify/check-machines-dbus

Relevant to: https://bugzilla.redhat.com/show_bug.cgi?id=1784289

machines: decompress ipv6 addresses before validating them

---

pkg/docker/containers-view.jsx

Otherwise the translation is not possible in languages, which do not
have plural forms (like most of Asian languages).

docker: Always use variables in ngettext

---

pkg/lib/notifications.js
pkg/packagekit/updates.jsx
pkg/systemd/overview-cards/healthCard.jsx
pkg/systemd/page-status.jsx
test/verify/check-packagekit
test/verify/check-services

The visual UX should be exactly the same as now, this also does not change strings. But this fixes #13400 and simplifies the code.

systemd: Replace OS updates health card entry with a page notification

---

doc/guide/https.xml
src/common/cockpitwebcertificate.c
src/common/cockpitwebcertificate.h
src/common/test-webcertificate.c
src/tls/connection.c
src/tls/connection.h
src/tls/main.c
src/tls/test-server.c
src/ws/cockpitcertificate.c
test/verify/check-connection

If a found ws-certs.d/ *.cert file has a corresponding *.key file, use
that instead of expecting a merged private key in the *.cert file. This
makes it easier to use Cockpit with LetsEncrypt or other automatically
maintained TLS certificates.
These days we mostly only need that for cockpit-tls. But fix it for
cockpit-ws as well, so that we keep remotectl happy (it complains
otherwise that it cannot find the key).
Fixes #8922

tls: Support separate certificate key file

---

test/verify/check-packagekit

cockpit-ws-dbgsym and cockpit-dashboard both have strict version
dependencies to cockpit-ws. Packagekit 1.1.13 now shows removals in
`get-updates`.
Include cockpit-dashboard into the update, and remove the -dbgsym on
Debian/Ubuntu.

test: Avoid removing packages in fake cockpit-ws update

---

pkg/systemd/graphs.js

Similarly to PR #13265, use the `hidden` attribute for the graphs
instead of .show()/.hide(). The latter sets `display: none`, which
causes the widget to have a zero height, which causes flot to crash with
Error: Invalid dimensions for plot, width = 647, height = 0 36 graphs.js:230:10
resize http://localhost:9090/cockpit/@localhost/system/graphs.js:230
Fixes #13290
https://bugzilla.redhat.com/show_bug.cgi?id=1792623

systemd: Fix graphs having wrong `display` attribute

---

test/verify/check-setroubleshoot

Show sealert info and audit.log on hitting
https://bugzilla.redhat.com/show_bug.cgi?id=1784506 , as it has become
hard to reproduce that bug locally now.

test: Add troubleshoot information to setroubleshoot failures

---

src/ws/login.js

Call `disableLogin()` with the missing name as argument, so that the
error message can print it properly.

ws: Fix error message on missing browser APIs

---

pkg/machines/components/nicEdit.jsx
test/verify/check-machines-dbus

Previously we were checking only node devices list, but we should also
check the interfaces list when showing the list of the available resources.
In addition if the current NIC was `Bridge to LAN` it was parsed improperly.
This commit fixes that as well.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1791543
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1791537

machines: Fix default bridge selection for `Bridge to LAN` NIC

---

src/ws/test-remotectlcertificate.c

This covers loading an existing certificate, not building one from given
parts. These can have the key first and then the certs, or the other way
round, so cover both orders.
See issue #13411

ws: Add unit tests for loading combined certificates

---

pkg/shell/switcher.less
pkg/systemd/overview.less

- Adjust the shell to provide more space for VM resolutions (<= 1024×768)
- Tweak layout, headings, and cards for various common resolutions, including:
- various typical mobile sizes
- VM <= 1024×768
- 1600×1200
- 2560×1440
- 1280×1440 (half-tiled browser window in 2560×1440)
- 1920×1080
- 960×1080 (for half-tiled browser windows in 1920×1080)
- and a lot of various widths in-between (to make sure elements are sized in a pleasant enough manner)

overview: Breakpoint optimizations

---

doc/guide/packages.xml
pkg/dashboard/manifest.json.in
pkg/kdump/manifest.json.in
pkg/machines/manifest.json.in
pkg/networkmanager/manifest.json.in
pkg/packagekit/manifest.json.in
pkg/shell/base_index.js
pkg/shell/index.html
pkg/shell/indexes.js
pkg/shell/shell.less
pkg/storaged/manifest.json.in
pkg/systemd/manifest.json.in
pkg/users/manifest.json.in
po/manifest2po
src/common/cockpitsystem.c
src/ws/cockpithandlers.c
test/verify/check-pages

To see OS specific documentation, you need to use also ws from this PR.
Followup:

Show per page documentation

---

src/websocket/websocketconnection.c

websocket: Fix unaligned access in send_prefixed_message_rfc6455()

---

test/verify/check-metrics

This makes sure that the page configures as expected and doesn't crash.
Don't test the innards of the graph again, as they are exactly the same
widgets as the ones already tested further above.
Reproduces https://bugzilla.redhat.com/show_bug.cgi?id=1792623

test: Add tests for CPU and memory graph pages

---

pkg/storaged/overview.jsx

It was forgotten when updating the layout of the panels in #11825.

storage: Fix layout of "Show all ..." button

---

pkg/storaged/vgroup-details.jsx

People find it hard to see which volume group the page is about.

storage: Highlight volume group name

---

webpack.config.js

The solution originates from https://github.com/webpack-contrib/mini-css-extract-plugin/issues/168

maint: mini-css-extract-plugin prints too many logs in console

---

test/common/tap.py
test/common/testlib.py
test/selenium/run-tests
test/selenium/selenium-network.py
test/selenium/selenium-tuned.py
test/verify/check-apps
test/verify/check-dashboard
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-examples
test/verify/check-journal
test/verify/check-machines-dbus
test/verify/check-machines-virsh
test/verify/check-multi-machine
test/verify/check-multi-machine-key
test/verify/check-packagekit
test/verify/check-services
test/verify/check-shutdown-restart
test/verify/check-system-info
test/verify/machineslib.py
test/verify/netlib.py
test/verify/packagelib.py
test/verify/storagelib.py

This avoids hardcoding/repeating the parent class name, and thus avoids
subtle bugs.
Only keep the explicit grandparent class call in `TestMachines.setUp()`,
as `NetworkCase.setUp()` breaks testCreate().

test: Use super() consistently

---

.tasks

This has been broken for quite a while now. Let's disable it to prevent
issue spam.

.tasks: Drop learning trigger

---

test/common/testlib.py

unittest.case has a TestCase subclass that breaks the loader, so testlib
needs to filter it out when loading specific tests.

testlib: Fix leaf_classes filter on module

---

test/verify/check-accounts

Otherwise `cockpit.permissions` are not loaded and the name cannot be
changed.
Fixes #13446

test: Wait until page is initialized before changing name

---

po/Makefile.am

Strings like `_("Context", "String to translate")` were not picked up.
TBH I don't understand this syntax fully (can someone point me to some doc?). But there is `gettext:1c,2,2t` and we use `_` as synonym for `gettext`. And when I compared `po/cockpit.pot` with this and without this patch, nothing was dropped, only a few new strings were picked up (mostly from storage).

po: Pickup also strings with specified context

---

.tasks
pkg/docker/docker.js
pkg/lib/cockpit-components-listing.jsx
pkg/machines/selectors.js
pkg/packagekit/mock-updates.js
pkg/selinux/setroubleshoot-view.jsx
pkg/storaged/jobs-panel.jsx
tools/urls-check

1. There was no issue, so it opened and immeditally closed one: https://github.com/marusak/cockpit/issues/25
2. There was closed issue that was modified less than 7 days ago - it did nothing
_I removed the check for 7 days so I don't need to wait a week to test it :)_
3. The task succeeded, so it just commented on the last issue: https://github.com/marusak/cockpit/issues/25#issuecomment-579714251
4. The task failed, so it opened a new issue: https://github.com/marusak/cockpit/issues/27 and kept it open (while opened, the task would not run again)
I also added it into `.tasks` file and fixed some non-existent URLs. It needs https://github.com/cockpit-project/bots/pull/470 or if we agree that it is a not good change, than I need to implement different `issues` method for this PR.
Also …

Validate urls

---

pkg/systemd/overview.less

PatternFly's `.pf-c-alert` rightfully has `margin-bottom` set. However, we're using it in a grid on the overview, so we should rely on `grid-gap` for proper spacing. Therefore, `margin-bottom` is redundant and adds too much space.
Test this with content in an `/etc/motd`.

overview: Drop MOTD's bottom margin; use grid gap

---

pkg/storaged/dialog.jsx

Fixes #3739
Before:
After:
And see the original issue for how it looked with long names.

storage: Don't duplicate descriptions

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx

This commit fixes the following problematic workflow:
* The user makes the validation of the fields of Create VM dialog to
fail (ex: leaving an empty field)
* Then successfully creates a VM
Result: They will shortly notice an inline validation error that the VM
name already exists, because the new VM list causes the dialog to
re-render and the validation to fail on existing VM name.
Expected result: The dialog should not do any inline validation after it
was successfully submitted and before it closes.

machines: When validation succeeds don't try to validate `Create VM` dialog again

---

pkg/systemd/overview-cards/serverTime.js
pkg/systemd/overview.jsx
pkg/users/local.js
test/verify/check-system-info

Fixes #8583 
I haven't found any other place, where the format would not be localized. If you find something, please point it out, and I'll fix it out.
The only other place related to time, that should be localized, are calendars:
(names of days, on which day week starts... - this can be done with setting up `language` but it requires to import all locale files - which cannot be automated... But there are  also other options, so I just plan to open issue for that and take a look at it separately).
I am not sure about that change on the overview page. It seems so obvious that I doubt it was not purposely that way? Now looks like this in English and is localized: 
Is that right?
Likely breaks tests, so spinning them out

Localize times

---

doc/man/cockpit.conf.xml

I attempted to disable session timeout, and was wondering why it wasn't working; I had:
[WebService]
IdleTimeout=0
On re-reading, it looks like it should be:
[Session]
IdleTimeout=0
[caveats: am still waiting the 15 minutes to see if this works; I edited the XML by hand in github UI, so I'm not sure if well-formed/valid]
If I'm reading it right, all of the existing examples are for WebService, which threw me.

doc: provide example of disabling session timeout

---

test/verify/check-storage-luks

In new Fedora-31 update, this message looks like: `/dev/sda could not be opened.`

test: Update message for not-initialized devices

---

test/verify/check-storage-lvm2

Adding lvol0 will appear as the new first table entry (asciibetical
sorting), and thus pool and /dev/TEST/thin will move down by one entry.
Fix the expected table row for the "Create Snapshot" menu entry, and
also ensure that the rows are as expected after creating lvol0.
Fixes #13499

test: Fix TestStorage.testSnapshots

---

test/common/cdp.py

... and firefox does not complain that there is unreachable code.
My try @ https://github.com/cockpit-project/cockpit/pull/13515

test: Hack a hack a bit so it is more hacky

---

test/verify/check-realms

The `b.mouse()` waits until the timeout, and the whole thing is retried
5*timeout times by b.wait(). When the test failed this led to timeouts of
half an hour due to that quadratic behaviour.
Lower the timeout to 4s, so that in total this waits 4*4*5=80s,
comparable to our standard 60s timeout.
Also drop the redundant wait_present() (mouse() already does that) and
avoid a blanket except:.
Fixes #13519

test: Fix excessive timeout in check-realms waitTooltip()

---

pkg/machines/machines.less
pkg/shell/shell.less

less ≥ 3.11 will try to look for a <filename>.less (e. g.
"page.css.less") which does not exist.
Cherry-picked from master commit 65dfb4fc17790

[r82] Drop less markers from *.css imports

---

pkg/Makefile.am
pkg/docker/org.cockpit-project.cockpit-docker.metainfo.xml
tools/cockpit.spec
tools/debian/cockpit-docker.install

Tested locally by adding the file to `usr/share/metainfo/org.cockpit-project.cockpit-docker.metainfo.xml`
Fixes #13416.

docker: Add appstream

---

pkg/networkmanager/interfaces.js

Similar to commit f1d06abedaee50d, but bump it harder. Right after
starting the test and cockpit, the VMs are fairly loaded (particularly
rhel-8-2), so that eth0 does not get shut down quickly enough and the
checkpoint_destroy() succeeds. As a result, Cockpit just disconnects,
the curtain never comes up, and there is never a restore.
Fixes #13532

networking: Increase checkpoint settle time

---

test/selenium/selenium-machines-basic.py

Seems that just 10s don't cut the mustard all the time. Let's use
the default.
Cherry-picked from master: d100d3d (TODO: check after it lands)

[8.2] test: Wait default time for machine to reboot

---

pkg/machines/actions/provider-actions.js
pkg/machines/components/deleteDialog.jsx
pkg/machines/components/diskAdd.jsx
pkg/machines/components/nicAdd.jsx
pkg/machines/components/vmDisksTab.jsx
pkg/machines/components/vmOverviewTabLibvirt.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus
test/verify/machineslib.py

Transient VM will differ in:
- It's deletion is disabled. It ceases to exist once it's turned off
- Memory, vCPU and Bootorder are not configurable.
- Autostart property is not shown at all
- Added support for adding and removing disks for transient VM (until now it resulted in error)
- Added support for adding and removing vNICs for transient VM (until now it resulted in error)
- Disk and vNIC configuration is disabled

machines: Support transient VMs

---

test/verify/check-login

Wait until the page built up instead of logging in and immediately out
again. login_and_go() does not wait very long, so that the subsequent
logout() can often cause a lot of unexpected message noise about
terminated channels and prematurely aborted resource loading.

test: Robustify testSessionRecordingShell

---

pkg/machines/components/vm/vmUsageTab.jsx
pkg/machines/libvirt-virsh.js

We would incorrecly divide cpuTime supplied by libvirt-dbus by number of
vCPUs to get an average of all vCPUs.
Number supplied by libvirt-dbus is already average.
This is probably caused by the fact that code was written for older
virsh provider, which supplied sum of all vCPUs times. Update virsh
provider too.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1763641

machines: fix CPU statistics

---

pkg/machines/components/create-vm-dialog/autoDetectOS.py
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/create-vm-dialog/password.css
pkg/machines/components/create-vm-dialog/password.jsx
pkg/machines/getOSList.py
pkg/machines/libvirt-common.js
pkg/machines/scripts/create_machine.sh
test/verify/machineslib.py

machines: Create vm dialog - add unattended installation option

---

test/verify/run-tests

Replace it with writing into an anonymous temporary file, so that the
test can write directly into it without having to worry about blocking
or polling.
If we ever need it for debugging/inspecting running tests, we could even
use named temporary files.

test: Drop stdout polling from run-tests subprocesses

---

test/common/testlib.py

This affects a lot of tests, and is too frequent and also too unspecific
for a naughty. See https://bugs.debian.org/951477 for details.
As our unexpected message filtering is line-by-line, this also needs to
ignore the whole stack trace. Make the patterns specific enough to not
match on just any stack trace.

test: Ignore iptables crash on debian-testing

---

pkg/systemd/kernelopt.sh

In that case there won't be a space in front of the key. We still want
to retain that check to make sure that we don't catch a key which is a
suffix of the given one, so explicitly add a test for the key being at
the beginning of the line.
Current fedora-coreos exposes that, as the "mitigations=" option is the
very first one now.

systemd: Fix kernelopt.sh to recognize options at the beginning of line

---

test/avocado/testlib_avocado/machineslib.py

The Selenium tests assume that libvirtd.service is already running (they
don't test the "no service" empy state). This is true for RHEL and
Fedora ≤ 30, but in Fedora 31 libvirt moved to being socket activated.
As the current code does not look at libvirtd.socket, just start the
service manually.
This only matters for the fedora-31/selenium tests, not for real-life
usage on RHEL 7, so we don't need to fix that on the Machines page on
this branch.
See https://github.com/cockpit-project/bots/pull/501 and
https://github.com/cockpit-project/cockpit/issues/13563 for details.

avocado: Ensure that libvirtd.service is running for Machines tests

---

test/common/testlib.py
test/verify/check-networking-checkpoints
test/verify/check-networking-settings

At the beginning of the test, the VM is very busy as so many things
happen at once. This causes NetworkManager device updates to be very
slow and run into the checkpoint revert threshold. This causes the new
settings for eth2 to never be applied, and instead the test gets stuck
on the "Change/Rollback" dialog.
To mitigate this, let the VM settle down a bit.
Fixes #13464

test: Robustify NM checkpoint rollback tests

---

test/verify/machineslib.py

libvirtd.service asynchronously creates libvirt-sock, so the test needs
to wait until it exists before it can chown it.

test: Fix check-machines race condition on ubuntu-stable

---

pkg/machines/components/diskAdd.jsx
test/verify/machineslib.py

If you try to add disk to VM, and switch to "Use existing" without
changing anything else in the UI (keep default pool and volume),
the format is not updated into correct value.
Fix this.
https://bugzilla.redhat.com/show_bug.cgi?id=1792319

machines: Fix incorrect format when adding existing disk to VM

---

tools/git-version-gen

When the TAR sources are modified with Yocto (devtool modify) a temporary repository is created. Therefore the check must be extended to avoid errors.

tools: add support for yocto

---

tools/cockpituous-release

It branched off on Feb 11:
https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html

cockpituous: Release to Fedora 32

---

pkg/storaged/nfs-mounts.py

It is pretty harmless to leave a mount point directory behind, and we
shouldn't let this prevent people from removing entries.
Fixes #13566

storage: Ignore all OS errors when removing unused NFS mount points

---

test/verify/check-packagekit
test/verify/packagelib.py

This allows us to run these for downstream gating, and also speeds up the tests.

tests: Run many package related tests in persistent testbeds

---

pkg/lib/page.css

@patternfly/react-styles 3.7 stopped shipping a copy of
patternfly-variables.css. Import it from @patternfly/patternfly instead.
package.json explicitly depends on the latter, but not on the former, so
we don't have control over react-styles.
The file is identical to the one from @patternfly/react-styles 3.6.4
(the version which we used until yesterday).

lib: Import patternfly-variables.css from main module

---

test/verify/check-metrics

On our shared infrastructure the VM's CPU usage often can't climb over
90%, and so TestMetrics.testOverview fails very often. Be content with
> 75%, it's enough to demonstrate that CPU usage is high.

test: Be a bit less demanding on full CPU usage in metrics test

---

test/verify/check-packagekit

Crashing PackageKit in the middle of an rpm install tends to corrupt the
RPM database (observed a lot on RHEL 8.2). Backup/restore it in that
test.

test: Avoid RPM database corruption in testPackageKitCrash()

---

test/verify/packagelib.py

Sometimes the automatic uninstalling of our test packages failed on
Debina/Ubuntu, when testPackagekitCrash() killed PackageKit/dpkg on a
bad time:
```
dpkg: error processing package slow (--purge):
package is in a very bad inconsistent state; you should
reinstall it before attempting a removal
```
Use `--force-remove-reinstreq` to override this, so that it doesn't
bleed into and break the next test.

test: Fix uninstalling of test packages on Debian

---

test/common/testlib.py
test/verify/check-login

Generalize the backup/restore of users, so that tests can do useradd,
chage, and other changes without permanently changing the VM.
Also revert changes to other config files and rename instead of remove
binaries.
Part of issue #13481

test: Make check-login nondestructive

---

test/verify/check-storage-nfs

Re-enable /sbin/mount.nfs after the test ran.

test: Fix cleanup in TestStoragePackages.testNfsMissingPackages

---

pkg/lib/page.css

@patternfly/react-styles 3.7 stopped shipping a copy of
patternfly-variables.css. Import it from @patternfly/patternfly instead.
package.json explicitly depends on the latter, but not on the former, so
we don't have control over react-styles.
The file is identical to the one from @patternfly/react-styles 3.6.4
(the version which we used until yesterday).
Cherry-picked from master from 4ace78c1

[rhel 8.2] lib: Import patternfly-variables.css from main module

---

tools/cockpituous-release

Fedora 32 is around the corner, let's not burden ourselves with too many
parallel versions. Those users who want the latest stuff can upgrade to
Fedora 31 now.

cockpituous: Stop releasing to Fedora 30

---

test/README.md
test/selenium/README.md

Selenium and the default OS were moved in
https://github.com/cockpit-project/bots/pull/501
fedora-30 testing was dropped in
https://github.com/cockpit-project/bots/pull/563

test: Update documentation for moving tests to Fedora 31

---

test/verify/check-login

This broke check-terminal due to unexpected shell messages if
check-login ran before.

test: Clean up user profile modifications in check-login

---

tools/cockpit.spec

cockpit-{packagekit,storaged,pcp} are meant to be recommended/suggested
on RHEL as well, but were accidentally inside the "not RHEL"
conditional.  The other packages don't exist in RHEL or are merged into
cockpit-system, so the conditional is still correct for them.
Also add a Recommends: PackageKit to cockpit-system for minimal
installations, so that the on-demand installation for further packages
(e. g. insights-client for Subscriptions, or realmd for IdM) works.
https://bugzilla.redhat.com/show_bug.cgi?id=1803858

tools: Fix RPM weak dependencies

---

test/verify/check-metrics

In recent Fedora 31, the dd command for the memory hog tends to abort
with a partial read after ~ 20 MB. Use the `iflag=fullblock` option (as
dd suggests by itself) to avoid that.

test: Fix TestMetrics.testOverview for partial dd reads

---

test/selenium/selenium-sosreport.py

Just like its verify counterpart, only select a few fast sosreport
modules. The full test takes too long now on Fedora 31.

test: Speed up selenium-sosreport.py

---

test/selenium/selenium-sosreport.py

Just like its verify counterpart, only select a few fast sosreport
modules. The full test takes too long now on Fedora 31.
Cherry-picked from master commit 5577b11a0.

[r82] test: Speed up selenium-sosreport.py

---

test/containers/check-bastion

Use podman for Fedora ≥ 31.
That also doesn't need the iptables hack.

test: Support podman in containers/check-bastion

---

pkg/systemd/overview-cards/motdCard.scss

Bump the text down by the difference in font size.

system: Fix MOTD text alignment

---

test/verify/check-networking-firewall

firewalld and libvirt start up in parallel, and libvirtd asynchronously
adds its zone into firewalld after starting up. So wait until it did
that, so that we get a stable zone count.
Otherwise it often happened that the initial `--get-active-zones` did
not yet include the libvirt zone, and the later assertion about what's
shown on the Networking page failed due to a number mismatch.
Conditionalize the waiting on libvirt being available, as not all images
have it.

test: Fix race condition in TestFirewall.testNetworkingPage

---

pkg/shell/switcher.scss
pkg/systemd/graphs.scss

Non-Chromium Edge doesn't support grid-template-area specification in grid-template. This is a feature bug in the browser (and other browsers support it fine).
The solution is to specify `grid-template-area` instead of `grid-template` when using named grid areas.

EdgeHTML: Un-shorthand grid-template-area

---

pkg/systemd/graphs.html
pkg/systemd/graphs.js
test/verify/check-metrics

There were two elements with ID `system-link`. One was always hidden,
but since every ID needs to be unique, it was not behaving as expected.
Fixes #13578

system: Fix breadcrumb on graphs subpages

---

test/common/testlib.py
test/verify/check-kdump
test/verify/machineslib.py

In the past we had all too many tests which got stuck on mis-handling VM
boot timeouts, quadratic timeout loops, and similar. These are a bit
hard to spot.
Introduce a second line of defense and hard-limit each individual test
to 10 minutes.
The vast majority of our tests take less than 5 minutes. Some tests
legitimately take longer, though -- provide a `@timeout(seconds)`
decorator that can override the 10min default on a class or method
level. Mark the three tests which are known to take > 5 mins
accordingly.

test: Introduce hard timeout for an individual test

---

test/common/testlib.py
test/verify/check-accounts

Fortunately, commit dcb23b1ab2cb already does the heavy lifting.
----
I also added a second commit which fixes a common test flake. It's conceptually unrelated, but I ran into it twice locally, and indeed it also [happens on CI](https://logs.cockpit-project.org/logs/pull-532-20200217-071414-d7ba954f-ubuntu-1804-cockpit-project-cockpit/log.html) [quite often](https://logs.cockpit-project.org/logs/pull-554-20200224-070033-5f67f5d8-debian-stable-cockpit-project-cockpit/log.html#132).

test: Make check-accounts nondestructive

---

test/verify/check-pages

Our stable branches don't run fedora-31, thus never validate translation
updates. Let's run them on rhel-* images as well to fix this.

test: Run translations tests on RHEL images

---

test/verify/check-pages

Our stable branches don't run fedora-31, thus never validate translation
updates. Let's run them on rhel-* images as well to fix this.
Cherry-picked from master commit 450aec887

[rhel-8.2] test: Run translations tests on RHEL images

---

test/verify/check-machines-dbus
test/verify/machineslib.py

This is second batch of making machines tests nondestructive.
It fixes networking related tests. There are still 3 pools related, 4 disks related and testCreate.

Machines networking tests nondestructive

---

test/verify/run-tests

Commit 1217eb02 broke retrying unstable tests for which tests-policy did
not find a specific reason (like ssh/test harness failures). We always
want to limit the retries to 3, and we (currently) always want to retry
failed tests.
Show the reason for the retry in the test ouput, so that we can
analyze/track this better.

tests: Fix test retrying in verify/run-tests

---

test/common/testlib.py
test/verify/check-machines-dbus
test/verify/run-tests

When writing commit 58e661870, I failed to notice
bots/machine/machine_core/timeout.py which also uses SIGALRM. Setting
one for each test breaks the `testvm.Timeout` invocations in the bots
machinery and various tests, as they would not set a timeout of their
own, and thus they all timed out after 10 mins instead of the originally
intended much shorter timeout.
Thus revert the part that sets an alarm in MachineCase, and move that to
test/verify/run-tests. Call the individual test through timeout(1), to
avoid using alarm() in the run-tests process as well (as handling the
global Machine instance also involves Timeouts).

test: Don't let global timeout interfere with testvm.Timeout, fix debian/ubuntu tests

---

test/verify/check-sosreport

Only run one module in parallel and add two of the more expensive
modules. The previous configuration was so fast that there's a high
chance to not ever get a progress bar, which our test expects.

test: Slow down sosreport a bit

---

test/verify/check-machines-dbus
test/verify/machineslib.py
test/verify/storagelib.py

Machine.add_disk() requires explicit control over QEMU and thus is not
available for @nondestructive tests.
Add a new StorageHelpers.add_ram_disk() method that creates a RAM disk
(using `scsi_debug`) of a given size and return the device name. This
takes care of cleaning up itself when the test ends.
Use this in the Machines tests. Eliminate the prepareDisk() helper
function, as we only actually need a GPT table in one test.

test: Move check-machines* tests to RAM disk

---

pkg/kdump/kdump.scss

The previous code led to the dialog being moved to the left side of the
screen.
Fixes #12771

kdump: Apply width to the modal-dialog class instead of modal in kdump dialog

---

test/verify/run-tests

Show how many serial tests run and how long they took in total. This
will guide us to when they become the critical path and we need to start
parallelizing them.
Also drop the final "Test run finished..." line, it has no useful
information. The result code is already shown in the previous
"# TESTS ..." line.

test: Print statistics about serial tests

---

test/verify/packagelib.py

Same as in commit 458e145 for the Ubuntu part. Without the virbr0
interface, NM thinks it's offline.

test: Start libvirtd on packagekit tests for Debian

---

test/verify/check-login

On Fedora 32, these cause some more messages.
Also remove a duplicated message.

test: Allow more sudo noise for SELinux restricted users

---

pkg/networkmanager/firewall.jsx
pkg/systemd/hwinfo.jsx

New version of `eslint-plugin-react` was released and it was reporting
these two cases as `Empty components are self-closing`.

Adjust to new version of eslint

---

pkg/networkmanager/firewall.jsx
pkg/systemd/hwinfo.jsx

New version of `eslint-plugin-react` was released and it was reporting
these two cases as `Empty components are self-closing`.
Cherry-picked from master commit 8940569939

[7.8] Adjust to new version of eslint

---

pkg/networkmanager/firewall.jsx
pkg/systemd/hwinfo.jsx

New version of `eslint-plugin-react` was released and it was reporting
these two cases as `Empty components are self-closing`.
Cherry-picked from master commit 8940569939

[8.2] Adjust to new version of eslint

---

pkg/packagekit/updates.scss

This apparently got lost somewhere in the PF4 conversion.
Current master:
With this fix:

packagekit: Leave some space between "available" and "history" tables

---

pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

Both the cli and gui of firewalld use the zone id, and not the name to
identify zones. Cockpit should do the same to avoid confusion.

firewall: Use ids for zones instead of names

---

pkg/systemd/reporting.jsx

Cancel button should not be "danger".

systemd: Turn crash reporting cancel button into secondary

---

doc/guide/Makefile-guide.am
examples/gtk-broadway/gtk.html
pkg/machines/components/create-vm-dialog/createVmDialogUtils.js
pkg/machines/libvirt-common.js
pkg/machines/libvirt-virsh.js
pkg/systemd/overview-cards/realmd-operation.js
src/bridge/bridge.c
test/verify/check-packagekit
test/verify/check-realms

We were mostly doing this for the sake of RHEL 7, which lacked C.UTF-8,
which is what we actually want to be using.
This should fix issues with some of the test machines not having
en_US.UTF-8 installed, and allows removal of a few workarounds that
tested for C.UTF-8 with a fallback to en_US.UTF-8.

all: stop using en_US.UTF-8 as a default locale

---

pkg/docker/containers-view.jsx
pkg/lib/cockpit-components-empty-state.css
pkg/lib/cockpit-components-empty-state.jsx
pkg/networkmanager/firewall.jsx
pkg/packagekit/updates.jsx
pkg/packagekit/updates.scss
pkg/selinux/setroubleshoot-view.jsx
pkg/storaged/devices.jsx
pkg/systemd/logs.js

We've had pkg/lib/cockpit-components-empty-state.jsx for a while, but so far it was only being used on the Logs page. I generalized it and converted most of our React pages to it.
The only place that's left is pkg/machines/components/libvirtSlate.jsx (the "service is not active" curtain), that will require some further extension to also allow the check box. That's a pattern that we have on more than one place, so that should get some deeper thought. This PR is big enough as it is already, so let's handle this separately.

Empty state factorization

---

test/verify/run-tests

tests-policy has no idea about the current retry count, it just always
adds the `# RETRY` reason to the output. This caused it to appear in the
log even after the 3rd run, after which we don't actually retry any
more. But log.html still considered it as a retry instead of a failure,
and then not ever showed the failure.
Always filter out test-policy's retry reason. For the actual retries,
it's printed again anyway (previously leading to duplication), and for
the last one don't print it any more.
Fixes #13697

test: Fix TAP output for infrastructure retries in run-tests

---

pkg/apps/application-list.jsx
pkg/apps/application.jsx
pkg/apps/utils.jsx
pkg/networkmanager/firewall.jsx
pkg/playground/react-demo-listing.jsx
pkg/selinux/setroubleshoot-view.jsx
pkg/storaged/multipath.jsx
pkg/storaged/storage-controls.jsx
test/verify/check-networking-firewall
test/verify/storagelib.py

This covers most buttons except for Machines. I kept pkg/storaged/plot.jsx as-is as that's a bit arcane, and docker as I just didn't get to that. I'll handle that in a separate PR, if we even still care.
-  [x] Move from disabled class to attribute: PR #13687 13552

Port more buttons to PF4 React component

---

test/verify/check-machines-dbus
test/verify/machineslib.py

This is a variant of PR #13696 that keeps the test structure as-is. I was debugging in the wrong direction, so I think the test split is not actually necessary. Now it's a matter of taste, but let's first see what the tests have to say.

test: Make testAddDisk nondestructive (variant without test split)

---

tools/cockpit.spec

docker hasn't worked out of the box since Fedora 31 due to being
incompatible with cgroupsv2 [1], and we don't test it there for that
reason. As such it's slowly deteriorating, and podman+cockpit-podman is
the officially supported solution.
So disable `%{build_docker}` on Fedora ≥ 32, only keep it for 31 for
now as that's a stable release. Also guard the cockpit metapackage's
docker recommendation by the same condition; it was previously wrong, it
would have added the condition even with disabling `build_docker`.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1746355

Stop building docker for Fedora ≥ 32

---

test/verify/check-docker
tools/debian/control
tools/debian/rules

Drop cockpit-docker for Debian/Ubuntu development series, some packaging cleanups

---

test/verify/check-networking-firewall

Save/restore firewalld configuration in between tests.
libvirtd.service times out after 2 minutes when not used, and thus tears
down the libvirt firewalld zone. Make sure it is running in the tests
that assume the libvirt zone.

test: Make check-networking-firewall nondestructive

---

pkg/lib/cockpit-components-empty-state.jsx
pkg/machines/components/libvirtSlate.css
pkg/machines/components/libvirtSlate.jsx
pkg/packagekit/updates.jsx
test/verify/machineslib.py

Use our common EmptyStatePanel and PF4's Button components. Leave the
checkbox for now, as PF4's Checkbox component is badly aligned (grid
layout within the EmptyStateBody doesn't work right).

machines: Convert LibvirtSlate to PF4-React

---

test/verify/check-networking-firewall

check-machines-* can leave the default libvirt network stopped, so make
sure to start it.
Other tests need the libvirt zone as well, so move the code into
setUp().
Turn the positive OS list in testAddCustomServices into a negative list,
so that it is more robust when adding new OSes.

test: Robustify and generalize libvirt zone setup in check-networking-firewall

---

test/verify/machineslib.py

On current Fedora, libvirt ships socket units that auto-activate
libvirtd.service. This means that even when stopping libvirtd.service,
our page is still connected to libvirt and its requests cause the
service to auto-restart. Thus the empty state goes away all by itself
without having to press a button.
We should handle socket activation properly (issue #13563), but for now
just robustify that test case to really only test the service in
isolation.

test: Fix flake in TestMachines.testLibvirt

---

pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css
test/verify/check-networking-firewall

So ports can also directly be added to firewalls. So far this PR doesn't allow you to add or remove them, it just shows them. I'm not sure if we want to support modifying them because feature creep on the firewall page wouldn't really have an end as there's so much we could support.

firewall: Show ports that were directly added to the firewall

---

test/verify/check-networking-firewall

Work around https://bugzilla.redhat.com/show_bug.cgi?id=1813830 by
restarting libvirtd for each firewall test before trying to start the
libvirt default zone.

test: Fix starting libvirt default network after restarting firewalld

---

test/common/testlib.py
test/verify/check-example

See individual commits.
I tested this with a simple
```diff
--- test/verify/machineslib.py
+++ test/verify/machineslib.py
@@ -295,6 +295,7 @@ class TestMachines(NetworkCase, StorageHelpers):
b.wait_in_text("tbody tr[data-row-id=vm-subVmTest1] th", "subVmTest1")
b.click("tbody tr[data-row-id=vm-subVmTest1] th") # click on the row header
+        self.assertTrue(False)
b.wait_in_text("#vm-subVmTest1-state", "running")
m.execute('[ "$(virsh domstate {0})" = running ] || '
```
And now on failure I get a screenshot that shows the running VM, instead of the "no VMs defined" after cleanup.
The verbose test log shows the correct order now: fail, do snapshots/sit, then clean up:
```
-> ph_mouse("tbody tr[data-row-id=vm-subVmTest1] th:not([disabled])","click",0,0,0,false,false,false,false) …
```

Make attachments great again

---

tools/cockpituous-release

Our cockpit-preview COPR is configured for current Fedora and RHEL 8
now, it doesn't build for CentOS/RHEL 7.

cockpituous: Disable releasing to COPR

---

pkg/machines/components/vm/vmUsageTab.jsx
pkg/machines/libvirt-virsh.js

We would incorrecly divide cpuTime supplied by libvirt-dbus by number of
vCPUs to get an average of all vCPUs.
Number supplied by libvirt-dbus is already average.
This is probably caused by the fact that code was written for older
virsh provider, which supplied sum of all vCPUs times. Update virsh
provider too.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1763641
Cherry-picked from master commit cc5b7661b8f8893

[r78] machines: fix CPU statistics

---

Makefile.am

`$(abspath $(srcdir))` and `$(abs_srcdir)` don't do the same thing if
there are symbolic links in the path. In particular, if /home is a
symlink to /var/home (like on OSTree), the former is
`/var/home/<user>/...`, while the latter is `/home/<user>/...`
This caused broken tarball builds.
Consistently use the `$(abs_*)` make variables so that the values agree
on the same prefix.

build: Consistently use absolute source and build dir

---

test/common/testlib.py

`print_exc()` prints to given fd and returns None. `format_exc()`
returns the string, that `print_exc()` would print.

test: Change `print_exc()` to `format_exc()`

---

pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

In order to be consistent with other firewalld interfaces, we shouldn't
use the short name.

firewall: Use ids for services instead of names

---

test/verify/check-storage-lvm2

If the test fails, actually clean up the VG, to avoid keeping scsi_debug
busy. Speling is improtant!

test: Fix cleanup in TestStorage.testLvm

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/common/testlib.py
test/verify/check-machines-dbus
test/verify/machineslib.py

Since commit 70894926b7, TestMachines does not need `NetworkCase` any
more, so the inheritance hacks can be dropped. Eventually we want to
move addIface() into a more generic class, but that should happen
similar to StorageHelpers.

test: Clean up inheritance of TestMachines

---

test/verify/machineslib.py

This has a similar profile as debian-testing, and it sometimes also
happens for `denied_mask="wr"`.

test: Add expected AppArmor messages for TestMachines.testAddDisk on ubuntu-stable

---

test/verify/check-machines-dbus
test/verify/machineslib.py

* Don't duplicate the initiator name detection in
testStoragePoolsCreate(); instead, let prepareStorageDeviceOnISCSI()
return the initiator IQN and re-use that.
* Refine the sed expression to only accept `InitiatorName=`. On
Debian/Ubuntu, if the daemon has never run, the file contains
"GenerateName=yes", and we really don't want to use "yes" as an
initiator name.
* Ensure that we have an initiator name by starting iscsid before
reading the name.

test: Robustify check-machines iSCSI tests

---

test/verify/machineslib.py

This hack was introduced for fedora-i386 testing, but that hasn't been a
thing for a long time. Issue #8385 got closed to inactivity, so we
are not tracking that anywhere either.

test: Drop obsolete "unknown host CPU" hack from TestMachines.testCreate()

---

test/common/testlib.py

This properly cleans up after tests which fail after e. g. `cryptsetup open`
on the scsi_debug disk.

test: Clean up remaining devicemapper devices and mounts from RAM disk

---

test/common/testlib.py

They take up 60% of our total log space and compress really well. E. g.
20 MB → 380 kB gzipped.

test: Compress journals

---

test/verify/check-realms

It sometimes fails with a message that certmonger is not running, or
something like that, but will recover from that.

test: Robustify ipa-getcerts in check-realms

---

Makefile.am

This speeds up test/image-prepare for humans and CI. Official releases
use "dist" and build xz tarballs, and we only want the -cache for these
for license reasons.

build: Don't produce cockpit-cache.tar.gz in dist-gzip mode

---

pkg/users/index.html

The tooltips were places at the end of the body element on hover. When
someone clicked on the checkbox, that triggered actions and the groups were
re-rendered. By re-rendering, the page lost the context of which tooltip
belongs to which element (as those elements were created from scratch).
That kept dangling tooltip at the end of the body after each click on
these checkboxes.
With this patch the tooltips are rendered in the same DOM element, so when
groups are destroyed, those tooltips are destroyed as well.
Fixes #12262

accounts: Properly dismiss tooltips

---

test/verify/check-machines-dbus
test/verify/machineslib.py

The packages are on the images now [1], and the tests got adjusted to
also work on Debian/Ubuntu [2]. The Debian images only ship the -cloud
kernel which doesn't provide the `target_core_mod` kernel, so the tests
don't currently work there.
Debian/Ubuntu's libvirt does not provide the iscsi-direct backend
(https://bugs.debian.org/918728), only the iscsi backend, so only test
that one.
Ubuntu 19.10's targetcli has a broken `targetcli delete` command
(https://bugzilla.redhat.com/show_bug.cgi?id=1659195). As this breaks
nondestructive cleanup, just skip the test here. Let's just make sure it
keeps working on the LTSes.
[1] https://github.com/cockpit-project/bots/pull/651
[2] https://github.com/cockpit-project/cockpit/pull/13749

test: Enable Machines iSCSI tests on Ubuntu

---

test/README.md
test/verify/check-multi-os

By now, the Cockpit version on CentOS 7 is 195, which is also "old" and
sufficient for proving backward/forward compatibility. Also, ensuring
proper interoperability with current CentOS/RHEL 7 makes much more sense
now than with a long-EOL Fedora.

test: Use centos-7 image instead of fedora-23-stock in check-multi-os

---

test/README.md
test/verify/check-multi-os

By now, the Cockpit version on CentOS 7 is 195, which is also "old" and
sufficient for proving backward/forward compatibility. Also, ensuring
proper interoperability with current CentOS/RHEL 7 makes much more sense
now than with a long-EOL Fedora.
Cherry-picked from master commit 59ad5d924bcd

[rhel-8.2] test: Use centos-7 image instead of fedora-23-stock in check-multi-os

---

test/README.md
test/verify/check-multi-os

By now, the Cockpit version on CentOS 7 is 195, which is also "old" and
sufficient for proving backward/forward compatibility. Also, ensuring
proper interoperability with current CentOS/RHEL 7 makes much more sense
now than with a long-EOL Fedora.
Cherry-picked from master commit 59ad5d924bcd

[rhel-7.8] test: Use centos-7 image instead of fedora-23-stock in check-multi-os

---

pkg/systemd/logs.js
pkg/systemd/logs.scss

Fixes #11665
@garrett WDYT?
Before:
After: 
After in reasonable resolution:

Format logs better

---

test/verify/check-accounts
test/verify/check-login

This happens when running the tests in downstream dist-git gating, or
against an existing --machine/--browser where the root user is already
logged in.
In that case, `who` output might not start with the admin session, and
the "Terminate Session" button is not disabled.

test: Fix check-{accounts,login} to get along with root login

---

test/selenium/selenium-machines-non-root.py

I got quite confused by this while working on #13482 and even thought for a while that this test is all a giant race condition. (Creating a machine and then checking that the UI says "No VM defined".)
But it all makes sense, it's just not clear for an outsider what is actually going on.

test: Clarify selenium-machines-non-root.py

---

test/verify/check-storage-lvm2

Sometimes the resized pool's capacity is only 92 instead of 96 MiB,
so allow anything in that range.

test: Allow some capacity wiggle room in check-storage-lvm2 testLvm

---

test/verify/check-storage-lvm2

Creating the partition table takes some time to propagate trough udev
and udisks. Make sure that the VG creation dialog sees the partition
table on the scsi_debug device, and not just the original raw device.
Otherwise the PV initialization will overwrite the partition table
instead of creating a partition.

test: Fix race condition in check-storage-lvm2 testUnpartitionedSpace

---

doc/man/cockpit-desktop.xml
src/ws/cockpit-desktop.in
test/verify/check-connection

If given, cockpit-bridge will be started on the remote host through
ssh instead.
This is an experimental/demo feature for now, mostly to understand how
cockpit's parts can be plugged together in a very flexible manner.

ws: Add optional remote ssh host argument to cockpit-desktop

---

test/verify/check-networking-basic
test/verify/check-networking-firewall
test/verify/machineslib.py
test/verify/netlib.py

tests: Get rid of "eth1" assumption in Cockpit VMs

---

test/common/testlib.py
test/verify/check-example
test/verify/machineslib.py

Creating and deleting iSCSI nodes leaves some node information behind in
/var/lib/iscsi. This causes a subsequent boot to hang, as it waits in
vain for an IQN which does not exist any more.
Work around that by restoring the originally empty /var/lib/iscsi.
See https://bugzilla.redhat.com/show_bug.cgi?id=1817241

test: Avoid reboot hangs after iSCSI tests

---

test/verify/check-setroubleshoot

We often have SELinux policy bugs in various OSes, like
https://github.com/cockpit-project/bots/issues/573. These will
appear on the SELinux page instead of "No alerts", which often causes
that test to fail.
Clean up pending alerts to get setroubleshootd and our page into an
empty state.

test: Clear initial SELinux alerts in TestSelinux.testTroubleshootAlerts [fix commit message on squash]

---

test/verify/check-example

testOne() intentionally leaves a file and directory behind, so that
testTwo() can validate that testOne's tearDown correctly restored them.
But clean them up in testTwo, so that subsequent tests are not affected
by them.
Also rename the directory to not be so close/similar to
/var/lib/cockpittest/; we use the latter in dialogs (like the storage
pool tests), and it appeared as possible completion.

test: Clean up after TestNondestructiveExample

---

pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

We switched over to using ids for presentation for both services and
zones. So instead of a custom name, allow setting of a custom id.
Fixes #12849 partially
----

firewall: Remove the name field from the AddServices dialog

---

test/verify/check-networking-basic
test/verify/netlib.py

Replace the provisioning of a second VM with a local DHCP server, and
use a veth instead of a QEMU device.
Drop the Alias= hacking; it's obsolete, NM does not do D-Bus activation
any more on any of our current images.

test: Make check-networking-basic nondestructive

---

pkg/systemd/overview-cards/realmd-operation.js

Installing cockpit-ws credentials is only supported for FreeIPA. When
joining an AD domain, trying to call the `ipa` command line client will
just thrown an error message "IPA client is not configured on this
system". This appears in the "Join Domain" dialog without further
details, but the joining works anyway, so this was rather confusing.
Only actually run install_ws_credentials() when the Server software is
"ipa".
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1813136

systemd: Fix error message when joining AD domains

---

pkg/systemd/overview-cards/realmd-operation.js
test/verify/check-realms

Commit 0a760b705ce was missing the realms-op-diagnostics field, which
also uses "hidden", and thus never appeared when calling .show(). The
effect was that clicking on the "More" link to get the verbose
diagnostics just made the whole error message go away.
Change the "hidden" instead of the "display" attribute to fix that. Do
the same for realms-op-error for consistency.
Add a test for the error handling: Initially we just want to show the
error message and the "More" link, and when clicking we want both go to
away and show the verbose "diagnostics" log.
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1813136

systemd: Fix showing the "More" diagnostics in realm join dialog

---

src/common/test-config.c

Previously the test would fail in an environment where XDG_CONFIG_DIRS
was set as it takes precedence over the built in defaults. So let's just
set XDG_CONFIG_DIRS and test that feature instead.

test: handle XDG_CONFIG_DIRS

---

containers/ws/Dockerfile

cockpituous will replace the value on release:
https://github.com/cockpit-project/cockpituous/blob/master/release/release-dockerhub#L85
Fixes #13812

containers: Add VERSION label to cockpit/ws

---

package.json
webpack.config.js

Some rules may be imported more times or they might be overwritten in
the same file. Removing such rules reduces the size of css files.
Related #12910
Fixes at least my comment from #12910, possibly the whole issue? I am still not sure what @garrett meant there so cannot verify it.
Some stats:
File name | Size before | Size after | Proportion
--- | --- | --- | ---
/usr/share/cockpit/apps/apps.css.gz| 11K|9.4K | 85%                             
/usr/share/cockpit/users/users.css.gz| 14K|11K | 78%                            
/usr/share/cockpit/tuned/performance.css.gz| 8.4K|8.1K | 96%                    
/usr/share/cockpit/dashboard/dashboard.css.gz| 9.8K|8.7K | 88%                  
/usr/share/cockpit/kdump/kdump.css.gz| 16K|10K |62% …

Reduce size of css files

---

package.json
pkg/lib/_global-variables.scss
pkg/lib/cockpit-components-table.scss
pkg/systemd/overview.scss
webpack.config.js

* This was split out of https://github.com/cockpit-project/cockpit/pull/13695 to allow quicker merging 
When PF4 has a breakpoint of 768px width, it's actually 1108 for us,
as the sidebar is 340px. This does use the intended content area, but there's a
mismatch between content and browser width as we use iframes.
So redefine grid breakpoints in _gloabal-variables.scss file which is
configured to be visible by all scss files.
In order that these variables take effect we should make sure that the
components that are using these variables are also using scss and not css.
See https://github.com/patternfly/patternfly-react/issues/3815 for more
info.
In order to achieve that utilize null-loader, which allows us to filter
out CSS stylesheets from specific directories.

Redefine PF4 breakpoints global variables to avoid premature wrapping

---

src/bridge/cockpitconnect.c

This is being used for SNI and better error messages for TLS
connections [1]. Recent glib versions started to warn about this, which
makes our tests fail:
(test-httpstream:172365): GLib-Net-WARNING **: 02:19:07.627: GTlsClientConnection certificate verification will fail because its server-identity property is NULL. Fix your application!
(test-websocketstream:172431): GLib-Net-WARNING **: 02:19:08.201: GTlsClientConnection certificate verification will fail because its server-identity property is NULL. Fix your application!
[1] https://developer.gnome.org/gio/stable/GTlsClientConnection.html#GTlsClientConnection--server-identity

bridge: Pass connectable to TLS client connection

---

test/verify/check-services

There can be a different failure on the overview page that contains the word
"failed".
Fixes #13818

test: Make check for no failed services more robust

---

configure.ac

Commit 4d6ae2d1ba707 introduced an assumption that .git is a directory,
which is not true for worktrees.

build: Unbreak git worktrees

---

test/verify/check-setroubleshoot

Fedora seems to have a new local modification, that is preventing tests
from seeing 'No System Modifications'.
Log: https://logs.cockpit-project.org/logs/pull-700-20200331-143900-468782d5-fedora-testing-cockpit-project-cockpit/log.html#202-2
Related https://github.com/cockpit-project/bots/pull/700
Related https://github.com/cockpit-project/bots/pull/699

test: Also cleanup selinux modules

---

configure.ac

By prioritizing the tarball version, a git overlay has no effect
on the readout version. With this modification the version detection
works in Yocto 3.x.

feat: prioritizing the tarball version

---

test/verify/check-machines-dbus

Seems that the related bug got into debian as well.
Related https://github.com/cockpit-project/bots/pull/705

test: Also reload libvirtd on debian-testing

---

pkg/systemd/overview.jsx

It is not actually used by the rest of the code.
This matters with #13482, calling cockpit.permissions would cause a reload of the page when permissions actually change.

system: Don't call cockpit.permissions for LoginMessages

---

pkg/packagekit/autoupdates.jsx

CentOS/RHEL 8 and Fedora use dnf, and we don't support CentOS/RHEL 7
from master any more, so these can go. There is no functional change.

packagekit: Remove remaining mentions of yum

---

containers/unit-tests/README.md
containers/unit-tests/run.sh
containers/unit-tests/start

Add missing :Z option so that this can be run on a Fedora/RHEL host with
SELinux on.

containers: Fix unit-tests container for SELinux

---

containers/unit-tests/README.md
containers/unit-tests/run.sh
containers/unit-tests/start

Turns out :Z destroys the labels on the host, so let's not do that.
Instead, document that you need to setenforce 0.
Better solutions appreciated!
This reverts commit d82cda29177294d795a2879d4484f272c37f3bc0.

Revert "containers: Fix unit-tests container for SELinux"

---

test/verify/check-login

If check-login ran before the Machines tests, the latter failed with
internal error: child reported (status=125): Unable to get host boot time: No such process'
Libvirt looks at the boot time in /run/utmp to determine that, and
apparently fails to fall back to /proc/uptime in some versions
(https://bugzilla.redhat.com/show_bug.cgi?id=1783715)
Avoid that by restoring the file.

test: Restore utmp in check-login to pacify libvirt

---

pkg/shell/index.html
pkg/shell/indexes.js
pkg/shell/shell.scss
test/verify/check-menu
test/verify/check-pages

Rename 'Cockpit' to 'Web Console'.
Move 'About Cockpit' into 'Help' as it makes more sense there as in
account settings.
Inspired by the designs for the new navigation where this item was moved into Help section.
@garrett agree with this change?

shell: Move 'About Cockpit' into 'Help' and rename it

---

Makefile.am
src/branding/opensuse-tumbleweed/Makefile.am
src/branding/opensuse-tumbleweed/branding.css
tools/cockpit.spec

I don't know if you want to litter your spec file with our stuff but worth a try I guess :)
Apart from the usual package name differences there are also some files packages twice or not owned directories caught.
The debug trick doesn't work, the macro has different content on openSUSE. Also, openSUSE doesn't like stale symlinks.

tools: spec file adjustments for openSUSE

---

pkg/lib/cockpit-components-dialog.jsx

Commit a0f826 adjusted the buttons in the modal footers to be left aligned but
missed the case of the storage dialogs where for the 'in progress'
operations the spinner and 'in progress' message has to be adjusted has
well.

storage: Right align idle message and spinner in the modal footers

---

src/ws/Makefile-ws.am
src/ws/fatal.conf
test/common/testlib.py
tools/cockpit.spec

It is rather impractical to ship a static configuration file in
cockpit-tests. It will get in the way once we ship a default one in
cockpit-ws [1], and a lot of tests have not actually used it as
(1) nonDestructiveSetup() removes an existing cockpit.conf after each
test, and (2) a lot of tests set up their own cockpit.conf.
Instead, create it dynamically in MachineCase.setUp().
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1816044

ws: Eliminate static cockpit.conf from cockpit-tests

---

test/verify/check-services

Commit e93698e6a fixed testNotifyFailed(). Fix testHiddenFailure() in
the same way, so that a failure to load available updates does not get
in the way.

test: Make check for no failed services more robust, take #2

---

test/verify/check-networking-bond
test/verify/check-networking-checkpoints

Recent versions don't install dhclient by default any more, and NM uses
its internal DHCP client. So this test does not work any more.

test: Skip dhclient-modifying tests on Fedora CoreOS

---

pkg/machines/app.jsx
pkg/machines/components/networks/createNetworkDialog.jsx
pkg/machines/components/networks/networkList.jsx

Virtual networks on qemu:///session do not have any use case and such virtual network cannot be even used. Remove selection of connection since it's pointless, making qemu:///system default and only option. 
Fixes: #13617

machines: Disable qemu:///session for Virtual Network creation

---

test/common/testlib.py

Example logs:
- https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13837-20200403-111315-157ca9c7-fedora-coreos/log.html
- https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13837-20200403-083858-157ca9c7-fedora-coreos/log.html#65

test: Restart sssd for non-destructive tests

---

test/common/testlib.py

This avoids
Warning: Stopping cockpit.service, but it can still be activated by:
cockpit.socket
between all nondestructive tests.

test: Stop cockpit.service quietly

---

pkg/machines/components/deleteResource.jsx
pkg/machines/components/networks/network.jsx
pkg/machines/components/vmDisksTab.jsx
pkg/machines/components/vmnetworktab.jsx

PF4 React Table component sometimes recreates the components inside Table rows,
and then showModal will revert to false, causing the dialog to close.
By keeping the state outside of the Table components we can rely
on the dialog staying open.
Note: Commit 20963cb addressed a similar issue with different approach.
In our case that approach is not adequate because we need to keep
information about more state properties than just the visibility of the
modal.
Fixes #13860

machines: Split DeleteResourceSource component to avoid nesting statefull modals inside table rows

---

test/verify/check-multi-machine
test/verify/check-packages
test/verify/netlib.py

This is generally error prone, and specifically bad on OSTree. Use bind
mounts instead to fake things.
Make check-packages @nondestructive, so that restore_dir() will do the
temporary bind mount for us. That test is also super-quick (boot time
dominated the test time).
Make netlib.py helpers nondestructive as well, which will help with
making bond and vlan tests fully nondestructive.

test: Eliminate writing to /usr

---

pkg/machines/components/vmnetworktab.jsx

* /sys/class/net can contain other things than symlinks to interfaces,
e. g. `bonding_masters` (after `modprobe bonding`). Use find instead
of ls to only pick the symlinks.
* Fix showing the error message; previous code only showed
`<unavailable>` in the console, as the error message from spawn is an
object.
* It was not obvious what the pop() was doing; replace with trim(), as
the purpose is to avoid getting an empty element after the final \n.
* Use standard JS promise API.
Fixes commit fc3dbd91de

machines: Fix network device detection

---

test/verify/check-machines-dbus

It's also possible to create the test network after the page was loaded
(how we used to do it) and just wait for the the internal state to get updated,
before opening the dialog which uses the newly added resource, but this is
prompt to be more unstable than just creating the necessary resources
before page load.
Fixes #13861

tests: Robustify testNICAdd by creating the test Virtual Network before page load

---

pkg/networkmanager/interfaces.js
test/verify/check-networking-bond

After calling "select_btn_select(btn, choice)", we want "select_btn_selected(btn) == choice".
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1817948

networking: Fix explicitly selecting a select button choice

---

pkg/apps/application-list.jsx
pkg/apps/application.css

It was misbehaving in some locales, like Japanese otherwise.
Also style that installed and non-installed apps align.
Before:
Now:

apps: Use flex instead of table in caption

---

pkg/machines/components/libvirtSlate.jsx
pkg/packagekit/updates.jsx
test/verify/check-packagekit
test/verify/machineslib.py

Fixes #13895
I could find only these two places where we use also secondary options.
There may be some places I missed? (if you can find some, please let me know). But they most likely don't use this empty state component so they should be migrated as well.
@garrett 
Now looks like:

Change empty state secondary buttons to use link-styled buttons

---

pkg/sosreport/index.html
pkg/systemd/graphs.html
tools/webpack-make

In language files (like 'de.po') we refer to manifest files like
`pkg/sosreport/manifest.json.in`. This is later on used with `msggrep`
to only include relative files. Looking for `manifest.json` did not
return any results and therefore we would not translate things in shell
like labels or help menu items. (We would translate it only if the same
string comes also from different location, which was the case for
majority of label as <title> usually has the same string.)

tools: When filtering manifest files look for '.in'

---

test/verify/check-machines-dbus

Specify a type and source in the "permanent attachment to running VM"
check. Otherwise it's going to default to "Direct attachment" and try to
use whichever real interface happens to be first. This is almost
certainly going to fail, as e. g. "lo" can't be attached (resulting in
"invalid argument") and vnet0 or most other interfaces are already busy.

test: Fix Machines testNICAdd permanent attachment

---

test/verify/check-system-info

systemd-timesyncd got split out recently into a separate package,
conflicting with chrony, see
https://github.com/cockpit-project/bots/pull/757

test: Drop chrony purging from debian-testing

---

test/README.md

- slightly restructure the document, adding a "Helpful tips" section
- describe how to conduct manual testing with bots/vm-run
- mention chrome://flags/#allow-insecure-localhost
- describe how to set up an ssh alias

tests: add some tips to README.md

---

containers/bastion/Dockerfile
containers/ws/Dockerfile

Our copr does not build Fedora 30 packages any more, so building the
official cockpit/ws currently fails on Dockerhub.
[DockerHub failure log](https://hub.docker.com/repository/registry-1.docker.io/cockpit/ws/builds/021b2e2a-dd8e-4ba9-9ec2-36b213af6d3d)

containers: Bump bastion and ws containers to Fedora 31

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

Previously when `virt-install` was not available the condition
evaluated to 'true' since `this.state.virtInstallAvailable !==
undefined` is truthy.
The test was also not properly checking the disabled button
functionality since when freshly loading the page the button is always
disabled for a fraction of a second. This commit fixes the test as well
to perform a more robust check.
This fixes the testDisabledCreate flake test - with failures such as 
https://logs.cockpit-project.org/logs/pull-13695-20200416-160442-23b1ea4b-rhel-8-2-distropkg/log.html#192-2
or 
https://logs.cockpit-project.org/logs/pull-13695-20200416-160442-23b1ea4b-ubuntu-2004/log.html#192-2

machines: Fix condition for disabling 'Create' button

---

pkg/machines/components/networks/createNetworkDialog.jsx
test/verify/check-machines-dbus

When user selected "None" IP configuration, virtual networks would
still have defualt IP configuration.
Fixes: #13893

machines: Fix no IP configuraiton for virtual networks

---

pkg/systemd/overview-cards/motdCard.scss

Instead of relying on margin, content in the overview grid relies on the
grid gap for spacing.
Fixes #13884
After this commit:

overview: remove bottom margin under motd

---

src/base1/test-http.js

Commit 9afcaabd5c65 introduced a new playground page, which broke
test-http.html.

base1: Adjust test-http for recent playground change

---

pkg/systemd/README-realmd.md

The "services" image recently grew a Samba AD server [1], document how
to use it.
Manually testing Cockpit, realmd, or any other part of the OS against
Microsoft Active Directory can easily be done with an AWS managed domain
controller, document that as well.
Also add the missing /run-freeipa step that was introduced in
https://github.com/cockpituous/bots/commit/9ebea751e
[1] https://github.com/cockpit-project/bots/commit/b13ed9db

systemd: Add instructions how to test Active Directory
