cockpit-project/cockpit

- test/verify/check-networking-bridge
- test/verify/check-networking-team
This is relatively straightforward now, except for the different behaviour of "same IP", that @mvollmer and I discussed in the above PR.
With that we have parity with Selenium tests in the networking area. For now I'd like to keep the other tests destructive with `provision`, so that we have a few tests that exercise "real" (well, QEMU) network interfaces.
> Make team and bridge tests nondestructive

- test/common/testlib.py
ssh usually tries to set the client locale into the server ssh session,
even though they don't exist there. This often causes tests to fail with
invalid or unusable locale: en_US.UTF-8
unexpected messages. The latest cockpit/tasks container refresh seems to
have subtly changed the locale configuration, so that this now fails
every Debian test.
Not having any non-C locales on Debian images is deliberate, as we want
to test this scenario somewhere. So just ignore that error.
> test: Ignore "invalid locale" messages on Debian

- test/verify/check-storage-luks
Test passes without it and it only breaks the test.
(well, TBH I haven't tested it, but lets try it here)
> test: Skip tangd-update.service hack on rhel-7-9

- pkg/systemd/overview-cards/systemInformationCard.jsx
- test/verify/check-system-info
Implementing issue #13541  for displaying the system uptime in the System Information card on the Overview page.
> systemd: Display uptime on overview page

- HACKING.md
- src/base1/cockpit.js
The window.debugging = "all" command can be used in the
javascript console to produce lots of debug output. However
the more specific messages such as "spawn" were hard to use
since one had to set that global in the relevant frame,
or use localStorage and refresh.
We now set things up to automatically reflect the storage
debugging variables in each frame, via a getter/setter.
The sessionStorage overrides localStorage if both are set.
In addition we add documentation for this mechanism.
> base1: Document and fix up javascript debugging

- pkg/packagekit/updates.jsx
Before:
Notice the two English strings in the header. This PR fixes both.
> Fix early translations in packagekit

- doc/man/cockpit.conf.xml
- pkg/shell/base_index.js
- test/verify/check-menu
Common Criteria [1] only require the availability of an idle auto-lock,
not that it's enabled by default. As Cockpit is never the primary
session on a device, it makes more sense to let the login/window manager
(desktop) or screen lock (mobile devices) take care of protecting the
session.
Instead, let's rather implement an automatic timeout of sudo privileges,
once that rework is in place. That will mimic the behavior of the
command line (ssh + sudo).
Also add some code cleanups:
* Only set up the idle timers in the shell if the timeout is non-zero.
This isn't as easy to do in the frames, as we currently don't block
frames construction on the GetUInt(IdleTimeout), but it helps a bit.
* Rename setupTimers() to a more specific setupIdleResetTimers().
* Fix listening to scroll events.
* In …
> shell: Disable idle timeout by default

- pkg/machines/libvirt-dbus.js
`ex` is an object and thus not directly printable. Consistently turn it
into a string so that the warning becomes useful. Other places already
used `JSON.stringify()`, which works, but is a bit harder to read.
Also use catch() consistently.
> machines: Fix D-Bus error messages

- test/verify/check-journal
It was unreliable before and still is not parsed sometimes.
Example failure: https://logs.cockpit-project.org/logs/pull-13948-20200422-200356-e4a8ea2c-fedora-31/log.html#50-2
> test: Don't check crash function name

- pkg/systemd/overview-cards/motdCard.jsx
- test/verify/check-system-info
Initial empty lines are commonly used to separate multiple motd.d/
entries from one another, but we don't show these. They look bad in the
Alert box, so strip them. But still retain leading spaces, as they are
commonly being used for ASCII art.
> systemd: Strip leading empty lines in motd

- pkg/systemd/services/services.jsx
Since we preload the Services page, try to minimize the amount of DBus API
calls we do when it's running in the background. In this case we are
only interested in the failed units, so that we set the Page Status
which appears in the overview page and in the shell.
In addition, in order to get the processFailedUnits function to really
run after the API calls are done, we needed to chain the promises
properly.
> services: when the page is hidden just list the failed units and return

- src/ws/cockpitwebservice.c
- test/verify/check-realms
Identity management domain users are usually case insensitive, in
particular the domain part. E. g. with FreeIPA, "user@domain" and
"user@DOMAIN" mean exactly the same. With AD, even the user name is case
insensitive, and in fact the canonical name starts with an upper case
("Administrator@DOMAIN").
Linux' canonical form (reverse resolution of uids, or `$USER`) is
lower-case, though. This led to a failed "original vs. challenge
subject" string comparison in authorize_check_user(), resulting in
sessions not getting root privileges.
To fix this, if a direct comparison fails, compare again against the
lower-case form of the credential's user name. This avoids having to
decode the subject's hex string and thus introducing more protocol
assumptions.
Note that native Linux user names are case …
> ws: Accept upper-case login names for ssh/polkit agent challenges

- pkg/lib/page.scss
For some reason, paragraphs have lost margins between PF3 and PF4. And subsequent paragraphs do not have spacing between themselves, so I'm re-adding this to all of Cockpit.
We usually don't use paragraphs next to each other, but sometimes we do.
> lib/page: Re-add space between paragraphs

- test/verify/check-dashboard
Commit 313ee7ac replaced previously used "hacklib" with disabling
preloading on just the default machine. However in this test we actually
switcher between three machines quickly, which makes the issue even
worse.
Example failure: https://logs.cockpit-project.org/logs/pull-13905-20200424-092742-2c601399-fedora-31/log.html#214-2
I noticed that since yesterday we got quite a few of these failures. I haven't seen them before, so I assume it must be it.
> test: Disable preloading of machines in dashboard

- test/verify/run-tests
We control the timeout outside of the actual test, thus the test has no
chance to call its cleanup handlers. This causes all subsequent serial
tests to fail as well. Recreate the test VM in this case.
Also, try harder to get a complete log for these tests, as they don't
properly flush their stdout themselves.
Fixes #13971
> test: Restart persistent VM on serial tests which time out

- pkg/kdump/kdump.js
- pkg/machines/index.js
- pkg/packagekit/updates.jsx
- pkg/storaged/devices.jsx
- pkg/storaged/nfs-details.jsx
- pkg/systemd/hwinfo.jsx
- pkg/systemd/overview.jsx
- pkg/systemd/services/services.jsx
- pkg/users/local.js
Edge 11 still doesn't know about Promise.finally(), which caused the
Services page to crash since the React rewrite.
Also change all other pages to do the import in the same style.
> pkg: Import polyfills on all pages that use finally()

- test/verify/check-storage-luks
Fails with:
```
Failed to reset failed state of unit tangd-update.service: Unit tangd-update.service not loaded.
Failed to restart tangd-update.service: Unit tangd-update.service not found.
```
As found in https://github.com/cockpit-project/bots/pull/762
> test: Skip tangd hack on centos-8

- test/common/testlib.py
This message does not provide much information. We may actually know
about the real problem and may have naughty for it. Failing on this
message does not help us in any way.
> test: Don't fail on `Failed to generate stack trace: (null)`

- doc/authentication.md
- doc/guide/authentication.xml
- doc/guide/cert-authentication.xml
- test/verify/check-realms
authentication.md was wrong about what exactly the authentication schema
is for Kerberos/GSSAPI. Show the precise identifiers in cockpit.conf,
and give an explicit example how to disable kerberos. Fix the same error
in the certificate authentication docs.
Add a link to the primary server authentication docs to make this easier
to find.
Add a test case to make sure that this actually works.
Thanks to @H20-17 for discovering this!
Fixes #13036
Fixes #13202
> doc: Document how to disable kerberos negotiation

- HACKING.md
- Makefile.am
- tools/README.dist
- tools/webpack-make
- tools/webpack-watch
- webpack.config.js
Watch mode makes fast iterations much faster. Compared to plain `make`,
watch mode and disabling eslint reduces e. g. tuned from 19s to 3s, or
systemd from 48s to 17s on the first rebuild, and 5s (!) on the second.
> tools: Add watch mode to webpack-make

- HACKING.md
Since we fixed vm-run to provide a reasonable default networking with
the windows-10 image, we don't need to create a bridge on the host any
more. This avoids messing up the host's networking and requiring root
privileges, and also works fine in podman.
[1] https://github.com/cockpituous/bots/commit/3287a378
> HACKING: Avoid bridge on the host when starting windows-10

- test/verify/check-setroubleshoot
Fedora 31 contains `ipa_custodia` rule, which is not on rhel/centos
machines. That means that when we generate script on these machines and apply
it to the f-31 one, they are not the same, as we don't remove all rules
and don't do anything specific about modules.
Just remove this rules from the ansible machines as rhel/centos don't
modify it and fedora contains it, so it will set it back up.
> test: Cleanup modules on ansible machine

- doc/authentication.md
Commit 1faa25851 added some documentation how to disable Kerberos
authentication. But its not the browser which initiates it, it's the
server (if GSSAPI is available).
Thanks to @H20-17 for spotting!
> doc: Clarify GSSAPI authentication

- tools/cockpit.spec
Very often, Fedora's s390x koji builders are extremely slow, and failing
random unit tests. This is not reproducible on a beaker machine, nor did
it ever happen on Debian or Ubuntu's builders. As the koji builders are
not accessible for debugging, and there is no discernible property
(cpuinfo, virtualization, etc.) between builds that work and those that
don't,  just generally make unit tests non-fatal on s390x.
This is a desperate measure, but this has broken our releases for many
months now, and we otherwise stuck with that.
See issue #13909
> tools: Make unit tests non-fatal on Fedora s390x

- pkg/machines/components/nicEdit.jsx
- pkg/machines/components/vmDisksTab.jsx
- pkg/machines/components/vmnetworktab.jsx
(should robustify [testNetworkSettings](https://jenkins-continuous-infra.apps.ci.centos.org/job/fedora-rawhide-pr-pipeline/3295/artifact/package-tests/logs/FAIL-str_verify.log)) flake test
> machines: move nicEdit modal dialog out of the Table rows

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/timer-dialog.js
This gets rid of about 40% of D-Bus messages (2733 → ~ 1687 on my
systemd for a single Services page load, or 316 → 258 during preloading
on Overview), mostly due to only getting one (unnecessary)
UnitNew/UnitRemoved signal pair per unit instead of two.
This also will give us a more fine-grained control about which
signals/property changes to listen to, and when.
> services: Avoid using D-Bus proxy on systemd Manager object

- pkg/storaged/luksmeta-monitor-hack.py
- test/verify/check-storage-luks
When reloading a page, Cockpit correctly closes all channels, which
will correctly kill all processes spawned via cockpit.spawn.  Child
processes of those processes will usually also exit on their own
because they get their stdin/stdout closed.
The "udevadm monitor" process spawned by luksmeta-monitor-hack would
not get killed on a page reload however, since it doesn't immediately
react to having its pipes closed, since it doesn't read from stdin and
doesn't write to stdout frequently enough.
Thus we make sure it is killed explicitly.
> storage: Don't leave udevadm processes behind on page reload

- test/common/testlib.py
- test/verify/check-journal
By setting `allow_core_dumps` to `True` we say that we should not check
for coredumps in journal. Lets also not save them.
While on it, I moved this setting to `crash()` in test-journal, as it
makes more sense there.
Part of #13854
> tests: When allowing coredumps, don't save them

- .eslintrc.json
- pkg/docker/containers-view.jsx
- pkg/lib/cockpit-components-listing.jsx
- pkg/machines/components/diskEdit.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/overview.jsx
- pkg/storaged/storage-controls.jsx
- pkg/systemd/overview-cards/insights.jsx
- pkg/systemd/overview-cards/systemInformationCard.jsx
- pkg/systemd/overview-cards/usageCard.jsx
- pkg/systemd/page-status.jsx
- pkg/systemd/services/service-tabs.jsx
- test/verify/check-docker
This rule is actually very useful, as it points to things, that are not
keyboard navigable. We were introducing new breakages since we disabled
this rule (like services and overview pages).
Here is list of things that did not work before, but do now:
- service-tabs.jsx: The whole navigation (targets, sockets...) was not
reachable by keyboard.
- page-status.jsx: Items in 'Health' card were reachable by keyboard,
but could not be activated by keyboard.
- usageCard.jsx: Text 'View graphs' on 'Usage' card was reachable by
keyboard, but could not be activated by keyboard.
- systemInformationCard.jsx: Text 'View hardware details' on 'System information'
card was reachable by keyboard, but could not be activated by keyboard.
- insights.jsx: Text 'Not connected to Insights' on 'Health' card was …
> Fix keyboard navigation

- pkg/storaged/luksmeta-monitor-hack.py
Calling sys.exit will throw an exception to get its job done, and if
that happens at the wrong moment, we get a backtrace like this:
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7fb30d260048>>
File "/usr/lib64/python3.6/subprocess.py", line 785, in __del__
File "<stdin>", line 115, in sigexit
SystemExit: 0
In order to avoid this, let's just do everything directly in the
signal handlers and exit cleanly via os._exit().
Fixes #14011
> storage: Cleaner exit for luksmeta-monitor-hack

- tools/cockpit.spec
`cockpit-system` on rhel bundles some other packages, like c-selinux and
c-sosreport. Make sure that this package has the same `Requires` as its
standalone counterparts.
`cockpit-sosreport` requires `sos` and `cockpit-selinux` requires, not
recommends, setroubleshoot-server.
> specfile: Fix up requires for cockpit-system

- test/verify/check-login
Sometimes this test failed with `sudo: 2 incorrect password attempts`.
> test: Allow authorize messages in check-login testBasic

- doc/guide/cockpit-channel.xml
- doc/guide/cockpit-dbus.xml
- doc/guide/cockpit-file.xml
- doc/guide/cockpit-http.xml
- doc/guide/cockpit-session.xml
- doc/guide/cockpit-spawn.xml
We have deprecated the old jQuery .done()/.fail() API a long time ago,
no new code should be written with it any more. Also, these days
promise callbacks are usually written with arrows, to get sane `this`
behaviour. All browser engines have supported arrows for many years now.
This will better reflect real code and make the Cockpit API easier to
relate to standard JS.
> doc: Use standard Promise API and ES6 arrow handlers

- examples/pinger/ping.html
- examples/pinger/pinger.js
* `<pre>` does not belong into `<p>`, it's a block element on its own.
(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre)
* Define a constant for the button element as well, for consistency.
* Use standard JS Promise API instead of the obsolete jQuery one.
* Use some modern ES6 syntax, all browsers have supported that for a
long time.
> examples: Modernize pinger

- test/verify/machineslib.py
In the create VM dialog we don't show distributions whose EOF support
finished more than a year ago.
testCreate machines test  which was expecting it started to fail.
Just use the default CirrOS for the failing test.
Split out of #14015 in order to merge faster.
Please fix the Closes line on merge.
> tests: OpenBSD 6.3 is not supported for 1y already now (3/5/19)

- test/common/testlib.py
How to test:
```
--- test/common/testlib.py
+++ test/common/testlib.py
@@ -946,9 +946,6 @@ class MachineCase(unittest.TestCase):
"xargs: basename: terminated by signal 13",
-        # SELinux messages to ignore
-        "(audit: )?type=1403 audit.*",
-        "(audit: )?type=1404 audit.*",
"(audit: )?type=1400 audit.*: avc:  granted .*",
```
`./test/verify/check-setroubleshoot TestSelinux.testEnforcingToggle` fails with:
```
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1404 audit(1588661472.381:367): enforcing=0 old_enforcing=1 auid=1000 ses=4 enabled=1 old-enabled=1 lsm=selinux res=1
```
then running ` TEST_ALLOW_JOURNAL_MESSAGES="(audit: )?type=1403 audit.*,(audit: )?type=1404 audit.*" ./test/verify/check-setroubleshoot …
> test: Possibility to add allowed messages from ENV

- pkg/networkmanager/interfaces.js
- test/verify/check-networking-checkpoints
- test/verify/netlib.py
A long settle_time time causes the checkpointing race to get pretty
tight, and checkpoints would be unexpectedly rolled back in our
integration tests.  On the other hand, we had to increased the
settle_time in 7b115d15f44aa and f1d06abedaee50d to make the
checkpointing tests themselves more robust.
Thus, we reset the settle_time to something that is appropriate for
manual use, switch off checkpointing entirely for most of the
integration tests, and use a long settle_time when testing checkpoints
themselves.
Fixes #13821
> networking: Avoid checkpointing in tests and use custom settle_time

- Makefile.am
After an install from source, the builder's uid leaks on the manifest.json file.
Specifying the `--no-same-owner` prevents it from occurring.
Before:
```
[archie@d47f818d4c65 cockpit-218]$ sudo make install -j 4
[...]
[archie@d47f818d4c65 cockpit-218]$ ls -al /usr/local/share/cockpit/users
total 224
drwxr-xr-x  2 root   root     4096 May  5 19:04 .
drwxr-xr-x 23 root   root     4096 May  5 19:04 ..
-rw-r--r--  1 root   root     3222 May  5 19:04 index.html.gz
-rw-rw-r--  1 archie archie    751 May  5 18:58 manifest.json
-rw-r--r--  1 root   root     2605 May  5 19:04 po.ca.js.gz
```
After:
```
[archie@9b3ee741a9ad cockpit-218]$ ls -al /usr/local/share/cockpit/users
total 224
drwxr-xr-x  2 root root   4096 May  5 19:32 .
drwxr-xr-x 23 root root   4096 May  5 19:32 ..
-rw-r--r--  1 root …
```
> Fix manifest ownership on install

- tools/webpack-make
The results of incremental runs of webpack are not really good enough
for 'official' things like creating images for CI.  For example, the
_OUTPUT and _INSTALL variables in Makefile.deps are not always
correct.
> tools: Force a "make" run after incremental webpacking

- pkg/shell/index.html
The dialog does nothing else now.
> shell: Rename "Authentication" to "SSH Keys"

- test/common/testlib.py
- test/verify/check-machines
- test/verify/check-realms
- test/verify/check-terminal
libvirtd often crashes when stopping it right after starting [1]. As a
workaround, be a little less demanding, and wait for domain interfaces
to have initialized before stopping the service again.
Also make sure that the page recognized that the service started up
again and the empty state goes away.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1828207
Fixes #12978
> test: Avoid libvirtd crash in TestMachines.testLibvirt, some more test fixes

- pkg/lib/superuser.jsx
- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
The page currently relies entirely on polkit permissions for PackageKit
calls. Make sure that everything gets reinitialized when superuser
status changes. This is a blunt and simple fix for now, this will be
refined later.
> packagekit: Reload Software Updates page on superuser changes, some code cleanup

- pkg/machines/components/memorySelectRow.jsx
Relevant PF issue: https://github.com/patternfly/patternfly-react/issues/3187
> machines: remove workaround for PF3 slider component

- test/verify/check-system-info
This avoids violations of systemd-gpt-generator and possibly other
things that try to parse it.
> test: Fix SELinux context of fake /proc/cmdline

- pkg/lib/packagekit.js
- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
This properly reacts to superuser changes instead of reloading the page, and also disables auto-updates when unprivileged.
@mvollmer, of course we can also directly land this instead of #14053 if you prefer.
> packagekit: Better reaction to superuser changes

- test/verify/check-system-info
- test/verify/netlib.py
Commit 30cf873d105d880 introduced a chcon into check-system-info.
Debian/Ubuntu images do ship chcon, but don't enable SELinux, so this
failed. Use `selinuxenabled` instead like in check-connection. Also
update `slow_down_dhclient()` (where this was copied from) to
consistently use the same approach to guard chcon.
> test: Fix chcon test

- pkg/lib/cockpit-components-logs-panel.jsx
- pkg/lib/journal.css
- pkg/lib/journal.js
- pkg/lib/journal_line.mustache
- pkg/networkmanager/interfaces.js
- pkg/storaged/logs-panel.jsx
- pkg/systemd/logs.js
- pkg/systemd/services/service.jsx
- test/verify/check-services
Also making sure that 'Logs' breadcrumb on logs page correctly shows
filters that were applied in the box.
Keyboard navigation and activation is also supported. Both in embedded
logs as well as on the logs page.
Fixes #1113
> Enable going from embedded logs panel to specific log entries

- test/verify/check-machines
* wait as long as we can by monotoring the logs in order to make sure
that the OS has reached a state when it can definitely respond to live
detaching a disk.
* wait first on the virsh command line till the disk is gone before
verifying on the UI.
> tests: attempt to robustify testDetach disk

- test/verify/check-multi-machine
- test/verify/check-multi-machine-key
These tests seem to be very slow on Fedora 31 so lets try disabling
preloading.
> test: Disable preloads for multimachine tests

- pkg/lib/machine-color-picker.html
- pkg/lib/machine-dialogs.js
- pkg/lib/machine-dialogs.scss
- test/verify/check-dashboard
Originally from changes in #13663's host switcher. I split out the commits so they can be independent from that huge PR.
I reworked the way the color selector acts and functions. The positioning is now 100% CSS with no JS changes, so it is more resilient.
I've also added a commit to move the location to the right side instead of below. (This is optional; we could back out the commit before squashing, if others aren't fans. I like it though.)
Additionally, I added preliminary keyboard support (for tabbing around). However, you cannot activate colors by the keyboard (yet). That would probably require changing click handlers.
> Machines color selector

- src/common/cockpitchannel.c
- test/verify/check-terminal
When a channel applies back-pressure to its input because its output
queue is getting too large, it relies on the consumer to acknowledge the
reads by ponging to the pings that the channel sent out.
However, it can happen that the last ping was sent for a sequence number
*before* the one that the channel expects for lifting the pressure. Then
the receiver could drain the output queue and dutifully respond to all
pings, but the last sequence number would still be smaller than the
treshold for lifting the pressure. But the channel isn't sending
anything else either and thus never generates new pings.
Fix this by sending an additional ping when going into pressure mode, to
ensure that the last pong sequence number is within the out_window
again.
This can also be reproduced/investigated with …
> common: Fix deadlock in channel pressure handling

- tools/cockpituous-release
This committed an "Update to VERSION" change to our Dockerfiles to
cockpituous' cockpit repo fork's master branch. This is totally useless.
Our official cockpit/ws containers are built from the
cockpit-project/cockpit-container github repo.
> tools: Drop obsolete second release-dockerhub invocation

- test/common/testlib.py
- test/containers/check-bastion
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-login
- test/verify/check-machines
- test/verify/check-realms
- test/verify/check-superuser
- test/verify/run-tests
These messages indicate that something is wrong and they need our
attention. Just retrying it hides it and makes it harder to notice.
Also show similar message on browser errors.
How to test:
```
--- test/common/testlib.py
+++ test/common/testlib.py
@@ -946,9 +946,6 @@ class MachineCase(unittest.TestCase):
"xargs: basename: terminated by signal 13",
-        # SELinux messages to ignore
-        "(audit: )?type=1403 audit.*",
-        "(audit: )?type=1404 audit.*",
"(audit: )?type=1400 audit.*: avc:  granted .*",
```
and then 
` ./test/verify/run-tests TestSelinux.testEnforcingToggle`
Without this patch it runs the test 3 times. With this patch it does not retry at all.
> test: Don't retry on journal and browser messages

- test/common/testlib.py
This is a recent regression that breaks all machines tests:
https://bugzilla.redhat.com/show_bug.cgi?id=1835909
> test: Ignore qemu-kvm → /dev/mapper/control SELinux policy violation on rhel-8-3

- test/verify/check-pages
After tickling the frame to reload, wait for that to happen. Otherwise,
if that happens a bit more slowly, the subsequent `data-ready` wait is a no-op, and
`#file-content` never gets visible as the test still looks into the old
(and now destroyed) page context.
----
Example: https://logs.cockpit-project.org/logs/pull-14098-20200517-193551-1a756276-fedora-coreos/log.html#180-2
> test: Fix race condition in TestPages.testFrameReload()

- Makefile.am
Similar to commit 90db3d2da7, prevent eternal hangs of the C unit tests.
This has commonly caused long-hanging semaphore or koji/brew builds.
> test: Add C unit test timeout

- .eslintrc.json
- pkg/storaged/dialog.jsx
- pkg/users/index.html
- pkg/users/local.js
- test/verify/check-multi-machine
Lets use <ul> and <li> since it is actually list.
Also use 'role="presentation"' to indicate that the box itself has no
semantic meaning, it just is wrapper that catches events when user click
anywhere on the box.
Also did one small change for sliders in storage where I added
'role="presentation"' so it is not used in a11y tree. We always have
input next to this slider for it to be accessible. Making fully
accessible slider is not that complicated, but the goal with our sliders
always was that they are ignored when using keyboard and users will just
use inputs.
That also makes it possible to enforce another a11y jsx rule.
> users: Make users list correctly accessible

- pkg/systemd/logs.js
The old behavior had two issues:
1. It was not working when the page was translated (#13902)
2. It was prone to races (#14037)
Fixes #13902
Fixes #14037
Tested it locally and it all seems to work as expected. Also ran testBasic 10 times and succeeded every time. Let's see if CI agrees with me.
> logs: Keep state in variables and don't parse it from HTML

- src/common/test-webserver.c
If cockpit_test_find_non_loopback_address() finds an IPv6 address, then
we can't just concatenate `:port`, but need to enclose the address in
`[]`. g_network_address_parse() supports that syntax for IPv4 as well.
Many thanks to Aurelien Jarno for the fix!
https://bugs.debian.org/960752
> test: Fix test-webserver port address formatting for IPv6

- test/verify/check-setroubleshoot
- test/verify/check-terminal
A few months ago, Chromium changed the clipboard related permissions
(it's an experimental API). Use the new ones, and fall back to the old
ones until we update our cockpit/tasks container [2].
[1] https://chromedevtools.github.io/devtools-protocol/tot/Browser/#type-PermissionType
[2] https://github.com/cockpit-project/cockpituous/pull/327
> test: Adjust to changed clipboard permissions in current Chromium

- pkg/lib/packagekit.js
- test/verify/check-packagekit
- test/verify/check-terminal
To unbreak https://github.com/cockpit-project/bots/pull/873 and evade https://bugzilla.redhat.com/show_bug.cgi?id=1837461 - that old API is really starting to break down.
-  [x] Adjust naughty patterns: https://github.com/cockpit-project/bots/pull/884
> RHEL 7.9 PackageKit/rhsmd backports

- tools/cockpit.spec
Commit 4b112e2c turned the recommends into a requires. But
setroubleshoot-server is in AppStream, so this is invalid. Revert this
part.
https://bugzilla.redhat.com/show_bug.cgi?id=1838003
> tools: Revert cockpit-system → setroubleshoot-server dependency on RHEL

- test/common/testlib.py
This is just noise if we can only get one line saying that some process
dumped core.
If there is also stack trace, it will fail on that and will actually
show it in the test result.
Should deal with annoying reports like [here](https://logs.cockpit-project.org/logs/pull-13663-20200520-110435-5db84413-fedora-32/log.html).
> test: Don't fail on coredump message when failed to generate core

- configure.ac
Added a feature to turn polkit on and off. With this feature auto-detection problems can be avoided (OpenWRT and Yocto < 2.3).
Issue #14052
Extend #13963
> feat(polkit): add configuration feature to disable polkit

- configure.ac
Detects the misconfiguration if polkit is enabled but not installed.
> build: detect misconfiguration of polkit

- test/verify/check-testlib
- test/verify/run-tests
This allows downstream tests to run nondestructive tests in the same
manner as upstream -- with test retries, naughties, and not having to
specify the check-* command.
> test: Add --machine/--browser options to run-tests

- tools/cockpit.spec
- tools/debian/control
The new integrated host switching obsoletes most of the dashboard use
cases, and we don't want to promote the "remote server graphs" feature
much as it's really not very good.
Also adjust the package description, as cockpit-ssh moved into
cockpit-bridge a long time ago already.
> tools: Drop cockpit-dashboard recommendation from cockpit metapackage

- test/common/parent.py
- test/common/run-tests
- test/run
- test/verify/check-testlib
- test/verify/parent.py
This should fix TAP output for external projects using the cockpit test
infrastructure.
> test: Move run-tests to test/common

- test/verify/check-machines
Some Machines tests check adjusting the guest RAM size to the maximum of
what the host has available. The formatting of the usage donut then
depends on whether that results in a size < 1 GiB (in which case the
usage will be formatted in MiB) or > 1 GiB (then it will be GiB). Thus
replicate the cockpit_format_bytes() logic in the test to work with
testbeds that have more RAM.
This doesn't affect the creation dialog itself, just the donut check; so
move the text computation logic out of the VmDialog class.
--- 
I locally tested this against our current 1 GiB test VMs as well as an 1.1 GiB one from https://github.com/cockpit-project/bots/pull/890
> test: Adjust Machines tests for test VMs with 1 GiB RAM

- test/common/testlib.py
- test/verify/check-login
It seems like the best way to document that cockpit is intended to work
with pam_tally2 is to put it under our integration tests.
Let's upload this WIP to see which bots fail horribly: that should give
us an idea of where this test can be run.
> test: add integration test for pam_tally2/faillock

- pkg/machines/libvirt-dbus.js
- test/verify/check-machines
Starting a pool might fail for multiple reasons, aka target host unreachable,
and it takes some time until the operation times out. Until then we are seeing
the dialog spinner and a frozen dialog and we need to wait even a mibute
untill the API call times out and we get an error message.
Furthermore a user might want to just define resource and activate it later
on when the target storage is available.
Closes #14114
> machines: When creating a storage pool don't try to activate it

- pkg/networkmanager/firewall.jsx
- test/verify/check-networking-firewall
OLD:
And reload the page when access level changes.
When access is limited all zone sections are shown as empty, which is
not very useful.  So we hide them altogether.
> networking: Hide Firewall actions when access is limited 

- test/verify/check-multi-machine
Just adding fips=1 kernel argument is not sufficient any more, booting
breaks completely then. Use `fips-mode-setup --enable` if available,
which is the officially documented way of enabling FIPS on RHEL 8.
See https://bugzilla.redhat.com/show_bug.cgi?id=1839963
This fixes known  issue https://github.com/cockpit-project/bots/issues/904
> test: Fix FIPS mode enabling on RHEL

- test/common/run-tests
- test/verify/check-networking-basic
- test/verify/check-networking-checkpoints
- test/verify/check-networking-mac
- test/verify/check-networking-mtu
- test/verify/check-networking-other
- test/verify/check-networking-settings
- test/verify/check-networking-unmanaged
- test/verify/check-networking-vlan
- test/verify/check-storage-basic
- test/verify/check-storage-format
- test/verify/check-storage-hidden
- test/verify/check-storage-ignored
- test/verify/check-storage-iscsi
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-msdos
- test/verify/check-storage-multipath
- test/verify/check-storage-nfs
- test/verify/check-storage-partitions
- test/verify/check-storage-raid1
- test/verify/check-storage-resize
- test/verify/check-storage-scaling
- test/verify/check-storage-unused
- test/verify/check-storage-used
- test/verify/check-storage-vdo
So that we can select them properly with run-tests. Otherwise classes
with the same name hide each other.
Also eliminate `dataclass` from  run-test, it's still too new for RHEL 8.
> test: Rename test classes to be unique

- test/verify/machineslib.py
Some Machines tests check adjusting the guest RAM size to the maximum of
what the host has available. The formatting of the usage donut then
depends on whether that results in a size < 1 GiB (in which case the
usage will be formatted in MiB) or > 1 GiB (then it will be GiB). Thus
replicate the cockpit_format_bytes() logic in the test to work with
testbeds that have more RAM.
This doesn't affect the creation dialog itself, just the donut check; so
move the text computation logic out of the VmDialog class.
Cherry-picked from master commit 3ceac9489d2f0
> [r82] test: Adjust Machines tests for test VMs with > 1 GiB RAM

- test/verify/check-machines
We write the year 2020. Forgotten by the masses, and shadowed by the
turmoils of the COVID-19 pandemic, a little gray Linux distribution took
its last breath and withered away. The big Lib Virt forgot about its
once loved child, and refused to ever look at it again.
But a small group of intrepid developers put on their red helmets^Whats,
mounted their cockpit, and went out to salvage it. Never shall the world
forget "Fedora 28" again, and it will still stand strong long after
every other penguin in the world ate their last fish.
---
Boring technical epilogue: libvirt only allows installing a distribution
up to a year after its EOL. Make sure that we don't run into that trap
anytime soon again.
> test: Fake EOL date of Fedora 28

- doc/urls.md
- examples/xhr-proxy/manifest.json
- examples/xhr-proxy/xhrproxy.html
- examples/xhr-proxy/xhrproxy.js
- test/verify/check-examples
This is an example how to monkey-patch XMLHttpRequest() for HTTP
requests to a local service port.  Cockpit pages cannot use the standard
XMLHttpRequest() due to its strict Content-Security-Policy, so these
need to be wrapped into a raw cockpit channel and be done from the host
where the session runs.
At the same time this also demonstrates how to talk to a port from JS
that is only accessible locally on the cockpit session machine, i. e.
where cockpit's channel acts as a proxy.
> examples: Add XMLHttpRequest proxying through a Cockpit channel

- src/ws/main.c
This was done 5 years ago in commit 0750a1024586d23 to disable SSL3.
This is the default these days, and that setting is now invalid with
recent GnuTLS/glib versions:
G_TLS_GNUTLS_PRIORITY is invalid; ignoring
Drop it and rely on the OS defaults. Our integration test will still
make sure that SSL3 and other old ciphers won't work.
> ws: Stop setting G_TLS_GNUTLS_PRIORITY

- pkg/lib/machines.js
- pkg/networkmanager/firewall-client.js
- pkg/realmd/operation.js
- pkg/selinux/setroubleshoot-client.js
Cockpit should always use the maximum privileges it has.  Otherwise
actions might be rejected that are actually allowed.
Cherry-picked from master commit 168f819ebd, restricted to a safe and
non-intrusive subset.
https://bugzilla.redhat.com/show_bug.cgi?id=1841559
> all: Add { superuser: "try" } for things that might need Polkit

- test/README.md
Generic image handling tools and image description are done in bots, so
refer to its documentation instead [1]. The image list was also
outdated.
Stop mentioning `$TEST_DATA`, as it's deprecated and will go away soon.
[1] https://github.com/cockpit-project/bots/pull/941
> test/README.md: Refer to bots documentation for images

- pkg/shell/nav.scss
Moving the focus ring a little bit away from navigation text makes it easier to read the focused element.
> nav: Nudge focus ring offset by a small amount

- test/image-prepare
We are going to eliminate `$TEST_DATA`, it currently influences too many
things which really don't belong together. There is little reason to put
the built rpms into some user-controlled path -- in particular, we
*don't* want to put them into some persistent and possibly remote
storage if `$TEST_DATA` points to a container volume.
get_temp_dir() is too unspecific to be used as public API, so let's
eliminate it. This is the only consumer outside of bots itself.
> test: Drop get_temp_dir() usage from image-prepare

- test/common/cdp.py
We need to use firefox nightly since shipped versions don't include
`--remote-debugging-port` option. For this we want to disable automatic
updates.
Also we need `remote.frames.enabled` due to https://bugzilla.mozilla.org/show_bug.cgi?id=1593226
> test: Fix preferences for new Firefox

- test/verify/check-journal
- test/verify/check-system-info
This fixes the new [TestJournal flake](https://logs.cockpit-project.org/logs/pull-14187-20200604-183640-0593dbc0-debian-testing/log.html#136-2), and also simplifies a test that I noticed while debugging the coreos kernel oops. That will need a naughty, though.
> Fix TestJournal flake, simplify TestSystemInfo

- pkg/machines/scripts/create_machine.sh
- pkg/machines/scripts/install_machine.sh
- test/verify/check-machines
We were passing this parameter so that when the VM installation finishes
it won't automatically reboot. It will stay alive and if the user tries
to reboot it, it will just shut off, because the installation VM config is
always set up with <on_reboot>destroy</on_reboot>.
Some more info for understanding the virt-install logic here:
When creating a new VM through virt-install we have two steps:
1) the install phase, where the guest is set to boot off the fetched/supplied kernel/initrd
2) the post-install phase, where the guest is set to boot off <disk>
In order for the post-install config to actually take effect, the VM needs to be
fully powered off, after which libvirt will replace the 'install phase'
config with the 'post-install config'.
So, virt-install will force on_reboot=destroy, so …
> machines: Remove --noreboot parameter to virt-install for VM installation

- test/common/run-tests
- test/common/testlib.py
The global machine is created when running non-destructive tests without
passing `--machine`. It is created without networking and there is no
way for a test to override this default.
The machines we run non-destructive tests against usually have
networking enabled. Thus, enable networking for the global machine as
well.
> test: allow networking in testlib's global machine

- test/common/testlib.py
- test/verify/check-connection
This didn't use to work in Atomic times, but does now -- so let's keep
it that way. So un-skip some check-connection tests on fedora-coreos and
instead have them disable the container, rpm-ostree install cockpit-ws,
and use that instead.
Splice testBasic() into a "normal" mode (using the container on ostree)
and an "ws overlay" mode with the same test.
The only problem is an SELinux denial. Let's figure this out later and
disable SELinux for the time being.
Generalize the dbus-daemon message hack in testlib.py to apply to all
Fedoras. One of these days we need to fix this properly..
> test: Check overlaying cockpit-ws RPM on Fedora CoreOS

- containers/ws/README.md
Fedora CoreOS disables password based SSH logins by default. But the
cockpit/ws container uses ssh to access its host, thus Cockpit's login
page is broken by default. Document how to enable it.
Fixes https://github.com/cockpit-project/cockpit-container/issues/16
> containers/ws: Document how to enable password SSH logins

- src/ws/cockpit.service.in
systemd 231 replaced it with the `+` prefix, and 240 deprecated it. All
our supported OSes have newer systemd versions now, and our ./configure
even demands ≥ 235.
> ws: Replace deprecated PermissionsStartOnly systemd option

- tools/debian/rules
Currently all available buildds are emulated, and thus very slow. It
takes way more than 10 minutes to run test-tls-certfile, so skip that
and other slow unit tests on this architecture.
> tools: Don't run slow unit tests on RISC-V architectures in Debian/Ubuntu

- test/common/run-tests
See commits.
I ran into this when trying to use `run-tests` from gating, where it is run from a tarball, not a git checkout
> test/common/run-tests: don't fail when not run from a git checkout

- src/base1/test-http.js
- src/bridge/test-httpstream.c
- src/bridge/test-packages.c
- src/common/cockpitwebresponse.c
- src/common/test-webresponse.c
- src/ws/test-channelresponse.c
- test/verify/check-connection
- test/verify/files/embed-cockpit.html
There is no good use case for including parts of Cockpit's resources
into websites of a different origin. Cockpit does not expose any images
or scripts which would work or make sense there. Thus set the
`Cross-Origin-Resource-Policy` header [1] to `same-origin` for both
static and authenticated paths.
Do this even for "ping", as this doesn't matter for that API -- CORP
leaves the complete response intact, it just instructs the browser to
discard the response contents.
The only cross-origin use case that we have is to embed Cockpit frames
into other websites. The CORP header does not affect `<iframe>`, so this
continues to work fine.
[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)
Cockpit's web server now sets the …
> common: Set strict Cross-Origin-Resource-Policy

- test/common/run-tests
- test/common/testlib.py
- test/verify/check-testlib
This is useful for skipping one or two specific tests in downstream
gating without having to explicitly enumerate all the others.
> test: Add run-tests --exclude option

- src/base1/Makefile.am
Commit 46db248 dropped it, so that it fell out of cockpit-bridge. This
broke every third-party Cockpit package. We didn't mean to obsolete it
*that* fast!
Fixes #14229
> base1: Ship base1/patternfly.css again

- doc/guide/https.xml
Customizing `G_TLS_GNUTLS_PRIORITY` was dropped in commit 8d832e78f, so
this does not apply any more.
> guide: Drop obsolete "SSL Versions and Ciphers" section

- pkg/kdump/kdump.js
- pkg/lib/packagekit.js
- pkg/lib/superuser.js
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/interfaces.js
- pkg/packagekit/updates.jsx
- pkg/selinux/setroubleshoot.js
- pkg/shell/hosts.jsx
- pkg/sosreport/index.js
- pkg/storaged/client.js
- pkg/systemd/logs.js
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/overview.jsx
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services.jsx
- pkg/tuned/dialog.js
- pkg/users/account-details.js
- pkg/users/account-roles.js
- pkg/users/accounts-list.js
- pkg/users/local.js
- pkg/users/password-dialogs.js
There is no JSX in that file, and there shouldn't be -- that file should
be usable from non-React/JSX code as well.
This is mostly just cosmetical, but as this file is expected to be
copied to external projects, let's not raise wrong expectations.
This also disambiguates it from pkg/shell/superuser.jsx, which *is*
React/JSX.
> lib: Rename superuser.jsx to superuser.js

- test/common/run-tests
`./test/common/run-tests --test-dir test/verify TestRunTestListing.testNonDestructive` is ran 3 times, because it comes from affected file.
`./test/common/run-tests --test-dir test/verify TestTestlib.testRestoreAPI` is not retried, as it comes from affected file, but failed.
> run-tests: Make sure affected tests are robust

- test/verify/check-login
The test restarts cockpit a lot, so occasionally runs into disconnect
messages.
> test: Allow restart messages in TestLogin.testTally

- src/ws/cockpit.service.in
Now that cockpit-ws (with cockpit-session) runs in a separate unit,
cockpit.service itself (which just runs cockpit-tls) does not need a lot
of privileges any more. Lock down everything that systemd can throw at
it.
This depends on a fixed SELinux policy that now landed in Fedora.
(https://bugzilla.redhat.com/show_bug.cgi?id=1761765)
> ws: Lock down cockpit.service privileges

- tools/cockpit.spec
The RHEL  i686 builders hang more often than not *after* running the
unit tests. This is not a supported architecture in RHEL 8, so don't
bother.
> tools: Don't run unit tests on RHEL 8 i686

- test/common/run-tests
Running all machines tests 3 times takes too long and the global timeout is reached.
> run-tests: Don't try machines tests 3 times

- test/verify/check-machines
- test/verify/check-system-info
Noticed in RHEL downstream dist-git tests, where these two fail.
> Two test fixes

- test/verify/check-multi-machine
The fingerprint prompt is now "SHA256 Fingerprint (ecdsa-sha2-nistp256)"
without the "ssh-" prefix, and a more detailed algorithm. Make the ssh-
prefix optional and only take the first part of the algorithm, so that
this gets along with either format.
> test: Adjust SSH fingerprint parsing for RHEL 8.3 OpenSSH

- test/verify/check-loopback
- test/verify/check-multi-machine-key
Recent Fedora versions now put the distro specific configuration into
/etc/ssh/sshd_config.d/50-redhat.conf, which includes
`PasswordAuthentication yes`.
> test: Adjust for /etc/ssh/sshd_config.d/ directory

- test/verify/check-login
Running testTally more than once in a row (as it happens when a PR
touches check-login) causes the second run to fail on an existing tally
log. Instead of assuming that it does not exist (which isn't a good
assumption for already existing testbeds), just make sure to delete it,
and restore it at the end.
> test: Fix TestLogin.testTally to not fail on existing tally log

- test/verify/check-realms
Current images have a sufficient SELinux policy.
> test: Enable TestIPA.testClientCertAuthentication on centos-8-stream

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
> machines: 'target' is not a required property in a storage pool object representation

- pkg/systemd/logs.html
- pkg/systemd/logs.js
- pkg/systemd/logs.scss
- test/selenium/selenium-navigate.py
- test/verify/check-journal
Fixes #14104
Release note:
If this lands in time for 222, let's merge it with the "no .service suffix" feature, like this:
The text filter gained new `since:` and `boot:` quantifiers which restrict the logs to a given time span (e.g. `since:-12hours`) or the number of a previous boot (e.g. `boot:-2`). The "Time" dropdown controls these fields, and continues to have the same standard options as before, but they can now be customized easily.
The `service:`*unitname* filter now accepts a unit name without the `.service` suffix. This mirrors the [systemctl](https://www.freedesktop.org/software/systemd/man/systemctl.html) command line behaviour.
> logs: Use predefined filters rather than 'start' option

- pkg/machines/components/vm/vmExpandedContent.jsx
Otherwise oops can happen:
`TypeError: Cannot read property 'initiallyOpenedConsoleTab' of undefined`.
From what I can see this must be a timing related issue so just don't try
to access the object if not ready yet.
> machines: Check if 'ui' is defined before accessing it

- test/verify/check-terminal
In Fedora dist-git testing it only got to ~ 600000 after a minute, so
give it five minutes instead of one.
> test: Increase timeout for terminal flooding test

- tools/cockpit.spec
openSUSE builds may pull in a dummy /etc/os-release so can't actually
rely on that.
> tools: different approach to remove stale branding links

- src/ssh/Makefile-ssh.am
- src/ws/Makefile-ws.am
- src/ws/cockpitwebservice.c
Nothing uses that field, and it causes the build to not be reproducible.
Thanks to Bernhard Wiedemann for finding this!
> ws: Drop "build" date field from websocket info

- test/verify/check-connection
This turns our wiki documentation [1] into a test case, to ensure that
it actually works. It also makes it much easier to experiment with
different configurations.
[1] https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX
> test: Test reverse proxying with nginx

- doc/authentication.md
- doc/guide/cert-authentication.xml
- test/common/testlib.py
- test/verify/check-login
- test/verify/check-realms
Structurally this is similar to authentication against FreeIPA: The full user certificate is imported into LDAP.
Lousy preview of guide page: https://piware.de/tmp/cert-authentication.html (all CSS is missing,  but it's readable enough)
> Document and test certificate authentication against AD

- test/verify/check-connection
If nginx and cockpit run on the same machine, there is no need for
cockpit to speak TLS or even generate its own certificates. Test talking
to cockpit-ws directly in `--for-tls-proxy` mode. ws only listens to
localhost.
Factor out the actual assertions (curl and browser) into a common
checkCockpitOnProxy() helper.
> test: Add check for nginx reverse proxy for plain-http cockpit

- test/verify/check-journal
Factor out the very common, and sometimes changing, selector for the
sleep crash in the journal list box.
Eliminate single-use selector variables.
> test: Clean up TestJournal.testAbrt* selectors

- test/verify/check-journal
Clean the complete journal for test runs, and also cover
/run/log/journal/. That way, messages from previous tests don't cause
duplicate log entries and thus duplicate selectors.
----
This hopefully fixes [this failure](https://logs.cockpit-project.org/logs/pull-1030-20200701-055444-0331ee8a-fedora-testing-cockpit-project-cockpit/log.html) spotted in https://github.com/cockpit-project/bots/pull/1030 . I cannot reproduce that locally, but it's a good enough theory to test it :)
> test: More thoroughly backup/restore journal

- pkg/networkmanager/manifest.json.in
During our usability testing in June, one participant tried to
search for firewalld, without success, so adding that as a keyword
> networkmanager: add firewalld keyword

- pkg/docker/containers-view.jsx
Drop the extra column title, it pushed "Created" and "Size" to the wrong
column.
Fixes #14278
> docker: Fix image table headings

- doc/man/cockpit-tls.xml
- doc/man/remotectl.xml
- src/ws/cockpitcertificate.c
- src/ws/remotectl-certificate.c
- src/ws/remotectl.c
- src/ws/remotectl.h
- src/ws/test-remotectlcertificate.c
TLS certificates should not be valid for longer than two years [1], and
some browsers (in particular, Safari) are being really picky about it.
So reduce the lifetime for our self-signed (previously 100 years) or
sscg (previously 10 years) certificates to 1 year, and automatically
renew them when they are expired.
[1] https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years
Fixes #14121
> ws: Automatically renew auto-created expired certificates

- pkg/lib/cockpit-components-onoff.jsx
- pkg/networkmanager/interfaces.js
- test/verify/check-networking-basic
The direction of this state flag was reversed a while back but this one
was missed which caused the Automatic switches for the DNS, DNS Search
Domains, and Routes settings weren't getting disabled correctly.
Fixes #14290
> networking: Disable automatic switches in IP settings dialogs

- test/common/testlib.py
- test/selenium/testlib_avocado/libnetwork.py
- test/verify/check-machines
- test/verify/check-networking-firewall
New versions of pyflakes seem to be catching some errors in our use of
str.format() in the tests.  Fix those up.
I've made the changes, in each case, that preseve the existing
functionality, but in some cases (particularly, firewall) it's not clear
what the correct intent was.  Someone should look over those.
```
test/verify/check-networking-firewall:420:32 '...'.format(...) has unused arguments at position(s): 1
test/verify/check-networking-firewall:422:32 '...'.format(...) has unused arguments at position(s): 1
test/verify/check-machines:3617:19 '...'.format(...) has unused arguments at position(s): 0
test/common/testlib.py:1498:30 '...'.format(...) has unused arguments at position(s): 0
test/selenium/testlib_avocado/libnetwork.py:176:47 '...'.format(...) has unused named argument(s): …
```
> tests: fix some pyflakes .format() gripes

- pkg/docker/index.html
- pkg/machines/components/memorySelectRow.css
- pkg/machines/components/memorySelectRow.jsx
- pkg/machines/components/storagePools/storageVolumeCreateBody.jsx
- pkg/machines/components/vcpuModal.css
- pkg/machines/components/vcpuModal.jsx
- src/base1/cockpit.css
Fixes #14309
Details:
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/
> a11y, ux: Change input[type=number] to inputmode

- pkg/shell/indexes.js
- test/verify/check-menu
For example visiting firewall of HW details page did not show any active
item in the main menu.
Fixes: #10545
Closes: #14325
> shell: Always show active menu item

- test/verify/check-login
`ChallengeResponseAuthentication` is now also set in some sshd_config.d/
snippet, and it keeps being tossed around. So just sed it in all
matching files. This complicates the code a little, but makes it more
robust against future changes.
> test: Adjust check-login for changed sshd config on Fedora CoreOS

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- test/verify/check-machines
This feature was inherently broken.
virt-install is using the username of the user that ran the script to
create the same user inside the VM if the 'User password' was passed.
However, since we run the script to create the VM with 'superuser:
true', it always runs as root, when the cockpit user has privileges
to do so, resulting in virt-install always creating the root user of the
VM and no user account.
Untill we will be able to pass to the virt-install script the user name
of the new user we need to disable this feature.
https://bugzilla.redhat.com/show_bug.cgi?id=1853918
virt-install Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1855020
> machines: Remove the option for user account creation for unattended installations

- test/verify/check-connection
I've seen this test fail quite a lot recently, like [here](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14328-20200708-135108-83a12c32-ubuntu-2004/log.html#276) or [here](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14338-20200709-061131-c1c5d7d9-ubuntu-2004/log.html#19). This should fix it.
> test: Allow authorize messages in TestConnection.testCockpitDesktop

- test/verify/check-machines
This check was inherently racy, because of https://bugzilla.redhat.com/show_bug.cgi?id=1818089
When we performed the 'destroy' operation on the domain, virt-install
exited and restarted the guest. Thus for a fraction of a second the
state was 'shut off' allowing the test sometimes to pass.
> test: stop testing the VMs state after attempting shutdown during installation

- test/verify/check-services
Fedora dist-git gating tests take longer than 1:45 hours, and if
TestServices.testBasic runs late, then our test-onboot.timer will fire
unexpectedly. Raise it to 200 mins (more than 3 hours), which provides
enough margin.
> test: Fix TestServices.testBasic for long VM uptimes

- test/run
The unit tests during image-prepare already run for the verify scenarios
on all OSes. There is no point running them again on selenium and
container.
> test: Don't run unit tests on auxiliary scenarios

- pkg/networkmanager/interfaces.js
Using the "Managed" property seems to be unreliable, and nmcli seems
to use the state enumeration so we do that as well.
> networkmanager: Use device state to find managed devices

- pkg/machines/libvirtUtils.js
When performing VM Creation/Installation in two steps we need to pass to
the 'virt-install' script the complete VM configuration. We already do
that but interfaces of type 'ethernet' were not parsed.
This commit add support for these.
Fixes #14316
> machines: support iface type 'ethernet' when detecting NICs before VM installation

- test/verify/check-connection
The message sometimes looks like this:
couldn't read from connection: Peer failed to perform TLS handshake: The TLS connection was non-properly terminated.
> test: Fix allowed message in TestConnection.testCockpitDesktop

- package.json
Latest update of novnc breaks, so set it to version 1.1.0
> depencency: set version for novnc.

- examples/long-running-process/README.md
- examples/long-running-process/index.html
- examples/long-running-process/long-running.css
- examples/long-running-process/long-running.js
- examples/long-running-process/manifest.json
- test/verify/check-examples
Cockpit pages should never spawn long-running precious processes, as a
cockpit session is not reliably connected for a long time:  Network
interfaces go down or  roam, TCP timeouts happen, browsers crash, tabs
get closed accidentally, batteries drain, people close/suspend their
laptops, and so on. 
Most services that Cockpit talks to manage their own runtime state and
jobs, such as udisks, libvirt, or podman. But this is not the case for
e.g. running Ansible playbooks or launching installer scripts. These
should be wrapped into a transient service unit, so that systemd takes
over the role of the job manager.
Add a "long-running-process" example which demonstrates this. It runs an
arbitary shell command in a transient cockpit-longrunning-$USER.service,
shows the live log output, and …
> examples: How to launch and reattach to a long-running process

- test/verify/check-metrics
Commit d6fdd2a283b9f fixed the loading of compressed PCP archives (for
data older than a day). Add a corresponding integration test case to
make sure this stays working.
This also lays a test basis for the upcoming performance problem
debugging work.
See https://bugzilla.redhat.com/show_bug.cgi?id=1804844
> test: Add test for historic PCP data

- package.json
Latest 1.2 update of novnc breaks current version of @patternfly/react-console, so set it to version 1.1.0.
Cherry-picked from master commit 76f4802
> [rhel-7.9] package.json: Fix version for novnc

- pkg/lib/cockpit-components-listing-panel.scss
See https://github.com/cockpit-project/cockpit-podman/issues/410
- `align-items: end` does not seem to work in chrome but it needs `flex-end`
- Items cannot be positioned to the end of container in chrome.
Therefore I just dropped `flex: auto` to stop the container from
taking all remaining space and just put space between those two
elements.
Before (firefox and chrome):
After (firefox and chrome):
> lib: Make sure that flex items work correctly on chrome as well

- test/verify/check-sosreport
Clicking the Cancel button merely .close()s the sosreport process, it
does not synchronously wait for its termination. So  it is often still
around right after that. Give it 10s to terminate.
sosreport with the full configuration takes about two minutes, so the
chances of this catching the regular (non-cancel) end is negligible.
> test: Fix race condition in TestSOS.testCancel

- pkg/lib/listing.scss
- pkg/machines/machines.scss
- pkg/packagekit/updates.scss
- pkg/shell/nav.scss
- pkg/systemd/logs.scss
- pkg/systemd/overview-cards/healthCard.scss
- src/ws/login.css
Chrome and WebKit do not yet properly support justify-content and
align-items set to start or end for flex.
https://caniuse.com/#feat=mdn-css_properties_align-items_flex_context_start_end
Both do support start/end for grid, however.
(Do note that flex-start/flex-end are not appropriate for grid, so we
have to be aware if the element is using a display of flex or grid.)
https://caniuse.com/#feat=mdn-css_properties_align-items_grid_context_start_end
Therefore, for the time being, we need to ensure all display: flex
elements are using flex-start & flex-end instead of start & end, for
Chrome and WebKit support.
This is a follow-up to #14360 and applies to more of Cockpit.
> compat (Chrome, WebKit): Use flex-start/end in flex

- test/verify/check-machines
fedora-testing has been Fedora 32 for a while now, so hack_broken_caps()
needs to be applied to it as well.
> test: Fix TestMachines.testConfigureBeforeInstall on fedora-testing

- test/verify/check-login
Replace logins that are supposed to be successful with login_and_go().
> test: Simplify check-login

- src/ws/session-utils.c
- src/ws/session-utils.h
- src/ws/session.c
- test/verify/check-login
SELinux is somewhat understandably upset that we're passing an
unexpected readwrite fd across a privilege barrier.  From our side, it
seems reasonable, since we've just applied seals to make it immutable,
but SELinux doesn't understand that.
Avoid the problem by reopening the file descriptor readonly using the
usual /proc/self/fd trick.
> session: reopen memfd ro to avoid SELinux trouble

- containers/ws/README.md
Apparently podman on Fedora CoreOS has stopped looking into the
docker.io registry by default, so that a bare "cockpit/ws" would just
check registry.fedoraproject.org.
See https://github.com/cockpit-project/cockpit-container/issues/20
-----
This can be tested on e. g. our fedora-coreos image, after `podman rmi --all`. I can reproduce the original reporter's problem and validated that with the prefix it works well.
> containers/ws: Adjust install instructions for image download

- pkg/machines/components/networks/network.jsx
- pkg/machines/components/networks/networkList.jsx
- pkg/machines/components/storagePools/storagePool.jsx
- pkg/machines/components/storagePools/storagePoolList.jsx
- pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
- test/verify/check-machines
The PF4 tables have some differences with our previous table implementation. Porting the rest of the tables in machines page to PF4 to achieve uniformity. 
(Review with --ignore-all-space to save you time, it's a lot of unavoidable whitespace changes)
> machines: Port storage pools and networks lists to ListingTable component

- pkg/machines/components/vm/vmActions.jsx
This was forgotten in PR #14195
Don't use  DropdownItem's `tooltip=` property as that does not work [1].
Wrap it in a Tooltip instead.
[1] https://github.com/patternfly/patternfly-react/issues/4581
> machines: Port remaining PF3 Tooltip

- pkg/machines/scripts/create_machine.sh
- test/verify/check-machines
PXE installs did not have this option before, so the virt-install
process spawned the installation and immediately exited.
As a result of this, when the installation finished or was forcefully stopped,
virt-install was not controlling the VM any more in order to do the
post-install actions, like changing the boot-order so that with next
reboot the installer won't start again.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1853408
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1859045
> machines:  add --wait -1 option to virt-install for all installation types

- pkg/shell/nav.scss
Simple adjustment to fix #14304.
This makes the host switcher have an underline when hovered, like all the rest of the items in the top bar. I'm not sure if it'll fix the issue 100%, but this should help a lot.
> nav: Underline hostname on hover

- pkg/lib/cockpit-components-listing-panel.jsx
- pkg/machines/components/vm/vmExpandedContent.jsx
- pkg/storaged/content-views.jsx
The <a> element had missing href.
!Note:
This affected Storage Page and VMs page.
The file needs to be synced with cockpit-podman since there exists the same problem.
> lib: fix keyboard natigation in the NavItems of expandable table rows

- tools/webpack-make
- webpack.config.js
Something has changed and now node_modules seems to be too large to watch.
> tools: Ignore node_modules when watching.

- test/verify/check-sosreport
Use pgrep's `-x` option for exact match, to avoid pgrep catching the
`check-sosreport` command. This happens when the tests run on the
same machine as cockpit.
> test: Fix TestSOS.testCancel

- test/verify/check-machines
Solves tests failures like https://logs.cockpit-project.org/logs/pull-14365-20200717-113454-6764db97-debian-testing/log.html#91-2
I was not able to find in the libvirt documentation what is exactly that defines the default network.
In any case, re-definining it won't hurt, and it will prevent some tests failures.
> test: Make sure that default libvirt network is defined in Machines tests

- pkg/machines/libvirt-dbus.js
Before this commit, when a user clicked 'Delete' for a VM while it was
being created, the following racy scenario happened:
1: Delete operation first calls 'Destroy' API for the domain (See DELETE_VM function)
2: virt-install script would exit but the VM would still exist (not
`Undefine` call processed yet, and
pkg/machines/scripts/create_machines.sh continue by trying to
redefine the VM in order to inject the metadata.
3: The `Delete` operation in not yet done, it will also try to call 'Undefine'
API for the domain
The Undefine/Define API calls (steps 2,3) sometimes did not run in the expected order
resulting in the domain to not get removed in the end.
So by swapping the order of destroy/undefine in the 'Delete' operation
we make sure that when virt-install script exits (that happens …
> machines: Robustify VM delete operation in case it was performed during installation

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
When user selects an OS in VM creation dialog and then selects another
OS, they are greeted by TypeError "value.os is undefined".
Fixes #14394
> machines: Fix TypeError for OSRow in VM creation dialog

- tools/cockpit.spec
Recent Fedora does not pull it in automatically any more.
No need to do that for Debian, as there make is build-essential.
Part of issue #14409
> tools: Add make build dependency for RPM

- test/verify/check-machines
This test was often failing to delete the VMs because it was clicking on
practically disabled selectors without event listeners for click.
Normally 'click' function from testlib, checks for the 'disabled'
attribute on the selector before clicking it, but in this case the
selector won't have a 'disabled' attribute, rather it's child (the 'a' element)
will have an 'aria-disabled' attribute.
Related failure: https://logs.cockpit-project.org/logs/pull-14373-20200724-054736-89df2b19-centos-8-stream/log.html
> tests: fix testCreateFileSource flake

- pkg/machines/components/storagePools/storagePoolList.scss
I saw wonky progress bar alignment in https://github.com/cockpit-project/cockpit/pull/14387#issue-454998717 and addressed it.
As the widgets each use their own grid, I had to use a bit of hardcoding, as there was no parent grid, nor is subgrid supported (except in Firefox). That said, I made things flexible based on screen width and in case the text needs to overflow. (So it'll be back to looking wonky, but just for the long text.)
Tested in Firefox, Chrome, WebKit; desktop and mobile sizes.
> machines: Fix progressbar alignment (mostly)

- pkg/machines/scripts/install_machine.sh
- test/verify/check-machines
This test suffers from the following race condition:
* A VM installation is running
(virt-install is running through pkg/machines/scripts/install_machine.sh script)
* The test clicks 'Force Off' button from the UI which makes virt-install
command exit and install_machines.sh script should continue to try to
re-define the domain in order to inject the metadata.
* Then the test tries to delete the VM and expects to see an empty list after
the delete operation
-- Race condition --
Sometimes the deletion was processed before the install_machine.sh
script redefined the domain, resulting in non empty list after the
delete operation.
There is nothing really to be fixed in the source code, this test just
asks for problems.
Robustify it by waiting for the metadata of the VM to get set, which …
> tests: Robustify TestMachines.testCreateThenInstall

- pkg/machines/components/vmSnapshotsCreateModal.jsx
- pkg/machines/components/vmSnapshotsTab.jsx
- pkg/machines/libvirt-dbus.js
- pkg/machines/xmlCreator.js
- test/verify/check-machines
- test/verify/machinesxmls.py
So far user can only input name of snapshot and description.
Name is pre-generated from VM name + date and time, and description is optional input, so ideally user doesn't have to input anything an can straight go to clicking "Create".
I also experimented here with how we evaluate  incorrect inputs in dialogs, and tried to us React's onBlur trigger. This means that whenever uses looses trigger of a input field (clicks outside of a input field or start typing into another input field), input field is evaluated. This is more immediate and more direct compared to evaluating inputs only after user click "Create".
> machines: Implement creation of VM snapshots

- test/common/run-tests
- test/common/testlib.py
[fedora-31/firefox](https://logs.cockpit-project.org/logs/pull-14422-20200729-061421-ab92649c-fedora-31-firefox/log)  # TESTS PASSED [2760s on 2-ci-srv-06, 137 serial tests: 0: 2466s, 1: 2354s]
[debian-stable](https://logs.cockpit-project.org/logs/pull-14422-20200729-061421-ab92649c-debian-stable/log) # TESTS PASSED [1700s on 3-ci-srv-02, 137 serial tests: 0: 1334s, 1: 1665s]
[fedora-31](https://logs.cockpit-project.org/logs/pull-14422-20200729-061421-ab92649c-fedora-31/log) # 1 TESTS FAILED [2764s on 4-ci-srv-06, 137 serial tests: 0: 2477s, 1: 1975s]
[fedora-32](https://logs.cockpit-project.org/logs/pull-14422-20200729-061421-ab92649c-fedora-32/log) # 1 TESTS FAILED [3589s on 1-ci-srv-03, 137 serial tests: 0: 3583s, 1: 1490s]
> Run nond tests in parallel batches

- test/verify/check-login
RHEL 8.3 has Cockpit 224 now, and thus an SELinux friendly memfd
handling. Remove the special case.
> test: Adjust TestLogin.testSELinuxRestrictedUser on rhel-8-3-distropkg

- src/ws/mock-kdc.conf.in
Recently krb5 started to be stricter about unrecognized enctypes [1],
and that commit is now in Fedora Rawhide. This broke test-kerberos with
cockpit-ws:ERROR:src/ws/test-kerberos.c:301:test_authenticate:
assertion failed (GSS_S_CONTINUE_NEEDED == status): (1 == 851968): Unspecified GSS failure.
Minor code may provide more information (Decrypt integrity check failed)
Between Fedora 33 and CentOS 8 there is no set of encryption types that
is supported everywhere; also, we don't particularly care about the 
encryption type for this unit test, so just use whatever kerberos
considers a good default [2].
[1] https://github.com/krb5/krb5/commit/be5396ada0e8dab
[2] https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/kdc_conf.html#encryption-types
> ws: Clean up unsupported krb5 enctypes from mock KDC

- test/verify/check-packagekit
- test/verify/packagelib.py
Latest systemd fixes the message for a scheduled reboot to actually say
"Reboot" instead of "Shutdown". Accept either.
> test: Adjust expected systemd message for scheduled reboot

- src/base1/_fonts.scss
Value are fetched from https://github.com/RedHatOfficial/RedHatFont/blob/master/webfonts/red-hat-font.css
There has been some confusion with fonts weights because from other
sources like https://fonts.google.com/specimen/Red+Hat+Text#standard-styles
the RedHat fonts appear to use different font wrights.
Let's just trust the official RedHat repository for this.
> Fix weight values for Redhat fonts

- src/ws/cockpitcertificate.c
- test/verify/check-connection
According to Common Criteria:
Server certificates presented for TLS shall have the Server Authentication
purpose (id-kp 1 with OID 1.3.6.1.5.5.7.3.1) in the extendedKeyUsage field.
Add a `keyUsage` and `extendedKeyUsage` field, and also mark that it's a
CA as it is a self-signed certificate.
https://bugzilla.redhat.com/show_bug.cgi?id=1859812
> ws: Add key usage and constraints to self-signed server certificate

- pkg/shell/indexes.js
Showing it for a disconnected machine does 'work' in the sense that
the SuperuserIndicator stays invisible, but it wouldn't try to
reconnect once the machine changes its state from "failed" to
"connected".
By only rendering the SuperuserIndicator for connected machines, we
make sure that the indicator correctly follows the connectedness state
of the machine.
> shell: Only show superuser indicator when a machine is connected

- src/base1/_fonts.scss
The RedHatText Italic font family now has a font-style of italic. This follows the style used for the other italic red hat fonts.
> base1: fix style for Red Hat italic font

- test/verify/check-login
In current rawhide, there is now a message
sudo: unable to open /sudo/ts/unpriv: Permission denied
Just allow any kind of permission message for sudo in that test, it's
not useful to pin them down so carefully.
> test: Allow more sudo related messages in testSELinuxRestrictedUser

- test/common/testlib.py
- test/verify/pytest_dynamic_loader.py
- pass expected varibales via env vars instead of cmd line params
- rename check-* to check-*.py to be able to find tests.
usage:
```
PYTHONPATH=test/common/:test/verify BROWSER=localhost:9091 MACHINE=localhost:2201 pytest-3 -v -s test/verify/check-login.py
```
> tests: allow to use pytest as scheduler for test execution

- pkg/lib/machine-info.js
- pkg/systemd/hwinfo.jsx
- test/verify/check-system-info
We parse lines in form `/sys/class/dmi/id/key:value`, but if value
contains `/`, the parsing got all wrong. It was mainly issue with
`bios_date`, as it is in form `MM/DD/YYYY`.
Also specify exact expected format in moment, so when we fail to parse
this value, we don't show current date (since `moment(undefined)` shows
current time).
Fixes #14461
> hwinfo: Fix parsing of bios_date

- src/ws/session-utils.c
- src/ws/session-utils.h
- src/ws/session.c
- test/verify/check-login
Spawning cockpit-bridge under the shell has caused quite a lot of
annoying problems over time, mostly to do with file descriptors:
- the user's shell rc scripts can write messages to stdout, which would
be interpreted as cockpit frames
- some shells (csh) don't support the redirection syntax we've been
trying to use to solve the above problem
- some shells (tcsh) seem to close all fds >= 3
- some shells (tlog-rec-session) open a new pseudoterminal, running the
session command with stdin/out/err attached to it, and writing the
results to stdout, regardless of which fds they were written on
The above problems make it pretty difficult to come up with a mechanism
to get a clean fd through to cockpit-bridge which we can reliably speak
cockpit protocol on.  Let's give up on trying.
Instead, we …
> session: don't spawn cockpit-bridge with the shell

- test/common/testlib.py
We see a lot of messages like:
Failed to create temporary file for coredump /var/lib/systemd/coredump/core.libvirtd.1001.746601e77b394c91b233abce203cf0ca.18835.1597175105000000.lz4: No such file or directory
while running machines tests.  This is caused by the fact that we blow
away the /var/lib/systemd/coredump directory between testcases.
Instead, let's delete the contents of the directory, but leave the
directory itself in place.
> testlib: don't remove /var/lib/systemd/coredump

- src/ssh/cockpitsshrelay.c
`bdata` here is passed in to our callback with a `len` parameter.
Respect it.
This prevents an obscure error where we can end up printing some extra
junk that was laying around in memory, at the end of the output.  In
particular, we were seeing a stray 'sh %s' showing up from (apparently)
nowhere in some of our tests.  The actual origin of that was the
"LESSOPEN=||/usr/bin/lesspipe.sh %s" environment variable.
This 'sh %s' (which had no trailing newline) was causing later stderr
output which should be ignored (in particular, warnings about missing
locales) to fail to match the filter for those messages.
For what it's worth, this issue probably stopped actually appearing some
time ago due to unrelated changes in cockpit-ssh.  We see the issue now
in our integration tests only as a result …
> ssh: fix printing of non-nul-terminated stderr

- test/verify/check-machines
The "used memory" parameter differs between running and shut off VM. In
this test, a dialog with memory parameters would be opened immediately
after shutting off a VM, which would lead to a race condition where an
the old value would be rendered because there was not enough time to update
a VM config.
Fix this by waiting until the memory parameters of VM are updated.
This race condition was causing a failure: https://logs.cockpit-project.org/logs/pull-14471-20200812-073912-3ad9266e-rhel-8-3/log.html#97-2
> machines: Fix memory race condition in testConfigureBeforeInstall

- test/verify/check-machines
`startLibvirt()` tries to start the `default` network, but if it was
removed by some previous test it fails. The line I moved was introduced
in #14404 with exactly this same intention, but it needs to happen
sooner.
Hopefully fixes https://src.fedoraproject.org/rpms/cockpit/pull-request/29
> test: Define 'default' network before trying to start it

- src/tls/Makefile-tls.am
It seems adding these dependencies was missed when cockpit-tls was
converted to a thread-based concurrency model.
> tls: add missing -pthread deps to Makefile-tls.am

- pkg/lib/cockpit-components-file-autocomplete.jsx
- test/verify/check-pages
When a directory path is specified, a listing of options wouldn't contain a
current directory, only its children. This would lead to bugs where:
1. The user could not change a path to the parent directory of the previously
specified directory
2. The user could not just type a full path to some directory and then press
Enter. They would have to use autocomplete shortcut or choose from a
list of options offered in a dropdown.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1866995
> lib: Include current directory in FileAutoComplete option listing

- pkg/storaged/format-dialog.jsx
- pkg/storaged/fsys-tab.jsx
- test/verify/check-storage-luks
- test/verify/check-storage-mounting
A filesystem that has a crypto backing device with the "noauto" option
will now always have the "noauto" mount option, even when mounted.
If such a filesystem doesn't have the "noauto" option, Cockpit will
warn about it and offer to add it.
Fixes #14467
Cockpit now behaves more sensible with encrypted filesystems that have "noauto" in their LUKS options. Such a filesystem will now also always have "noauto" in their mounting options even when mounted.
> storage: Support "noauto" crypto backing devices better

- tools/cockpituous-release
Bodhi activation point is the [next Tuesday](https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html). We won't have another release in the meantime so lets not forget about it. I'll start preparing F33 image now so we can also test it.
> cockpituous: Release to Fedora 33

- tools/cockpituous-release
Fedora 33 is branched now, let's not support too many releases in
parallel.
> cockpituous: Stop releasing to Fedora 31

- test/verify/check-machines
Recently a security issue was fixed by setting libvirt's socket
permissions to 0660 from 0666.
See https://people.canonical.com/~ubuntu-security/cve/2020/CVE-2020-15708.html
This completely breaks libvirt-dbus system connection.
root@ubuntu:~# gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.ListDomains 0
Error: GDBus.Error:org.libvirt.Error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
That is because libvirt-sock by default allows rw access to users that are in the libvirt group.
root@ubuntu:~# ls -la /var/run/libvirt/libvirt-sock
srw-rw---- 1 root libvirt 0 Aug 24 15:33 /var/run/libvirt/libvirt-sock
However libvirt-dbus system process is running as libvirtdbus/libvirtdbus user/group.
root@ubuntu:~# ps …
> tests: Intruduce hack for libvirt-dbus on system connection on ubuntu

- pkg/machines/components/desktopConsole.jsx
- pkg/machines/machines.scss
This table incorrectly inherited CSS from PF4 tables, because it's
nested in the PF4 table, and some rules from the imported PF4 were
applied.
Let's make this a simple grid and avoid using nested tables.
In addition the 'Launch Remote Viewer' button was ported to PF4 Button.
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1868584
> machines: Fix Desktop Viewer Console tab CSS issues

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
There are cases where the OS autodetection script returns successfully,
but the result in an empty dict.
Always re-enable the OS input after the script returned.
Fixes #14501
> machines: fix disabled OS input in case OS autodetection returned empty dict

- test/verify/check-superuser
This is not necessary since Cockpit runs "sudo -k" as part of limiting
access.  Also, it is not portable to at least Fedora 33.
> test: Don't explicitly remove /run/sudo/ts/admin

- test/selenium/testlib_avocado/seleniumlib.py
This method is deprecated since Python version 3.3 and is removed in Python version 3.8.
Fedora 32 ships by default Python 3.8
> test: Replace deprecated `time.clock()` with `time.process_time()`

- containers/bastion/install.sh
`systemd` has been present for `fedora` images up to version 31. In
version 32 it has been dropped. `cockpit-ws` requires this package.
See https://github.com/cockpit-project/bots/pull/1184
Will need to be backported to 7.9 and 8.3 stable branches.
> bastion: Install systemd into the image

- test/selenium/testlib_avocado/seleniumlib.py
This method is deprecated since Python version 3.3 and is removed in Python version 3.8.
Fedora 32 ships by default Python 3.8
Cherry-picked from master commit e0badff
> [rhel-8.3] test: Replace deprecated `time.clock()` with `time.process_time()`

- pkg/sosreport/index.js
In sosreport 4.0, the saved file is indented with a tab. Be less picky
in the regexp and accept any kind of whitespace.
> sosreport: Adjust to output format in sosreport 4.0

- test/avocado/testlib_avocado/seleniumlib.py
This method is deprecated since Python version 3.3 and is removed in Python version 3.8.
Fedora 32 ships by default Python 3.8
Cherry-picked from master commit e0badff
> [rhel-7.9] test: Replace deprecated `time.clock()` with `time.process_time()`

- src/ws/mock-kdc.conf.in
Recently krb5 started to be stricter about unrecognized enctypes [1],
and that commit is now in Fedora Rawhide. This broke test-kerberos with
cockpit-ws:ERROR:src/ws/test-kerberos.c:301:test_authenticate:
assertion failed (GSS_S_CONTINUE_NEEDED == status): (1 == 851968): Unspecified GSS failure.
Minor code may provide more information (Decrypt integrity check failed)
Between Fedora 33 and CentOS 8 there is no set of encryption types that
is supported everywhere; also, we don't particularly care about the
encryption type for this unit test, so just use whatever kerberos
considers a good default [2].
[1] https://github.com/krb5/krb5/commit/be5396ada0e8dab
[2] https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/kdc_conf.html#encryption-types
Cherry-picked from master commit 8eed6e7
> [rhel-7.9] ws: Use default krb5 enctypes from mock KDC

- pkg/lib/patternfly/patternfly-4-overrides.scss
PF4 changed to using Red Hat Text as the default and fixed the alignment issues. Therefore, we no longer need an override for the dropdown to properly align the dropmarker in split buttons.
Screenshot from the split button on the Overview page in Cockpit without the override:
Closes https://github.com/patternfly/patternfly/issues/2715
> PF: drop override (font & alignment changed in PF)

- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.css
Utilize Page PF4 component instead.
Also replace usage of bootstrap .breadcrumb class with the PF4 React
component.
This fixes regression in network details page introduced by:
commit 60571e3c599f5bc98a7a034204be965634427a45
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Thu Aug 6 17:13:34 2020 +0200
network: Utilize cards and PF4 tables for showing the interfaces lists
Previously:
Now:
> networking: interface-details: stop using container-fluid bootstrap class for page layout

- pkg/lib/cockpit-components-logs-panel.jsx
- pkg/lib/cockpit-components-logs-panel.scss
- pkg/lib/journal.css
- pkg/networkmanager/networking.css
- pkg/storaged/block-details.jsx
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/details.jsx
- pkg/storaged/devices.jsx
- pkg/storaged/drive-details.jsx
- pkg/storaged/index.html
- pkg/storaged/jobs-panel.jsx
- pkg/storaged/logs-panel.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/optional-panel.jsx
- pkg/storaged/overview.jsx
- pkg/storaged/storage.css
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vgroup-details.jsx
- test/verify/check-services
- test/verify/check-storage-hidden
- test/verify/check-storage-iscsi
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-nfs
- test/verify/check-storage-vdo
- test/verify/storagelib.py
Since we have the cards design in many pages already, I felt that the storage page felt somehow awkward.
I feel now it's more consistent with the rest of the pages.
Now:
Before:
> Modernize storage page - stop using bootstrap classes and use PF4 components instead

- pkg/machines/c3charts.jsx
- pkg/machines/components/vm/vmUsageTab.jsx
- test/verify/check-machines
Nested PF4 tables have issues, we should not follow this pattern.
Replace tables with flex for creating the layout of this component.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1873931
> machines: fix distance between the chart elements in VM Usage tab

- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/systemd/graphs.html
Now:
Previously:
And the alignment issue:
Now:
Previously:
> Fix breadcrumbs in graphs page and every page that uses React Breadcrumb component

- pkg/machines/components/vmSnapshotsRevertModal.jsx
- pkg/machines/components/vmSnapshotsTab.jsx
- pkg/machines/components/vmSnapshotsTab.scss
- pkg/machines/libvirt-dbus.js
- pkg/machines/machines.scss
- test/verify/check-machines
Reverting to a snapshot means VM is restored to a state in which it was when a snapshot was taken.
Deleting snapshots is self explanatory.
Also with action of reverting, it's important to distinguish which snapshot is "current". Current snapshot means that current state of VM is "closest", is succeeding "current" snapshot. So when you create several snapshots, let's say A, B, C, D in that order, at that moment D is current snapshot. But when you revert to the snapshot B, that snapshot becomes the current one.
I tried to solve this problem of distinguishing current snapshot by adding border on the right side of the row of the snapshot and changing background color to `--pf-global--BackgroundColor--200`. Although I don't know if this would be clear enough to the user.
> machines: Implement reverting and deletion of VM snapshots

- pkg/machines/components/vm/vmUsageTab.jsx
- pkg/machines/helpers.js
- test/verify/check-machines
machines: Unify combination of units in the usage tab
The same unit should be used both for the graph and the helper text below.
Fixes #14503
> machines: Unify combination of units in the usage tab

- test/verify/check-accounts
Commit 3aa13 was supposed to deal with this, but we still get the same
errors.
Cherry-picked out of https://github.com/cockpit-project/cockpit/pull/14517
> tests: wait for all processes of the deleted users to go away in check-accounts

- src/ssh/cockpitsshrelay.c
- test/verify/check-multi-machine-key
Previously, Cockpit would only try the first identity in the list
used by libssh, and rely on the agent to have all the default keys
loaded into it.  But this wont be the case when a default key is
protected by a passphrase (and doesn't happen to be the first in the
libssh list).
We still need to try such a protected default key since we want to
prompt the user for its passphrase.
This also changes the general order of things in order to prepare for
an eventual switch to ssh_userauth_publickey_auto:
- The agent is tried first.
- do_key_auth also tries the agent.
> ssh: Almost use ssh_userauth_publickey_auto instead of custom code

- pkg/kdump/kdump-view.jsx
- pkg/lib/patternfly/patternfly-4-overrides.scss
This approach should be served as an example of how to use
DescriptionList component for displaying data instead of the much used
<form> which is incorrectly used in many places.
Now: 
Previously: 
This commit improves the mobile version of the kdump page.
> kdump: Utilize description list instead of form for displaying data

- pkg/shell/hosts.jsx
- pkg/shell/indexes.js
- test/verify/check-host-switching
We were disabling to remove host on which we are currently at. We had at
last two reports about this, so lets not enforce it.
When user removes such host, will be switched to the `localhost`.
Fixes #14150
> hosts: Enable to remove the current host

- pkg/users/account-create-dialog.js
- pkg/users/password-dialogs.js
- pkg/users/users.scss
- test/verify/check-accounts
Modeled after anaconda where you can use a weak password if you click
the button two times.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1652390
Fixes #14478
@andreasn WDYT? Also the wording is not ideal, maybe I should spin up one fedora VM to see what exactly anaconda says.
<hr> 
Release note draft:
**Accounts: Allow setting up weak passwords**
Cockpit now allows users to set up a weak passwords. User is firstly notified that such password is weak but if user wishes to continue then clicking the submit button again will use the selected password anyway.
> users: Allow weak passwords

- pkg/lib/cockpit-components-table.scss
Commit 8960ea incorrectly adjusted the padding of the `<td>`s but not
`<th>`s in nested tables.
Fixes #14546
> machines: fix misaligned first header column in nested tables

- pkg/networkmanager/index.html
When having the string on separate line it is then generated as:
`msgid "                Firewall              "` (damn you github, don't suppres those spaces, I am trying to prove something here :unamused: )
Noticed in #14576
> firewall: Fixup spacing in translation string

- tools/cockpit.spec
/usr/share/pcp/lib/pmlogger does not exist any more in pcp 5.2.1 (moved
somewhere else). systemd works fine now, so move to the more robust and
generic systemctl command to restart pcp instead of hardcoding the path.
Thanks to Mark Goodwin for the report and suggestion!
https://bugzilla.redhat.com/show_bug.cgi?id=1877189
> tools: Use systemd to restart pmlogger

- pkg/machines/components/vnc.jsx
react-console will request exclusive access by default (shared=false)
When cockpit used "Graphics Console (VNC)", it will disallow other
connection to VNC.
Only way to release the connection is shutdown VM
and don't open "Graphics Console (VNC)"
Otherwise, you can't use 3rd party VNC viewer to connect.
If VNC listens 0.0.0.0 IP, no matter open "Graphics Console (VNC)" or
not
It will hold the connection and disallow other connection.
Testing with OpenMediaVault 5.x (Debian buster)
Cockpit 217-2~bpo10+1
> machines: Enable noVNC shared access

- pkg/machines/components/vnc.jsx
Not sure why tests found it before, but now it's broken on master.
> machines: Fix shared proptype introduced in commit f5b0630

- test/common/testlib.py
https://bugs.debian.org/951477 crept into ubuntu groovy as well now.
----
[example](https://logs.cockpit-project.org/logs/pull-14588-20200910-070235-28574157-ubuntu-stable/log.html#155)
> test: Ignore ip6tables crash on ubuntu-stable as well

- src/bridge/cockpitdbusloginmessages.c
- src/common/Makefile-common.am
- src/common/cockpitmemfdread.c
- src/common/cockpitmemfdread.h
We have some generally useful code to read from a sealed memfd file
descriptor into an allocated buffer, with good error checking.  Factor
it out to a new file in common/, anticipating its use from a future
feature to be added to cockpit-ws.
Make two changes while doing do:
- separate the code for parsing the environment variable from the code
for reading from the memfd (as the other use will not be via an
environment variable)
- log errors via GError rather than directly
> bridge: factor out memfd-reading code to common/

- tools/cockpit.spec
This allows to build smaller containers
> tools: don't require systemd at runtime

- src/common/Makefile-common.am
- src/common/cockpitjsonprint.c
- src/common/cockpitjsonprint.h
- src/ws/session-utils.c
- src/ws/session-utils.h
- src/ws/session.c
We have some generally useful "libc-only" functions for printing json to
stdio streams located in session-utils.  They go together nicely with
the stream-based memfd helpers in the same file.  Factor them both out
to common/, anticipating their use from a future feature to be added to
cockpit-tls.
Make two changes while doing so:
- the memfd helpers are now more explicitly json-oriented, growing
support for adding leading '{' and trailing '}', along with an
optional version field (which is used in -session and will be used
from -tls).
- the memfd helpers no longer return success/failure, but rather
assert().  The failures are pretty unlikely, and we weren't properly
checking the return value anyway.
> session: factor out json printing to common/

- test/verify/check-networking-bridge
Otherwise the internal state of Cockpit might be incomplete and the
deletion might not actually happen.
At least that's the theory.
> test: Wait for bridge to be fully shown before deleting it

- test/verify/check-accounts
- test/verify/check-connection
- test/verify/check-host-switching
- test/verify/check-keys
- test/verify/check-menu
- test/verify/check-multi-machine
- test/verify/check-multi-machine-key
- test/verify/check-multi-os
- test/verify/check-networking-basic
- test/verify/check-networking-bond
- test/verify/check-networking-bridge
- test/verify/check-networking-checkpoints
- test/verify/check-networking-firewall
- test/verify/check-networking-settings
- test/verify/check-networking-team
- test/verify/check-realms
- test/verify/check-services
- test/verify/check-shutdown-restart
- test/verify/check-superuser
- test/verify/check-system-info
Commit 2d50f4bcad skips entire test classes for the basic packages, so
they don't need individual -distropkg special cases any more.
> test: Clean up obsolete rhel-8-3-distropkg special cases

- pkg/lib/ct-card.scss
- pkg/storaged/storage.scss
Don't make the content fill its grid cell and don't put a border on
the last row.
Before:
After:
> storage: Some Card layout and render fixes

- pkg/systemd/overview-cards/realmd-operation.js
- test/common/run-tests
- test/verify/check-realms
If the join process is cancelled later than just a tiny amount of time
after starting the installation process, the system is in a half-joined
state, ipa-client-install fails with random exceptions, realm list
claims you are joined, but you are not fully, and realm
leave/ipa-client-uninstall also failsbecause of the inconsistent system
state.
Let's not allow that any more. If the join fails due to invalid
credentials etc, the dialog will come back with a proper error message,
and if it succeeds you can always immediately leave again.
> systemd: Disallow cancelling a running domain join

- test/verify/check-storage-mdraid
This seems to happen often right after stopping them, for unknown
reasons.
> test: Be robust against mdraids starting themselves spontaneously

- test/verify/check-networking-firewall
There seems to be some issue with this part of test where it times out
waiting for the change in the UI. There are 3 possible explanations:
1. The service fails to stop/start
2. There is no event delivered (or is delivered but we process it wrongly)
3. It just takes a bit longer to propagate in the UI
This PR does not fix any of these issues (possibly the last one) but it
should point if the issue is no. 1 or no. 2. Then we can do more
debugging.
I cannot reproduce it locally while running that test in loop in 3 parallel batches...
Talking about failure like this: https://logs.cockpit-project.org/logs/pull-14602-20200911-063101-73421c5c-fedora-32/log.html
> test: Wait for firewalld service state

- test/verify/check-login
Wait until the /system page has loaded, instead of immediately logging
out after logging in. It may otherwise happen that the
JavaScript/websocket parts haven't initialized yet, and the `cockpit`
object isn't available yet.
> test: Fix race condition in TestLogin.testBasic

- package.json
- pkg/machines/index.html
- pkg/systemd/index.html
- webpack.config.js
The system page redesign in commit f8c0966a6d made that obsolete.
> package.json: Drop unused d3 module

- pkg/networkmanager/interfaces.js
We already import the uuid NPM module, so actually use it. Replace our
home-grown solution.
> networkmanager: Use uuid module

- test/image-prepare
- tools/cockpit.spec
- tools/make-srpm
On RHEL/CentOS, cockpit is delivered as two mostly identical source
packages.  "cockpit" with build_basic=1, and "cockpit-appstream" with
build_optional=1.
Do that split upstream, so that upstream testing better reflects what
actually happens downstream in RHEL. This will also finally exercise the 
`build_*=0` code paths, so that we stop breaking them:
- Check the OS and source package name in the spec to provide the 
correct values for build_*. This minimizes the downstream delta to
just Name: and %changelog.
- Adjust make-srpm to build a separate cockpit-appstream.spec on
RHEL/CentOS, and build srpms for all generated specs.
> Split basic/optional package build on RHEL

- package.json
- webpack.config.js
This gets rid of these warnings:
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Enable deprecation tracing in webpack config, so that it's easier for us
in the future to track down the root causes. See
See https://github.com/webpack/webpack/issues/6568#issuecomment-377491754 for details.
> Bump optimize-css-assets-webpack-plugin to latest version

- src/bridge/cockpitdbusinternal.c
Initialize the socket auto pointer right away. This fixes this warning:
```
src/bridge/cockpitdbusinternal.c: In function 'create_io_stream_for_unix_socket':
/usr/include/glib-2.0/glib/gmacros.h:1049:17: warning: 'socket' may be used uninitialized in this function [-Wmaybe-uninitialized]
1049 |     { if (_ptr) (cleanup) ((ParentName *) _ptr); }                                                              \
|                 ^
src/bridge/cockpitdbusinternal.c:66:22: note: 'socket' was declared here
66 |   g_autoptr(GSocket) socket;
|                      ^~~~~~
```
> bridge: Fix warning about uninitialized value

- test/verify/kubelib.py
The test was expecting the "Login failed" error message in the
curtain, for unknown reasons.  It actually appears in the dialog, and
always has, I think.
> test: Fix check-openshit testNodeNavigation

- test/verify/check-metrics
When building the centos-8-stream image from the cloud image instead of
the DVD [1], it ends up having no swap.
As this keeps changing between images, determining if the image has swap
is very robust, and as the test handles both cases, replace the static
list with a dynamic check.
[1] https://github.com/cockpit-project/bots/pull/1250
> test: In check-metrics, check if image has swap

- tools/cockpit.spec
cockpit-ssh has been shipped by cockpit-bridge for a long time, so fix
the conditional BuildRequires for libssh-devel to apply to build_basic.
When building without `build_basic`, then the conditional BuildRequires:
libssh-devel does not get installed, and the package build fails with
checking build with cockpit-ssh... yes
checking for LIBSSH... no
configure: error: Package requirements (libssh >= 0.8.5) were not met:
Disable the ssh feature in this case.
> tools: Fix building without libssh-devel

- test/common/run-tests
- test/common/testlib.py
When restarting a global machine, we want it to keep its ports because
they are already hard coded into the command lines for running the
nondestructive tests.
Also, and more importantly, we used to release all the networking port
locks for all global machines when restarting a single one. This
resulted in allocating a control port for the restarted machine that
was still in use by other global machines.
The error message for that was:
libvirt domain already exists: operation failed: domain
'fedora-33-127.0.0.2-2201' already exists with uuid ...
since the control port is included in the domain name for virtual
machines.
Fixes #14657
> test: Fix restarting of global machines

- test/verify/check-storage-luks
In recent versions, cryptsetup uses memory-hard PBKDF, which overflows
our default 1 GiB of RAM. Run the tests with 1.5 GiB to avoid that,
which is the minimum requirement for CentOS 8 [1]. See [2] for details.
[1] https://wiki.centos.org/About/Product
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1881829
> test: Run LUKS tests with more VM memory

- tools/cockpit.spec
- tools/make-rpms
When not building basic/optional packages, also remove the corresponding
source map files. This fixes cockpit-debuginfo and 
cockpit-appstream-debuginfo both shipping the same files.
https://bugzilla.redhat.com/show_bug.cgi?id=1870521
> tools: Fix duplicated -debuginfo files

- test/verify/check-sosreport
It's coming in fedora-33, but it's way too slow without Internet and
times out the tests almost every time.
> test: Speed up sosreport 4

- test/verify/check-storage-resize
- test/verify/check-storage-used
Commit 0c067822b3 forgot two places that also call `cryptsetup luksFormat`:
- Use a bigger VM in TestStorageResize, as Cockpit itself creates the
LUKS device there.
- check-storage-used is a @nondestructive test (no `provision`), but
there the test itself calls `cryptsetup luksFormat`, so just use the
option to tell it to use less RAM.
> test: More cryptsetup PBKDF adjustments

- test/verify/check-storage-resize
- test/verify/check-storage-used
Commit 0c067822b3 forgot two places that also call `cryptsetup luksFormat`:
- Use a bigger VM in TestStorageResize, as Cockpit itself creates the
LUKS device there.
- check-storage-used is a @nondestructive test (no `provision`), but
there the test itself calls `cryptsetup luksFormat`, so just use the
option to tell it to use less RAM.
Cherry-picked from master commit 883f1d036dd0
> [rhel-8.3] test: More cryptsetup PBKDF adjustments

- test/verify/check-multi-machine
It legitimately takes about a minute on a quiet system, so it often ran
into the default 1min timeout.
> test: Increase timeout for fips-mode-setup

- test/common/cdp.py
Recent chromium versions (seen with 85.0.4183.121) have become
ridiculously chatty, spewing thousands of messages like
ERROR:paint_controller.cc(646)] PaintController::FinishCycle() completed
VERBOSE2:thread_state.cc(429)] [state:0x560d0d8fefc0] ScheduleGCIfNeeded
Explicitly set verbosity 0. This was, and is supposed to be, the
default, but apparently not any more.
> test: Quiesce Chromium logorhea

- test/verify/check-dashboard
- test/verify/check-host-switching
Adjust check-{dashboard,host-switching} to switch to the hardware info
subpage instead of the graphs subpage, as we will soon replace the
latter with a standalone webpack.
> test: Use different /system subpage in page switching tests

- test/common/testlib.py
Commit 962ea145f65a changed MachineCase.write_file() to use 
restore_file(). This broke TestRunTest.testExistingMachine on Fedora 32
in a subtle way: As the override files are now already existing, the 
inner test tried to restore the original version instead of just
deleting the file, but that happened *after* nonDestructiveSetup()
already removed the backup directory.
Call disable_preload() *after* nonDestructiveSetup() to fix this.
> test: Fix cleanup of override files

- test/common/testlib.py
See https://bugzilla.redhat.com/show_bug.cgi?id=1884236.
> testlib.py: Add gensnippet_if crash to allowed_messages

- src/bridge/cockpitpolkitagent.c
This code doesn't do anything anymore, since we never install a log
handler anymore.  It should have been removed earlier.
> bridge: remove log handler remover code

- tools/cockpit.spec
This reverts commit 5eb6af26402d059b0d2f23ace45c8e1ee7b1524f.
> Revert "tools: Require shadow-utils also on Fedora/RHEL"

- src/ssh/cockpitsshrelay.c
This should be fixed by now, also the SSH_OPTIONS_KNOWNHOSTS option
should now be present everywhere.
> ssh: Remove old hack

- pkg/packagekit/autoupdates.jsx
basename would print an error if none of the commands was found.
Also add zypper for compleness. Needs to be before apt as there's
some compat package that provides a redirection from /usr/bin/apt to
zypper that would lead to misdetection.
> packagekit: avoid error from basename

- pkg/storaged/crypto-panel.jsx
- pkg/storaged/overview.jsx
- test/verify/check-storage-luks
People might want to find them easily in order to unlock them
manually.
Demo: https://www.youtube.com/watch?v=mmFOTQ39ZPk
Fixes #14697
Cockpit now lists those encrypted devices in the overview that are still locked. This makes them easy to find if you want to unlock them manually.
> storage: List entries from /etc/crypttab that are still locked

- test/verify/check-sosreport
This test keeps running into the timeout on rhel-atomic.
See cockpit-project/bots#1271
> tests: Increase timeout in check-sosreport

- test/verify/check-embed
- test/verify/files/embed-cockpit/embed.js
- test/verify/files/embed-cockpit/index.html
- test/verify/files/embed-cockpit/manifest.json
This test contains cross-origin requests to an embedded iframe, which
isn't allowed anymore by chromium>=85.
--- 
The alternative would be to introduce this test on a page in cockpit somewhere and embed cockpit within cockpit. But I struggle to think of the benefits of this. I guess maybe test the login in an iframe?
> test: Fix check-embed to work with chromium>=85

- .github/workflows/release.yml
- tools/cockpituous-release
Enter the new world of GitHub actions [1]/GitLab pipelines [2]. This
simplifies our end of the infrastructure considerably:
* No need any more to set up webhooks, all the relevant configuration
is right in the workflow file.
* Does not need any infrastructure on our side any more.
* GitHub automatically provides a temporary `GITHUB_TOKEN` with
sufficient write access to the project to publish a release, so we
don't need to carry around that secret.
[1] https://github.com/features/actions
[2] https://docs.gitlab.com/ee/ci/pipelines/
> cockpituous: Run release in a GitHub workflow

- src/base1/test-spawn-proc.js
In Debian sid coreutils, on a non-usrmerge system, seq lives in
/usr/bin.
> base1: don't hardcode seq(1) location in tests

- pkg/machines/components/vmSnapshotsTab.jsx
- test/verify/check-machines
The creation time of two two snapshots is the same within the test, so they appear in
random order in the list which confuses the test.
The test itself had some wrong logic as well, which was addressed within
this commit. For consistency use snapshot names following the rows
indexes because it get confusing otherwise.
> test: fix TestMachines.testSnapshotRevert flake

- tools/cockpituous-release
The built dsc doesn't go anywhere, so that just happens in vain. It's
also the only thing that requires a GPG key, so let's just drop that.
> cockpituous: Drop release-dsc

- test/verify/check-embed
- test/verify/files/embed-cockpit/embed.js
- test/verify/files/embed-cockpit/index.html
- test/verify/files/embed-cockpit/manifest.json
The default "Referrer-Policy" for chromium is now
strict-origin-when-cross-origin, which caused the previous version of
the test to fail as js from the local embed-cockpit.html file to the
iframe was considered cross-origin.
By making the embed file the default shell, it is no longer
cross-origin.
Fixes #14718
Closes #
> rhel-8.3: test: Fix check-embed to work with chromium>=85

- test/verify/check-embed
- test/verify/files/embed-cockpit/embed.js
- test/verify/files/embed-cockpit/index.html
- test/verify/files/embed-cockpit/manifest.json
The default "Referrer-Policy" for chromium is now
strict-origin-when-cross-origin, which caused the previous version of
the test to fail as js from the local embed-cockpit.html file to the
iframe was considered cross-origin.
By making the embed file the default shell, it is no longer
cross-origin.
Fixes #14718
Closes #
> rhel7.9: test: Fix check-embed to work with chromium>=85

- src/common/cockpitwebserver.c
https://bugzilla.gnome.org/show_bug.cgi?id=746339 got fixed long ago in
GLib 2.46. `g_socket_new_from_fd()` now returns a proper error if the fd
is not a socket.
Our glib dependency is already higher (2.50) than that, so drop the
hack.
> common: Drop obsolete hack in CockpitWebserver

- test/common/cdp.py
There are 200 allowed changes in 10 seconds by default. Bump it up to
9999 otherwise tests can hit this and then fail with:
```
Too many calls to Location or History APIs within a short timeframe.
SecurityError: The operation is insecure.
```
Fixes #14720
> test: Bump up location change rate limiter in Firefox

- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
Reduce the description list row spacing globally to 1.5rem.
Not a big difference here:
> services: Port service details info to PF4 description list

- test/verify/check-machines
We stop showing Oses whose release date is more than 3 years old, which
also don't have information about their EOL.
See https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/components/create-vm-dialog/createVmDialogUtils.js#L64
For Windows Server 2016 this was the case according to libosinfo
database.
***
{
"id": "http://microsoft.com/win/2k16",
"shortId": "win2k16",
"name": "Microsoft Windows Server 2016",
"version": "10.0",
"family": "winnt",
"vendor": "Microsoft Corporation",
"releaseDate": "2017-10-17",
"eolDate": "",
"codename": "",
"recommendedResources": {
"ram": 2147483648,
"storage": 42949672960
},
....
***
> test: fix testCreateURLSource not being able to pick up Windows Server 2016

- .github/workflows/unit-tests.yml
- containers/unit-tests/README.md
- containers/unit-tests/start
This allows us to test a new unit-tests container in a pull request by
(temporarily) specifying a staging tag, without breaking all other PRs,
and also keep all the configuration inside our repository.
Semaphore 2.0 has these advantages as well, but does not offer enough
(free plan) capacity to sustain the volume of Cockpit PRs. We even run
into bottlenecks with Semaphore 1.
Add a commented out step for an interactive debug shell, to provide an
equivalent for Semaphore's "Launch SSH session".
> github: Run unit tests as an Actions workflow

- pkg/machines/components/vm/vmExpandedContent.scss
- pkg/machines/index.html
The custom rule to stretch the page vertically is not needed any more.
> machines: pf-c-page should not be wrapped by a div

- test/common/testlib.py
Otherwise, we don't get any output when things like
self.assertTrue(condition)
fail.
> testlib: Also print assertion failures

- pkg/machines/components/vmDisksTab.jsx
Sometimes Ooops: TypeError would show when you try to load directly the
page with VM (e.g. .../machines#vm?name=[VM_NAME]&connection=[CONNECTION])
because there was no check to make sure that volumes, which are used to
get data about disk with volume as a source, were already fetched thru
dbus API.
> machine: Fix race condition when rendering data about disks

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/machines/components/deleteDialog.jsx
- pkg/machines/components/deleteResource.jsx
- pkg/machines/components/diskAdd.jsx
- pkg/machines/components/diskEdit.jsx
- pkg/machines/components/networks/createNetworkDialog.jsx
- pkg/machines/components/nicAdd.jsx
- pkg/machines/components/nicEdit.jsx
- pkg/machines/components/storagePools/createStoragePoolDialog.jsx
- pkg/machines/components/storagePools/storagePoolDelete.jsx
- pkg/machines/components/storagePools/storageVolumeCreate.jsx
- pkg/machines/components/vcpuModal.jsx
- pkg/machines/components/vm/bootOrderModal.jsx
- pkg/machines/components/vm/firmwareModal.jsx
- pkg/machines/components/vm/memoryModal.jsx
- pkg/machines/components/vmSnapshotsCreateModal.jsx
- pkg/machines/components/vmSnapshotsRevertModal.jsx
- pkg/machines/machines.scss
- test/verify/check-machines
For showing in progress in modals start using the isLoading variant of buttons
instead of showing spinner in the footer which is the suggested way from
PF4 to show in progress dialogs.
It will have one trivial merge conflict with https://github.com/cockpit-project/cockpit/pull/14740 but I want to see the tests since it will be probably a massacre.
> machines: port to PF4 modals

- configure.ac
- src/common/Makefile-common.am
- src/common/cockpithacks-glib.h
- src/common/cockpithacks.h
- src/common/cockpitjsonprint.c
- src/common/cockpitmemfdread.c
- src/common/cockpitmemfdread.h
- src/common/cockpittest.c
- src/common/cockpittest.h
- src/common/test-jsonfds.c
- src/tls/test-server.c
Also:
- add a convenient utility macro for asserting `GError` message contents
- fix a minor issue with the escaping in the printer code
> add tests for json-memfd print/parse

- pkg/systemd/hwinfo.jsx
- pkg/systemd/hwinfo.scss
That's a trivial PF3->PF4 conversion, no UI changes are expected.
Screenshot before and after here:
> hwinfo: replace ListView with DataList from PF4 in security mitigations modal

- package.json
- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.css
- test/verify/check-networking-bond
Upgrade @patternfly/patternfly to get support for help icon in modal
headers.
See https://github.com/patternfly/patternfly/issues/3474
> network: replace network page modals with PF4 modals

- test/verify/check-multi-machine
It legitimately takes about a minute on a quiet system, so it often ran
into the default 1min timeout.
Cherry-picked from master branch commit 25407ad
For https://github.com/cockpit-project/bots/pull/1311
> [rhel-8.3] test: Increase timeout for fips-mode-setup

- pkg/machines/components/vmOverviewTabLibvirt.jsx
That was cherry-picked from https://github.com/cockpit-project/cockpit/pull/14756/commits because it's actually fixing a bug (machines details page not wrapping properly) and should go inside this release.
> machines: Fix description (not group)

- src/common/Makefile-common.am
- src/common/cockpitcontrolmessages.c
- src/common/cockpitcontrolmessages.h
- src/common/cockpitmemfdread.c
- src/common/cockpitmemfdread.h
- src/common/cockpitwebserver.c
- src/common/test-jsonfds.c
- src/tls/connection.c
- src/ws/cockpitauth.c
- src/ws/session.c
- test/verify/check-login
For a long time (since `cockpit-tls` landed) we've been unable to log the IP address of remote connections.   Use our already-existing memfd-json utilities to add a metadata blob passed from `cockpit-tls` to `cockpit-ws` as a way of getting the connection metadata (specifically, the remote IP) into `-ws`.
> Use json-memfd to pass "origin-ip" from -tls to -ws (enabling remote IP logging)

- pkg/machines/components/vm/vmExpandedContent.jsx
When the VM is shut off we display a message, 'Please start the VM to
see the console'. The user should be able therefore to start it from the
same page the message is displayed at.
Fixes #14785
Previously:
Now:
> machines: show vm actions header in console page as well

- test/verify/check-machines
Flake was caused by the fact that usually snapshot create commands would
get spawned at the same time, so the creation time would be same.
When snapshots have different time creation, they are sorted
descendingly. When they have same time creation, they are sorted by
name, which is and ascending sorting. This create a race condition. Fix
it by forcing a different time of creation.
> machines: fix testSnapshotRevert flake

- .github/workflows/unit-tests.yml
The default is 6 hours, which causes too long hangs.
> workflows: Reduce unit-test timeout to 1 hour

- containers/unit-tests/run.sh
If the unit tests container manages to run for more than 50 minutes then
it's probably wedged.  Print out some extra info to help us track down
the problem.
See also #14813
> containers: dump some information on wedged unit tests

- test/common/run-tests
- test/common/testlib.py
- test/verify/check-dashboard
- test/verify/check-host-switching
- test/verify/check-machines
- test/verify/check-realms
This partially reverts the work done in 47dc4d28 (#14680). The goal of
the decorator should have been to not run decorated affected tests 3
times to make sure they're stable.
> test: Introduce @no_retry_when_changed

- pkg/machines/components/diskAdd.jsx
- test/verify/check-machines
Allow the selection of storage pool only after all of the volumes of
storage pools are fetched. This prevents a race condition which causes a
flaky test.
<details>
<summary>Example of such flaky test</summary>
```
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
error: Failed to start network default
error: Requested operation is not valid: network is already active
/usr/lib/python3.6/site-packages/rtslib_fb/root.py:175: UserWarning: Cannot set dbroot to /var/target. Target drivers have already been registered.
.format(self._default_dbroot)) …
```
> machines: fix testAddDiskSCSI

- .github/workflows/po-refresh.yml
We need this to fetch tags and history, as it builds the project.
> workflows: Fix po-refresh

- pkg/machines/components/vm/vmActions.jsx
- pkg/machines/components/vmOverviewTabLibvirt.jsx
should solve this issue: https://logs.cockpit-project.org/logs/pull-14819-20201027-163530-f61a5b97-rhel-8-3-distropkg/log.html#284
> machines: avoid crash because of vm.metadata being undefined on deleted VM

- .github/workflows/po-refresh.yml
This does a full package build at the moment, and thus requires build
dependencies.
Move to Ubuntu 20.04, as 18.04's libssh is too old.
----
My previous PR #14824 was not sufficient, it [failed on missing build deps](https://github.com/cockpit-project/cockpit/runs/1319197992?check_suite_focus=true). Now I properly tested this [on my repo](https://github.com/martinpitt/cockpit/runs/1319861003?check_suite_focus=true), with missing credentials -- so the actual po-refresh went alright, and it just (expectedly) failed to push it to the weblate git repo.
> workflows: Fix po-refresh harder

- pkg/lib/cockpit-components-table.scss
- pkg/machines/components/networks/network.jsx
- pkg/machines/components/storagePools/storagePool.jsx
- pkg/machines/components/vm/vmActions.jsx
- test/verify/check-machines
Stop overriding the size of the buttons with custom CSS and do it the
PF4 way instead.
Now clicking on run button twice in order to create an error does not
work so remove the relevant test code.
Fixes #14728
> machines: Improve visual feedback when changing a VM's state

- pkg/lib/cockpit-components-dialog.jsx
- pkg/lib/cockpit-components-install-dialog.jsx
- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/storaged/dialog.jsx
When an 'idle message' is presented show it in the same row with the
action buttons in the footer.
Before:
After: 
Before:
> storage: Show spinner inside the buttons when operation is in progress

- pkg/lib/cockpit-components-dialog.jsx
Many dialogs are using this component, especially in storage page.
Some of these are addressing long running operations, which should/cannot be stopped.
Cancel button is disabled in this case, but the users should not be able
to close the dialog with the [x] or Esc button either.
> lib: remove [x] button and the Esc handler on header from cockpit-components=dialog

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- test/verify/check-machines
By default GiB are used as a unit for memory. However if recommended memory is
something like 1.5GiB, it's floored to 1GiB which then results to error
and user having to fix it manually. Prevent this from happening.
Fix it also for storage.
> machines: Use MiB for memory/storage if recommended value is not a whole number

- pkg/shell/base_index.js
- pkg/shell/hosts.jsx
- pkg/shell/indexes.js
- pkg/shell/nav.jsx
There was this weird event listener in `pkg/shell/base_index.js` that
was listening on events from react components created in a completely
different place. It was very hard for other maintainers to find where
this is being handled.
Also this function had a bunch of hacks like ignoring `button`s clicks
or we had to have `event-eater` hack.
Also it was not working ideally as the hack with `button` did not work
out as expected when we clicked on the icon in that button.
This patch just does it "the right way" where we handle events on
appropriate elements when we create them. This does not need any of
those hacks and works more reliably not mentioning it is much better
readable.
Seems to work nicely for me, lets see if tests see some place I forgot to check out.
> shell: Implement navigation and host switching in more sensible way

- pkg/machines/components/aggregateStatusCards.jsx
Only Enter and Space should select the card that has focus.
:sigh we got this small bug inside the release yesterday.
> machines: fix keyboard navigation in for storage/networks cards

- Makefile.am
- containers/unit-tests/run.sh
Avoid the ginormous (> 64 KiB!) tar invocation lines with all our built
webpack inputs in silent mode. These made the build output hard to read
(finding warnings or errors), and unnecessarily blew up build logs.
Also reduce verbosity in unit test container runs -- there is no
surprise what's going on there, as it is a static container image, and
it's very easy to reproduce the run locally.
> build: Reduce tar verbosity

- pkg/machines/components/vm/bootOrderModal.jsx
- test/verify/check-machines
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1880175
> machines: Show cdrom details in bootorder dialog

- test/common/chromium-cdp-driver.js
- test/common/firefox-cdp-driver.js
Also if `text` is present, show rather that then the whole exception.
This error is super noisy and makes the log file too big.
See for example [this one](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14860-20201105-101029-336f7f16-fedora-32-firefox/log)
> test: Accept firefox reported error

- test/verify/check-machines
In addition, addCleanup functions will be called in reverse order to the order they are added (LIFO).
So we want the following cleanup order to appear:
- cleanup Pools and Networks
- cleanup Vms
- stop libvirtd
Since Vms use the above two resource types and this can lead to
cleanup issues if the order is not kept.
Lastly don't undefine Storage pools at cleanup, we don't do it for other
resources.
> tests: storage pool cleanup was meant to be done in teardown - not setup

- test/verify/check-login
We run the login tests not only on our own test VMs but also as part of
distro package validation testing.  Stop hardcoding the IP we use in our
test framework.
Fixes #14874
> tests: Accept more IPs in login tests

- src/common/cockpitchannel.c
- src/common/test-channel.c
The cockpit_channel_control() function can be called with
a NULL options argument. In the case of a "close" message
this would have resulted in a NULL pointer being used.
> commen: Fix NULL dereference in cockpit_channel_control()

- pkg/lib/cockpit-components-file-autocomplete.jsx
- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/systemd/overview-cards/serverTime.js
- test/verify/check-system-info
menuAppendTo="parent" should be used in this case.
Also remove redundant 'modal-body' class from the content of the PF4
Modal.
Fixes #14857 , please add it when merging - I forgot.
> PF4 Selects in modals are not espaping outside of the modals by default

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
If value is passed as unit object, then selector would choose the first
value since it expects only strings. The desired string can be found
under unit.name.
> machines: Fix incorrect unit shown in memory row

- pkg/shell/base_index.js
- pkg/shell/credentials.js
- pkg/shell/index.html
- pkg/shell/index.js
- pkg/shell/indexes.js
- pkg/shell/shell-modals.jsx
- test/verify/check-apps
- test/verify/check-menu
- test/verify/check-pages
There are still two remaining ones. Both use `pkg/lib/machine-dialogs.js` which cannot be simple converted into PF4.
@mvollmer mentioned some time ago that we shoud move all of these into dashboard (which also uses them) and implement the ones we need in host switcher in react. I think that is the approach in which we want to go.
Tests are going to be very sad, just want to get a list of failing tests that I can fix locally first.
> Migrate shell modals to PF4

- test/verify/check-machines
In the fedora CI images /dev/disk/by-path is missing. However by-id &&
by-uuid folders seem to exist in all environments, so better rely on
these.
This commit should fix the CI failure as seen here http://artifacts.dev.testing-farm.io/c62eccee-a5a7-44c6-bf49-a678743f00dc/work-tests.ymlwKJRIS/tests-1iMmfU/verify/TestMachines-testStoragePoolsCreate-fedora-32-localhost-22-FAIL.png
> tests: replace usage of /dev/disk/by-path with /dev/disk/by-id in machines tests

- .github/workflows/unit-tests-refresh.yml
This will make sure that we don't keep a  broken and un-upgradeable
unit-tests container around, like in the last year.
----
This is a single large job (will take over an hour), but I don't really know otherwise how to parallelize it effectively with keeping the atomicity. I.e. I wouldn't want to e.g. upload a new amd64 container if the i386 refresh fails. But nobody will actually watch this and wait for it, so I think it's bearable.
I temporarily copied the dockerhub cockpituous token secret to my fork, and [manually started a run](https://github.com/martinpitt/cockpit/actions/runs/361589834). Let's wait until this is successful before reviewing/landing.
> workflows: Add automatic weekly unit-test container refresh

- package.json
- pkg/dashboard/index.html
- pkg/dashboard/list.js
- pkg/lib/plot.js
- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- pkg/playground/jquery-patterns.html
- pkg/playground/metrics.html
- pkg/playground/pkgs.html
- pkg/playground/plot.html
- pkg/playground/service.html
- pkg/playground/test.html
- pkg/playground/translate.html
- pkg/shell/index.html
- pkg/shell/indexes.js
- pkg/sosreport/index.html
- pkg/storaged/devices.jsx
- pkg/storaged/index.html
- pkg/systemd/index.html
- pkg/systemd/logs.html
- pkg/systemd/logs.js
- pkg/systemd/services.html
- pkg/systemd/services/timer-dialog.js
- pkg/systemd/shutdown.js
- pkg/tuned/dialog.js
- src/base1/Makefile.am
- test/verify/check-pages
- webpack.config.js
base1's jquery API was deprecated 2½ years ago [1], and all external consumers got moved away from it in [2].
This requires some cleanup in our own webpacks (separate commit).
[1] https://cockpit-project.org/blog/cockpit-163.html
[2] https://github.com/cockpit-project/cockpit/pull/8505
> base1: Stop building and shipping jquery

- test/verify/check-machines
When killing the VMs  which are getting installed in the tests we always expect one
alert coming from virt-install, which we clear for the next Vm creation
to get tested. Sometimes more alerts are present and we should count with it,
instead of failing the test if more than one alert appeared.
Fixes failures like testCreateFileSource here https://logs.cockpit-project.org/logs/pull-14899-20201116-133548-02d8420b-rhel-8-3-distropkg/log.html
> tests: fix cleaning up alerts in TestMachines.testCreate*

- test/verify/check-login
- test/verify/check-machines
- test/verify/check-networking-bond
- test/verify/check-networking-bridge
- test/verify/check-networking-team
fedora-testing is now based on fedora-33, so remove it from the list.
> test: treat fedora-testing similarly to fedora-33 

- test/verify/check-storage-basic
- test/verify/check-storage-format
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-multipath
- test/verify/check-storage-nfs
- test/verify/check-storage-partitions
- test/verify/check-storage-raid1
- test/verify/check-storage-unused
- test/verify/check-storage-used
Our test VMs indeed prepare a qemu VM with a VirtIO disk present. However, in
fedora CI, we don't have control of the test environment provided, in
matters of what disks are present.
They currently use XEN virtual machines for testing, and the root
partition appears to be on /dev/xvd*, which is simply the Xen disk
storage device.
Let's make the check for when the storage page is loaded a bit more
relaxed. With this commit we wait for mount point == '/' in the
"filesystems" table.
> tests: don't rely on a VirtIO disk to exist in storage tests

- .github/workflows/unit-tests.yml
Sometimes gihub fails to trigger this workflow so allow us to do so
manually. Also drop the `pull_request` as it is not actually needed.
> workflows: Allow manually triggering unit tests

- src/base1/Makefile.am
- src/base1/test-chan.js
- src/base1/test-spawn.js
This test previously failed with the standard JS EventListener API, as
with that the registered listeners get called asynchronously, while with
jQuery they got called synchronously. This caused send() to _first_ call
the fallback MockPeer.onrecv() echo implementation, and _then_ the
registered "real" recv handler. Thus the former sent wrong and
unexpected replies. To fix that, postpone onrecv()'s own reply sending,
so that the event listeners have a chance to run first.
Adjust the number of expected messages in "filter message in" for that,
as this now does not see MockPeer.onrecv()'s standard reply any more.
This was the last jQuery consumer in the unit tests (and all of base1),
so drop the jquery bundling hack as well.
> base1: Drop jQuery usage from test-chan

- test/verify/netlib.py
Every now and then NetworkManager is not running and then bunch of tests fail.
Fixes #14877 - I could not find any reason why NetworkManager would not be running. Seems just like some rare race happening. Lets just start it back up. If I see the same issue again as I reported in #14877 I'll reopen the issue.
Fixes failures like these: https://logs.cockpit-project.org/logs/pull-14927-20201119-104043-0eba091a-ubuntu-stable/log.html#153-2
> test: Always start NetworkManager for NetworkCase tests

- test/common/testlib.py
We sometimes see also "Failed to generate stack trace: invalid `Elf' handle".
Should fix https://logs.cockpit-project.org/logs/pull-14923-20201119-031817-a364e9ca-fedora-33/log.html#43
> test: Accept more versions of "Failed to generate stack trace" messages

- test/verify/check-machines
$ osinfo-query os --fields=eol-date,release-date,name | grep CirrOS
CirrOS 0.3.0                                       | 2011-10-20   | 2013-02-08
CirrOS 0.3.1                                       | 2013-02-08   | 2014-03-19
CirrOS 0.3.2                                       | 2014-03-19   | 2014-09-08
CirrOS 0.3.3                                       | 2014-09-08   | 2015-04-22
CirrOS 0.3.4                                       | 2015-04-22   | 2017-02-14
CirrOS 0.3.5                                       | 2017-02-14   | 2017-11-20
CirrOS 0.4.0                                       | 2017-11-20   |
This list above shows that already three years passed from CirrOS last
release. Today was the last day that we showed CirrOS in the list,
following the pattern that when no EOL date is …
> tests: TestMachines: Stop using CirrOS image - since 20/11/20 it's missing from the dropdown

- test/common/testlib.py
> test: Don't disable preload for nonexisting packages

- test/common/run-tests
- test/common/testlib.py
So we don't break it in `run-tests` and also that we can be more safe in
bots' store-failures script.
> test: Make unexpected message a defined constant

- test/verify/check-storage-luks
The latest tang release in centos-7 (version 6-2) now contains a fix for
https://bugzilla.redhat.com/show_bug.cgi?id=1703445.
There are now no more OS images left using this branch which require
this workaround, so let's remove it entirely.
> test: remove tangd-update workaround

- test/verify/check-machines
debian-testing just got virt-install 3.2.0, which includes a fix to
prevent rebooting of a newly-created VM if it was manually stopped.
We therefore don't need this workaround on debian-testing anymore.
See also https://bugzilla.redhat.com/show_bug.cgi?id=1818089
See also https://github.com/virt-manager/virt-manager/commit/1b48772bc1fc8aa7fd390c7b42d675395e5d7969
> test: adapt to new virt-install in debian-testing

- pkg/machines/components/diskEdit.jsx
The onchange event occurs when the checked state has been changed, which
will happen for one of the radio buttons controlling the access mode.
The way this was implemented earlier was causing the dialog to have a
weird behavior on tests. Let's make one state update per event which
hopefully will robustify the testDiskEdit.
> machines: when changing the disk's access mode do it in a deterministic way

- .github/workflows/npm-update.yml
- .github/workflows/po-refresh.yml
The default `GITHUB_TOKEN` does not have the privileges to trigger
further workflows, in particular running unit tests. This is deliberate
behaviour [1].
So follow the recommendation and use our Cockpituous token instead.
Fixes #14941
[1] https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
> workflows: Use cockpituous instead of github token for npm/po updates

- .gitignore
- containers/unit-tests/run.sh
- po/Makefile.am
Commit 4b2f7176730 broke building cockpit.pot as src/base1/ does not
exist any more.
Let's prevent that in the future, and build the PO template during unit
tests, and do some spot-checks in it that it really catches HTML, js,
C, and manifest files.
> po: Fix PO template build

- Makefile.am
- configure.ac
- src/ws/cockpit-tempfiles.conf.in
- src/ws/cockpit.socket.in
- test/verify/check-connection
Prevent non-admin users from seeing useless messages about how to enable
the web console.  They can't do that anyway.
This adds a new configure option, --with-admin-user=, to define which
group is considered to be the admin users group.  The default is a check
for the following groups, in order: wheel, sudo, root.
Open question: should non-admins see the message about how to login?
> motd: show the motd only to admin users

- test/verify/check-metrics
This test is dependent on time of day. When it runs at an hour or day
boundary it can fail so lets just give it some safe time when it behaves
predictably.
Fixes #14950
> test: Set exact time for TestMetrics.testBasic

- pkg/machines/components/stateIcon.scss
- pkg/machines/components/vm/vmExpandedContent.scss
PF4 imports come first, then we import the custom CSS. In SCSS the most
rule should take effect, when there is not difference in the specificity.
I noticed on my system the opposite however.
When being certain about overwriting default value, increase the
specificity, so that we don't rely on the order of the imported CSS.
> Fix CSS rule specificity when overwriting PF4 rules

- pkg/machines/components/stateIcon.jsx
'state' should always be a string as we fetch it from the libvirt API, but
seems that users have encountered crashes because of 'state' being
undefined there.
Fixes #14959
> machines: ensure that 'state' is a String before applying string functions

- .github/workflows/po-refresh.yml
actions/checkout always uses a token to clone the tree. This lands in
.git/config as `extraheader = AUTHORIZATION basic ...`, which overrides
our global setting in ~/.git-credentials. As a result, `git push` to the
cockpituous fork was denied.
Tell checkout to use the cockpituous token instead for consistency.
> workflows: Fix po-refresh token

- test/common/run-tests
With this patch we can see in log which tests were ran on the same VM.
That is useful when we suspect something broke the VM but with 4
parallel nond machines running we cannot easily know which test ran
right before the test we investigate.
Would look something like this: (both zero as I ran them on one VM)
```
> warning: Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
> warning: transport closed: disconnected
ok 2 test/verify/check-networking-firewall TestFirewall.testNetworkingPage [ND] (0)
DevTools listening on ws://127.0.0.1:9378/devtools/browser/b4131698-953a-46b8-959c-bd2f79956fb8
CDP: {"source":"security","level":"error","text":"Refused to apply style from …
```
> test: Show which serial machine was used

- src/ws/login.js
Super-simple patch that swaps out style display for show/hide (which takes elements in addition to strings for this exact case).
> login: Use show() and hide() instead of display: block/none

- tools/cockpit.spec
- tools/debian/control
Cockpit 233 stopped shipping base1/jquery.js in cockpit-bridge, see
commit 049e8b8dce. The pages which still require jQuery started to
bundle it in their own webpacks. Thus users must not try a partial
upgrade with e.g. upgrading cockpit-bridge to ≥ 233, but leaving e.g.
cockpit-storaged at an older version.
Add Breaks/Conflicts to the cockpit-bridge package dependencies to
prevent that.
Fixes #14974
> tools: Prevent co-installation of newer bridge with older packages

- pkg/base1/test-dbus-common.js
Only do the D-Bus call after the watch is set up, like in the other
watch tests.
> base1: Fix race condition in "watch barrier" D-Bus unit test

- pkg/machines/components/stateIcon.jsx
replaceAll has been a native v8 string method only short time, therefore
it has not yet reached support in all browsers.
Fixes #14980
> machines: replace usage of replaceAll with replace

- .github/workflows/npm-update.yml
actions/checkout always uses a token to clone the tree. This lands in
.git/config as `extraheader = AUTHORIZATION basic ...`, which overrides
our global setting in ~/.git-credentials. As a result, `git push` to the
cockpituous fork was denied.
Tell checkout to use the cockpituous token instead for consistency.
See also d65d4c3789f5
> workflows: Fix npm-update token

- test/common/testlib.py
- test/verify/check-apps
- test/verify/check-dashboard
- test/verify/check-packagekit
Checking against image name has two disadvantages:
1. In RHEL downstream the "distropkg situation" can happen on base system as
well since we split into cockpit and cockpit-appstream and when we
update both on the same time, we are actually testing
cockpit-appstream against distro version.
2. When actively delivering to RHEL it is rather common that we need to
update tests on image refresh.
This approach solves both of these problems. Of course, it has potential
to leave old dead branches in the code, but I think it still provides us
with more advantages. Also it is easy to recognize if we can cleanup
these branches if we know what version of cockpit-system we have in our
oldest distropkg and what we have already released into rhel.
> test: Dynamically recognize distropkg affected versions

- .github/workflows/unit-tests-refresh.yml
- containers/unit-tests/build
- containers/unit-tests/start
We build and use the container on GitHub, so it makes most sense to also
keep the container image there, instead of downloading it from docker.io
dozens of times each day. The latter is not only wasteful, but also
prone to run into pull limits now.
> containers: Move unit-tests container to GitHub registry

- tools/cockpit.spec
- tools/debian/control
cockpit-docker has not been supported/built for a while, but apparently
some users still have it installed. Clean it up on upgrades as well (or
let them keep an older cockpit-bridge), but prevent broken partial
upgrades.
This extends commit 23fadbd9b25e4f3.
Fixes #14979
> tools: Prevent co-installation of newer bridge with older cockpit-docker

- .github/workflows/npm-update.yml
Pushing to the cockpituous fork failed due to
! [remote rejected] HEAD -> npm-update-qunit-20201201-144141 (shallow update not allowed)
Fetch the full history to fix that.
-----
I [ran this fix on my fork](https://github.com/cockpit-project/cockpit/actions/runs/394071621), it succeeded and produced PR #14991, and unit tests got triggered as expected. We can't/shouldn't actually land that as it includes the fix from this PR, but it proves that this works.
> workflows: Fix npm-update

- test/verify/check-machines
The refresh in https://github.com/cockpit-project/bots/pull/1365
introduces a newer libvirt which now handles firmware.
> test: centos-8-stream image supports VM firmware configuration now

- pkg/lib/patternfly/patternfly-4-overrides.scss
Add an override to let card headers wrap. This is also being addressed upstream.
Meanwhile, we have an override that fixes long content in headers, such as buttons in the action area on card headers.
> pf4: Allow card headers to wrap

- test/verify/check-machines
The refresh in https://github.com/cockpit-project/bots/pull/1365
introduces a newer libvirt which now handles firmware.
Cherry-picked from master commit 96fbc352dab. This also includes some
other OS list changes which are not really relevant for this branch, but
it's nice to keep the list in sync with master.
> [r83] test: centos-8-stream image supports VM firmware configuration now

- pkg/machines/components/vmOverviewTabLibvirt.jsx
An state error icon was missing a dismiss handler. Therefore an error
could no tbe dismissed from overview card even if it was already fixed.
> machines: Add a dismiss handler for state errors in overview card

- pkg/machines/libvirt-common.js
- pkg/machines/scripts/create_machine.sh
Commit 00263f56 removed the option from the UI but not the script. The
script ended up with passing to virt-install the user-password-file with
the content 'undefined' as string. This is obviously broken, so let's
just remove the option from here as well.
> machines: clean up create_machine.sh script from user-password-file option

- pkg/machines/components/vmSnapshotsCreateModal.jsx
When `fieldId` and `id` is used together, this label is unnecessary. But
mainly the `input text` part makes it more confusing then helping and
also tricky to translate. Screen readers know it is input and also that
it expects text, and thanks to fieldId it knows it is named Name or
Description.
> machines: Drop unnecessary aria-label

- pkg/machines/components/diskAdd.jsx
- pkg/machines/components/storagePools/storageVolumeCreate.jsx
- pkg/machines/components/storagePools/storageVolumeCreateBody.jsx
- test/verify/check-machines
Firstly, add an max size allowance when creating new storage volumes.
The new max value is the total capacity of the pool.
This is a very generous max limit, but anything stricter like setting
the pool capacity cancels the whole idea of thin-provisioning.
It's perfectly fine that the combined capacity of all volumes exceeds
capacity of the storage pool as long as the volumes are actually not using it
all.
Secondly, validate that the storage volume name is not empty.
This change affects two dialig, the Volume Creation and the Add Disk
dialog.
Fixes #13120
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1777685
> machines: add extra field validation for storage volume creation dialog

- pkg/tuned/change-profile.jsx
- test/verify/check-tuned
Also use PF4 components for labels and layout.
Fixes #3607
Now looks like this:
> tuned: Show which profile is active

- test/verify/check-sosreport
The mentioned issue was fixed, seems to work locally. Lets see what CI thinks.
This is driven as gating for 8.3 is broken on sos and if this works, we can just locally hack around it without delivering new version into BaseOs.
> test: Use proper config for sos 4

- pkg/machines/components/vm/vmActions.jsx
- pkg/machines/components/vmCloneDialog.jsx
- pkg/machines/components/vmCloneDialog.scss
- test/verify/check-machines
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1683391
Fixes #14523
For release notes:
Cloning creates a new VM that uses its own disk image for storage, but most of the clone’s configuration and stored data is identical to the source VM. This makes it possible to prepare a number of VMs optimized for a certain task without the need to optimize each VM individually.
> machines: add support for cloning VMs

- containers/unit-tests/run.sh
- pkg/base1/test-dbus-common.js
Install the "notify" handler before calling watch(). Before the test had
a race condition where watching finished before the onnotify_cache() was
installed, and thus `cache` was empty.
Also wait until watch() succeeds, so that the subsequent test does not
run into assertions being called after done(). watch() is guaranteed to
return after notify handlers got called [1], this ensures that this
actually happens.
[1] https://cockpit-project.org/guide/latest/cockpit-dbus.html#cockpit-dbus-watch
----
This is meant to fix [this failure](https://github.com/cockpit-project/cockpit/runs/1481034306?check_suite_focus=true#step:4:3598) ([another example](https://github.com/cockpit-project/cockpit/runs/1480864471?check_suite_focus=true#step:4:3180)), which currently haunts us like crazy, out of the …
> base1: Fix race condition in "watch change" dbus test

- pkg/sosreport/index.js
- test/verify/check-sosreport
Also, the refresh in https://github.com/cockpit-project/bots/pull/1441
updates sosreport to 4.0, so adjust the special case list accordingly.
Backported from master commit 792a3175a
> [r83] test: Use proper config for sos 4

- .github/workflows/unit-tests.yml
The recent podman version on the OSBS repo which GitHub workflows use
now fails as unprivileged user on Ubuntu 18.04 (which is still what
`ubuntu-latest` points to):
ERRO[0063] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH
This package does not yet exist in 18.04, so move the workflow to 20.04
instead.
Note: We could also run it with sudo or with docker, but let's keep
close to what developers do on their machines.
> workflows: Fix unit tests with podman

- pkg/storaged/drives-panel.jsx
- pkg/storaged/things-panel.jsx
Admittedly this is shown just when `$0 > 20` which would work fine for
majority of languages, but some languages use modulo when picking the
correct plural form where this would not work out.
> storage: Correctly use plural forms

- .github/workflows/unit-tests-refresh.yml
Similar as in commit 881b3343b90f, the unit-tests-refresh workflow now
fails in Ubuntu 18.04 due to missing slirp4netns. But for building
containers we also want overlayfs, which is also not available by
default. So run the builds and runs in system podman to avoid both
issues.
--- 
See the [recent nightly failure](https://github.com/cockpit-project/cockpit/actions/runs/404572813) for the now-familiar failure to talk to npmjs.com. I [triggered this manually](https://github.com/cockpit-project/cockpit/runs/1508679926?check_suite_focus=true), and it gets much further again, and just fails on the dreaded "watch change" test.
> workflows: Fix unit tests with podman for container refreshes

- tools/cockpit.spec
Commit cc34ffcab caused our COPR EPEL-8 builds to only build the basic
packages. This is not intended: Neither do COPR or EPEL repositories
have the BaseOS/AppStream split (so it doesn't make sense to split the
source package), nor do we ever release a cockpit-appstream.srpm to
them.
So make EPEL behave like Fedora and build all packages again.
Fixes #14974
> tools: Build all binary packages for EPEL

- pkg/lib/cockpit-components-terminal.jsx
This is a backport of part of 6341cf173473417e35dd88fbf049fa767c87fdcc
and prevents check-embed from flaking.
> terminal: Protect against invalid resizes

- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/history.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
Fixes: #14749
Fixes: #14723
Use PF4 cards for updates page. Redesign and refactor autoupdates.
.
.
.
> updates: Redesign available and up-to-date pages and autoupdates

- pkg/storaged/vdo-details.jsx
This allows naughty patterns to match it, and is generally the right thing to do.
> storage: Include stderr of fsadm in dialog

- doc/protocol.md
- src/common/Makefile-common.am
- src/common/cockpitframe.c
- src/common/test-frame.c
- doc: document that cockpit frames are non-empty
- common: add a restriction to the protocol format
- common: reimplement cockpit_frame_read()
> common: reimplement cockpit_frame_read()

- test/verify/check-subscriptions
This allows us to remove the various --insecure and insecure=0 options
when contacting Candlepin.
More importantly, it allows insights-client to perform its performance
metric upload to Candlepin, something that can't be configured to be
done insecurely.
> test: Configure the real Candlepin CA certificate on the client

- .github/workflows/npm-update.yml
- .github/workflows/po-refresh.yml
GitHub's base VMs don't automatically refresh package indexes, so it can
happen that one of the package dependencies get out of date and are not
available on the mirrors any more.
Run `apt update` first to ensure that the workflow installs the latest
packages.
Ported from starter-kit commit 8771907002e2.
> workflows: Fix apt installation

- package.json
- pkg/base1/cockpit.js
- pkg/lib/_global-variables.scss
- pkg/lib/cockpit-components-table.scss
- pkg/lib/listing.scss
- pkg/lib/page.scss
- pkg/machines/components/vm/vmDetailsPage.scss
- pkg/machines/components/vms/hostvmslist.scss
- pkg/machines/machines.scss
- pkg/playground/jquery-patterns.js
- pkg/playground/plot.js
- pkg/playground/speed.js
- pkg/playground/test.js
- pkg/shell/hosts.jsx
- pkg/storaged/devices.jsx
- pkg/storaged/storage.scss
- pkg/systemd/services/service-details.scss
- pkg/systemd/services/services.scss
- webpack.config.js
Explicitly include the required PF variables definitions into components
instead. This makes separate compilation and lib component reuse easier,
and paves the way for using sassc (which doesn't support global
resources). Finally it makes it explicit where we still use PF3, instead
of adding it to each and every built CSS file.
-----
This by and large works, but fails test-static code as the generated dist/base1/cockpit.css contains wrong font paths. I somehow feel between a rock and a hard place here: our webpack rule which applies the string-replace-loader stuff *only* applies to *.js files at the top level; I originally tried to build this from a separate pkg/base1/cockpit.scss, but this fails miserably. At the same time, when building it from cockpit.js it does not apply the …
> webpack: Drop sass-resources-loader

- pkg/shell/index.html
webpack builds shell.scss, which in turn imports nav.scss.
So, the requirement 'shell/index.css' is enough.
Fixes: #15057
> shell: Drop already bundled nav.css

- tools/debian/cockpit-ws.postinst
Use `/nonexistent` instead of `/nonexisting` home directory to be
consistent with other Debian system users.
Use `--quiet` to avoid confusing warnings on package installation.
https://bugs.debian.org/968400
> tools: Clean up cockpit-ws system user creation

- doc/authentication.md
There is a small typo in doc/authentication.md.
Should read `successful` rather than `succussful`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, succussful -> successful

- src/bridge/bridge.c
- src/bridge/cockpitpcp.c
- src/bridge/mock-bridge.c
- src/common/cockpithacks-glib.h
- src/ssh/cockpitsshrelay.c
- src/ssh/cockpitsshrelay.h
- src/ssh/ssh.c
- src/ws/main.c
~~Add a new log writer function (this is post-2.50 GLib language for a log
handler) which ensures that g_debug() lands on stderr instead of stdout.~~
~~This will allow us to drop our stdout→stderr redirections everywhere.~~
~~This is really really preliminary.  I have no idea if it will work.~~
~~It's also built on top of #14390 because there would be minor rebase issues otherwise, and I'm in a hurry :)~~
~~See https://gitlab.gnome.org/GNOME/glib/-/issues/2087 for an upstream discussion about this issue.~~
GLib 2.68 is gaining g_log_writer_default_set_use_stderr() to allow us to direct all logging output toward stderr.  Use that when it's available.
Because it's not widely available yet, move our dup2()-based "outfd" workarounds to a much simpler approach: assign the value of the stderr …
> all: remove "outfd" workaround

- tools/cockpit.spec
- tools/debian/control
cockpit's primary way to get a privileged bridge is through sudo now. If
it is not available, the shell just shows "Something went wrong / Spawn
failed". So recommend sudo to avoid this.
Demote polkit to a fallback dependency, to correspond to the shell manifest.
https://bugs.debian.org/978135
> tools: Recommend sudo over polkit

- containers/bastion/Dockerfile
- containers/ws/Dockerfile
I verified that `podman build` works for both containers still. I ran both produced containers, and cockpit-ws works. I can log in through the bastion host container to my SSH.
> containers: Bump bastion and ws containers to Fedora 33

- test/verify/check-kdump
Current kdump unit gained a `ConditionKernelCommandLine=crashkernel`
which makes the unit behave more gracefully in the default state -- it
stays stopped instead of failing. Adjust the test to get along with both
cases.
> test: Adjust check-kdump for unit with precondition

- pkg/lib/patterns.js
This will hopefully help with flaky Firefox tests which are not able
to produce screenshots.
Example: https://logs.cockpit-project.org/logs/pull-14913-20201216-093850-252cf626-fedora-32-firefox/log.html#49-2
> shell: Also log dialog field errors to console

- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.scss
- test/verify/check-networking-firewall
The 'Add service to zone' dialog was sligthly refactored to avoid usage
of custom components. The new design makes the UI more user friendly,
since the radio buttons don't jump around any more, when switching
between the two radio button options, and the attached text is revealed.
> firewall: remove PF3/bootstrap dependency

- test/common/cdp.py
When `TEST_BROWSER=firefox` was used together with `TEST_SHOW_BROWSER=1`
it was not playing along. In some newer version of firefox the one empty
argument caused some issues.
> test: Fix firefox in visible mode

- containers/unit-tests/README.md
- pkg/base1/test-dbus-common.js
In that test it could happen that after the first `notify` signal with
the expected properties there is a second `onnotify()` invocation with
an empty property update dict (which is unnecessary, but formally
conforming with the spec, and mostly harmless).
I broke that in commit d196498c44, which replaced a deep update of the
cache object with a shallow override: I wrongly thought that there
should/will only ever be one invocation.
Go back to a "deep update" to accomodate multiple notify signals,
similar to how the "watch interfaces" test works.
Fixes #15095
> base1: Fix D-Bus "watch barrier" test

- pkg/machines/components/vm/overview/vmOverviewCard.jsx
- pkg/machines/libvirt-common.js
- test/verify/check-machines
The default VM CPU mode is to host-model mode. The XML in this case looks like:
<cpu mode='host-model' check='partial'/>
When the Vm starts, the live xml adapts and shows the host-model expanded.
This is expected and important since the expansion varies depending on
the host and so needs to be tracked across migration.
Therefore, when performing the check between inactive and active XML CPU
configuration, we need to have a special case for the host-model mode.
Related to: rhbz#1913205
> machines: fix check of cpu configuration between active/inactive XML

- test/verify/check-metrics
Replace the hardcoded list of which images have swap with a `swapon --show`
check. This allows us to change our images (virt-install vs. cloud
image) and, as a @nondestructive test, also makes it more robust for
running as downstream gating test.
> test: Dynamically detect swap in check-metrics

- webpack.config.js
This may be borderline useful for single-webpack projects like
starter-kit, but it is too much noise for cockpit with its many webpacks.
> webpack: Quiesce sassc version

- src/bridge/cockpitpcpmetrics.c
I cannot build the source due to this error:
```
src/bridge/cockpitpcpmetrics.c: In function ‘convert_metric_description’:
src/bridge/cockpitpcpmetrics.c:516:25: error: passing argument 2 of ‘pmLookupName’ from incompatible pointer type [-Werror=incompatible-pointer-types]
516 |   rc = pmLookupName (1, (char **)&info->name, &info->id);
|                         ^~~~~~~~~~~~~~~~~~~~
|                         |
|                         char **
In file included from src/bridge/cockpitpcpmetrics.c:29:
/usr/include/pcp/pmapi.h:266:39: note: expected ‘const char **’ but argument is of type ‘char **’
266 | PCP_CALL extern int pmLookupName(int, const char **, pmID *);
|                                       ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Not sure why CI nor anyone …
> pcp: Fix cast

- src/bridge/cockpitwebsocketstream.c
- src/bridge/cockpitwebsocketstream.h
- src/bridge/test-websocketstream.c
We add a ref to the object when making the async call, but we don't free
it from the completion handler.  Use an autoptr to make sure we get this
right.
Also, modernise the header a bit to make sure autoptr works with this
type.
Add a testcase which detected a leak before this change.
I've spent a couple of days being confused about why valgrind is only flagging this leak in a small number of cases.  It was reliably triggered from the branch porting the cockpit connection code to GSocketClient (due to an earlier error being flagged, which I've replicated here in another test).  This fix seems logical and correct to me, but I'm a bit nervous that there's an outstanding reference somewhere...
Let's see what the bots think.
> bridge: fix a leak on connect in websocketstream

- src/common/cockpitmemory.c
- src/ws/cockpitauth.c
- src/ws/cockpitcertificate.c
- src/ws/test-creds.c
Replace our homegrown shenanigans with a more "official" way.
cockpit_memory_clear() has an additional useful feature of clearing a
nul-terminated string if len is specified as -1, so keep it around for
this purpose alone.
> common: reimplement cockpit_memory_clear()

- src/ws/cockpitauth.c
- src/ws/test-handlers.c
- test/verify/check-connection
Mark our cookie as `SameSite: Strict` [1]. The current `None` default
will soon be moved to `Lax` by Firefox and Chromium, and recent versions
started to throw a warning about it.
[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
https://bugzilla.redhat.com/show_bug.cgi?id=1891944
> ws: Restrict our cookie to the login host only

- src/bridge/cockpitconnect.c
- src/bridge/cockpithttpstream.c
- src/bridge/cockpitstream.c
- src/bridge/cockpitwebsocketstream.c
- src/bridge/test-httpstream.c
- src/bridge/test-websocketstream.c
- src/common/cockpitwebserver.c
Replace our home-grown iterator/connect logic with GSocketClient: it's more than powerful enough to do everything we need.
Take the opportunity to port to GTask.
Right now I want to see what the bots say about this.  The second commit needs to be discussed.
> bridge: use GSocketClient in cockpit_connect_stream()

- src/bridge/cockpitconnect.c
Move a variable declaration from top-of-block to site-of-assignment to
avoid a false-positive from clang.
> bridge: shuffle around some deck chairs

- test/common/testlib.py
- test/verify/check-host-switching
- test/verify/check-journal
- test/verify/check-machines
To prevent ourselves from using this due to muscle memory.
@martinpitt WDYT about this? This is just idea how not to introduce new cases just because we are used to writing `wait_present`.
> test: Rename wait_present to discourage it's usage

- test/verify/check-system-info
This started failing with:
#hwinfo th:contains(CPU) is ambiguous
Indeed there are two elements starting containing 'CPU' string in the
description. Let's keep using the old wait_present method.
See failure https://logs.cockpit-project.org/logs/pull-15130-20210113-101552-dd028da8-fedora-33/log.html#298-2
> tests: fix TestSystemInfo.testCPUSecurityMitigationsEnable

- po/Makefile.am
Then the `find` could not find the file as it was one directory up as
expected.
I tried to unify all the .pot files to use the same pattern, but that
did not work out well, as each works ever so slightly differently.
> po: Don't double cd when building cockpit.appstream.pot

- .github/workflows/unit-tests-refresh.yml
- .github/workflows/unit-tests.yml
- containers/unit-tests/README.md
- containers/unit-tests/build.sh
- containers/unit-tests/run.sh
- containers/unit-tests/scenario-check-memory.sh
- containers/unit-tests/scenario-distcheck.sh
- containers/unit-tests/start
- tools/check-dist
Split the actions performed while unit testing into separate files:
- build.sh: configure and build on a checked out tree
- scenario-check-memory.sh: run `make check-memory`
- scenario-distcheck.sh: run various `make distcheck` type tests
This allows a human user to run the various test scenarios on a checked
out tree, including building it with the correct arguments, without
spinning up a container.
Modify run.sh to always call build.sh, and call a scenario script
according to the value of the SCENARIO environment variable.  Modify the
start script to set this variable according to a now-mandatory
commandline argument.
Adjust the github workflows so that we do four testcases now:
- amd64 gcc check-memory
- i386 clang check-memory
- amd64 clang distcheck
- i386 gcc distcheck
This gets us …
> unit-tests: Introduce unit-test "scenarios"

- pkg/storaged/side-panel.jsx
- pkg/storaged/storage.scss
Just place the two elements using flex instead of arranging them using
two table columns.
Fixes #14973
> storaged: fix sidepanel warning/actions overflowing on some screen sizes

- doc/protocol.md
- src/bridge/cockpitfslist.c
- src/bridge/test-fs.c
For #14170, This is just the starting point for running strace, I added a few basic attributes that are usually available for ls. 
This PR also does not do anything regarding the watch on fslist, I'd be happy to have any guidance how to handle it.
> bridge: Add extra parameters on fslist

- test/verify/check-machines
This would fix a failing test in case of different moment js formats
(e.g. "Today 11:11 PM" vs "Today at 11:11 PM")
Fixes a test fail at https://github.com/cockpit-project/cockpit/pull/15120
> machines: Fix test for different time formats

- src/bridge/cockpitpeer.c
This was always the intention, but the code would potentially treat
many of the early "open" requests as being first, until the peer
bridge would send its "init" message.
This was mostly harmless since the code would combine properties from
all these "open" requests, and none would be lost.  Except for
"init-superuser", where later requests would overwrite earlier ones.
It is not useful to have properties like" user" and "password" on
anything but the first request.  Thus, we make it so that we only ever
look at the first "open" request.
> bridge: Only gather info from the first channel for peer bridges

- test/verify/check-metrics
Fixes our #2 top flake on https://images-frontdoor.apps.ocp.ci.centos.org/failure-stats.html
> Reorganize check-metrics, fix "current memory" metric flake

- test/verify/check-metrics
This fixes the 7th [top flake](https://images-frontdoor.apps.ocp.ci.centos.org/failure-stats.html) ([example](https://logs.cockpit-project.org/logs/pull-15123-20210115-073403-44eb2a33-ubuntu-2004/log.html#81-2)), and another one that I saw during my local runs. I'm not 100% sure about the third commit yet, I'll either squash it or take it out. Locally tests work for me with debian-testing and ubuntu-2004, but let's get them a crunching through our bots.
> Fix check-metrics tests that use prepareArchive()

- pkg/lib/cockpit-po-plugin.js
starter-kit and other projects that just have one webpack have no need
to specify any option. The plugin previously crashed with
TypeError: Cannot read property 'subdir' of undefined
in that case. Default to an empty object if options are undefined.
> lib: Fix cockpit-po-plugin instantiation without options

- test/verify/check-login
This test is written with the assumption that trying to change the PAM
password to a bad one will have more than one retry. This isn't the case
on some images that use authselect, such as our centos-8-stream or
rhel-8-* images.
This was previously hacked around in the image *.install scripts [1],
but also hits us in Fedora/RHEL downstream gating tests, which is why
that test is currently skipped [2]. Adjust the PAM config in the test
itself, so that it can run in any testbed, and we can re-enable the test
downstream.
[1] https://github.com/cockpit-project/bots/pull/1555
[2] https://src.fedoraproject.org/rpms/cockpit/blob/917966b/f/tests/run-test.sh#_75
Cherry-picked from master commit 83e1ec6c9504f.
> [rhel-8.3] test: Fix TestLogin.testExpired for pam_pwquality with retry=1

- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-overrides.scss
- pkg/systemd/hwinfo.jsx
- pkg/systemd/terminal.jsx
- pkg/systemd/terminal.scss
- test/verify/check-terminal
In the meantime terminal page was fixed for mobile devices:
Previously:
Now:
> Stop importing PF3 in terminal and hwinfo pages - and some tiny cleanups

- test/verify/check-system-info
The first commit is good, and will fix the follow-up errors that we see often:
```
subprocess.CalledProcessError: Command 'if selinuxenabled 2>/dev/null; then chcon --reference /proc/cmdline /run/cmdline; fi && mount --bind /run/cmdline /proc/cmdline' returned non-zero exit status 32.
```
But the initial failure is in b.reload():
```
{"exceptionId":1,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9191/cockpit/$91dd94251495964ea7683d4428bfbe9207ff1951456cd17b1642ef718eb9f1c5/system/hwinfo.html#/","exception":{"type":"object","className":"te","description":"te","objectId":"{\"injectedScriptId\":14,\"id\":1}","preview":{"type":"object","description":"te","overflow":false,"properties":[{"name":"problem","type":"string","value":"internal-er …
```
> Fix TestSystemInfo.testCPUSecurityMitigationsDetect flake

- test/verify/check-journal
- test/verify/check-metrics
- test/verify/check-services
In rhel-8.4 it is not available, see https://bugzilla.redhat.com/show_bug.cgi?id=1918340
As part of https://github.com/cockpit-project/bots/pull/1551
It still will have one test failing, but that one we need to naughtify
> test: Only disable ntp if available and active

- test/common/cdp.py
So that people can easily have both the regular Firefox for their
normal use and Firefox Nightly for the tests.
> test: Look for and prefer "firefox-nightly" executable

- tools/debian/control
- tools/debian/rules
hppa needs almost an hour to run the test-tls-certfile unit test. Skip
slow tests on this architecture to avoid a build timeout.
https://bugs.debian.org/981127
> tools: Skip slow tests on hppa in Debian

- pkg/storaged/mdraid-details.jsx
This should be triggered by mdraid itself, but doesn't seem to happen
reliably.  This is not a surprise.
> storage: Trigger udev after adding disks to a MDRaid device

- pkg/shell/base_index.js
- pkg/shell/indexes.js
- pkg/shell/machines/machines.js
- test/verify/check-host-switching
Release note:
----
Cockpit remembers all remote hosts of a session and used to immediately connect to all of them when starting the next session.  Now a SSH connection is only opened when navigating to the remote machine for the first time.
> shell: Never connect to remote machines automatically

- tools/webpack-make
In some versions of webpack, irrelevant warnings are resulting
in failure to build from sources
> tools: Don't treat webpack warnings as errors

- test/common/testlib.py
The current nightlies now support the `Page.captureScreenshot()` API.
> test: Enable screenshots for Firefox

- README.md
We stopped using semaphore a while ago...
> README.md: remove link to semaphore build status

- test/verify/check-realms
TestKerberos.testNegotiate() is using an undocumented feature of
m.execute() by passing the individual arguments of curl as a list rather
than a string.  This feature has long been broken: ssh just concatenates
the arguments back together anyway.  This is plainly illustrated by the
fact that this test has been calling m.execute() with
'/usr/bin/curl -v -s'
as the first argument, and it's been working.
Split that out properly in preparation for an upcoming change to the
bots to make this function properly.
> test: fix an m.execute() invocation in check-realms

- test/verify/check-login
As of pam 1.4.0-1 in debian-testing, tally2 is gone and has been
replaced with faillock.  Unfortunately, the tests are currently failing
due to the /sbin/faillock command not currently being properly packaged.
For now, we're introducing a naughty in bots#1569 to deal with that, but
let's make sure that this test starts working again properly once the
issue has been resolved.
> check-login: use faillock on debian-testing

- test/verify/check-realms
Commit 426bd42b31a1f was incompatible with
https://github.com/cockpit-project/bots/commit/13eff0d5743b
and also did not really make sense: `2>&1` is shell syntax, not an argv,
so instead run the whole command as a single shell string.
> test: Fix check-realms curl invocation harder

- pkg/machines/components/vm/overview/bootOrder.jsx
- test/verify/check-machines-create
- test/verify/check-machines-settings
It was implemented previously quite naively, resulting in wrong warnings
being shown in the UI when there was a mismatch between the active and
inactive XML bootable devices.
For example:
* The user would attach a transient disk/NIC to the running guest.
* That would cause a mismatch between the enumerated bootable devices
between the active and the inactive XML configuration,
* The UI would show a warning, but there would be no way for the user to
find out that the transient device they just added was the reason
for the warning.
Doing a 1-1 comparison of the bootable devices between the active and
inactive XML is a real pain, since these devices don't have some unique
common identifier.
So let's remove this functionality of allowing the users to edit boot
order on running VMs to avoid …
> machines: Disable boot order editing for running guests

- tools/cockpit.spec
It was in condition for RHEL only.
Don't use 'Provides' as [1] states:
```
If a package supersedes/replaces an existing package without being a sufficiently
compatible replacement as defined above, use only the Obsoletes: line from the above example.
```
[1] https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages
> spec: Fix obsoleting of c-dashboard for also Fedora - FIX COMMIT MESSAGE ON MERGE!

- Makefile.am
- tools/build-debian-copyright
- tools/npm-install
It's a reasonably common problem to pull, switch branches, or rebase on
top of new changes from master, and have changes to node module
dependencies which will cause the build to fail if `npm install` isn't
run again.  Even worse: sometimes the build succeeds, only to cause
runtime javascript errors during testing.
This is almost always indicated by a corresponding change in
package.json.
Make sure package-lock.json is newer than package.json, and if not,
display a warning about it, asking the user to fix it.  Use a ridiculous
amount of whitespace to make sure the message sticks out from the noise
and to make it easier to copy/paste the suggested command.
Also: add a new Makefile target `make npm` to explicitly touch
package-lock.json after a sucessful `npm install` (since npm won't do it …
> build: force `npm install` after package.json changes

- Makefile.am
Instead of our substitution rule being used to transform
pkg/*/manifest.json.in
into
pkg/*/manifest.json
and then a separate copy rule being used to copy the file into
dist/*/manifest.json
just do the substitution directly.
This solves two minor issues:
- the pkg/*/manifest.json files were being treated by make as
non-precious intermediates, which means that you'd often see them
being deleted as part of a large `rm` at the end of a fresh build
- for some reason, webpack-make is writing the manifest.json file for
networkmanager (and only networkmanager) to its Makefile.deps,
resulting in make *not* deleting the file as a non-precious
intermediate.  This had the effect that we'd see spurious copies of
the file sometimes.
> build: change the generation of manifest.json

- test/verify/check-storage-vdo
- test/verify/storagelib.py
The device is often still busy.
> test: Retry deletion in StorageTestVDO

- test/verify/check-realms
TestKerberos.testNegotiate() is using an undocumented feature of
m.execute() by passing the individual arguments of curl as a list rather
than a string.  This feature has long been broken: ssh just concatenates
the arguments back together anyway.  This is plainly illustrated by the
fact that this test has been calling m.execute() with
'/usr/bin/curl -v -s'
as the first argument, and it's been working.
Split that out properly in preparation for an upcoming change to the
bots to make this function properly.
Cherry-picked from master commits 426bd42b3 and a2c78179fe4.
> [rhel-7.9] test: fix an m.execute() invocation in check-realms

- test/common/testlib.py
They take a *lot* of space and upload bandwidth, and we use them so
rarely that it is not generally worth the trouble. We can re-enable them
on demand if we every run into crashes which can't easily be reproduced.
> test: Stop creating core dump artifacts

- test/common/run-tests
If there is no .git directory, i.e. when running from a release tarball,
then run-tests spits out an unsightly two-page long git error and help.
Check if the project is a git checkout before trying to determine
changed tests.
> tests: Fix git help spewage when running from releases

- pkg/apps/utils.jsx
- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
A followup of a previous redesign. It mainly changes:
- Fix a autoupdates modal not closing
- Use PF4 progress bar instead of a custom one
- And most importantly, get rid of the Header bar, which was almost always present on top of the updates page. After a previous redesign, the Header bar was only used to show a status of what's happening in updates page and a Cancel button in case an update is in progress. Both of this can be shown in an empty state panel:
> updates: Redesign updates followup

- tools/cockpit.spec
- tools/make-srpm
Turns out that sources in BaseOS *can* ship binary RPMs in AppStream as
well. This got an explicit blessing, and will significantly simplify our
downstream packaging.
We may eventually reunite them for RHEL 8 as well, but for now let's fix
RHEL 9 and ELN.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1916251
> tools: Drop cockpit-appstream split for RHEL/ELN ≥ 9

- package.json
- pkg/lib/cockpit-components-file-autocomplete.jsx
- pkg/lib/patternfly/patternfly-4-overrides.scss
- test/common/testlib.py
- test/verify/check-pages
* debouncedChange method was never called, which is clearly caused by some refactoring
oversight. However it's needed for monitoring the user's key input.
* PF4 Select's onFilter property can be used to *synchronously* filter the select
options, however the displayed filesystem entries are updated asynchronously.
We therefore need to allow PF4 to do the filtering.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872660
Blocked on:
https://github.com/patternfly/patternfly-react/pull/5370
https://github.com/patternfly/patternfly-react/pull/5375
> lib: improve our custom FileAutocomplete component

- pkg/lib/cockpit-components-table.jsx
When we use `<Th>` as cell elements, the dataLabel property is not applied
correctly and we got a warning in the console. In addition in the mobile
mode the missing `data-label` was causing the cell labels to not exist.
Use the original `data-label` property to fix the visual regression until it's fixed upstream by:
https://github.com/patternfly/patternfly-react/pull/5406
> lib: workaround missing dataLabel property in <Th> PF4 component

- test/README.md
> test: Update nested virt documentation URL

- pkg/machines/app.jsx
- pkg/machines/components/vm/vmDetailsPage.jsx
- pkg/machines/components/vm/vmDetailsPage.scss
The VM details page can get quite long, and notifications were stored
before this commit on the top of the page. When the problematic operation was
initiated from somewhere in the bottom of the page, the notifications
panel was not visibile for usual screen sizes. Let's make the notifications
sticky as we do in the main page.
Previously:
Now:
> machines: use toast notifications in the VM's details page

- src/websocket/test-websocket.c
- src/websocket/websocket.c
It is possible for g_hash_table_insert to invalidate the strings. Move the ownership transfer to after the check to ensure we don't touch the name and value again after insert.
> web_socket_util_parse_headers: Move Insert after check

- pkg/packagekit/updates.jsx
Page header is usually no longer present on other cockpit pages
> updates: Get rid of the page header

- tools/cockpituous-release
Fedora "master" branches were renamed recently.
> tools: Rename Fedora rawhide branch in cockpituous control file

- pkg/apps/application.css
- pkg/apps/index.html
- pkg/kdump/index.html
- pkg/kdump/kdump-view.jsx
- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-overrides.scss
- pkg/lib/table.css
- pkg/machines/index.html
- pkg/metrics/index.html
- pkg/metrics/metrics.scss
- pkg/networkmanager/firewall.html
- pkg/networkmanager/index.html
- pkg/networkmanager/networking.scss
- pkg/packagekit/index.html
- pkg/packagekit/updates.scss
- pkg/selinux/setroubleshoot.html
- pkg/shell/shell.scss
- pkg/sosreport/index.html
- pkg/sosreport/sosreport.scss
- pkg/storaged/index.html
- pkg/systemd/hwinfo.html
- pkg/systemd/index.html
- pkg/systemd/logs.html
- pkg/systemd/logs.scss
- pkg/systemd/overview.scss
- pkg/systemd/services.html
- pkg/systemd/services/services.scss
- pkg/systemd/terminal.html
- pkg/systemd/terminal.scss
- pkg/users/index.html
Remove all per page CSS for this purpose.
The single visual difference by this is that loading page spinner is in
the center of the page now, instead of the top that it was before.
This is the expected behavior.
Please review carefully :) Prone to :bug:
> Add a global CSS rule for extending pages height and avoid double scrollbar

- pkg/networkmanager/firewall.html
One test checks that `<div id="firewall"` exists.
This was introduced in 9113eb5f.
> firewall: Change order of aattributes to make tests happy

- tools/cockpituous-release
Fedora 34 branches from Rawhide today:
https://fedorapeople.org/groups/schedule/f-34/f-34-all-tasks.html
bodhi will get enabled in two weeks, so don't add that yet.
> cockpituous: Add Fedora 34 koji builds

- pkg/lib/cockpit-components-file-autocomplete.jsx
cockpit-certificates uses a custom version of that component that can be
dropped once FileAutocomplete supports creatable files.
> lib: add fileExists property to FileAutocomplete component

- .github/workflows/build-dist.yml
- Makefile.am
- containers/unit-tests/scenario-dist.sh
- containers/unit-tests/scenario-distcheck.sh
- containers/unit-tests/start
The npm install/webpack steps are very expensive, and annoying to do
locally for reviewing PRs or updating a local checkout. Introduce a new
"build-dist" workflow which creates a downloadable dist tarball for each
interesting commit (PRs and pushes to master for now).
Split out the building part from scenario-distcheck.sh into a new "dist"
scenario, so that we can finish this workflow in the least possible
amount of time, as we soon want to trigger the tests after this
workflow, to re-use the built dist tarball.
Skip building the cockpit-cache*.tar.xz for this workflow -- we don't
need it for CI and it's expensive to build.
------
Note: This does not yet use the built dist tarball in unit nor integration tests. I'd like to build this one step at a time. The next step would be to adjust …
> Build `make dist` artifact for every master commit and PR

- pkg/base1/cockpit.js
cockpit.language was previously set inside cockpit.locale. That function
was only called for the languages which have a matching 'po' file.
English as the default does not have a po file and therefore
cockpit.language was not set for it. Similarly there was not cockpitLang
cookie when english was used.
> Make sure that cockpit.language is set also when that is english

- pkg/lib/patternfly/patternfly-overrides.scss
This should hopefully keep both PF3 and PF4 in check and let us have the correct spacing for each.
> lib/pf: Unset PF3 margin for PF4 radio/checkbox

- .github/workflows/build-dist.yml
actions/checkout uses the `pull/NNN/head` ref by default instead of the
proposed branch's HEAD. This lead to wrong tarball names:
The SHA in `cockpit-*.g<SHA>.tar.xz` did not match the artifact's
`dist-<SHA>` name and moreover not the local developer's `git describe`,
so that it is impossible to check whether the dist tarball for the
current local version was already downloaded.
Tell the checkout action to explicitly check out the PR's proposed
branch, exactly like in naming the artifact.
----
Our pre-built artifacts on github have a correct tarball name for `push` events:
```
❱❱❱ unzip -t dist-d6ba35c7ecebab22cbceba7757b6e7afab9b5621.zip 
Archive:  dist-d6ba35c7ecebab22cbceba7757b6e7afab9b5621.zip
testing: cockpit-237.13.gd6ba35c7e.tar.xz   OK
```
But it is wrong for PRs:
```
❱❱❱ unzip …
```
> workflows: Fix build-dist tarball name for PRs

- pkg/metrics/metrics.jsx
- src/bridge/cockpitcpusamples.c
- src/bridge/cockpitinternalmetrics.c
- src/bridge/test-metrics.c
- test/verify/check-metrics
Shows up to 16 cores ordered by their load. I picked 16 as it is a number that the UI manages just fine, is still human parsable (having list of 150 items is not) and standard user will see all their cores and on big servers it will be obvious that the list is shorter.
> Show busiest CPU cores

- pkg/machines/actions/provider-actions.js
- pkg/machines/components/vm/disks/diskAdd.jsx
- pkg/machines/libvirt-dbus.js
- pkg/machines/xmlCreator.js
- test/verify/check-machines-disks
Until this moment, a VM's disk could been only specified by **storage pool + volume combination**. However libvirt allows also to specify a disk thru a **file path** (useful for things such as adding iso files as disks to existing VM https://github.com/cockpit-project/cockpit/issues/13003).
The "Use Existing" section now has option to choose Source Type. Pool+Volume combination is default.
Custom path option allows user to specify a path to file to be used as disk.
> machines: Disks with custom file paths

- Makefile.am
- test/image-prepare
- tools/cockpit.spec
Since the introduction of `$XZ_COMPRESS_FLAGS` in commit 67831b9d2f and
supressing the build of cockpit-cache-* tarballs in commit 3482db3f5
there is no reason to build a .tar.gz dist any more, as `xz -0` is even
faster than gzip.
Drop the `dist-gzip` make target, adjust the "dump file name" target for
xz, and switch the .spec and image-prepare to using the tar.xz
targets/tarballs.
bots/make-source defaults to `dist-gzip`, is rather hard to work with
for dist-xz even with a custom target, and most of it is a big cockpit
special case (and not used in any other project). Let's phase it out,
and just do the few build steps ourselves -- these are project specific
anyway, so let's not pretend we can do an "one size fits it all" script.
While at it, replace make-source's static `-j8` with a …
> build: Drop gzipped dist tarballs and make-source usage

- src/branding/opensuse/Makefile.am
Just installed cockpit on a tumbleweed system and was sad to see it had the default favicon so I found `/usr/share/pixmaps/distribution-logos/square-hicolor.svg` and converted it to a 48x48 favicon.ico.
> Add OpenSUSE Tumbleweed favicon

- Makefile.am
- pkg/lib/included-modules-plugin.js
- tools/build-copying
- tools/build-debian-copyright
- tools/debian/copyright.template
- tools/webpack-make
- webpack.config.js
This is the branch to stop disting fragments of node_modules/ for copyright and dependency purposes.
I'm currently locally inspecting in detail the difference between the generated tarballs, but it looks pretty promising so far...
> Stop disting node_modules/ fragments

- test/common/run-tests
Every failed test that is not retried (like the third run) does not have
new line after test name. Example:
```
not ok 59 test/verify/check-machines-disks TestMachinesDisks.testAddDiskAdditionalOptions [ND@1]# ----------------------------------------------------------------------
```
This causes issues for storing tests. We have workaround for stripping `# ---` from test names.
But sometimes when things go haywire, we don't get this devider, but we
might get something like:
```
not ok 294 test/verify/check-testlib TestRunTestListing.testBasictimeout: failed to run command `test/verify/check-shell-active-pages`: No such file or directory
```
Always putting new line at the end of the output prevents this unwanted behaviour.
Example logs:
- With having `timeout:` on the same line - …
> test: Always end up test with a new line

- test/verify/check-static-login
Configure pam_faillock on debian-testing the same way as on all other
OSes, with deny=4. The default is 3, which caused the test to fail.
This was previously hidden by our naughty for the missing `faillock`
binary (https://github.com/cockpit-project/bots/issues/1585), but this
was fixed in pam 1.4.0-3.
> test: FIx TestLogin.testTally for debian-testing

- src/ws/remotectl-certificate.c
- src/ws/test-remotectlcertificate.c
- test/verify/check-connection
Only call set_cert_attributes() for our own managaged 0-self-signed
certificate. Administrator provided ones are often shared with other
services, and mangling the permissions on every cockpit.service start
can actively damage these.
Add unit tests which cover both "our own" and "admin managed" cases.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1907254
> ws: Don't let remotectl touch permissions of admin-provided certificates

- pkg/metrics/metrics.jsx
- pkg/systemd/overview-cards/insights.jsx
- pkg/systemd/page-status.jsx
> Remove last redundant tabIndex attributes

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/machines/components/create-vm-dialog/createVmDialogUtils.js
This is an attempt to fix testCreateFileSource flake as seen [here](https://images-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-machines-create+TestMachinesCreate.testCreateFileSource).
> machines: use debounce instead of custom setTimeout when calling onOsAutoDetect

- test/image-prepare
- test/run
I started this as preparation for replacing the fedora-testing image with a scenario. That will still need some discussion *where* to run these, similar to where to run the "nightly master" tests. I have an idea, but I'll discuss them in a meeting or on IRC.
In the meantime,  there is enough fodder here to warrant a full CI run. I also trigger the dnf-copr scenario, as this PR touches it.
> image-prepare: various cleanups, add --overlay option

- pkg/storaged/storage.scss
Dialogs no longer have this class since some time ago.
- "intermission" is no longer used anywhere.
- "medskip" is used, but just a bare <div> without any CSS gives the
right spacing now.
- "widest-title" needs to be invisible, so we keep that CSS paragraph
but make it global.
Fixes #15337
> storaged: Don't use modal-body class in CSS

- pkg/networkmanager/app.jsx
- pkg/networkmanager/interfaces.js
- test/verify/check-networkmanager-basic
Previously the page was stuck with a spinner.
Fixes #15245
> networkmanager: show an empty state if NM is not installed

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- test/verify/check-metrics
Show maximum of 5 empty minutes in the current hour. This does not affect missing data in general, only the current hour if cut short. See example: (this is extreme, takes two minutes after full hour)
Before:
Now:
> metrics: Don't show too much empty space for future events

- doc/guide/feature-systemd.xml
- pkg/machines/components/vm/vmActions.jsx
- pkg/shell/indexes.js
- pkg/systemd/overview.jsx
- pkg/systemd/shutdown.jsx
- test/verify/check-pages
- test/verify/check-system-realms
- test/verify/check-system-shutdown-restart
This should make clearer distinction between 'restart' (often used in relation to a service restart) and a 'reboot' (used in relation to a system reboot)
Fixes #15273
> Replace 'restart' with 'reboot' when related to a system reboot

- pkg/systemd/logs.html
Logs was missing a `</div>`
I found this as I had the file opened (for whatever reason) and VS Code bugged me about it. :wink:
> logs: Fix unclosed div as a result of dde47795

- test/common/testlib.py
Sometimes, copy_journal() and friends can cause exceptions themselves,
e.g. due to timing out reading the journal. This previously circumvented
all addCleanup() handlers, which causes all subsequent tests to fail.
Handle runtime exceptions in these artifact generation methods locally
instead, and just print them.
----
This should fix  [this kind of follow-up failures](https://logs.cockpit-project.org/logs/pull-15355-20210217-032549-97d78124-ubuntu-2004/log.html#68) due to improper cleanup.
> test: Run cleanup handlers if debug artifact generation fails

- test/common/run-tests
- test/verify/check-example
- test/verify/check-testlib
This test checks fix introduced in 7a790f2.
Question: I would like to also test retries for changed test files and changed source files. My idea is to change for example `FITNESS FOR A PARTICULAR PURPOSE` string in copyright in one test file (`test/verify/check-example`) and in one source file (maybe users or so) and then check it is retried 3 times. Possibly also testing these retries for tests that fail or tests that don't want these retries. But this involves changing files on the machine that runs tests. Is that a good practice?
> test: Test output from failed tests

- pkg/machines/components/vm/disks/diskAdd.jsx
- test/verify/check-machines-disks
A flake would show up when during a test for adding disks to VM,
it would incorrectly click on "Use existing" mode, resulting in error
"cannot read property of undefined" of undefined.
Also, as part of that, refactor the way mode is chosen during
testAddDiskCustomPath, as the way I programmed it previously was
unintuitive and hard to read.
Fixes following flake:
```
File "/work/bots/make-checkout-workdir/test/verify/check-machines-disks", line 688, in testAddDiskCustomPath
self.VMAddDiskDialog(
File "/work/bots/make-checkout-workdir/test/verify/check-machines-disks", line 254, in execute
self.open()
File "/work/bots/make-checkout-workdir/test/verify/check-machines-disks", line 267, in open
b.click("label:contains(Use existing)")
File …
```
> machines: Refactor VMAddDiskDialog and fix testAddDiskCustomPath flake

- test/verify/check-packagekit
Most recent RHEL 8.4 cloud image does not enable it by default any more.
> test: Enable subscription-manager in dnf in TestUpdatesSubscriptions

- pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
- pkg/machines/components/storagePools/storageVolumeCreate.jsx
- test/verify/check-machines-storage-pools
It's impossible to create a volume when a storage pool is deactived.
But right now, user has to fill out the form only to find this out.
Also when storage pool is deactivated, the "No storage volumes defined
for this storage pool" string is shown in volumes list. That's incorrect.
There are no volumes because libvirt API cannot fetch any information
about volumes for deactivated storage pool. 
Therefore to fix both problems, just hide the storage volumes list if pool
is deactivated and instead show a warning telling to user to activate the
pool
> machines: correct few details in storage page when pool's deactivated

- pkg/lib/cockpit-components-modifications.css
- pkg/lib/cockpit-components-modifications.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/selinux/setroubleshoot.scss
- test/verify/check-selinux
No difference functionally, just looks.
Before:
Now:
> Restyle selinux to fit other pages

- test/verify/check-packagekit
This reverts commit 33d1a9bc6f5cf046a159466fd36ef52607480421.
This was really the wrong thing to do. Ideally rhsm would revert the
recent change that broke the default subscription-manager.conf, but if
that really has to stay, then our page needs another approach of
figuring out whether subscriptions are really required.
> Revert "test: Enable subscription-manager in dnf in TestUpdatesSubscriptions

- pkg/machines/components/common/machinesConnectionSelector.jsx
- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/machines/components/vm/disks/diskEdit.jsx
hasNoPaddingTop is needed on FormGroups when these contain many inline
checkboxes or radios.
Remove redundant 'isInline' from FormGroup with only one child.
> machines: fix some alignment issues with checkboxes

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- test/verify/check-metrics
> metrics: Don't show swap column when no is being used

- test/verify/check-packagekit
This is blocked still, but I mostly want to ensure that tracer works as expected on RHEL 8.4, so that we don't ship something broken.
> Test tracer on rhel-8-4

- tools/webpack-make
The condition cleanup in commit d4ea3eacb719 was wrong: the previous
test only covers *.html files, but we don't want to install the unit
test *.js and *.css files either. Revert that part.
Spotted by rpmdiff.
Fixes #15376
> tools: Stop shipping unit tests

- Makefile.am
- configure.ac
- pkg/networkmanager/manifest.json.in
- tools/debian/rules
This is not being used any more since commit 168f819ebd0.
> build: Drop --with-networkmanager-needs-root configure option

- test/make_dist.py
Common workflow is to fix tests in existing PR. One would adjust tests
and then prepare machine to validate these changes. But due to changes
in tests the downloading would be unnecessary skipped.
> make_dist: Changes in tests are not reason to skip download

- test/common/testlib.py
- test/verify/check-shell-active-pages
With full chromium instead of chromium-headless, the `focus(".terminal")`
focused *away from* the actual element that receives the input, so that
typing the sleep command went into Nirvana. Just drop that, it's
unnecessary -- we want the Terminal page to automatically focus the
input. (check-system-terminal also does not focus explicitly).
Drop the weird `line_text()` helper, and wait until the terminal shows a
full prompt (with '`$`), instead of just "anything". This does the same
as check-system-terminal (albeit a bit simplified).
Wait for the default selection of the "delete frame" dialog to happen.
Previously the clickery started too early before the dialog got fully
initialized, and then missed to actually stop the terminal frame.
Fix the waiting for "sleep command goes away"; before …
> test: Fix TestActivePages races and bugs

- Makefile.am
- configure.ac
- pkg/shell/manifest.json.in
There is little reason to do that. On any sensible system these programs
belong into `$PATH`, and as we don't build-depend on pkexec nor sudo,
the shipped manifests will always have /usr/bin/{sudo,pkexec} anyway.
This gets rid of one part of dynamic manifests, and thus makes them
more portable (~/.local/share/cockpit) and easier to generate by webpack.
Fixes #14347
-----
This is the easiest part of our attempt to not have to deal with *.manifest.in and having to invoke configure and make to build them. It'd be a lot nicer for manifests to be part of static dist and the release tarballs.
> shell: Drop pkexec/sudo path hardcoding into manifest

- Makefile.am
- configure.ac
- pkg/storaged/client.js
- pkg/storaged/manifest.json.in
This was fixed in storaged 5 years ago, and all supported OSes have a
newer udisks version. This configure flag has not been actually used in
our spec/debian files for a long time.
> storaged: Drop obsolete --with-storaged-iscsi-sessions

- Makefile.am
- configure.ac
- pkg/storaged/manifest.json.in
- pkg/storaged/utils.js
- test/verify/check-storage-vdo
- tools/cockpit.spec
- tools/debian/rules
This gets rid of one part of dynamic manifests, and thus makes them more
portable (~/.local/share/cockpit) and easier to generate by webpack. It
also avoids an "unbreak my build" configure argument for CentOS/RHEL.
The manifest is a much more "quirkable" text file which can be handled
through overrides by admins who know what they are doing.
> storaged: Replace --with-vdo-package and --with-nfs-client-package configure option with manifest maps

- tools/cockpituous-release
bodhi activation for Fedora 34 is today [1]. Drop Fedora 32 instead,
which is soon EOL.
[1] https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html
> cockpituous: bodhi for Fedora 34, drop Fedora 32

- pkg/lib/packagekit.js
The `enabled=` option in subscription-manager.conf is not a reliable
indicator whether the installed system needs any subscriptions. On at
least the qcow image, the dnf plugins (both subscription-manager and
product-id) are disabled by default, and the first invocation of
subscription-manager auto-enables them.
Instead, ask RHSM if there are any installed Red Hat products on the
system. That list is empty on Fedora/CentOS. As before, if RHSM itself
is absent, quietly consider this as "system does not need subscription".
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1931429
> lib: Check installed Red Hat products instead of yum config file

- pkg/lib/sassc-loader.js
Revert the sassc-loader.js part of commit 13376b031b and always have
sassc build a source map. The actual .map file is written by later
stages in the pipeline (mini-css-extract-plugin), so this does not
add back the map files into dist/ in production mode.
Parse the processed scss file's included files from the source map and
declare them as dependencies. This fixes both `webpack-watch` and `make`
to properly rebuild a webpack if any included file from a .scss file
gets changed.
Fixes #15398
> lib: Add included file dependencies in sassc-loader

- test/common/run-tests
Commit a0c8d08f10 changed the retry_reason printing to happen after
flushing stdout. This kept it stuck in Python's IOStream buffer until
more output (from the next few tests) was printed, and thus eventually
put the marker onto the wrong test.
Fix this by flushing after the retry reason in the `!print_tap` case.
With `print_tap`, the flushing happens at the end of the function, and
it is ok and desirable to buffer the entire output and flush it out just
once.
Fixes #15414
> test: Fix retry reason printing in run-tests

- test/verify/check-system-journal
systemd-journald is socket activated in recent RHEL 8/Fedora. Stop these
units as well, to prevent a race condition where some background
activity immediately starts journald again while the cleaning is still
in progress.
> test: Fix race condition in TestJournal

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
If the processor (for example) is loaded to around 80% all the time and just
fluxes one or two % up and down it is interpreted as event every minute.
Lets consider the rise over 80% to be at least somewhat significant.
I was working on this page while my CPU was busy and noticed I had waaay to many events, even though the graphs looked pretty stable. Loaded machine !== something bad is happening. Better ideas are welcomed. I was thinking about taking average from all points and then checking if the 80% mark is not close to average or so, but I though to start with something simple and see what others think.
Before:
After:
> metrics: Going over 80% does not mean necessary event

- Makefile.am
- configure.ac
- pkg/apps/application-list.jsx
- pkg/apps/manifest.json.in
- test/verify/check-apps
- tools/cockpit.spec
- tools/debian/rules
This gets rid of the remaining piece of manifests which depend on
./configure options. This gets us closer to making them fully portable
and buildable by webpack.
This uses the same approach as the storage page in commits
0b14a00754cd4 and 9e6a715adca: Put a per-distro map into the manifest,
which is easy enough to tweak/override by admins, and patch by
distributors.
The previous `--with-vdo-package`, `--with-nfs-client-package`, `--with-appstream-config-packages`, and `--with-appstream-data-packages` options for `./configure` got removed. This information is now contained in the respective manifest files, for example for the [Storage page](https://github.com/cockpit-project/cockpit/blob/master/pkg/storaged/manifest.json.in). This makes the manifest files portable across distributions. …
> apps: Replace --with-appstream* configure options with manifest map

- pkg/static/login.js
cockpit-ws support for `/cockpit+` URLs got introduced in version 120
(October 2016). Our master branch has not supported such old OSes for a
long time, so drop the backwards compat code for remote servers which
don't support remote logins.
This gets rid of a place that parses base1's manifest version.
> login: Drop compat code for version < 120

- src/bridge/cockpitpackages.c
- src/bridge/cockpitrouter.c
- src/bridge/test-router.c
- src/common/cockpitjson.c
- src/common/cockpitjson.h
- src/common/cockpittemplate.c
- src/common/cockpittemplate.h
- src/common/cockpitwebresponse.c
- src/common/test-json.c
- src/common/test-template.c
This replaces the custom code for managing the argv/envp and variable expansions inside of them with a generic transform performed at the JSON level.  This already makes the code much easier to understand (since everything we do is eventually turned back into a JsonObject again anyway) and sets the stage for adding a second level of variable expansion without things getting wildly out of hand.
> Clean up variable expansion in the router

- test/verify/check-selinux
Stop assuming a particular order of the SETroubleshooter solutions. They
changed in recent Fedora 33.
----
Fixes [this failure](https://logs.cockpit-project.org/logs/pull-1719-20210225-082448-28f06b5e-fedora-33-cockpit-project-cockpit/log.html#163-2) in the [fedora-33 refresh](https://github.com/cockpit-project/bots/pull/1719).
> test: Relax setroubleshoot ordering assumptions

- test/common/run-tests
Commit 2db63f19efd4f57 regressed run-tests for non-cockpit projects:
```
fatal: ambiguous argument 'pkg/': unknown revision or path not in the working tree.
[...]
File "starter-kit/test/common/run-tests", line 240, in <listcomp>
changed_tests.extend([test for test in test_files if any(pkg in test for pkg in changed_pkgs)])
NameError: free variable 'changed_pkgs' referenced before assignment in enclosing scope
```
Fix this by explicitly telling git that `pkg/` is a path, by prefixing
it with `--`. Also, move the `changed_tests` extension into the right
scope, in case the git command still fails.
> test: Fix run-tests changed_pkgs crash for non-cockpit projects

- pkg/machines/components/vm/disks/diskAdd.jsx
- pkg/machines/components/vm/disks/diskEdit.jsx
- pkg/machines/helpers.js
- pkg/machines/libvirt-dbus.js
- pkg/machines/libvirt-xml-update.js
- test/verify/check-machines-disks
Cache is a disk property which says if and how is I/O cached.
It is already exposed when adding a disk. It can be edited only
for a shutoff VM.
The motivation to implement this was https://github.com/cockpit-project/cockpit/pull/15407 , where migration could be considered unsafe and end up with an error `Migration may lead to data corruption if disks use cache other than none or directsync`. So it's good to allow user to change cache in order to fix the error.
> machines: Expose editing disk cache mode

- HACKING.md
GTestDBus [1], which we use in test-server, requires dbus-daemon and
can't work with dbus-broker. Document it as required dependency to run
the browser based unit tests.
[1] https://developer.gnome.org/gio/stable/GTestDBus.html
Fixes #14409
> HACKING.md: Document dbus-daemon as required unit test dependency

- pkg/apps/manifest.json.in
- pkg/base1/manifest.json.in
- pkg/base1/test-http.js
- pkg/kdump/manifest.json.in
- pkg/machines/manifest.json.in
- pkg/metrics/manifest.json.in
- pkg/networkmanager/manifest.json.in
- pkg/packagekit/manifest.json.in
- pkg/playground/manifest.json.in
- pkg/selinux/manifest.json.in
- pkg/shell/manifest.json.in
- pkg/sosreport/manifest.json.in
- pkg/ssh/manifest.json.in
- pkg/storaged/manifest.json.in
- pkg/systemd/manifest.json.in
- pkg/tuned/manifest.json.in
- pkg/users/manifest.json.in
This field was introduced in #4964 as "purely informational for now",
and isn't even parsed by cockpit.  Meanwhile, it's one of the few things
preventing us from untangling our webpack build from autotools.
Even within cockpit, usage is inconsistent: most packages set "version"
to the string that @Version@ expands to, but machines had it set to the
integer 0, and pcp and static had no "version" field at all.
It seems nobody is going to miss this.  Just drop it.
The one place which did reference this was a test which directly read
the manifest.json.in file from the playground and does a direct
comparison on it.  That's been adjusted accordingly now.
> pkg: drop "version" from manifests

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
These are often things like snaps or mounted ISO images, and are
usually 100% used. Hide them from the "Disks" card, as that is not an
alerting condition, and they take attention away from the "real" disks.
Fixes #15434
-----
This is similar to issue #2454, but on the metrics page. I'll send a PR for the storage page as well once this is in.
> metrics: Hide read-only loop mounts

- test/verify/check-machines-settings
- test/verify/machineslib.py
The kebab actions with disabled elements are rendered like this
(simplified):
<li role="menuitem" id="vm-subVmTest1-clone">
<a aria-disabled="true" class="pf-m-disabled pf-c-dropdown__menu-item">Clone</a>
</li>
Thus clicking on the -clone ID directly happily clicked into the void
even if the contained `<a>` link was still disabled.
This fixes at least `TestMachinesLifecycle.testBasic` and possibly other
flakes as well.
Fixes #15441
> test: Fix VMVirtualMachinesCaseHelpers.performAction() for disabled elements

- Makefile.am
We have some custom rules in `make uninstall` to deal with removing the
installed files from dist/, including a separate rule for map files.
We don't always install map files anymore, and due to the changes in
96027bf8, don't even create the directory in that case.
This doesn't play nicely with our uninstall rule which assumes that the
directory will definitely exist.  Add a check.
Add a check also to the equivalent rule for the normal installation
files: this makes `make uninstall` nicely idempotent.
> build: fix `make uninstall` if no debug is present

- pkg/lib/cockpit-components-dialog.css
- pkg/lib/cockpit-components-dialog.jsx
- pkg/lib/cockpit-components-listing-panel.scss
- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/packagekit/updates.jsx
- pkg/shell/nav.jsx
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/format-dialog.jsx
- pkg/storaged/iscsi-panel.jsx
- pkg/storaged/jobs-panel.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/nfs-panel.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/storage-controls.jsx
- pkg/storaged/storage.scss
- pkg/storaged/things-panel.jsx
- pkg/storaged/vgroup-details.jsx
- test/verify/check-kdump
- test/verify/check-storage-basic
- test/verify/check-storage-format
- test/verify/check-storage-luks
- test/verify/check-storage-nfs
- test/verify/check-storage-unused
- test/verify/check-storage-vdo
- test/verify/storagelib.py
This commit:
* replaces icons with components from react-icons, also makes sure these
are accessible
* replaces custom lists with DataLists component
* replaces all dialog fields like TextInputs, Checkboxes, Radio buttons with PF4
components
* replaces custom dropdowns with Dropdown component
Todo:
> storage: use only PF4 components and stop including PF3 stylesheets

- test/verify/check-system-s4u-ssh
> test: Add kerberized sudo to s4u proof of concept

- test/common/testlib.py
- test/verify/check-shell-host-switching
- test/verify/check-users
These two tests do logout() quickly after logging in. This often causes
the asynchronously loading preloads to load too late, running into
"ReferenceError: cockpit is not defined.
Avoid that by disabling the preloads in these tests, they are not
relevant for them.
----
Seen in https://logs.cockpit-project.org/logs/pull-15443-20210302-062758-9525688c-fedora-32-firefox/log.html in PR #15443
> tests: Avoid "ReferenceError: cockpit is not defined" failures

- tools/cockpit.spec
It is more efficient to do callout just once.
Also, call the scriptlets for all units. For some units the scriptlets
are noops, but it's more future-proof to call them anyway.
Taken from downstream commit:
https://src.fedoraproject.org/rpms/cockpit/c/367f83ef
> tools: Coalesce systemd scriptlets

- pkg/shell/machines/machines.js
It used to be emitted after the very first call to "refresh", which
would usually be the one that has all the data, but sometimes the
first call only has the overlays for localhost, or similar, and then
navigation would be done too soon.
The effect would be that Cockpit would not connect to the remote
machine immediately after log in, when there is a remote machine in
the initial URL, like "https://foo.org:9090/@bar.foo.org"
Now the Loader will explicitly trigger the "ready" signal when it has
done it's initial loading.
> shell: Emit "ready" signal for machines at the right time

- test/verify/check-system-s4u-ssh
According to the man pages (`man pam_sss_gss`), this depends on the sudo
version. It works in fedora-33 without the extra configuration of
env_keep at least.
> test: Kerberized sudo might not need KRB5CCNAME in env_keep

- test/verify/check-metrics
The `VAR=hugestring` shell approach is rather brittle: bash seems to have
some kind of optimization or garbage collection that cleans up the
memory soon after allocation. In Fedora 34 this is so fast that it
breaks the test, but it eventually happens in other distros as well.
Also, the actual memory usage wiggles wildly between 600 and 0 MB for an
allocation of 200 MB.
Replace this with awk, which can also build arbitrarily long strings
(and thus memory usage). This is much faster, much more precise/stable,
and still works everywhere including Fedora CoreOS (which has neither
Python nor Perl).
> test: More robust memory hog

- pkg/lib/cockpit-components-terminal.jsx
- pkg/systemd/terminal.jsx
- pkg/systemd/terminal.scss
- test/verify/check-system-terminal
Fixes #11261
Release note:
Terminal: Add option to choose font size
Users can change font size in terminal that fits their preferences.
> Terminal: Add option to select font size

- tools/release-guide
This script only ever gets called on the cockpit-project.github.io
repository, and the default branch there is called 'main' now, so change
the script accordingly.
> release-guide: update to push to main branch

- test/common/run-tests
When testing stable branch, we don't want to compare against `master` as
the diff is not interesting for us. We want to compare against stable
branch head instead.
Together with https://github.com/cockpit-project/bots/pull/1744:
If I would run command that ^ generated for https://github.com/cockpit-project/cockpit/pull/15463 and then checked `changed_tests` variable, it would be an empty array. If I would then remove `BASE_BRANCH=rhel-8.4` from this command it would produce:
```
['test/verify/check-shell-multi-machine', 'test/verify/check-machines-snapshots', 'test/verify/check-networkmanager-unmanaged', 'test/verify/check-shell-host-switching', 'test/verify/check-machines-lifecycle', 'test/verify/check-networkmanager-checkpoints', 'test/verify/check-networkmanager-mtu', …
```
> run-tests: Compare changed tests/files against base branch

- pkg/base1/cockpit.js
- pkg/base1/test-file.js
- pkg/users/account-details.js
- test/verify/check-pages
Split out from #15350, and I fixed watching binary files.
> Fix cockpit.file.watch() for binary files, fix watching of /run/utmp on users page

- pkg/shell/base_index.js
The "source" variable might be undefined at this point in the code
when the window is closing.
> shell: Don't access undefined "source"

- src/ws/cockpitwsinstancecert.c
- test/common/testlib.py
- test/verify/check-reauthorize
- test/verify/check-shell-keys
- test/verify/check-static-login
- test/verify/check-superuser
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-users-roles
service stdout/err output appear as journal priority "info" (6) instead
of "notice". This rendered a large portion of our
allow_journal_messages() inert (and explains why commit cf82ab8b132
"worked"), and more importantly, does not spot glib warnings that we
really want to see, such as in issue #14704 or #14896.
Allow cockpit-session's "last failed login" messages for every test for
now, they don't indicate a failure or unexpected condition in most cases
-- a lot of tests check logins which are supposed to fail.
Bring back a cleaner variant of commit cf82ab8b132 with a more specific
name `allow_failed_sudo_journal_messages()`, and use it in the tests
which explicitly test becoming administrator with unprivileged users.
Add specific expected messages to the remaining tests which produce …
> test: Check for unexpected info level journal messages

- .github/workflows/publish-dist.yml
- test/make_dist.py
From there they can be downloaded without a GitHub token, and thus
become accessible to packit and other CI systems. Do this in a new
publish-dist workflow, as build-dist has no access to secrets and we
need our GitHub token for this.
As git's tarball names are not predictable, wrap them into a
`<sha>.tar` similar to the GitHub artifact.
Adjust make_dist.py to download the dist tarball from the -dist GitHub
repo. This gets rid of the bots API and token requirement.
----
This  is preparation for [running PackIt tests in upstream PRs](https://github.com/martinpitt/cockpit/pull/12). As this introduces a new `on_workflow:` workflow, this needs to be on master before it will actually run.
> workflows: Upload built dist tarballs to -dist repository

- test/common/testlib.py
And if it fails to find axe, write it to stderr and not to stdout.
> test: Don't try to use axe on Firefox

- pkg/systemd/logs.js
- test/verify/check-system-journal
The current approach had a bunch of issues:
- It was doing `sh -ec` instead of using `cockpit.script()`
- It was using `then()` and `done()` at the same time
- It would never fail (due to those `grep` and `sort`)
- It was doing grep which is ugly
- The `sort` was not necessary as we sort it anyway
- The `host` option was unused
But mainly it was not error prone since we introduced possible spaces in
qualifiers. We could now have `journalctl --since="2021-03-03 08:00"`
which would be then parsed in command as `["journalctl", "since=2021-03-03 08:00"]`.
That is fine because separate arguments are treated as such, but when
we did `join(" ")` it would generate `journalctl --since=2021-03-03 08:00` where `08:00`
would not be recognized anymore. This lead to not showing any services
on the logs …
> logs: Fixup services loading

- pkg/lib/cockpit-components-logs-panel.jsx
- pkg/lib/journal.css
- pkg/lib/page.scss
- pkg/storaged/devices.jsx
- test/verify/check-system-journal
The badges look different in bootstrap compared to PF4. Are we happy with the change?
Before:
After:
> lib: make cockpit-logs-panels independent from PF3

- pkg/machines/components/vm/disks/diskAdd.jsx
This was resulting on console warnings:
Warning: An update (setState, replaceState, or forceUpdate) was scheduled from inside an update function
> machines: fix wrong usage of nested setState calls

- pkg/lib/cockpit-components-modifications.css
- pkg/lib/cockpit-components-modifications.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/selinux/setroubleshoot.js
- pkg/selinux/setroubleshoot.scss
- test/verify/check-selinux
This commit made the following changes:
* Replace icons with the React components from react-icons
* Replace `<pre>` with <TextArea>.` <pre> `in PF4 does not have a grey
background
* Replace custom expandable section with ExpandableSection PF4
component
* Replace list-group and list-group-items which are used for displaying
solutions with Cards
> selinux: remove last usages of PF3 and stop including it

- test/common/run-tests
This will allow cockpit-composer to use bigger global machines, so that
all of its tests can go back to being nondestructive (and thus once
again run in Fedora/RHEL gating). See
https://github.com/osbuild/cockpit-composer/commit/a7577b988c1fd3
(which was a quick hack to unbreak the tests)
> test: Add nondestructive VM CPU/RAM size options to run-tests

- test/common/run-tests
This is the last place in run-tests that uses print() without flushing.
As the output is heavily interleaved with stderr and direct
sys.stdout.buffer writes, unflushed print()s mess up the log file.
----
This may help with a mess like [this](https://logs.cockpit-project.org/logs/pull-1262-20210312-060925-9dd70cbb-fedora-33-firefox/log.html). The main fix for that should be https://github.com/cockpit-project/bots/pull/1787 but I think it can't hurt being thorough here.
> test: Flush stdout after printing result

- test/common/testlib.py
This has been a game of whack-a-rat, and there's still new messages
appearing, like "sudo: no valid sudoers sources found, quitting".
But this is non-sense: Simplifiy the function to allow *all* messages
from sudo; that's what we are effectively trying to do, and we only use
it in tests where we expect sudo to fail.
> test: Generalize allow_failed_sudo_journal_messages()

- .github/workflows/publish-dist.yml
When multiple parallel workflows race against each other, the final
`git push` may fail if origin/master has moved while trying to update it
locally. In that case, do the entire update construction again, as in
the meantime older tarballs may also have been cleaned up already.
> workflows: Retry dist git commit several times

- src/ws/remotectl-certificate.c
- src/ws/test-remotectlcertificate.c
- test/verify/check-connection
If the certificate already exists, and ownership and permissions are
already as expected, then don't call chmod()/chown(). This avoids
failing on a read-only /etc/ once the certificate is set up.
https://bugs.debian.org/983514
> ws: Fix remotectl --ensure for read-only /etc

- packit.yaml
- test/run-verify-host-user.sh
- test/run-verify-host.sh
- test/verify/check-system-services
This was developed against my fork in https://github.com/martinpitt/cockpit/pull/13, with lots of intermediate/failing results (which justify the commits here).
> Fix FMF tests for Fedora 34, enable in packit

- pkg/lib/patternfly/patternfly-4-overrides.scss
This is being tracked upstream at:
https://github.com/patternfly/patternfly/issues/3926
> pf4: Add override to draw input group focus ring above other elements

- pkg/machines/components/vm/disks/diskAdd.jsx
Remove isInline from the "Persistence" group. This only makes sense to
use when more than one items are part of the group.
> machines: fix alignment of radio buttons in 'add disk' dialog

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/machines/libvirt-common.js
- pkg/machines/scripts/create_machine.sh
- test/verify/check-machines-create
- test/verify/check-machines-disks
- test/verify/check-machines-lifecycle
- test/verify/check-machines-settings
- test/verify/check-machines-storage-pools
- test/verify/machineslib.py
- test/verify/machinesxmls.py
Distro cloud images have locked login accounts by default. The user can now specify the root and user account login credentials when creating VMs based on cloud images. The cloud image itself will be used as the backing store for the VM's disk.
> machines: add support for passing cloud-init metadata when creating VMs with cloud images

- pkg/systemd/README-realmd.md
- test/verify/check-packagekit
- test/verify/check-system-realms
- test/verify/check-system-s4u-ssh
https://github.com/cockpit-project/bots/pull/1768 moves the services
image from CentOS 7 to Fedora CoreOS and containerizes the candlepin
server. Adjust tests accordingly.
> test: Adjust for changed services image

- test/README.md
- test/common/testlib.py
- test/run-verify-host-user.sh
- test/verify.fmf
- test/verify/check-system-services
In the European evenings/American mornings, the tests on Testing Farm
are really slow (supposedly, AWS spot instances with lots of noisy
neighbors?), have a hard time finishing in two hours, and lots of tests
fail because expensive actions (such as loading the Services page or the
Terminal torture test) actually take more than one minute.
Introduce a `$TEST_TIMEOUT_FACTOR` environment variable to globally
scale the timeouts, use it for FMF tests on Fedora, and bump the global
plan timeout to four hours.
[example from yesterday evening](http://artifacts.dev.testing-farm.io/b0212fd2-d876-457f-bdfd-d0cfded5b77a/)
> fmf: Increase plan timeout and duration for Fedora

- pkg/realmd/README.md
- test/verify/check-packagekit
- test/verify/check-realms
- test/verify/check-subscriptions
https://github.com/cockpit-project/bots/pull/1768 moves the services
image from CentOS 7 to Fedora CoreOS and containerizes the candlepin
server. Adjust tests accordingly.
Cherry-picked from master commit d2c9f0c269ac29612
Changes:
- Completely sync over pkg/realmd/README.md from current master, as the
information here was heavily out of date (e.g. the "ipa" image has
not existed for some time).
- Replace the JSON filtering in Python with `jq`, as there is no Python
on Fedora CoreOS.
> [r79] test: Adjust for changed services image

- src/ws/cockpitwebservice.c
Commit 20c24824fb forgot to free the allocation.
Spotted by `make check-memory TESTS=test-handlers` on current Fedora 33.
> ws: Fix CockpitWebService.id leak

- test/make_dist.py
Prefer an existing local build/webpack, to make sure that local
developer settings are applied.
> test/make_dist: Don't download if ./dist/ already exists

- .github/workflows/npm-update.yml
This is what we used to do when we still used npm-trigger. Some modules
like react-console are updated very often, and validating these
becomes too expensive/annoying.
> workflows: Run npm-update twice a week only

- pkg/systemd/README-realmd.md
- test/verify/check-packagekit
- test/verify/check-system-realms
- test/verify/check-system-s4u-ssh
https://github.com/cockpit-project/bots/pull/1768 moves the services
image from CentOS 7 to Fedora CoreOS and containerizes the candlepin
server. Adjust tests accordingly.
Cherry-picked from master commit d2c9f0c269ac296.
> [r84] test: Adjust for changed services image

- .github/workflows/prune-dist.yml
This avoids unbounded growth of the -dist repository. This force-pushes,
so is prone to race with parallel publish-dist jobs. So run this at
Sunday night, where the probability of human PRs is very low; no other
workflows run at this time either.
-----
I tested this on my fork. Before:
```
$ git clone https://github.com/martinpitt/cockpit-dist c
$ du -hs c/.git; du -hs c
314M	c/.git
562M	c
```
Then in [ran the workflow](https://github.com/martinpitt/cockpit/actions/runs/675122930), and now it [shows the truncated history](https://github.com/martinpitt/cockpit-dist/commits/master) and is smaller:
```
$ git clone https://github.com/martinpitt/cockpit-dist c2
$ du -hs c2/.git; du -hs c2
281M	c2/.git
529M	c2
```
I expect that the effect will be a lot more dramatic on the real cockpit repo.
> workflows: Regularly prune -dist repository

- tools/webpack-make
Commit b82b22abef679 caused webpack-watch to always delete
manifest.json, which broke efficient local development pretty hard.
Leave the manifest.json alone, they actually *are* good enough for
building RPMs now, as these are just static file copes. Still keep the
cleanup of Makefile.deps though, until webpack-make gets cleaned up more
thoroughly.
> tools: Don't delete manifest.json in webpack watch mode

- pkg/lib/console.css
The console likes to hardcode its width, causing layouts to break.
Forcing it to 100% makes it render within the boundaries.
Fixes #15472
> lib/console: Force width to containment size

- test/verify/check-testlib
- tools/test-static-code
The regexp changes here broke things, but the breakage was being
temporarily covered up by a separate bug, so they didn't show in the
initial round of tests on the PR.
At the same time, things are very much broken right now, so revert the
changes in check-testlib.
We need to add an exception to the static code checks again until we fix
this properly.
> verify: revert recent changes to check-testlib

- pkg/users/account-details.js
- test/verify/check-users
get_last_login() made the assumption that the date is separated by three
spaces. But that's not the case in reality, as the "From:" column can
become very wide. As there is no reliable column size or separator that
sets apart the date, just take the last five words from the line
instead, which should be the date.
With the previous code, this tried to parse "web cons ::ffff:172.27.0.
Tue Mar..." as a date, which returned an invalid `Date` object. This
confused the `!details.logged.last` check -- it was a proper object (and
thus not falsy), but stringifying it yielded `null`, and thus moment
spat out "Invalid date". Avoid that by explicitly testing whether
getTime() is an actual number -- for invalid dates this will be `NaN`.
This was not caught by the tests because they just asserted that …
> users: Fix lastlog parsing

- test/verify/check-multi-machine
This makes the test stricter, and also makes them work on OSes that
don't set a host name by default (like fedora-coreos). The new Overview
page doesn't render `#system_information_hostname_text` at all without a
host name.
Cherry-picked from master commit 1cfa5787b6be1
----
This should unbreak the rhel-atomic refresh in https://github.com/cockpit-project/bots/pull/1822
> [r79] test: Use predictable host names in check-multi-machine

- tools/webpack-make
Stop removing Makefile.deps in watch mode.  There's no good reason for
it anymore, and it's causing problems.
Also, drop conditionalising the generation of the dependencies on the -m
argument having been passed.  This argument is mandatory.
> webpack-make: drop a "watch mode" special case

- pkg/lib/cockpit-components-plot.jsx
- pkg/networkmanager/network-interface-members.jsx
- pkg/networkmanager/network-interface.jsx
- pkg/networkmanager/network-main.jsx
- pkg/networkmanager/plots.js
- pkg/storaged/drives-panel.jsx
- pkg/storaged/overview.jsx
- pkg/storaged/plot.jsx
- pkg/storaged/side-panel.jsx
Previously when hovering on the resources, we highlighted them in the
relevant part of the screen. This has two main issues:
* The lists can get long so nothing guarantees that the resources of interest
are in the visible part of the screen
* The highlighted section was just changing background color which is
not helping people with limited vision.
This commit replaces this highlighted sections on hover with an inline
tootip that appears when the plot is focused.
Note: title is also read by screen reader software therefore is an accessibility
enhancement from our previous state.
Fixes #4006
> lib: replace onHover custom function in plots with an inline tooltip

- test/common/run-tests
- test/run-verify-host-user.sh
- test/verify/check-testlib
This was inelegant (hardcoding) and often wrong: cockpit has stable
rhel-8.x branches, and cockpit-machines' default branch is "main".  E.g.
a local run-tests invocation in cockpit-machines or other project which
has a "main" instead of a "master" branch previous spat out this error:
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: bad revision 'origin/master'
It is also conceptually dubious: The "retry affected tests" logic is
intended for pull requests, which always have an explicit target branch.
It is not intended for downstream gating (where we previously had a hack
to disable it), nor particularly desirable for local test runs (where …
> test: Drop run-tests --base default branch name

- Makefile.am
There is no tools/npm-update.  It got renamed to npm-install during
reviews, but I missed changing this message.
Update the message accordingly.
> build: fix a message

- src/tls/cockpit-certificate-helper.in
- src/ws/remotectl-certificate.c
This was never being explicitly done, under the assumption that the
certificate file, as created by IPA, would be world-readable by default.
It's not, so let's do it ourselves.
The reason this is working is because remotectl is coming along after
the fact and setting the permissions, incorrectly (under the assumption
that there was also a private key in there), but in a way that would
allow cockpit-tls to load it, at least.
Remove that code from remotectl now as well: we will soon stop running
remotectl in the normal case.
release blocker because: this is a bug that we should fix before the new ipa-certificate-creating script appears in its first release.
> tls: set permissions of 10-ipa.cert on install

- pkg/apps/packagekit.js
- pkg/lib/packagekit.js
progress_reporter (see pkg/apps/packagekit.js) is combining progress
from multiple operations by using the base/range logic.
The only way for this concept to work is to only have this callback get
called when the percentage has changed.
Otherwise, we just keep adding progress without any actual change
happening in the backend.
Example:
method = InstallPackages
base = 1, range: 99
PK backend: Properties changed: { Percentage: 0 }
progress_reporter: data_percentage = 1 + 0 * 100/99 = 1
PK backend: Properties changed: { Percentage: 1 }
progress_reporter: data_percentage = 1 + 1 * 100/99 ~= 2.01
PK backend: Properties changed: { Status: 2 }
progress_reporter: data_percentage = 1 + 2.01 * 100/99 <--- here the
percentage increased but it should not! Percentage property did not change
Fixes …
>  File filter...  lib: packagekit: update progress bars by using the PK backend provided value

- pkg/systemd/page-status.jsx
This removes the unwanted padding added.
Fixes #15591
> overview: buttons in the health card are used inline and should be using the isInline property

- test/common/run-tests
This was prone to unexpected behavior if output would contain any of
these key words.
> tests: Don't try to parse skip and retry reasons from output

- src/bridge/cockpitdbuscache.c
- src/bridge/cockpitdbuscache.h
- src/bridge/cockpitdbusjson.c
This matters when the watch rules are not sufficiently narrow.  For
example, when there is no rule at all, a cache for o.fd.NetworkManager
would react to PropertiesChanged notifications from o.fd.systemd1.
It would cache and distribute values for systemd1 properties (which is
wasteful but mostly harmless), and would ask o.fd.NetworkManager for
values of systemd properties that have been invalidated (which is
clearly wrong).
> bridge: Explicitly filter DBus signals by sender when cache watching

- test/verify/check-kdump
- test/verify/check-machines-create
- test/verify/check-storage-format
- test/verify/check-storage-luks
- test/verify/check-storage-resize
- test/verify/packagelib.py
Use name prefix matching for tests which clearly apply to all
RHEL/CentOS images by design choice (as opposed to "specific bugs").
Invert the feature/bug OS lists in check-machines-create, so that it
captures the old behaviour and go to zero, as opposed to having to be
extended with each new OS (which is error prone).
----
Prerequisite for fixing tests for RHEL 9 (see #15614)
> test: Generalize some OS special cases

- test/common/testlib.py
Appending to the list would modify the class variable, which is shared
between all instances of MachineCase.  Thus the allow_journal_messages
call from one test would still be active in the next test.
> test: Reset allowed_journal_messages between test cases

- src/common/cockpitchannel.c
If a text channel sends some invalid UTF-8 (such as reading utmp before
commit 05ce4d2aeb), cockpit_channel_send() queues (with a timer) a flush_buffer(),
so that the next received block can finish the incomplete glyph. But if
the channel got closed in the meantime, that ran into an already freed
`self`, and trying to access its properties crashed.
Fix that by stopping the timer in flush_buffer() if it is active --
closing the channel flushes the buffer in cockpit_channel_real_close()
anyway, so there is no point trying to write anything else afterwards.
https://bugzilla.redhat.com/show_bug.cgi?id=1943169
> common: Fix crash in channel flush_buffer()

- test/common/testlib.py
- test/verify/check-metrics
This leads to many test failures not being retried, as with that commit
they started to fail twice: First for the real reason, then because of
whichever journal messages caused the failure.
In many cases that happens because tests tend to call
allow_journal_message() at the end, which they never get to if they fail
in the middle. But even if we'd change that, it's still conceptually
wrong -- tests should have one back trace and failure reason only, not
two.
This was introduced for
https://github.com/cockpit-project/bots/issues/1453 , but we don't
actually require that -- the naughty can match on the error that the
browser console writes.
This reverts commit 34ee9ee4036b59df5d04489b75c4587103e3ba49.
----
This fixes brittle tests like [this …
> Revert "testlib: Always output unexpected journal and browser messages"

- pkg/systemd/overview-cards/realmd-operation.js
- src/tls/cockpit-certificate-helper.in
"ipa" turns out to have been a bad verb to use as a subcommand in
cockpit-certificate-helper: we will soon want to also add "ipa cleanup".
Since cockpit-certificate-helper has yet to appear in a release, we can
fix this before we introduce potential compatibility problems.  Do a
quick patch now to expect the arguments "ipa request" in order to make
it easier to add "ipa cleanup" later.
> tls: change "ipa" to "ipa request" in certificate helper

- test/run
Don't let dnf install Recommends on upgrade. We don't want that to
install cockpit's recommendations like c-packagekit, as this will make
the `rpm -e` commands from the *.install script fail.
----
Blocks https://github.com/cockpit-project/bots/pull/1828
> test: Fix dnf-copr upgrade scenario

- test/verify/check-system-journal
Commits c27aa2601338b and 40f8e0df6d40d built an ever-increasing series
of delicate hacks to restore the journal to the original state, but this
again breaks on RHEL 9: it confuses the audit subsystem, which causes
several system service failures (such as hostnamed, homed, and the
systemd@user service) and eventually breaks testSELinuxRestrictedUser.
Revert that hackery, make testBasic() destructive, and fix the other
nondestructive tests to only consider the journal since the test start
time, so that they can still run multiple times on the same running VM.
-----
`TestLogin.testSELinuxRestrictedUser` was the one remaining [failure](https://logs.cockpit-project.org/logs/pull-15614-20210330-051315-637dcdf0-rhel-9-0-bots-1860/log.html#293) from #15614 . I can't reproduce this locally, and I …
> test: Drop journal save/restore hacks in TestJournal

- pkg/users/account-details.js
This parsing has been changed in 299e6f6f51 on 23.3.2021.
Therefore we only tested it on dates with double digit dates which
failed to notice that when date is single digit it does not work correctly.
We split the string on space, which produces:
`Tue Mar 23 14:49:04 +0000 2021` => ["Thu", "Mar", "23", "14:49:04", "+0000", "2021"]
`Thu Apr  1 08:58:51 +0000 2021` => ["Thu", "Apr", "", "1", "08:58:51", "+0000", "2021"]
When we then take last 5 fields in the latter case we don't get month
which breaks subsequent parsing.
> users: Fix lastlog parsing - April the 1st edition

- autogen.sh
Our configure.ac includes AM_GLIB_GNU_GETTEXT, which is pretty
oldschool.  We should definitely move away from that, as per:
https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration
https://wiki.gnome.org/MigratingFromIntltoolToGettext
Until that time, however, add an explicit check for it in ./autogen.sh
to prevent autoreconf from failing with a message about "undefined macro
AM_GLIB_GNU_GETTEXT".
More to the point, though: this has the added side-effect of giving
LGTM/Semmle's deptrace machinery a chance to understand the dependency
and install the correct packages for us.
> autogen: check for glib-gettextize

- test/common/firefox-cdp-driver.js
When Runtime.evaluate() encounters a rejected promise, it fails with
```
"response": {
"message": "Debugger: expected Debugger.Object, got Proxy",
"data": "_returnError@chrome://remote/content/cdp/domains/content/runtime/ExecutionContext.jsm:193:22\nevaluate@chrome://remote/content/cdp/domains/content/runtime/ExecutionContext.jsm:173:23\nsetTimeout handler*ph_wait_cond/<@debugger eval code:242:25\nph_wait_cond@debugger eval code:238:12\n@debugger eval code:1:13\nevaluate@chrome://remote/content/cdp/domains/content/runtime/ExecutionContext.jsm:147:29\nevaluate@chrome://remote/content/cdp/domains/content/Runtime.jsm:279:20\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45\n"
}
```
instead …
> test: Work around Firefox CDP mis-handling promise rejections

- test/verify/check-embed
- test/verify/check-testlib
- test/verify/files/measure-cpu
- test/verify/files/mock-escrow-server
- test/verify/files/mock-insights
- tools/test-static-code
- tools/urls-check
The first one of these is pretty important: the test-static-code script, when run in a directory with nodes_modules/ checked out will try to scan all the python it finds in there, and reject an awful lot of it, which (if you have the git hook setup) will pretty much prevent you from ever pushing anything.
> more pycodestyle fixes

- pkg/systemd/overview-cards/realmd-operation.js
- src/tls/cockpit-certificate-helper.in
- test/verify/check-system-realms
When we were originally creating this file, it was a very direct copy of the shellscript that was being assembled in-place by browser-side javascript code.  It was never meant to be a proper script.
Perform some general cleaning up, as well as splitting some of the code into functions.  Introduce the use of a permissions-restricted working directory (which will be cleaned up on exit).  Step up our automake game a little, and support installations not in /etc.
Finally: remove the +x bit.  It's meaningless on .in files; the script will be set +x on installation.
also:
Dismantle another shell-script-via-javascript instance for cleaning up the certificate and keytab on leaving an IPA domain and move the functionality to cockpit-certificate-helper.
While we're at it, make sure the .key file is …
> tls: tidy up cockpit-certificate-helper, move "cleanup" from javscript

- test/common/testlib.py
The directory sometimes seems to disappear asynchronously, leading to
occasional errors like:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4n4loeh6'
This shouldn't happen, but life is too short to fix all the bugs in it.
> test: Ignore errors when removing self.tmpdir during teardown

- test/common/parent.py
- test/containers/check-bastion
- test/containers/parent.py
- test/containers/run-tests
- tools/parent.py
- tools/test-static-code
- tools/urls-check
We have two classes of of cases where our imports are not at the top of
the file:
- various tricks to manipulate the path before importing other modules
- gi.require_version()
For gi.require_version() we could probably just drop it, but let's leave
it there and add a #NOQA comment.
For the path manipulation, let's up our game a bit.  We avoid this issue
in test/verify/ by symlinking path.py from test/common/.  Do the same
thing for test/container/ and tools/.
Fix a bug in path.py: it uses abspath() instead of realpath() when
determining the value of TEST_DIR, which means that it's not resolving
the symlink.  That's worked up to this point only because path.py has
only ever been linked to from the same depth as its original location in
test/common/.  Linking it from tools/ breaks that …
> pycodestyle: E402 fixups (import at top of file)

- src/bridge/cockpitcgroupsamples.c
- src/bridge/cockpitpcpmetrics.c
- test/common/testlib.py
- test/containers/check-bastion
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-superuser
This adds the "cockpit/ssh" syslog identifier, which is used for
messages written to stderr on remote machines, and adds all the
GLIB_DOMAINS that are used by core Cockpit.
> test: Look at more journal messages

- containers/bastion/Dockerfile
- containers/ws/Dockerfile
Otherwise it pulls from docker.io where we can hit pull rate limit.
> containers: Pull fedora image from registry.fedoraproject.org

- pkg/lib/cockpit-po-plugin.js
- test/verify/check-static-login
The plugin works with webpack v5, but throws a deprecation warning:
> [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets
> will be frozen in future, all modifications are deprecated.
> BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
> Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
> Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
When building with webpack v5, use the more fine-grained `processAssets`
hook, which is meant for adding extra assets. This API is not available
in v4 yet, so until we move all our projects to v5 we have to support
both cases.
> lib: Adjust cockpit-po-plugin for webpack v5

- containers/ws/atomic-install
In commit e87ad98d4 base image was changed which meant that now `$container` is `oci` and not `podman`.
> containers: Use correct $container type

- test/verify/check-connection
Sometimes it looks like this:
cannot reauthorize identity(s): unix-user:admin
Spotted in https://github.com/cockpit-project/bots/pull/1912 where it caused [this random failure](https://logs.cockpit-project.org/logs/pull-1912-20210411-111351-7ebd59aa-ubuntu-stable-cockpit-project-cockpit/log.html#14)
> test: Relax expected messages in TestConnection.testCockpitDesktop

- test/verify.fmf
The release tarballs include the necessary test dependencies already.
> fmf: Don't install npm

- test/verify/check-connection
- test/verify/check-kdump
- test/verify/check-login
- test/verify/check-multi-machine
- test/verify/check-multi-machine-key
- test/verify/check-session
- test/verify/check-system-info
- test/verify/check-terminal
- test/verify/packagelib.py
This was dropped in
https://github.com/cockpit-project/bots/commit/ac9b124ee1a7
Drop cases which were really Atomic specific, and replace most others
with `ostree_image`.
> test: Drop usage of Machine.atomic_image

- src/common/cockpiterror.c
I've just updated to F34 and cannot `make` cockpit due to:
```
In file included from /usr/include/glib-2.0/glib/gthread.h:32,
from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
from /usr/include/glib-2.0/glib.h:32,
from src/common/cockpiterror.h:23,
from src/common/cockpiterror.c:22:
src/common/cockpiterror.c: In function ‘cockpit_error_quark’:
/usr/include/glib-2.0/glib/gatomic.h:117:5: error: argument 2 of ‘__atomic_load’ discards ‘volatile’ qualifier [-Werror=incompatible-pointer-types]
117 |     __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
|     ^~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gthread.h:260:7: note: in expansion of macro ‘g_atomic_pointer_get’
260 |     (!g_atomic_pointer_get (location) &&                             \
|       ^~~~~~~~~~~~~~~~~~~~ …
```
> cockpiterror.c: Use glib macro instead of our own implementation

- pkg/networkmanager/networking.scss
Relevant to: https://bugzilla.redhat.com/show_bug.cgi?id=1946877
This is far from optimal but I was not able to find a way to let it
escape the PF4 dialog.
It needs to be ported to PF4 anyway, which will properly solve the issue.
> network: flip direction of the MAC dropdown in add bond dialog

- test/verify/check-storage-resize
When growing the partition always check the the filesystem keep being
mounted after the operation is ready.
Some debugging notes here:
I noticed in the journal of the failing test, that systemd unmounted the FSYS which makes the footer warning on schrink not show up.
The relevant logs:
```
Mar 30 17:25:32 localhost systemd[1]: Unmounting /run/foo...
Mar 30 17:25:32 localhost systemd[1742]: run-foo.mount: Succeeded.
Mar 30 17:25:32 localhost systemd[1517]: run-foo.mount: Succeeded.
Mar 30 17:25:32 localhost udisksd[1643]: Cleaning up mount point /run/foo (device 253:1 is not mounted)
Mar 30 17:25:32 localhost systemd[1]: run-foo.mount: Succeed
```
Copied from: https://logs.cockpit-project.org/logs/pull-15623-20210330-165121-87cf409c-fedora-33-firefox/TestStorageResize-testResizeLuks-fedora- …
> tests: robustify testResizeLuks

- .gitignore
- src/common/cockpitwebcertificate.c
- src/common/cockpitwebcertificate.h
- src/common/test-webcertificate.c
- src/tls/Makefile-tls.am
- src/tls/certificate.c
- src/tls/certificate.h
- src/tls/cockpit-certificate-ensure.c
- src/tls/cockpit-certificate-helper.in
- src/tls/main.c
- src/tls/utils.h
- src/ws/cockpit.service.in
- src/ws/cockpitcertificate.c
- tools/cockpit.spec
- tools/debian/cockpit-ws.install
This tool is a very small C program which does the following two things:
- uses the recently-split-out certificate handling support from cockpit-tls to check that a certificate is installed (and in the case of a self-signed certificate, not close to expiry)
- if not, uses the recently-added "selfsign" subcommand in cockpit-certificate-helper to create a new self-signed certificate
Even though we are the only user, we add a utility function to certificate.c to get the expiry of a certificate, because it's a better fit there.
Stop calling remotectl and use cockpit-certificate-ensure, instead.
> tls: add new cockpit-certificate-ensure tool, and use it

- pkg/networkmanager/network-interface.jsx
- test/verify/check-networkmanager-basic
Commit 5c7b284a082 broke the "connect device" button. Fix the initial
condition in connect() to what we had before that commit: we can connect
if there is either a MainConnection that we can activate, or a device
with ghost settings. (Thanks to Marius Vollmer for this).
Also fix the modify call, `self.dev` is not a thing.
https://bugzilla.redhat.com/show_bug.cgi?id=1946874
> networkmanager: Fix device connection button

- doc/guide/cockpit-file.xml
- pkg/base1/cockpit.js
- pkg/base1/test-file.js
This is useful when watching large files or non-readable devices, i.e.
when the caller is only interested in the actual change notification.
Add a `read` option to watch(), which can be set to `false` to disable
reading. If not present, keep the original default to not break
backwards compatibility.
Fixes #14188
> base1: Add option to disable file reading for cockpit.file().watch()

- src/tls/test-server.c
- src/ws/test-auth.c
RHEL's Coverity scanner got fixed to get along with glib ref counting, so the scan results are down to just two unit test issues. These are both false positives, but let's address them to have a clean slate.
https://bugzilla.redhat.com/show_bug.cgi?id=1938693
> Two coverity fixes

- pkg/systemd/overview.jsx
- pkg/systemd/overview.scss
- pkg/systemd/system-global.scss
> overview: remove some custom styling from our superuser alert 

- test/verify/check-system-info
- test/verify/files/mock-insights
Latest insights-client dropped the `insecure_connection` option and only
accepts TLS. Change mock-insights to serve TLS, and re-use our "alice"
certificate for it.
Disable certificate verification, as apparently there is no way to
convince the later stages of insights-client to accept a locally added
CA.
> test: Enable TLS for mock insights server

- pkg/static/login.js
As we're using `"".replaceAll()` in Cockpit already, we should have a check for it.
This bumps up our minimum supported browser versions to mid-2020.
> login: Add check for String.prototype.replaceAll

- containers/ws/README.md
- doc/guide/feature-sosreport.xml
- test/verify/check-connection
- test/verify/check-static-login
Fedora/RHEL Atomic are both end-of-life, so clean up the ws container
and guide documentation.
Adjust some test comments to say "OSTree" instead.
> Drop obsolete "Atomic" references

- .babelrc.json
Commit fc73c07195c3 added a check for String.replaceAll(), update to the
browsers which support that. These correspond to our website:
https://github.com/cockpit-project/cockpit-project.github.io/commit/ea70505944
> babelrc: Bump supported browser versions

- test/verify/check-system-info
- test/verify/files/mock-insights
Latest insights-client dropped the `insecure_connection` option and only
accepts TLS. Change mock-insights to serve TLS, and re-use our "alice"
certificate for it.
Disable certificate verification, as apparently there is no way to
convince the later stages of insights-client to accept a locally added
CA.
Cherry-picked from master commit 12850afd8667.
> [r84] test: Enable TLS for mock insights server

- test/verify/check-system-info
The comment still refered to an earlier version of PR #15698 which
actually added ca.pem to the system trust store and generate a new
"insights.pem" certificate from that. The simpler version that finally
landed forgot to clean up the comment.
> test: Fix comment for mock-insights setup

- pkg/lib/cockpit-components-dialog.jsx
* onClick on buttons is fired only with the primary key anyway - no need
for extra check
* modal-in class is not used
> lib: Remove some unneeded code from cockpit-component-dialog

- pkg/lib/polyfills.js
- pkg/static/login.js
Our most recent browser version bump in commit 1c8084d7e7a05c4 now
ensures that all our supported browsers have `Promise.finally()`:
https://caniuse.com/?search=Promise.prototype.finally
Drop our polyfill and add a corresponding check to the login page.
Fixes #12151
> lib: Drop Promise.finally polyfill

- test/verify/check-packagekit
subscription-manager uses systemd now. This avoids a hanging unit start
when systemd tries to D-Bus activate it.
---
This happened in the downstream RHEL 8.5 gating tests. I hacked around it in the STI scripts there.
> test: Disable rhsm.service through systemd

- test/verify/check-subscriptions
The POOL_COMMAND on recent candlepin versions now finds two pools with
almost exactly the same properties. Ensure that we only pick the first
matching one, to avoid building a broken multi-line command.
> test: Select first pool from candlepin

- test/common/testlib.py
- test/verify/check-session
- test/verify/check-shell-host-switching
Examples: [one](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-15680-20210419-065427-0bb1666b-fedora-33/log.html#87), [two](https://logs.cockpit-project.org/logs/pull-15679-20210412-093836-32d61aac-ubuntu-stable/log.html), [three](https://logs.cockpit-project.org/logs/pull-15698-20210415-161600-83597863-rhel-8-5/log.html), and it's on our weather report.
> Fix unstable TestHostSwitching.testNoAutoconnect , clean up unexpected messages a bit

- .github/workflows/publish-dist.yml
The repository gets too big with 7 days of builds, and makes prune-dist
fail due to too big pushes.
> workflows: Reduce published dist tarball retention to 3 days

- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
Previously when the user would have had arbitary minutes already set up,
we would set supported=false and hide the autoupdates card from the UI.
Fixes #15712
> packagekit: Accept arbitary minutes in the OnCalendar unit property validator

- pkg/lib/cockpit-components-terminal.jsx
- pkg/systemd/terminal.jsx
Note: The patternfly import needs to be done before the react-core imports,
otherwise it resets the styles. (resulting is false modal background)
Fixes #12939
The alert modal looks like this:
> terminal: show an alert if navigator.clipboard.readText API is not supported

- Makefile.am
Move the custom dist-hook bits into `if ENABLE_DOC`, as these files
don't exist with `--disable-doc`.
Fixes #15710
> build: Fix `make install` failure with --disable-doc

- pkg/lib/patternfly/patternfly-4-overrides.scss
Fixes #15639
PF4 uses H4 for titles. However, H4 is often set with different font family and
size in other frameworks; notably, but not limited to PatternFly 3.
> lib/pf4: Use alert font style for alert titles

- src/ws/cockpit-desktop.in
Fixes #13700
---
Our integration tests don't/can't cover this, this needs to be tested manually. I did that on a clean Fedora 33 live system, with `/usr/libexec/cockpit-desktop /` and `/usr/libexec/cockpit-desktop metrics`, it works fine.
> ws: Enable sandbox in cockpit-desktop's webkit browser

- .github/workflows/build-dist.yml
- .github/workflows/unit-tests.yml
On the latest GitHub 20.04 image, podman can't pull our unit-tests
container any more:
Error committing the finished image: error adding layer with blob "sha256:...":
Error processing tar file(exit status 1): operation not permitted
Let's run the containers as root. This does not matter much for the
host, and until podman is officially supported in Ubuntu, system podman
has fewer potential permission problems.
----
These spontaneously started to fail today, like [build-dist here](https://github.com/cockpit-project/cockpit/pull/15732/checks?check_run_id=2408260405) or [unit-tests here](https://github.com/cockpit-project/cockpit/pull/15732/checks?check_run_id=2408145586).
[tested build-dist on my fork](https://github.com/martinpitt/cockpit/actions/runs/773717557), but not unit-tests. Let's …
> workflows: Run unit-tests container as root

- autogen.sh
- test/make_dist.py
Commit d3f51710dda moved from node_modules/.stamp to package-lock.json
as our canonical stamp file, which regressed make_dist. This fixes
running autogen/configure/make dist with pre-built dist again, as it
does not pointlessly rebuild everything again.
In autogen.sh, don't run npm install if package-lock.json already
exists.
----
These two are the harmless/obvious changes from PR #15720.
> Restore package-lock.json from cached dist tarballs

- src/common/cockpitjson.c
- src/common/cockpitwebcertificate.c
Spotted by coverity:
src/common/cockpitjson.c:1073: cond_notnull: Condition "copy", taking true branch. Now the value of "copy" is not "NULL".
src/common/cockpitjson.c:1076: notnull: At condition "copy", the value of "copy" cannot be "NULL".
src/common/cockpitjson.c:1076: dead_error_condition: The condition "copy" must be true.
src/common/cockpitjson.c:1076: dead_error_line: Execution cannot reach the expression "json_object_ref(object)" inside this statement: "json_node_take_object(new_n...".
> Fix two coverity errors

- .gitignore
- Makefile.am
- test/make_dist.py
- tools/build-debian-copyright
Our current [cockpit-dist](https://github.com/cockpit-project/cockpit-dist/) approach is broken: it becomes too big too quickly, and causes [prune-dist](https://github.com/cockpit-project/cockpit/actions/workflows/prune-dist.yml) to just error out on `git push -f`. In cockpit-machines we recently [reworked the dist storing](https://github.com/cockpit-project/cockpit-machines/pull/84) to keep the literal files in git, not the full tarballs.
For that to work in cockpit, we need to have `make dist` *not* do npm/webpack after unpacking pre-built dist/ and package-lock.json. It should be fast (well under 1 minute) to retain the "fast local PR testing/development" behaviour that we have right now.
The main thing that is currently broken is the generated debian/copyright file.
With the fixes …
> Fix debian/copyright failure during `make dist` with pre-built dist/

- test/common/testlib.py
- test/verify/check-kdump
https://bugzilla.redhat.com/show_bug.cgi?id=1929259 has crept into RHEL
9.0.
----
Blocks the image refresh in https://github.com/cockpit-project/bots/pull/1955, see [failed test](https://logs.cockpit-project.org/logs/pull-1955-20210423-050736-4d7f63e8-rhel-9-0-cockpit-project-cockpit/log.html#51)
> Fix tests for current RHEL 9.0

- Makefile.am
- selinux/cockpit.fc
- selinux/cockpit.if
- selinux/cockpit.te
- selinux/cockpit_session_selinux.8
- selinux/cockpit_ws_selinux.8
- tools/cockpit.spec
This policy will be shipped in cockpit-ws package on rhel-9 onward and fedora-33 onward.
This policy is taken from Fedora rawhide.
We don't plan to backport to rhel-8 and centos-8. Debian/suse may come later.
> Add custom selinux policy

- tools/cockpit.spec
Moving above to ensure that service is executed with the proper label.
See https://github.com/cockpit-project/cockpit/pull/15707#discussion_r619292665
> specfile: Change order of selinux post action

- test/verify/check-selinux
In new rhel-8-5 CI has seen:
```
org.fedoraproject.Setroubleshootd: couldn't introspect /org/fedoraproject/Setroubleshootd: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```
> test: Relax setroubleshootd disconnect message

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
- pkg/systemd/services/services.jsx
- pkg/systemd/services/services.scss
- test/verify/check-system-services
So I was thinking how I can solve https://github.com/cockpit-project/cockpit/issues/14321 
Went to service details and I realized that so much information there are not useful for most scenarios, or at least they were never useful for me till now. 
So I though I should hide them by default, and display indead some more useful information, like the port a socket activated service is exposed at, for example.
Having the above mentioned property exposed we can move forward in the future with linking the service details of service sockets to the firewall page. 
What do you think? @marusak ?
With my changes cockpit.socket looks like this:
> Hide unimportant details from service details and show some important ones instead

- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
>  packagekit: filter duplicate error messages and display them in separate lines

- doc/guide/packages.xml
- pkg/metrics/manifest.json
- pkg/shell/indexes.js
- test/verify/check-pages
- test/verify/check-shell-multi-machine-key
Currently when one  would navigate to `/metrics` (through "View details and history") no menu item would be shown as active. Also it was not possible to define documentation items for metrics.
Problem with this component is that it is being treated as separate component but it does not have separate menu entry. There are a few options how this could be fixed:
- Add 'Metrics' menu item
- Serve this on `/system/metrics` and move `pkg/metrics` source into `pkg/systemd/source`
- Do what I have done in this PR
- Some other hack/workaround I haven't though of (?)
Before I document this new option, write tests and  cleanup commits I would like to hear what others think. Is this step in a good direction or would you solve this differently?
> metrics: Show active menu item and add documentation to pcp

- test/verify/check-system-services
This often starts out with being exactly "1.0 MB", which fails the
previous condition. There is no particular expectation how much memory
this initially uses, so just reduce it.
----
I've seen this at least twice today, most recently [here](https://logs.cockpit-project.org/logs/pull-15761-20210429-145258-8dad8c4e-rhel-8-5/log.html#252)
> test: Fix initial expected memory in TestServices.testBasic

- pkg/lib/cockpit-components-inline-notification.jsx
- test/verify/check-networkmanager-firewall
Alerts are already visibly errors and provide ARIA to screen readers.
Additionally, `<kbd>` is not passed to screen readers in any special way.
By default, `<kbd>` just unnessarily changes the font to mono.
> lib: Drop redundant error message in alert modals

- pkg/storaged/client.js
If the client.manager.wait() is rejected, the following initializations
then can't detect any features, which sets client.features = {}. This
tricks the UI into thinking that initialization is complete, but nothing
really works: There are no known features or file systems.
To make this less hilariously hard to debug, do the same as
client.init() does on a wait failure and return `client.features =
false`. This keeps the overview page in the "initialization" empty
state.
If there is a "changed" signal from the manager proxy after that, it
will then re-trigger the initialization properly. Otherwise, the page
remains in "Storage can not be managed on this system", which is more
honest than offering broken dialogs everywhere.
----
Spotted in https://github.com/cockpit-project/bots/pull/1952 …
> storaged: Check for udisks manager proxy failure

- pkg/shell/superuser.jsx
- pkg/static/login.js
- pkg/systemd/superuser-alert.jsx
- src/bridge/askpass.c
- src/bridge/cockpitpeer.c
- src/bridge/cockpitpeer.h
- src/bridge/cockpitpipechannel.c
- src/bridge/cockpitpolkitagent.c
- src/bridge/cockpitrouter.c
- src/bridge/cockpitrouter.h
- src/common/cockpitpipe.c
- src/common/cockpitpipe.h
- src/ws/cockpitauth.c
- src/ws/cockpitwebservice.c
- src/ws/test-auth.c
- src/ws/test-authssh.c
- src/ws/test-handlers.c
- test/common/testlib.py
- test/containers/check-bastion
- test/verify/check-packagekit
- test/verify/check-reauthorize
- test/verify/check-shell-keys
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-superuser
- test/verify/check-system-info
- test/verify/check-system-realms
- test/verify/check-system-shutdown-restart
- test/verify/check-users-roles
This avoids running sudo without explicit request. This means that we don't probe anymore with `sudo -vn` but instead show the actual error message from sudo.
Demo: https://www.youtube.com/watch?v=Z1Cz-TTPsUs
----
Cockpit will no longer try to run sudo on the very first login, and you have to explicitly turn on administrative access once for each browser profile that you use to access Cockpit. This prevents cockpit's use of sudo being noisy in the journal.
In addition, Cockpit now shows sudo's exact messages in the "Administrative access" dialog.
> shell: Genuine sudo errors

- pkg/lib/ct-card.scss
This exact same rule is defined a few lines below once again.
> lib: Remove duplicate css rule

- pkg/base1/test-dbus-common.js
Similarly to commit dc2aaff1ab82c26898, the other two D-Bus watch tests
need a deep update of the cache as well. After commit 4e5a309f0af the
order of the messages changed (often), and we could get the "empty"
state updates after the "real" one.
> base1: Fix D-Bus watch tests

- selinux/cockpit.te
Looks like this setting is implicit with kerberos enabled.
cockpit.socket fails to start if kerberos_enabled=false
> selinux: allow cockpit socket to bind nodes

- .github/workflows/build-dist.yml
- .github/workflows/prune-dist.yml
- .github/workflows/publish-dist.yml
- test/make_dist.py
In publish-dist, directly commit dist/ and related files to the -dist
repo (the ones which make_dist actually needs), and tag the commit with
the SHA, so that they are still easy to look up.  Drop the "old tarball"
removal. This uses git in a much more efficient way, as it now only
stores the deltas. In particular, for commits/PRs which don't change
src/, that will just add an additional tag to the previous build and
store no extra files at all. This avoids regularly overflowing the -dist
repo and making `git push` hang.
Simplify build-dist to do away with the intermediate tarball, as there
are not so many files to make upload-artifact inefficient.
Push every build as an individual tag only, without having them on a
branch. That avoids the need for force-pushing and history rewriting, …
> Rework pre-built dist upload/download

- Makefile.am
- test/make_dist.py
When using cached dist/ files, `make dist` is very fast, and files are
often much less than one second apart. Copying files to the temporary
dist tree with plain `tar` dropped the sub-second mtimes, which often
leads to inverted mtime ordering. E.g. while the ordering is correct in
the build tree:
$ stat -c %y package-lock.json  dist/shell/manifest.json
2021-05-03 15:58:09.164707531 +0200
2021-05-03 15:58:09.256708795 +0200
the manifest.json's mtime got stored as "15:58:09" in the generated
`make dist` tarball, and suddenly become older than package-lock.json.
This caused build failures in environments without npm/node (like during
RPM package build).
Consistently use the POSIX tar format when copying file trees around, so
that all files are copied with exact mtimes. This replaces the …
> build: Fix `make dist` to preserve time stamps

- tools/cockpit.spec
- selinux stuff without %if %with_selinux
- obsoletes without version
- /usr/share/cockpit/static/fonts not owned
> tools: specfile fixes

- containers/ws/Dockerfile
The label commands where adjusted to contain IMAGE and NAME as env variables.
With newer podman, these are apparently just passed into the environment of the
docker run call itself, instead of being string-substituted on the command line.
See containers/podman#10192
> containers: Adjust label commands in cockpit/ws Dockerfile to follow man page example

- pkg/lib/menu-select-widget.scss
- pkg/shell/shell-modals.jsx
- pkg/shell/shell.scss
The language selection dialog now looks like this in the PR:
I've worked on interactions a little too. Check out background override with the `:focus-within` selector. It improves both keyboard and mouse usage, keeping the background highlight on the selected item even when something else is being selected or when the focus is outside of the list.
> Restyle language menu to select

- .github/workflows/build-dist.yml
- .github/workflows/publish-dist.yml
While putting the individual files into the artifact zip works (done in
commit cf04588de554fa6), the artifact becomes much bigger (8.5 MB → 39
MB), much slower to create/upload (1 s → 40s [sic]), and also slower to
download/unpack (1 s → 13s).
So go back to storing the entire dist tarball as artifact (we already
have it anyway), and move the file selection to publish-dist.
-----
Tested on my fork. Compare the step times and artifact sizes of [build-dist](https://github.com/martinpitt/cockpit/runs/2493417211?check_suite_focus=true) and [publish-dist](https://github.com/martinpitt/cockpit/runs/2493492640?check_suite_focus=true) against a [build-dist](https://github.com/cockpit-project/cockpit/runs/2493135975?check_suite_focus=true) and …
> workflows: Go back to tarball artifact output in build-dist

- test/common/testlib.py
Example failure: https://logs.cockpit-project.org/logs/pull-152-20210504-131857-cb98179e-fedora-34/log.html#43-1
> test: Don't fail when a session has closed before we could terminate it

- test/verify/check-connection
- test/verify/check-shell-host-switching
- tools/cockpit.spec
- tools/debian/cockpit-ws.install
- tools/debian/cockpit-ws.postinst
- tools/debian/cockpit-ws.postrm
- tools/debian/rules
Users commonly want to just remove /etc/motd.d/cockpit or
/etc/issue.d/cockpit.issue, instead of symlinking them to /dev/null.
However, rpms' %config handling does not respect that, and brings back
the files on upgrade. This also raises an alarm in `rpm --verify`.
Likewise, dpkg's conffile logic only handles plain file content changes
or removals, not symlinks.
Stop packaging the symlinks, and create/remove them in the package
scrips instead.
https://bugzilla.redhat.com/show_bug.cgi?id=1876848
> tools: Dynamically manage motd/issue symlinks in package scripts

- Makefile.am
- configure.ac
- doc/Makefile-doc.am
- doc/guide/Makefile-guide.am
- doc/man/Makefile-man.am
- packit.yaml
- src/bridge/Makefile.am
- src/ssh/Makefile-ssh.am
- tools/mock-build-env/README.md
- tools/mock-build-env/gnutls.pc
- tools/mock-build-env/json-glib-1.0.pc
- tools/mock-build-env/krb5-gssapi.pc
- tools/mock-build-env/krb5.pc
- tools/mock-build-env/security/pam_appl.h
This re-enables packit tests after commit c4908fe050dda.
This is a hack, but at least we have all our tests to tell us when we break this again.
> make dist fixes, allow building in a minimal environment, re-enable packit

- test/verify/check-superuser
The test calls Browser.relogin().
---
Fixes [this failure](https://logs.cockpit-project.org/logs/pull-15803-20210507-143509-d9ddecc7-fedora-33-firefox/log.html#198)
> test: Allow restart messages in TestSuperuser.testBasic

- pkg/lib/service.js
- pkg/metrics/metrics.jsx
- test/verify/check-metrics
If there is no data and pmlogger.service is not running, give a more
specific message, and offer to enable/start it if the user is
privileged.
Split the test case into two cases: pmlogger is stopped (then UI for
restarting it), or it's failing or hanging (then old troubleshoot link
UI).
-----
Limited access mode, not running:
Superuser access, not running -- this is the common case:
Unit failed (permissions  don't matter):
And finally, if there's something "weird" going on, i. e. pmlogger is running, but it does not collect any data (hopefully most users will never see this):
> metrics: Add button to enable pmlogger.service

- doc/guide/feature-pcp.xml
- test/verify/check-metrics
Demonstrate how to export PCP metrics from a client machine into an
already existing Grafana installation. This uses the recently added
Grafana container on the services image [1], which is completely
unconfigured other than having the two required plugins (PCP and Redis)
installed (as our tests can't access the internet).
So far, Cockpit is not involved in this at all. Over time, we can build
UI for this and replace the CLI commands.
Document in the feature page how to expose PCP metrics manually.
[1] https://github.com/cockpit-project/bots/pull/1990
-----
> test: Test Grafana integration via CLI

- pkg/lib/cockpit-components-listing-panel.jsx
- test/verify/storagelib.py
The tests used to identify tabs by their position in the DOM, but that
isn't reliable since the ListingPanel instantiates tabs dynamically.
Thus, while the tests might look for the third .ct-listing-panel-body
for the third tab, only two tabs might have been instantiated and the
.ct-listing-panel-body for the third tab is actually the second one in
the DOM.
To make this reliable, let's put the actual tab index into the DOM as
an attribute and have the tests look for that.
We never actually got bitten by this, but we will in the future when
we have more tabs than two.
> storage: More robust testing of content listing tabs

- tools/cockpit.spec
Commit 5705709d41 dropped the motd/issue symlinks in /etc from the rpm,
so there should not be any dangling symlinks any more.
----
@lnussel , this is some cleanup from [this discussion](https://github.com/cockpit-project/cockpit/pull/15784#discussion_r629067830). Do you mind reviewing this one? Thanks!
no-test as this does not affect anything in our CI. The fedora-33 run will just show that we didn't syntactically break the spec file.
> tools: Drop obsolete OpenSUSE specific /run ghosts

- pkg/systemd/overview-cards/insights.jsx
- test/verify/check-metrics
Drop the extra /insights suffix, which is not valid.
https://bugzilla.redhat.com/show_bug.cgi?id=1958379
> systemd: Fix insights URL

- containers/unit-tests/build.sh
- containers/unit-tests/scenario-dist.sh
Skip the full `make` build and xz extreme compression in the "start
dist" scenario.
> containers: Speed up dist unit-tests scenario

- pkg/storaged/dialog.jsx
The two uses of FormGroup in Row looked inconsistent to me re helperText, but I didn't investigate this further
> storage: Use FormGroup helperText consistently in dialogs

- test/common/testlib.py
Commit b0c8efbd introduced dataclass, but we can't use that yet as
RHEL/CentOS 8's Python does not yet have that. Rewrite the code using a
4-tuple instead.
> testlib: Eliminate dataclass

- pkg/lib/cockpit-components-table.jsx
This gets reported when this library is being used in other projects
with different set of eslint rules.
> lib: Remove unused parameters in callbacks

- pkg/lib/serverTime.js
- test/verify/check-system-info
Checking for the service unit existence is not sufficient: On Fedora,
systemd-timesyncd.service does exist, but is disabled and never actually
used, as chronyd.service is running. Thus setting any custom NTP servers
has no effect, and is thus highly misleading.
Run `TestSystemInfo.testTimeServers` on all OSes, and ensure that the
"specific NTP servers" option is disabled when timesyncd is not in use.
----
I noticed that while investigating our [long-standing testTimeServers unstable test](https://logs.cockpit-project.org/logs/pull-15810-20210510-174243-2cab9769-fedora-34/log.html#280), and thought "WTH? That doesn't make any sense"..
> lib: Only offer configuring specific NTP servers with enabled systemd-timesyncd

- packit.yaml
This should allow us to catch test bugs before releases (like the recent
introduction of `dataclass` into testlib, which isn't available in
RHEL/CentOS 8 yet).
> packit: Run on CentOS stream
