cockpit-project/cockpit

- pkg/storaged/drives-panel.jsx
- pkg/storaged/iscsi-panel.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/mdraids-panel.jsx
- pkg/storaged/others-panel.jsx
- pkg/storaged/overview.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/storage.css
- pkg/storaged/things-panel.jsx
- pkg/storaged/vdos-panel.jsx
- pkg/storaged/vgroup-details.jsx
- pkg/storaged/vgroups-panel.jsx
- test/verify/check-storage-mdraid
Now they use the same layout as the Devices, Drives, etc panels on the
Storage Overview page.
> storage: Improve side panels on Details page

- pkg/systemd/overview.scss
> overview: Make the sudo notification responsive

- pkg/systemd/overview-cards/configurationCard.jsx
- test/verify/check-system-info
To make it re-open the { superuser: "try" } channel.
> systemd: Re-init ServerTime when access level changes

- doc/man/cockpit.conf.xml
description update.  make it clear cockpit.conf is not required and make need to be created
> man: updated cockpit.conf(5) manpage

- pkg/lib/machine-unknown-hostkey.html
- pkg/lib/patterns.js
> Host modal button & spinner order

- pkg/shell/base_index.js
> shell: Clicking connection error indicator oopses

- test/verify/check-machines
See https://github.com/cockpit-project/bots/pull/896
> test: Latest rhel-8-3 image supports VM firmware selection

- pkg/shell/indexes.js
- pkg/shell/superuser.jsx
- test/verify/check-superuser
> shell: Make the super-user-indicator apply to the current machine

- pkg/systemd/logs.html
- pkg/systemd/logs.js
- pkg/systemd/logs.scss
- test/verify/check-journal
This is rough implementation of inline help for logs. I though I would post it here so @andreasn can take a look and let me know what he thinks about it in this early stage. It contains all the info I think should be there, but I would appreciate help with wording it correctly :)
(and yes, I'll do in the meantime the journal command)
Fixes #13937
> logs: Introduce inline help

- pkg/shell/nav.scss
Fixes #14160 - help icons are cut off
> nav: Replace help icon w/ SVG for better rendering

- test/README.md
- test/common/testlib.py
- test/verify/check-docker
- test/verify/check-journal
- test/verify/check-kdump
- test/verify/check-login
- test/verify/check-machines
- test/verify/check-networking-firewall
- test/verify/check-storage-format
- test/verify/check-storage-luks
- test/verify/check-storage-resize
- test/verify/check-system-info
> test: Add special cases for rhel-8-3-distropkg

- test/common/testlib.py
> test: Remove unused expected message

- pkg/machines/components/diskAdd.jsx
(These are not clean backports unfortunately)
> Some fixes for disk add dialog for rhel 7.9

- test/common/run-tests
> test: Fix run-tests to get along with non-blocking stdout

- test/verify/check-accounts
- test/verify/check-connection
- test/verify/check-host-switching
- test/verify/check-journal
- test/verify/check-networking-firewall
- test/verify/check-pages
- test/verify/check-realms
- test/verify/check-roles
- test/verify/check-setroubleshoot
- test/verify/check-system-info
cockpit got rebased in 8.3, drop the special cases.
This needs to land in lockstep with https://github.com/cockpit-project/bots/pull/990
> test: Adjust to RHEL 8.3 getting cockpit 221.1

- package.json
> package.json: Update remarkable package dependency

- pkg/kdump/kdump-view.jsx
- test/verify/check-kdump
> Kdump nondestructive test

- test/verify/check-journal
- test/verify/check-kdump
- test/verify/check-keys
- test/verify/check-system-info
distropkg is going to fail, but I'll trigger distropkg for https://github.com/cockpit-project/bots/pull/1032 which should succeed.
> test: Update to a new release in 8.3

- pkg/lib/form-layout.scss
- pkg/machines/components/networks/networkOverviewTab.jsx
- pkg/machines/components/vmOverviewTabLibvirt.jsx
Highlights:
- Improve PF4 support
- Restyle to better match current PF4 (spacing, label style)
- Use CSS custom properties instead of SASS variables
Closes #13683
Closes #14306
Fixes #13641
> ct-form updates (2020-07)

- src/ws/test-remotectlcertificate.c
If sscg is present in the build environment, the test failed on two
things:
* The "falling back to openssl" message does not happen for
/remotectl-certificate/create, as sscg is actually being used.
But it will still happen for the /create-no-permission test, so make
it optional.
* There is a second file in  ws-certs.d/ for the sscg-generated CA.
Expect that iff sscg is installed.
> ws: Fix test-remotectlcertificate with sscg

- po/cs.po
- po/de.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nl.po
- po/uk.po
- po/zh_CN.po
> Translations refresh

- pkg/shell/manifest.json.in
- pkg/shell/superuser.jsx
- src/bridge/cockpitrouter.c
- src/ws/cockpit-desktop.in
- src/ws/cockpitwebservice.c
- test/verify/check-connection
https://bugzilla.redhat.com/show_bug.cgi?id=1841104
> desktop: Use "pkexec" to start the privileged bridge

- test/verify/check-s4u-ssh
> tests: Add the S4U proof of concept as a verify test

- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- test/verify/check-networking-bond
- test/verify/check-networking-bridge
- test/verify/check-networking-team
Use "group" and "member" instead.
> networking: Don't use "master" or "slave" in the code

- HACKING.md
Fixes #13970
----
I tested these in a Fedora 32 and a Debian sid toolbox.
> HACKING: Document how to build distribution packages

- pkg/machines/components/nicEdit.jsx
Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1857044
> machines: fix close button on the header of NIC Edit modal dialog

- tools/cockpit.spec
See https://fedoraproject.org/wiki/Changes/UseMakeBuildInstallMacro
Thanks to Tom Stellard!
> tools: Use %make_install macro

- src/ws/session.c
We currently store forwarded Kerberos credentials in what is effectively
a "child setup" function in cockpit-session, after we fork() but before
we exec() cockpit-bridge.
Let's try to reduce the amount of stuff we do after fork():
- after fork() but before exec() is an implementation detail of how
processes are spawned on unix systems
- POSIX specifies a very small number of functions (mostly syscalls)
that are unconditionally safe to call at this point.  The number goes
up if you're on Linux (which we always are), and if the original
process is single-threaded (which it probably currently is), but none
of these things are well-specified anywhere.  In any case, it's best
practice to exec() ASAP after a fork().
- we want to move to a new spawn helper in the future without support
for …
> session: Store krb credentials before fork()

- pkg/machines/manifest.json.in
- pkg/networkmanager/manifest.json.in
- pkg/systemd/manifest.json.in
> all: Adjust documentation URLs to recent RHEL docs changes

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/cockpit-components-table.scss
- pkg/lib/listing.scss
- pkg/machines/components/networks/networkList.jsx
- pkg/machines/components/storagePools/storagePoolList.jsx
- pkg/machines/components/storagePools/storagePoolList.scss
- pkg/machines/hostvmslist.jsx
- pkg/machines/hostvmslist.scss
> Some style fixes on PF4 tables

- pkg/shell/superuser.jsx
Previously, connecting to a remote host and switching around the admin
level on it would change the setting for the next session on the local
host.
> shell: Remember last admin level per host

- package.json
See  https://github.com/yannickcr/eslint-plugin-react/issues/2728
Does not affect master, I'll check with rhel-8-3 branch as well.
> package.json: Pin down eslint-plugin-react

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- test/verify/check-machines
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1862333
> machines: Fix OS autodetection in create VM dialog and add test for it

- package.json
- pkg/systemd/overview-cards/configurationCard.jsx
This isn't being used any more.
> systemd: Drop bootstrap-combobox

- pkg/lib/cockpit-components-table.scss
- pkg/machines/hostvmslist.scss
- pkg/machines/machines.scss
This was blocking me on https://github.com/cockpit-project/cockpit/pull/14283.
> machines: Fix padding for actions in VM list

- test/verify/check-docker
- test/verify/check-machines
- test/verify/check-metrics
- test/verify/check-networking-checkpoints
- test/verify/check-realms
- test/verify/check-system-info
See https://github.com/cockpit-project/bots/pull/1135
> test: Adjust special cases for ubuntu-stable moving to 20.10

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
- test/verify/check-networking-basic
- test/verify/check-pages
- test/verify/check-realms
- test/verify/check-services
Remove a bunch of uneeded CSS.
> services: Move Dropdown to the PF4 React component

- pkg/lib/long-running-process.js
These changes always crop up when I run `npm run eslint:fix`
> lib: Run eslint:fix on long-running-process.js

- pkg/lib/cockpit-components-file-autocomplete.jsx
- pkg/lib/cockpit-components-table.jsx
- test/common/testlib.py
- test/verify/check-login
- test/verify/check-machines
- test/verify/check-networking-basic
- test/verify/check-pages
Resolves rhbz#1865821
Resolves rhbz#1866995
> [backport] Update rhel-8-3 branch

- pkg/lib/journal.css
- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.css
- pkg/systemd/logs.scss
- test/verify/check-networking-basic
- test/verify/check-networking-bond
- test/verify/check-networking-bridge
- test/verify/check-networking-checkpoints
- test/verify/check-networking-settings
- test/verify/check-networking-team
> Make networking page less bootstrap dependent and usable on mobile devices

- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/networking.css
> firewall: bring back grey background by using Page component

- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/machines/hostvmslist.jsx
- pkg/machines/hostvmslist.scss
- test/common/testlib.py
- test/verify/check-machines
> machines: Implement filtering of VMs list

- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.css
Issue #14303 is not yet completely addressed, but let's make it step by step.
> Some design improvements in the Network page

- containers/bastion/Dockerfile
- containers/ws/Dockerfile
- test/README.md
- test/selenium/README.md
- test/verify/check-docker
- test/verify/check-login
- test/verify/check-machines
- test/verify/check-networking-firewall
- test/verify/check-packagekit
- tools/cockpit.spec
See https://github.com/cockpit-project/bots/pull/1187
> Stop documenting and testing Fedora 31

- src/bridge/cockpitcgroupsamples.c
- src/bridge/test-metrics.c
We don't use this metric in cockpit itself for v2 - the docker page uses v1 (and its integration tests will make sure this does not regress). But I need it for https://github.com/martinpitt/performance-graphs to add the top CPU/memory consumers.
I added a smoke unit test, but the real functional test for now is something like this:
```
{ printf '\n{ "command": "open", "channel": "c", "payload": "metrics1", "source": "internal", "interval": 1000, "metrics": [ {"name": "cgroup.cpu.usage"} ] }\n---\n'; sleep 3; } | ./cockpit-bridge --interact=---
```
Fixes #14420
> bridge: Support internal cgroupsv2 metrics

- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- test/verify/check-networking-bond
> network: Correctly set up ARP related fields on edit

- pkg/users/account-details.js
- pkg/users/authorized-keys-panel.js
- pkg/users/index.html
- pkg/users/users.scss
- test/verify/check-accounts
- test/verify/check-keys
New design: ![Screen Shot 2020-08-27 at 13 50 53](https://user-images.githubusercontent.com/14921356/91439105-bc362b00-e86c-11ea-8874-fa53398b1e70.png)
> Modernize users page - stop using bootstrap classes and start using PF4 components instead

- src/ws/login.css
1. Fit layout to content
2. Scale logo width to 100% minus 1rem padding for each side
> login: Fix mobile layout

- pkg/lib/cockpit-components-listing-panel.scss
- pkg/lib/cockpit-components-table.jsx
- pkg/lib/cockpit-components-table.scss
- pkg/packagekit/history.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
> Packagekit list to PF4 table component

- Makefile.am
- containers/ws/atomic-install
- src/ssh/cockpitsshrelay.c
- test/verify/check-login
- tools/cockpit.spec
- tools/debian/cockpit-ws.dirs
Spotted here: https://github.com/cockpit-project/cockpit/pull/14578#discussion_r485512928
> Drop /var/lib/cockpit

- pkg/packagekit/history.jsx
- pkg/packagekit/updates.jsx
- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sv.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
- test/verify/check-packagekit
This is a result of a rebase that I not entirely managed...
> Fix forgotten strings

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services.jsx
- test/verify/check-services
> services: Remove systemd templates

- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sv.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
> Dear bots, would you mind doing a po-refresh? Danke!

- src/common/cockpitjsonprint.c
- src/common/cockpitmemfdread.c
Here are some more issues that I found while unit-testing the newly factored-out code.
The unit-tests themselves depend on the control-messages handling code (which will come later).
> some fixups to robustify the JSON print/read code

- pkg/lib/cockpit-components-listing-panel.jsx
- pkg/lib/cockpit-components-listing.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/networking.css
- pkg/packagekit/history.jsx
- test/verify/check-networking-firewall
Simplebody version from Listing component is not used elsewhere so it
was removed.
> firewall: port tables in Firewall page to PF4 Tables

- test/verify/check-metrics
- test/verify/check-storage-luks
See https://github.com/cockpit-project/bots/pull/1250
> [rhel-8.3] backport CentOS 8 Stream test fixes

- test/verify/check-realms
freeipa-client got added to the image in
https://github.com/cockpit-project/bots/pull/1262
> test: Enable FreeIPA tests on ubuntu-2004

- pkg/users/password-dialogs.js
The conversation goes something like this:
$ passwd
Changing password for anton.
Current password:
You must wait longer to change your password
Current Password:
passwd: Authentication token manipulation error
passwd: password unchanged
Note that there is a second "Current Password" prompt, and that it has
different capitalization.  Previously, we would miss that prompt, but
often enough the "\n" that was sent as a reaction to "You must wait
longer" would answer it.  But often not, since passwd very likely
drains its input before reading a password.
Also, we make sure that a timeout is shown with the intended error
message, and not "Your session has been terminated", which is
misleading.
> users: Fix conversation with passwd re "you have to wait longer"

- test/verify/check-sosreport
This test on rhel-atomic keeps running into the timeout.
See cockpit-project/bots#1271
> tests: Increase timeout in check-sosreport

- pkg/dashboard/list.js
- pkg/lib/machine-change-port.html
- pkg/lib/machine-dialogs.js
- pkg/lib/machines.js
- pkg/shell/hosts.jsx
This capability was removed in Cockpit 135, in 082da24a5a2a27d521e.
> lib: Assume cockpit-ws doesn't have the "ssh" capability

- pkg/lib/machine-add.html
- pkg/lib/machine-dialogs.js
Shweta Jalgaonkar did a review of the text strings used in the add
host dialog, and these are the changes she recommended.
> add host: wording fixes

- package.json
- pkg/lib/cockpit-components-file-autocomplete.jsx
- test/verify/check-pages
> package.json: Update @patternfly/react-core package dependency

- pkg/lib/cockpit-components-table.jsx
> lib: Update documentation url to a new location

- pkg/machines/components/vm/vmActions.jsx
- pkg/machines/components/vm/vmExpandedContent.jsx
- pkg/machines/components/vmDisksTab.jsx
- pkg/machines/components/vmnetworktab.jsx
> machines: VM details: Change run/stop button to primary & add buttons to secondary

- .github/workflows/npm-update.yml
- .github/workflows/po-refresh.yml
- .tasks
This avoids a lot of moving parts in our infrastructure (webhook,
npm-trigger roundtrip, tasks container).
> Run po-refresh and npm-update in GitHub workflows

- package.json
See https://github.com/react-dropzone/react-dropzone/issues/1022
Fixes failures like [this](https://logs.cockpit-project.org/logs/pull-1327-20201023-062930-2e809c52-ubuntu-stable-cockpit-project-cockpit/log.html)
> package.json: Add 'file-selector' dependency

- pkg/dashboard/index.html
- pkg/dashboard/list.js
- pkg/shell/shell.scss
Support for this has been removed in b37b8592e42e.
> dashboard: Don't offer user synchronization

- pkg/machines/app.jsx
- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/machines/components/deleteDialog.jsx
- pkg/machines/components/deleteResource.jsx
- pkg/machines/components/diskAdd.jsx
- pkg/machines/components/diskEdit.jsx
- pkg/machines/components/networks/createNetworkDialog.jsx
- pkg/machines/components/nicAdd.jsx
- pkg/machines/components/nicEdit.jsx
- pkg/machines/components/storagePools/createStoragePoolDialog.jsx
- pkg/machines/components/storagePools/storagePoolDelete.jsx
- pkg/machines/components/storagePools/storageVolumeCreate.jsx
- pkg/machines/components/vcpuModal.jsx
- pkg/machines/components/vm/bootOrderModal.jsx
- pkg/machines/components/vm/firmwareModal.jsx
- pkg/machines/components/vm/memoryModal.jsx
- pkg/machines/components/vmSnapshotsCreateModal.jsx
- pkg/machines/components/vmSnapshotsRevertModal.jsx
- pkg/machines/machines.scss
- test/verify/check-machines
Also never use /tmp but self.vm_tmpdir
> test: destroy and undefine all storage pools in machines tests teardown

- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.css
> networking: fix dropdown getting hidden after the end of the card

- test/common/run-tests
> test: Test tests marked as changed 3 times instead of 600

- pkg/machines/components/aggregateStatusCards.css
- pkg/machines/components/aggregateStatusCards.jsx
- pkg/machines/machines.scss
Split the icon fixes for the storage pool and network cards out from #14686.
> machines: Fix storage pool and network icons

- test/verify/check-connection
- test/verify/check-journal
- test/verify/check-kdump
- test/verify/check-login
- test/verify/check-machines
- test/verify/check-multi-os
- test/verify/check-networking-firewall
- test/verify/check-pages
- test/verify/check-storage-format
- test/verify/check-storage-luks
- test/verify/check-storage-resize
- test/verify/check-system-info
Generic tests special cases. I found bunch of cases where the whole
class was skipped on distropkg and also tests were skipped on distropkg.
Cleaned up those cases (replaced the 8-3-distropkg with 8-4) and in one
case there was special case for distropkg in test where distropkg was
skipped so cleaned that one as well.
> test: Introduce RHEL 8.4 image

- pkg/machines/scripts/create_machine.sh
- pkg/machines/scripts/install_machine.sh
- test/verify/check-machines
> machines: Allow a space characters in arguments of virt-install

- pkg/machines/components/aggregateStatusCards.css
- pkg/machines/components/aggregateStatusCards.jsx
- pkg/machines/components/aggregateStatusCards.scss
- pkg/machines/components/consoles.css
- pkg/machines/components/networks/networkList.jsx
- pkg/machines/components/networks/networkList.scss
- pkg/machines/components/storagePools/storagePoolList.jsx
- pkg/machines/components/storagePools/storagePoolList.scss
- pkg/machines/components/vm/vmExpandedContent.jsx
- pkg/machines/components/vm/vmExpandedContent.scss
- pkg/machines/components/vmOverviewTabLibvirt.jsx
- pkg/machines/hostvmslist.jsx
- pkg/machines/hostvmslist.scss
- pkg/machines/machines.scss
> machines: Card layout follow-up

- test/verify/check-machines
Honestly I don't see point in doing this - it can only produce unexpected messages.
@KKoukiou or @skobyda do you know why was the case?
> test: Don't logout in machines tests

- pkg/systemd/overview-cards/realmd-operation.js
- test/verify/check-realms
> realmd: Allow canceling dialog after failing to contact domain

- test/common/testlib.py
- test/verify/check-journal
- test/verify/check-login
- test/verify/check-setroubleshoot
- test/verify/check-storage-vdo
Issues for them are resolved.
Really just quick grep, not tested at all, lets see what CI has to say. Very likely I'll need to roll back some of those.
> tests: Drop old and obsolete hacks

- src/ws/login.css
- src/ws/login.html
- src/ws/login.js
> Login: Refactor show and hide

- pkg/systemd/services/services-list.jsx
- pkg/systemd/services/services.jsx
Fixes #9439
Really no idea about this. It was reported 2.5 years ago. Since then we've rewritten the whole services page. Lets see if it still happens. I'll let all tests run and if does not reproduce, I'll retry all of them up to 3 times. If it fails, then I'll try to take a look how it behaves and what can be the problem there.
> systemd: Fix up L10N

- .github/workflows/unit-tests.yml
- containers/unit-tests/start
Get rid of the triplication by using a strategy matrix.
> workflows: Factorize unit tests

- test/README.md
These are supported platforms to run the tests on.
> test: add rhel-8-4 and rhel-atomic to README.md

- package.json
As promised, @allisonkarlitskaya :)
Reverts #14789
> package.json: Drop 'file-selector' dependency

- pkg/networkmanager/utils.js
If the inner most `Promise.All` (the one with `Interface` and `Capabilities`)
would failed, the firewall page when opening 'Add zone' dialog would oops.
The issue was it would resolve even though it should not. Since I find
that return inside return inside return difficult to read I rewrote it
to better readable version when we resolve when we are happy with
everything.
Also this commit does not really investigates why that promise would
fail, but now we will at least see the error message in CI with
`JSON.stringify`.
Partly fixes issue like this: https://logs.cockpit-project.org/logs/pull-14875-20201106-104848-2dd3c321-ubuntu-stable/log.html#153-2
Partly because now the page won't oops but the list of interfaces won't be present so it will likely fail later on waiting for some interface. …
> firewall: Fix oops upon opening zone adding dialog

- pkg/systemd/terminal.jsx
- test/verify/check-terminal
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1897430
> terminal: Reconnect channel with 'Reset' button if exited

- src/bridge/cockpitdbusjson.c
- src/bridge/cockpithttpstream.c
- src/bridge/cockpitinteracttransport.c
- src/bridge/cockpitinternalmetrics.c
- src/bridge/cockpitpcpmetrics.c
- src/bridge/cockpitpeer.c
- src/bridge/cockpitpipechannel.c
- src/bridge/cockpitrouter.c
- src/bridge/cockpitwebsocketstream.c
- src/common/cockpitchannel.c
- src/common/cockpitjson.c
- src/common/cockpitjson.h
- src/common/test-json.c
- src/ws/cockpitchannelsocket.c
- src/ws/cockpitwebservice.c
- src/ws/cockpitwebservice.h
- src/ws/test-webservice.c
Here's a bunch of cleanups inspired by the recent coverity scanning.  The last one is pretty big, and will require a very close reading.
> Random cleanups

- pkg/apps/utils.jsx
- pkg/machines/components/diskEdit.jsx
- pkg/machines/components/networks/createNetworkDialog.jsx
- pkg/machines/components/storagePools/createStoragePoolDialog.jsx
- pkg/machines/components/storagePools/storageVolumeCreate.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/index.html
- pkg/playground/test.html
- pkg/shell/active-pages-dialog.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/multipath.jsx
- pkg/storaged/vdo-details.jsx
So much closer to https://github.com/cockpit-project/cockpit/issues/14544
There a few more places where this is used. Some are a bit trickier (like dropdowns in shell), some just need to be carefully looked at so nothing gets broken.
> Pull right

- pkg/kdump/kdump.scss
- pkg/lib/cockpit-components-table.scss
- pkg/lib/listing.scss
- pkg/lib/page.scss
- pkg/machines/components/vms/hostvmslist.scss
- pkg/machines/machines.scss
- pkg/metrics/metrics.scss
- pkg/packagekit/updates.scss
- pkg/playground/journal.jsx
- pkg/playground/jquery-patterns.js
- pkg/playground/plot.js
- pkg/playground/react-patterns.js
- pkg/playground/speed.js
- pkg/playground/test.js
- pkg/shell/active-pages.scss
- pkg/shell/shell.scss
- pkg/sosreport/sosreport.scss
- pkg/systemd/overview.scss
- pkg/systemd/services/services.scss
- pkg/users/users.scss
Found while I was working on dropping sass-resources-loader.
> Small CSS fixes/cleanups

- pkg/storaged/vdo-details.jsx
This is a forward port of #15021.
> storage: Include stderr of fsadm in dialog error message

- test/verify/check-storage-luks
> test: Remove tang cache updating hacks

- test/common/testlib.py
This allows more precise naughty patterns.
> testlib: Always output unexpected journal and browser messages

- test/verify/check-networking-basic
- test/verify/check-networking-bond
- test/verify/check-networking-bridge
- test/verify/check-networking-firewall
- test/verify/check-networking-team
- test/verify/check-networking-unmanaged
- test/verify/check-networking-vlan
- test/verify/check-storage-basic
- test/verify/check-storage-format
- test/verify/check-storage-hidden
- test/verify/check-storage-iscsi
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-msdos
- test/verify/check-storage-multipath
- test/verify/check-storage-nfs
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-vdo
For now doing just networking and storage tests as first experiment.
> test: Use `wait_visible` instead of `wait_present`

- test/verify/check-accounts
- test/verify/check-machines
- test/verify/check-packagekit
And one more batch left after this one will follow
> Second batch of replace `wait_present` with `wait_visible`

- pkg/systemd/overview-cards/motdCard.jsx
- test/verify/check-system-info
For release notes:
Overview: introduce editing of /etc/motd
----------------------------------------------------
Closes #8296
> overview: allow editing motd

- pkg/packagekit/autoupdates.jsx
- test/verify/check-packagekit
The former is better English style.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
> Say updates will be installed "every day" not "everyday"

- pkg/lib/machine-add.html
- pkg/lib/machine-dialogs.scss
> shell: Add host dialog: fix a11y & add helper text

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1908683
> machines: Fix rounding of memory when switching from MB to GB

- Makefile.am
- pkg/lib/qunit-template.html
- webpack.config.js
Inspired by recent changes in starter-kit.
> Webpack cleanups

- src/ws/session-utils.c
Trivial: add a bug ref to a comment.  I had to track this down again today and it took me a bit of time.
> session: add a bug reference to a comment

- test/common/cdp.py
- test/common/firefox-cdp-driver.js
- test/verify/check-embed
- test/verify/check-host-switching
- test/verify/check-machines
This fixes 3 out of 7 or 8 broken tests. The last commit is rather intrusive so I want to see if it actually works or if it has some issues. It many actually fix some of those remaining tests as well.
> Firefox fixes

- po/.gitignore
- po/Makefile.am
- po/html2po
- po/manifest2po
I diffed po/cockpit.pot from master and this branch, and they are identical except for the timestamps.
> po handling cleanups backported from starter-kit

- package.json
- pkg/storaged/mdraids-panel.jsx
Two tiny unrelated changes, did not want to open two PRs.
> eslint:fix fix and translation fix

- pkg/systemd/logs.scss
Make #journal element (immediate child to body) stretch to fill <body>
> system: Remove double scrollbar on the page

- pkg/lib/cockpit-components-plot.jsx
- pkg/lib/cockpit-components-plot.scss
- pkg/lib/hooks.js
- pkg/lib/plot.js
- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/networking.scss
- pkg/networkmanager/plots.js
- pkg/playground/plot.css
- pkg/playground/plot.html
- pkg/playground/plot.js
- pkg/storaged/devices.jsx
- pkg/storaged/overview.jsx
- pkg/storaged/plot.jsx
- pkg/storaged/storage.scss
- test/selenium/selenium-base.py
- test/selenium/selenium-network.py
- test/verify/check-networking-basic
- test/verify/check-pages
- webpack.config.js
This is a evolution of #14850.
> Plotting with SVG

- containers/unit-tests/build.sh
- package.json
- pkg/lib/plot.css
- pkg/shell/shell.scss
- test/verify/check-pages
- tools/cockpit.spec
- webpack.config.js
These are each rather trivial, let's test them together for efficiency
> Various cleanups

- pkg/lib/journal.js
- pkg/systemd/logs.js
- test/verify/check-journal
There is race that when stop() is called, it stops existing processes but
right after it a new process is created and thus it keeps running forever.
Normally this would not be a problem, but with this weird
combination of JS + React it can happen that messages from this service
are shown in the UI.
Honestly, the best solution would be to write it fully in React, I am really playing with the idea of doing that.
> Catching down testJournal.testBasic flake

- containers/unit-tests/scenario-distcheck.sh
- pkg/lib/cockpit-po-plugin.js
- pkg/lib/sassc-loader.js
These things turn up when running "npm run eslint" or "npm run eslint:fix".
> pkg/lib: Fixes for eslint

- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/index.html
- pkg/networkmanager/networking.scss
Follow-up to #15046.
Intention: Organize the SCSS a bit better and remove as much as we can. (Grouping helps to more easily identify related parts.)
So far, the unique commit is 35cd2c3 (and everything after, if there's anything after).
> Network post-PF4: SCSS cleanup

- pkg/lib/cockpit-components-table.scss
- pkg/lib/page.scss
- pkg/systemd/services/services.scss
> lib/page: Improve color contrast for list errors

- pkg/lib/cockpit-components-table.jsx
- pkg/machines/app.jsx
- pkg/machines/components/vm/vmActions.jsx
- pkg/machines/components/vms/hostvmslist.jsx
- test/verify/check-machines-lifecycle
- test/verify/check-machines-nics
> machines: jump back to the main VM page when the VM in whose Details page we are at get's removed from the state

- pkg/shell/indexes.js
- test/verify/check-pages
I guess tests would not hurt, would they :) (no-test while I write them, want to give @garrett chance to take a look)
> a11y: Fix some general issues

- test/verify/storagelib.py
The code was careful not to click on non-existing elements, for
example, but it assumed a stable DOM so that there are no
check-before-use races.  This was true in the days of PhantomJS but is
no longer true with CDP.
Thus, we now allow a testlib.Error and retry.
> test: Allow for asnychronous DOM changes in storagelib

- pkg/machines/components/storagePools/storagePool.jsx
- test/verify/check-machines-storage-pools
> tests: remove no_retry_when_changed from  check-machines-storage-pools

- src/common/cockpitjson.c
- src/common/cockpitpipetransport.c
- src/common/cockpitwebresponse.c
- src/websocket/test-websocket.c
- src/ws/test-auth.c
> coverity fixes

- pkg/machines/components/vm/nics/nicEdit.jsx
- test/verify/check-machines-nics
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1911657
> machines: fix detection of the nic source when displaying the warning in the modal

- pkg/networkmanager/interfaces.js
- test/verify/check-networking-bond
The NM data structure says "master", our own model says "group".
> networking: Fix confusion between master and group

- test/verify/check-packagekit
- test/verify/packagelib.py
As needed for https://github.com/cockpit-project/bots/pull/1574
> test: Restart packagekit service after we do cleanup

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/cockpit-components-table.scss
- pkg/machines/components/vm/disks/vmDisksCard.jsx
- pkg/machines/components/vm/snapshots/vmSnapshotsCard.jsx
- pkg/machines/components/vm/snapshots/vmSnapshotsCard.scss
- pkg/storaged/crypto-panel.jsx
- pkg/storaged/fsys-panel.jsx
- pkg/storaged/nfs-panel.jsx
- pkg/storaged/storage.scss
- test/verify/check-machines-create
- test/verify/check-machines-lifecycle
- test/verify/check-machines-snapshots
- test/verify/check-storage-nfs
Now it will look like:
Machines page:
Storage page:
>  lib: follow the pattern for empty lists as seen on PF4 Table demos

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
- pkg/systemd/services/services.jsx
> services: use PF4 select for choosing unit type

- pkg/machines/components/vm/consoles/desktopConsole.jsx
- test/verify/check-machines-consoles
This was changed to title case in 2ab1b5ebdebd for no good reason.
@KKoukiou was there a good reason for this change?
> machines: Use sentence case

- Makefile.am
- test/common/testlib.py
See individual commits for details. This does some parts of what is being discussed in PR #15235
> node_modules/ improvements

- pkg/static/login.css
> login: Fix layout for "connect to" for requireHost

- pkg/static/login.css
> login: Add margin under the error

- tools/build-debian-copyright
- webpack.config.js
These should be easy to land.  Let's see what the bots say!
> two trivial cleanups

- test/common/chromium-cdp-driver.js
- test/common/firefox-cdp-driver.js
> test: revert whitelisting of error about rendering on document.body

- Makefile.am
- configure.ac
- pkg/lib/sassc-loader.js
- tools/cockpit.spec
- tools/npm-install
- tools/webpack-make
- webpack.config.js
...also make their generation conditional.
> stop disting map files

- pkg/machines/components/networks/networkList.jsx
- pkg/machines/components/storagePools/storagePoolList.jsx
- pkg/machines/components/vm/vmDetailsPage.jsx
- pkg/metrics/metrics.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/network-interface.jsx
- pkg/storaged/details.jsx
- pkg/systemd/hwinfo.jsx
- pkg/systemd/hwinfo.scss
- pkg/systemd/logDetails.jsx
- pkg/systemd/services/service.jsx
- pkg/users/account-details.js
- test/verify/check-system-info
> Make breadcrumbs sticky in all pages that can get 'tall' enough

- pkg/systemd/logs.scss
> logs: Fix sticky day headings

- pkg/storaged/nfs-details.jsx
> storaged: Add a skip after the NFS editing top alert

- package.json
- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- test/verify/check-machines-create
> package.json: Update @patternfly/react-core, @patternfly/react-console

- pkg/lib/patternfly/patternfly-4-overrides.scss
Fixes one of the issues in #15362
> lib/pf4: Fix radio and check alignment

- pkg/static/login.html
> login: Use form on login page

- HACKING.md
- test/make_dist.py
- tools/make-debs
- tools/make-srpm
See individual commits for details. I tested all of make-{dist,srpm,rpm,deb} from a completely clean git checkout, with downloading and with self-building.
> Make all the things

- pkg/lib/cockpit-components-shutdown.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
Fixes #15344
Fixes #15353
Fixes #11222
New spinner is from PF4: no extra styles are added there; regarding alignment I really can't notice something weird:
Reboot done as requested:
New error page:
or 
Old error page:
> Packagekit: fix some minor issues

- pkg/packagekit/updates.jsx
> packagekit: Don't load all package details at once 

- pkg/systemd/logs.js
- test/verify/check-system-journal
Honestly, I just needed PR to run tests :) 
It needs tests and `until:<time_in_future>` should keep following.
> logs: Support 'until' quantifier

- pkg/storaged/side-panel.jsx
- pkg/storaged/storage.scss
- test/verify/check-storage-basic
- test/verify/check-storage-format
- test/verify/check-storage-hidden
- test/verify/check-storage-iscsi
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-msdos
- test/verify/check-storage-multipath
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-scaling
- test/verify/check-storage-used
- test/verify/check-storage-vdo
This uses Patternfly `Flex` components to do the layout, and CSS for font sizes and margins.
> storage: Improve side panel layout, again

- .eslintrc.json
- test/common/run-tests
The second commit can be seen here: https://logs.cockpit-project.org/logs/pull-1244-20210221-210937-96f64c9e-fedora-32/log
```
not ok 23 test/verify/check-image TestImage.testOSTree [ND]Restarting global machine 1
```
> Two random small fixes

- pkg/systemd/logDetails.jsx
- pkg/systemd/services/services.jsx
- test/verify/check-system-services
Both commits need tests but I would like to hear options about this first.
> logs: Add redirection to services page

- pkg/storaged/lvol-tabs.jsx
> storaged: Layout pool descriptions horizontally

- pkg/apps/application.css
- pkg/lib/cockpit-components-table.scss
- pkg/lib/console.css
- pkg/lib/context-menu.css
- pkg/lib/form-layout.scss
- pkg/lib/journal.css
- pkg/lib/listing.scss
- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-overrides-variables.scss
- pkg/lib/patternfly/patternfly-overrides.scss
- pkg/lib/table.css
- pkg/lib/timeline.css
- pkg/lib/variables.scss
- pkg/machines/machines.scss
- pkg/networkmanager/networking.scss
- pkg/packagekit/updates.scss
- pkg/shell/nav.scss
- pkg/shell/shell.scss
- pkg/storaged/storage.scss
- pkg/systemd/services/services.scss
- pkg/systemd/services/timer.scss
- pkg/systemd/system-global.scss
- pkg/systemd/terminal.scss
- pkg/users/users.scss
> lib/page: Remove unused colors

- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/machines/components/networks/createNetworkDialog.jsx
- pkg/machines/components/storagePools/createStoragePoolDialog.jsx
- pkg/machines/components/storagePools/storageVolumeCreateBody.jsx
- pkg/machines/components/vm/disks/diskAdd.jsx
- pkg/machines/machines.scss
See https://www.patternfly.org/v4/components/form/html-demos/#grid
> machines: replace usage of ct-form-split with PF4 grid as suggested in the docs

- pkg/systemd/services/timer-dialog.jsx
Thanks in advance for reviewing.
> Fix minor typo: monthtly -> monthly

- pkg/networkmanager/network-interface.jsx
Thanks in advance for reviewing.
> Fix minor typo: disabnle -> disable

- pkg/machines/components/vm/disks/diskEdit.jsx
> machines: fix misaligned label in disk edit dialog

- pkg/Makefile.am
> Make release tarball re-buildable

- pkg/lib/cockpit-components-password.jsx
- pkg/users/accounts-list.js
- pkg/users/users.scss
- test/verify/check-shell-multi-machine
- test/verify/check-users
> Users fixes and restyling

- pkg/lib/packagekit.js
- test/common/run-tests
- test/verify/check-machines-create
- test/verify/check-machines-disks
- test/verify/check-machines-lifecycle
- test/verify/check-machines-networks
- test/verify/check-machines-settings
- test/verify/check-machines-snapshots
- test/verify/check-system-journal
- test/verify/machineslib.py
As seen in https://github.com/cockpit-project/bots/pull/1742
Possibly we need a few more backports, but lets start with this to get overview of what is broken and then add more commits (as master is green).
> [rhel-8.4] Sync up tests

- pkg/lib/cockpit-components-modifications.css
- pkg/lib/cockpit-components-modifications.jsx
- pkg/lib/cockpit-components-table.jsx
- pkg/selinux/setroubleshoot-view.jsx
> SELinux restyling follow-ups

- pkg/machines/components/create-vm-dialog/createVmDialog.jsx
- pkg/machines/libvirt-common.js
- pkg/machines/scripts/create_machine.sh
- test/verify/check-machines-create
> machines: allow creation of non-root user for unattended installations

- pkg/systemd/overview-cards/usageCard.jsx
> overview: fix accessibility of the progress bar

- pkg/packagekit/updates.jsx
- test/common/testlib.py
- test/verify/check-packagekit
This addresses some issues that I found while running the tests on the [testing farm](http://artifacts.dev.testing-farm.io/5799e7f1-7fba-4f4b-9f8b-a79ef5ce78a9/) and locally.
> packagekit fixes

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.js
- pkg/kdump/kdump.scss
- pkg/lib/patternfly/patternfly-4-overrides.scss
- test/common/test-functions.js
- test/verify/check-kdump
Main page on master:
Main page on this PR:
location dialog on master:
location dialog on this PR:
mobile location dialog on master:
mobile location dialog on this PR:
> kdump: remove last usages of PF3 and stop including it

- doc/guide/authentication.xml
Spelling correction: primaray to primary
> Spelling correction: primaray to primary

- pkg/storaged/dialog.jsx
We no longer convert the text input into a number immediately on every
change.  That did interfere severely with the user input.  For
example, it was impossible to type a decimal point "." at the end of
the text because it would immediately be removed again when converting
the text to a number and back again.
Instead, textual input is converted to a final number in the validate
function.
Fixes #15409
> storage: Improve size slider text input

- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
> packagekit: fix alignment issues on smaller screens

- src/bridge/cockpitconnect.c
- src/common/test-json.c
- src/common/test-jsonfds.c
- src/websocket/websocketserver.c
- src/ws/cockpitcertificate.c
- src/ws/cockpitwebservice.c
- src/ws/session-utils.c
- src/ws/test-kerberos.c
https://bugzilla.redhat.com/show_bug.cgi?id=1938693
> Fix coverity issues

- pkg/lib/machine-info.js
- pkg/systemd/hw-detect.js
- test/verify/check-system-info
> systemd: Fix CPU name parsing on PowerPC, hw info code cleanup

- test/verify/check-machines-disks
Related with: https://bugzilla.redhat.com/show_bug.cgi?id=1792379
> test: add the check which is the dialog can be closed correctly

- pkg/apps/utils.jsx
- pkg/kdump/kdump-view.jsx
- pkg/lib/cockpit-components-empty-state.jsx
- pkg/machines/components/vm/disks/diskAdd.jsx
- pkg/storaged/content-views.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/side-panel.jsx
- pkg/systemd/reporting.jsx
> pf4: Switch spinners to SVG

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.scss
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/networking.scss
- pkg/selinux/setroubleshoot-view.jsx
- pkg/selinux/setroubleshoot.scss
- test/verify/check-kdump
Fixes #15511
Redesigned as requested in https://github.com/cockpit-project/cockpit/issues/15511#issuecomment-799502949
> kdump: redesign to match the styling of other pages

- configure.ac
- src/bridge/Makefile.am
Fixes #14052
I tested this with all six combinations -- auto (no argument), `--enable-polkit`, `--disable-polkit`, with and without polkit-devel installed.
> build: Fix polkit detection

- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/cockpit-components-shutdown.scss
- pkg/lib/timepicker-helpers.js
- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
- test/verify/check-system-shutdown-restart
> packagekit: lib: use TimePicker component from PF4

- test/README.md
- test/common/testlib.py
- test/verify/check-connection
- test/verify/check-machines-create
- test/verify/check-static-login
- test/verify/check-storage-resize
- test/verify/check-storage-vdo
- test/verify/check-system-info
- test/verify/check-system-journal
Image added in https://github.com/cockpit-project/bots/pull/1859
> test: Add special cases for rhel-9-0

- containers/bastion/cockpit-auth-ssh-key
- pkg/apps/watch-appstream.py
- pkg/base1/cockpit.js
- pkg/lib/inotify.py
- pkg/machines/components/create-vm-dialog/autoDetectOS.py
- pkg/machines/getOSList.py
- pkg/packagekit/callTracer.py
- pkg/storaged/luksmeta-monitor-hack.py
- pkg/storaged/nfs-mounts.py
- pkg/storaged/vdo-monitor.py
- src/bridge/cockpitcgroupsamples.c
- src/bridge/cockpitstream.c
- src/common/cockpitbase64.c
- tools/tap-driver
- tools/test-static-code
- tools/title2sentence.py
- tools/webpack-make
- webpack.config.js
Let's play around a bit with LGTM over the weekend...
https://lgtm.com/projects/g/cockpit-project/cockpit/
> first round of LGTM fixes

- test/verify/check-metrics
- test/verify/check-shell-keys
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-storage-luks
- test/verify/check-storage-resize
These provide better log when they fail.
For example `assert (size > 300000)` provides:
```
assert (size > 300000)
AssertionError
```
while `assertGreater(size, 300000) provides:
```
assert (size > 300000)
AssertionError: 1 is not greater than 300000
```
I only kept `assert False, <reason>`.
> test: Use unittest assert methods

- test/verify/check-packagekit
Fixes https://github.com/cockpit-project/bots/pull/1861
> test: Centos-8-stream now has tracer

- test/verify/check-packagekit
Cherry-picked from master commit 6543215.
> [84] test: Centos-8-stream now has tracer

- pkg/lib/cockpit-components-table.scss
- pkg/lib/ct-card.scss
- pkg/lib/listing.scss
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/metrics/metrics.scss
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/network-main.jsx
- pkg/networkmanager/networking.scss
- pkg/packagekit/updates.scss
- pkg/storaged/storage.scss
Related issue: https://github.com/patternfly/patternfly/issues/3959
> Some custom CSS cleanup act

- .eslintrc.json
- pkg/lib/page.scss
- pkg/networkmanager/interfaces.js
- pkg/selinux/setroubleshoot-view.jsx
- pkg/shell/index.html
- pkg/shell/shell-modals.jsx
- pkg/shell/shell.scss
- test/verify/check-apps
- test/verify/check-pages
> shell: use pf4 Menu component for the display language list

- src/bridge/bridge.c
- src/bridge/cockpitpeer.c
- src/common/Makefile-common.am
- src/common/cockpitfdpassing.c
- src/common/cockpitfdpassing.h
- src/common/test-jsonfds.c
- src/tls/connection.c
So far this is pretty useless, but it will allow us to use the stderr fd to reliably communicate with sudo, without side-effects.
> proof of concept: pass stderr via socket to the privilged helper

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/ct-card.scss
- pkg/storaged/optional-panel.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/storage.scss
> lib: some improvements on the empty state patterns in tables

- pkg/lib/cockpit-components-install-dialog.jsx
- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
- test/verify/packagelib.py
> Restyle updates to have status and settings cards

- test/common/testlib.py
Otherwise the last few journal messages of the current test might leak
into the next and wrongly be considered as part of it.
Fixes #15544
> test: Wait for session termination before the next non-destructive test

- pkg/lib/patternfly/patternfly-4-overrides.scss
> lib: add patternfly override for misaligned card actions

- pkg/systemd/overview.jsx
- pkg/systemd/overview.scss
- test/verify/check-static-login
Since this is part of grid it would create empty slots.
Fixes #15738
> overview: Don't render empty elements

- pkg/base1/test-utf8.js
- tools/debian/copyright.template
> Update link to Apache license

- src/tls/certificate.c
- src/tls/cockpit-certificate-helper.in
@allisonkarlitskaya WDYT about these changes?
> Fix two coverity errors (mm edition)

- pkg/packagekit/autoupdates.jsx
- test/verify/check-packagekit
> packagekit: Fix automatic updates config

- test/make_dist.py
The tar timestamp workaround from commit cf04588de554 with only touching
webpacks, but not node_modules/ and package-lock.json was completely
flawed: This would only work on an already existing cockpit.git
checkout, but not on any clone that happened after building the dist
cache.
So we have to touch all the files, which also simplifies the code quite
a bit.
To work around the `tar --touch` bug, add a sleep to ensure that the
unpacked files are at least one second apart. This is a giant hack of
course, but let's unbreak our CI and investigate this in an orderly
fashion.
-----
Fixes failures like [this](https://logs.cockpit-project.org/logs/pull-1980-20210503-111056-aa04ab54-ubuntu-stable-cockpit-project-cockpit/log.html).
I'm terribly sorry for the thinko!
I deliberately make this …
> test: Quick-fix dist tarball unpacking

- pkg/lib/cockpit-components-dialog.jsx
- pkg/lib/cockpit-components-shutdown.jsx
- pkg/networkmanager/firewall.jsx
- pkg/packagekit/autoupdates.jsx
- pkg/storaged/dialog.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/services/timer-dialog.jsx
- pkg/users/account-create-dialog.js
- pkg/users/account-details.js
- pkg/users/expiration-dialogs.js
- pkg/users/password-dialogs.js
Previously, it would reload the page.
> storaged: Apply a dialog when its form is submitted

- test/common/link-patterns.json
- test/common/pixel-tests
- test/common/pixeldiff.html
- test/common/test-functions.js
- test/common/testlib.py
See https://github.com/cockpit-project/starter-kit/pull/433 for some actual action.
> test: Add support for pixel testing

- test/verify/check-connection
- tools/cockpit.spec
Follow-up from https://github.com/cockpit-project/cockpit/pull/15784#pullrequestreview-651965021
> Fix rpm validation errors

- tools/node-modules
This got accidentally duplicated in rebasing.
> tools/node-modules: drop a duplicate section

- pkg/lib/cockpit-components-dialog.jsx
- pkg/users/account-details.js
- pkg/users/expiration-dialogs.js
- pkg/users/users.scss
- test/verify/check-users
Fixes https://github.com/cockpit-project/cockpit/issues/15821
Fixes https://github.com/cockpit-project/cockpit/issues/15794
> users: Improve account lock and expire dialogs

- pkg/packagekit/updates.jsx
> packagekit: fix some react warnings

- .github/workflows/reposchutz.yml
Ensure that we explicitly ack changes to .github/ by way of setting a
label.
> .github: add workflow to spot .github/ changes

- test/common/testlib.py
- test/verify/check-testlib
...and add a small test to make sure we're getting reasonable values.
> testlib: implement system_before() on Debian

- pkg/storaged/clevis-luks-passphrase.sh
- test/verify/check-storage-luks
> test: Run TestStorageLuks.testClevis also on the Debians

- tools/cockpit.spec
> packagekit: Require polkit

- pkg/lib/packagekit.js
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/packagekit/updates.jsx
> Update url redirects

- pkg/packagekit/autoupdates.jsx
https://bugzilla.redhat.com/show_bug.cgi?id=1964177
----
"every day" still had some old translations, so this works now:
The others don't yet have msgids, and thus are not translated yet, but at least can be with this fix.
> packagekit: Translate automatic updates frequency

- pkg/storaged/storage.scss
Fixes the scrollbar issue introduced in https://github.com/cockpit-project/cockpit/pull/15844
> storage: Fix scrollbar issue; change pre display

- pkg/storaged/fsys-panel.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/storage-controls.jsx
> storage: Add aria-label for usage bars

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
> Small metrics fixes

- test/verify/packagelib.py
The libvirtd code path was incomplete: It's not enough to start
libvirtd, it would also need to ensure that the `default` network is
actually up.
However, we don't actually need this any more -- just adding a dummy
connection works on all Debian/Ubuntus, so let's simplify this. On the
Fedora family this is not necessary at all, as NM already manages the
main interface there.
----
This should fix a common [flake on debian-stable](https://logs.cockpit-project.org/logs/pull-15812-20210531-080229-aeb4f086-debian-stable/log.html). I am not 100% sure yet if we also need this on Testing Farm machines, hence starting out as draft.
> test: Fix PackageCase NetworkManager setup

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/systemd/services/services-list.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/services.scss
- test/verify/check-system-services
Fixes #15797
Fixes #15798
Fixes #15796
> SPUR: services: Improve UI in the main services page

- pkg/lib/cockpit-components-table.scss
- pkg/lib/patternfly/patternfly-4-overrides.scss
> lib: Update redirected links

- test/verify/storagelib.py
Removing it early breaks newer LVM2 versions, see
https://bugzilla.redhat.com/show_bug.cgi?id=1969408
> test: Only remove a loopback device file once its done

- pkg/selinux/setroubleshoot-view.jsx
- pkg/selinux/setroubleshoot.js
- test/verify/check-selinux
Spotted in/blocking https://github.com/cockpit-project/bots/pull/2085
> selinux: Fix broken toast alert, fix tests

- .github/workflows/unit-tests.yml
- test/common/testlib.py
Instead of having all the image specific quirks listed explicitly.
Cherry-picked from master commit f754e5f72dc.
> [r84] test: Call self.machine.allowed_messages in check_journal_messages

- pkg/selinux/setroubleshoot-view.jsx
- test/verify/check-machines-lifecycle
- test/verify/check-machines-settings
- test/verify/check-selinux
- test/verify/machineslib.py
- test/verify/machinesxmls.py
Blocks https://github.com/cockpit-project/bots/pull/2104
> [r84] check-selinux fixes

- pkg/systemd/services/service-details.jsx
- test/verify/check-system-services
> Service details page improvements (SPUR)

- .gitmodules
- autogen.sh
- test/README.md
- test/run
- test/verify/check-networkmanager-firewall
And init test/reference external repository.
> networking: Add first pixel tests :rocket: 

- packit.yaml
According to the packit team, we should be able to merge this next Monday.
Doing the PR now so that it doesn't fall off my radar.
> Revert "packit: add some fake docs as a temporary hack"

- pkg/apps/application-list.jsx
- pkg/apps/application.css
- pkg/apps/application.jsx
- pkg/apps/index.html
- pkg/apps/index.jsx
- pkg/apps/utils.jsx
- test/verify/check-apps
This fixes multiple alignment and spacing issues and makes the page
consistent in design patterns with all other pages.
Also follow the Card based design approach like all other pages for
consistency.
Fixes #15964
Disclaimer:  This is fixing multiple issues on the page - not all - let's make a SPUR for being extra picky here in the future
Main page before
-----------------------
Main page after
---------------------
Details page before
--------------------------
Details page after
------------------------
> apps: Use PF4 components for the page layout

- packit.yaml
This has been pretty consistently red lately, for reasons outside of our
control.  Take it out of the list for now so that we don't get too used
to merging red PRs.
> packit.yaml: stop testing on rawhide

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
This was the root cause of my woes in https://github.com/cockpit-project/cockpit/pull/15812#issuecomment-849514020 and  https://github.com/cockpit-project/cockpit/pull/16009#issuecomment-870290908  . These are part of #16009, but that may still need some discussions/design iterations -- let's fix these, as they also cause test flakes.
> Two urgent Metrics page fixes

- Makefile.am
- autogen.sh
- configure.ac
- doc/guide/Makefile-guide.am
- test/common/axe.js
- test/common/testlib.py
- tools/gen-spec-dependencies
Take the axe to autogen.sh and replace it with a clean minimalistic rewrite.
> autogen.sh: minimalistic rewrite

- doc/guide/Makefile-guide.am
- src/common/Makefile-common.am
two minor tweaks to dependencies to reduce `make dist` work
> more build cleanup

- containers/ws/README.md
Copying back from changes in
https://github.com/cockpit-project/cockpit-project.github.io/pull/420
> containers/ws: README tweaks

- pkg/lib/timepicker-helpers.js
> lib: Adjust URL to renamed patternfly-react main branch

- pkg/lib/cockpit-components-plot.jsx
- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/timer-dialog-helpers.js
- test/verify/check-system-services
Plots on main:
Plots on this PR:
Timers on main:
Timers on this PR:
> Port Services page and plots from moment to Date/Intl

- Makefile.am
- containers/ws/Dockerfile
- test/README.md
- test/run-verify-host.sh
- test/verify/check-testlib
- tools/cockpituous-release
- tools/debian/adjust-for-release
- tools/make-bots
> various updates for main

- .github/workflows/prune-dist.yml
Successful test run is here: https://github.com/cockpit-project/cockpit/runs/3018284994?check_suite_focus=true
> prune-dist.yml: run in cockpit-dist upload

- pkg/lib/patternfly/patternfly-4-overrides.scss
See #14752
I mostly just wanted to open a PR since it has been a while :)
But also I am wondering, if we want to check redirections for PF repo as they seem to be transferring issues a lot.
> pkg: Update pf url

- package.json
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/test-util.js
- pkg/storaged/utils.js
- test/verify/check-storage-luks
- test/verify/check-system-info
- tools/cockpit.spec
- webpack.config.js
This was the last page to be converted. Drop moment npm dependency, it's
deprecated and we don't want to grow new usage of it.
Fixes #15979
> storaged: Port from moment to timeformat

- pkg/lib/cockpit-components-logs-panel.jsx
- test/verify/check-system-journal
Found this while playing with https://github.com/cockpit-project/cockpit/pull/16091
These two changes were unrelated, so sending separate PR.
> Logs improvements

- test/verify/check-storage-nfs
See https://github.com/systemd/systemd/commit/0a59216
> test: Adjust to new systemd capitalized description

- test/verify/check-system-s4u-ssh
I was looking at that PoC today and trying to understand its details. Here are some simplifications and changes that make it look more like what we want to eventually do. Many thanks to @Gundersanne for your help with this!
> check-system-s4u-ssh improvements

- pkg/systemd/overview-cards/insights.jsx
https://bugzilla.redhat.com/show_bug.cgi?id=1984841
> systemd: Update Insights URLs to console.redhat.com

- src/ws/session.c
The previous dup_string() copied strings containing NUL bytes (and an
explicit length). We don't require that for user or display names, as
they are not allowed to contain NUL bytes, so normal strndup() behaviour
is fine for these.
> ws: Use cockpitmemory allocation functions

- pkg/users/account-details.js
- test/verify/check-users
Locking of not-current account is already tested.
Fixes #16152
> users: Don't allow locking of the current account

- pkg/shell/nav.scss
- pkg/shell/superuser.jsx
- pkg/systemd/overview.scss
- pkg/systemd/superuser-alert.jsx
Fixes #14305.
Changes to the shell and overview alert.
> Make switching to admin access more visible

- src/tls/connection.c
- src/ws/cockpitauth.c
Here's the first few commits from #16000, as requested.  Those should be easy to land.
> non-controverial tls refactoring

- pkg/systemd/reporting.jsx
> abrt: Update url to gnome API

- pkg/shell/index.html
- pkg/shell/nav.scss
It is about 'Session' and not about user.
Fixes #16173
> shell: Change user icon in the top menu

- pkg/storaged/dialog.jsx
> storage: Use HelpIcon and Popover for dialog explanations

- test/common/test-functions.js
- test/common/testlib.py
- test/verify/check-selinux
> more selinux string fixes

- test/run-verify-host.sh
Also see https://github.com/cockpit-project/bots/commit/c7ea7746b3
This is needed for downstream gating
> fmf: Add hack for stuck chpasswd

- pkg/lib/cockpit-components-table.scss
> lib: Update PF link

- test/verify/check-storage-luks
We missed this when merging #13192.
> test: Adapt TestStorageLuks.testReboot for recent changes

- pkg/shell/superuser.jsx
- test/verify/check-superuser
Add a new pixel test for the superuser dialog.
> Utilize PF4 components for the superuser dialog

- pkg/lib/cockpit-components-table.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/selinux/setroubleshoot.js
- test/verify/check-selinux
> selinux: allow bulk deletion of selinux notifications

- packit.yaml
- test/README.md
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-team
- test/verify/check-packagekit
- test/verify/check-static-login
- test/verify/check-storage-unused
- tools/cockpit.spec
> Enable Fedora 35 in packit, drop/clean up Fedora 33 packit/test/doc

- test/README.md
- test/common/cdp.py
- test/common/testlib.py
- test/run
- test/verify/check-metrics
- test/verify/check-packagekit
- test/verify/check-packages
- test/verify/check-pages
- test/verify/check-reauthorize
- test/verify/check-session
- test/verify/check-shell-host-switching
- test/verify/check-shell-keys
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-storage-partitions
- test/verify/check-superuser
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-system-services
- test/verify/check-system-terminal
- test/verify/check-users-roles
Tested locally with: TEST_MOBILE=true TEST_OS=fedora-34 test/verify/check-networkmanager-basic -st TestNetworkingBasic.testBasic
It created a: TestNetworkingBasic-testBasic-network-main-mobile-pixels.png file as expected.
> Introduce tests on mobile screen sizes

- pkg/playground/metrics.js
- pkg/playground/pkgs.js
- pkg/playground/service.js
- pkg/playground/test.js
- pkg/playground/translate.js
This shaves off 1.3 MB from that webpack.
> playground: Port from jQuery to DOM/JS standard API

- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nb_NO.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sk.po
- po/sv.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
PO refresh run: https://github.com/cockpit-project/cockpit/runs/3530259411?check_suite_focus=true
> [rhel-8.5] po: Update from Fedora Weblate

- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nb_NO.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sk.po
- po/sv.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
> [rhel-9.0] po: Update from Fedora Weblate

- po/ca.po
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ko.po
- po/nb_NO.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sk.po
- po/sv.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
From [this workflow run](https://github.com/cockpit-project/cockpit/runs/3542276864?check_suite_focus=true)
> [rhel-8.5] Update translations from Fedora Weblate

- pkg/lib/cockpit-components-listing-panel.scss
- pkg/lib/cockpit-components-table.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/selinux/setroubleshoot.scss
> Fix some selinux page UI issues 

- pkg/networkmanager/network-main.jsx
- pkg/selinux/setroubleshoot-view.jsx
> pkg: Fix usage of `ngettext`

- pkg/lib/cockpit-components-listing-panel.jsx
- pkg/lib/cockpit-components-listing-panel.scss
- pkg/selinux/setroubleshoot.scss
Follow-up to https://github.com/cockpit-project/cockpit/pull/16320
Fixes #16311
> Selinux UI issues

- examples/embed-cockpit/application.html
- test/verify/check-connection
- test/verify/check-embed
- test/verify/files/embed-cockpit/embed.css
- test/verify/files/embed-cockpit/embed.js
- test/verify/files/embed-cockpit/index.html
Split out from #16342, as the full thing still needs reporter feedback and some rework of the unit test.
> various fixes/improvements to testing embedding and reverse proxying

- src/bridge/test-httpstream.c
Comparing the received control message JSON against the expected value
in string form has always been brittle: It assumes a
predictable/reproducible GLib dictionary serialization. This will break
across different GLib versions once we add a new static header.
So change the tests to compare the control message with
`cockpit_assert_json_eq()` (which will do parsing and deep object
comparison) instead of plain string comparison. Introduce a new
assert_channel_response() helper for this.
> bridge: Robust JSON object comparison in test-httpstream.c

- pkg/networkmanager/index.html
- pkg/networkmanager/interfaces.js
> network: Change STP label and group options

- pkg/storaged/client.js
Calling wait() on a proxy with { watch: false } is pointless, it will
resolve immediately.  Instead, waiting on the explicit watch() call
will correctly delay us until all proxies in scope of that watch call
have been initialized.
The manager object has been waited on and checked independently
already before, so we don't have to worry about it being valid in
init_model.
> storage: Wait for the watch during init, not the unwatched proxies

- pkg/storaged/client.js
- pkg/storaged/nfs-panel.jsx
- pkg/storaged/utils.js
- pkg/storaged/vdos-panel.jsx
The data in localStorage is always for the login host.
> storage: Read /etc/os-release from current host

- test/verify/check-kdump
This prepares us for addressing UI fixes with NFS kdumps.
----
> test: Add check-kdump full end-to-end NFS dump test

- pkg/systemd/overview-cards/healthCard.scss
Was part of the last login PR, split up as it's small. Change was suggested by @KKoukiou
> systemd: Use patternfly variables for spacing

- pkg/storaged/block-details.jsx
- pkg/storaged/client.js
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/crypto-panel.jsx
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/details.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/drive-details.jsx
- pkg/storaged/drives-panel.jsx
- pkg/storaged/format-dialog.jsx
- pkg/storaged/fsys-panel.jsx
- pkg/storaged/fsys-tab.jsx
So that we don't mix old and new styles.
> storage: Replace all "var" keywords with "let" or "const"

- pkg/storaged/iscsi-panel.jsx
- pkg/storaged/jobs-panel.jsx
- pkg/storaged/logs-panel.jsx
- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/mdraids-panel.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/nfs-panel.jsx
- pkg/storaged/optional-panel.jsx
- pkg/storaged/others-panel.jsx
- pkg/storaged/part-tab.jsx
- pkg/storaged/plot.jsx
- pkg/storaged/pvol-tabs.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/storage-controls.jsx
- pkg/storaged/swap-tab.jsx
- pkg/storaged/test-util.js
- pkg/storaged/things-panel.jsx
- pkg/storaged/utils.js
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vdos-panel.jsx
- pkg/storaged/vgroup-details.jsx
- pkg/storaged/vgroups-panel.jsx
The previous attempt accidentally missed a lot of files.
> storage: Eliminate "var"

- pkg/base1/cockpit.js
Spotted while I was converting base1 to const/let. So this was useful for something after all :grin:
> Three cockpit.js fixes

- pkg/systemd/overview-cards/realmd-operation.js
- test/verify/check-system-realms
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2006028
> realmd: React on privileges change

- pkg/packagekit/history.jsx
- pkg/packagekit/updates.scss
> packagekit: Improve visuals of updates-history and flow list

- pkg/kdump/config-client.js
- pkg/kdump/kdump-client.js
- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.js
- pkg/kdump/test-config-client.js
- test/verify/check-kdump
https://bugzilla.redhat.com/show_bug.cgi?id=2004041
> kdump: Show "Directory" field for NFS mounts, various bug fixes and cleanups

- test/verify/check-storage-mdraid
I am only testing this if it still fails.
> test: Remove old storage hack

- .github/workflows/weblate-sync-po.yml
- .github/workflows/weblate-sync-pot.yml
- po/Makefile.am
> update po-refresh to use deploy key

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
> metrics: change the URL when changing the date filter

- pkg/sosreport/index.jsx
These were only used for cancelling, but the value of archive_files did
not get determined until `sos report` finished -- but at that point it
can't be cancelled any more. Also, sosreport has not produced .md5 files
for quite some time.
Drop `archive_files`, and fold the remaining piece of sosCancel()
directly into the button handler.
> sosreport: Drop useless tracking of archive_files

- pkg/apps/application-list.jsx
- pkg/apps/application.css
- pkg/apps/application.jsx
- pkg/apps/index.html
- pkg/apps/index.jsx
- pkg/apps/utils.jsx
- test/verify/check-apps
- test/verify/check-sosreport
Empty state:
Before:
Now:
There is an issue with the progress bar in the details page, but this also exists on master.
> apps: fix some small issues and improve the UI

- test/verify/check-static-login
- test/verify/check-storage-nfs
- test/verify/storagelib.py
NFS missing packages pcp message: [example 1](https://logs.cockpit-project.org/logs/pull-16591-20211111-062659-15458191-ubuntu-2004/log.html#202), [example 2](https://logs.cockpit-project.org/logs/pull-2621-20211111-092541-ab8bcc50-ubuntu-2004-cockpit-project-cockpit/log.html#202)
SELinux restricted user: [example 1](https://logs.cockpit-project.org/logs/pull-16592-20211111-081715-d53af45e-fedora-34/log.html#166), [example 2](https://logs.cockpit-project.org/logs/pull-16593-20211111-094553-b657576a-fedora-34/log.html#166)
> Fix two unexpected messages

- pkg/networkmanager/manifest.json
> networkmanager: Update firewall documentation URL

- src/bridge/bridge.c
Port the code for spawning ssh-agent to GSubprocess, merging it with the
(now-very-similar) code for spawning dbus-daemon.
We spawn ssh-agent with -D so that we have better control over its
lifetime.  In particular, the `prctl()` that we were previously doing
had no effect, because without `-D` ssh-agent `fork()`s immediately.
Closing all file descriptors also had no effect because this was already
the default behaviour of `g_spawn_sync()` and is also the default
behaviour of `GSubprocess`.
> bridge: modernise ssh-agent spawning code

- Makefile.am
- configure.ac
- pkg/static/login.js
- src/ws/Makefile-ws.am
- src/ws/cockpit-desktop.in
- test/containers/check-bastion
Let's start discussing underlying changes to the build system, login page, and cockpit-ws to support cockpit-client.
> start merging flatpak

- pkg/static/login.js
- src/ws/cockpitauth.c
- src/ws/cockpithandlers.c
- src/ws/main.c
super secret internal config option to enable lots of unrelated things!
Would also be possible as an envvar.  I don't mind either way.
> X-For-CockpitClient

- src/client/cockpit-client
- src/client/cockpit-client.ui
..and the usual <Ctrl>R accelerator.  <Ctrl><Shift>R does a hard reload,
bypassing caches.
> cockpit-client: add a reload button

- tools/node-modules
Use V=0 by default, as our other similar tools do.
> tools/node-modules: default to "friendly messages"

- pkg/shell/superuser.jsx
> rhel-8-5: Utilize PF4 components for the superuser dialog

- .github/deploy-keys.sh
- .github/workflows/update-flathub.yml
- containers/flatpak/update-flathub
I did this for the 259 release and it resulted in:
- https://github.com/cockpit-project/cockpit/runs/4458153711?check_suite_focus=true
- https://github.com/cockpit-project/org.cockpit_project.CockpitClient/commit/deb285ddee68ea0a2f42cf9cc9984dce98d0abec
I'm going to do a manual fix-up before I PR.
> new workflow for updating flathub

- pkg/shell/shell-modals.jsx
List the installed cockpit packages on Arch Linux.
> shell: Add pacman compatibility to "About web console"

- HACKING.md
- doc/guide/cert-authentication.xml
- pkg/lib/cockpit-components-file-autocomplete.jsx
- pkg/lib/cockpit-components-table.jsx
- pkg/lib/long-running-process.js
- pkg/lib/packagekit.js
- pkg/networkmanager/dialogs-common.jsx
- pkg/networkmanager/networking.scss
- pkg/selinux/setroubleshoot-view.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/timers.scss
- test/common/testlib.py
- test/verify/check-packagekit
- test/verify/check-static-login
- test/verify/check-storage-resize
Running codespell again; inspired by #16727.
> Fix typos and spelling issues found by codespell

- src/client/cockpit-client-ssh
- src/common/cockpitwebserver.c
- tools/termschutz
...all of them for issues I introduced myself :facepalm:
> a few lgtm fixups

- tools/webpack-jumpstart
purely for discussion purposes
> partial jumpstart

- pkg/storaged/client.js
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/format-dialog.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/nfs-mounts.py
- pkg/storaged/storage.scss
- pkg/storaged/stratis-details.jsx
- pkg/storaged/utils.js
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vgroup-details.jsx
- test/common/test-functions.js
- test/common/testlib.py
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-nfs
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-used
- test/verify/check-storage-vdo
New pixels: https://github.com/cockpit-project/pixel-test-reference/compare/792d490ff3cfc7dedf9c1dddb0020c6d44c419ec..1534f778d70a5a75d2dd3167e6c6334568ae0763
Demo: https://www.youtube.com/watch?v=yG_uFDtaRYM
> storage: Improve action summary for dialogs

- pkg/base1/cockpit.js
- pkg/packagekit/updates.jsx
- pkg/shell/hosts_dialog.jsx
- pkg/shell/superuser.jsx
- test/verify/check-packagekit
I have been looking a lot into browser console lately and these nothing-saying warnings were always bothering me. So here I am getting rid of those I saw.
> Quench warnings in console

- HACKING.md
- Makefile.am
- containers/unit-tests/scenario/distcheck
- pkg/lib/inotify.py
- pkg/storaged/vdo-monitor.py
- test/containers/check-bastion
- test/git-hook-pre-push
- test/static-code
- tools/Makefile-tools.am
- tools/escape-to-c
- tools/node-modules
- tools/test-static-code
...and fix a bunch of Python flakes that we were missing before.
> cleanup tools/test-static-code

- test/verify/check-pages
- test/verify/check-system-info
- test/verify/check-system-terminal
This image fixed https://github.com/cockpit-project/bots/issues/2323 and it does not have failing service anymore
> Update reference images for new Fedora image

- containers/flatpak/test/test-browser
- containers/unit-tests/setup.sh
- pkg/storaged/luksmeta-monitor-hack.py
- pkg/storaged/nfs-mounts.py
- src/client/cockpit-client
- test/common/fmf_metadata/cli.py
- test/common/testlib.py
- test/containers/check-bastion
- test/make_dist.py
- test/static-code
- test/verify/check-shell-keys
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-users
- test/verify/storagelib.py
- tools/build-debian-copyright
- tools/min-base-version
- tools/tap-driver
- add vulture to test/static-code
- add it to the unit-tests container
- fix up a bunch of issues that it found
> test/static-code: add vulture to the list of checks

- .gitignore
- selinux/cockpit.te
- src/branding/arch/Makefile.am
- src/branding/centos/Makefile.am
- src/branding/debian/Makefile.am
- src/branding/fedora/Makefile.am
- src/branding/opensuse/Makefile.am
- src/branding/rhel/Makefile.am
- src/branding/scientific/Makefile.am
- src/branding/ubuntu/Makefile.am
- src/common/test-jsonfds.c
- src/systemd/Makefile.am
- test/verify/check-connection
- tools/cockpit.spec
- tools/debian/cockpit-ws.postinst
- tools/make-rpms
As usual, the "uncontroversial" stuff split out from #16839.
> various rpm packaging cleanups

- test/README.md
- test/verify/check-storage-resize
- test/verify/check-storage-vdo
I need this to run some tests first :) Please don't land
> test: Update lists of supported OSes

- pkg/networkmanager/firewall-client.js
- pkg/networkmanager/firewall.jsx
- test/verify/check-networkmanager-firewall
Some UXResearch/general improvements for the firewall page.
---
Custom firewall ports can now include a small description for the system administrator.
> Firewall page improvements

- test/common/testlib.py
> test: Don't allow unused pixel test references

- test/verify/check-packages
- test/verify/check-system-realms
Broken out from PR #16884, these should be harmless.
> Various small test fixes

- test/common/testlib.py
- test/verify/check-storage-used
New references: https://github.com/cockpit-project/pixel-test-reference/compare/a292f9e2799749fe0b99bd662099611d019997f2..bed9ed36da1a31965361ad19c110cb2aef50d95f
> test: Add 1280x768 "medium" layout for pixel tests

- pkg/systemd/overview-cards/healthCard.scss
- pkg/systemd/overview-cards/lastLogin.jsx
- pkg/systemd/page-status.jsx
- pkg/systemd/page-status.scss
Fixes https://github.com/cockpit-project/cockpit/issues/16897
> Improve healthcard spacing

- pkg/networkmanager/firewall-client.js
- pkg/networkmanager/firewall.jsx
- test/verify/check-networkmanager-firewall
Moves away from one of the deprecated end points and some test/code cleanups.
> Firewall improvements II

- pkg/systemd/services/service-details.jsx
- test/verify/check-system-services
> services: Fix user relationships

- test/README.md
- Add more section, so that things are easier to find and link to
- Start with the usual human concern of running a single test. Move the
"run all tests" below and add a caveat -- most developers really
don't want to run the full suite locally.
- Document `TEST_SHOW_BROWSER` instead of the manual approach
- Remove some redundancy.
- Expand the section about iterating fast, in particular with a permanently
running VM.
> test: Documentation updates

- test/common/run-tests
- test/common/testlib.py
- test/verify/check-metrics
- test/verify/check-system-journal
- test/verify/check-testlib
> Various test fixes

- test/common/testlib.py
- test/verify/check-networkmanager-basic
- test/verify/check-session
- test/verify/check-system-services
Again broken out from #16942, to test them in isolation.
In particular the TF fedora-34 fix affects main already, so this should land ASAP.
> Some test fixes

- test/verify/check-metrics
- Blocked on https://github.com/cockpit-project/bots/pull/2930
> TestHistoryMetrics fixes

- pkg/users/account-create-dialog.js
- pkg/users/account-details.js
- pkg/users/account-roles.js
Fixes: #16886
Edit: screenshots
> users: Rename locking in create new account

- pkg/apps/application-list.jsx
- pkg/apps/application.jsx
- pkg/kdump/kdump-view.jsx
- pkg/lib/cockpit-components-firewalld-request.jsx
- pkg/lib/page.scss
- pkg/metrics/metrics.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/network-interface.jsx
- pkg/networkmanager/network-main.jsx
- pkg/packagekit/updates.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/storaged/details.jsx
- pkg/storaged/multipath.jsx
- pkg/storaged/overview.jsx
- pkg/systemd/hwinfo.jsx
- pkg/systemd/logDetails.jsx
- pkg/systemd/logs.jsx
- pkg/systemd/overview.jsx
- pkg/systemd/overview.scss
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services.jsx
- pkg/users/account-details.js
> Adjust the sides of pages in mobile sizes

- pkg/users/account-create-dialog.js
- pkg/users/password-dialogs.js
- test/verify/check-users
> users: Add override button to confirm weak password

- pkg/systemd/services/services.jsx
- test/verify/check-system-services
> Added a link under "Unit not found" to view all services

- pkg/users/account-details.js
Date() has trouble parsing some dates/times; e.g. Firefox 91 and 97:
> new Date('Jan 4 11:52:37 -0500 2022')
Invalid Date
> new Date('Jan 4 11:52:37 +0100 2022')
Date Tue Jan 04 2022 11:52:37 GMT+0100 (Central European Standard Time)
The Date documentation [1] also explicitly discourages using it for
parsing dates if they are not in ISO format (which the above is very
much not).
As `lastlog` has no way of outputting timestamps (or machine readable
output, for that matter), call `date` to convert the date/time string
into a time stamp. However, still keep the JavaScript dissection of the
lastlog string, as cutting out the string does not work at all with
`cut` and `sed`, and is way too complicated with `awk` even.
[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_ …
> users: Call `date` instead of using Date() to parse `lastlog` output

- Makefile.am
- test/common/parent.py
- test/image-prepare
- test/verify/atomiclib.py
- test/vm.install
- tools/cockpit.spec
Backport https://github.com/cockpit-project/cockpit/pull/16935 , so that we can drop the `*.install` files from bots.
- Depends on https://github.com/cockpit-project/bots/pull/2982
> [r7.9] test: Rewrite image-prepare using image-customize

- pkg/systemd/services/services.jsx
- test/verify/check-static-login
- test/verify/check-system-services
> Show when error happens on services page

- tools/cockpituous-release
Point 13 on https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html
> cockpituous: Enable bodhi for Fedora 36

- pkg/lib/page.scss
- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
Addressing https://github.com/cockpit-project/cockpit/issues/16435
Currently a work in progress. I'm trying to keep each change separate, at least for now, in case any are controversial.
The goal is to optimize in several places to make the page better overall on smaller screens (and more optimal on larger screens too).
> metrics: Make better use of space

- package.json
- pkg/lib/cockpit-components-plot.jsx
- pkg/lib/cockpit-components-privileged.jsx
- pkg/lib/serverTime.js
- pkg/metrics/metrics.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/network-interface.jsx
- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.jsx
- pkg/shell/shell-modals.jsx
- pkg/shell/superuser.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/stratis-details.jsx
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vgroup-details.jsx
- pkg/systemd/abrtLog.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/overview-cards/insights.jsx
- pkg/systemd/page-status.jsx
- pkg/systemd/reporting.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/superuser-alert.jsx
- pkg/users/account-details.js
- pkg/users/account-logs-panel.jsx
- pkg/users/accounts-list.js
- pkg/users/authorized-keys-panel.js
- pkg/users/expiration-dialogs.js
- pkg/users/local.js
This will run the checks as part of the unit-test's "distcheck"
scenario.
----
All the issues were fixed yesterday in PR #17066 and #17062.
> package.json: Cover test/common in eslint checks; fix code style for current ESLint version

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
> metrics: Fix link construction for user services

- packit.yaml
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/metrics/metrics.jsx
- pkg/static/login.js
- test/common/firefox-cdp-driver.js
- test/verify/check-metrics
- test/verify/check-system-journal
These are good and low-risk polish for the post dev-freeze RHEL update. This is also the first-ever PR against the new rhel-9.0 branch, so using this to fix tests (if necessary).
> [rhel-9.0] Backport some fixes

- src/bridge/Makefile.am
- src/common/Makefile-common.am
- src/pam-ssh-add/pam-ssh-add.h
- src/ssh/cockpitsshrelay.c
This is some initial split out parts of #17064.
> random build cleanups

- test/verify/check-connection
- test/verify/check-storage-luks
- test/verify/check-storage-stratis
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-services
- Uses https://github.com/cockpit-project/bots/pull/3034
- Requires https://github.com/cockpit-project/bots/pull/3045
> test: Use SSHConnection.reboot() API

- test/verify/check-sosreport
See:
```
test/verify/check-sosreport TestSOS.testBasic
9.23 min
test/verify/check-sosreport TestSOS.testWithUrlRoot
9.23 min
```
https://grafana-frontdoor.apps.ocp.ci.centos.org/d/ci/cockpit-ci?orgId=1&from=now-2d&to=now&viewPanel=34
> sos report test (slow)

- test/common/testlib.py
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-team
- test/verify/check-packagekit
- test/verify/check-pages
- test/verify/check-static-login
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-system-services
- tools/cockpit.spec.in
... and another chance to try our increased CI parallelism from https://github.com/cockpit-project/cockpituous/pull/459
> Test cleanups and fixes

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/page.scss
When new items appear on a page, they are highlighted for a short while to spot them more easily.
> lib: Animate new items in ListingTable

- pkg/networkmanager/firewall-switch.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/networking.scss
- test/verify/check-networkmanager-firewall
Firewall page improvements from https://github.com/cockpit-project/cockpit/issues/9047#issuecomment-1026005844
> Firewalld redesign

- test/common/testlib.py
- test/run-verify-host-user.sh
- test/verify.fmf
- test/verify/check-storage-nfs
This seems to be the last "low hanging fruit".
> Moar nondestructive tests

- test/verify/check-shell-multi-machine
Test CI run, to check if it's really available everywhere.
> test: fips-mode-setup should be avaiable everywhere

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/page.scss
- pkg/storaged/drives-panel.jsx
- pkg/storaged/iscsi-panel.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/mdraids-panel.jsx
- pkg/storaged/others-panel.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/stratis-details.jsx
- pkg/storaged/stratis-panel.jsx
- pkg/storaged/things-panel.jsx
- pkg/storaged/vdos-panel.jsx
- pkg/storaged/vgroup-details.jsx
- pkg/storaged/vgroups-panel.jsx
> storage: Highlight side panel new items

- test/image-prepare
Run cockpit tests offline on Arch Linux.
> test: test Arch Linux offline

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/timer-dialog.jsx
- test/verify/check-system-services
> Check if command exists when creating a systemd timer

- test/verify/check-connection
- test/verify/check-kdump
- test/verify/check-metrics
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-checkpoints
- test/verify/check-packagekit
- test/verify/check-selinux
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-storage-iscsi
- test/verify/check-storage-multipath
- test/verify/check-storage-stratis
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-realms
- Needs https://github.com/cockpit-project/bots/pull/3147
> test: Add special cases for ubuntu-2204

- pkg/storaged/fsys-panel.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-hidden
Fixes #17173
Fixes #14424
Fixes #14008
> storage: Ignore anything mounted like a Canonical "snap"

- test/verify/check-metrics
And update to new aria label.
Needs to land in lockstep with https://github.com/cockpit-project/bots/pull/3153
> test: Enable grafana pcp plugin manually

- pkg/storaged/drive-details.jsx
From:
To:
(With mocked data, my nvme is not that chill :cold_face: :snowflake: )
> storaged: add spacing between smart data

- .github/workflows/flatpak-test.yml
- test/verify/check-metrics
And update to new aria label.
Cherry-picked from main commit 1093d94f9e7f90f.
> [rhel-9.0] test: Enable grafana pcp plugin manually

- .github/workflows/reposchutz.yml
Let's try `pull-requests` instead of `issues`.  Maybe we'll get lucky?
> reposchutz: try again with fixing the permissions

- pkg/storaged/dialog.jsx
> storage: Don't clear dialog errors when setting options etc

- test/static-code
- test/verify/check-networkmanager-firewall
- test/verify/check-pages
- test/verify/check-system-info
- test/verify/check-system-services
- test/verify/packagelib.py
- test/verify/storagelib.py
With that, our test/static-code is getting the same maximum length as cockpit-machines, and we can share the script.
- Builds on top of #16944
> test: Reduce maximum line length to 200

- pkg/networkmanager/firewall.jsx
Check the device's capability using & as some devices capabilities are
of value 11 which makes it show up twice.
Closes #17280
> firewall: filter net devices using a bitmask &

- pkg/lib/dialogs.jsx
- pkg/lib/hooks.js
- pkg/shell/active-pages-modal.jsx
- pkg/shell/base_index.js
- pkg/shell/credentials.jsx
- pkg/shell/index.js
- pkg/shell/indexes.jsx
- pkg/shell/shell-modals.jsx
- pkg/shell/topnav.jsx
This puts the dialog specification close to where it is opened, and
allows the removal of some ceremonial code.
> shell: Use new protocol for TopNav dialogs

- pkg/lib/dialogs.jsx
Man, I was really not paying attention anymore...
> dialogs: Fix example

- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/dialogs.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/overview-cards/cryptoPolicies.jsx
- pkg/systemd/overview-cards/motdCard.jsx
- pkg/systemd/overview-cards/realmd.jsx
- pkg/systemd/overview.jsx
- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/timer-dialog.jsx
> systemd: Use new protocol for dialogs

- pkg/storaged/mdraid-details.jsx
- pkg/storaged/stratis-details.jsx
- pkg/storaged/vdo-details.jsx
Remove please from all confirmation dialogs.
> storaged: remove please from dialogs

- pkg/lib/cockpit-components-firewalld-request.jsx
- pkg/networkmanager/firewall-client.js
Right now checking if it is available everywhere. Then I would migrate few more calls that have `...2` version
> firewall: Use new firewalld methods

- test/common/lcov.py
- test/common/run-tests
https://cockpit-logs.us-east-1.linodeobjects.com/pull-17418-20220602-161656-1dd16e0c-fedora-36-devel/Coverage/work/bots/make-checkout-workdir/github-pr.diff.gcov.html
> test: Code coverage for the PR diff

- test/common/cdp.py
With Firefox 101 the CDP target initialization takes a tad longer, so
that almost all tests fail with "Error: No inspectable targets".
Change the waiting loop to not just check that we can connect to the CDP
port, but that CDP has at least one debug target.
----
This fixes the Firefox test failures in packit on [F36](https://artifacts.dev.testing-farm.io/8e8179a4-068e-4137-9907-ea0650d6d5bc/) and rawhide, as 101 recently landed. This will soon affect Fedora 35 (i.e. our tasks container) as well.
> test: Wait for CDP targets during browser/CDP startup

- containers/bastion/Dockerfile
- containers/ws/Dockerfile
> containers: Bump bastion and ws containers to Fedora 34 -- FIX COMMIT MESSAGE ON MERGING

- .gitignore
Introduced in e2f2d830e1d1597312
> .gitignore: add version.m4

- HACKING.md
Full tests, this validates the new tasks container from https://github.com/cockpit-project/cockpituous/pull/498
> HACKING.md: updates

- pkg/networkmanager/firewall-client.js
- pkg/networkmanager/firewall.jsx
- test/verify/check-networkmanager-firewall
> firewall: Allow editing custom services

- pkg/static/login.css
- src/branding/default/branding.css
> login: Fix overlapped "Connect to:" & alert

- pkg/storaged/content-views.jsx
- test/verify/check-storage-vdo
This approach is copied from `pkg/storaged/fsys-panel.jsx` or `pkg/storaged/fsys-tab.jsx`.
> storage: Listen on changed fs sizes

- test/common/testlib.py
@allisonkarlitskaya  @martinpitt @marusak what do you think of using sphinx for generating documentation of our testlib combined with some documentation on how to set up the tests. The documentation should be aimed for us but mostly for people new to writing tests.
Secondly which docstring format do we go for, the Rst style looks the best in sphinx.
https://realpython.com/documenting-python-code/#docstring-formats
Oh and we might want to make a cockpit theme for sphinx?
> test: document testlib functions (part one of X)

- test/common/run-tests
This will hopefully producer nicer diffs, especially when moving code
blocks around.
Here is a plain diff from #17468.  The gist of the change is to move a block of code from `componentDidUpdate` into `render`, but the diff obscures this quite a bit.
```diff
diff --git a/pkg/shell/topnav.jsx b/pkg/shell/topnav.jsx
index 4c3f278171..4a9d348cb2 100644
--- a/pkg/shell/topnav.jsx
+++ b/pkg/shell/topnav.jsx
@@ -61,8 +61,8 @@ export class TopNav extends React.Component {
osRelease: {},
};
-        this.superuser_connection = cockpit.dbus(null, { bus: "internal", host: props.machine.connection_string });
-        this.superuser = this.superuser_connection.proxy("cockpit.Superuser", "/superuser");
+        this.superuser_connection = null;
+        this.superuser = null;
read_os_release().then(os …
```
> test: Use a "patience" diff for the coverage report

- pkg/kdump/kdump-view.jsx
- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/cockpit.js
- pkg/packagekit/kpatch.jsx
- pkg/shell/hosts_dialog.jsx
- pkg/shell/indexes.jsx
- pkg/shell/topnav.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/format-dialog.jsx
- pkg/systemd/logsJournal.jsx
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services.jsx
This PR fixes a bunch of warnings generated by LGTM and accumulated over the years https://lgtm.com/projects/g/cockpit-project/cockpit/alerts/?mode=list&severity=warning&lang=javascript
Ideally LGTM would complain instead of turn green in PR's.
> Fix LGTM warnings/errors

- pkg/base1/test-http.js
Using `assert.async()` is a bit dangerous with QUnit: you need to make
sure the `done()` method always gets called.
We have a few cases in our tests that fail when run against the Python
bridge, but don't call `done()`.  Clean those up.
In general, converting the tests to async/await syntax is easier than
trying to sort out the state machines involved here.
> base1: fix some test-http asserts

- .stylelintrc.json
- pkg/lib/ct-card.scss
- pkg/lib/table.css
- pkg/metrics/metrics.scss
- pkg/packagekit/updates.scss
- pkg/shell/credentials.scss
- pkg/shell/nav.scss
- pkg/static/login.css
- pkg/storaged/storage.scss
This is the first take of the [auto fixeable](https://github.com/cockpit-project/cockpit/issues/17329#issuecomment-1164754748), should include the most non-controversial rules.
> Enabling stylelint rules take 1

- test/common/testlib.py
Hack to work around out infra issue.
> test: Disable storing of coredump

- test/common/testlib.py
Closes https://github.com/cockpit-project/cockpit/issues/17491
> Python3.11

- pkg/networkmanager/manifest.json
Fixes #17496
I will get in touch with rhel docs team to ask about this. We got promised that they will not break these urls :man_shrugging:
> firewall: Update docs link

- test/common/testlib.py
This makes LSP work nicely in our tests:
Downside is that we have some work todo:
> Add optional static typing for testlib

- pkg/shell/nav.scss
> shell: update PF link to link to it's redirect

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- src/bridge/cockpitcpusamples.c
- src/bridge/cockpitcpusamples.h
- src/bridge/cockpitinternalmetrics.c
- src/bridge/test-metrics.c
- test/verify/check-metrics
> Metrics: Add CPU temperature to metrics page

- pkg/lib/cockpit-components-password.jsx
Setting id of a whole FormGroup will ease referencing it in the tests.
> lib: Set id of PasswordFormFields FormGroup

- test/common/lcov.py
This will help with storing of this value.
> test: Show overall coverage status

- test/browser/browser.sh
> tf: Add hack for sos missing python magic

- doc/protocol.md
> Fix typo in http-stream2

- pkg/networkmanager/manifest.json
https://bugzilla.redhat.com/show_bug.cgi?id=2122111
Fixes ##17679
> networking: Update rhel docs

- pkg/storaged/client.js
- pkg/storaged/dialog.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/mount-users.py
- pkg/storaged/nfs-mounts.py
- test/verify/check-storage-nfs
Finding and stopping processes that use a mount point started out as a
feature for NFS only but is now used across all of the Storage page.
Let's reflect that in the code.
> storage: Refactor mount user handling

- pkg/networkmanager/manifest.json
This reverts commit bf456a0e206622af63de1b31b709b6cd49067d95.
See https://bugzilla.redhat.com/show_bug.cgi?id=2122111
> Revert "networking: Update rhel docs"

- src/Makefile.am
- test/run
SCNR!
- https://github.com/cockpit-project/bots/pull/3812
> test/run: Add scenario for running integration tests with the Python bridge

- src/cockpit/channel.py
We add a function called run_wrapper() to catch ChannelError from the run() function and turn it into a close() message.
It would be more elegant to handle this by setting a done callback on the task and calling .result() from it in order to re-raise and catch the exception.  Unfortunately, there are some non-ChannelError exceptions being raised in our code right now, and they're currently being ignored, and this change would result in them being re-raised.  We can address that in a future PR.
> python: support ChannelError from AsyncChannel.run()

- src/Makefile.am
- src/cockpit/channels/__init__.py
- src/cockpit/channels/metrics.py
- src/cockpit/samples.py
This only implements the overview page metrics, so let's make incremental changes for the other metric types.
> python: metrics1 channel

- containers/unit-tests/setup.sh
Required for my bots PR https://github.com/cockpit-project/bots/pull/3735
Blocked on PR #17785
> containers: add mypy to the unit-test container

- pkg/base1/test-metrics.js
- src/cockpit/channels/metrics.py
After this PR, the cockpit-bridge and Python bridge should be somewhat consistent in error handling
> metric1 unit tests

- src/cockpit/samples.py
For RHEL 8 we still need to support CGroups v1, this was tested seperate of the cockpit-bridge as the bridge currently does not run on Python 3.6 due to the usage of walrus operators.
> python: add CGroups v1 support

- src/cockpit/samples.py
This brings the Python bridge internal metrics support up to date with the C bridge.
> python: support 'disk.dev.{read,written}' metrics

- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
Without this change users cannot open links in the descriptions.
> Packagekit description links

- src/cockpit/channel.py
- src/cockpit/protocol.py
- src/cockpit/router.py
- src/cockpit/transports.py
These are the trivial/non-controversial bits split out from #17851.
> a few minor fixes

- pkg/systemd/overview.jsx
Change separated out of https://github.com/cockpit-project/cockpit/pull/17319 so we only have one pixel test update in the PR
> overview: Fix split button variant

- pkg/base1/test-chan.js
The "filter message in" qunit test in test-chan.html fails periodically due to a race.  The source of this race is a workaround that was added in 66e283fd78f4e05c24ce803050eafac676b861d6:
// HACK: send the reply asynchronously, so that mock_peer addEventListener() gets to see it before our own onrecv()
window.setTimeout(() => self.send(null, JSON.stringify(reply), 0));
Unfortunately, this hack was only applied to the control messages, and not data.  This meant that for our "filter message in" test case, for example, we'd usually see the "one" "two" "three" data messages echoed back to us immediately — and terminate the test — before receiving the "ready" control message.
Every now and then, due to timing, we'd get the extra "ready" control message, though, and get an error looking like: …
> tests: fix periodic test-chan.html failure

- .github/workflows/unit-tests.yml
- HACKING.md
- pkg/base1/test-echo.js
- pkg/base1/test-http.js
- pyproject.toml
- src/Makefile.am
- src/ws/test-server.c
- test/pytest/test_browser.py
> Unify python testing, get qunit tests under coveragepy

- pkg/lib/cockpit-components-modifications.jsx
- pkg/lib/timeformat.js
> Update redirected urls

- .github/codeql-config.yml
- src/cockpit/bridge.py
- src/cockpit/channel.py
- src/cockpit/channels/metrics.py
- src/cockpit/channels/packages.py
- src/cockpit/channels/trivial.py
- src/cockpit/internal_endpoints.py
- src/cockpit/peer.py
- src/cockpit/protocol.py
- src/cockpit/remote.py
- src/cockpit/router.py
- src/systemd_ctypes
- test/pytest/test_bridge.py
This is some initial work for landing the peer bridge stuff.  Let's start getting it checked out in advance.
> python: Core classes rework

- pkg/shell/nav.jsx
- pkg/shell/topnav.jsx
- test/verify/check-shell-menu
Explanation of the commit message in inline comment. For more info on this HACK please read https://github.com/wellyshen/react-cool-onclickoutside/blob/master/README.md#detecting-iframe-clicks
Fixes #17944
> shell: fix open state toggling of the dropdowns on the shell

- src/cockpit/bridge.py
- src/cockpit/buffered.pyfragment
- src/cockpit/channel.py
- src/cockpit/channels/http.py
- src/cockpit/packages.py
- src/cockpit/protocol.py
- change quoting to `"""` instead of `'''`
- disable debug output by default
> two small python tweaks

- src/cockpit/channel.py
- src/cockpit/transports.py
- test/pytest/test_transport.py
#17962 is starting to get too big again.  Let's merge some of the more obvious bits of it.
> python: prep work for superuser bridge

- src/cockpit/bridge.py
- src/cockpit/channels/dbus.py
- src/cockpit/internal_endpoints.py
- src/cockpit/protocol.py
- src/cockpit/router.py
- test/pytest/test_bridge.py
#17962 got too big, yet again.  More "non-controversial" stuff to review first.
> Some more peer prep patches

- doc/guide/cockpit-util.xml
Commit 5fecb13dd2c changed the defaults from base-2 to base-10, but forgot to adjust the documentation.
---
Thanks to @jkonecny12 for reporting!
> doc: Fix factor default in cockpit.format_*()

- pkg/lib/cockpit-po-plugin.js
- pkg/lib/cockpit.js
- pkg/shell/base_index.js
- pkg/shell/indexes.jsx
- pkg/static/login.js
- test/verify/check-pages
Addresses #14058
Much more work is needed to fix the UI everywhere, but this is a start.
> shell: Add basic language RTL support

- pkg/shell/base_index.js
- test/verify/check-system-services
> shell: setDarkMode also when updating existing frames

- pkg/users/accounts-list.js
> Accounts fixes

- pkg/tuned/dialog.jsx
> tuned: fixed typo in exception

- pkg/systemd/logs.jsx
> systemd: correct copy to 'keyboard' to 'clipboard'

- pkg/users/accounts-list.js
> users: fix display of the groups view

- pkg/base1/test-dbus-common.js
- src/cockpit/channels/dbus.py
> python: Assorted D-Bus fixes

- pkg/lib/timeformat.js
- pkg/systemd/services/services.jsx
- test/verify/check-packagekit
- test/verify/check-static-login
Various test and code fixes spotted by running with the pybridge scenario, broken out from PR #18039
> Various fixes

- src/cockpit/transports.py
There are a lot of reasons why we might get an exception when trying to read or write on a transport (for example: ECONNRESET), and pretty much all of those should be treated as a disconnection of the transport.
Previously we handled EPIPE on write() — expand handling to all OSError types, and also on read.
> python: better exception handling in Transport code

- test/common/testlib.py
These might result in spurious failures in slower environments.
> test: Warn about waits that get close to their timeout

- src/cockpit/bridge.py
- src/cockpit/packages.py
- test/verify/check-packagekit
- test/verify/check-static-login
- test/verify/check-system-info
- test/verify/check-system-realms
Moar fixes split out from #18039
> Two pybridge fixes, fix some test flakes

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
> metrics: use standard patternfly component for the metrics page heading labels

- pkg/base1/test-dbus-common.js
- pkg/base1/test-dbus.js
- src/cockpit/channel.py
- src/cockpit/channels/dbus.py
- test/verify/check-metrics
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-checkpoints
- test/verify/check-networkmanager-firewall
- test/verify/check-networkmanager-mac
- test/verify/check-networkmanager-mtu
- test/verify/check-networkmanager-team
- test/verify/check-networkmanager-unmanaged
- test/verify/check-networkmanager-vlan
- test/verify/check-packagekit
- test/verify/check-storage-stratis
- test/verify/check-system-realms
> python: Track name owner for dbus channel

- pkg/lib/patternfly/patternfly-4-overrides.scss
> lib: fix tables in modals in dark mode

- tools/cockpit.spec
see https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
> Migrate to SPDX license

- src/cockpit/config.py
- src/cockpit/packages.py
- test/verify/check-apps
- test/verify/check-kdump
- test/verify/check-storage-nfs
- test/verify/check-storage-stratis
& stop using an external dependency for version parsing
> add manifest overrides

- pkg/systemd/services/services.jsx
- test/verify/check-system-services
> services: reflect filters also in the URL

- src/cockpit/channels/dbus.py
- test/pytest/test_bridge.py
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-other
- test/verify/check-networkmanager-settings
- test/verify/check-networkmanager-team
> python: Signal improvements

- pkg/shell/nav.jsx
> shell: fix proptypes warning in CockpitNav component

- .github/workflows/release.yml
Similar to https://github.com/cockpit-project/bots/pull/4224
> workflows: Pacify git's permission check in release workflow

- src/cockpit/bridge.py
- src/cockpit/channels/stream.py
- src/cockpit/peer.py
- src/cockpit/protocol.py
- src/cockpit/superuser.py
- src/cockpit/transports.py
- test/common/testlib.py
- test/pytest/test_bridge.py
- test/pytest/test_transport.py
- test/verify/check-superuser
This is a UI improvement and should also result fewer error messages landing in the journal.
> python: Collect and report error messages from sudo.

- pkg/shell/nav.scss
> nav: Force long usernames and hostnames to wrap

- pkg/users/account-logs-panel.jsx
- pkg/users/local.js
Using `[]` as "uninitialized" state for `logins` caused the useEffect() to run in an endless loop, calling `last` hundreds of times per second. It's legal for a user to not have any recent logins, in which case the effect would call `setLogins([])`, and re-triggering itself.
> users: Fix calling `last` in endless loop, fix crash on lastlog failure

- pkg/lib/cockpit-components-table.jsx
React will complain about this.
> lib: Don't use "undefined" as column key with ListingTable

- pkg/base1/test-file.js
... what one does in sleepless nights to wear out :brain: :grin:
> base1: Port test-file.js QUnit tests to async functions

- src/cockpit/print.py
This is useful for debugging the bridge (either C or Python).
Start exploring:
```
PYTHONPATH=src python3 -m cockpit.print help
```
> python: add cockpit.print helper module

- pkg/lib/cockpit-po-plugin.js
- src/cockpit/packages.py
- test/pytest/test_packages.py
- test/verify/check-apps
- test/verify/check-metrics
- test/verify/check-pages
- webpack.config.js
> python: (temporarily) send */po.js along with /manifests.js

- pkg/Makefile.am
- pkg/networkmanager/org.cockpit-project.cockpit-networkmanager.metainfo.xml.in
- tools/cockpit.spec
- tools/debian/cockpit-networkmanager.install
- tools/debian/control
> networkmanager: ship appstream xml file

- src/cockpit/bridge.py
- src/cockpit/channel.py
- src/cockpit/channels/stream.py
- src/cockpit/packages.py
- src/cockpit/peer.py
- src/cockpit/router.py
- src/cockpit/superuser.py
- src/cockpit/transports.py
- test/pytest/test_bridge.py
- test/verify/check-metrics
- test/verify/check-pages
This was easy and fun.   Let's hope it works :sweat_smile:
> add support for non-superuser peers from manifest.json files

- pyproject.toml
- src/cockpit/channels/packages.py
- src/cockpit/data/fail.html
- src/cockpit/packages.py
- test/common/testlib.py
- test/verify/check-connection
- test/verify/check-superuser
My take on  #18243.
...plus a couple of fixes to get `check-connection` all-green.
> Packages webserver error handling improvements

- test/common/storagelib.py
On current CentOS 8 Stream, this fails on all kinds of timeouts and 
ENOSPC. Make this more robust:
* `cryptsetup luksFormat` uses oodles of RAM by default for its PBKDF
function. Limit it to at most 300 kB. 
* Increase the /new-boot size partition to 500 MB, as 300 MB is too 
small for recent RHEL 8.
* Exclude /new-root from tar to avoid recursive file inclusion.
* Add `-set -x` for easier interactive debugging what exact command is
hanging at the moment. Splitting the script is not easy, as it
defines several variables which are being used throughout the script,
but that already helps.
----
This fixes https://github.com/cockpit-project/bots/pull/4320.
> test: Robustify encrypt_root()

- pkg/systemd/overview-cards/cryptoPolicies.jsx
- test/verify/check-system-info
Support DEFAULT:SHA1, LEGACY:AD-SUPPORT and FIPS:OSPP cryptography polices.
> systemd: support a subset of crypto subpolicies

- test/pytest/test_bridge.py
This get's our coverage up to 90% for channels/metrics.py
> test: add tests for the internal metrics channel

- pkg/users/account-create-dialog.js
- pkg/users/accounts-list.js
- pkg/users/dialog-utils.js
- pkg/users/group-create-dialog.js
- pkg/users/local.js
- test/verify/check-users
The user is required to specify the new group name and optionally they can also choose they group id.
> users: Introduce group create dialog (Splitted out from https://github.com/cockpit-project/cockpit/pull/18136)

- src/cockpit/channels/http.py
If reading the response throws a http.client exception, close the channel with that error message, instead of crashing the thread and letting it log tracebacks. This does not change observable behaviour much, but cleans up unexpected error messages.
---
This will fix the last [podman failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1196-20230202-124820-1dc12492-fedora-37-pybridge/log.html) with the pybridge, see https://github.com/cockpit-project/cockpit-podman/pull/1196
> python: Properly report HTTPExceptions

- pyproject.toml
- src/cockpit/channel.py
- src/cockpit/channels/filesystem.py
- src/cockpit/channels/http.py
- src/cockpit/channels/metrics.py
- src/cockpit/channels/stream.py
- src/cockpit/peer.py
- src/cockpit/print.py
- src/cockpit/samples.py
- src/cockpit/superuser.py
- test/pytest/test_code.py
This reduces `python3 -m mypy src/cockpit` from 95 to 7 errors.
> python: Fix/ignore mypy errors, add mypy to CI

- pyproject.toml
- src/cockpit/askpass.py
- src/cockpit/packages.py
> python: cockpit-askpass

- src/cockpit/bridge.py
- src/cockpit/channels/dbus.py
- src/cockpit/channels/http.py
Split out from PR #18318, these should be the "harmless and obvious" ones.
> Three small python fixes

- src/tls/test-server.c
test-tls-server often fails with
recv_reply: assertion failed (len >= 100): (-1 >= 100)
which is not particularly enlightening. It could be something simple like EINTR, or the timeout loop actually running all the way to the end without ever getting an actual response. Make the failure of both of them more explicit and verbose, and also print errors.
---
I saw [this failure](https://download.eng.bos.redhat.com/brewroot/work/tasks/635/50720635/build.log) several times downstream by now. Let's figure out what this is!
> tls: Make test failures more useful

- src/cockpit/channels/dbus.py
This either needs https://github.com/systemd/systemd/pull/26375 or we need to stop using GDBus in test-server for the direct connection.
> python: Connecting to specific D-Bus addresses

- src/cockpit/channel.py
- src/cockpit/channels/stream.py
- src/cockpit/transports.py
This is my attempt at half of #18340, plus some bonus cleanups.
> python: clean up subprocess signal handling, shutdown

- test/verify/check-system-info
- test/vm.install
Broken out from PR #18318, as they affect all OSes.
> Two test fixes

- test/common/storagelib.py
Running grub2-mkconfig will execute /etc/grub.d/10_linux, which will update /boot/loader/entries with the kernel command line from /etc/default/grub.  On at least rhel-9, /etc/default/grub contains a empty GRUB_CMDLINE_LINUX (while /etc/kernel/cmdline is correct), and grub2-mkconfig would thus clobber the BLS entries.
Concretely, "net.ifnames=0" would be lost, and the inter-VM network 10.111.112.0 would not be available anymore since it has been configured using the old name of the interface.
This has only recently become a actual problem since earlier versions of grub2-mkconfig would only look at BLS entries that match the current machine ID.  Our rhel images have entries like
ffffffffffffffffffffffffffffffff-4.18.0-458.el8.x86_64.conf
that would be missed earlier.  Now all entries are …
> test: Prevent grub2-mkconfig from clobbering BLS entries

- pkg/lib/cockpit-components-file-autocomplete.jsx
- pkg/lib/cockpit-components-shutdown.jsx
- pkg/metrics/metrics.jsx
- pkg/networkmanager/firewall.jsx
- pkg/packagekit/updates.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/shell/hosts_dialog.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/iscsi-panel.jsx
- pkg/systemd/terminal.jsx
When calling setState with this.state the state might have already changed.
This is one of the ~ 70 codeql warnings, split out so we can deal with them more easily. Also hopefully with less re-trying as this touches almost all the tests/packages.
> pkg: fix all potentially inconsistent setState calls

- src/cockpit/askpass.py
- src/cockpit/bridge.py
- src/cockpit/channels/dbus.py
- src/cockpit/polyfills.py
- test/verify/check-storage-stratis
Once upon a time, there was a sad Python version, called by their peers as "3.6". Few features it had, little love it got from developers. Let that ugly duck grow into a beautiful swan, and learn how to run Cockpit!
Split out PRs:
- #18297
- #18320 
- #18321
- #18360
- #18361 obsoleted by #18365
- #18385
- #18380 -- Skipped test instead, to avoid making this a blocker
> pybridge: Back to the past!

- pkg/users/accounts-list.js
- pkg/users/users.scss
- test/common/testlib.py
- test/verify/check-users
> Users page improvements

- test/browser/browser.sh
- test/browser/run-test.sh
- test/verify/check-system-journal
Run the two most useful/important ones, as they are quite expensive.
---
See https://bugzilla.redhat.com/show_bug.cgi?id=2172891#c7
> fmf: Enable ABRT tests on Fedora

- pkg/systemd/services/busnames.js
- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/timer-dialog-helpers.js
- test/verify/check-system-services
Some preparation, split out from #18422
> Services: test fixes and code cleanup

- test/common/storagelib.py
This allows us to get rid of the autorelabel and the need to switch off SELinux during relabeling (which was new for Fedora 38).
> test: Copy SELinux attributes when encrypting the rootfs

- pkg/base1/test-dbus.js
- pkg/lib/cockpit.js
- pkg/lib/machine-info.js
- pkg/lib/serverTime.js
- pkg/lib/service.js
- pkg/networkmanager/interfaces.js
- pkg/storaged/client.js
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/iscsi-panel.jsx
- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/utils.js
This doesn't fix all cockpit.defer()s yet. Some are *really* hard and need API work, and for some others I just ran out of time.
> cockpit.defer cleanup

- pkg/systemd/services/services.jsx
Before it was bogus:
Now it's correct:
```
❱❱❱ systemctl --user list-timers
NEXT                        LEFT       LAST                        PASSED     UNIT                    ACTIVATES                
Wed 2023-03-08 10:34:19 CET 27min left Wed 2023-03-08 09:34:19 CET 32min ago  backup.timer            backup.service
n/a                         n/a        Sat 2023-03-04 07:28:53 CET 4 days ago grub-boot-success.timer grub-boot-success.service
❱❱❱ date
Wed Mar  8 10:06:30 AM CET 2023
```
Fixes #18418
> systemd/services: Read CLOCK_BOOTTIME with Python

- pkg/systemd/services/service.jsx
After cockpit-project/cockpit#18422, I want to address the remaining state handling instabilities like cockpit-project/cockpit#18465. I started with the details page, that's a bit easier to do.
- Goes on top of #18494
> systemd/services: Rewrite Service into a functional component

- HACKING.md
- test/README.md
Emphasize a toolbox-based approach (issue #18460) and working on the web-y parts (as that's what most contributors want to do. I.e. everyone except if your name is Allison :wink: ). This should hopefully address most woes of new GSoC aspirants.
I tested this under Ubuntu 22.04, and toolbox works like a charm!
See https://github.com/martinpitt/cockpit/blob/hacking/HACKING.md for the rendered result.
> HACKING: Emphasize toolbox and webpack-watch workflow

- pkg/systemd/services/services.jsx
Take timer loading out of the critical path in listUnits(). We don't need them for the initial page load. Instead, load them if/when actually showing the Timers tab, and update the page once they are all loaded.
https://issues.redhat.com/browse/COCKPIT-915
> systemd/services: Lazily load timer information

- pkg/users/account-create-dialog.js
- pkg/users/accounts-list.js
- pkg/users/local.js
- pkg/users/parsers.js
Split from https://github.com/cockpit-project/cockpit/pull/18234
> users: General cleanups

- package.json
https://github.com/sass/dart-sass/releases/tag/1.59.3
> Bump sass to fix performance regression

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- test/verify/check-metrics
Split out of https://github.com/cockpit-project/cockpit/pull/18461 to seperate the discussion about the gradient colors from porting to clip-paths.
> metrics: use polygon with clip path instead of svgs

- HACKING.md
I made a few changes in the previous PR and got a little carried away. :wink:
> hacking: Improve used language

- pkg/users/account-details.js
- pkg/users/users.scss
> users: fix text misalignment issue in account overview menu

- test/verify/check-shell-keys
The flakiness might have disappeared...
> test: Pixel test the full shell key dialog

- HACKING.md
See https://github.com/garrett/cockpit/blob/hacking-steps/HACKING.md for rendered preview.
> Hacking steps

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.js
Follow up cleanups keeping it smaller this time :)
> Kdump follow up

- pkg/kdump/kdump-view.jsx
- pkg/lib/cockpit-components-inline-notification.jsx
- test/verify/check-kdump
Previous: (without expandable :) )
New:
> Kdump expendable ModalError

- pkg/systemd/overview-cards/realmd.jsx
- test/verify/check-system-realms
fixes #9772 
Updated label from "Join Domain" to "Install Domain Support"
> systemd: Improve realmd label

- test/verify/check-metrics
To be landed in lockstep with https://github.com/cockpit-project/bots/pull/4542
> tests: update selector to match grafana from the new services image

- pkg/apps/application-list.jsx
- pkg/apps/application.scss
- pkg/apps/utils.jsx
Progress bar text is now on left of bar, bar has inline style and limited width.
This fixes issue #18463.
> pkg/apps: Fix progress bar and cancel button

- pkg/lib/cockpit-components-dialog.jsx
- pkg/metrics/metrics.jsx
- pkg/networkmanager/firewall.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/optional-panel.jsx
- pkg/systemd/services.jsx
Another round of fixes for https://github.com/cockpit-project/cockpit/pull/18423/files
> Codeql cleanups

- pkg/metrics/metrics.scss
n the gradient we don't use 80% but 70% since it takes 10% to actually transcend to the new color.
> metrics: use gradient for marking graph area when load/saturation is over 80% limit

- test/common/lcov.py
They now have sane relative filenames instead of the "webpack://..." URL prefix.
> test: Adapt coverage processing to new esbuild source maps

- test/common/lcov.py
We want to know when this fails.
> test: Don't ignore errors during coverage report generation

- .github/workflows/flatpak-test.yml
- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
- .github/workflows/reposchutz.yml
- .github/workflows/unit-tests.yml
- .github/workflows/urls-check.yml
- .github/workflows/weblate-sync-po.yml
- .github/workflows/weblate-sync-pot.yml
- po/cs.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/he.po
- po/it.po
- po/ja.po
- po/ka.po
- po/ko.po
- po/nb_NO.po
- po/nl.po
- po/pl.po
- po/pt_BR.po
- po/ru.po
- po/sk.po
- po/sv.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
[correct weblate commit](https://github.com/cockpit-project/cockpit-weblate/commit/a988b071335704a83d7dac68c2da91cc42a68893)
The other changes (like flatpak, protection, unit) test themselves here.
> Workflow platform and permission updates

- pkg/lib/cockpit-components-modifications.jsx
- pkg/networkmanager/network-interface-members.jsx
- pkg/networkmanager/network-main.jsx
- pkg/packagekit/updates.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/sosreport/sosreport.jsx
- pkg/storaged/block-details.jsx
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/drive-details.jsx
- pkg/storaged/jobs-panel.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/optional-panel.jsx
- pkg/storaged/stratis-details.jsx
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vgroup-details.jsx
- pkg/systemd/hwinfo.jsx
- pkg/users/account-details.js
- pkg/users/account-logs-panel.jsx
- pkg/users/accounts-list.js
- pkg/users/authorized-keys-panel.js
Cherry-picked out of https://github.com/cockpit-project/cockpit/pull/18739
> all: Use <CardTitle component="h2"... for cards

- pkg/storaged/client.js
- pkg/storaged/manifest.json
- test/verify/check-storage-stratis
> storage: Enable on-demand installation of Stratis on RHEL 9

- pkg/metrics/metrics.jsx
- src/bridge/cockpitdisksamples.c
- src/bridge/cockpitdisksamples.h
- src/bridge/cockpitinternalmetrics.c
- src/bridge/test-metrics.c
- src/cockpit/samples.py
- test/pytest/test_samples.py
- test/verify/check-metrics
> Metrics: Add cgroup disk IO usage

- test/verify/check-metrics
So that we can update it easier.
> test: Relax assumptions about Grafana DOM specifics

- src/cockpit/samples.py
- src/cockpit/superuser.py
- test/common/run-tests
- test/common/testlib.py
- test/verify/check-example
- test/verify/check-testlib
Broken out from PR #18757
Fix [this RHEL 8 runtime bridge crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18758-20230507-065718-5b53fa4a-centos-8-stream-pybridge/log.html#52) and [this unit test failure during package build](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18757-20230505-203053-94cb8c7a-debian-testing-bots-4733/log.html)
> Some pybridge fixes/cleanups

- src/bridge/cockpitwebsocketstream.c
The initial value was not used anywhere in on_socket_connect(). Recent clang now warns about this:
> warning[deadcode.DeadStores]: Value stored to 'problem' during its initialization is never read
Localize a few variables to their time of actual initialization to make this more obvious and robust.
> bridge: Drop unused "problem" initialization

- test/common/storagelib.py
- test/run
- test/verify/check-storage-format
- test/verify/check-storage-luks
- test/verify/check-storage-partitions
This extends and replaces the existing "dnf-copr" scenario.
> test: New "daily" scenario for dnf and udisks2 daily builds

- src/cockpit/channels/dbus.py
We have a 'type' field that we should send back on D-Bus replies — it contains the signature of the reply message.  The only thing which apparently uses it is one of the qunit tests.
ccb21bc97d tried to fix the unit test by returning the originally-passed type (of the *input* arguments) as the type of the return value.  That was enough to fix the test, but only because the test method returned the same arguments as it was passed.
Let's do a better fix: use a slightly lower-level API on systemd_ctypes to get access to the actual reply message.  Use that to send the correct type field for the reply.
> python: fix 'type' field on D-Bus replies

- pkg/lib/cockpit-components-form-helper.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
isHidden and component properties are no longer valid.
> all: fix some usages of FormHelperText

- test/reference-image
> test: Switch pixel tests to fedora-38

- test/common/packagelib.py
Lately tests have been failing to execute pacman -Sy due to a stray lockfile.
> test: cleanup possible leftover pacman lockfile

- doc/guide/feature-machines.xml
- doc/guide/https.xml
- doc/guide/packages.xml
- doc/guide/sso.xml
- doc/man/cockpit-tls.xml
- doc/man/cockpit.conf.xml
- src/cockpit/config.py
- src/cockpit/internal_endpoints.py
- src/cockpit/packages.py
- test/pytest/test_packages.py
- test/verify/check-connection
> Document and test $XDG_CONFIG_DIRS, fix the Python bridge to respect it

- test/common/test-functions.js
- test/common/testlib.py
Experiment for https://github.com/cockpit-project/starter-kit/pull/662
> test: make loading sizzle optional for tests

- .gitmodules
- src/build_backend.py
- src/cockpit/_vendor/bei
- src/cockpit/channels/packages.py
- src/cockpit/data/__init__.py
- src/cockpit/packages.py
- src/cockpit/peer.py
- src/cockpit/superuser.py
- test/pytest/test_peer.py
Split out from https://github.com/cockpit-project/cockpit/pull/18882 by request of @martinpitt 
> Initial review for the first bunch of commits up to (including) "bump ferny version". Feel free to split them out, test, and land them in a separate PR quickly, with possibly the changes below.
> Preparation work for #18882 (Cockpit Client new ssh)

- src/cockpit/transports.py
- test/common/cdp.py
- test/common/ruff.toml
- test/common/run-tests
- test/common/testlib.py
- test/pytest/test_transport.py
- test/verify/check-metrics
- test/verify/check-packagekit
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-storage-mdraid
- test/verify/check-users
- test/verify/ruff.toml
Probably better to split this up in chunks because of test retries. Plus it fixes a CI spotted issue :)
> Ruff toml begone (part 1 of many)

- tools/debian/rules
Fixes the sadness on https://buildd.debian.org/status/logs.php?pkg=cockpit&ver=294-1
> Fix pybridge debian build

- pkg/playground/speed.js
- pkg/systemd/timer-dialog.jsx
- test/common/pixeldiff.html
Let's first test if a pixel test still loads.
> Github code scan fixes

- test/common/cdp.py
- test/common/lcov.py
- test/common/netlib.py
- test/common/ruff.toml
- test/common/storagelib.py
- test/common/testlib.py
- test/verify/check-packagekit
- test/verify/check-shell-multi-machine-key
- test/verify/check-static-login
- test/verify/check-system-realms
- test/verify/ruff.toml
These PR's are getting smaller and smaller. Not 100% confident about the `map` changes let's see how it goes, please verify that coverage did not break.
> Ruff toml begone 5

- pkg/shell/base_index.js
This reverts commit 1bc7ee5d2054a320fcd0d2606ff31dc6f3750d9d.
> shell: inline the forward_command conditional to make it more explicit 

- test/common/testlib.py
Commit 2cfcdacee ("Create attachments and sit before cleanup handlers") accomplished its goal by monkeypatching some deep internals of unittest.
Instead of trying to monkeypatch unittest, handle attachments and sit() from from tearDown(). It also gets called before cleanups, and we already have similar failure-checking code present there for us to use.
Update from Martin Pitt: The first attempt was reverted in commit 94369d95bee1 as it did not print tracebacks properly, which broke both `--sit` mode (not showing the error) and naughty matching (as they match on the traceback). To fix that, change the boolean checkSuccess() to getError() which returns traceback object if there was any error. tearDown() can use that to print the error before calling the cleanup handlers.
---
I tested this …
> testlib: change approach for --sit and log captures, take two

- src/cockpit/superuser.py
When the superuser bridge gets auto-started via the init message or the
integration tests, it can happen that packages get reloaded while the
superuser bridge already runs, but is still initializing. At that point,
`self.current` is still "init", and once packages finished loading,
set_config() stopped that "init" bridge as it is not decleared by the
manifests (usually "sudo" and "pkexec"). That led to the session
sometimes not being privileged.
This was particularly prone to happen in the "devel" scenario where the
packages are much larger and processing took much longer.
We need to keep the "init" phase for correct error tracking, and that
value is also recognized by the shell to hide the indicator. Avoid
the race by remembering the current peer name separately as a new member
of …
> pybridge: Fix superuser startup vs. package reloading race

- src/cockpit/samples.py
This can fail with "OSError: [Errno 19] No such device" for cgroups that disappear underneath us.
---
Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19041-20230629-152605-f1fca553-debian-testing-other/log.html#57) -- metrics, the gift that keeps on giving! :wink:
> pybridge: Ignore read errors from cgroup metrics

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
> metrics: Merge average and top progress bars

- examples/long-running-process/index.js
- examples/pinger/pinger.js
- examples/xhr-proxy/xhrproxy.js
- examples/zoner/tz.html
- pkg/base1/test-dbus-framed.js
- pkg/base1/test-framed-cache.js
- pkg/base1/test-framed.js
- pkg/playground/speed.js
- pkg/playground/test.js
- pkg/users/users.js
These were some findings from evaluating https://semgrep.dev
> users: Fix "user is locked" detection; pkg, examples: Avoid assigning .innerHTML

- pkg/lib/cockpit-components-logs-panel.jsx
- pkg/sosreport/sosreport.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/storage-controls.jsx
- pkg/users/account-details.js
trying to solve this good first issue 
https://github.com/cockpit-project/cockpit/issues/19061
> onKeyPress is replaced with onKeyDown

- src/cockpit/channels/packages.py
Don't synchronously send the whole document in a single channel data
block. They are often quite large (especially in `NODE_ENV=development`
mode, but even in production). The synchronous send_data() blocked the
bridge for too long, broke flow control, and stalled parallel package
channel downloads for too long. That often led to
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
browser errors.
This got aggravated a lot when going through cockpit-ssh (as it happens
on our OSTree images with the cockpit/ws container), but even
occasionally happened with the standard setup.
Send them in 4K blocks instead, like the C bridge does. Use the same
threading approach as our http-stream2 channel to avoid blocking.
> pybridge: Asynchronously send package files in chunks

- pkg/networkmanager/network-interface.jsx
- test/verify/check-networkmanager-basic
Closes: #19019
---
It now looks as following:
> networkmanager: add pixel test for edit checkboxes

- tools/node-modules
> tools: don't parse --force as valid SHA

- pkg/networkmanager/mtu.jsx
> network: fix MTU dialog error in Automatic mode

- test/verify/check-networkmanager-mtu
And with that we have 100% test coverage of the MTU dialog
> test: add test for Automatic or wrong MTU values

- pkg/storaged/details.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/vdo-details.jsx
And put them each in their own StackItem and Card, for proper padding and borders.
Before:
After:
> storage: Allow multiple alerts on details page

- test/README.md
Explain the pixel tests architecture, add examples and include some pixel test contributor notes.
> test: expand the pixel tests section

- pkg/shell/superuser.jsx
- pkg/shell/topnav.jsx
Otherwise the proxy ends up being permanently invalid.
> shell: Create superuser proxy only when connected to the machine

- pkg/lib/DynamicListForm.jsx
- pkg/lib/DynamicListForm.scss
This component originates from cockpit-podman. I plan to also use it in cockpit-machines, therefore moving it to /pkg/lib
> lib: Add DynamicListForm to /pkg/lib

- src/client/cockpit-beiboot
- src/cockpit/bridge.py
- src/cockpit/channel.py
- src/cockpit/channels/filesystem.py
- src/cockpit/channels/packages.py
- src/cockpit/channels/stream.py
- src/cockpit/jsonutil.py
- src/cockpit/packages.py
- src/cockpit/peer.py
- src/cockpit/protocol.py
- src/cockpit/remote.py
- src/cockpit/router.py
- src/cockpit/superuser.py
- src/cockpit/transports.py
- test/pytest/mocktransport.py
- test/pytest/test_bridge.py
- test/pytest/test_packages.py
- test/pytest/test_peer.py
- test/pytest/test_transport.py
The recent work on the packages code introduced a nice set of static type hints for JSON.  Let's expand those to be used in other places, as well.
> expand use of accurate JSON type hints

- pkg/storaged/content-views.jsx
- pkg/storaged/stratis-details.jsx
StorageLink is only for privileged operations. It will render as nothing when the user has no admin privs.
> storage: Don't use StorageLink for navigation

- package.json
> package.json: bump xterm.js

- pkg/networkmanager/firewall-client.js
- pyproject.toml
- src/cockpit/channel.py
- src/cockpit/channels/packages.py
- src/cockpit/packages.py
- src/cockpit/peer.py
- src/cockpit/superuser.py
- test/common/netlib.py
- test/common/testlib.py
- test/verify/check-loopback
- test/verify/check-networkmanager-firewall
- test/verify/check-static-login
- test/verify/check-superuser
- test/verify/check-users
https://issues.redhat.com/browse/RHEL-5369 
The other two don't have RHEL issues as it's hard to reproduce them manually. But our CI broke on these a lot.
> rhel-9.3 fixes: superuser reload, async package loading, NM handler debounce

- src/build_backend.py
This fixes three problems:
- the order of files in our sdist was dependent on the non-deterministic order of iteration over a set.  Change that to a tuple.
- the gzip header of our sdist contained a timestamp.  Fix that by using gzip manually and passing `mtime=0`.
- each member in our wheel had either the timestamp of the file from disk or (in case of the generated files) the current time.  Fix those to 1980 (zip's equivalent of 1970) to avoid the problem.
Fixes #19373
```sh
rm -rf a b dist; build .; mv dist a; sleep 1; build .; mv dist b; diffoscope --exclude-directory-metadata=yes a b
```
> src/build_backend.py: produce deterministic builds

- pkg/playground/speed.html
- pkg/playground/speed.js
- src/cockpit/channel.py
- src/cockpit/transports.py
- test/pytest/test_bridge.py
- test/verify/check-connection
https://issues.redhat.com/browse/RHEL-5341
> rhel-9.3: Fix large file uploads

- pkg/systemd/hwinfo.jsx
- pkg/systemd/overview-cards/healthCard.jsx
- pkg/systemd/superuser-alert.jsx
Obviously it's a bit wasteful to convert everything without bringing in improvements but most of this was quite easy to convert.
> Convert more of pkg/systemd to functional components

- src/cockpit/jsonutil.py
- src/cockpit/peer.py
- src/cockpit/remote.py
- test/verify/check-shell-multi-os
- test/verify/check-storage-vdo
- test/verify/check-superuser
> Implement initial superuser mode for "Add Host", unbreak connecting to RHEL 8

- src/cockpit/jsonutil.py
- src/cockpit/peer.py
- src/cockpit/remote.py
- test/verify/check-shell-multi-os
- test/verify/check-storage-vdo
- test/verify/check-superuser
Backport PR #19389, this is the last major pybridge regression that is on our radar. https://issues.redhat.com/browse/RHEL-3537
> [rhel-9.3] Implement initial superuser mode for "Add Host", unbreak connecting to RHEL 8

- pyproject.toml
- test/common/cdp.py
- test/common/netlib.py
- test/common/packagelib.py
- test/common/run-tests
- test/common/testlib.py
- test/verify/check-metrics
- test/verify/check-networkmanager-basic
- test/verify/check-packagekit
- test/verify/check-shell-multi-machine-key
- tools/urls-check
Convert .format() to f-strings with ruff's auto-fixer.
> ruff: Enable UP032 f-string rule

- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/resize.jsx
- test/common/storagelib.py
- test/verify/check-storage-resize
This will be used also for partitions in a future commit.
> storage: Move resize related code to its own file

- test/common/chromium-cdp-driver.js
- test/common/packagelib.py
- test/common/testlib.py
- test/verify/check-system-realms
- https://cockpit-logs.us-east-1.linodeobjects.com/pull-19583-20231108-090526-5dc0c5ce-rhel-9-4-networking/log.html#36-1 (this was my fault from earlier today)
- https://cockpit-logs.us-east-1.linodeobjects.com/pull-19587-20231108-092957-f919d989-rhel-8-10-other/log.html#56
- https://cockpit-logs.us-east-1.linodeobjects.com/pull-19587-20231108-092957-f919d989-rhel-8-10-other/log.html#56
> Fix flakes du jour

- test/reference-image
Pixel changes:
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19581-20231107-143015-8624553c-fedora-39-networking/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19581-20231107-143015-8624553c-fedora-39-other/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19581-20231107-143015-8624553c-fedora-39-storage/log.html
> test: update reference-image to Fedora-39

- test/verify/check-selinux
Our images now have a working auditd. This will make sure that we don't break it again.
> test: Drop "fix auditd" hack

- src/cockpit/bridge.py
On startup of cockpit-bridge, try to detect if:
- our stderr is connected to a socket
- we have python3-systemd installed
If both are true, then we'll log to the journal in preference to logging to stderr.
This will catch the case where we would have already been logging to the journal via cockpit-ws, but provides for better output, mainly when it comes to displaying the source of the messages.
It has an additional benefit of preventing logging a tonne of debug messages into the ferny.InteractionAgent (also a stderr socket) when we'd prefer to see those messages in the journal.
> bridge: try logging to systemd-journald

- pkg/storaged/pages.jsx
- pkg/storaged/storage-controls.jsx
- test/common/testlib.py
- test/verify/check-storage-basic
- test/verify/check-storage-lvm2
> storage: Mock and ignore usage for pixel tests

- test/common/packagelib.py
- test/verify/check-packagekit
- test/verify/check-system-realms
That was a RHEL 7 thing, and dead code.
> test: Drop remaining vestiges of yum

- .github/workflows/unit-tests-refresh.yml
- containers/unit-tests/setup.sh
Fixes: #19725 
Refresh run: https://github.com/cockpit-project/cockpit/actions/runs/7166956574
> unit-tests: Install python3-flake8 from unstable

- pkg/storaged/iscsi/session.jsx
- pkg/storaged/lvm2/volume-group.jsx
- pkg/storaged/mdraid/mdraid.jsx
- pkg/storaged/nfs/nfs.jsx
- pkg/storaged/pages.jsx
- pkg/storaged/stratis/pool.jsx
- pkg/storaged/stratis/stopped-pool.jsx
> storage: Sort tables first by category

- test/common/chromium-cdp-driver.js
- test/common/firefox-cdp-driver.js
- test/common/testlib.py
This fixes the tests for the new Grafana in https://github.com/cockpit-project/bots/pull/5737
> Fix frame tracking race condition for firefox

- test/common/storagelib.py
- test/verify/check-storage-btrfs
- test/verify/check-storage-mdraid
Included this helper already in the btrfs subvolume deletion PR but in the test function, as more things can use it I've created this PR.
> Btrfs refactor tests

- test/common/storagelib.py
check  cleanup operations of storagelib for loopback device.
> add check to storagelib loopback device cleanup

- test/browser/run-test.sh
- test/verify/check-storage-lvm2
And make it produce evidence for our naughty matcher.
> test: Mark TestStorageLvm2.testRaidRepair as "destructive"

- pkg/storaged/mdraid/mdraid.jsx
So that the UI never is in an inconsitent state where the card says "Running" but the "Remove" action of a device is still disabled, for example. This mostly helps the tests.
> storage: Use consistent "running" state for MDRAIDs

- doc/guide/static/gtk-doc.css
- doc/guide/static/style.css
- test/static-code
All these were done automatically with `stylelint --fix`. Start to cover the guide in test/static-code runs.
> guide: stylelint fixes

- pkg/storaged/anaconda.jsx
- pkg/storaged/pages.jsx
> storage: Remove AnacondaAdvice scaffolding

- pkg/kdump/kdump-client.js
- pkg/lib/cockpit-components-table.jsx
- pkg/systemd/overview-cards/insights-poll-hack.sh
This will unblock https://github.com/cockpit-project/bots/pull/5912
> [r8] backports

- packit.yaml
Without this, the c8s test can't run.
> packit: Put back build job

- .github/workflows/release.yml
This was forgotten in commit f16f1fc14b88.
> workflows: Switch tarball generation job to the tasks container

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/filesystem/mounting-dialog.jsx
- test/verify/check-storage-anaconda
- test/verify/check-storage-luks
Since Anaconda will want to mount them and write to them.
Also, resizing partitions, creating encrypted PV, etc work better when LUKS is open.
> storage: Leave LUKS devices open in Anaconda mode

- test/verify/check-apps
Appstream moved it's location, and some tests where not yet updated. The changes are independent of Fedora-40 so should be fine to merge.
> Apps page changes for Fedora 40

- pkg/users/users.js
On page load getLogins is called twice with the initial watch() callback. As getLogins is super expensive on RHEL/Fedora due to the lack of `passwd --all` debounce the call to improve the loading performance.
---
This should help a ton, otherwise there is also this hack https://github.com/cockpit-project/cockpit/pull/20086
> users: debounce getLogins call

- pkg/lib/cockpit-components-empty-state.jsx
The last commit blocks me from converting app.tsx to typescript in navigator.
> Some typing fixes

- test/verify/check-storage-mdraid
> test: Wait for usage bar before mdraid pixel test

- pkg/users/account-details.js
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20106-20240227-100318-635f2cd7-ubuntu-stable-other/log.html
> Test groups flake

- pkg/lib/cockpit-components-dropdown.jsx
For testing it can be easier to set an id to click on for toggling the menuToggle.
> lib: support setting an id for the toggle button

- pkg/systemd/logs.jsx
- test/verify/check-system-journal
Items:
verifies if feature is fixed: https://github.com/cockpit-project/cockpit/issues/20123
> Logs: Check Indentifiers are reloaded when changed priorities

- pkg/storaged/client.js
Since 2.9.0 EnableModules has been deprecated and replaced by EnableModule which can only enable a given module.
---
It would be cool if the `pkg/storaged/$thing` enabled itself but that becomes a bit hairy with juggling client state around.
2.9.0 is packaged in RHEL 8 so should be available everywhere we need it.
> storaged: enable modules with the non-deprecated udisks API

- pkg/shell/manifest.json
- pkg/systemd/overview-cards/tuned-dialog.jsx
These were forgotten in commit b10e0d9988fa84d6be.
> shell, tuned: Update remaining doc links to RHEL 9

- pkg/users/users.js
Hi,
On systems without coreutils date (i.e busy box-based systems), the catch on the date parsing was causing an undefined entry to come back. This resolves that by returning last login as null
> users: Fix handling of failed date parsing

- test/verify/check-shell-multi-machine
- test/verify/check-system-realms
See individual commit messages. This fixes/blocks https://github.com/cockpit-project/bots/pull/6147
> Various ssh/freeipa cleanups/fixes

- test/pytest/test_transport.py
Commit bb34a02a5e00 dropped the SocketTransport, as we don't need it any more. But the unit tests were covering some generic _Transport class functionality. Bring them back using SubprocessTransport instead.
Closing a SubprocessTransport channel does not currenty kill the process, thus the two original "*_close()" tests hang forever. Explicitly kill the process for now. See PR #18340 for possible solutions, but this has been stalled for over a year now.
----
Let's at least land this part, this is harmless and better than not having any unit tests.
> pytest: Bring back Transport tests

- pkg/users/expiration-dialogs.js
- pkg/users/password-dialogs.js
- pkg/users/shell-dialog.js
- pkg/users/users.js
According to the docs and protocl the superuser option is "try" and "require". Split off from https://github.com/cockpit-project/cockpit/pull/20308 let's see what the tests say :)
> users: cockpit.spawn's superuser option is not a boolean

- pkg/lib/cockpit.d.ts
> Extend cockpit typing

- test/README.md
> test/README.md: document TEST_BIND_GLOBAL=1

- pkg/lib/patternfly/patternfly-5-overrides.scss
> pf: Fix split button double spacing issue

- pkg/lib/dialogs.jsx
This new feature can be useful when you create a dialog in an async function and want to return the result of that dialog via async/await features.
For example in the files plugin we want to query a user to replace a file and await the result of that. In the Dialog component you return the interesting dialog values via `Dialogs.close` or `Dialogs.reject` if you want to throw an exception.
---
---
In Files this made the code simpler see:
```
diff --git a/src/upload-button.tsx b/src/upload-button.tsx
index e022595..7804210 100644
--- a/src/upload-button.tsx
+++ b/src/upload-button.tsx
@@ -66,29 +66,24 @@ const FileConflictDialog = ({
path,
file,
uploadFile,
-    waiter,
}: {
path: string[];
file: FolderFileInfo,
uploadFile: File,
-    waiter: Waiter,
}) => {
const Dialogs = useDialogs(); …
```
> lib: allow awaiting Dialogs.show()

- pkg/users/account-details.js
lastlog 2 form util-linux has a different location for its login db, instead using a persistent sqlite database located at `/var/lib/lastlog/lastlog2.db` this checks using `test -e` if the old path `/var/run/utmp` exists. if the spawn of test fails, we assumes that we are using lastlog2
> support for watching lastlog2

- packit.yaml
- test/browser/browser.sh
- test/browser/main.fmf
- test/browser/run-test.sh
The main difficulty here was working around https://issues.redhat.com/browse/TFT-2564
> packit: Enable CentOS Stream 10 tests

- pkg/lib/cockpit-components-form-helper.tsx
I want to use this in typed code from cockpit-files.
> pkg/lib: port form-helper component to typescript

- pkg/packagekit/manifest.json
The updates page also allows one to configure kpatch and configure automatic updates.
> packagekit: mention kpatch/updates in the manifest

- pkg/storaged/client.js
- pkg/storaged/stratis/create-dialog.jsx
- pkg/storaged/stratis/pool.jsx
As a preparation to support file size limits.
> storage: Move to "r6" of the Stratis D-Bus API

- tools/urls-check
Fixes the failing workflow:
https://github.com/cockpit-project/cockpit/actions/workflows/urls-check.yml
> tools: URLError has no attribute code

- pkg/lib/cockpit-upload-helper.ts
Our use of `{ mode: 'byob' }` gets us in trouble on WebKit.  We see "ReadableStreamBYOBReader needs a ReadableByteStreamController" on any attempt to upload a file.  This affects:
- Cockpit Client
- Epiphany
- Safari on macOS and iOS
And indeed, https://caniuse.com/mdn-api_readablebytestreamcontroller agrees that we can't use this yet.
We also can't simply change to the default reader: the reason we chose the BYOB reader is that it let us control the block size that was returned.  The default reader returns large blocks (on the order of 2MB) which we can't send over the websocket, because of limitations in `cockpit-ws`:
```
server is trying to frame of size 524294 or greater, but max supported size is 128KiB
Received extremely large WebSocket data from the server
```
It seems we can't get …
> pkg/lib: make the upload-helper WebKit-compatible

- test/common/packagelib.py
This commit was broken in several ways:
- `systemctl list-units` only shows loaded units, so it doesn't include units like `dnf-automatic-install.timer` which are not running/loaded at the beginning of a test. This skipped the PackageCase setUp/addCleanup.
- There is no unit "dnf-automatic". It should have been dnf-automatic-install.{timer,service}
- This doesn't make sense as a cached property, as the set of units can change between tests and even during tests.
- Without the caching, this is unnecessarily expensive.
This needs rethinking.
This reverts commit d3cde1612121bdc81923862f94a53cec3121a0bd.
----
@jscotka FYI. This landed yesterday in PR #20631 but now [breaks like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20671-f738dd81-20240627-210904-fedora-40-expensive/log.ht …
> Revert "test: packagelib - robustify disabling of services"

- package.json
- pkg/lib/timeformat.ts
Commit 4a0d1a38b530 eliminated the last user of that API.
> package.json: Drop date-fns

- pkg/lib/cockpit.d.ts
- pkg/lib/credentials.js
- pkg/shell/hosts_dialog.jsx
Some preparatory commits for my work to provide the ssh host dialogs as a general library, and pulling them out of the shell. I want to test the credentials.js bit in isolation.
> Fix race condition in credentials.js, add some missing cockpit.js type annotations

- test/common/testlib.py
- test/verify/check-client
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-os
- test/verify/check-system-realms
- test/verify/check-system-shutdown-restart
- test/verify/check-users-roles
This started with some preparation for making the "Add host" functionality optional/configurable (see PR #20749), but I found some other crufty bits while at it :grin:
> Various test cleanups

- test/pytest/conftest.py
This is a fixup for 3ec1476d506ad0f45f1de10308e3dd13eb6d69ed.
We used a check for Python 3.6 to see if we had an old version of pytest-asyncio.  This was a bad idea, because Debian has old pytest-asyncio even though it has a newer Python.
Change the check to directly check the version of pytest-asyncio.
> pytest: fix pytest-asyncio version check

- pkg/storaged/dialog.jsx
- pkg/storaged/lvm2/create-logical-volume-dialog.jsx
This allows us to remove SelectOneRadioVertical which is almost the same as SelectOneRadio.
---
No UI changes:
> storaged: make SelectOneRadio support a vertical option

- pkg/systemd/logs.jsx
- pkg/systemd/logs.scss
Fixes https://github.com/cockpit-project/cockpit/issues/20146
> Allow the tooltip to be clicked in the journal filter panel

- test/verify/check-system-journal
This is a test case for https://github.com/cockpit-project/cockpit/pull/20806 and the recent fix @garrett made https://github.com/cockpit-project/cockpit/pull/20818
Let's pixel test this so we catch PF changes :)
New Pixels: https://cockpit-logs.us-east-1.linodeobjects.com/pull-20821-32935135-20240731-075551-fedora-40-other/log.html
> Test logs tooltip

- pkg/metrics/manifest.json
- test/verify/check-metrics
- test/verify/check-storage-luks
- test/verify/check-system-realms
Various fixes for https://github.com/cockpit-project/bots/pull/6711
> centos-10: Fixes

- .github/dependabot.yml
- package.json
- pkg/lib/cockpit-components-terminal.jsx
- pkg/lib/console.css
These are the new names, and they have more recent releases.
> build: Switch to @xterm/xterm and @xterm/addon-canvas

- test/common/testlib.py
- test/verify/check-metrics
- test/verify/check-packagekit
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-system-realms
Also see https://github.com/cockpit-project/bots/pull/6797
> Some test cleanups to prepare for upcoming ubuntu-2404 image

- test/pytest/test_bridge.py
We have a fixture which creates a bunch of testcases for unit testing fsinfo, including cases where we don't have access to access directories.  This prevents pytest's tmpdir pruning from cleaning up after the test.
Make sure we set mode 0777 on all directories after we're done.
This takes care of the pile of warnings like
warnings.warn(
/usr/lib/python3.12/site-packages/_pytest/pathlib.py:95: PytestWarning: (rm_rf) error removing /tmp/pytest-of-lis/garbage-1fa620ed-1fff-4854-aa93-d6a13d1567e3
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-lis/garbage-1fa620ed-1fff-4854-aa93-d6a13d1567e3'
that you otherwise get after a few runs of the test (once pytest start trying to prune the tmpdir of the older runs).
> test: fsinfo: set u+rwx on directories on teardown

- test/browser/browser.sh
https://src.fedoraproject.org/rpms/shadow-utils/c/029086935e7eb96ea4e9f1e86984caaa113c593d?branch=rawhide
> test: drop shadow-utils workaround

- pkg/systemd/services.jsx
Fixes https://github.com/cockpit-project/cockpit/issues/21086
> systemd: update unit-file.h link

- containers/ws/install.sh
- containers/ws/label-install
- containers/ws/label-uninstall
- test/common/testlib.py
- test/image-prepare
- test/ostree.install
- test/run
- test/verify/check-client
- test/verify/check-connection
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
- test/verify/check-shell-multi-os
- test/verify/check-static-login
- test/verify/check-superuser
- test/verify/check-system-shutdown-restart
- test/vm.install
- test/ws-container.install
This is some preparation work for introducing a beiboot and ws container based RHEL 8 test on main.
> Various test and cockpit/ws container cleanups

- src/session/session-utils.c
> session: fix copy/paste abort message for setresuid

- pkg/storaged/manifest.json
- pkg/users/manifest.json
The doc URL changed.
Fixes #21166
> storage: Update LVM doc link

- doc/protocol.md
- pkg/lib/credentials.js
> fswatch1 cleanups

- .github/dependabot.yml
- pkg/storaged/manifest.json
- test/verify/check-static-login
Fixes #21229
Closes #21209 
Follow-up for https://github.com/cockpit-project/bots/pull/7085
> Three small fixes

- pkg/shell/state.jsx
- pkg/shell/topnav.jsx
- pkg/shell/util.jsx
- test/verify/check-pages
> shell: Take docs from the correct manifest item

- pkg/lib/cockpit.js
Small tweaks split out from my TS attempt, that fails on a unit test failure which I don't understand so lets try to improve cockpit.location gradually.
> Cockpit location small tweaks

- test/common/testlib.py
The `<TopNav>` has a hackish `handleClickOutside()` that reacts to
any "blur" event anywhere on the menu. With the right timing (which
happens with `TestKerberos.testNegotiate` on our CI), opening the
session menu and scrolling a bit triggers a blur event, which closes the
menu again.
Avoid this by disabling the "scroll into view" part of the mouse click.
We don't need it in this case, as we just scrolled the session menu
opener itself in the previous step.
----
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16808-52da73bc-20241119-054347-fedora-40-firefox-networking/log.html#41) is our #2 top flake (after #20609).
The [screenshot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16808-52da73bc-20241119-054347-fedora-40-firefox-networking/TestKerberos-testNegotia …
> test: Avoid scrolling race with session menu

- pkg/lib/cockpit-path.ts
- pkg/lib/cockpit/_internal/base64.js
- pkg/metrics/metrics.jsx
- pkg/networkmanager/interfaces.js
- pkg/packagekit/autoupdates.jsx
- pkg/selinux/setroubleshoot-view.jsx
- pkg/shell/hosts_dialog.jsx
- pkg/shell/nav.jsx
- pkg/shell/util.jsx
- pkg/static/login.js
- pkg/storaged/anaconda.jsx
- pkg/storaged/client.js
- pkg/storaged/dialog.jsx
- pkg/systemd/logsJournal.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/services.jsx
- pkg/users/account-create-dialog.js
- pkg/users/expiration-dialogs.js
String.prototype.substr() is a deprecated API.
---
:see_no_evil: hopefully the retry flakes are not too bad.
> pkg: convert substr() usage to substring()

- pkg/lib/cockpit.js
Another incremental fixes PR, I will look into fixing the substr usage everywhere in cockpit but that's a train ride topic :)
> cockpit.location TypeScript found issues

- test/pytest/test_bridge.py
Fully cover fsreplace1 error cases.
> test: bridge: extend fsreplace1 tests

- pkg/systemd/overview-cards/cryptoPolicies.jsx
> systemd: ignore comments in /etc/crypto-policies/config

- pkg/storaged/client.js
- pkg/storaged/lvm2/volume-group.jsx
- test/verify/check-storage-lvm2
> test: Wait for LVM2 RAID to be fully synchronized before pixel test

- pkg/static/login.scss
> Fix UI elements related to OAuth / Bearer token validation

- pkg/apps/application-list.jsx
- pkg/apps/application.jsx
- pkg/apps/apps.jsx
- pkg/apps/appstream.js
- pkg/apps/utils.tsx
- pkg/lib/cockpit.d.ts
This helped me with https://bugzilla.redhat.com/show_bug.cgi?id=2325759
> apps: code cleanup, initial typing, debug functionality

- test/vm.updates-testing
See https://dnf5.readthedocs.io/en/latest/dnf5_plugins/config-manager.8.html
Fixes #21361
> test: Adjust vm.updates-testing to dnf5

- test/browser/main.fmf
- test/browser/run-test.sh
- test/verify/check-networkmanager-checkpoints
- test/verify/check-networkmanager-mtu
- test/verify/check-storage-mdraid
- test/verify/check-system-info
See https://github.com/orgs/cockpit-project/projects/4/?pane=issue&itemId=60070873
> Make some networking and storage tests nondestructive

- test/common/static-code
This was missing from commit e395923115e
---
Oops! :fearful: Mea culpa.
> test: Adjust project root path for moved static-code

- src/appstream/org.cockpit_project.cockpit_kdump.metainfo.xml.in
- src/appstream/org.cockpit_project.cockpit_networkmanager.metainfo.xml.in
- src/appstream/org.cockpit_project.cockpit_selinux.metainfo.xml.in
- src/appstream/org.cockpit_project.cockpit_sosreport.metainfo.xml.in
- src/appstream/org.cockpit_project.cockpit_storaged.metainfo.xml.in
- src/client/org.cockpit_project.CockpitClient.metainfo.xml
- src/ws/org.cockpit_project.cockpit.appdata.xml.in
It should probably match the rDNS app id (that got changed in f459553303c8419b88bdd70b3c5c79d62734d66d).
/cc @martinpitt
> appstream: Fix developer id

- test/common/webdriver_bidi.py
- test/verify/check-metrics
- test/verify/check-pages
https://issues.redhat.com/browse/COCKPIT-1159
> Chromium headless → full follow-ups

- test/verify/check-users
Improve our test coverage in the users page, some functionality was not covered at all.
> Test logout account dialog

- test/verify/check-system-tuned
> test: enable tuned tests on Arch Linux

- pyproject.toml
- test/common/storagelib.py
- test/verify/check-storage-nfs
> Extend testlib typing

- pkg/storaged/btrfs/volume.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-btrfs
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2352385
> storage: Implement deletion of multi-device btrfs

- pkg/packagekit/updates.jsx
- test/common/packagelib.py
- test/verify/check-packagekit
Preparations for implementing `dnf needs-restarting` support.
> Some tracer cleanup

- tools/debian/control
See https://salsa.debian.org/utopia-team/cockpit/-/merge_requests/3
Thanks to Arif Ali for the original patch!
> debian: Prefer "sos" over "sosreport"

- package.json
Noticed while working on #21611. This needs a node_module refresh, let's not do this now. I just don't want to forget about it.
> package.json: Apply eslint to TypeScript code

- pkg/packagekit/updates.jsx
This got broken in commit 26c7e0df8b9.
> packagekit: Fix tracer comment

- src/cockpit/transports.py
- test/pytest/test_transport.py
Python 3.14 unceremoniously yanked the PidfdChildWatcher API without deprecation notice which leaves us in a bit of a tight spot, since we make use of it.  At the same time, the API that the maintainer has suggested to use instead isn't working for us.
Let's just use pidfd_create() directly with the mainloop and call waitpid() when it fires.  We can also disentangle ourselves a bit more from the state tracking inside of the process and always take care of it for ourselves (by way of a separate state variable).
We need to be careful here: in case pidfd support isn't present (old kernel or old Python, as in RHEL 8) then we need to fall back to the old watcher API.  This is deprecated, and also removed in Python 3.14, but that's not a problem: we'll only hit the fallback path on ancient …
> bridge: Implement pidfd watching manually

- test/common/testlib.py
Unblocks podman PF 6 port, see https://cockpit-logs.us-east-1.linodeobjects.com/pull-2058-74f7e589-20250327-171436-ubuntu-2204/log.html#14
> Make logout work in the old shell

- pkg/lib/cockpit-components-password.jsx
> lib: Password field help button to inline button

- pkg/storaged/btrfs/filesystem.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/btrfs/volume.jsx
- pkg/storaged/crypto/keyslots.jsx
- pkg/storaged/iscsi/session.jsx
- pkg/storaged/lvm2/thin-pool-logical-volume.jsx
- pkg/storaged/lvm2/volume-group.jsx
- pkg/storaged/mdraid/mdraid.jsx
- pkg/storaged/overview/overview.jsx
- pkg/storaged/pages.jsx
- pkg/storaged/partitions/partition-table.jsx
- pkg/storaged/storage-controls.jsx
- pkg/storaged/storage.scss
- pkg/storaged/stratis/pool.jsx
- pkg/storaged/stratis/stopped-pool.jsx
- test/common/storagelib.py
- test/verify/check-storage-btrfs
- test/verify/check-storage-luks
Current pixeldiffs: https://github.com/cockpit-project/pixel-test-reference/compare/6be9633953501c23b6aeb1eb4642ede0ef27be7f..de2210d327158fcb68f96561ee44055ae069594d
> PF6 bits for Storage

- pkg/shell/nav.scss
- pkg/shell/shell.scss
Builds on top of https://github.com/cockpit-project/cockpit/pull/21832
This changes the UI a bit, but it realigns it to be more like PF6. We needed to do _something_, so I figured we might as well modernize it a little. :wink: 
Preview:
> Pf6 host switcher

- pkg/lib/patternfly/patternfly-6-overrides.scss
- pkg/shell/nav.scss
- pkg/shell/shell.tsx
- test/verify/check-shell-menu
> shell: Use PF utility for hiding the skip link (to fix RTL)

- tools/cockpit.spec
Currently if you install Cockpit on a system that doesn't have SELinux installed by default, and then install SELinux later down the line, this leads to Cockpit failing since it's policy is not installed till `cockpit-ws`'s post run is triggered again and it's installed. However we can avert this if we move the policies to it's own package, we can then require it as a dependency if the system has or installs `selinux-policy-base` so the package manager then brings in this new package and correctly installs the policies
I've checked this against Tumbleweed and Fedora 41, I imagine I'll have to make a few more changes from the test suite
> tools: Move SELinux policies to cockpit-ws-selinux

- src/cockpit/osinfo.py
- test/verify/check-storage-basic
- test/verify/check-storage-lvm2
- test/verify/check-system-realms
The ubuntu-stable CI image is moving from 24.10 to 25.04 and we need to adapt a little.
> Updates for Ubuntu 25.04

- tools/cockpit.spec
https://bugzilla.redhat.com/show_bug.cgi?id=2362721
> tools: Add license to RPMs

- test/common/pixel-tests
- tools/node-modules
This will make it so editor doesn't appear for tag message
> test: Skip pixel tests & node modules tag signing

- pkg/lib/cockpit.d.ts
- pkg/lib/os-release.ts
And also make "stringify" optional in a FileSyntaxObject, for files that are never written.
> lib: Type the read_os_release function

- .github/workflows/flatpak-test.yml
- containers/flatpak/test/test-browser
Fixes [recent regression](https://github.com/cockpit-project/cockpit/actions/runs/15003521981/job/42156289010?pr=22001), and adds some debugging output.
> Fix flatpak test

- pkg/users/account-details.js
> allow fullname to be set as empty string

- test/verify/check-storage-mdraid
- test/verify/check-storage-stratis
> test: Adapt to new centos-10 image

- test/verify/check-system-services
Waiting on the failed unit to show up flakes in our CI, all are other tests wait on the loading state to go away before asserting anything on the page.
> test: wait on services page to load

- doc/guide/feature-machines.xml
- doc/guide/multi-host.xml
> reflect deprecation of host switching in docs

- test/common/packagelib.py
- test/vm.install
- tools/cockpit.spec
- tools/cockpit.suse.pam
I've finally had the time to get this submitted!
So as per #21335 this is a small set of the changes that don't fit into any strict category. I've tried to keep this as small as I can, but let me know if you want it smaller
> Various changes for TW testing

- pyproject.toml
- src/cockpit/beiboot.py
- src/cockpit/beipack.py
- src/cockpit/bridge.py
- src/cockpit/channel.py
- src/cockpit/channels/dbus.py
- src/cockpit/channels/http_channel.py
- src/cockpit/channels/metrics.py
- src/cockpit/config.py
- src/cockpit/internal_endpoints.py
- src/cockpit/misc/bootloader.py
- src/cockpit/packages.py
- src/cockpit/peer.py
- src/cockpit/remote.py
- src/cockpit/router.py
- src/cockpit/samples.py
- src/cockpit/superuser.py
We want everything strictly typed, but it ain't always easy this converts so more of a code to be strictly typed where possible.
> Bridge types again

- pyproject.toml
- src/cockpit/channels/filesystem.py
- src/cockpit/channels/metrics.py
- src/cockpit/channels/pcp.py
- src/cockpit/channels/stream.py
Just some small Friday cleanups :)
> Bridges types again 2

- pyproject.toml
- test/common/packagelib.py
- test/common/submanlib.py
- test/verify/check-packagekit
> package test typing

- src/common/test-jsonfds.c
- src/pam-ssh-add/test-ssh-add.c
https://issues.redhat.com/browse/RHEL-104798
---
This only affects two unit tests, hence "no-test".
> Fix gcc address sanitizer issues

- test/common/packagelib.py
When CI hits green, please comment on https://bugzilla.redhat.com/show_bug.cgi?id=2306114
> test: drop "dnf clean" failure workaround

- test/common/packagelib.py
This reverts commit 10a12e5b5f94fa2ab1aae1151e465c6862338823.
This was fixed in pacman:
https://gitlab.archlinux.org/pacman/pacman/-/commit/8d14b22260026ec3d567d6367f83b9ab580b6556
> Revert "test: Don't create a empty pacman repo"

- packit.yaml
- plans/all.fmf
- test/browser/browser.sh
- test/browser/main.fmf
- test/browser/run-test.sh
- test/verify/check-system-services
https://issues.redhat.com/browse/COCKPIT-1214
----
Related, but not blocking:
- https://github.com/packit/packit-service/issues/2834
- https://github.com/cockpit-project/bots/pull/8043
> test: Add CentOS 9 bootc tmt test

- pkg/networkmanager/wireguard.jsx
The goal of useInit is to run initialisation code once.
> networkmanager: prefer useInit over useEffect

- pkg/lib/cockpit-components-install-dialog.jsx
> lib: re-use fmt_to_fragments helper

- src/cockpit/channels/pcp.py
PCP 7.0 (PMAPI_VERSION_4) changed the API, in particular wrt. timespecs: https://github.com/performancecopilot/pcp/commit/02c8fb5656ab635c68
---
See https://github.com/cockpit-project/bots/pull/8193 and recent bridge metrics crash that we [started to see in rawhide TF](https://artifacts.dev.testing-farm.io/c824d021-37a8-4261-a389-75c71ef1a94d/).
> bridge: Adjust metrics channel to PCP 7 timespec API change

- pkg/metrics/metrics.jsx
> metrics: drop isDatepickedOpened state which is never read
