cockpit-project/cockpit

- test/common/testlib.py
testlib: add locale message exception for fedora-coreos
fedora-coreos recently dropped the glibc langauge packs, meaning that
we're now getting the "unknown locale" warning there as well (since the
browser sends 'en-us').
We have an exception in place for debian-*, so extend that to
fedora-coreos.
> testlib: add locale message exception for fedora-coreos

- test/verify/check-system-services
In some test environments sockets.target is (inexplicably) not running,
even though basic.target `Wants=` it. Check `basic.target` instead,
which is in the critical path for a successful boot, and also
alphabetically earlier so that we can see it in screenshots.
Fixes #15838
> test: Use basic.target instead of sockets.target in TestServices

- .github/workflows/reposchutz.yml
github.sha seems to refer to the current state of the main branch of the
repository, not the base branch that the PR was proposed against.  That
means that if someone else lands a github workflow change in the
meantime, unrelated PRs will start going red.
Change that to be based on github.event.pull_request.base.sha.
> reposchutz: use pull_request.base.sha

- package.json
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/storage.scss
- test/verify/check-storage-luks
tang-show-keys is now widely enough available to use it in our tests instead of jose.
However, different versions of tang-show-keys use different hashing algorithms, so we need to account for all possibilities in our dialog.
This PR also removes from the dialog the alternative command that people might use if they don't have tang-show-keys. The assumption again is that everybody has it now, and having this in the dialog just adds to the perceived complexity of the task.
> storage: Tang key hash improvements

- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/dialog.jsx
- test/verify/check-storage-luks
- The first commit changes logic of how we remove keys. Fixes #15773
- The second commit changes UI:
Before it looked like this:
Now it looks like this:
-The third commit fixes layout in `Add key` modal
Before it looked like this:
Now it looks like this:
@garrett WDYT? One thing is about 'Remaining passphrase' helper text. We probably want to mention that user should type in different passphrase, not the one that is removing. Should we just change label?
Needs tests fixes, working on them now.
> storage: Luks modal body fixes

- .github/workflows/reposchutz.yml
The workflow has a fairly simple strategy at present: if there are
changes to the `.github` directory (as per `git diff`) then fail.  That
has two problems:
- the changes might have come from an unrelated PR that got merged in
the meantime; and
- the PR can "get away with" individual commits that make changes, as
long as there are future commits that revert those changes.
Depending on the merge/rebase strategy used when landing, thre are
some creative way to sneak changes through anyway.
Replace the previous logic with a new one: list all commits which are:
- reachable from the PR;
- not already on the target branch; and
- modify `.github`
and fail if the result is non-empty.
Factor out the context expressions for the relevant SHAs into
environment variables to improve readability. …
> reposchutz: improve change detection logic

- pkg/storaged/clevis-luks-passphrase.sh
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/lvol-tabs.jsx
- test/verify/check-storage-luks
Whenever a passphrase is needed, we now also try the stored passphrase
in addition to one recovered from Clevis.
But while a passphrase recovered from Clevis can be assumed to work, a
stored passphrase can easily be wrong.  Therefore, if a operation that
requires a passphrase fails, we now give the use the opportunity to
provide a different one.
This also fixes the flow when adding/changing Clevis keys.  Earlier,
this was done with two dialogs where the first asks for the passphrase
and the second will show the error if that passphrase was wrong,
without giving the user a opportunity to correct the passphrase.  Now
this is still done in two steps, but the second one will show a
passphrase input if the operation failed because of a wrong
passphrase.
Unlocking a disk is one of the …
> storage: Improved passphrase handling

- pkg/storaged/format-dialog.jsx
Otherwise systemd might have outdated UUID / mount point mappings and
might unmount our new filesystem right away again.
Here are the details.  Start with this in /etc/fstab:
UUID=<uuid1> /run/foo ...
This causes systemd to associate uuid1 with /run/foo.  Now uuid1 is
unmounted, the block device is formatted, and a new fstab is written
with the new uuid2 but with the same mount point:
UUID=<uuid2> /run/foo ...
At this point, systemd sees that uuid1 has disappeared and will make
sure that /run/foo is not mounted, because it still associates
/run/foo with uuid1.  At the same time, Cockpit will mount the new
filesystem at /run/foo.  This is a race and sometimes Cockpit does the
mount, and then systemd does its cleanup and unmounts.  (If systemd
does the cleanup first, it will find /run/foo …
> storage: Reload systemd before mounting after formatting

- packit.yaml
Even though this is prone to instability, we'd still rather like to learn about OS regressions earlier than later.
> packit: Enable Rawhide

- src/tls/cockpit-certificate-helper.in
Spotted by coverity: "warning[SC2046]: Quote this to prevent word splitting."
> tls: Fix quoting of locale check

- pkg/lib/machine-info.js
- pkg/systemd/hw-detect.js
It seems that 'Rank' is not always defined. It not being present would
make the whole page oops.
While on that I made sure, that any missing field would not be
represented as `undefined` but would have some (at least empty string)
value.
Fixes #15631
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1966686
> hwinfo: Don't oops when some hw details are missing

- webpack.config.js
Disable mergeLongHand in cssnano.
The official fix has already landed upstream but we unfortunately can't
update cssnano without updating also CssMinimizerPlugin.
An update of CssMinimizerPlugin will not work without webpack-5.
Therefore let's keep the WA for now.
> Fix missing borders in Selects

- .github/workflows/reposchutz.yml
`git fetch` isn't fetching the named tag, but rather just populating
`FETCH_HEAD`.  That's OK.  We already check that the fetch was
successful and we got the thing we expected, so checking that the tag is
also equal to the thing we expect is just superfluous.  We never use it
anyway.
> reposchutz: drop superfluous check for tag

- test/common/testlib.py
They don't seem to affect operations significantly but are blocking
image refreshes.
> test: Allow selinux denials regarding "dma_heap"

- .github/workflows/livetest.yml
If we put a `if:` on each `job:` then the workflow will dispatch, but at
least it won't start any VMs.
> livetest: stop spinning up a vm every single time anyone writes any comment on any PR or issue

- webpack.config.js
Redux is not dependency of this repo anymore.
> webpack: Remove workaround for redux

- .github/workflows/reposchutz.yml
The deconstruction assignment to get the issue number from the context
was broken: it's at `context.issue.number`, not `context.number`.
Just code it directly.  It's more typing, but it's a lot less
error-prone and also easier to read.
> reposchutz: fix label-removing code

- test/verify/check-selinux
Looks like we always had a spiffy clean SELinux record.  But a new
rhel-9-0 image now needs this code to work again.
> test: Use correct selectors for listing toggles in check-selinux

- Makefile.am
- pkg/build
- tools/webpack-make
Split the necessary variables and rules for building dist/ out of the
primary Makefile.am and into pkg/build.  Include that back into the main
Makefile.am.
The only changes are to the invocation of webpack-make:
- don't set the BUILDDIR.  Nothing uses that anymore.
- don't call webpack-make via tools/missing.  This won't work without
autogen, and it never made sense anyway, mostly leading to non-sense
error messages.
- stop using timeout.  We don't seem to get stuck builds all that often
anymore, and besides, we have better ways of dealing with those these days.
Meanwhile, using this tool interferes with signal delivery (which is why we
often see node running long after terminating a build).
This file is a makefile, but has `#!/usr/bin/make -p` on top, and is
marked as executable, so it …
> pkg/build: new script for standalone webpack

- test/common/testlib.py
instead of having all the image specific quirks listed explicitly.
> test: Call self.machine.allowed_messages in check_journal_messages

- pkg/storaged/nfs-details.jsx
- pkg/storaged/overview.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/storage.scss
This is a bunch of little fixes of small, unrelated things for the storage page, including a fix for #15886.
I tried to use PF4 when possible, but fell back on some custom CSS changes in several places, as:
1. we're not using the latest PF4 (and cannot use the utility classes yet, so I crafted some fallbacks that should cause no harm — as they're simple and the same as PF4's classes — but the specific CSS still should be removed once we upgrade PF4)
2. in the storage page, we're also still using custom widgets for listing
> storage: Layout fixes

- pkg/systemd/overview-cards/insights.jsx
> insights: Correctly align Insights status

- pkg/shell/shell.scss
This allows the select to pop above the list and outside of the dialog.
Fixes #15769
> shell: Make keys scrollable instead of modal body

- test/common/pixel-tests
Use --force to really blow away the index.  Git otherwise refuses to
remove things from it that are neither in the HEAD commit nor in the
working tree.
Fetch the "empty" branch before using it.
Always push to the remote, even when there are no changes.  The previous push might have failed and this is an easy way to try again.
> test: More robust pixel-tests pushing

- selinux/cockpit.te
Stylistic issue only. Detected by "selint".
Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
> selinux: fix permission ordering

- test/verify/check-metrics
Firefox since version 91 contains space in attributes format.
Before: `--utilization:0.9321325; --saturation:0;`
Now: `--utilization: 0.9321325; --saturation: 0;`
> tests: Accept white spaces in attributes

- test/make_dist.py
- tools/build-debian-copyright
- tools/git-utils.sh
- tools/make-bots
- tools/node-modules
- tools/webpack-jumpstart
The summary:
- minor changes to the copyright scanning script to avoid a mess on stderr
- add a new `git-utils.sh` which contains a common implementation of the logic for maintaining and using a cache of a git repository of a given name relative to `GITHUB_BASE`, with utilities for checking it out to various different places in the cockpit tree
- use that from `tools/node-modules`
- use that from `tools/make-bots`
- ~~use that from `test/common/pixel-tests`~~
- use that from a new script `tools/jumpstart`
- use that last one from `test/make_dist.py`
- only commit `dist/` and `package-lock,json` to `cockpit-dist`
> jumpstart / git-caching

- pkg/shell/listing.scss
If we divide by multiplying fractions, it works without any odd Sass functions and imports.
> shel: Make our SCSS Dart Sass friendly

- test/verify/check-metrics
On Fedora/RHEL systems, starting pmproxy and redis in parallel does not
work: pmproxy needs to start *after* redis is already running, so that
its metrics API actually works. So use the same code structure on all
operating systems.
PR #15812 will fix that properly and get rid of that manual
initialization, but that still takes a while to land.
> test: Fix race condition in TestGrafanaClient initialization

- tools/make-bots
This gets set when testing bots PRs.  If the PR was proposed from a
fork, then it won't be in the set of commits fetched by default, so
request it explicitly.
> make-bots: manually fetch COCKPIT_BOTS_REF, if specified

- pkg/lib/cockpit-po-plugin.js
We might have more than one flag, so look for the word "fuzzy" in the
entire flags string.
We use \b because JS RE doesn't seem to support < and > or \< and \>.
> cockpit-po-plugin: improve fuzzy flag matching

- pkg/metrics/metrics.jsx
During user testing it was reported several times that the "Disks"
history column is ambiguous wrt. whether it shows capacity usage or I/O.
It's the latter, so update the label. Keep it in the current metrics
though, as that shows both kinds of metrics (and further clarifies them
with labels).
Also keep "Network" instead of "Network I/O", as there is no ambiguity
there, and the label would get too wide.
https://bugzilla.redhat.com/show_bug.cgi?id=1969904
> metrics: Change "Disks" history label to "Disk I/O"

- .github/workflows/unit-tests.yml
Hardcoding "master" does not work for PRs which target e.g. rhel-8.4.
---
As noticed in #15939
> workflows: Fix unit-tests' "changed" detection to compare against correct target branch

- pkg/systemd/reporting.scss
1a28f9788e0fc9075ee5bb32fc563e20a5f947b5 introduced an @import of
"./_global-variables.scss" in reporting.scss.
I'm not sure why this got imported with "./" but since that's not in the
same directory, it seems wrong.  Furthermore, although it works under
sassc, it breaks with Dart Sass.
Other users seem to import this as "_global-variables.scss" and rely on
path resolution to find it in pkg/lib, so let's do the same here.
> systemd: fix _global-variables.scss import path

- test/image-prepare
Fixes #12781
I am not 100% sure this is the best improvement. I felt like rewriting much of it, but as I don't yet know all the ways in which the tests images can be used, this is probably the least intrusive and does what #12781 requests: creates the symlink to the image file only after building it has been completed.
> image-prepare: symlink only when image complete

- .github/workflows/build-dist.yml
- .github/workflows/publish-dist.yml
- .gitignore
- Makefile.am
- pkg/build
In summary:
- use pkg/build instead of automake
- run directly on the github actions runner
> streamline dist workflow

- packit.yaml
- test/make_dist.py
- tools/webpack-jumpstart
We don't get docs built by the build workflow anymore, so try building
them in the sandcastle.
update: That didn't work.  Let's add a nasty workaround, instead.
> packit.yaml: workaround to fix docs build

- test/image-prepare
Commit 779d7f08936ba caused three regressions:
* Crash with `UnboundLocalError: local variable 'qcow2_image' referenced before assignment`
with `--overlay`, if the target image was already existing (as it
happens with preparing the `dnf-copr` scenario). In that case
prepare_install_image() does not create any new overlay, so return
None instead.
* Crash due to the target symlinking already existing with `--overlay`,
as the previous os.unlink() was not moved along with the os.symlink()
move.
* `VirtMachine` needs to be called on the .qcow2 overlay file
instead of the target symlink, as the latter does not exist yet
without `--overlay`.
Factorize the logic into a new finalize_image().
Also rename the return vaules of prepare_install_image() to something
more descriptive.
-----
I tested this …
> test: Re-fix image-prepare with --overlay

- pkg/storaged/fsys-tab.jsx
- test/verify/check-storage-mounting
When the FS is currently mounted and x-systemd.automount is used
together with noauto, do not show a warning about inconsistent mount
point.
The FS will be mounted, will just not block early boot.
Closes #15902
> storage: take into consideration x-systemd.automount when showing warning in fs tab

- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/metrics/metrics.jsx
- pkg/networkmanager/network-interface.jsx
- pkg/storaged/block-details.jsx
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/drive-details.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/mdraid-details.jsx
- pkg/storaged/nfs-details.jsx
- pkg/storaged/part-tab.jsx
- pkg/storaged/pvol-tabs.jsx
- pkg/storaged/swap-tab.jsx
- pkg/storaged/unrecognized-tab.jsx
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vgroup-details.jsx
- pkg/systemd/services/service-details.jsx
We used to have an local override for this in
patternfly-4-overrides.scss which however stopped working at some point.
PF4 exposed a class to do that now, so use that class for this purpose.
See https://github.com/patternfly/patternfly/issues/3630
Note: There are some cases were we might still want horizontal lists
even on xs screen sizes, and that when both label and content take very
small space. See metrics -> disk load.
> Make description lists collapse to vertical mode when on xs screen sizes

- test/common/testlib.py
For images not explicitly specified by a provision, assume that we want
the image to have been created by test/image-prepare.
Throw an early exception with a useful message, for ourselves, if it
doesn't exist.
Note that passing a pathname as the image name is explicitly supported,
and the basename (without extension) will be used for setting the
Machine.image variable.
> testlib: force use of prepared images

- pkg/lib/cockpit-components-table.jsx
- pkg/networkmanager/firewall.jsx
This fixes the duplicate Ids issues for expandable rows in networking firewall page.
Fixes #15193
> lib: table: parameterize expandId and contentId with the table id

- package.json
Now that we're on Webpack 5, we can move to sass-loader 12.  It's a bit
smaller, mostly due to fewer internal dependencies.
```
⬢[lis@f34 cockpit]$ diff -ru master/dist sass-loader-12/dist
⬢[lis@f34 cockpit]$ 
```
> package.json: bump sass-loader to 12

- pkg/lib/cockpit-components-firewalld-request.jsx
- pkg/lib/cockpit-components-firewalld-request.scss
- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- test/verify/check-metrics
This is the next (and a rather major) step towards setting up a machine in Grafana.
TODO:
The "Metrics settings" button introduced in [Cockpit 245](https://cockpit-project.org/blog/cockpit-245.html) has a new switch to set up exporting metrics to the network through the [PCP pmproxy service](https://linux.die.net/man/1/pmproxy) and the [Redis database](https://grafana-pcp.readthedocs.io/en/latest/datasources/redis.html):
If the machine uses firewalld, you can allow pmproxy in a particular zone afterwards:
After that, a remote [Grafana](https://grafana.com/) instance can read the machine's metrics through the [PCP Grafana plugin](https://grafana-pcp.readthedocs.io/), as described on the [PCP metrics feature page](https://cockpit-project.org/guide/latest/feature-pcp.html).
> metrics: Add switch for setting up pmproxy

- test/common/testlib.py
- test/run
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
Remove the logic of setting `NODE_ENV=development` for default
`TEST_OS`, and set it according to the addition of a new test scenario
called `/devel`.
Add also the option for `/firefox-devel` to be able to test a devel
build against Firefox.
>     test/run: add a "/devel" scenario

- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/format-dialog.jsx
- test/verify/check-storage-hidden
- test/verify/check-storage-luks
- test/verify/check-storage-mounting
- test/verify/check-storage-resize
- test/verify/storagelib.py
This is a sneaky attempt to solve a UI issue in #13192: By using a dropdown for switching on Encryption, we have a obvious place for adding the "Re-use old format and keys" option.
> storage: Offer choice of LUKS version 1 or 2 when formatting

- tools/webpack-make
Here's a few commits to tidy up `webpack-make` and teach it a more modern dialect of JS.
These are pretty much exclusively focused around the `Makefile.deps` generation code.
This PR doesn't change the result.  It's pure cleanup, with no side-effects:
```
⬢[lis@f34 cockpit]$ diff -ur master/dist webpack-make-refactors/dist
⬢[lis@f34 cockpit]$ 
```
> webpack-make refactors

- configure.ac
It's a leftover from when we built c-kubernetes.
Fixes #15965
> configure.ac: Drop unused golang check

- Makefile.am
- pkg/build
- tools/webpack-make
Using make to implicitly generate .gz output at `make install` time has
two major problems:
1) in srcdir!=builddir builds, these are the only files that land in
the builddir/dist/ directory, since all of the webpack outputs come
already shipped with the tarball
2) since `make install` is often run as root, these files end up
in your build tree, owned by root
At the same time, we don't want to integrate that into the webpack
process, because it would slow things down during development.
Move the .gz outputs to a separate variable in webpack-make, and deal
with them in a more explicit fashion from the Makefile, from an install
hook.
> build: handle .gz file output explicitly

- tools/webpack-watch
webpack-watch currently hands the following option to webpack-make:
-d "$mydir/../dist/$1/Makefile.deps"
which results in "tools/../dist/" appearing in several places in the
generated Makefile.deps, eg:
static: tools/../dist/static/manifest.json
Use the usual $(realpath -m) tricks to change our working directory to
the top_srcdir and call webpack from there with a fixed relative path,
the same way as pkg/build does.
> webpack-watch: rework path handling a bit

- pkg/storaged/format-dialog.jsx
- test/verify/check-storage-luks
- test/verify/check-storage-partitions
The filesystem will appear in the new partition, not the device with
the paritition table, ouch.  Cockpit would wait forever.
> storage: Fix mounting of just created partitions

- package.json
css-loader 3 depends on postcss 7 which is in conflict with the new ("11
hours ago") version 5.0.7 of optimize-css-assets-webpack-plugin.  This
is resulting in these warnings:
```
npm WARN postcss-discard-comments@5.0.1 requires a peer of postcss@^8.2.15 but none is installed. You must install peer dependencies yourself.
```
and the build failing like so:
```
/work/bots/make-checkout-workdir/node_modules/postcss/lib/processor.js:167
throw new Error('PostCSS plugin ' + i.postcssPlugin + ' requires PostCSS 8.\n' + 'Migration guide for end-users:\n' + 'https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users');
^
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
```
There are already quite a lot of issues filed against
optimize-css-assets-webpack-plugin about this …
> package.json: downgrade optimize-css-assets-webpack-plugin

- autogen.sh
- test/common/parent.py
- test/common/run-tests
- test/image-prepare
Most python things that need to use the bots first import parent.py to
set up the path to enable importing things from the bots directory.
Use this as a nice place for a hook to check out the bots, if they're
not already there.
With this in place, we no longer need the blanket call in autogen.
> test: check out the bots on an as-needed basis

- test/common/cdp.py
Hinting seems to involve some randomness and might produce slightly
different glyphs on different runs.  This is trouble for the pixel
tests.  Let's switch it off.
> test: Disable font hinting with Chromium

- HACKING.md
Installing the test suite's cockpit.pam.insecure is really bad advice --
it disrespects the distribution's standard policy, and is not even going
to work on systems without `pam_selinux`.
Fixes #15981
> HACKING: Install official PAM config

- autogen.sh
- test/common/testlib.py
- test/run
Totally "throw it over the fence" drive-by.
I think we can (and should) do better.
> pixel tests: checkout submodule on demand

- Makefile.am
This is being accidentally included via the "commited dist" mechanism,
based on its presence in the git.  It doesn't make sense to do that,
though: this directory might contain reference images, be empty, or
might not exist at all.
So we probably actually need to discuss this: does it make sense to dist this, after all?  Does anyone do integration tests based on a tarball *on the host*?  What about the checks that say we only run the pixel tests on fedora-34?  Is this meaningful for packit?
> build: don't "dist" test/reference

- .github/workflows/build-dist.yml
- test/verify/check-testlib
This seems to be the only thing which needs to be changed immediately.
Everything else is URLs in documentation, and GitHub will automatically
forward those.
> workflows: change 'master' to 'main' in a workflow

- containers/bastion/cockpit-auth-ssh-key
- doc/authentication.md
- doc/guide/authentication.xml
- doc/guide/cert-authentication.xml
- doc/guide/cockpit-http.xml
- doc/i18n.md
- pkg/metrics/metrics.jsx
- test/verify/check-metrics
- tools/cockpit.spec
We have a lot of links to our GitHub repository on the web littered
around in our source tree.  Change them all from master to main.
> various: replace 'master' with 'main' in urls

- pkg/users/account-details.js
- pkg/users/local.js
moment is deprecated, and the users page only uses absolute dates/times.
See #15979
-----
This is the first page for trying this, it's easy to convert. Let's discuss general style/coding issues here, then I'm happy to port some more pages.
The difference is negligible, with Intl it even looks a tiny bit better in "last login", and it's identical for "Access":
Master, English:
This PR, English:
Master, German:
This PR, German:
> users: Replace moment with Intl.DateTimeFormat

- pkg/static/login.html
- pkg/static/login.js
Fixes #15992
The `forEach` patch is at the top so the fix for IE (which we still need to "support", to tell IE users we don't support them). Hiding the `noscript` elements is at the bottom so it runs immediately after the browser constructs the DOM. (It's like `document`'s `ready` event, without event binding.)
> login: Move forEach patch & noscript inline

- test/verify/check-connection
- test/verify/check-networkmanager-basic
As spotted in the rhel-9-0 image refresh: https://github.com/cockpit-project/bots/pull/2144
> Adjust check-connection for OpenSSL 3, fix TestNetworkingBasic.testBasic regression

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
- tools/cockpit.spec
Previously this just failed with "unit pmlogger.service does not exist".
Instead, when enabling pmlogger, offer to install the package. Just like
with the button in the empty state, request a relogin afterwards to pick
up the new manifest.
> metrics: Fix enabling pmlogger in Metrics Settings if pcp is not installed

- pkg/metrics/metrics.jsx
- pkg/users/account-details.js
- test/verify/check-metrics
moment is deprecated, and the metrics page only uses absolute dates/times.
Clean up the generation of the "last 14 days" selector to avoid the two
useless back-and-forth conversions, and handle the "Today" case in a
more symmetric fashion.
Avoid any locale based formatting altogether with the journal timestamp
computations, as they expect a fixed format anyway. (We could also do
this with `@unixtimestamp`, but this does not generate human friendly
values in the Logs page search box.)
See #15979
> metrics: Replace moment with Intl.DateTimeFormat

- lgtm.yml
Add a lgtm.yml file to override the default command for the C build: we
gain nothing from running the full webpack build, so skip it.
> lgtm.yml: don't webpack when checking C code

- pkg/lib/journal.js
- pkg/lib/serverTime.js
- pkg/lib/timeformat.js
- pkg/metrics/metrics.jsx
- pkg/systemd/logDetails.jsx
- pkg/systemd/overview.jsx
- pkg/users/account-details.js
- test/verify/check-system-info
- test/verify/check-users
This is now the third page that moves from moment.js to Intl.DateTimeFormat, and we have enough commonality to factorize this. The Overview page is also part of check-page's "iterate through all known languages", so we get some nice test coverage with this.
This changes the format a bit, but it's now consistent between users, metrics, and overview pages:
German on main:
German on this branch:
English on main:
English on this branch:
Journal details page header on main:
Journal details page header on this branch:
> Create time format helper library, port Overview and Journal pages from moment to that

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
Always show the "Export to network" switch. Install the redis package if
redis.service does not exist.
Change the pmlogger existence check from `.state === undefined` to
`.exists`, as that is easier to understand, and we were already using
the latter for pmproxy.
Rename TestCockpitPcp to TestMetricsPackages, as this covers more
packages than just cockpit-pcp now.
-----
I interactively tested that with
systemctl stop pmlogger pmproxy redis; rpm -e --verbose cockpit-pcp pcp redis; systemctl daemon-reload
and then enabling pmlogger and pmproxy either one by one, or both together. After pmlogger and relogin (as advertised), history appears, and after pmproxy, querying metrics with
curl 'http://localhost:44322/series/labels?names=hostname'
works. Our integration tests can only test package …
> metrics: Install redis package on demand

- pkg/systemd/hwinfo.jsx
- test/verify/check-pages
- test/verify/check-system-info
This changes the visible date format, but makes it consistent with other
pages.
Main:
This PR:
(There is no spacing change - this was just me selecting an arbitrary part of  the screen)
> systemd: Port hwinfo page from moment to timeformat

- .github/workflows/npm-install.yml
These are being created/deleted semi-randomly, resulting in the
submodule showing up with a "dirty" diff in the parent project.
Ignore the noise.
bonus: fix up a bug in the error handling code of the workflow that I caught while testing it.
The working case can be observed here:
- https://github.com/allisonkarlitskaya/cockpit/pull/11#issuecomment-872198505
- https://github.com/allisonkarlitskaya/node-cache/blob/d981c33c850313d78f0ff81bd1650b24c7f9ef8d/.gitignore
The functional failure handling can be seen here (in response to a deliberately introduced syntax error in `package.json`, for testing purposes):
- https://github.com/allisonkarlitskaya/cockpit/pull/11#issuecomment-872202367
> npm-install workflow: ignore *.pyc files

- pkg/storaged/storage.scss
This is a super-simple alternative to #15914, with the minimum changes to fix hovering of the sidepanel, to make it consistent with the other panels in the middle of the page.
> storage: Make sidepanel hover consistent

- tools/make-bots
We probably all have a checkout of `bots/` somewhere already.  Martin
mentioned that he likes to setup a symlink to it when creating a new
worktree.  Let's automate that process in an elegant way.
Modify `tools/make-bots` to check for the presence of a symlink at
`~/.config/cockpit-dev/bots`.  If one is found, use the directory that
it points to as a target for a symlink from `bots`, as an alternative
to checking out our own copy.
A small matter of taste: we print the (relative) directory name of the
specified bots directory in the log message, but we actually link to the
`~/.config/cockpit-dev/bots` symlink itself.  That way you can update the
symlink as-needed (if working on another branch, for example) and all
existing cockpit repository worktrees will automatically switch over.
> make-bots: support symlinking to another bots dir

- test/common/testlib.py
The content of such a rectangle seems to stick out by one pixel
sometimes, probably because coordinates are rounded wrongly at some
point.
> test: Make ignored pixel test rectangles slightly larger

- pkg/storaged/dialog.jsx
- pkg/storaged/format-dialog.jsx
- test/verify/check-storage-format
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
Release note:
Fields have been re-ordered and warnings and errors are now consistent with Cockpit's common styling.
> storage: Polish for the Format dialog

- pkg/storaged/test-util.js
- pkg/storaged/utils.js
Some hosts don't have a static host name in /etc/hostname, or it is set
to "localhost" (which some OSes also count as "not really set"). These
get their host names via DHCP, which hostnamed considers "transient".
Consider the transient host name as well to decide whether a RAID is
local or not.
-----
This was spotted in https://github.com/cockpit-project/bots/pull/2168 , see that PR for details. I trigger an additional run against that PR to make sure it works now.
> storaged: Check transient hostname as well for RAID name

- .github/workflows/unit-tests.yml
Sometimes they hang eternally, and it's annoying to be told only that
late. They normally take 13 minutes, and we don't want them to take
longer than 20.
> workflows: Reduce unit test timeout to 20 minutes

- test/verify/check-connection
Most recent RHEL 8 re-disables core dumps by default by setting
`DefaultLimitCORE=0` (as in RHEL 7). Instead of making assumptions about
the test environment, ensure that core dumping is enabled for hostnamed.
----
Spotted in https://github.com/cockpit-project/bots/pull/2156 , running an extra check against that image refresh.
> test: Ensure core dump limit in TestConnection.testBasic

- .github/workflows/unit-tests-refresh.yml
- containers/unit-tests/setup.sh
This was dropped prematurely in commit 012483503e53, our rhel-8.4 branch
still uses it and backporting the sass changes is too intrusive for a
stable branch.
Also, drop our `COCKPITUOUS_GHCR_TOKEN` from the unit-tests-refresh workflow. The only other consumer of that is cockpituous, which I dropped in https://github.com/cockpit-project/cockpituous/pull/426 . After that, we can eliminate that secret.
> containers/unit-tests: Put back sassc

- test/verify/check-metrics
- The login form now requires actual typing to trigger the handlers.
- Dashboard CSS classes changed a bit. Let's avoid any assumption and be
satisfied with the "Welcome" string appearing anywhere on the page.
- "Save & Test" button is now called "Save & test"
- The "Dashboard" tab's aria label moved from the containing `<li>` into
the `<a>`. That makes a label-based selector awkward, so instead
select by link target in the tabs section.
- The "Delete dashboard" button in the data source import does not have
any useful properties any more, and that check is not important. Drop
it.
- The dashboard panel classes changed in a non-overlapping way. Replace
the `.panel-wrapper` selector with a generic `<div>` one.
With these changes the test works for both Grafana 7.5 and 8.0.
----
This blocks …
> test: Adjust TestGrafanaClient for Grafana 8

- test/run-verify-host.sh
Current RHEL 9 Testing Farm instances have a broken and mostly empty
epel.repo file. Clean it up before installing the real epel-release rpm,
otherwise that rpm won't overwrite the stub.
---
This is the same fix as for c-machines in https://github.com/cockpit-project/cockpit-machines/pull/246 .
> fmf: Clean up broken stub epel repo

- Makefile.am
Commit a6e2689e848a0173b45a6e70cf15de2bf87b8696 rearranged the
conditionalisation of our docs targets and accidentally introduced an
unconditional dependency on dist/guide/html/index.html to the
install-data-local: rule, even if docs were disabled.
We can't conditionalise the rule itself, for fear of bringing back
automake's complaints about duplicated definitions, so introduce a
variable.  This isn't pretty, but it works.
Fixes #16064
> build: fix `make install` with `--disable-doc`

- .github/workflows/npm-install.yml
- .github/workflows/prune-dist.yml
- .github/workflows/webpack-jumpstart.yml
After a bit of a trial period, the names `cockpit-dist upload` and
`COCKPIT_DIST_DEPLOY_KEY` seem a bit awkward.  Rename them to just
`cockpit-dist` and `DEPLOY_KEY`.
Ditto `node-cache upload` and `NODE_CACHE_DEPLOY_KEY`.
The new environments and secrets have already been deployed.  The old
ones can be pulled down after we land this.
> workflows: rename environments and secrets

- test/run-verify-host.sh
Do the same as in cockpit-machines:
https://github.com/cockpit-project/cockpit-machines/blob/main/test/browser/browser.sh#L23
> fmf: Really force EPEL 8 on RHEL 9

- pkg/storaged/crypto-keyslots.jsx
The previous checks in CryptoKeyslots don't completely rule out that
slots === null, which is a potential crash. The code below does error
handling based on "keys is empty", so set it to an empty list on a null
slots value.
Spotted by Coverity.
Fixes #15988
> storaged: Handle null slots

- Makefile.am
- configure.ac
- po/Makefile.am
- src/bridge/Makefile.am
- src/ws/Makefile-ws.am
- tools/node-modules
Here's a bunch of changes to `po/Makefile.am` to make it possible to build `cockpit.pot` without needing to do the whole automake thing.
You can see it in use from a new workflow here: 
- https://github.com/allisoninc/cockpit-weblate/blob/main/.github/workflows/sync-pot.yml
- https://github.com/allisoninc/cockpit-weblate/runs/3048500342?check_suite_focus=true
Together with the new workflow this solves one half of the "what do we do about weblate?" cockpituous token puzzle: this part ends up requiring no credentials at all, since it runs out of the -weblate repository.
The other half still open, of course, is getting the .po files from the weblate back into cockpit and opening a PR and running tests.  That's gonna be a bit of work still....
The changes here are more or less harmless on …
> build cleanups for cockpit.pot generation

- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-mtu
- test/verify/check-networkmanager-team
- test/verify/check-networkmanager-vlan
Otherwise it could happen that the dialog is not fully rendered yet.
Observed in the wild with the bonding dialog's MAC dropdown triangle
(presumably as the list was still empty).
----
[Failed test example](https://logs.cockpit-project.org/logs/pull-16087-20210712-163822-6a95f0da-fedora-34/log.html#64-2)
> test: Wait for networking dialog initialization before pixel test

- pkg/lib/timeformat.js
- pkg/systemd/overview-cards/systemInformationCard.jsx
- pkg/systemd/overview.jsx
Introduce a new timeformat.distanceToNow() wrapper for this.
Drop moment initialization from systemd page, as this was the last usage
of moment.
----
This looks a bit different now, date-fns adds the "about.." as it is rounded:
> systemd: Move system uptime from moment to date-fns

- pkg/packagekit/history.jsx
- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
This changes the "last checked" slightly for short time intervals (as
moment's and date-fns' durations are a bit different), and moves from
ISO to our standard localized format for the update history.
"Last checked" on main:
With this PR:
History on main (all langs):
History with this PR (standard localized format that we now use everywhere):
> packagekit: Port from moment to timeformat

- pkg/lib/cockpit-components-file-autocomplete.jsx
This will allow us to fix https://bugzilla.redhat.com/show_bug.cgi?id=1866225
Fixes https://github.com/cockpit-project/cockpit/issues/14491
See more info: https://github.com/patternfly/patternfly-react/issues/5502
> lib: Retaining keyboard-entered value in file autocompletion typeahead text field when focus leaves input away

- test/common/testlib.py
Normally, attach() is being called for dynamically generated files, and
it is (moderately) desirable to move them into the attachment directory
instead of copying them. But this must not happen for static source code
files, otherwise the second call will fail bitterly if two tests run in
parallel. This currently breaks cockpit-podman a lot.
Switch attach() to copy files by default, which is the safe thing to do.
Add a `move` flag to opt into the optimization, and use it for
known-safe dynamically generated files like screenshots and journals. In
particular, this stops moving common/pixeldiff.html and similar git
tracked files out of the source tree.
----
I am not actually sure how we didn't notice that before -- right now it's absolutely impossible for me to get …
> test: Don't delete pixeldiff source code through attach()

- tools/cockpit.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1983077
----
Validated  with
test/image-prepare -qB fedora-34
rpm -q --scripts -p tmp/build-results/cockpit-ws-*.rpm
Now it is correct:
```
if grep --color=auto pam_cockpit_cert /etc/pam.d/cockpit; then
```
> spec: Fix syntax error in PAM grep

- HACKING.md
- tools/webpack-make
- tools/webpack-watch
This allows developers to rapidly iterate on code that gets tested in
our standard VMs without having to manually copy the code. This
minimizes the cycle to "save" -- "wait a bit" -- "press reload in the
browser".
webpack-watch has no actual option parsing, so relax the positional
argument checking and pass on any additional arguments to webpack-make.
This requires to put the options *after* the page name, but we'll get
used to that quickly.
----
As my laptop doesn't have libvirt, setroubleshoot etc. installed, I spend the majority of my development iteration with manually calling `scp -r` after each successful build. This gets rid of this annoyance, especially as I occasionally forget the scp and then get confused why my changes don't apply. It's not exactly a pretty implementation in …
> tools: Add --rsync option to webpack-{watch,make}

- test/verify/check-system-s4u-ssh
This is the more common case, without a remote ssh host in between. Not
too many surprises, just that this uncovers that the current approach of
setting up the delegation rule does not scale. Filed as
https://pagure.io/freeipa/issue/8927
> test: Test sudo on cockpit machine in check-system-s4u-ssh

- pkg/metrics/metrics.scss
metrics: Adjust history metrics graph labels to avoid overlapping
* Increase the width of half-columns from 5% to 8%, as otherwise there
is not enough space for the label even in English on wide pages. It
does not hurt to use the space that we have to provide a little more
detail on the half-column then.
* Reduce the top label width for narrow browsers in two steps, as
otherwise they begin to overlap.
* Use absolute font sizes instead of relative ones, as otherwise the
sublabels become too small (as they are relative to the parent label,
not to the global default), and we can also assume that the PF
standard sizes are sane.
Addresses half of #16016; very narrow sizes/mobile mode still needs to
be fixed (probably through rotating the labels).
main:
This PR:
main:
This PR:
main:
This PR: …
> metrics: Adjust history metrics graph labels to avoid overlapping

- Makefile.am
- src/common/Makefile-common.am
build: clean up distdir rules
I've always wondered why we split our dist-hook up so randomly: it seems
like some group of things is in one place and another group in another.
Then there's the one for displaying the error message for the docs.
Replace this with a combined override rule for `distdir`.  We're now in
control of the process: of course, we call distdir-am first, but after
that, we can do everything we need, and from one place instead of three
different ones.
In addition to cleanup, this has two positive impacts:
- `make dist` after `--disable-doc` will now fail immediately, not
after a bunch of work is already done
- we no longer depend on `$(BUILT_SOURCES)` here, which avoids
needlessly building some files which won't be disted anyway
> clean up dist rules

- doc/guide/feature-pcp.xml
Update broken `pcpstat` and `pcpinfo` links with working linxu.die.net links. On PCP Metrics page
If you feel that the updated links are not the best choice feel free to edit or drop them below.
> Replace broken links with linux.die.net links

- test/verify/check-system-s4u-ssh
Creating the impersonating S4U ticket for the user will eventually
happen in cockpit-session. This must not require the admin
password/kinit. Conceptually, it is supposed to only use the cockpit
krb5.keytab.
Drop the call, it works fine without it.
> test: Drop unnecessary kinit admin@COCKPIT.LAN in check-system-s4u-ssh

- doc/guide/Makefile-guide.am
Due to two uses of $(AM_V_GEN) and a `rm` on a separate line, the
current output from the docs rule looks like
GEN      dist/guide/html/index.html
GEN      dist/guide/html/index.html
rm -f dist/guide/html/cockpit-guide.proc
combine everything into a single invocation to get it looking like
GEN      dist/guide/html/index.html
> doc build: tweak rule visual output

- .github/workflows/webpack-jumpstart.yml
- .gitignore
- pkg/build
Using the .merge_commit_sha from GitHub is seriously dangerous (it's
usually not up to date when the workflow gets launched) and kinda
pointless (it's completely transient, and will change next time someone
pushes main).
Perform the merge for ourselves to dodge the first problem and provide
some information to help reproduce the merge in order to solve the
second problem.
- https://github.com/allisoninc/cockpit/pull/2
- (main push) https://github.com/allisoninc/cockpit/runs/3162944269?check_suite_focus=true
- (PR) https://github.com/allisoninc/cockpit/runs/3162948761?check_suite_focus=true
> webpack-jumpstart.yml: perform merge for ourselves

- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
RHEL systems can be installed from repositories other than the Red Hat
CDN, like a DVD, UBI, or e.g. the AWS cloud mirror. These don't require
a subscription.
There is no proper dnf/subscription-manager API to tell whether a system
actually needs a subscription, so introduce a heuristics: If the
"coreutils" package is available from any repository, then consider the
repos good enough to deliver operating system updates (as opposed to
some COPR etc. which just delivers some auxiliary package).
https://bugzilla.redhat.com/show_bug.cgi?id=1970057
> packagekit: Handle unregistered RHEL systems with non-CDN OS repository

- packit.yaml
- tools/git-utils.sh
- tools/webpack-jumpstart
- a `--rebase` option will allow rebasing the local tree to get the same tree we built the cache against
- update packit to use `--rebase`
> implement `tools/webpack-jumpstart --rebase`

- src/ws/session.c
- test/verify/check-system-realms
Storing delegated kerberos tickets into the default (user-)global
default keyring is a bit problematic: It changes the available
credentials to all other currently running sessions of that user, and
prevents being able to clean up the ccache after the session ends. The
global default keyring is really aimed at users doing `kinit` explicitly
(or the initial desktop session login).
Move to what SSH does [1], create a session specific file ccache in the
user's XDG runtime directory, and export it through `$KRB5CCNAME`.
Delete the ccache at session end. logind will clean up the runtime
directory for us after a while as well, which is a nice second line of
defense.
The user can always copy the ticket somewhere else while the session is
running, so this does not need to be a 100% robust …
> ws: Move to session specific kerberos keyring

- .gitignore
Having a / at the end of the ignore pattern causes a symlink not to be
ignored.  For some time now, tools/make-bots can put a symlink there, so
ignore that too.
> .gitignore: ignore /bots even if it's a symlink

- src/ws/session.c
They are prerequisites for the S4U stuff, but apply to the already existing GSS authentication as well. I want to test them separately, and they should be straightforward to land.
> Some small cockpit-session kerberos fixes

- containers/unit-tests/run.sh
The unit tests container prints out a message at 50m with some
information about stuck processes.  That was useful when the tests
timeout was 60m, but isn't so helpful now that the tests are being
terminated after 20m.  Reduce the timeout to 18m so we still get in
before the deadline.
> containers: lower timeout for debug output

- .github/workflows/webpack-jumpstart.yml
- tools/git-utils.sh
- tools/node-modules
From the sunday-trainrides-with-nothing-to-do department:
`node:14` is a pre-cached image on GitHub, so it's faster.  I had to fix a few problems with old git versions, but it seems to work now.
See
- https://github.com/allisoninc/cockpit/pull/3
- https://github.com/allisoninc/cockpit/pull/3/checks?check_run_id=3213790366
> move webpack jumpstart build to `node:14`

- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
PackageKit 1.2.4 finally fixed a long standing bug [1] about mis-parsing
the "severity" field for an update. The current version now finally
returns correct results. Adjust the tests to factorize the "supports
severities" into a `self.supports_severity` flag, and make it dynamic
based on the PackageKit version.
Also adjust the old bugs.freedesktop.org reference to the current one
(the bug tracker got migrated to GitHub a while ago).
[1] https://github.com/PackageKit/PackageKit/issues/268
----
Blocks https://github.com/cockpit-project/bots/pull/2265
> test: Adjust for PackageKit 1.2.4 severity parsing support

- pkg/packagekit/kpatch.jsx
- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
Now there are patches available, I tested this on real rhel 8.4 machine.
@garrett and @martinpitt WDYT?
kpatch is available, but not installed:
kpatch settings dialog:
Kpatch is installed, enabled and all the fun stuff. Also patches are available (see in the list)
There are some patches applied:
This one is probably something we don't want. I run different kernel, but I have patches for different kernel installed. I guess I should not list it? (the other kernel is still available, I just don't use it right now). Should it list only installed patches for the current kernel?
Release note:
On operating systems with support for live kernel patching Cockpit now offers to enable this feature. Software updates page shows if `kpatch` is supported, if there are any patches active as well as …
> packagekit: Introduce kpatch integration

- test/README.md
With the IdentitiesOnly option, ssh only offers the configured
IdentitiyFile. This option is useful for situations where the ssh agent
offers too many different identities causing an authentication failure.
> test: Add IdentitiesOnly to the ssh config example

- test/verify/check-system-realms
Similarly to commit 7a6b68a8afc, reset failed systemd units. Otherwise
they appear as the first few lines in the terminal (through a bash
profile plugin) and break the test assumption of the prompt being in the
first line.
----
Seen in https://github.com/cockpit-project/bots/pull/2274 in [this failure](https://logs.cockpit-project.org/logs/pull-2274-20210803-145127-82795814-fedora-33-cockpit-project-cockpit/log.html#254-2)
> test: Reset failed units in TestKerberos.testNegotiate terminal test

- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/storage.scss
Follow-up to #15844, to fix the HTML.
Would've been in #15870, but I wanted the previous fix to be implemented quickly. This changes a lot more.
> storage: Use semantic HTML in verify key modal

- .gitignore
Ignore all Test file extensions in a general manner so for example
Test*.gz is not missing.
> Generalize ignoring test output files

- autogen.sh
- configure.ac
Since autoconf 2.70 all obsolete macro warnings are turned on by default and prints the following message when running `./autogen.sh`.
```
configure.ac:45: warning: The macro `AC_PROG_CC_C99' is obsolete.
configure.ac:45: You should run autoupdate.
./lib/autoconf/c.m4:1659: AC_PROG_CC_C99 is expanded from...
configure.ac:45: the top level
configure.ac:47: warning: The macro `AC_ISC_POSIX' is obsolete.
configure.ac:47: You should run autoupdate.
./lib/autoconf/specific.m4:550: AC_ISC_POSIX is expanded from...
configure.ac:47: the top level
configure.ac:48: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:48: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:48: the top level
configure.ac:95: warning: The macro …
```
> build: Remove obsolete autoconf macros

- src/bridge/bridge.c
- src/common/cockpitconf.c
- src/ws/cockpit-session-client-certificate.c
- test/verify/check-packagekit
It seems we really need to update our unit-tests container to pull in a recent pycodestyle.. I'm doing that in PR #16207
> Fix version 250 Coverity regressions, fix pycodestyle regressions

- .github/workflows/unit-tests.yml
- containers/unit-tests/scenario-distcheck.sh
Since commit 4077dee3d2f65b our unit test runs did not run pycodestyle
any more, as that started to skip the pycodestyle check in a non-git
tree (such as the unpacked tree that `distcheck` runs in). As
test-static-code does not run in `check-memory` either, none of the four
scenarios ended up running it.
So explicitly call it in the distcheck scenario, and relatively early so
that failures (which happen quite often) are easier to spot in the log.
----
Spotted in PR #16204 , which also has a commit to actually fix the current pycodestyle errors. Until that lands, this PR should fail.
Also fix the timeout in the workflow.
> containers: Properly run test-static-code during unit tests

- doc/guide/cockpit-file.xml
We got in the last weeks two users who struggled with `cockpit.file()`
as they were trying to resolve files in relative paths.
> doc: Document paths in cockpit.file

- pkg/packagekit/updates.scss
The Red Hat font numbers are not all the same size which makes the
progress bar "jump" when the progress changes. As a workaround, the
label now reserves enough space so the progress bar now doesn't jump
around.
> packagekit: don't make the progress bar jump

- test/verify/check-packagekit
See [failure](https://logs.cockpit-project.org/logs/pull-2281-20210806-023413-e20d8773-fedora-testing-dnf-copr-cockpit-project-cockpit/log.html#93-2) in https://github.com/cockpit-project/bots/pull/2281
> test: fedora-testing does not have kpatch

- pkg/base1/cockpit.js
Checking `documents.scripts` was buggy: It only ever considered the last
`<script>` (introduced 7 years ago in commit c4935df4bf16).
This breaks browsers like Brave (and presumably others), where
cockpit.js is the second-to-last script (the last one is some unnamed
empty entry).
But all of that complicated checking isn't necessary any more: The last
vestiges of require.js and the AMD loader got dropped three years ago in
commit ff5149ec5e. There days there is one and *only* one way to use
cockpit.js: Through a global `<script>` import. (Our webpack
configuration (and that of starter-kit and all cockpit-* derivates)
declares `cockpit` as an external.)
So drop the unnecessary, broken, and hard to understand/debug code, and
always register cockpit on the global `window` object.
Fixes #12745 …
> base1: Fix and simplify cockpit.js loading

- test/verify/check-system-services
Our RHEL images have EDT timezone, so when TestServices.testBasic was
started after 20:00 EDT, `date` would still print the previous day
(evening), while the browser (which runs in UTC) would already show the
next day morning. So to determine what the browser considers as "today",
make a JavaScript query instead of `date`.
This was a regression from commit 08541cbe5.
---
[example](https://logs.cockpit-project.org/logs/pull-2284-20210807-023327-c580b9a5-rhel-8-5-cockpit-project-cockpit/log.html#259-2) (commonly happen around image refreshes).
Reproducer: `timedatectl set-ntp off; timedatectl set-time '23:00:00'`
> test: Fix TestServices.testBasic for different VM/browser time zones

- test/common/testlib.py
- test/verify/check-metrics
- test/verify/netlib.py
- test/verify/storagelib.py
Only two of these messagess still actually appear, drop the other two.
The two "no such metric: kernel.all.cpu.nice: Unknown metric name"
instances in check-metrics happen because these two tests start with
an empty /var/log/pcp and pmlogger.service stopped, so that indeed the
metrics channel will not be able to find any metric (and
`kernel.all.cpu.nice` is just the first one that it tries). So these are
legitimate, ignore these in the specific tests with a comment.
Move the networking/storage ones into the particular test classes and
make them more specific, to avoid introducing more of them.
See #15625
> test: Make unexpected PCP error messages more specific

- pkg/lib/machine-info.js
- pkg/systemd/hw-detect.js
- pkg/systemd/hwinfo.jsx
- pkg/systemd/overview-cards/systemInformationCard.jsx
If DMI is not available, fall back to reading the model and serial
number from /proc/device-tree/
----
On my RasPi 3  on main, Overview and hwinfo:
On this PR:
As I [mentioned here](https://github.com/cockpit-project/cockpit/issues/7476#issuecomment-894980354), I tried hard to fake a /proc/device-tree in our tests, but did not find a way to do this. So for now I tested this on my actual RasPi.
> systemd: Read hardware info from DeviceTree

- test/verify/check-system-info
In some cases, the VM's DMI reports the memory chip as "DIMM0" instead
of "DIMM 0". Let's not make too many assumptions about this, that's
outside of our control. Relax the string to just check for "DIMM".
[example](https://logs.cockpit-project.org/logs/pull-16217-20210809-081100-faea4110-rhel-9-0/log.html#218-2)
> test: Relax system DMI string test

- tools/urls-check
It seems that just `Mozilla/5.0` was not enough for https://bugzilla.mozilla.org
as it was returning `400 - Bad request`. Putting there something more
real makes it work again.
Fixes #16221
> tools: Update user-agent in urls-check script

- doc/guide/cert-authentication.xml
- doc/guide/sso.xml
- pkg/systemd/README-realmd.md
- src/tls/cockpit-certificate-helper.in
- src/ws/session.c
- test/verify/check-system-realms
- test/verify/check-system-s4u
Turn the Proof of Concept in check-system-s4u-ssh into cockpit-session
code to create an S4U ticket for the user in tlscert authentication
mode. This will be used in the future to further authenticate to sudo or
ssh, but this requires further configuration. In the default FreeIPA
configuration, these tickets are not trusted by anything, so it is
harmless to create them by default.
The testClientCertAuthentication in TestIPA covers the successful case,
in TestAD the "not available" case (no unexpected error messages), and
in TestLogin the case where the machine is not joined to a domain.
Adjust check-system-s4u-ssh to acquire the S4U ticket from cockpit
through a TLS certificate login, instead of the custom Python script.
-----
Documentation preview is on https://piware.de/tmp/guide-s4u . …
> ws: Create S4UProxy user ticket on tlscert authentication

- test/verify/netlib.py
- test/verify/storagelib.py
Commit 8bd081d8c1712c made the error message more specific, but it turns
out that a variant sometimes happens as well:
pcp-archive: instance name lookup failed: network.interface.in.bytes.5: Instance identifier not defined in the PCP archive log
So change the pattern back to what we had before that commit.
----
[example](https://logs.cockpit-project.org/logs/pull-16224-20210810-144638-675c82b8-fedora-33/log.html#65-2)
> test: Re-ignore variant of PCP error message

- pkg/networkmanager/networking.scss
Use display flex to allow space for the "add button", so it appears on
the same line as the select element. To keep the minus buttons button
aligned with the other buttons the margin-right has to be explictly
removed.
Fixes: #16219
> networkmanager: Align add button next to adresses selection

- pkg/shell/machines/machines.js
- pkg/systemd/overview.jsx
- test/verify/check-shell-host-switching
- test/verify/check-system-info
The systemd hostnamed D-Bus API returns Hostname for the configured
system hostname. This issue is only visible when no static hostname is
configured as PrettyHostname and StaticHostname are then empty.
Fixes #9909
> systemd: Correct typo HostName -> Hostname

- src/bridge/cockpitpcpmetrics.c
- src/bridge/test-pcp-archives.c
`label.ll_start.tv_sec` is a 32 bit type on armhf and other platforms.
Multiplying with 1000 causes an integer overflow, which completely
messes up the time stamp. Fix this by casting to a 64 bit type first.
Fixes #16083
------
I validated the bug and fix on my RasPi 3. The fix is good, but I'd like to create a unit test for this.
> bridge: Fix PCP archives on 32 bit architectures

- test/verify/check-system-realms
test/verify/check-system-realms:711:18 f-string is missing placeholders
test/verify/check-system-realms:675:32: W605 invalid escape sequence '\['
> tests: Fix pyflakes warnings

- test/verify/check-connection
We have a regexp to allow the journal message:
self.allow_journal_messages(r"cannot reauthorize identity\(s\): unix-user:.*")
which is occasionally thrown by cockpitpolkitagent.  Sometimes this
message ends up coming over ssh, though, and then it hits the journal
looking like this:
Aug 16 05:26:22 rhel-8-5-127-0-0-2-2201 cockpit/ssh[2210]: cockpit-bridge-Message: 05:26:22.822: cannot reauthorize identity(s): unix-user:admin
(ie: a journal message from 'cockpit/ssh' containing a glib-formatted
message string, as was written by cockpit-bridge to ssh's stderr).
We can fix that by adding a `.*` to the start of the message pattern.
The reason that we weren't seeing this failure more often is that it's
extremely rare: I had to run the test 30 times in a loop to get the
failure, and I think even …
> test: fix an allowed journal message regexp

- test/verify/check-metrics
For example here: https://logs.cockpit-project.org/logs/pull-16234-20210816-101305-cf949df2-fedora-34-devel/log.html#47
> test: "pcp: Unknown metric" also happens in TestCurrentMetrics

- test/verify/check-selinux
The message about "Allow zebra..." is changing in some distros and seems
likely to change again.  Instead of trying to build a regexp around
that, let's just match on a different item from the table.
> test: change match string in selinux modifications table

- test/verify/check-system-realms
- test/verify/check-system-s4u
[ regression introduced in #16168 ]
It's true that we clean up /var/cache on creating images, but sometimes
we install packages onto the system after image creation (for the copr
variant, for example) and that can recreate the directory.
Use `mkdir -p` to avoid the error.
Also: use `mkdir -Z` instead of running `restorecon` separately.
That should help us with some of these failures: https://logs.cockpit-project.org/logs/pull-2313-20210817-130647-dde6097b-fedora-testing-dnf-copr-cockpit-project-cockpit/log.html#250-2
```
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2021-08-17T13:35:52Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
mkdir: cannot create directory …
```
> test: allow for existing /var/cache/krb5rcache

- pkg/lib/timeformat.js
- pkg/systemd/overview.jsx
As part of #13882 improvements, when the succesful/failed login date is
in the same year as the current year drop the year in the date time
output. Intl.DateTimeFormat has no standard preset without a year in it.
> systemd: Don't show the current year for logins

- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-keyslots.jsx
- pkg/storaged/crypto-panel.jsx
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/format-dialog.jsx
- pkg/storaged/fsys-panel.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/jobs-panel.jsx
- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/side-panel.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-hidden
- test/verify/check-storage-luks
- test/verify/check-storage-mounting
- test/verify/check-storage-resize
- test/verify/check-storage-used
Cockpit used to expose the device mapper device that implements encryption.  Now we fold that away and pretend the content sits directly in the backing device.
First demo: https://www.youtube.com/watch?v=DASfi39YGZ8
Second demo: https://www.youtube.com/watch?v=kSYuO0WZHWU
Third demo: https://www.youtube.com/watch?v=VnzG2VcDyik
Fourth demo: https://www.youtube.com/watch?v=-1L71pzWdhs
Release notes:
Cockpit used to make the encryption layer of a encrypted filesystem explicit: It had its own row in the content table and it would be referred to in other places in the UI.  Now the encryption layer is hidden away and Cockpit pretends encryption is a inherent property of a Filesystem.
> storage: Integrate encryption better

- containers/bastion/Dockerfile
- containers/ws/Dockerfile
Tested with
```
podman build -t cockpit/ws containers/ws
podman build -t cockpit/bastion containers/bastion
podman run -it --rm -p 9999:9090 localhost/cockpit/bastion
```
Our CI does not really cover this `FROM:`, as it replaces it with the pre-built `cockpit/base` container on our images. I.e. that already tests on Fedora 34. This only affects the official production container that we push during release.
> containers: Bump bastion and ws containers to Fedora 34

- tools/cockpituous-release
Only support two releases at a time.
> cockpituous: Stop releasing to Fedora 33

- HACKING.md
- tools/webpack-watch
In 8d3a015dcc7c0cf1b the -d option was removed in favor of positional
arguments.
> webpack-watch: update webpack-make invocation

- pkg/lib/machine-info.js
- test/verify/check-system-info
Cheap or self-built machines often have template DMI information which
was not set by the vendor. Ignore such fields and treat them like
empty/absent values. This will trigger the fallback to the board
name/vendor, which in many cases is present and valid; if that does not
work either, just don't show any hardware name/version at all.
Fixes #7476
> systemd: Ignore "To Be Filled By O.E.M." DMI values

- test/common/testlib.py
Sometimes `TestPages.testBasic` produces this after looking at network
related pages. Put it back into generally allowed patterns (partial
revert from commit 8bd081d8c).
----
[example](https://logs.cockpit-project.org/logs/pull-16281-20210831-121051-a153938e-debian-testing/log.html#93)
> test: Allow another variant of pcp-archive messages

- test/verify/check-networkmanager-team
NetworkManager seems to sometimes not assign a MAC address to the team
interface. This is unrelated to what the test is trying to do, so drop
this particular check.
---
This breaks every other gating test. [Example](http://artifacts.dev.testing-farm.io/e76f2ea5-8429-42ad-91dc-26e8e07e37e6/).
> test: Drop waiting for team MAC address

- test/common/testlib.py
It sometimes also looks like this:
pcp-archive: instance name lookup failed: disk.dev.read_bytes.1: Instance identifier not defined in the PCP archive log
---
[example](https://logs.cockpit-project.org/logs/pull-16288-20210901-082742-3b5e484e-fedora-35/log.html#133)
> test: Relax expected "instance name lookup failed" PCP message

- test/verify.fmf
- test/verify/check-networkmanager-firewall
It is not actually being used any more by tests, it has loads of race
conditions due to being a dynamically added zone, and requires expensive
libvirt test dependencies in FMF/gating tests.
Only keep waiting for the libvirt zone in firewalld if libvirt is
actually running and the default network exists. Otherwise this could
happen during tests and confuse the expected zone count.
---
This is a more intrusive, but better (if it works) alternative to PR #16287.
This should hopefully help for failures like [this (our CI)](https://logs.cockpit-project.org/logs/pull-16281-20210831-184227-dbe34f3f-fedora-35/log.html#56-2) and [this (testing farm)](http://artifacts.dev.testing-farm.io/e76f2ea5-8429-42ad-91dc-26e8e07e37e6/). This is our second and third biggest flake right now.
> test: Drop libvirt startup in check-networkmanager-firewall

- test/verify/check-packagekit
In downstream gating, a package can get installed to a test VM, which
could affect the status on updates page. Use tracer to make
the test robust and find out the correct status to be expected.
> test: Make TestUpdates.testBasic more robust

- .github/workflows/release.yml
We want our node-cache to have tags corresponding to cockpit releases
[1], so that we get a proper replacement for the old manually built
cockpit-cache-XXX.tar.xz artifacts. These are useful for having a
straightforward way for taking a release tarball, getting a matching
node_modules, and thus being able to patch/build cockpit from a release
(i.e. what distributions do all the time).
So far we have manually tagged node-cache for a few releases, and it's
part of our release process [2], but we have forgotten a few times --
and this is perfectly automatable.
Add this to our standard release workflow. It must run in a separate
job, as it uses the deploy key from the "node-cache" environment; this
secret is (deliberately) not present in the "release" environment for
the container. Delete the …
> workflows: Tag node-cache on releases

- containers/bastion/README.md
- test/containers/check-bastion
In Fedora ≥ 34, the container is not able to read the passed key any
more due to SELinux restrictions. Use the designated docker/podman
volume flag `:Z` to fix that.
Backported from main commit 5954eedaae0cf18
> [r85] containers: Fix SELinux context of SSH private key

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
- pkg/systemd/services/service-tabs.jsx
- pkg/systemd/services/services-list.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/services.scss
- pkg/systemd/system-global.scss
- test/verify/check-system-services
pficon classes seem to not work any more, at least for the services
page.
Start using the icons from @patternfly/react-icons, which will make the
icons reappear.
This also enables us to stop including PF3 in this page.
> services: fix missing icons from the services details UI

- pkg/systemd/overview-cards/systemInformationCard.jsx
- pkg/systemd/overview-cards/usageCard.jsx
- pkg/systemd/overview.scss
no-left-padding class is redundant - the padding of the 'a' element
was 0 by default
The rest of the rules don't apply at all.
> overview: remove some unused CSS

- tools/webpack-make
- tools/webpack-watch
This removes the wrapper script `webpack-watch` and makes `webpack-make` if it's called as `webpack-watch`.
> make webpack-watch a symlink of webpack-make

- containers/unit-tests/setup.sh
libssh got a recent security update, include corresponding debug symbol
repository.
---
* Fixes [failed container refresh](https://github.com/cockpit-project/cockpit/runs/3519542139?check_suite_focus=true)
> containers/unit-tests: Add missing ddebs for security updates

- HACKING.md
- tools/webpack-make
Since commit 92acdea1e1ee3 it is not possible any more to run
webpack-watch with eslint, as there is no option to enable it, and the
program overwrites `ESLINT=1` from the environment.
Drop the weird inconsistency between webpack-{make,watch}), and default
to running eslint in both modes. Then `--no-eslint` can be used to
disable it.
> tools: Provide eslint mode for webpack-watch

- pkg/base1/test-dbus-common.js
- src/ws/mock-service.c
I saw this happening in PO refreshes, let's backport this to stable branches.
> [r85] Backport dbus unit-test fix

- pkg/sosreport/index.js
This reduces the webpack'ed sosreport.js from 93 to 4 kB.
---
I interactively tested the success, cancel, and error cases, and it behaves and looks identical.
> sosreport: Port from jQuery to DOM API

- test/common/pixeldiff.html
I tested this with
- downloading a few pixel diff pngs from https://logs.cockpit-project.org/logs/pull-16303-20210905-184914-a34fdab9-fedora-34/ 
- run `python3 -m http.server` in test/common
- open http://localhost:8000/pixeldiff.html#TestStorageLuks-testLuks-tab in browser, and reload after every change
It now looks and behaves identical to the original.
> test: Port pixeldiff.html from jQuery to standard DOM API

- test/common/testlib.py
- test/verify/check-system-services
Test the list when searching for all "Test service", so that the whole
page contents is entirely defined by the test, and only shows
test.service and test-fail.service.
Test details with making sure that the log card is present, but ignore
the date heading and actual log contents. In mobile mode, this has an
interesting additional challenge of making sure that the horizontally
scrollable nav bar is all the way to the left -- if we need this more
often, this could become a testlib helper.
> test: Add pixel tests for Services list and details

- test/common/testlib.py
- test/verify/check-system-services
This was introduced in commit e62035b8a0af, but Browser.cdp already has
a `mobile` flag. Use that instead.
> test: Re-drop redundant Browser.is_mobile

- test/run-verify-host.sh
We should have https://github.com/cockpit-project/cockpit/pull/16252 on the rhel-9.0 branch to reflect reality, and get a clean fmf `ref:`.
> [rhel-9.0] backport FMF hacks

- pkg/apps/application-list.jsx
- pkg/apps/application.css
- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-overrides.scss
Attempt to solve https://github.com/patternfly/patternfly/issues/4206 by:
- remove our heading override
- change our remaining overrides to not apply to PF4 (anything a "pf-" in the class attribute)
- fix anything that looks wrong afterward
> Try to not step on PF4 when adjusting headings

- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/lib/patternfly/patternfly-overrides.scss
- pkg/shell/shell.scss
- pkg/shell/superuser.jsx
`.blank-slate-pf` is a PF3 (only) class, and the p + p margin hack only
happens on pages with PF3+PF4. Move these two to
patternfly-overrides.scss, so that they get cleaned up together with PF3
removal.
Similarly, the form group and modal box padding are PF4 specific fixes,
move them to patternfly-4-overrides.scss.
`.modal-content` is a PF3-only class which is only being used in the
shell -- move it to shell.scss.
Now page.scss only has `.ct-*` classes and changes which are genuinely
Cockpit specific (such as heading size changes).
Fixes #15425
> lib: Some page.scss cleanups

- test/common/testlib.py
- test/verify/check-packages
- test/verify/check-pages
- test/verify/check-session
- test/verify/check-shell-host-switching
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-system-services
- test/verify/check-users-roles
At some point there should probably be some factorization for "check something in the system menu", but it's not yet clear to me how this could look like. I suggest we first fix all tests, and then look at all the mobile special cases.
Remaining `@skipMobile`s:
- `check-metrics TestGrafanaClient`: Let's not bother testing Grafana in mobile mode
- `check-storage-partitions testSizeSlider`: Mobile mode has a too narrow slider that can't make precise enough settings, so the numbers are off; we may think about how to fix that, but I'd keep it out of this PR.
> More mobile test fixes

- src/bridge/cockpitdbuscache.c
Manager signals also need to be filtered, just as we did for property
signals in 11bea587f9a9385d262bb896155afe7aa30747be.
> bridge: Filter more DBus signals by sender when cache watching

- test/verify/check-static-login
This still has not been fixed.
> test: Ignore cockpit-session chown SELinux failure on fedora-35

- test/verify/check-kdump
- Clicking "Apply" again with a failed NFS validation is bogus -- it's
not going to change the validation error and not going to close the
dialog. Afterwards, the test clicked on the settings link again,
which is not possible in practice. Instead, close the dialog and
ensure that it goes away.
- Address the settings link via ID and explicitly check its expected
text.  Selecting it via :contains() is weird.
- Use button classes instead of strings for the dialog, and scope the
buttons for the dialog.
- Use f-strings instead of .format()
- Drop unused rreplace() method
- Fold rebootMachine() into enableKdump()
-----
This was some preparation for PR #16356
> test: check-kdump cleanup

- test/verify/check-storage-mounting
The `udisksctl lock` is async by itself (triggers an internal udisks
job), and its completion notification to the UI is async as well. The
test must wait until the UI picked up the locking before trying to mount
it -- otherwise it's trying to call .Mount() on the
still-existing-but-about-to-go-away unlocked udisks device.
Fixes #16358
----
[example](https://logs.cockpit-project.org/logs/pull-14109-20210915-131047-376af3d1-debian-testing/log.html#182-2)
I validated this locally by putting that part of the test in a `for i in range(10)` loop, and it works reliably for me now. See #16358 for the debugging notes and details.
> test: Fix race in TestStorageMounting.testEncryptedMountingHelp

- tools/cockpit.spec
Owning it by the meta-package is wrong: Page packages like
cockpit-{storage,podman,machines} should only depend on c-bridge, or at
most -system (which in turn depends on -bridge), not on the full
metapackage. Avoid an unowned directory in such situations.
Spotted by Ben Beasley in https://bugzilla.redhat.com/show_bug.cgi?id=196945
> tools: Move ownership of /usr/share/cockpit to cockpit-bridge.rpm

- pkg/systemd/logs.jsx
- pkg/systemd/logsJournal.jsx
- test/verify/check-system-journal
To circumvent loading a lot of logs by default which can be fairly slow
set the default preset to showing the last three days of logs.
Fixes: #15085
> ssystemd: show last three days of logs by default -- FIX COMMIT MESSAGE ON MERGE: systemd: show 24 hours of logs by default

- Makefile.am
- src/branding/arch/Makefile.am
- src/branding/arch/branding.css
Add branding for the Arch Linux distribution, this requires the
filesystem package to be installed which provides the Arch Linux logo.
---
Cockpit now includes branding for the [Arch Linux distribution](https://archlinux.org/).
> branding: Add Arch Linux branding

- tools/debian/control
debhelper 12 is currently in Ubuntu 20.04 LTS, our earliest supported
release.
No changes necessary for new policy:
https://www.debian.org/doc/debian-policy/upgrading-checklist.html#version-4-6-0
-----
This is an excuse to run CI against the new tasks container from https://github.com/cockpit-project/cockpituous/pull/440 , hence running all tests.
> tools: Bump Debian debhelper compat to 12, Standards-Version to 4.6.0

- test/verify/check-storage-mounting
Commit 96659e58 fixed the first instance of the race, but forgot the one
right after it.
---
[example](https://logs.cockpit-project.org/logs/pull-16362-20210917-080806-1911acc8-debian-testing/log.html#190-2)
> test: Fix race in TestStorageMounting.testEncryptedMountingHelp harder

- doc/guide/embedding.xml
- pkg/base1/test-http.js
- src/bridge/test-httpstream.c
- src/bridge/test-packages.c
- src/common/cockpitwebresponse.c
- src/common/test-webresponse.c
- src/ws/test-channelresponse.c
- test/verify/check-connection
- test/verify/check-embed
Declare `X-Frame-Options: sameorigin` [1] so that cockpit frames can
only be embedded into pages coming from the same origin. This is similar
to setting CORP in commit 2b38b8d (which applies to `<script>`,
`<img>`, etc.).
The main use case for embedding is to run cockpit-ws behind a reverse
proxy, while also serving other pages. Cross-origin embedding is
discouraged these days to prevent "clickjacking".
Cross-origin embedding already did not work in practice, due to our
cookie restrictions: Frames would always just show the login page.
However, this looks confusing and is unclean. With X-Frame-Options, the
browser instead shows an explanatory error page.
Mention the same origin requirement in the embedding documentation.
Fixes #16122
https://bugzilla.redhat.com/show_bug.cgi?id=1980688 …
> common: Restrict frame embedding to same origin

- test/verify/check-menu
Firefox returns a bit different wording.
Cherry-picked from main commit 6eebd26109a
----
This started to fail with upgrading Chromium in our tasks container.  The error now looks like this:
TypeError: Cannot set properties of undefined (setting 'value')
See [failing log](https://logs.cockpit-project.org/logs/pull-2431-20210921-023749-80bec242-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html#227-2).
> [r79] test: Make expected exception a bit more general

- pkg/systemd/overview-cards/healthCard.jsx
- pkg/systemd/overview-cards/lastLogin.jsx
- pkg/systemd/overview-cards/lastLogin.scss
- pkg/systemd/overview.jsx
- pkg/systemd/overview.scss
- test/verify/check-static-login
Always show the last login information under system information and only
show failed logins as a notification.
Closes: #13882
---
Previously, last successful or failed logins were shown in a dismissable alert, which took a lot of space. That login information was moved to the Health card.
A failed login:
> Move last login to system `Health` card

- pkg/lib/python.js
This frees up stdin for use by the actual program.
Also, this fixes quoting of $@ to allow spaces in the arguments.
> lib: Pass Python scripts via "-c" instead of stdin

- pkg/lib/patternfly/patternfly-4-overrides.scss
PatternFly's form select does not use similar spacing compared to PF's select.
This causes issues when the form select is not stretched. Seen @:
https://github.com/cockpit-project/cockpit-podman/issues/755
Upstream issue:
https://github.com/patternfly/patternfly/issues/4387
> lib/patternfly: Fix "form select" padding

- src/bridge/cockpitdbusjson.c
Otherwise a cache for the default name would still react to signals
from foreign sources when the default name can't be activated.
> bridge: Switch off CockpitDBusCache while it has no name owner

- pkg/metrics/metrics.scss
Without the absolute positioning (relative to its containing cell),
Safari / WebKit makes SVG elements and CSS lines way too tall, which
takes a lot longer to compute and hogs resources.
Fixes #16242
> metrics: Make WebKit happy with absolute position

- test/verify/check-storage-unused
Let's keep the logic of allowed and required devices.
> test: Allow `/dev/vda` for raid creations

- test/verify/check-system-shutdown-restart
This test queried the host's date to schedule a shutdown for the VM.
Our RHEL images run in the EDT time zone, so after 20:00 EDT the host
already moved to the next day, and the test would schedule the shutdown
for the wrong day. Avoid this by querying the VM's date instead.
----
This has broken pretty much every automatic RHEL/CentOS image refresh in a long time, as they keep running in the early UTC morning while it's still "yesterday" on these images. [example log](https://logs.cockpit-project.org/logs/pull-2450-20210924-023137-2306c660-rhel-8-5-cockpit-project-cockpit/log.html#273-2) from https://github.com/cockpit-project/bots/pull/2450
> test: Fix TestShutdownRestart.testBasic for different OS timezones

- test/verify/check-system-info
Compare the complete layout of the Overview page in a steady and
relatively well-defined state. This ensures that card layout, fonts etc.
are as expected.
Add a separate check for the motd box, as we have some non-trivial code
and CSS for sizing/aligning with the cards, and ensuring a fixed-size
font formatting.
> test: Add pixel tests for Overview page

- pkg/shell/active-pages-dialog.jsx
- pkg/shell/active-pages.js
- pkg/shell/base_index.js
- pkg/shell/credentials.js
- pkg/shell/hosts.jsx
- pkg/shell/index.js
- pkg/shell/indexes.js
- pkg/shell/machines/machine-dialogs.js
- pkg/shell/machines/machines.js
- pkg/shell/machines/test-machines.js
- pkg/systemd/overview-cards/realmd-operation.js
- pkg/systemd/overview-cards/systemInformationCard.jsx
- pkg/systemd/services/timer-dialog-helpers.js
- pkg/systemd/terminal.jsx
- webpack.config.js
These were the last webpack that still used `var`, so drop the temporary config override from webpack.config.js again. After this lands, I'll also eliminate the `no-var` hack from package.json again, but as that involves a `node_modules` rebuild, I'd like to do that separately.
> shell, systemd: Eliminate `var` keyword

- pkg/lib/serverTime.js
- pkg/lib/serverTime.scss
- test/verify/check-system-info
This brings it in line with the shutdown and Services timer dialog, and
avoids an unsightly dialog layout on mobile.
Change the state keeping to just have a single tiem string as variable,
as that's overall easier to manage. Move the minute normalization into
get_current_time(), as that's the only place where it's really necessary
-- writing out the values does not care about leading zeros.
Add a pixel test for the manual time setting. This does not capture the
whole expanded time picker list, as that grows beyond the dialog, but
still captures enough to make sure it looks as expected. There is no way
to collapse it again, but we want to do the screenshot after setting a
manual date and time, to include these input value strings into the
pixel test.
----
In main, the mobile dialog looks …
> lib: Move ServerTime component to PF4 TimePicker

- pkg/systemd/overview-cards/realmd-operation.html
- pkg/systemd/overview-cards/realmd-operation.js
- test/verify/check-system-realms
Setting them as placeholders was confusing:
- They got prefixed with "e.g.", quoted, and greyed out, and thus did
not look like proper values.
- Leaving the "domain" field empty used the auto-detected value; but
leaving the "admin" field empty literally tried to authenticate as
empty user name, so that field had to be filled.
Bring the dialog in line with the standard behaviour, use static fixed
placeholders (in case there is no auto-detected domain), and set
auto-detected realm/user names as actual values. With that, joining a
domain only requires to fill the admin password, everything else has
sane defaults.
Update the tests to expect pre-filled autodetected domain/admin names.
In TestPackageInstall.testDialogTransition, check that they remain empty
if there is no realm available. …
> systemd: Set auto-detected realm domain/admin as proper input values

- pkg/base1/cockpit.js
- test/verify/check-system-services
If a test fails at the "wrong" time, it may happen that test.service is
still enabled. The previous cleanup only stopped it, but not disablled
it again, so that the next test retry would unexpectedly find
test.service already enabled.
Clean up more thoroughly.
https://bugzilla.redhat.com/show_bug.cgi?id=2008208
---
I piggy-backed the trivial fix for https://github.com/cockpit-project/cockpit/issues/16221#issuecomment-928756101 on this PR.
> test: Fix test.service cleanup in TestServices

- src/bridge/cockpitcgroupsamples.c
It can happen that a cgroup goes away after opening an attribute file.
In that case, reading from the fd fails with ENODEV. This is essentially
the same as open() failing with ENODEV right away, so only write a
debugging message for this. This avoids breaking tests due to random
unexpected messages.
---
Seen in [this failure](https://logs.cockpit-project.org/logs/pull-2458-20210929-023815-e97ced59-fedora-34-cockpit-project-cockpit/log.html#54) of https://github.com/cockpit-project/bots/pull/2458
> bridge: Tone down ENODEV message about reading cgroups

- .github/workflows/po-refresh.yml
- po/Makefile.am
The current po-refresh job does two things:
- generates an updated cockpit.pot and commits it to the weblate repo
- copies .po files from the weblate repo and opens a PR with them
These two things are actually completely independent from each other, so
let's separate them out to allow for more fine-grained use of
credentials.
Introduce a update-pot job to the existing po-refresh workflow which
takes care of updating cockpit.pot and committing the results to the
weblate repository.  This job requires very few permissions: it only
needs to write to the weblate repository and it does that by way of a
deploy key.
Meanwhile, remove the commands from the `update-pot` rule in
po/Makefile.am to prevent this job from being done twice.  We need to
keep the target itself because bots/po-refresh …
> po-refresh.yml: split out pot upload to weblate

- pkg/systemd/overview-cards/lastLogin.jsx
- pkg/users/account-details.js
- pkg/users/account-logs-panel.jsx
- test/verify/check-users
Show a list of the 15 recent logins on the account details page, the last
login health card now includes a link to the account detail page.
Closes: #28
---
The user account details page now includes a list of your 15 most recent logins.
> users: Add an list of recent logins to the account details

- test/run-verify-host.sh
- tools/cockpit.spec
https://bugzilla.redhat.com/show_bug.cgi?id=2005760
https://bugzilla.redhat.com/show_bug.cgi?id=2008154
See [this downstream gating failure](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/78495/testReport/(root)/tests/_test_verify/) for an example how firefox has failed to install for the last weeks.
> Fix packagekit dependency, fix firefox install in rawhide

- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/overview-cards/realmd-operation.html
- pkg/systemd/overview-cards/realmd-operation.js
This has never worked -- literally the first-ever commit (87325b96bc343)
got this wrong (the code queried `.realms-join-computer-ou`, while the
HTML defines `#realms-op-computer-ou`). This never had an integration
test, testing it does not work with our Samba server (as it does not
define any "Computers" OU and `adcli show-computer` does not show the OU
either). Also, that feature is incomplete (there are many more fields
that one can set [1]), and nobody complained in all the years.
So let's just remove this, and only bring it back in the future when
there is some actual demand. This also gets rid of the
`.realm-active-directory-only` class special case.
[1] https://freedesktop.org/software/realmd/docs/gdbus-org.freedesktop.realmd.KerberosMembership.html
> systemd: Drop computer-ou input field from realm join dialog

- .github/workflows/npm-update.yml
Drop the final use of COCKPITUOUS_TOKEN from the cockpit repo and use
the `DEPLOY_KEY` in the `self` environment instead.  The PR opening gets
done with the scope-constrained GitHub Actions token.
Note: this is going to break the `/npm install` that `bots/npm-update` writes into the PR: it will be ignored, since it comes from a GitHub Actions token.  The agreed upon plan to sort that out involves triggering the `npm-install` workflow via `workflow_run` on the `npm-update` workflow and scanning the open PRs to find the one that was just created, and treat the `/npm install` comment there as the one that triggered the rebuild.
> .github: run npm-update workflow with deploy key

- test/common/chromium-cdp-driver.js
- test/common/firefox-cdp-driver.js
This is useful to guard against log spam in production, but it severely
gets in the way when doing development and console.log()-style debugging
-- most developers are not aware of this, and this is responsible for
way too many hairs which got pulled out. Disable the deduplication in
--trace mode, which is a nice compromise.
-----
Tested with this:
```diff
--- test/verify/check-users
+++ test/verify/check-users
@@ -327,10 +327,12 @@ class TestAccounts(MachineCase):
m.execute("useradd anton; echo anton:foobar | chpasswd")
self.login_and_go("/users", user="anton", superuser=False)
+        b.eval_js('console.log("MOO!")')
b.go("#/anton")
b.wait_text("#account-user-name", "anton")
b.wait_visible('#account-set-password:enabled')
b.click('#account-set-password')
+ …
```
> test: Disable browser log deduplication with --trace

- pkg/lib/service.js
- test/verify/check-system-tuned
`systemd_client` gets cached forever, and thus never reacts to privilege
changes (adding/dropping sudo channel). We also can't just reinitialize
this, as this would break existing proxies.
Instead, keep the long-lived proxy as unprivileged, and only use it for
watching/reading. Use a fresh cockpit.dbus() instance with `superuser`
for all the actions instead -- cockpit.dbus() is cheap, and actions are
done rarely.
This requires reworking the `JobRemoved` handler: doing this on the
persistent unprivileged proxy sometimes misses events from the separate
D-Bus connections, so this must happen on the same connection that
started the job. Move the listener into call_manager_with_job() as an
one-off, and get rid of the persistent `pending_jobs` house-keeping.
----
Also do some code cleanup, …
> lib: Fix service.js for privilege changes

- test/verify/check-shell-keys
Unfocus the input line, to avoid the blinking cursor and the slightly
unpredictable rounded corners of the focus ring.
----
[example failure](https://logs.cockpit-project.org/logs/pull-16538-20211102-104210-427b29b1-fedora-34-mobile/pixeldiff.html#TestKeys-testPrivateKeys-ssh-keys-dialog-mobile), this has plagued us for a while
> test: Fix unstable TestKeys.testPrivateKeys pixel test

- test/common/testlib.py
- test/verify/check-networkmanager-firewall
- test/verify/check-shell-keys
- test/verify/check-system-info
- test/verify/check-system-services
- test/verify/check-system-shutdown-restart
- test/verify/check-users
Generalize the blurring of the input element after typing keys in
set_input_text(). We keep running into the same problems with pixel
tests, and if tests need a particular item to be focussed, they should
be explicit in that.
The time/date validation checks in check-system-shutdown-restart *are*
dependent on keeping the focus, so provide a flag to disable the blurring.
> test: Generalize set_input_text() blurring

- pkg/storaged/dialog.jsx
- test/verify/check-storage-nfs
and not only those that are in the drop down list.  The list is not
always accurate and the user might have a better idea of what will
work.
> storage: Allow mounting all NFS directories

- pkg/lib/cockpit-components-table.jsx
- pkg/lib/cockpit-components-table.scss
- pkg/shell/active-pages-dialog.jsx
- test/verify/check-packagekit
- test/verify/check-storage-mdraid
- test/verify/check-storage-msdos
- test/verify/check-system-info
- test/verify/storagelib.py
The ListingTable component has already been partially ported to the non legacy PF4
table implementation, move it now completely.
This change is just an rewrite of the ListingTable component and should
not anyhow impact the consumers, as the properties and functionality
were not affected.
> lib: use new PF4 table (ComposableTable) implementation for all Table variants

- pkg/networkmanager/interfaces.js
show_modal_dialog expects an action to be a function which returns a
promise, as it didn't you would get an error that undefined has no
method 'then'. The issue was introduced in 3899b9b5d79df.
> networkmanager: Fix JavaScript error when applying settings

- pkg/systemd/overview-cards/systemInformationCard.jsx
On my system fields.product_serial and fields.chassis_serial is empty
causing an warning to be logged in the developer console:
validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tbody>.
> systemd: Handle react DOM validation error

- test/verify/netlib.py
Restarting NetworkManager and then immediately deleting network
devices via "ip link del dev" would sometimes not actually remove team
devices.
Thus let's first cleanly remove the devices via NM itself and then do
the restart.
The symptoms of this was a very flaky TestTeam.testBasic on rhel-8-6
when run after TestTeam.testActive on the same machine.
TestTeam.testActive would leave a unmanaged "tteam" device
behind (because of the bug fixed here), and the automatic activation
of the new connection object that TestTeam.testBasic would not happen
because of that, and "tteam" remained unmanaged.  (A explicit
actication would have put everything back in order.)
> test: Don't restart NM while deleting devices at the same time

- pkg/base1/test-dbus.js
Fedora 35 now gives an error message about "Object does not exist" vs.
previous versions saying "No such interface".  Accept both messages.
We don't actually run unit tests in Fedora 35 at the moment (although perhaps we should) but I can confirm that this fixes `make check` for me locally.
> base1: tweak error message check in test-dbus.js

- src/bridge/cockpitdbusjson.c
The CockpitDBusCache for the default name of a dbus channel is already
careful not to process signals from other sources than the default
name, but it starts doing that only as soon as the unique name is
known (or known to not exist).  Before that, it will accept all
signals, which might still lead to journal messages like
org.storage.stratis3: couldn't get managed objects at /org/freedesktop/UDisks2: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.storage.stratis3 was not provided by any .service files
Thus, we block signals initially as well, until the unique name is
known.
> bridge: Block signals initially for the default CockpitDBusCache

- src/tls/cockpit-certificate-helper.in
- test/common/chromium-cdp-driver.js
- test/verify/check-connection
- test/verify/check-system-realms
- tools/cockpit.spec
tools: Use our own SELinux policy on RHEL/CentOS 8 as well
This will fix the SELinux type of /etc/cockpit/ws-certs.d (from commit
6ec488185), and is going to fix systemd's cleanup of /run/cockpit in
PR #16572.
Drop the distribution test from the .spec, as this is actually also
being used in OpenSUSE. As this now builds on RHEL 8,  add a `name == "cockpit"`
guard, as we don't want to build this for cockpit-appstream.
This allows us to drop the fallback from cockpit-certificate-helper, as
certmonger can now finally write directly into ws-certs.d/ everywhere.
This will fix certificate auto-refresh on RHEL 8. Drop the corresponding
hacks/special cases from the integration tests.
-----
I asked @zpytela and @vmojzis  and got their blessing for this. It will also help with getting rid of that …
> tools: Use our own SELinux policy on RHEL/CentOS 8 as well

- pkg/apps/packagekit.js
Packagekit with apt backend reports backward percentages for the refresh
operation.
Guard these wrong values that the packagekit API returns by making sure
these are corresponding to an increasing percentage value.
Rewrite progress_reporter into a class and store the new percentage
value there as an attribute, instead of overwriting the object that the API returns, as
that it not public attribute.
Upstream bug report: https://github.com/PackageKit/PackageKit/issues/516
Fixes #16564
> apps: fix packagekit progress bar backword percentages

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-tabs.jsx
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services-list.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/services.scss
- pkg/systemd/services/timer-dialog-helpers.js
- pkg/systemd/services/timer-dialog.jsx
- test/verify/check-system-services
Most users are commonly familiar with the system systemd units. However, systemd offers the ability for unprivileged users to control and configure per-user units. Such units can now be managed from web console UI, the same way system-wide units are.
> services: show user owned systemd units in the services page

- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/serverTime.js
- pkg/lib/timeformat.js
- pkg/systemd/services/timer-dialog.jsx
- pkg/users/expiration-dialogs.js
PF's DatePicker defaults to Sunday as the start of the week instead of
the given locale's convention. There is currently no official JS API
which exposes that piece of locale information [1], and
`cockpit.language` does not even contain the country in most cases. So
add a `timefirmat.firstDayOfWeek()` approximation by language, which at
least gets it right for most of our supported languages *except*
English-speaking countries in Europe (in particular, en-GB and en-IE).
Add missing aria and localization to the timer creation and user account
expiration dialogs, so that their month names are properly translated.
[1] https://github.com/tc39/ecma402/issues/6
---
English looks as before:
In German, the week now starts on Monday:
> Fix DatePicker's start of week for most cases

- test/run-verify-host-user.sh
Map os-release detected "centos-8" to "centos-8-stream", which fixes
TestServices.testBasicSession (regression from commit 154da47d94).
Our tests do know about "fedora-35" now, and rawhide is now fedora-36.
----
packit centos 8 has [failed](http://artifacts.dev.testing-farm.io/749216f5-0781-43d0-ba61-ba4ba105ea42/) for a few days now, this should fix it.
> fmf: Fix TEST_OS mappings

- test/verify/check-static-login
Commit 745f978a19e51579 typoed the operation name.
----
Still [happened](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2623-20211112-023032-91f70e17-fedora-testing-cockpit-project-cockpit/log.html#166) in https://github.com/cockpit-project/bots/pull/2623 -- Sorry, brown paperpag.. :cry: I can't for my life reproduce this failure locally.
> test: Fix SELinux message matching

- test/verify/check-storage-partitions
- test/verify/storagelib.py
This method has proper cleanup defined.
This is easily reproducible:
```diff
diff --git test/verify/check-storage-partitions test/verify/check-storage-partitions
index b0c783dd4..c58789744 100755
--- test/verify/check-storage-partitions
+++ test/verify/check-storage-partitions
@@ -58,6 +58,7 @@ class TestStoragePartitions(StorageCase):
self.content_row_wait_in_col(1, 1, "ext4 file system")
self.content_dropdown_action(1, "Delete")
+        b.wait_visible("#foobar")
self.confirm()
self.content_row_wait_in_col(1, 0, "Free space")
```
and then run `./test/common/run-tests --test-dir test/verify TestStoragePartitions.testPartitions`. Without this patch it fails for the first time on this new `wait_visible` and then quickly fails on `dev = m.execute("set -e; dd if=/dev/zero of=/var/tmp/disk1 …
> test: Use add_loopback_disk() to create loopback disks

- pkg/users/password-dialogs.js
- test/verify/check-users
When a user types a bad password and tries to set a weak password
errors are shown underneath the password field. Changing the password
then again does not clear the password.
> users: Clear password errors when password is changed

- pkg/static/login.css
- pkg/static/login.html
- pkg/static/login.js
Based on https://www.patternfly.org/v4/components/login-page
This adds a toggle to switch text input types from "password" to "text",
to make it cleartext for viewing and back. SVG icons are inlined and
chosen based on the state of the input. Minimal JavaScript is used to
swap the attribute.
Allowing one to choose to swap to clear text lets people use complex
passwords and not have to second guess what they typed. It's a usability
and accessibility feature. (And it shouldn't be used when someone is
actively looking at their computer, but otherwise should be fine.)
The form still defaults to hiding the password by default.
> login: Add toggle button to view password

- doc/guide/cockpit-util.xml
- pkg/base1/cockpit.js
- pkg/kdump/config-client.js
- pkg/kdump/kdump-view.jsx
- pkg/lib/journal.js
- pkg/shell/base_index.js
- pkg/shell/machines/machines.js
This was an ages old compatibility shim for a time when Object.assign()
was not yet a standard browser API. Replace it with Object.assign() for
updating existing objects, and the spread operator for creating new
ones.
Drop the documentation as well. Keep cockpit.extend() as alias for
Object.assign() to keep the current API.
> Eliminate obsolete cockpit.extend()

- pkg/storaged/client.js
- pkg/storaged/content-views.jsx
- pkg/storaged/lvol-tabs.jsx
- test/verify/check-storage-vdo
The `vdo cli` API and standalone "vdo" block device type has been deprecated a while ago, in favor of the LVM/udisks-lvm2 API. The latter is the officially documented one [1].
The official VDO API is a particular "VDO" type of LVM volume, similar
to a thin pool volume or a normal LVM block LV. These consist of two
LVs:
(1) The physical "pool" volume which holds the compressed data; from
the user's point of view these are an internal implementation detail
and have no sensible actions other than growing. In particular,
these should not be (de)activated [2]. The `lvcreate` CLI also does
not require specifying them, it will just make up a new name.
(2) The virtual block volume which gets formatted, mounted, and used.
Stop showing type (1) as standalone top-level LV volumes.  Instead, add a …
> storaged: Properly represent LVM VDO pools

- pkg/systemd/services/timer-dialog.jsx
> services: make minus/plus icons in create timer dialog align with the selectors

- test/verify/check-networkmanager-vlan
The focus border around the close button of the dialog causes the pixel
tests to sometimes fail.
> test: Drop focus from close button

- pkg/lib/packagekit.js
- pkg/packagekit/updates.jsx
On Arch Linux and derivates cockpit-ws is included in the cockpit
package which makes users miss out on the "Web Console restart" warning
message. As these distriubtions all use the "alpm" backend, the
component now on load fetches the configured backend (can only be one)
to determine which package to check. Using packagekit was chosen over
parsing /etc/os-release or checking if pacman is installed on the
system as we already interact with packagekit over Dbus.
> packagekit: Show "Web Console restart" for Arch and derivates

- pkg/static/login.css
- pkg/static/login.html
This changes the red emoji &#x274c; to an actual SVG icon from PatternFly. It also only shows when there's something typed into the field, thanks to the (empty) placeholder attribute.
> login: Use × icon as input clear; show when needed

- pkg/storaged/content-views.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/things-panel.jsx
- pkg/storaged/vdos-panel.jsx
- test/verify/check-storage-vdo
This is the officially documented and supported API [1], both on the
command line and in UDisks. Add them as a new type to the "Create
logical volume" dialog and drop the standalone one from the things
panel.
Drop the "Use 512 byte emulation", this is not a thing with LVM VDO.
Also drop the "index memory" slider. This is a bit dubious, not even
exposed by `lvcreate` or the documentation, and can only be done via
changing the config file. The UDisks2 D-Bus API does support setting it,
but this is probably not something that the admin should customize
lightly (and if so, they can still set it in the config file). Also,
neither `lvdisplay` nor UDisks2 have an API to get the current value.
The pool name is rather uninteresting -- in fact, lvcreate does not even
need it. udisks2 does not …
> storaged: Create VDO devices as LVM LV type

- tools/cockpit.spec
`%selinux_modules_{,un}install` works fine in environments like guestfs,
which don't run with SELinux enabled. Adjust the condition so that
module installation happens there as well. The relabeling still won't
work there, but that has its own guard with calling `selinuxenabled`.
https://bugzilla.redhat.com/show_bug.cgi?id=2023579
> tools: Fix SELinux module installation in non-SELinux environments

- pkg/static/login.js
We suppress auto-login in the case that a hostname is required, but we
don't consider that one may already have been pre-filled.
Use the need_host() function to take both into account.
> static: re-enable autologin if hostname was given

- src/client/cockpit-client-ssh
When run in askpass mode, we attempt to access the cookie in the
response from cockpit-ws by way of response.cookie instead of the
(correct) syntax of response['cookie'].  Fix that.
> cockpit-client: fix assertion in cockpit-client-ssh

- src/client/cockpit-client
- src/client/cockpit-client.ui
This is pretty seriously broken right now, particularly when navigating
back to the login screen.  Let's disable it until this works better.
> cockpit-client: disable and hide forward/back

- containers/flatpak/cockpit-client.metainfo.xml.in
These are required for flathub.
> flatpak: add screenshots to cockpit-client metainfo

- tools/webpack-jumpstart
If we are rebasing and the HEAD commit is a merge, use the merged commit
ID to find the cached data, instead of the merge itself.  The subsequent
rebase will result in the merge commit itself being removed.
> webpack-jumpstart: look past merge commit for --rebase

- tools/git-utils.sh
It would be nice to be able to jumpstart from a known point in the git
history by doing an interactive rebase and adding
```
x tools/webpack-jumpstart
```
at the desired point.  Up until now that has been broken by git-rebase
setting a bunch of environment variables in the spawned command.  This
interferes with our use of git to work on the cache repository.
Unset those variables to fix the issue.
> tools: unset git envvars in git-utils.sh

- src/client/cockpit-client
Improve our workaround for
https://gitlab.gnome.org/GNOME/pygobject/-/issues/426 by directly
calling calling the method on the interface.
> cockpit-client: work around pygobject bug

- src/client/cockpit-client
Remove --wildly-insecure from the message printed when checking for the
sandbox fails, and hide it also from the --help output.
Leave the ***DANGEROUS*** --help message in the source code visible to
anyone who goes looking there.
> client: remove all mentions of --wildly-insecure

- .github/workflows/flatpak-test.yml
flatpak-test.yml checks out the head commit instead of the merge commit.
That was done to dodge a bug in webpack-jumpstart which caused it to
fail on merge commits.  That's been fixed, meanwhile, and we're also not
using jumpstart anymore anyway, and now this workaround is causing new
issues, like the failure in #16624.
TL;DR: let's just use the default and checkout the merge commit, since
that's what we're supposed to be testing anyway.
> workflows: use merge instead of head for flatpak test

- containers/flatpak/cockpit-client.yml.in
When proposing cockpit-client to flathub, we received some review
comments requesting some minor tweaks to the manifest.  Merge those back
upstream so that they're not undone again during the next release.
--share=ipc was added because X11 apparently requires it.
See https://github.com/flathub/flathub/pull/2655
> flatpak: tweak our manifest to match downstream

- test/common/testlib.py
- test/verify/check-metrics
In #16522 a new shell was introduced. This break on new images that
already have cockpit-system-258 installed.
We will need to change then test/common checkouts in all subprojects to include this fix - as now seen for example in https://github.com/cockpit-project/bots/pull/2669 or failing rawhide packit in machines or podman.
> testlib: Correctly deal with older shell versions

- test/common/testlib.py
This unblocks https://github.com/cockpit-project/cockpit-podman/pull/838 and similar ones.
I tested this locally against cockpit-podman.
> test: Add Arch support to MachineCase.system_before()

- pkg/storaged/content-views.jsx
- pkg/storaged/dialog.jsx
- test/verify/check-storage-vdo
Leftover from https://github.com/cockpit-project/cockpit/pull/16623#issuecomment-976407637
Looks like this now:
> storaged: Change VDO package installation alert to a helper text

- pkg/selinux/setroubleshoot-view.jsx
Commit 5108999badee3834fcc8e57222b5f9c82feae3a9 changed the
implementation of the ListingTable component and now the children rows
are not counting as extra rows, so the division by 2 is not needed.
Fixes #16640
> selinux: fix onSelect callback for selinux page

- doc/protocol.md
- src/bridge/cockpitconnect.c
This used to be used when cockpit-ws originated ssh connections to other
hosts on behalf of the session, but that hasn't happened since
082da24a5a2a27d521e7b6d1beb2bbe094ffdc54.  Nowhere else in the code
refers to this anymore, so let's drop it.
> bridge: remove "ssh-agent" internal address

- doc/protocol.md
- pkg/base1/test-http.js
- src/bridge/cockpitconnect.c
- src/bridge/cockpitconnect.h
- src/bridge/cockpithttpstream.c
- src/bridge/cockpitpackages.c
- src/bridge/cockpitpackages.h
- src/bridge/cockpitpipechannel.c
- src/bridge/cockpitrouter.c
- src/bridge/test-connect.c
- src/bridge/test-fs.c
- src/bridge/test-httpstream.c
- src/bridge/test-packages.c
- src/bridge/test-websocketstream.c
- src/common/cockpitwebserver.c
- src/common/cockpitwebserver.h
- src/common/test-webserver.c
- src/ws/main.c
- src/ws/test-handlers.c
- src/ws/test-server.c
- src/ws/test-webservice.c
Major changes:
* cockpit-bridge no longer opens a TCP port for serving packages
* we no longer have the `internal` connection option
* `internal: "packages"` is preserved as a one-off exception on HTTP streams for reasons of cockpit-ws/cockpit-bridge compatibility
* cleanup of listening options on cockpitwebserver, ~and cockpit-ws gains a -U option to listen on a unix socket~ (from #16650)
> clean up "internal" endpoints

- src/common/cockpitconf.c
- src/common/cockpitconf.h
- src/common/test-config.c
- src/websocket/websocketserver.c
- src/websocket/websocketserver.h
- src/ws/cockpitauth.c
- src/ws/cockpitwebservice.c
- src/ws/test-handlers.c
If we receive requests for exotic authentication types from the client like:
``` 
Authorization: Random xyz
```
and those types are not explicitly disabled in cockpit.conf with a stanza like:
```             
[Random]
action = none
```
then by default we'll try to spawn cockpit-session to respond to them.
This doesn't make a lot of sense, as cockpit-session doesn't support any types other than "basic", "negotiate" and "tls-cert" (which is only ever used internally, and already blocked when received from clients).                                                 
Modify the check to only spawn cockpit-session for the recognised types.  In case another type is specified, then the command to handle that type needs to be explicitly specified:
``` …
```
> ws: only spawn cockpit-session on known auth types

- pkg/lib/cockpit-components-table.jsx
- pkg/storaged/content-views.jsx
- pkg/storaged/crypto-panel.jsx
- pkg/storaged/details.jsx
- pkg/storaged/fsys-panel.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/nfs-panel.jsx
- pkg/storaged/storage.scss
- pkg/storaged/stratis-details.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-basic
- test/verify/check-storage-format
- test/verify/check-storage-hidden
- test/verify/check-storage-ignored
- test/verify/check-storage-iscsi
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-msdos
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/storagelib.py
This is a step towards https://github.com/cockpit-project/cockpit/discussions/16440
Screenshot (up-to-date): https://github.com/cockpit-project/cockpit/pull/16518#issuecomment-972712100
Demo (not pixel-perfect, but still valid): https://www.youtube.com/watch?v=xLfxxm-VKmU
------
The rows of the various tables now show more information about filesystems and other things.  You can now immediately see where a filesystem is mounted, there are links to the pages for volume groups etc, and the usage level is shown.
> storage: Redesign "content rows" everywhere

- pkg/lib/cockpit-components-table.jsx
Otherwise the mobile layout is has a unexpected empty row at the top.
Before:
After:
> lib: Ensure empty expander in ListingTable cell has right class

- pkg/users/account-create-dialog.js
On Arch Linux the useradd file `/etc/default/useradd` is only readable
by root, so any SHELL override is not picked up by `useradd -D`.
> users: use superuser for `useradd -D`

- doc/guide/cockpit-dbus.xml
This is tested by pkg/base1/test-dbus-address.js.
---
Tested interactively:
```
❱❱❱ dbus-run-session sh -c 'echo $DBUS_SESSION_BUS_ADDRESS; sleep infinity'
unix:abstract=/tmp/dbus-7QHVXYWCbt,guid=c07a5a03839c596f3dddc18861af1525
```
Then in cockpit, open dev console:
```js
e = cockpit.dbus("org.freedesktop.DBus", { bus: "none", address: "unix:abstract=/tmp/dbus-7QHVXYWCbt,guid=c07a5a03839c596f3dddc18861af1525"})
❱❱ Object { options: {…}, unique_name: null, constructors: {…}, wait: wait(e), meta: meta(e, n), notify: v(e), close: close(e), call: call(e, t, o, i, r), signal: signal(e, n, t, o, i), subscribe: subscribe(e, n, t), … }
e.call("/org/freedesktop/DBus", "org.freedesktop.DBus", "ListNames", []).then(console.log, console.warn)
❱❱ Array [ (2) […] ]
```
> doc: Document how to connect to a non-standard D-Bus with giving an address

- test/verify/check-metrics
In the "have swap" code path of this test it often happens that the
memory usage after killing both memhogs does not go back quite to the
same number as at the start of the test. In our noisy test VM this could
have any number of reasons. So make the check less strict by measuring
against the usage before starting mem-hog2 (which is higher, as memhog
is already running). The point of the check is that current memory usage
goes down after stopping the services, but we can't pinpoint an exact
number.
----
Fixes [this failure](https://logs.cockpit-project.org/logs/pull-16686-20211206-123627-ca37ceaf-fedora-35/log.html#291-1), which pretty much always happens on Fedora 35 in tests which touch metrics (and thus have to survive 3x affected retries)
> test: Robustify TestCurrentMetrics.testMemory

- pkg/shell/shell.html
blank-slate-pf and the FontAwesome icon both don't work any more in the
PF4-only shell. No real-life user should ever see this fallback any more
these days, having an icon there is really not important. So just drop
the icon and blank-slate style.
> shell: Clean up PatternFly 3 leftover

- test/verify/check-networkmanager-firewall
The tests no longer require port 8765 to be opened as the dbus tests now
run locally in the virtual machine. The port is closed in cockpit, so
the pixel tests can be updated and not opening the ports is an easier
change in bots.
> test: Close port 8765 to update the pixel tests

- containers/flatpak/cockpit-client.metainfo.xml.in
We renamed the desktop file but forgot to update it in the metainfo.
This was flagged by @flathubbot when we attempted to push the update.
We won't have to re-do the release or anything.  I've just manually patched it into the bot-written commit for the time being.  This kind of thing is part of the reason why we keep the metainfo outside of the tarball.
> flatpak: update desktop file in metainfo

- .github/workflows/update-flathub.yml
Instead of cloning our fork of the flathub repository, clone the
"official" one under the flathub project.  We still push the new branch
to our own repository, however.
This prevents us from having to keep our own repository up to date.  In
fact, our main branch now contains only a README telling you to look
elsewhere.
> workflows: clone flathub repository from flathub

- test/run-verify-host-user.sh
Generalize the `$TEST_OS` transformation for stream to apply to any
major version. Taken from corresponding script in cockpit-podman.
----
This should make https://github.com/cockpit-project/bots/pull/2704 actually effective, and fix the [c9s failure](http://artifacts.dev.testing-farm.io/27845049-5918-402b-985e-596423232e2e/).
> fmf: Fix $TEST_OS for centos-9-stream

- test/verify/check-shell-menu
On Arch Linux the package cockpit also provides cockpit-bridge while on
other distributions it's seperate.
> test: Add Arch Linux compatibility for `About Web Console`

- doc/man/cockpit-ws.xml
- src/common/cockpitwebserver.c
- src/common/cockpitwebserver.h
- src/common/test-webserver.c
- src/tls/Makefile-tls.am
- src/tls/connection.c
- src/tls/httpredirect.c
- src/tls/httpredirect.h
- src/tls/main.c
- src/tls/socket-activation-helper.c
- src/tls/test-server.c
- src/tls/test-socket-activation-helper.sh
- src/ws/Makefile-ws.am
- src/ws/cockpit-wsinstance-http-redirect.service.in
- src/ws/cockpit-wsinstance-http-redirect.socket.in
- src/ws/cockpit.service.in
- src/ws/main.c
- test/verify/check-connection
- tools/cockpit.spec
- tools/debian/cockpit-ws.install
This is a temporary increase in code size, since we still need to keep http→https redirection in `cockpit-ws` for the container case, but it's a precondition to removing it.
> handle http→https redirect from cockpit-tls

- doc/guide/cert-authentication.xml
- src/session/client-certificate.c
- test/verify/check-static-login
- test/verify/check-system-realms
- test/verify/check-system-s4u
sssd 2.6.1 introduces a new FindByValidCertificate() method which
validates the given certificate against the configured CA. Use this API
if available, and fall back to FindByCertificate() to keep compatibility
with older distributions.
This enables OCSP/CRL checks, and enables certmap rules in a safe way.
Update TestLogin.testClientCertAuthentication() to adjust the scary
comments, and make sure that certificates without a valid CA are
rejected if the new API is available.
Similarly, adjust check-system-realms to tell sssd about a valid CA, and
test valid/invalid cases.
Update the client certificate docs to show how to set up the CA in sssd,
and adjust the warning: certmap rules are now actually okay with sssd
2.6.1.
https://bugzilla.redhat.com/show_bug.cgi?id=1992149
CVE-2021-3698
----- …
> session: Validate client certificates against sssd's trusted CA

- src/ws/test-server.c
This fixes running the unit tests with `TEST_BROWSER=firefox` or
`TEST_SHOW_BROWSER`. Previously the missing favicon.ico threw off the
tests due to the 404 error.
---
This does not run in CI yet, but will be soon in #16719. For now, test this locally with
TEST_BROWSER=firefox make check
or
TEST_SHOW_BROWSER=1 make check TESTS=dist/base1/test-echo.html
> ws: Handle favicon.ico in test-server

- test/verify/check-packagekit
This was only enabled by accident and doesn't work very well, see
#2323.  Also, at least testNoSubOsRepo is broken on any "*/devel" test
context since packagekit is not preloaded there.
Thus, let's disable these tests before making fedora-35 the default.
> test: Skip TestUpdatesSubscriptions on fedora-35

- test/verify/check-static-login
Arch Linux has faillock default enabled with an deny default of three,
so the configuration file has to be updated to enable four deny's.
> test: enable testTally on Arch Linux

- test/verify/check-shell-keys
Ideally the package would enable pam_ssh_add but as it does not, enable
it for the private keys test.
> test: Enable pam_ssh_add for Arch Linux tests

- .github/workflows/unit-tests.yml
- containers/unit-tests/run.sh
- containers/unit-tests/setup.sh
- pkg/base1/test-dbus-common.js
This was originally used to install amd64 nodejs because there was no
binary version of node-sass for i386.  That stopped being a problem a
long time ago and we've since dropped installing nodejs:amd64, but we
forgot to remove adding the architecture for it.
> unit-tests: remove amd64 arch from i386 container

- src/client/cockpit-client-ssh
- test/README.md
Connecting to an address like
```
root@127.0.0.2:2201
```
doesn't currently work because ssh(1) doesn't under the port number. Break it out to a -p parameter, if it's present.
> cockpit-client: add support for :port

- pkg/base1/test-chan.js
The filter function should always return a boolean, and in one case we
were missing a return statement.  That seems to have worked out okay on
Chromium, but sometimes Firefox doesn't like it, leading to fails like
> log: not ok 154 - Expected 11 assertions, but 14 were run...
Make it explicit.
I have no idea if this is actually the problem from https://github.com/cockpit-project/cockpit/runs/4517621520?check_suite_focus=true#step:4:3391 but this fix certainly won't make things worse...
> tests: return true (not undefined) from a filter

- containers/unit-tests/build.sh
Commits b3e3b10fdae8 and 4193c1d96 fixed gcc -fanalyzer errors a while
ago. Now that we have a new enough gcc in the unit-tests container,
enable the analyzer permanently.
> unit-tests: Enable -fanalyzer for gcc

- test/run-verify-host.sh
By now the packaged firefox contains CDP. This makes the tests more
robust against CDP breakage in nightly.
Cherry-picked from starter-kit commit 9e162423eba.
> fmf: Go back to firefox distro version

- .github/workflows/flatpak-test.yml
Some package versions in the GitHub workflow machine's old package index
got cleaned up and are not available any more.
----
Fixes [this failure](https://github.com/cockpit-project/cockpit/runs/4543993599?check_suite_focus=true)
> workflows: Add missing apt update to flatpak-test

- test/verify/check-selinux
The next rhel-8-6 image will produce selinux alerts for rhsm.service
when logging into Cockpit.  We want them to dismiss them reliably
before starting the test.
In order for them to show up, auditd needs to be running already
during login, and we need to give the machinery copious time to pick
up the alert after the journal message has been written.
> test: Better handle selinux alerts produced during login

- pkg/metrics/metrics.scss
I realized we have a bit too much spacing in the metrics cards by default, especially when adding a maximum CPU and when there are several storage devices.
> Metrics spacing

- src/tls/test-cockpit-certificate-ensure.c
Fix areadlinkat() to not write to `buffer[-1]` if `readlinkat()` fails
with ENOENT.
Spotted by Coverity.
> tls: Fix potential out-of-bounds buffer access

- test/common/cdp.py
Firefox 97 enables Fission [1] by default to improve site isolation.
This broke DevTools Protocol's `Page` events [2]. Disable Fission to
work with current nightlies as well.
This bug hopefully gets fixed at some point, but this workaround will
not break.
[1] https://wiki.mozilla.org/Project_Fission
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1746154
----
We don't have that Firefox nightly in our tasks container (and won't have, as we can go back to the distro version), but I verified it locally against a current nighty. For easy comparison:
```
mkdir /tmp/fn; curl --location 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US' | tar -C /tmp/fn -xj
sudo ln -sfn /tmp/fn/firefox/firefox /usr/local/bin/firefox
```
and you can go back to the older one …
> test: Fix Firefox CDP driver for version 97 nightlies

- test/verify/check-system-realms
- test/verify/check-system-s4u
The sudo fix made it into RHEL 8.6 nightly and CentOS 8 Stream. Adjust
the test special case accordingly.
----
This needs to land in lockstep with https://github.com/cockpit-project/bots/pull/2729
> test: sudo with cert auth now works on RHEL 8.6/C8S

- src/session/session.c
- test/verify/check-static-login
tlog in RHEL/CentOS 9 now tries to read from its stdin even with `-c`.
While this is arguably a bug, it does not happen during VT or SSH logins
nor with `runas`. Let's just be robust against that and set stdin to
/dev/null.
----
This fixes the recent [c9s packit regression](http://artifacts.dev.testing-farm.io/96eec411-b0b0-49de-ae33-9778e853e7ad/). See https://github.com/cockpit-project/cockpit/pull/16718#issuecomment-995601497 for debugging notes.
> session: Close shell's stdin in user_has_valid_login_shell()

- Makefile.am
- configure.ac
- containers/flatpak/install
- tools/adjust-distdir-timestamps
- tools/tar-create
The goal is for a given git commit ID to always give the exact same `.tar.xz` output.
> build: build deterministic tarballs

- .gitignore
- containers/flatpak/Makefile.am
- pkg/base1/test-http.js
- src/bridge/bridge.c
- src/bridge/test-packages.c
- src/common/Makefile-common.am
- src/common/cockpitassets.gresource.xml
- src/common/cockpitwebresponse.c
- src/common/cockpitwebresponse.h
- src/common/test-webresponse.c
- src/ws/main.c
- src/ws/test-channelresponse.c
- tools/escape-to-c
We use glib-compile-resources to get a single html file bundled.  That
seems like overkill.
Ideally, we'd use #embed for this, but that seems like it'll take a
while longer, so use a small Python script to convert the .html into C,
and compile the resulting file in the usual way.
Formerly, cockpitwebresponse would default to serving a minimalist
internally-hardcoded document for errors, unless the resource was
provided.  Since this resource was provided from both -bridge and -ws,
the internal document was only used for testing.  That was for good
reason: the full document would be a pain to test on, and we'd have to
update the tests any time someone modified the html.
Let's turn the logic around there and default to the real document and
give the tests a mechanism to inject their minimal …
> build: stop using gresource

- tools/adjust-distdir-timestamps
The recently-introduced adjust-distdir-timestamps script attempts to
determine the correct base timestamp for the distribution by checking
first git, and then falling back to stat on the .tarball file, if git
fails.
The logic there is broken due to a typo, though: we anticipate the git
check may fail and redirect its stderr to avoid seeing the error, but it
ought to be redirected to /dev/null, not to stdout, where it is captured
and treated as a (completely invalid) timestamp.
> build: fix `make dist` from tarball

- test/containers/run-tests
The imp module will be dropped in Python 3.12, it's replacement is
importlib.
> containers: Stop using deprecated imp module

- test/common/cdp.py
We used to use en_US.UTF-8 as our "always available" English locale, but
it's not always available.  Use C.UTF-8 instead.
This fixes the many warnings from firefox that can be seen when running
unit-tests:
(firefox-esr:16949): Gtk-WARNING **: 14:46:06.423: Locale not supported by C library.
Using the fallback 'C' locale.
> test: change browser locale to C.UTF-8

- test/verify/check-pages
Available memory changes very impredictably, not to the least as a
result of asynchronous Cockpit page actions. Also, the playground's plot
is very small, so one gets rounding errors. 5% error margin for the
expected available memory became too small at least on centos-8-stream
on CentOS CI.
---
[example failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-2761-20220101-081017-c533283e-centos-8-stream-cockpit-project-cockpit/log.html) -- over the holidays, with e2e being down, c8s has failed consistently on this issue. Locally the test works fine now.
> test: Relax expected memory plateau in TestPages.testPlots

- test/verify/check-system-realms
After configuring 2FA for a user, it takes a while to propagate to the
client. Wait until this happens, so that the Cockpit login will not use
the simple password authentication and time out waiting for the second
factor prompt.
----
Plus a few related cleanups.
This should fix the [flake](https://logs.cockpit-project.org/logs/pull-2774-20220102-193458-c26d06ca-rhel-8-5-cockpit-project-cockpit/log.html#264-2) that recently started to happen quite often on rhel-8-5.
> test: Fix TestIPA.testUnqualifiedUsers 2FA race condition

- src/ws/cockpitauth.c
- test/common/testlib.py
- test/verify/check-connection
- test/verify/check-kdump
- test/verify/check-storage-luks
- test/verify/check-storage-stratis
- test/verify/check-superuser
Whenever the login page was opened without a client certificate (i.e. in
the vast majority of cases), ws would log an error
json_object_get_string_member: assertion 'node != NULL' failed
due to the sloppy way of checking for the existence of a client
certificate. Do this properly, and fail hard if tls sends a wrong data
type.
---
Spotted in #16764
> ws: Avoid regular json_object_get_string_member assertion, catch unexpected messages

- tools/urls-check
PF maintainers often transfer issues between their repositories. This is
nothing we need to worry about.
Such reports can be seen in:
https://github.com/cockpit-project/cockpit/issues/16607
https://github.com/cockpit-project/cockpit/issues/16221
https://github.com/cockpit-project/cockpit/issues/14752
> urls-check: Ignore patternfly redirects

- pkg/lib/cockpit-rsync-plugin.js
- tools/webpack-make
Currently it is not possible to easily run `npm run watch` and upload
artifacts using rsync as `./tools/webpack-make -r c` does. A webpack
plugin has some limitations no custom cli arguments can be passed,
either use env variables or --env.foo=1. Apart from that the plugin is
fairly simply but requires the `webpack.config.js` file to provide a
valid `packagename` for example `cockpit-machines` for the machines
plugin to the instantiated plugin.
> Add a cockpit rsync webpack plugin for cockpit plugins

- pkg/storaged/others-panel.jsx
- pkg/storaged/plot.jsx
- pkg/storaged/utils.js
Some virtual block devices, in particular not EC2 EBS volumes
(/dev/xvd*), do not appear as physical drive, so on EC2 instances there
were previously no storage graphs.
Show the "other devices" in the plot as well, as these are also
top-level objects. Factor the logic into utils, so that it can be used
in both the panel and the plot code.
Fixes #16493
----
I tested this on an EC2 instance (graphs now appearing) and my laptop (no difference). See #16493 for screenshots and debugging details.
> storage: Also show "other devices" in plots

- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/serverTime.js
- pkg/lib/timeformat.js
- pkg/systemd/services/timer-dialog.jsx
- pkg/users/expiration-dialogs.js
When using locale that contains country code (such as pt_BR or zh_TW) and
clicking on calendar icon oopses the page.
[1] mentions that hyphens should be used as separators. With this fix it
behaves as expected, that `pt_BR` has starting day Sunday but `pt` Monday.
[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation
> shell: Fix locale provided to DatePicker

- src/bridge/cockpitpackages.c
We've had a few users get confused about the generic "Not found" error
that we throw when trying to login to a system that's missing the
cockpit-system package.
Issue a better error message for that case.
Previously, when attempting to connect to a system which had `cockpit-bridge` installed, but not `cockpit-system`, you'd get a generic "Not found" error, with no hints about how to fix that.
cockpit-bridge now detects this problem and issues a more helpful message.
> bridge: give hints for missing cockpit-system package

- containers/flatpak/cockpit-client.metainfo.xml.in
This language ends up being extremely visible on our flathub page and in
GNOME Software, and it's possibly leading to people running `dnf install
cockpit-bridge` and expecting that to work.
Drop the language and just say that the server needs to have Cockpit
installed, but not enabled.
See also #16775
> flatpak: stop suggesting to install cockpit-bridge

- test/common/cdp.py
- test/common/test-functions.js
- test/common/testlib.py
This isolates pixel tests for the pages from changes in the shell
layout.
> test: Give content iframes a fixed size

- tools/test-static-code
The current logic already requires all files to contain the include, as
the sed would exit zero if there is no `^#` at all. Update the comment
accordingly to avoid confusion.
> tools: Fix comment for config.h check

- .github/workflows/flatpak-test.yml
flathub suggests running `appstream-util validate` on each upstream
commit.  Add it to the flatpak testing workflow.
> flatpak workflow: validate the generated metainfo

- test/verify/check-static-login
- test/verify/check-system-realms
sssd 2.6.1 has a broken error message ("Invalid certificate provided")
if sssd is missing a CA (https://github.com/SSSD/sssd/issues/5911)
sssd 2.6.2 fixes this and now says "Certificate authority file not
found". Adjust the expected error messages accordingly. This can be made
stricter once Fedora 35 and Debian testing both get the current version.
----
This broke [rawhide gating](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/100353/testReport/(root)/tests/_test_verify/) in yesterday's release. We don't test upstream on rawhide, but let's be prepared for the new sssd.
> test: Adjust expected sssd error message for missing CA

- test/verify/check-system-realms
These have happened for a long time, but tests did not notice these
until commit ade6e81943d5.
It is not immediately clear why that happens, but for now let's not ruin
most our PRs with this.
----
[example](https://logs.cockpit-project.org/logs/pull-16794-20220107-113510-fda46253-rhel-8-5/log.html#263)
I've seen this quite a lot in the recent days.
> test: Ignore unexpected certificate message in TestIPA.testQualifiedUsers

- test/common/testlib.py
This can also happen for `kernel.all.cpu.user`.
----
Seen [here](https://logs.cockpit-project.org/logs/pull-16798-20220110-064948-be591291-ubuntu-2004/log.html#58)
> test: Allow more variations of "Unknown metric name" messages

- tools/webpack-jumpstart
- `--force` will delete `dist/` if it already exists (should be uncontroversial)
- in `--partial` mode, only touch related files (this appeared in an earlier iteration of jumpstart work, but @martinpitt expressed misgivings about how it was duplicating the logic of the build system: let's discuss).
> two changes for webpack-jumpstart

- configure.ac
- src/bridge/bridge.c
- src/common/Makefile-common.am
- src/common/cockpitclosefrom.c
- src/common/cockpitcloserange.h
- src/common/cockpithacks.h
- src/common/cockpitpipe.c
- src/pam-ssh-add/Makefile.am
- src/pam-ssh-add/pam-ssh-add.c
- src/session/Makefile-session.am
- src/session/session-utils.c
- src/ws/cockpitauth.c
4cfc28a09dcf042b8091ca7739407a36f223ec6d introduced our own version of
close_range(), but this turned out to be the wrong API.  closefrom() is
meanwhile available on modern versions of glibc.  It features a
simplified API, with no chance of failure.
Rename cockpitcloserange.c to cockpitclosefrom.c and move the definition
into cockpithacks.h.  Introduce a configure check for closefrom() and
port all users to the closefrom() API.  In case that's not available, we
redirect those calls to our own cockpit_closefrom() (which is now only
conditionally-built).
Since neither the glibc API nor our own code have any chance of failure,
we can drop all the error checking we were doing before.
Incidentally, this should fix warnings we were occasionally seeing from
Valgrind that we were finding and …
> common: start using closefrom(), keeping our hack

- pkg/storaged/content-views.jsx
- pkg/storaged/storage-controls.jsx
- pkg/storaged/storage.scss
- pkg/storaged/stratis-details.jsx
- test/verify/storagelib.py
The main goal is to avoid https://github.com/patternfly/patternfly/issues/4547 by not having buttons in the mobile mode in the top right corner. We (almost) always have an expander on the row, which already takes space, and thus having a menu in mobile mode is free for us. And I like it in the top right corner. :-)
Demo: https://www.youtube.com/watch?v=-BSB-DN4yBM
> storage: Hide table buttons in narrow layouts

- src/ssh/cockpitsshrelay.c
This has existed since the initial commit b3a463baa2fa. Newer gcc
versions now spot this:
src/ssh/cockpitsshrelay.c:1688:11: error: variable 'size' set but not used [-Werror,-Wunused-but-set-variable]
guint32 size, i;
^
1 error generated.
Also make the `i` and `bytes` variables more local while we are at it.
----
Spotted in last night's [failed unit-test container refresh](https://github.com/cockpit-project/cockpit/runs/4755294331?check_suite_focus=true)
> ssh: Drop unused variable in on_channel_data()

- src/common/test-jsonfds.c
Fixes build failure with current clang:
src/common/test-jsonfds.c:530:25: error: variable 'object' set but not used [-Werror,-Wunused-but-set-variable]
g_autoptr(JsonObject) object = NULL;
^
----
This is the [second reason](https://github.com/cockpit-project/cockpit/runs/4762043181?check_suite_focus=true) after PR #16799 that broke the unit-tests container refresh. This time I actually did a clang build in a debian sid container locally, to ensure that this is the last bit. I'll also [trigger a refresh on this branch](https://github.com/cockpit-project/cockpit/actions/runs/1677848023).
> common: Fix unused assignment in test_memfd_json_error_cases()

- test/verify/check-static-login
The fix for https://bugzilla.redhat.com/show_bug.cgi?id=1814569 is now
present in fedora-testing
This PR should unblock https://github.com/cockpit-project/bots/pull/2785
> test: sudo and socketpair() now work properly on fedora-testing

- tools/cockpit.spec
This option doesn't exist anymore.
> cockpit.spec: drop --with-selinux-config-type

- src/bridge/cockpitpackages.c
- src/bridge/test-httpstream.c
- src/bridge/test-websocketstream.c
- src/common/Makefile-common.am
- src/common/cockpitwebrequest-private.h
- src/common/cockpitwebresponse.c
- src/common/cockpitwebresponse.h
- src/common/cockpitwebserver.c
- src/common/cockpitwebserver.h
- src/common/test-webresponse.c
- src/common/test-webserver.c
- src/ws/cockpitauth.c
- src/ws/cockpitauth.h
- src/ws/cockpitchannelresponse.c
- src/ws/cockpitchannelresponse.h
- src/ws/cockpitchannelsocket.c
- src/ws/cockpitchannelsocket.h
- src/ws/cockpithandlers.c
- src/ws/cockpithandlers.h
- src/ws/cockpitwebservice.c
- src/ws/cockpitwebservice.h
- src/ws/main.c
- src/ws/test-auth.c
- src/ws/test-authssh.c
- src/ws/test-channelresponse.c
- src/ws/test-handlers.c
- src/ws/test-kerberos.c
- src/ws/test-server.c
- src/ws/test-webservice.c
The handle-stream signal on CockpitWebServer has a veritable grab-bag of parameters.  I've wanted to extend it several times in the past, but have always shied away.
Let's start to clean this up.
Expose our internal CockpitRequest as a public type named CockpitWebRequest.  Instead of emitting six separate parameters on the handle-stream function, we now emit this single object.
We also push this object down through our stack of functions designed for responding to web requests, allowing for a large number of cleanups to move various bits of webserver implementation detail from the consumers of this API to be accessible via new accessors on CockpitWebRequest.
> webserver: expose and emit CockpitWebRequest

- test/verify/check-static-login
The fix made it to Fedora 34 stable, see commit 9ea3b2fe7f2.
---
Blocks https://github.com/cockpit-project/bots/pull/2800 but should fix the fedora-34 test on Testing Farm.
> test: sudo and socketpair() now work properly on fedora-34

- test/verify/check-connection
Fixes [this top flake](https://logs.cockpit-project.org/logs/pull-16795-20220107-134435-a1131daf-arch/log.html#15-2)
On [arch it fails most of the time](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=14&test=test%2Fverify%2Fcheck-connection+TestConnection.testCockpitDesktop#)
> Fix TestConnection.testCockpitDesktop arch test, and race condition

- test/common/run-tests
- test/common/testlib.py
We expect pixel test failures to be deterministic, expecially since we
wait for all animations to have stopped.  Often, failed pixel tests
are even expected since we update the references only late in the life
of a pull request.
> test: Don't retry failed pixel tests

- pkg/packagekit/kpatch.jsx
- test/verify/check-packagekit
This describes more precisely what this is about, and makes our UI
consistent with the RHEL documentation:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/applying-patches-with-kernel-live-patching_managing-monitoring-and-updating-the-kernel
> packagekit: Rename "Kernel patch" to "Kernel live patch"

- test/verify/check-system-realms
Occasionally the realmd tests run into a race condition of our service
proxy with realmd's idle timeout:
realmd[2202]: quitting realmd service after timeout
realmd[2202]: stopping service
cockpit-bridge[4480]: org.freedesktop.realmd: couldn't get all properties of org.freedesktop.realmd.Service at /org/freedesktop/realmd: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
The proxy causes the service to immediately start again, so there is no
harm done.
---
Spotted in [this test flake](https://logs.cockpit-project.org/logs/pull-16831-20220113-160722-5c62c8e9-fedora-35-devel/log.html#261). The corresponding [journal](https://logs.cockpit-project.org/logs/pull-16831-20220113-160722-5c62c8e9-fedora-35-devel/TestIPA-testClientCertAuthentication-fedora-35-127.0.0.2-2401-FA …
> test: Ignore realmd disconnect message on idle timeout for property updates

- HACKING.md
- Makefile.am
- test/check-dist
- test/git-hook-post-commit
- test/git-hook-pre-push
- test/static-code
- move the `dist/` checks to their own file and run it as part of `make check`
- make sure to invoke the test script in an environment free from `GIT_` envvars
- fix error handling due to unexpected `set -e` behaviour
- add a commit hook
- general cleanups
> more static code cleanups

- test/common/cdp.py
The --window-size parameter has no effect.
> test: Use MOZ_HEADLESS_WIDTH et al to control Firefox window size

- containers/flatpak/test/test-ssh
> flatpak: Wait for application to stop during test

- test/verify/check-metrics
This page consists of one `table` element with more `tr` elements, where
each has a button. Previous selector was not unique if there were more
than one item in the table.
> test: Don't expect only one item on dashboard

- .gitignore
These are generated by `make check`.
> .gitignore: ignore *.log and *.trs

- pkg/lib/cockpit-components-table.jsx
The TdExpandType requires a rowIndex to be provided as property.
> pkg/lib: add required property rowIndex

- test/verify/check-metrics
This page consists of one `table` element with more `tr` elements, where
each has a button. Previous selector was not unique if there were more
than one item in the table.
Cherry-picked from main branch commit 73497a629
> [rhel-8.5] test: Don't expect only one item on dashboard 

- test/verify/check-system-realms
- test/verify/check-system-s4u
The sudo fix made it into RHEL 8.6 nightly and CentOS 8 Stream. Adjust
the test special case accordingly.
Cherry-picked from main commit fd9e6a09fd20c.
----
Should fix [this failure](https://logs.cockpit-project.org/logs/pull-16849-20220119-090844-ce19f66c-centos-8-stream/log.html#170-2) which I ignored in #16849.
> [r8.5] test: sudo with cert auth now works on RHEL 8.6/C8S

- test/git-hook-post-commit
Deleting files will currently fail the post-commit hook (and therefore
the pre-push hook) with a message like
fatal: pathspec 'tools/gen-spec-dependencies' did not match any files
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
- 3f6fecd00 build: produce static cockpit.spec for release
This is caused by the fact that the filename shows up in the list of
changed files, but can't be extracted from the commit via git-archive,
because it doesn't exist anymore.
Replace our use of git-show with git-diff-tree, which is a better fit
anyway).  It also has a very nice feature to filter certain types of
events (eg. --diff-filter=d for deletes).
> git-hook-post-commit: deal with deleted files

- pkg/apps/application-list.jsx
- pkg/lib/os-release.js
- pkg/shell/topnav.jsx
- pkg/static/login.js
- pkg/storaged/client.js
The most obvious confusion is with remote logins:
It's more subtle with the Applications page, the refresh would simply fail if you e.g. logging into a remote Debian machine from a Fedora host.
> Fix /etc/os-release handling

- pkg/packagekit/kpatch.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
Testing for kpatch support can take quite long (UX review reported 8
seconds), and it is apparently confusing/not discoverable for users to
wait that long until they see the status of kpatch.
During detection of kpatch support on RHEL (the only OS where we
actually expect this to succeed), show a spinner as status. Also show a
disabled "Edit" button to avoid the layout jumping around once it gets
enabled.
Don't show the spinner on other OSes, as we expect it to fail there, and 
it is both confusing and also changing the page layout when the "Kernel
live patching" entry entirely disappears from the Settings card.
------
- Depends on PR #16833
On RHEL while loading:
On RHEL when loading is done (no change compared to main):
On RHEL when kpatch package is not available (done synthetically, …
> packagekit: Show a spinner while checking for kpatch support on RHEL

- src/branding/arch/Makefile.am
- src/branding/centos/Makefile.am
- src/branding/debian/Makefile.am
- src/branding/fedora/Makefile.am
- src/branding/opensuse/Makefile.am
- src/branding/rhel/Makefile.am
- src/branding/scientific/Makefile.am
- src/branding/ubuntu/Makefile.am
We need to add an extra / after the $(DESTDIR) and before /usr in order
to get the correct path.
...but the real scandal here is that not a single test failed :(
> branding: fix symlink installation

- test/verify/check-static-login
The fix made it to Fedora 35 stable as well. Similar to what commit
d9eda6d263 did for Fedora 34.
---
Blocks and needs to land in lockstep with a fedora-35 image refresh that includes [selinux-policy-35.11-1.fc35 ](https://bodhi.fedoraproject.org/updates/FEDORA-2022-87a0b7e8d0): https://github.com/cockpit-project/bots/pull/2839
This has caused [f35 packit failures](http://artifacts.dev.testing-farm.io/6ef24b96-630c-4044-b24a-d4509c34b4f4/) a few days ago when the new SELinux landed. This PR should make them green again.
> test: sudo and socketpair() now work properly on fedora-35

- test/verify/check-pages
Our fedora-testing image is moving to Fedora 35. Adjust
TestPages.testBasic for the changed name. Invert the condition to do the
right thing for future Fedora versions.
---
Blocks https://github.com/cockpit-project/bots/pull/2841
> test: Adjust expected Fedora documentation name for fedora-testing

- configure.ac
- containers/unit-tests/scenario/distcheck
Commit c66a65feacf4 caused Fedora koji builds to break on finding the 
debug symbols. Revert it for now. Let's figure this out after the 
release: Debian builds probably already supply the flag as part of their
reproducible build efforts, and we can put it back into the .spec file
when/where needed.
Also revert the corresponding unit test from commit 59e173100.
---
Supposed to fix [these koji failures](https://kojipkgs.fedoraproject.org//work/tasks/5249/81755249/build.log) which broke the release. I did a [scratch build with a clean revert](https://koji.fedoraproject.org/koji/taskinfo?taskID=81758410) which succeeded.
We don't see this upstream because this only fails on all arches in [Rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=81754804) but in [Fedora …
> Revert "build: add -ffile-prefix-map to CFLAGS"

- src/bridge/test-pcp-archives.c
On 32 bit architectures, `time_t` can now be a 64 bit type, so that
printing a `long` (32 bit) is not sufficient. Print/cast the time_t into
a `long long` to ensure that it works on all architectures.
Fixes build failure on x32:
src/bridge/test-pcp-archives.c: In function ‘test_metrics_archive_timestamp_now’:
src/bridge/test-pcp-archives.c:321:44: error: format ‘%li’ expects argument of type ‘long int’,
but argument 2 has type ‘time_t’ {aka ‘long long int’} [-Werror=format=]
----
This should fix the [Debian build failure on x32](https://buildd.debian.org/status/fetch.php?pkg=cockpit&arch=x32&ver=261-1&stamp=1643047857&raw=0).
> bridge: Fix time_t format string in test_metrics_archive_timestamp_now()

- packit.yaml
This introduces some architecture variety; so far we have only tested on
x86_64, and thus were missing issues about `int` size, endianess, or RPM
builds on different architectures.
----
This should hopefully prevent issues like yesterday's release failure -- see PPR #16872
> packit: Run package build and unit tests on i386 and s390x

- test/verify/check-kdump
Enabling kdump for the first time rebuilds the initrd, which is
inherently slow. On busy CI machines it sometimes takes more than a
minute.
The `TestKDump` class already does this by bumping the global timeout.
Be more specific here, to avoid hiding UI issues for operations that
should be fast.
----
[example 1](https://logs.cockpit-project.org/logs/pull-16686-20220125-102735-bf8b3591-rhel-8-6/log.html), [example 2](https://logs.cockpit-project.org/logs/pull-16826-20220113-155723-e5f39086-rhel-8-6/log.html#48), [example 3](https://logs.cockpit-project.org/logs/pull-16779-20220105-090740-28f20c62-centos-8-stream/log.html#48). I found some more on our logs server, but these should be sufficient to prove the issue. :grinning:
> test: Give starting kdump.service more time in TestKDumpNFS

- .gitignore
- Makefile.am
- configure.ac
- selinux/Makefile.am
- tools/cockpit.spec.in
- adds a `Makefile.am` to `selinux/` and a `--enable-selinux-policy` option
- removes the rules for building this stuff from the spec file
> build selinux policy as part of main build

- src/tls/certificate.c
- src/tls/cockpit-certificate-ensure.c
While trying to capture those `authorize` messages, I enabled `DEBUG 1` in `utils.h` and got greeted by compilation errors.
> Fix certificate filenames for debug calls

- src/bridge/bridge.c
- src/bridge/cockpitpipechannel.c
- src/bridge/test-pipe-channel.c
- src/session/session.c
- src/ws/cockpitauth.c
In the light of [pwnkit](https://blog.qualys.com/vulnerabilities-threat-research/2022/01/25/pwnkit-local-privilege-escalation-vulnerability-discovered-in-polkits-pkexec-cve-2021-4034) I audited all our usage of `argv`. Fortunately I didn't find anything important, but a few cleanups and robustifications can't hurt.
> argv robustifications

- HACKING.md
The hacking guide points to non-existing `tools/gen-spec-dependencies`, thus replaced that with `tools/create-spec`. Also adding the command makes it run cleanly, instead of failing to find `tools/cockpit.spec`.
Not sure about `--version 1`, let me know if that needs to be changed.
> hacking: update to use tools/create-spec

- pkg/systemd/terminal.jsx
- test/verify/check-system-terminal
The existing test ignores almost everything and is thus not very
useful.  The ".xterm-cursor-layer" is probably intended to catch the
cursor only, but does in fact covers the whole terminal area.
Also, the exact scrollbar position seems to vary, which has started to
cause random failures.
Thus, let's test the header and actual text area (without scrollbar)
separately.
> system: Improve terminal toolbar on mobile

- test/verify/check-connection
Try to check if we're being served the expected branding (CSS, logo,
favicon) correctly.  Make sure the variable substitutions are working
properly.
Add a pixel test for the login page to make sure it's visually correct.
>  test: add tests for working branding 

- .github/workflows/flatpak-test.yml
- autogen.sh
- packit.yaml
When run as `./autogen.sh rpm` then configure the package in exactly the same way as it would be configured by RPM for a build on this system.
@martinpitt mentioned wanting to have something like this.  To be honest, I'm not crazy about putting this in `./autogen.sh` and would like to find a better place for it.
> autogen.sh: add 'rpm' option

- test/README.md
- test/common/cdp.py
- test/common/test-functions.js
- test/common/testlib.py
- test/run
- test/verify/check-networkmanager-vlan
- test/verify/check-packagekit
- test/verify/check-packages
- test/verify/check-pages
- test/verify/check-shell-host-switching
- test/verify/check-shell-menu
- test/verify/check-static-login
- test/verify/check-superuser
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-services
- test/verify/check-users-roles
- test/verify/storagelib.py
test/common/testlib.py has a set of layouts and test code can switch a
Browser into one via Browser.set_layout.  Right now there is only
"desktop" and "mobile", but more can be easily added.
Browser.assert_pixels cycles through all the defined layouts and does
a pixel test for each.
> test: Rework pixel testing and mobile layout logic

- pkg/lib/machine-info.js
- test/verify/check-system-info
Issue: On multi-channel memory platforms, the Hardware information page / Memory information will only show the information of the Channel 0. 
Solution: Add Bank Locator into the locator info to distinguish the memory of different channels.
> Fixed incorrect memory information on multi-channel memory platforms.

- pkg/lib/cockpit-rsync-plugin.js
Scribbling over /usr/share/cockpit/ is evil: This is package manager
territory, and it might not even be writable (such as on Fedora CoreOS).
Sync to /usr/local/share/cockpit/ instead, which is meant for custom
built code. This also makes it possible to quickly go back to the distro
version.
> lib: Let webpack rsync plugin rsync to /usr/local/share/cockpit/

- pkg/storaged/client.js
So that we don't forget to bump them all together at the same time
when the time comes.
> storage: Document interface revision policy of Stratis

- pkg/systemd/overview-cards/healthCard.jsx
- pkg/systemd/overview-cards/shutdownStatus.jsx
- test/verify/check-system-info
In the health card in the system overview page we now show a scheduled
reboot/poweroff with the option to cancel it. The implementation does
not watch dbus property changes on org.freedesktop.login1.Manager as
they are not emitted when using `shutdown --reboot $timestamp`. For now
the file (/run/systemd/shutdown/poweroff) systemd creates when
requesting a shutdown is watched to detect scheduled shutdowns. The
systemd issue for dbus property changes is tracked here:
https://github.com/systemd/systemd/issues/22244
---
The Health card shows a scheduled reboot or poweroff. This can also be cancelled.
> systemd: display the scheduled reboot/shutdown time

- pkg/systemd/overview-cards/healthCard.scss
- pkg/systemd/overview-cards/shutdownStatus.jsx
- pkg/systemd/overview-cards/shutdownStatus.scss
- pkg/systemd/page-status.jsx
Apply the same change as was applied to the "bug fix" icon, so the
scheduled reboot icon does not stand out.
This makes everything look the same:
Required for https://github.com/cockpit-project/cockpit/pull/16885
> systemd: style the shutdown/reboot icon grey

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
Use Flex for a better layout, to avoid line breaks inside of the 1/5/15
minute fields.
---
Wide:
Medium narrow:
Minimum width:
Wide:
Medium narrow:
Minimum width:
> metrics: Improve load average splitting for narrow layouts

- test/common/testlib.py
Once in a hundred times or so, anti-aliasing of glyphs, rounded
corners, or similar things produces one or two pixel differences among
tens of thousands of perfectly rendered ones.  They are really hard to
spot in a delta image and not worth doing anything about.
> test: Allow 5 differences before failing a pixel test

- pkg/Makefile.am
Go 1.16 now defaults to `GO111MODULE=on` [1], which breaks our build, with a
*really* unhelpful error message, too:
package cockpit-kube-auth is not in GOROOT (/usr/lib/golang/src/cockpit-kube-auth)
Switch back to the old behaviour.
[1] https://go.dev/doc/go1.16
Fixes #16920
See https://bugzilla.redhat.com/show_bug.cgi?id=2050088
> Fix Build against Go 1.16

- test/run-verify-host.sh
firefox pulls in half a desktop, we don't need any of these for a
headless test. This reduces the number packages from 133 (459 MB) to 66
(365 MB).
> fmf: Don't install weak firefox dependencies

- test/verify/packagelib.py
packagekit.service tends to hang on shutdown. This bug [1] is ancient,
and we kept working around it in bots' *.install files; but we keep
losing that hack with newer images, and it's also missing on
rhel-9-0.install.
So centralize the hack here for all PackageKit related tests.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1717185
----
This ought to help a bit with the ridiculous [testTracer](https://logs.cockpit-project.org/logs/pull-16891-20220201-165621-7b1e6dcf-rhel-9-0/log.html) runtime of > 5 minutes on our infra. Locally it was ~ 170 seconds on main, and now around 90.
> test: Reduce packagekit.service stop time

- test/common/testlib.py
Leave it up to the user to make these tests destructive instead, in the case
the `machine_class` a test defines, is different than the class
`test/common/run-tests` script global machine uses for VM creation.
Background:
The `anaconda-webui` tests, do not use the `VirtMachine` class for the test VM
creation. For the purpose of overriding `Machine` class, `machine_class` property is
used, for the whole test suite.
The condition removed by this commit was blocking `anaconda-webui` tests
to have non-destructive tests running against the same global machine.
The only other obvious user of the `machine_class`, that could have been
affected by this change is `test/containers/check-bastion`, but that test
is destructive and therefore not affected.
> testlib: allow nondestructive tests runs against global machines with custom machine_class

- test/run-verify-host-user.sh
- test/verify.fmf
- test/verify/check-packagekit
testInfoSecurity and testTracer reboot, so they can't run on the Testing
Farm. Mark all other tests as nondestructive, and drop the special
treatment in the FMF tests. This will run a few more tests in FMF.
----
Also do some FMF test adjustments. The first round is experimental to get some details if the excluded tests work now, and if not, why exactly.
> test: Stop marking rebooting TestUpdates tests as nondestructive

- test/git-hook-post-commit
If this is used as a post-commit hook (and not run from the pre-commit
hook) then the output often blends in a little too well with the normal
post-commit messages like
```
[branch 2523c98cf] subject: made a change
1 file changed, 192 insertions(+), 88 deletions(-)
```
Detect if we are being run directly and make the output red in that
case.
I've been using this locally for a week or so and it's a big usability improvement for me.
> git-hook-post-commit: add some colour

- pkg/metrics/metrics.jsx
If timezone is shifted by 30 minutes compared to UTC, then `setMinutes`
does not behave as expected.
Example:
`time` in UTC is "10:34" which in some timezone is "3:04". We then want
to round the time by one minute down, so we do `setMinutes(33)` which
works for all timezones that are shifted by full hours but it completely
breaks some timezones as they now would not be "3:03" but "3:33" which
in UTC would be "11:03".
Fixes #16492
Before:
Same timezone:
Different timezone:
With this PR different timezone:
@ testing https://github.com/cockpit-project/cockpit/pull/15626
> metrics: Use `setUTC*` functions to work across all timezones

- test/common/run-tests
This does not change the logic much yet, just shifts around a lot of code to reduce the scope of variables/members, and make the structure easier to understand. It's a prerequisite for changing the scheduling.
> run-tests code cleanup

- Makefile.am
- pkg/build
- src/bridge/Makefile.am
- src/common/Makefile-common.am
- src/pam-ssh-add/Makefile.am
- src/ssh/Makefile-ssh.am
- src/tls/Makefile-tls.am
- src/websocket/Makefile-websocket.am
- src/ws/Makefile-ws.am
This builds the tree, runs `make install` into a temporary DESTDIR, and then rsyncs the result to another host (default: `c`).
This is intended to be used with the recently-added ./autogen.sh rpm feature in order to live-apply changes to a running VM image.
An incremental `make rsync` after no changes takes less than one second.
- check out the branch
- `./autogen.sh rpm`
- `test/image-prepare -q fedora-35`
- `vm-run -q fedora-35&`
- `make -j8 rsync`
- `ssh c systemctl enable --now cockpit.socket`
- open web browser, login
- break some stuff
- `ssh c systemctl stop cockpit.socket`   # needed because of "Text file busy"
- `make rsync`
- `ssh c systemctl start cockpit.socket`
- open web browser, watch stuff fail
- automatic cockpit restart to avoid the `ETXTBUSY` thing
- ability to install …
> build: add `make rsync` target

- Makefile.am
- tools/arch/PKGBUILD.in
- tools/debian/changelog.in
Similarly how we already create a valid spec file, rename PKGBUILD and
debian/changelog to *.in and replace the VERSION and SOURCE macros at
`make dist` time.
This fixes `image-customize --build` for deb and arch.
> tools: Build valid arch PKGBUILD and Debian changelog in dist tarballs

- pkg/lib/cockpit-components-logs-panel.jsx
Users might want to select log message or identifier to use it for
searching. We should not navigate in such case.
Fixes #14327
I tried to write tests but I am having no luck...
```
b.mouse(".cockpit-logline:nth-child(2) .cockpit-log-message", "mousedown", 0, 10)
b.mouse(".cockpit-logline:nth-child(2) .cockpit-log-message", "mousemove", 140, 10)
b.mouse(".cockpit-logline:nth-child(2) .cockpit-log-message", "mouseup", 140, 10)
```
> logs: Don't navigate to log details when selecting details

- pkg/systemd/services/service.jsx
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-firewall
- test/verify/check-networkmanager-team
- test/verify/check-system-services
The previous networking pixel tests were wildly inconsistent in their
assumed network interfaces: The references for basic and team had no
"virbr0", while the references for bond and bridge did. This was not a
conscious decision, just an arbitrary result of in whichever order
the tests happened to run when generating the references.
Stop the libvirt default network (i.e. virbr0) at the beginning of all
of these tests. In addition, the basic test assumed that firewalld was
running, so start it to actually make sure of that.
This makes these tests independent from whether
check-networkmanager-firewall runs before or after them.
----
This addresses the first four failures of [this mess](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16942-20220208-185207-b1fb7771-fedora-35/log. …
> fix networking and services pixel tests

- containers/ws/Dockerfile
- containers/ws/README.md
This will unblock https://github.com/cockpit-project/bots/pull/2907 .
Blockers:
Post landing:
> containers: Move cockpit/ws to Fedora 35

- test/common/testlib.py
- test/verify/check-system-realms
Example: https://logs.cockpit-project.org/logs/pull-16959-20220209-131529-8148213f-rhel-8-6/log.html#245
> test: Allow restart messages in testClientCertAuthentication

- test/verify/check-connection
There are several uses of curl with headers (-H) in this file, and all
of them involve either many headers or large values, and all of them are
written with long lines.
Use the new machine.curl() utility function from bots.
> verify: use machine.curl()

- test/common/run-tests
- test/verify/check-testlib
This reworks the run-tests parallel scheduler for serial tests in a very fundamental way.
Computing the batches in advance by just splitting the list into equal parts does not work well: It does not take retries and wildy different durations into account, and thus often created a wild imbalance beween the total runtime on the serial runner machines:
4592s on [host], 118 serial tests: 0: 4589s, 1: 2078s
In many cases this even led to a serial test batch dominate the total test time.
About half of the current weather report's "> 1 hour" test runs are due to this problem. [example 1](https://logs.cockpit-project.org/logs/pull-16904-20220202-163951-7852b004-fedora-35-firefox/log), [example 2](https://logs.cockpit-project.org/logs/pull-16904-20220202-163953-7852b004-fedora-35/log)
- builds on …
> run-tests dynamic serial test scheduling, drop static --batches, show number of parallel tests

- test/common/testlib.py
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-packagekit
- test/verify/check-pages
- test/verify/check-session
- test/verify/check-shell-keys
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
- test/verify/check-static-login
- test/verify/check-storage-luks
- test/verify/check-storage-stratis
- test/verify/check-superuser
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-system-tuned
- test/verify/check-users
- test/verify/check-users-roles
When it is used due to `relogin()`, `reload()` or `logout()` don't
always specify it but let these methods to do it.
There are still 11 cases where `allow_restart_journal_messages()` is used - these are due to different reasons than us logging out or relaoding (like killing cockpit, restarting the machine, removing host...)
Lets see if there are some flaky messages
> tests: Unify usage of `allow_restart_journal_messages()`

- test/common/testlib.py
- test/run
With parallel tests it could happen that two pixel tests were running
around the same time. One would start the git clone, the other would see
the existing .git; but if the cloning was not done yet, the actual files
were missing, and the test failed with "New pixel test reference".
Let's avoid that by going back to pulling the reference images from
test/run; this reverts commit c20822b980b. In exchange, replace the 
on-demand checkout in testlib.py with an instructive error message.
----
[example 1](https://logs.cockpit-project.org/logs/pull-16942-20220209-124540-22d91db9-fedora-35/log.html#89), [example 2](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16942-20220210-104937-a2b3c82a-fedora-35/log.html#267)
Now that we run 8 `@nd` tests in parallel instead of 2, this became …
> test: Fix race condition with checking out pixel tests

- test/common/testlib.py
As seen [here](https://logs.cockpit-project.org/logs/pull-16981-20220211-141347-7844ce1d-fedora-34/log.html#275):
```
Failed to issue method call: No session '%s' known
```
> test: Fix use of f-string

- pkg/lib/cockpit-components-password.jsx
- pkg/users/password-dialogs.js
Mark fields that need new passwords so that browser does not try to
input remembered passwords but rather offers to generate a new one.
Also mark old password so in that case browser tries to offer remembered one.
Before when I tried to create new user it auto filled my current password and username:
Now it does not do that:
And it offers to create a new one that is then filled in both fields:
And when old one is needed it is still correctly auto set:
> users: Use `autocomplete` property for password inputs

- HACKING.md
- tools/git-hook-pre-rebase
One of the more annoying things about the use of submodules is rebasing.
If the submodule was updated upstream and you have a copy if it checked
out in your working directory, then after the rebase, the old version
will still be checked out, and now it's the incorrect version.
More than once I've accidentally committed the old version again, as a
result of subsequent careless use of `commit -a`.  Even if you notice
the problem, it's an unnecessary nuisance.
Add a script to delete submodules before performing a rebase if:
- the submodule is checked out
- it contains no local changes
- it will be out of date after the rebase
Add a note to HACKING.md, suggesting to install the hook.
> tools: add git-hook-pre-rebase

- test/common/testlib.py
- test/verify/check-networkmanager-basic
- test/verify/check-users
I am mostly focusing on coreos being busted on second retry for `TestAccounts.testBasic`. The pattern is always the same in any PR that forces this test to be retried.
Happend in this PR - [link](https://logs.cockpit-project.org/logs/pull-16959-20220212-070809-163abf03-fedora-coreos/log.html#300-2)
In #16957 (retried 3 times already) [link](https://logs.cockpit-project.org/logs/pull-16957-20220212-093355-c5c8f01e-fedora-coreos/log.html)
In #16981 - [link](https://logs.cockpit-project.org/logs/pull-16981-20220212-092125-57e3bb8a-fedora-coreos/log.html#300-1)
It was fine 4 days ago, see #16940.
It always says:
```
> warning: fatal: Authentication failed: Timeout
```
and then CDP is sad is no page is loaded.
Fixes #16970
> tests: Some tweaks

- pkg/apps/application.jsx
- pkg/metrics/metrics.jsx
- pkg/networkmanager/firewall.jsx
- pkg/networkmanager/network-interface.jsx
- pkg/shell/base_index.js
- pkg/storaged/details.jsx
- pkg/systemd/hwinfo.jsx
- pkg/systemd/logDetails.jsx
- pkg/systemd/overview-cards/insights.jsx
- pkg/systemd/overview-cards/systemInformationCard.jsx
- pkg/systemd/overview-cards/usageCard.jsx
- pkg/systemd/page-status.jsx
- pkg/systemd/services/service-tabs.jsx
- pkg/users/account-details.js
- test/verify/check-metrics
- test/verify/check-networkmanager-firewall
- test/verify/check-pages
- test/verify/check-shell-host-switching
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-services
The browser creates an entry in the history whenever an iframe changes
its "window.location" (which is how our pages implement
in-page-navigation).  The shell did not expect this and would add
another entry whenever the location of the current iframe changes.
---
Cockpit used to interfere with the browser history, and hitting the back button would frequently get into a loop, for example. This has been fixed.
> shell: Fix browser history

- HACKING.md
> HACKING: Fix typo in git hook installation

- pkg/users/account-create-dialog.js
- pkg/users/password-dialogs.js
- test/verify/check-users
1. Enter long password (we enter 300 characters long)
2. Click on 'Set password' button - that triggers `validate()`
3. `validate()` sets `errors.password` to "Password is longer than 256 characters" and it is shown in the UI
4. Then `validate()` calls `password_quality()`. This takes longer because it checks 300 characters long password
5. But since the UI is updated with the error, bots type in new correct password
6. `change()` function that is invoked when inputs change clears the `errors` object
7. Now that `password_quality()` finally resolved, it checks if there are errors
in `errors` object, but that was already cleared. So it succeeds.
8. `validate()` succeeded, we get back to step 2, the promise resolved,
so it calls `passwd_change(account.name, state.password)`
9. …
> Fix user test races

- test/common/testlib.py
If a session does not go away after killing and terminating it, show the
session-status on stderr (i.e. the test log), so that we see what's
going on.
---
[This flake](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16938-20220214-145222-37e948c0-fedora-34/log.html#39) currently happens rather often, let's see what's going on. I'll rebase this after landing PR #16993, as that fixes the far more important race. But maybe in the meantime it catches this case, and I can investigate it already.
> test: Debug hanging logind sessions

- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-team
- test/verify/netlib.py
Commit e3802c02407 was not strong enough -- sometimes, virbr0 still came
online in the middle of a test. This also sometimes disrupts the
Firewall tests when they count the expected zones at the beginning, but
a second one (for virbr0) suddenly springs into existence.
Stop this harder by also disabling autostart. Also centralized it in
NetworkCase.setUp().
Avoid clobbering the `m` machine alias in setUp with a regexp match,
rename the variable.
---
[example failure](https://logs.cockpit-project.org/logs/pull-16993-20220214-162516-f665c18d-fedora-35/log.html#55)
> test: Factorize and strengthen disabling of virbr0

- test/verify/check-system-journal
If the daemon is already running when installing the mock
config/workflow, it will not pick it up.
---
[example](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16999-20220214-194134-4b331678-fedora-35/log.html#253-2), [example](https://logs.cockpit-project.org/logs/pull-16999-20220214-194134-4b331678-fedora-34/log.html#253-2)
[debugging notes](https://github.com/cockpit-project/cockpit/pull/16999#issuecomment-1039858186)
> test: Restart reportd after installing custom configuration

- tools/cockpituous-release
Fedora 36 got branched off and now needs its own koji builds. It does
not yet use bodhi. See
https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html
Drop Fedora 34, so that we keep the two latest releases, as usual.
> cockpituous: Add Fedora 36, drop 34

- test/common/testlib.py
Fedora 34's logind/systemd often leaves "closing" state logind sessions
around with *zero* processes. Explicitly kill the scope units to clean
up the session.
This is an utter hack, but as long as it does not happen any more on
newer versions, it will go away soon (as we just stopped updating Fedora
34 anyway).
---
Validated locally with
for i in `seq 10`; do TEST_OS=fedora-34 test/verify/check-users TestAccounts.testAccountLogs $RUNC -stv || break; done
Before, this reproduced the broken situation in the first or second run.
[example 1](https://logs.cockpit-project.org/logs/pull-16908-20220215-104929-2ca6371e-fedora-34/log.html#298), [example 2](https://logs.cockpit-project.org/logs/pull-16379-20220215-094728-1630e9de-fedora-34/log.html#300)
If we see this anywhere else, I'll report it …
> test: Increase session cleanup hammer size on Fedora 34

- test/common/testlib.py
Unexpected journal messages, such as service errors or crashes, are
often the cause for UI failures. Run the journal message check on test
failures as well, so that we can start writing more precise naughty
patterns.
> test: Check for unexpected messages on failures as well

- src/client/cockpit-client
- src/client/cockpit-client.ui
This reverts commit 6b716b1b87927ed4428a5514c27ed69242ce2fc4.
This is intended to land after #16938 and undo the temporary removal of back/forward in #16643.
> Revert "cockpit-client: disable and hide forward/back"

- containers/Makefile.am
- containers/ws/install-package.sh
The install scripts require `mount`, but that fell out of the default
fedora:35 container recently. This caused the latest container refresh
to fail to install:
+ /bin/mount --bind /host/etc/cockpit /etc/cockpit
/container/atomic-install: line 67: /bin/mount: No such file or directory
We need to land this, and immediately do a new official container build, as the current official one is just broken.
Spotted by https://github.com/cockpit-project/bots/pull/2950
> containers: Explicitly install util-linux-core into cockpit/ws

- test/verify/check-storage-vdo
It is already present from distribution.
It might be possible that some distros still need it, then I'll wrap it into `if !(rpm -q kmod-kvdo)...`
> test: Do not create kmod-kvdo package

- test/verify/check-metrics
When purging pcp on debian testing with 5.3.6 we are left with a broken
dependency so pmlogger does not start:
/etc/systemd/system/pmlogger.service.requires/pmlogger_farm.service:
broken symbolic link to /lib/systemd/system/pmlogger_farm.service
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986074
> test: workaround purge not cleaning up pmlogger requires

- test/common/cdp.py
Firefox 96 enables Fission [1] by default to improve site isolation.
This broke DevTools Protocol's `Page` events [2]. Disable Fission to
work with current nightlies as well.
[1] https://wiki.mozilla.org/Project_Fission
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1746154
> test: Fix Firefox CDP driver

- packit.yaml
- test/run-verify-host-user.sh
- test/verify/check-packagekit
- test/verify/check-static-login
Corresponding to cockpituous release targets in commit c9eadef1a0
----
Yesterday's [fedora-36 release](https://bodhi.fedoraproject.org/updates/FEDORA-2022-7b7b2119dc) [failed several tests](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/112990/testReport/(root)/tests/_test_verify/). I waived it, let's walk through them here.
- Builds on top of PR #17021
- Needs https://github.com/cockpit-project/bots/pull/2956
- Needs https://github.com/cockpit-project/bots/pull/2970
> packit: Start testing on Fedora 36

- test/verify/check-storage-nfs
All the other PackageKit related tests are skipped on arch
(check-packagekit, check-apps, TestMetricsPackages, etc.) as the current
mechanism of creating, installing, and cleaning up fake packages is
buggy.
Skip this test as well, as it runs into similar issues.
---
[example 1](https://logs.cockpit-project.org/logs/pull-15626-20220209-203633-a56677da-arch/log.html#153), [example 2](https://logs.cockpit-project.org/logs/pull-2987-20220222-125942-c6c8d0f1-arch-cockpit-project-cockpit/log.html)
I promise, I'll re-enable lots of tests after https://github.com/cockpit-project/bots/pull/2987 lands (in particular, the networkmanager ones) for a net positive balance :wink:
> test: Skip TestStoragePackagesNFS.testNfsMissingPackages on arch

- test/fedora-coreos.install
- test/image-prepare
This ensures that we stay independent from any changes that go on in
online repositories, and our mock/pbuilders are sufficiently pre-cached.
This got lost in the move to image-customize in commit e060058027fecc83.
> test: Reinstate offline builds for rpms/debs

- pkg/lib/cockpit-components-password.jsx
- pkg/users/account-create-dialog.js
- pkg/users/password-dialogs.js
I am trying to add password hints but for that I need some preparation work. Only visible change is dropping of password confirmation, now looks like this:
One disadvantage is, that now the value of password input is held by two components separately. That is not ideal, but once component needs it for setting it eventually up and other to run checks on it.
> Password component cleanups

- pkg/networkmanager/interfaces.js
- test/verify/check-networkmanager-checkpoints
The call_object_method function used to pass all return values as
individual arguments to the "then" function, but this got accidentally
changed in e4093f5e6ab3125de96aca0db403313a5962ccde to pass them all
in an array.
Thus, checkpoint_create would return an array containing the
checkpoint object path instead of the object path directly.  When this
got passed to checkpoint_destroy later on, this would fail with an
"invalid arguments" error.  Cockpit doesn't look closely at the exact
error, interpretes a failed checkpoint_destroy call always as "we got
disconnected", assumes that the checkpoint has been rolled back, and
brings up the "Connection will be lost" dialog.
This was missed by the tests because we switch off checkpoints during
those tests that dont expect them.
This is fixed here …
> networking: Fix return value of CheckpointCreate method - FIX COMMIT MESSAGE ON MERGING

- tools/debian/control
We don't want to add a "strong" dependency like "Recommends:" or even
"Depends:": We don't want to pull LVM packages onto a system just
because the admin installs Cockpit.
But let's at least show it as a suggested add-on and explain why you may
want it.
Fixes #17041
> tools: Suggest udisks2-lvm2 for Debian/Ubuntu

- pkg/networkmanager/ip-settings.jsx
- test/verify/check-networkmanager-settings
- test/verify/netlib.py
Initializion of the dialog was wrong for ignore-auto-dns,
ignore-auto-routes, and dns-search.  Taking values out of the dialog
was wrong for dns-search.
> networking: Fix IP Settings dialog

- test/run-verify-host.sh
Commit 24bb69a1927 accidentally dropped setting `$LOGS` to an absolute
path if `$TMT_TEST_DATA` is not set. This causes the test to fail with
test/browser/run-test.sh: line 75: logs/exitcode: No such file or directory
when running against older `tmt` versions. This is the case on the
internal RHEL testing farm, but not on the public Fedora/CentOS one
(which is why we didn't see this in packit).
> tmt: Put back absolute log path for older tmt versions

- pkg/lib/patternfly/patternfly-4-overrides.scss
- pkg/systemd/overview-cards/lastLogin.jsx
- pkg/systemd/overview-cards/shutdownStatus.jsx
Local workaround to use flex properly with a gap instead of having a right margin.
Upstream issue: https://github.com/patternfly/patternfly/issues/4523
> PF: Work around flex; make it use gap

- test/image-prepare
This was removed in commit e060058027f, but we are using it for the
dnf-copr scenario.
---
See https://github.com/cockpit-project/bots/pull/2993 , where the [dnf-copr scenario failed](https://logs.cockpit-project.org/logs/pull-2993-20220224-025251-50c295d9-fedora-testing-dnf-copr-cockpit-project-cockpit/log.html)
> test: Put back image-prepare --overlay

- test/run-verify-host-user.sh
This test repeatedly fails on the RHEL testing farm without any error
message, and then corrupts the VM. Skip it for now, until we can
investigate what's going on. Leave it running on the public Testing Farm
to ensure it does not get broken further.
---
This test works fine in packit (public TF) and even [CentOS 9 Stream](https://gitlab.com/redhat/centos-stream/rpms/cockpit/-/merge_requests/19) (also public TF), but failed in [RHEL downstream packaging](https://src.osci.redhat.com/rpms/cockpit/pull-request/99)
> fmf: Skip TestPages.testBasic on RHEL 9.0

- test/common/run-tests
So that this event can be spotted easily when looking at logs.
> test: Be verbose when a test times out

- test/common/testlib.py
- test/verify/check-shell-host-switching
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
- test/verify/check-superuser
- test/verify/check-system-info
I'm trying to get to the bottom of the [TestMenu.testBasic failure](https://logs.cockpit-project.org/logs/pull-17043-20220224-094403-fd5a366e-rhel-8-6/log.html#138-2) which happens very often. It's our current [top flake](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7) -- it fails in [2 out of 3 cases on centos-8-stream](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7&test=test%2Fverify%2Fcheck-shell-menu+TestMenu.testBasic)!
[example 2](https://logs.cockpit-project.org/logs/pull-17043-20220224-094403-fd5a366e-centos-8-stream/log.html#138-2), [example 3](https://logs.cockpit-project.org/logs/pull-17059-20220228-131339-7b5d1203-centos-8-stream/log.html)
> TestMenu improvements

- test/verify/check-storage-basic
There is something spethial about this label, and browsers/harfbuzz just
keep rendering it with some slight noise. Ignore the column. The check
above already ensures that the label appears in the expected column.
---
I see [this failure](https://logs.cockpit-project.org/logs/pull-17063-20220301-052940-903213ae-fedora-35/log.html#154) time and again. It is perfectly reproducible locally for me, it fails in about half of the runs.
> test: Ignore "ext2 filesystem" label in TestStorageBasic pixel test

- test/common/chromium-cdp-driver.js
- test/common/firefox-cdp-driver.js
This was previously crashing with
```
File "/var/home/martin/upstream/c3/test/verify/check-shell-menu", line 75, in testBasic
b.reload()
File "/var/home/martin/upstream/c3/test/common/testlib.py", line 216, in reload
self.cdp.invoke("reloadPageAndWait", ignoreCache=ignore_cache)
File "/var/home/martin/upstream/c3/test/common/cdp.py", line 201, in invoke
if "result" in res:
TypeError: argument of type 'NoneType' is not iterable
```
as client.reloadPageAndWait() did not return anything, but our cdp.py
driver expect an object. We could make the driver tolerate that, but 
let's be strict here to avoid unexpected empty results from DevTools API 
calls.
> test: Fix TypeError crash with --trace

- .eslintignore
- test/common/chromium-cdp-driver.js
- test/common/firefox-cdp-driver.js
- test/common/test-functions.js
- test/common/testlib.py
Now it's almost clean:
```
❱❱❱ node_modules/.bin/eslint test/common/
/var/home/martin/upstream/c3/test/common/chromium-cdp-driver.js
221:72  error  Extra semicolon  semi
/var/home/martin/upstream/c3/test/common/firefox-cdp-driver.js
290:72  error  Extra semicolon  semi
✖ 2 problems (2 errors, 0 warnings)
2 errors and 0 warnings potentially fixable with the `--fix` option.
```
That remaining error is fixed in PR #17062, and I want to avoid colliding.
Once these two land, I'll add it to the `npm run eslint` rules in package.json. But that will also incur a node_modules/ refresh, so let's do that separately.
> Fix ESLint errors in test/common/

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- test/verify/check-metrics
Often some application maxes out and gets bottle-necked on a single CPU
core. On systems with a lot of CPUs this is not visible in the average
CPU progress though. It is visible in the tooltip, but first this is not
very discoverable, and second there is no indication for the user to
actually check this, as there might be dozens of idle cores next to the
single 100% one.
On multi-core systems, show a second CPU progress bar for the currently
busiest CPU core. This provides a good balance between pointing out the
problem and avoiding cluttered UI with showing all of them all the time
(which is not even all that interesting).
Also add an info icon to the "n CPUs" progress if there are multiple
cores, so that users get a hint that there is a tooltip.
On multi-core systems, the Metrics page …
> metrics: Show top CPU core usage

- test/verify/check-packagekit
- test/verify/check-selinux
- test/verify/check-system-realms
The difference between "command" and "script" arguments is marginal,
insignificant, and confusing. Let's just always use command, and drop
the script= argument from machine_core at some point.
> test: Drop Machine.execute() calls with script=

- pkg/static/login.js
Our browser is in Chinese. When a user login to cockpit-ws and uses a wrong password, it always displays "Permission denied", but the user actually wants to see the prompt text in Chinese.
I found the prompt text passed by a .c file is always fetched first in login.js, and the internationalized "Permission denied" is used only when the decoding fails.
When we can confirm that the returned text is "Permission denied", using internationalized text directly will meet the needs of users.
> The prompt text "Permission denied" should display internationalized text when the login failed

- test/common/firefox-cdp-driver.js
It is captured by the promise closures and if there ever are
overlapping command evaluations, each needs to keep their own number.
> test: Minimize scope of "seq" in firefox-cdp-driver.js

- pkg/metrics/metrics.scss
- test/verify/check-metrics
I adjusted the extra spacing between the CPU bars & load and then decided to adjust all the spacing in the current metrics area.
The extra spacing between the CPU bars & load _definitely_ needs to be adjusted, but the rest are mostly subjective changes and I'm still not fully sold on it. I'd like feedback.
Before:
After:
> metrics: Compress space a bit

- test/common/testlib.py
Some tests seem to leak an "admin" session which is not started by
Cockpit. This causes TestSession.testBasic to fail its initial "no
running admin sessions" check.
Clean up more thoroughly, and just always kill leftover admin sessions
also on OSes other than OSTree.
---
Fixes [this failure](https://logs.cockpit-project.org/logs/pull-17080-20220303-065131-4ef167f5-rhel-8-6/log.html#130-2)
> test: Kill admin sessions after nondestructive tests

- test/common/testlib.py
And not immediately when creating the Browser object.  This avoids
having a "self.cdp" that looks valid but can nevertheless not take
snapshots.
> test: Set browser window size when first loading a page

- src/pam-ssh-add/Makefile.am
- src/pam-ssh-add/pam-ssh-add.c
- src/pam-ssh-add/pam-ssh-add.h
- src/pam-ssh-add/test-ssh-add.c
This prevents us from recompiling libcockpit-common files as -fPIC.
> pam-ssh-add: drop two uses of libcockpit-common APIs

- test/verify/check-metrics
On some busy CI machines, 3 minutes is not enough for the load to drop
below 10, so wait a little more.
---
I've seen this [fail a lot](https://logs.cockpit-project.org/logs/pull-17087-20220307-095055-49c7fcef-centos-8-stream/log.html#51-2) today, and it's getting annoying. I can't reproduce the long wait times locally, it's usually done after ~ 1.5 minutes. But our CI machines are a lot more busy.
> test: Increase timeout for load to drop

- pkg/systemd/services/services.jsx
- test/verify/check-system-services
These happen after `systemctl daemon-reload` when changing unit files,
or when stopping transient units (systemd-run). Then the page would
crash with
Cannot read properties of undefined (reading 'Names')
Intercept this condition and show the "Unit not found" empty state.
---
This can be seen in current logs, e.g. [here](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-17082-20220303-091332-1070fb01-fedora-35/log) in `TestCurrentMetrics.testCPU`.
> systemd: Fix Service details crash on disappearing units

- packit.yaml
The list here contains very many dependencies that are either no longer
required by this project to build an SRPM (xmlto, selinux-policy, npm)
or never were (the unrelated "autogen" package).
automake pulls in autoconf as a hard dependency central to its
functionality, but gcc's dependency on make seems a bit less central, so
list it explicitly.
> packit.yaml: reduce the srpm depends

- test/verify.fmf
This causes the package to be (formally) upgraded in RHEL/CentOS 8:
there cockpit is already at version 264.1 (from the rhel-9.0 stable
branch), but our version on main is 264. Due to this it "upgrades" to an
actually older version, and does not test current changes.
---
This should fix [these failures](https://artifacts.dev.testing-farm.io/6db08ef5-15c4-4468-a98a-1b0c5aa465a9/) that we got for a few days (since https://github.com/cockpit-project/cockpit/releases/tag/264.1). You can see the bug in the log:
```
+ rpm -q cockpit-system
cockpit-system-264.1-1.el8.noarch
```
Same fix as in https://github.com/cockpit-project/cockpit-machines/pull/601 , specifically https://github.com/cockpit-project/cockpit-machines/commit/119d5b01bf5b1bf336683aaea50a8a7839aab4e7
> fmf: Drop cockpit packages from test dependencies

- test/README.md
We dropped this from bots' testmap a while ago.
---
This is a first test for the increased test parallelization in https://github.com/cockpit-project/cockpituous/pull/459
> test: Drop rhel-8-5 from documented supported OSes

- test/image-prepare
The `america` mirror has been down for several days, and makes all our
tests red. We have a reasonably current image now, so current packages
work. This could always happen again, but the proper way to fix this is
to provide a pre-cached build environment on our image.
---
See [log](https://logs.cockpit-project.org/logs/pull-17109-20220310-053130-b26e93bf-arch/log.html)
> test: Stop hardcoded Arch repository/mirror

- test/verify/check-pages
Only test locales on RHEL as our default image also does pixel tests
which take longer and the locale tests take up a significant time (~ 5 min.)
> test: drop DEFAULT_TEST_OS from locale tests

- src/bridge/cockpitpackages.c
- src/bridge/test-packages.c
- src/common/cockpitwebresponse.c
- src/common/cockpitwebresponse.h
- src/common/test-webresponse.c
- src/ws/cockpithandlers.c
- test/verify/check-apps
- test/verify/check-pages
This causes at least Chromium to not ever re-request the file from the
webserver, so that switching languages does not have any effect.
This is a very heavy hammer, as it generally disables caching po.js even
when not switching languages (the common case). So this should be
replaced with a better design at some point.
Note that caching is already disabled if any Cockpit package is present
in the user's home directory, so this is not something completely new.
Fixes #8160
----
Draft for now. I want a full test run, and possibly also use it to test #16930
> ws: Don't cache po.js files forever

- tools/cockpit.spec.in
We currently install a symlink for compatibility purposes with the
intention of only installing it on RHEL <= 8, but the way the test is
written:
```
%if 0%{?rhel} <= 8
```
We install it on RHEL 8 plus every non-RHEL system, because if %{rhel}
is not defined, then it's equivalent to `%if 0 <= 8`, which is true.
Since we don't care about RHEL 7 on this branch anymore, change the
comparison to exactly 8.
> cockpit.spec: fix RHEL 8 check

- Makefile.am
- tools/make-dist
- tools/webpack-jumpstart
This is silly, but I like it :)
```
FETCH    dist  [ref: tag sha-a5a0b87f6da0eb78c20319c8f449f2d1f3f6bf5a]
fatal: couldn't find remote ref refs/tags/sha-a5a0b87f6da0eb78c20319c8f449f2d1f3f6bf5a
AUTOGEN  configure, Makefile.in
CONFIG   tmp/build-dist/Makefile
WEBPACK  base1
WEBPACK  apps
WEBPACK  kdump
WEBPACK  metrics
WEBPACK  networkmanager
WEBPACK  packagekit
WEBPACK  playground
WEBPACK  selinux
WEBPACK  sosreport
WEBPACK  shell
WEBPACK  static
WEBPACK  storaged
WEBPACK  systemd
WEBPACK  tuned
WEBPACK  users
DIST     cockpit-264.112.g2e441db12.tar.xz
```
> make tools/make-dist (and therefore image-prepare) a bit prettier

- pkg/lib/cockpit-po-plugin.js
Each package already includes base1/po.js, so including the base1/
translations in each webpack is redundant.
Fixes #13906
> cockpit-po-plugin: stop including base1/ in all packages

- pkg/selinux/setroubleshoot.js
This page does too many re-renders while initializing the page. First it
adds item by item and re-render after each one. Then it loads details one
by one and re-renders after each item is updated. With this patch it
does render only once.
Now works nicely with https://github.com/cockpit-project/cockpit/pull/17094
> selinux: Don't re-render after each item

- pkg/packagekit/history.jsx
When new item would get added, the existing ones would get re-keyed.
Timestamp is unique enough.
> updates: Use better key

- pkg/apps/index.html
- pkg/kdump/index.html
- pkg/metrics/index.html
- pkg/networkmanager/firewall.html
- pkg/networkmanager/index.html
- pkg/packagekit/index.html
- pkg/playground/translate.html
- pkg/selinux/setroubleshoot.html
- pkg/shell/index.html
- pkg/sosreport/index.html
- pkg/storaged/index.html
- pkg/systemd/hwinfo.html
- pkg/systemd/index.html
- pkg/systemd/logs.html
- pkg/systemd/services.html
- pkg/systemd/terminal.html
- pkg/users/index.html
- test/verify/check-apps
A great number of our pages contain this:
```
<script type="text/javascript" src="../*/po.js"></script>
```
in their .html files.  The effect is that the page pulls in the
translations for every package that the bridge knows about, including
those that may have come from a different source package.
This was introduced in #5898, but unfortunately the PR is a bit thin on
rationale for why this was done.
Each page really only needs it own translations, plus the translations
for base1.  Adjust accordingly.
See also discussion in #13906.
- Blocked on fixing #8160
Fixes #13906
> pkg: stop including cross-package translations

- .gitignore
- package.json
- pkg/Makefile.am
- pkg/build
- src/bridge/cockpitpackages.c
- src/common/cockpitwebresponse.c
- src/common/cockpitwebresponse.h
- src/common/cockpitwebserver.c
- src/common/cockpitwebserver.h
- src/ws/test-server.c
- test/verify/check-shell-multi-machine
- tools/build-debian-copyright
- tools/check-dist
- tools/webpack-make
- webpack.config.js
Our build system does quite some tricks to compress our assets on the
fly during the `make install` phase.  Let's just do the compression as
part of the webpack.
> webpack: replace our gzip tricks with compression-webpack-plugin

- test/verify/check-reauthorize
Create a new user `barney` instead of our over-used `user` name.
Apparently some tests leave behind a valid sudo token in the right
circumstances, which makes the test unexpectedly get sudo privileges at
the beginning.
----
[example 1](https://logs.cockpit-project.org/logs/pull-17122-20220311-095551-5bc76534-fedora-coreos/log.html#76), [example 2](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-17122-20220311-095551-5bc76534-arch/log.html#76-2), [example 3](https://logs.cockpit-project.org/logs/pull-17122-20220311-131019-99f17013-rhel-8-6/log.html#76-2)
> test: Robustify TestReauthorize.testSudo

- test/verify/check-pages
- test/verify/check-reauthorize
- test/verify/check-shell-keys
- test/verify/check-shell-multi-machine-key
- test/verify/check-static-login
- test/verify/check-users
- test/verify/check-users-roles
Better fix for #17128, plus some cleanup as repentence.
This ought to fix [this failure](https://artifacts.dev.testing-farm.io/c2bbcad3-d46a-45b3-b476-f1581912439c/), and similar ones that we had before: [example 1](https://logs.cockpit-project.org/logs/pull-17122-20220311-095551-5bc76534-fedora-coreos/log.html#76), [example 2](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-17122-20220311-095551-5bc76534-arch/log.html#76-2), [example 3](https://logs.cockpit-project.org/logs/pull-17122-20220311-131019-99f17013-rhel-8-6/log.html#76-2)
> test: Clean up sudo privileges for test user in TestLogin.testNoAdminGroup, Drop alternative truths on user creation

- HACKING.md
We dropped the windows-10 image a year ago (bots commmit ea9543f8818c1).
----
This is legit, but also part of stress-testing CI with https://github.com/cockpit-project/cockpituous/pull/459
> HACKING: Drop obsolete Edge documentation

- doc/guide/cockpit-file.xml
> doc: Clarify unit of cockpit.file's max_read_size option

- test/run-verify-host-user.sh
- test/verify.fmf
packit tests currently take ~ 1.5 hours, which is way too long for our
"max. 1 hour" goal. Many of them are also not that useful in downstream
gating, as they only exercise cockpit-internal functionality -- it's
enough to do that in upstream CI where we have a lot more performance
(due to parallelization).
So trim the list to those tests which exercise external APIs, and are
thus useful for reverse dependency gating.
This also eliminates all the excludes. Still keep the mechanism in
place, as we are surely going to have more of them in the future
(especially for development releases).
Adjust the test timeout to 1 hour to match our goal.
---
See the [log of a current test](https://artifacts.dev.testing-farm.io/bca39cdc-ee44-40bd-96a4-8d6b3afcea1f//work-allJ0Tz_d/log.txt) for current …
> fmf: Trim tests to only exercise external APIs and be faster

- pkg/kdump/kdump-view.jsx
- test/verify/check-connection
- test/verify/check-pages
- test/verify/check-shell-multi-machine
`tesTroubleshooting` [example 1](https://logs.cockpit-project.org/logs/pull-17133-20220313-193136-26d7dc1a-rhel-9-0/log.html#147), [example 2](https://logs.cockpit-project.org/logs/pull-17132-20220313-191222-c6c81578-centos-8-stream/log.html#147)
[rpm-ostree failure](https://logs.cockpit-project.org/logs/pull-17133-20220313-193136-26d7dc1a-fedora-coreos/log.html#13)
> Test fixes, fix kdump crash

- pkg/lib/cockpit-components-privileged.jsx
- pkg/systemd/hwinfo.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/overview-cards/cryptoPolicies.jsx
- pkg/systemd/overview-cards/cryptoPolicies.scss
- pkg/systemd/overview-cards/healthCard.jsx
- pkg/systemd/overview-cards/profiles-menu-dialog-body.jsx
- pkg/tuned/change-profile.jsx
- pkg/tuned/dialog.jsx
- test/verify/check-system-info
This implements the ability to set and show crypto policies from within
the cockpit system overview. The current implementation is limited to
three hardcoded policies and `update-security-policies` does not have an
option to list all existing policies. When a crypto policy is applied
but a user chooses to not reboot a notification is shown in the health
card overview.
---
Cockpit now has basic support for displaying and changing a subset of crypto policies (default, future, legacy). The current configured crypto policy is shown in the `configuration` card.
Crypto policy changes can be applied directly or later, when later is selected the health card shows that a reboot is required to fully apply the changed crypto policy.
> systemd: Implement crypto policies support

- .gitignore
- Makefile.am
- tools/make-compile-commands
Add a new script, tools/make-compile-commands, which can generate the
compile_commands.json script used by many static analysis tools.
> tools: add tool to create compile_commands.json

- tools/release-guide
9efc2e016e7544adbb99415e7527117587d35c09 dropped the rule for making
dist/guide/html, which was a seemingly-unused alias for
dist/guide/html/index.html, but it was actually in use from
tools/release-guide.
Update tools/release-guide to just build dist/guide/html/index.html
directly.
> tools/release-guide: adjust to build system changes

- selinux/cockpit.te
- test/verify/check-static-login
pam_faillock tries to chown its state files to the target user. That's
legit, so allow this in our policy. Drop the test hack that we've been
dragging around for a while.
> selinux: Fix policy for pam_faillock

- pkg/shell/index.html
Revert the shell part of commit af5678b0be5. This broke translation of
menu entries for external pages like starter-kit.
----
See https://github.com/cockpit-project/starter-kit/pull/542#issuecomment-1070472816 for details. I am actually not sure how this worked for our internal pages -- do we somehow bundle all manifest translations into shell's po file?
I built this locally, installed it into a VM, and validated that this makes starter-kit menu translation and tests happy again. We obviously need a better solution for this, but for now let's fix the regression.
> shell: Re-include cross-package translations

- test/common/testlib.py
- test/verify/check-static-login
- test/verify/check-storage-nfs
- test/verify/check-superuser
- test/verify/check-users
So that the usual tearDown actions will run, such as journal checking
and code coverage processing.
- Requires https://github.com/cockpit-project/bots/pull/3097
- Requires https://github.com/cockpit-project/bots/pull/3098
> test: Call super().tearDown() as appropriate, test fixes

- .github/workflows/flatpak-test.yml
- containers/flatpak/test/test-ssh
> workflows: Fix race between flatpak tests

- test/common/testlib.py
This should fix failures like [this](https://logs.cockpit-project.org/logs/pull-16475-20220318-172950-02d7d82c-arch/log.html#265) and [this](https://logs.cockpit-project.org/logs/pull-16475-20220318-172950-02d7d82c-arch/log.html#265). I've also seen these countless times on c8s packit tests.
> tests: Stronger user/home directory cleanup between nondestructive tests

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.js
- pkg/networkmanager/bond.jsx
- pkg/networkmanager/bridge.jsx
- pkg/networkmanager/bridgeport.jsx
- pkg/networkmanager/dialogs-common.jsx
- pkg/networkmanager/ip-settings.jsx
- pkg/networkmanager/mac.jsx
- pkg/networkmanager/mtu.jsx
- pkg/networkmanager/team.jsx
- pkg/networkmanager/teamport.jsx
- pkg/networkmanager/vlan.jsx
- pkg/packagekit/kpatch.jsx
- pkg/storaged/crypto-tab.jsx
- pkg/storaged/fsys-tab.jsx
- pkg/storaged/nfs-details.jsx
- pkg/systemd/overview-cards/cryptoPolicies.jsx
- test/verify/check-kdump
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-checkpoints
- test/verify/check-networkmanager-mac
- test/verify/check-networkmanager-mtu
- test/verify/check-networkmanager-other
- test/verify/check-networkmanager-settings
- test/verify/check-networkmanager-team
- test/verify/check-networkmanager-vlan
- test/verify/check-packagekit
- test/verify/check-system-info
"Apply" buttons should be "Save".
Reason: "Save" always means "make the changes and close this dialog", whereas "Apply" sometimes does this too but more often means "Just make the changes now and keep the dialog open", famously in Windows, where most of our users are. Making the options "Save" and "Cancel" is much clearer.
> all: Rename occurances of "Apply" to "Save", fix racy TestNetworkingBasic pixel test

- pkg/kdump/kdump.js
- pkg/kdump/manifest.json
- pkg/metrics/metrics.jsx
- pkg/storaged/storage-controls.jsx
- pkg/storaged/utils.js
- pkg/systemd/services/service-details.jsx
- test/verify/check-kdump
- test/verify/check-metrics
- test/verify/check-shell-multi-machine
This prepares us to switch to base-10 units globally. See individual commits for details.
The main apparent change here is on the Metrics page. It used to look like this:
and now looks like this:
> review and clean up base-2 vs. base-10 unit inconsistencies

- test/common/testlib.py
- test/verify/check-users
This should fix situations where the directory is still busy, so that it
cannot be removed.
---
This should hopefully fix [this kind of failure](https://logs.cockpit-project.org/logs/pull-17143-20220321-062402-200e1966-arch/log.html#302-2). I also added a cleanup to check-users to make its tests "affected", so that we get a more thorough run.
> test: Retry unmounting user runtime directory

- test/verify/check-superuser
On Arch Linux a new sudo release lacks "this incident will be reported"
part.
> test: lax the sudo incident message

- pkg/lib/patternfly/patternfly-4-overrides.scss
Fix for https://github.com/cockpit-project/cockpit-podman/pull/943, where there's a PF Flex nested immediately inside another PF Flex.
> pf4: Properly handled nested PF Flex

- pkg/metrics/metrics.jsx
Without specifying an aria-label the console logs the following message
on every metrics update:
"One of aria-label or aria-labelledby properties should be passed when
using the progress component without a title"
> metrics: fix missing aria-label on progress element

- test/verify.fmf
- test/verify/check-system-journal
Now all Fedoras have a libreport version which only accepts an API key.
Revert the dynamic bits of commit 2b20d62b2e68, and only send the API
key.
> test: Simplify ABRT tests to only use the API key

- test/verify/check-system-realms
The package is finally available again, and got added to the image in [1].
Adjust the mock chrony.service hack a bit -- this bug is still around,
and I filed [2][3] about it. chrony.service is now masked by default, so
unmask it. And systemd does not accept symlinks to other units any more,
so replace that with a copy.
[1] https://github.com/cockpit-project/bots/pull/3132
[2] https://launchpad.net/bugs/1966181
[3] https://bugs.debian.org/1008195
- Requires https://github.com/cockpit-project/bots/pull/3139
> test: Enable FreeIPA tests on debian-testing

- containers/flatpak/cockpit-client.yml.in
Thanks to BigmenPixel! Originally proposed in
https://github.com/flathub/org.cockpit_project.CockpitClient/pull/6
> containers: Update flatpak to GNOME runtime version 42

- pkg/base1/cockpit.js
- pkg/base1/test-format.js
- pkg/storaged/utils.js
- pkg/systemd/hw-detect.js
- test/verify/check-metrics
- test/verify/check-storage-lvm2
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/storagelib.py
This makes more sense as a default now. Storage and network devices,
network transmission speeds etc. have all been base-10 for decades. The
only place which is inherently/physically base-2 is total RAM size, and
reserved kdump memory because that's just its API. But these special
cases have all been explicitly moved to format as base-2 recently.
https://bugzilla.redhat.com/show_bug.cgi?id=1970119
---
[pixel diff review](https://github.com/cockpit-project/pixel-test-reference/compare/ac6d9ad037ca8939d6795834abf82b35c4039836..fa3e8b66637ce0815d01915779b5906b98245f4d)
This is most apparent on the Metrics, Storage, and Networking pages:
All sizes and rates are now shown in decimal units, such as "MB" or "kB/s". Physical storage, network devices,
and network transmission speeds have all been …
> base1: Default to base-10 units in cockpit.format_bytes*()

- pkg/metrics/metrics.jsx
Immediately refresh the history metrics when the Metrics page becomes
visible. This gives a better UX than having to wait for the next
one-minute auto-refresh timer.
Conversely, don't reload/refresh the history metrics at all if the page
is not visible, as that's just a waste of CPU and bandwidth.
> metrics: History metrics react to visibility changes

- pkg/lib/machine-info.js
- test/verify/check-system-info
On this architecture, cpuinfo does not start processor blocks with
`processor:`, but it looks quite different. It also does not have a
per-cpu name, just a "vendor_id" in the header. Adjust the parsing
accordingly.
Test this with a real-life cpuinfo from a bug report.
https://bugzilla.redhat.com/show_bug.cgi?id=2069500
https://bugzilla.redhat.com/show_bug.cgi?id=2069552
> systemd: Parse /proc/cpuinfo on s390x

- src/bridge/cockpitpeer.c
- test/verify/check-superuser
- test/verify/check-system-shutdown-restart
This makes SSH logins use the same default as HTTP logins.  Running
"sudo" without explicit request from the user is problematic.
Fixes #17169
> bridge: Default "init-superuser" to "none"

- test/verify/check-system-realms
Do the necessary PAM setup so that two-factor authentication with
pam_sss works. This mirrors the configuration on Fedora: use pam_unix
for  local users, and pam_sss for non-local ones.
> test: Enable 2FA auth tests on Debian/Ubuntu

- test/common/cdp.py
On Arch Linux there is a seperate package for the firefox developer
edition which can be installed alongside firefox. Add this as useable
firefox binary.
> test: add firefox-developer to firefox binaries

- doc/guide/feature-pcp.xml
- pkg/metrics/index.html
- pkg/metrics/metrics.jsx
- pkg/systemd/overview-cards/usageCard.jsx
- test/verify/check-metrics
We got a report about a confusing mental disconnection between the Usage
card's link ("View details and history") and the metrics page title
("Performance Metrics"). There is no overlap, and additionally
"Performance profile" on the Overview refers to tuned (which is
completely different).
Rename both to "metrics and history" for consistency, and avoiding the
"performance" overlap. Also move to sentence case for the breadcrumb, to
comply to [1] and be consistent with e.g. the "Kernel crash dump" page
tile.
[1] https://www.patternfly.org/v4/ux-writing/capitalization/#capitalization-across-patternfly
---
[pixel diff link](https://github.com/cockpit-project/pixel-test-reference/compare/fa3e8b66637ce0815d01915779b5906b98245f4d..54401adf76a823142cd2a1061fcb2d545342051b)
> metrics: Consistent page title and Overview link

- .github/workflows/flatpak-test.yml
- .gitignore
- Makefile.am
- containers/flatpak/Makefile.am
- containers/flatpak/cockpit-client.yml.in
- containers/flatpak/prepare
- containers/flatpak/update-flathub
- src/client/Makefile.am
- src/client/add-metainfo-releases
- src/client/org.cockpit_project.CockpitClient.metainfo.xml
Create a tool to turn the point form notes in our tags into a proper set
of `<release/>` tags for metainfo and fill this information in when
building a tarball.
Install the metainfo if building with --enable-client.
This will simplify the process of releasing the flatpak.
> client: install metainfo file

- test/verify/check-static-login
Don't overwrite the standard pam_deny/pam_permit lines. They are there
for a very good reason, and we should keep the config changes to a
minimum.
In particular, `auth sufficient pam_faillock authsucc` does *not* fail
the login, so it needs the `pam_deny` fallback. Alternatively, the
module could be `required`, but let's stick to what the manpage says.
This resolves https://launchpad.net/bugs/1966416 and the corresponding
https://github.com/cockpit-project/bots/issues/3146
----
The previous PAM delta was:
```diff
--- /etc/pam.d/common-auth.orig 2022-03-25 10:41:29.088000000 +0000
+++ /etc/pam.d/common-auth 2022-03-25 10:48:48.913419254 +0000
@@ -17,11 +17,11 @@
auth [success=2 default=ignore] pam_unix.so nullok
auth [success=1 default=ignore] pam_sss.so use_first_pass
-auth requisite …
```
> test: Fix pam_faillock configuration in Debian/Ubuntu

- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-team
- test/verify/check-reauthorize
- test/verify/check-shell-multi-machine
In testlib reload(), logout() already calls
allow_restart_journal_messages().
> test: remove already handled restart messages

- test/verify/check-superuser
Since version of `sudo` 1.9.10-1 lecture is not enabled by default.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006273
> test: Don't expect lecture on debian-testing

- HACKING.md
Testing cockpit-bridge changes here locally did not work due to the
paths defaulting to /usr/local.
> HACKING: Document ./configure paths for cockpit-bridge

- test/common/pixel-tests
Useful for external projects, like anaconda-webui, where the cockpit
code is not in the root of the repo.
> tests: allow having the test/reference directory in another subdir

- pkg/systemd/services/timer-dialog-helpers.js
- pkg/systemd/services/timer-dialog.jsx
- test/verify/check-system-services
Fix the setOpen() call to actually happen *after* `create_timer()`
promise finishes and succeeds. Otherwise the dialog closes immediately.
Fix the promise chaining in create_timer_file() to actually return
errors from creating the .service file, by dropping the parallel catch
handler (which was just logging). Instead, chain it up to creating the
.timer file as well.
Fix chaining of the Reload call.
There is not a lot of opportunity for this to actually fail, but it can
happen on inaccessible or even non-existing directories. Do that in the
test.
> systemd: Show timer creation errors

- package.json
- webpack.config.js
This should get pulled in by PatternFly, and lets us avoid npm requiring
git.
> package.json: drop explicit Red Hat font depend

- pkg/systemd/overview-cards/cryptoPolicies.jsx
- pkg/systemd/overview-cards/profiles-menu-dialog-body.jsx
- test/verify/check-system-info
FIPS is a restricted set of cryptographic algorithms which requires a
special kernel boot parameter to be enabled. To enable FIPS mode on
RHEL/Fedora fips-mode-setup --enable has to be executed and the machine
succesfully rebooted.
> systemd: add FIPS as crypto policy

- test/common/run-tests
- test/run
Reporting/updating the status of naughties requires proper permissions
(e.g. a GitHub token to update comments of Cockpituous), which is not
something common outside of the cockpit project members. Also, local
runs ought to not change the status of naughties, as the runs may be
local testing.
Hence, slightly change the default behaviour of `run-tests` to not update
the status of naughties anymore; introduce a new `--track-naughties` that
restores the old behaviour, and which will need to be used in CI
invocations of `run-tests`.
Use `--track-naughties` in existing `run-tests` invocation, to retain the
old behaviour.
> test: add `--track-naughties` option for `run-tests`

- pkg/kdump/kdump-client.js
- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.scss
- pkg/lib/cockpit-components-dialog.jsx
- pkg/lib/service.js
- test/verify/check-kdump
This is often due to some mis-configuration, such as an NFS remote
directory not existing on the server. There is currently no better
machine-readable API for showing the root cause of the error, so
show the journal of the recently failed kdump.service run.
Use the same `<CodeBlockCode>` formatting and size as the realmd
overview card.
If the dialog is able to read the journal, then don't show the original
exception. That often reads "systemd job RestartUnit
["kdump.service","replace"] failed with result failed" which is not very
useful. Only show that if reading the journal failed (which "should not
happen™").
Assert the error formatting more precisely in the integration tests.
https://bugzilla.redhat.com/show_bug.cgi?id=2062297
----
Wide window, NFS error:
Narrow window, same NFS error: …
> kdump: Show current journal when (re)starting service fails

- test/verify/check-static-login
These should produce a proper error message. This was apparently broken
in the past: https://bugs.debian.org/859648
Skip this on OSTree, as root logins don't work there.
> test: Check pam_access denied logins

- pkg/shell/manifest.json
This is supposed to happen automatically, but due to bug [1] it did not.
[1] https://github.com/cockpit-project/bots/pull/3226
Fixes #17233
> shell: Add entry for Georgian

- pkg/packagekit/updates.jsx
When the packagekit service has not refreshed yet PackageKit returns
G_MAXUINT which on Linux corresponds to 2^32-1 and shows as last checked
136 years ago.
PackageKit code https://github.com/PackageKit/PackageKit/blob/dadea5f987d7f86baff9abf42f9462d7f76a0e0e/src/pk-transaction-db.c#L219
> packagekit: handle timeSinceRefresh unitialized

- .github/deploy-keys.sh
- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
Instead of running the npm-update workflow in the `self` environment and    
using SSH to push, push via HTTPS (with the `contents: write` permission    
now granted).    
This frees us to use the `node-cache` environment, which lets use use    
the `DEPLOY_KEY` secret from there with `tools/node-modules push`.    
Eventually we may want to create an environment with both deploy keys    
inside of it so that we can force-push the commit after we create the    
PR, in order to trigger the testing workflows to run.  Since we're not    
actually doing this force-push at the moment anyway, let's take this    
approach as the easier one.
Take a look at the branch here: 
https://github.com/cockpit-project/cockpit/commits/npm-update-workflow
It has the changes from this PR, plus a bogus commit …
> workflows/npm-update(-pf).yml: change the environment

- .github/workflows/reposchutz.yml
Commit 0ce651fc7a dropped all write permissions. But deleting the label
requires writing to the issues API.
----
See [current workflow failure](https://github.com/cockpit-project/cockpit/runs/6001588717?check_suite_focus=true). *This* PR will fail also in any case, as reposchutz runs from main.
I temporarily removed reposchutz as a required check.
> workflows: Restore issues write permissions to reposchutz

- .github/deploy-keys.sh
- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
Do an extra force-push via SSH after opening the PR to trigger the tests to run.
See a test workflow run here:
https://github.com/cockpit-project/cockpit/actions/runs/2160854103
which opened this PR here:
https://github.com/cockpit-project/cockpit/pull/17252
and which reposchutz was able to successfully reproduce `npm install` for here:
https://github.com/cockpit-project/cockpit/runs/6006502062?check_suite_focus=true
> Fully automatic npm-update

- test/verify/check-storage-nfs
When the testNfsClient flakes and a nfs share is mounted to /mnt/test
the cleanup first restores /etc/exports and then restarts nfs-server.
This causes issues with umount'ing the share and gives permission errors
when trying to remove the share. Making sure the share is umount'ed and
directory removed before restoring /etc/exports and restarting
nfs-server.
> test: make testNfsClient clean up properly

- test/README.md
- test/verify/check-connection
- test/verify/check-static-login
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/check-system-info
- test/verify/check-system-journal
Also drop unused rhel-9-0-distropkg skips. We never set that up and
don't plan to, as there is just a single cockpit srpm in RHEL 9.
> test: Adjust special cases for rhel-9-1

- test/verify/check-shell-multi-machine
FIPS is tested by the crypto-policy checks in TestSystemInfo. This check
just boots two more VMs in vain.
> test: Drop redundant TestMultiMachine.testFIPS

- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
In case no update happened, we really ought to be skipping the
force-push.  Check the current branch name, and don't do a force push if
it's main.
> workflows/npm-update{,-pf}.yml: don't force push main

- .github/workflows/npm-update-pf.yml
- .github/workflows/npm-update.yml
- tools/node-modules
Drop our internal copy of the code for launching npm inside of the
container and use the version of it that now lives in the bots.
> tools/node-modules: use bots/npm install

- .github/workflows/reposchutz.yml
We use `--not` with `git log` to find the merge base of the base branch
with the proposed branch, which doesn't work if we fetched them shallow.
I had thought that `git fetch` would fix this, but it turns out not to
sufficiently de-shallow the already-checked-out target branch.
Just do `fetch-depth: 0` from the start to avoid this non-sense.
I didn't test this, but it certainly won't make anything *worse* :)
> reposchutz: use fetch-depth: 0

- pkg/systemd/overview-cards/insights.jsx
- test/verify/check-system-info
- test/verify/files/mock-insights
The mock-insights server and the client config for it have been
updated from here:
https://github.com/candlepin/subscription-manager/pull/2998
https://github.com/candlepin/subscription-manager/pull/2996
The /var/lib/insights directory needs to be read as superuser, so the
InsightsStatus component needs to re-open its file watches
accordingly.
> systemd: Updates for the Insights status

- configure.ac
This makes sure we get the executable with the correct `--host` prefix,
allowing us to successfully cross-compile.  Without this, `AR` gets
hard-coded to `ar`.
> configure.ac: use AC_CHECK_TOOL to find ar

- pkg/packagekit/kpatch.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
A new option to only install kpatches.
---
It is now possible to only install kpatch updates. This is useful at times when a reboot or service restarts are not acceptable, to at least fix kernel vulnerabilities.
> Install kpatches only

- pkg/systemd/kernelopt.sh
- test/verify/check-system-info
Removing a kernel leaves behind its BLS entry [1], and `kernel-install remove`
leaves GRUB's default kernel setting to the just removed kernel [2].
Both bugs together cause a boot failure when removing old kernels [3].
Work around that by restoring grub's defaults after the fake kernel
install/removal.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2078379
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2078359
[3] https://github.com/cockpit-project/bots/pull/3293
- Requires https://github.com/cockpit-project/bots/pull/3296
> nosmt code and test cleanup, work around kernel-install bugs

- test/common/cdp.py
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-kdump
- test/verify/check-metrics
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-checkpoints
- test/verify/check-networkmanager-unmanaged
- test/verify/check-packagekit
- test/verify/check-pages
- test/verify/check-selinux
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine
- test/verify/check-sosreport
- test/verify/check-static-login
- test/verify/check-storage-format
- test/verify/check-storage-ignored
- test/verify/check-storage-luks
- test/verify/check-storage-mdraid
- test/verify/check-storage-resize
- test/verify/check-storage-scaling
- test/verify/check-storage-stratis
- test/verify/check-system-realms
- test/verify/check-system-services
- test/verify/check-system-shutdown-restart
- test/verify/check-users
- test/verify/netlib.py
- test/verify/storagelib.py
One full minute is way too long for our UI to react for our UI
standards. In general, our UI should react very fast even on loaded CI
machines. The main exception are waiting for OS APIs that genuinely take
a lot of time (such as formatting a drive or joining a FreeIPA domain),
but these should (and often already do) have an explicit wait_timeout().
This also makes development of tests less annoying, and speeds up
known-failing tests (with naughty matching).
Lower the default timeout to 15s, drop the redundant low timeout in
TestConnection, and add explicit timeouts for legitimately long-running
steps. This makes it easy for us to grep the tests for things that are
slow, and worth looking into.
The biggest offender is the Services page, which is known to be dog
slow. Until we fix this …
> test: Lower default CDP timeout to 15s

- pkg/systemd/logs.jsx
- pkg/systemd/logs.scss
Name of this class has been changed in the recent PF update so it
stopped working. Using utility prevents such breakage in the future.
Fixes #17257
> logs: Use utility for toolbar wrapping

- pkg/lib/cockpit.js
- pkg/shell/base_index.js
> shell: Don't show "Oops" for silent errors

- pkg/packagekit/updates.jsx
Order the install updates buttons based on amount of updates with
kpatches being the fewest.
> packagekit: order kpatches before security updates

- .github/workflows/release.yml
This is a shared repository, and e.g. cockpit-machines is using that as
well now. We want to tag c-machines releases in this as well. To avoid
version number collisions, prefix the tag with the project name.
> workflows: Prefix node-cache tags with project name

- pkg/systemd/overview.jsx
If `Shutdown` is much longer than `Reboot` (e.g. in Japanese) then the
`Shutdown` string overflows out of the page.
@garrett this is just very simple approach. Do you think we should do something different here, or is this good enough?
Before:
Now:
> overview: Right alight reboot dropdown

- test/verify/check-storage-hidden
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
- test/verify/check-storage-mounting
- test/verify/storagelib.py
- tools/cockpit.spec.in
- tools/debian/control
UDisks2 used to return from methods calls like AddConfigurationItem
before the requested changes have been reflected in the Configuration
properties.  This has been fixed in 2.9.0.
> test: Assume that fstab and crypttab updates are synchronous now

- src/tls/server.c
- src/tls/server.h
- src/tls/test-server.c
We've run into issues where port 9123 isn't available on the builder
we're using, so let's use a dynamically allocated port instead.
We accomplish this by passing 0 as the port number (which already
worked) but we need to have a way to figure out what port we actually
used.  We add a minimal accessor to the server code to let us get the
listener socket fd, which we can call getsockname() on to determine to
where we ought to connect.
> tls: avoid static port in test-tls-server

- pkg/systemd/hw-detect.js
- pkg/systemd/hwinfo.jsx
This PR improves the hardware information shown on ARM devices such as the Raspberry Pi and shows why there is no memory information shown for normal users.
> Hardware information improvements

- src/bridge/cockpitpackages.c
If we can't find a file called "po.js", return an empty document rather
than an error.  This matches what happens in the globbing case, and
avoids filling the debugging console with messages about incorrect
content type when requesting po.js in English (due to our HTML 404
page).
> bridge: Don't 404 on "po.js"

- tools/cockpit.spec.in
> cockpit.spec: drop RHEL build hanging workarounds

- src/client/cockpit-client
Do a conditional import of libhandy, and if it's available, use it to
automatically set our colour scheme to match the system setting.
Notes:
I followed the implementation suggestions here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference
We can't use the "GTK4+ libadwaita" route because WebKit isn't available for GTK4 yet: https://bugs.webkit.org/show_bug.cgi?id=210100
I've checked this, and it works from inside of the flatpak container as well.
I've also checked using the `--external-ws` commandline option to point the browser to external sites that support dark mode, and the setting is wired through automatically.
For example
```
src/client/cockpit-client --external-ws https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
```
That suggests …
> client: enable dark mode if libhandy is available

- pkg/shell/topnav.jsx
We already pick these items from manifest and translate them. We just
never told Cockpit to show them in the target language.
> shell: Translate documentation links

- packit.yaml
- pkg/systemd/overview-cards/shutdownStatus.jsx
These should be treated as advisory, but they will help us to spot
issues like https://bugzilla.redhat.com/show_bug.cgi?id=2081039
----
systemd 251 started to guard this as a privileged operation with polkit [1].
So call this as root if possible.
This is an incomplete fix: We should not even show the cancel action if
the session is not root and not allowed via a polkit rule, but that is
more intrusive -- let's fix the exploding gating test first.
https://bugzilla.redhat.com/show_bug.cgi?id=2081039
[1] https://github.com/systemd/systemd/commit/ec14fba91c94f38f3
> packit: Enable tests on Fedora Rawhide, systemd: Cancel shutdown as root

- pkg/lib/_global-variables.scss
Contents of `@patternfly/patternfly/base/patternfly-variables.scss` currently includes two imports:
```scss
@import "../sass-utilities/all";
@import "variables";
```
The `sass-utilties/all` import does not render into CSS; it only includes SASS-specific contents (that is: variables and mixins). However, the `variables` import _does_ render to CSS, which means that we wind up with CSS-rendered outputs of PatternFly variables every time our `_global-variables.scss` file is included anywhere... and this file of ours is included in `page.scss`, so this is a problem with every single page.
Changing the import in our `_global-variables.scss` to only use the sass-utilities file means that we're not accidentally redefining the CSS variables on the page. (The `@import "variables";` is included …
> sass: Reduce duplication in variables import

- tools/make-compile-commands
We try hard to avoid the "except in certain circumstances" exception to
`make --dry-run` that the manpage talks about, making a renamed copy of
the Makefile to avoid it being regenerated, but we forgot that these
exceptions also apply to regenerating included Makefiles.
In particular, our current approach causes the "dummy" .deps/*.Po files
to be generated as a side-effect of running tools/make-compile-commands.
If that process races with the actual compilation (as it often does), it
can lead to incorrect results.
Let's up our game a bit and also try to remove "include" lines from the
Makefile that we're processing.
Removing these files from consideration (and sometimes rebuilding) also
reduces the time to create `compile-commands.json` from just under 1s to
just under 100ms.
> make-compile-commands: avoid including makefiles

- pkg/metrics/metrics.jsx
- pkg/metrics/metrics.scss
- test/verify/check-metrics
The originating event (such as starting a service) may have happened
earlier than in the current minute. So show a "View detailed logs"
action link for this case as well, but show an increased time range (15
minutes before the event to 1 minute after it) and verbosity (debug
instead of info).
Fixes #16496
> metrics: Show logs link for events without journal messages

- pkg/metrics/metrics.jsx
- test/verify/check-embed
- test/verify/check-examples
- test/verify/check-metrics
Current metrics cards for CPU and memory now show [Podman](https://podman.io/) containers, in addition to systemd services.
> metrics: show podman container cpu usage

- pkg/shell/superuser.jsx
- pkg/systemd/superuser-alert.jsx
- test/verify/check-superuser
- test/verify/check-system-info
Now they use function components and the UnlockDialog maintains its
own state.
Most importantly, the new SuperuserButton is no longer tied to the
life-cycle of the dialogs and the SuperuserAlert component and its
parents do not need to do anything special to keep it alive.
> shell: Rewrite superuser dialogs 

- pkg/metrics/metrics.jsx
This splits out the dialog state from the button state, and avoids the
slightly awkward delayed handleSave invocation in case some packages
need to be installed.
This then allows us to use Dialogs.show.
> metrics: Refactor PCPConfig dialog

- pkg/storaged/client.js
- pkg/storaged/content-views.jsx
- pkg/storaged/details.jsx
- pkg/storaged/format-dialog.jsx
- pkg/storaged/lvol-tabs.jsx
- pkg/storaged/pvol-tabs.jsx
- pkg/storaged/utils.js
- pkg/storaged/vdo-details.jsx
- pkg/storaged/vdos-panel.jsx
- pkg/storaged/warnings.jsx
- test/verify/check-storage-vdo
RHEL 9 dropped the legacy API and the `vdo` command line tool. This
caused the "Create LV" dialog to falsely claim that the "vdo" package
needs to be installed, even though it was already -- and then fail the
creation as the `vdo` program was not available.
This was hidden by the obsolete test skips from the times when RHEL 9
images really didn't have a kmod-kvdo yet, but that has existed for a
long time already.
The `vdo` package is only necessary for creating a new volume (the rest
is built into the kernel and LVM itself), so define a new
`lvm_create_vdo` feature which checks the availability of `vdoformat`.
Check this in the "Create LV" dialog as well.
> storaged: Fix VDO for RHEL 9

- test/README.md
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-packages
- test/verify/check-static-login
- test/verify/check-storage-lvm2
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-services
- test/verify/storagelib.py
This temporarily makes the base-2 vs. base-10 special cases even more
ugly. But we'll be able to drop all of that soon after landing the first
update in RHEL 8.7, and dropping support for testing on 8.6.
> test: Adjust for rhel-8-7

- pkg/shell/superuser.jsx
Sudo sometimes takes a bit to terminate, but having the dialog stay
open is confusing.  People might think that they have clicked the
"Authenticate" button by accident, maybe.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2073263
> shell: Immediately close superuser dialog when cancelling

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
- test/common/testlib.py
- test/verify/check-packagekit
- test/verify/check-sosreport
- test/verify/check-system-services
- test/verify/packagelib.py
Cockpit allows for the creation of simple systemd system timers without
the option for deletion. This commit implements deletion for all timers
created in /etc/systemd/system/ by cockpit or by hand. The unit which is
triggered by the timer is also removed. Masked timers are not allowed to
be deleted as these are system timers in /etc/systemd/system symlinked
to /dev/null.
---
User created systemd timers in /etc/systemd/system can now be removed in cockpit.
> systemd: allow removal of cockpit created timers

- pkg/lib/patternfly/patternfly-4-overrides.scss
Fix for https://github.com/cockpit-project/cockpit-podman/pull/897#issuecomment-1127637202 across Cockpit. We don't hit it often, but we do hit it more when more tabs are added.
> pf4: Wrap tabs when there's not enough space

- test/verify/check-static-login
On Fedora Rawhide, the message now looks like this:
cockpit-session: Failed to map certificate to user: [org.freedesktop.DBus.Error.NameHasNoOwner] Could not activate remote peer: activation request failed: unit is masked.
Relax the pattern to accept this as well.
---
Seen in #17384 in the failed [rawhide test](https://artifacts.dev.testing-farm.io/6edab079-87c6-42dc-9aff-4d74f2353e43/).
> test: Relax expected D-Bus error message

- .github/workflows/release.yml
- tools/cockpituous-release
As a follow-up to #17337, let's get rid of our SSH key release secret as well. See the individual commits for details.
- Builds on top of PR #17337 
- Requires new deploy key: https://github.com/cockpit-project/bots/pull/3410
>  Disable release-dockerhub, use deploy key for release website update

- test/git-hook-pre-push
This reverts a tiny piece of d126de6a642f1ddac1fedd31adb5268c1f561a67.
This script is typically run by git from a symlink located in the
~/.git/hooks/ directory, which results in `$0` pointing to that link, and
not to the original file.  In order to make sure we resolve the path
relative to the location of the original file, go back to using
realpath, as before.
> git-hook-pre-push: bring back realpath -m

- .eslintignore
- test/common/sizzle.js
- test/common/testlib.py
This symlink always points to the same place (inside `node_modules/`), so we may as well just resolve that location directly.
This avoids all kinds of problems we've seen, such as `tar -h` failing on this file, or https://github.com/packit/packit/issues/1560
Fixes #17370
> test: drop sizzle.js symlink

- test/verify/check-storage-lvm2
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/storagelib.py
rhel-8-6 is no longer supported, and rhel-8-7-distropkg now uses
base-10 units.
> test: Clean up rhel-8-6 and rhel-8-7-distropkg for storage tests

- test/verify/check-system-info
The time doesn't matter when there is no scheduled shutdown, and it
used to be zero but seems to have changed to 18446744073709551615 with
systemd 251.
> test: Only assert type of cancelled shutdown

- test/verify/check-metrics
The Fedora coreos image now has a busybox container, so these tests can
be enabled.
> test: enable podman cpu metric tests for coreos

- pkg/static/login.css
> login: Make fonts path relative, so prefixes work

- containers/ws/install.sh
- containers/ws/label-run
This prepares the ws container for being able to run unprivileged.
Without /host, the branding will be completely broken, and trying to
run it with a customized /etc/os-release volume (aka bind mount) will
fail.
Only do the linking if /etc/os-release is not already mounted as a
volume.
---
The full support for unprivileged ws will come in a follow-up PR. But this particular bit is awkward to work around especially for our offline "update existing container" image-prepare, so I'd like to land this first, refresh the official container, and refresh our fedora-coreos image with that (although that step is blocked by https://github.com/cockpit-project/bots/pull/3437)
> containers/ws: Move os-release symlinking into run script

- pkg/shell/hosts.jsx
In e45d47f0efe1f17 editing hosts was allowed for non admin privileges
which was the last user of this.state.privileged.
> shell: drop privileged state

- tools/git-utils.sh
Trying to call `git init` with the GIT_WORK_TREE variable set gives the
following error:
fatal: GIT_WORK_TREE (or --work-tree=<directory>) not allowed without specifying GIT_DIR (or --git-dir=<directory>)
So call init_cache before we set the variables to make sure the
directory already exists.
> git-utils.sh: pre-init the cache directory for untar

- .github/workflows/release.yml
- .gitignore
- Makefile.am
- autogen.sh
- configure.ac
- tools/make-dist
Currently, we choose the version number that we use at the time that ./autogen.sh is first run.  That means that if you configure your tree and hack on it for a while, making commits as you go, the overly-specific version number will soon be out of date.  This version number is the number used when building tarballs for testing.  Even switching to old branches on previous versions can result in the version number not being updated.
Let's move to automake's suggested approach[1] to dynamic versioning by introducing a `version.m4` file.  We write that file from two places:
- `./autogen.sh` writes an approximate version number (the last release) appended by +git (eg. "270+git")
- from `make dist` we write the value we find in `$(VERSION)` and call autoreconf to update the configure script …
> build: change approach to versioning

- test/run
Now that they use run-tests, they should also use --track-naughties.
> test: Use --track-naughties also for container scenarios

- test/verify/check-connection
- test/verify/check-users
- tools/cockpit.spec.in
Avoid some "Recommends", as they are discouraged:
- Lift subscription-manager-cockpit to Requires, it's an essential part
on RHEL.
- Require sudo, that's our main UI for getting administrative
privileges.
- Demote NetworkManager-team to Suggests.
Shuffle the Requires:, Provides:, and Suggests: lines a bit to keep the
same kind together in a single block.
https://bugzilla.redhat.com/show_bug.cgi?id=2093231
---
This also fixes an [unexpected error message](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17426-20220603-183752-19c4b4ea-fedora-35/log.html#304), which seems really unlucky, but let's just deal with it.
> tools: Adjust RHEL dependencies

- pkg/networkmanager/firewall.jsx
- test/verify/check-networkmanager-firewall
Zone name may be defined so we should use that when possible.
Before:
After:
> firewall: Prefer zone name when given

- pkg/storaged/manifest.json
- pkg/storaged/utils.js
- test/verify/check-storage-vdo
That string hacking was only working in locales with `.` as decimal
separator, but e.g. not German or Portugese.
Use the new precision option from commit 083f889c0a47 (released in
Cockpit 266). Adjust the VDO tests accordingly.
> storaged: Set cockpit.format_bytes() precision instead of string hacking

- pkg/systemd/services/service.jsx
- test/verify/check-system-services
Fixes issue on service details page where 'Services' link doesn't lead back
to the services overview page when service Id containts special characters.
> systemd: Fix link in BreadcrumbItem

- pkg/lib/cockpit.js
- pkg/static/login.js
10 years ago in Firefox 11 MozWebSocket was replaced by Websocket.
https://bugzilla.mozilla.org/show_bug.cgi?id=695635
> static: lib: drop MozWebSocket fallback

- containers/ws/Dockerfile
- containers/ws/README.md
- containers/ws/default-bastion.conf
- containers/ws/label-run
- test/fedora-coreos.install
- test/verify/check-ws-bastion
This provides the basic functionality of the ./containers/bastion demo
container. You can already customize cockpit.conf and the branding, but
it does not support SSH key logins yet. This will be added in a
follow-up.
The [cockpit/ws container](https://quay.io/repository/cockpit/ws) can now also be run in unprivileged mode. It then presents an unbranded login page. The user always has to specify a host name, and it connects to that host with SSH.
This mode is suitable for deploying to e.g. Kubernetes or similar environments where you cannot have or want privileged containers. In this "bastion host mode", you can get a Cockpit for servers in your data center without opening an extra port for cockpit-ws on them.
For now this only supports password authentication. Support for SSH key …
> containers/ws: Support running as unprivileged user

- Makefile.am
- src/client/add-metainfo-releases
I wanted to get all of this stuff out of the process of building a tarball, but
- managing this externally is (really) hard.  At some point you find yourself writing XSL and ask yourself "...what am I doing?".
- ximion/appstream#354 will hopefully provide a proper fix for this eventually
- the current approach is working well enough
Instead of trying to create some new thing which we'll just have to replace a little bit later anyway, let's just make the current stuff work.
This fixes `make distcheck`.
> hack metainfo releases a bit more

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.js
- test/verify/check-kdump
Disable the service switch and show a tooltip when the kernel's command
line lacks the crashkernel option. Without this change a user can try to
enable the service which will instantly fail without an indication that
crashkernel has to be configured upfront.
> kdump: show tooltip when crashkernel is not configured

- package.json
- test/browser/run-test.sh
This release contains a fix for nodejs to prefer ipv4 resolving which
is needed as Firefox the CDP runs only on ipv4 on Fedora rawhide on
packit.
> package.json: Update chrome-remote-interface

- pkg/packagekit/updates.jsx
I am not sure how this could happen but it seems to happen on Ubuntu 22.04.
Fixes #17405
> updates: Do not oops on non found update

- .github/workflows/unit-tests-refresh.yml
- .github/workflows/unit-tests.yml
- containers/unit-tests/build
Commit b746f5aef3671446 changed the unit-tests workflow, but not the
-refresh one.
---
See last night's [failure](https://github.com/cockpit-project/cockpit/actions/runs/2525468187)
[run against this branch](https://github.com/cockpit-project/cockpit/actions/runs/2526902198)
> workflows: Adjust unit-tests-refresh to recent container changes

- pkg/static/login.js
Since Internet Explorer is no longer support and Microsoft Edge does
support document.baseUri this can be dropped.
> static: drop Internet Explorer workaround for baseUri

- pkg/shell/topnav.jsx
The "proxy" property of the SuperuserIndicator was not updated in time
with a change to the "host" property since "componentDidUpdate" runs
after render.  Let's just keep the proxy up-to-date in "render"
itself.
Fixes #17467
> shell: Fix rendering of access level indicator

- test/README.md
- test/run
These were dropped in commit d81735ca198 and
https://github.com/cockpit-project/bots/pull/3526
> test: Drop obsolete container test documentation and scenario

- pkg/systemd/services/service-details.jsx
- pkg/systemd/services/service-details.scss
- pkg/systemd/services/service.jsx
- pkg/systemd/services/services-list.jsx
- pkg/systemd/services/services.jsx
- pkg/systemd/services/services.scss
- test/verify/check-system-services
Fixes: #16780
This uses localStorage to store paths of every pinned unit.
There is no way to tell appart unit aliases because stored objects
are identical so as a side effect all aliases refering to the same
path end up being pinned.
Pinning unit:
Unpinning unit:
Pinned unit is on the top of the list:
Failed units are above pinned units:
Tooltip:
> services: Add pinning services

- test/verify/check-system-realms
This package was again dropped.
This reverts commit ef04f8b9398dcac6f0c63e459cc0eb84859459b9.
> test: Disable FreeIPA tests on debian-testing

- pkg/static/login.css
- pkg/static/login.html
- pkg/static/login.js
The login page now has a dark mode which changes with your system's dark settings. Most desktops have a setting for this in "appearance" area in system settings, including GNOME, KDE, Windows, macOS, Android, and iOS/iPadOS.
Here's [Cockpit Client](https://flathub.org/apps/details/org.cockpit_project.CockpitClient), which [also recently got dark mode a few releases ago](https://cockpit-project.org/blog/cockpit-269.html), in the standard light mode:
And after switching to dark settings, it looks like this:
We’re still working on adding dark mode for Cockpit once you've logged in, in the near future.
> Login: Dark mode

- test/common/tap-cdp
This used to be handled by the tap driver, but since we don't use that
anymore, we need to add a check for it here.
Fortunately, we didn't break anything in the meantime.
> tap-cdp: return non-zero if we see 'not ok' lines

- test/browser/run-test.sh
Commit 121e770ab9a regressed running tests from tarballs: As there is no
.git directory, tools/node_modules fails to run. So add a check for .git.
We can also simplify this: Since commit c00710475274a, our tarballs
include the NPM modules necessary for testing, so we never need to run
npm.
----
See [this failure](https://artifacts.dev.testing-farm.io/03a6bbff-9b47-4212-a38d-7842673bf82e/) from https://src.fedoraproject.org/rpms/cockpit/pull-request/72
> fmf: Fix node_modules/ handling for tarballs

- pkg/lib/page.scss
Both transform and opacity adjustment change the stacking order. This causes issues like popups displaying under the rows during animation.
Fixes #17482
> lib/page: Simplify new row animation

- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-team
Fedora and RHEL 9 phase out /etc/sysconfig/network-scripts support, see
/etc/sysconfig/network-scripts/readme-ifcfg-rh.txt.  Writing this file
is between that and NetworkManager, cockpit does not trigger or
influence it. That check already had some non-trivial skip conditions,
and now starts to fail on RHEL 9.1 as well now.
---
This broke downstream gating. If you are in the RH network, the [log is here](http://artifacts.osci.redhat.com/testing-farm/5d3f0d0f-e191-4588-93f4-ce10f7f436c3/work-upstreammF6XmB/plans/upstream/execute/data/test/browser/output.txt).
> test: Drop brittle sysconfig name check in NetworkManager tests

- test/common/testlib.py
`reference-image` is used only for pixel tests, and currently also only
in some cases (e.g. only for chrom* browsers and non-devel builds).
Simplify its usage a bit: read it only when needed, and consider its
lack non-fatal (situation handled already).
> test: make the `reference-image` file optional

- containers/ws/install.sh
Commit 76da7b7fc29 broke building the official container against COPR:
`dnf --installroot` only considers the repos in the target tree, not on
the host. So create cockpit.repo in /build.
---
I noticed that when I [synced the recent changes](https://github.com/cockpit-project/cockpit-container/commit/ff6df9118190b4aca436591d37fdea274c38c58e) to cockpit-container, and bumped the release to 272. I [added the fix](https://github.com/cockpit-project/cockpit-container/commit/92a0ec596c10ed186c1ce1b139a3b404c2e409ef)  to cockpit-containers directly, built the container, validated it, and pushed it to quay.
I didn't notice that in my earlier testing as I was building the container against local rpms. Sorry for the blunder!
> containers/ws: Fix pulling in packages from COPR

- containers/ws/label-install
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-bridge
- test/verify/check-networkmanager-team
- test/verify/check-ws-bastion
This changed on the most recent Fedora CoreOS refresh [1] and thus breaks the install script.
[1] https://github.com/cockpit-project/bots/pull/3562
After this lands, refresh the official container, then refresh the image.
> containers/ws: Accept $container == podman, test ws install script, pycodestyle fix

- test/common/lcov.py
- test/common/run-tests
- test/common/testlib.py
This also moves all the coverage related code into lcov.py.
This is a continuation of #17475 that just makes comments and doesn't request changes.  Having cockpituous request changes might block merging in annoying ways.  Maybe we want that eventually, but not yet.
>  test: Post review comments for uncovered code additions

- pkg/packagekit/updates.jsx
You're not supposed to have two primary buttons for the same related
section.  panel was missing the case when the reboot button was shown
not because of packages requesting a reboot, but because of services
that need a manual restart.
Fixes #17514
> packagekit: Fix "Restart services" button priority

- pkg/packagekit/updates.jsx
- test/verify/check-packagekit
So far, watchTransaction() only updated the state on "Package" signals.
When reattaching to an already running transaction (on page reload, or
after relogin), this kept the "Initializing.." empty state until the
next Package signal arrived.
We can do better: The transaction object has `LastPackage` and `Status`
properties which we can read to get the data for the package which is
currently being updated. So factor out the code for reading the D-Bus
object properties and computing the state, and call it for both the
"Package" signal and the state of the transaction when attaching to it.
This will also make it easier for us to work on the "Applying updates"
page, as our tests create packages which hang forever -- and thus we
couldn't use page reloads to check the effect of code changes. …
> packagekit: Show current package when reattaching to running update

- containers/ws/README.md
- containers/ws/cockpit-auth-ssh-key
- containers/ws/label-run
- test/verify/check-ws-bastion
Load a provided SSH key into ssh-agent, and let cockpit-ssh use it from
there. This is the same approach that we use with "regular" cockpit and
connecting to remote hosts in the shell.
This drops the restriction that keys must be in the old RSA PEM format. SSH has
moved to the proprietary "OpenSSH" format a few years ago, but openssl (or
anything else other than SSH itself) cannot decrypt these any more.
Unfortunately ssh-add does not allow reading the password from stdin, so
construct and use an askpass agent (similar to Client).
Restrict the lifetime of keys in the agent to 30 seconds. That gives the login
process enough time to connect, but avoids keeping the unencrypted key in
memory indefinitely.
----
- Builds on top of #17504
[Cockpit …
> containers/ws: Support all OpenSSH key types

- test/browser/run-test.sh
Introduced in commit 70de12208c4
----
Should fix [this failure](https://artifacts.dev.testing-farm.io/8c35e8cb-73e0-4894-b642-96f153b322bc/), seen in PR #17544.
> fmf: Fix syntax error in node_modules checkout

- pkg/storaged/manifest.json
- test/verify/check-storage-nfs
- test/verify/packagelib.py
Make it possible to install optional NFS/Stratis support using
PackageKit.
> storaged: add Arch Linux nfs-utils/stratisd packages

- .github/workflows/unit-tests-refresh.yml
- .github/workflows/unit-tests.yml
- Makefile.am
- src/ws/test-server.c
Refreshing our unit-tests container has recently [started to fail](https://github.com/cockpit-project/cockpit/actions/runs/2646144001) both on the scheduled runs on main, and in PR #17549. See [this comment](https://github.com/cockpit-project/cockpit/pull/17549#issuecomment-1182741018) for details of the debugging.
I [triggered a run](https://github.com/cockpit-project/cockpit/actions/runs/2661693623) against this branch, but with an extra commit that avoids pushing the container to the registry -- for now I just want to see if the tests work. And they did! :partying_face:
> Fix unit-test container refresh, fix valgrind invocation for HTML tests

- src/client/cockpit-client
Current RHEL 9 has libhandy 1.2.3, which does not yet have the
`StyleManager` API. This causes client to crash with an AttributeError
since commit 9d9b1f8e5c04.
https://bugzilla.redhat.com/show_bug.cgi?id=2106096
---
See bz for how I tested this.
> client: Fix crash on absent Handy.StyleManager

- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
- test/verify/check-packagekit
This allows users to start a manual update and queue a reboot without
having to babysit the progress.
Rework the progress page layout a bit:
- Use a Grid layout, so that the update log has the same alignment than
the progress bar.
- Stop centering the "Cancel" button, which was a bit dubious wrt. PF
recommendations anyway. Show it to the right of the progress bar
instead.
- Hide the cancel button instead of disabling it, once cancellation is
not allowed any more.
- Rename "Update log" to "View update log" to clarify what the action
means.
- Increase the spinner size, to make it easier to see.
https://bugzilla.redhat.com/show_bug.cgi?id=2056786
-----
- Builds on top of PR #17517
The update progress page offers you to reboot the machine after applying updates succeeded. If the machine can …
> packagekit: Add "Reboot after completion" switch to update progress page

- test/verify/check-packagekit
On latest Debian testing there are even more messages like
```
Metadata for module libsystemd.so.0 owned by FDO found: {
"type" : "deb",
"os" : "debian",
"name" : "systemd",
"architecture" : "amd64",
"version" : "251.2-7",
"debugInfoUrl" : "https://debuginfod.debian.net"
}
```
Just stop pretending that we can capture them all, and accept all
journal messages for this test.
---
I've seen two instances of [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17500-20220713-122423-1ee1f24b-debian-testing/log.html#306-1) recently.
> test: Robustify testPackageKitCrash expected messages

- test/verify/check-storage-stratis
For stratis if you have multiple filesystems we show the space one
filesystem takes up relative to the other. As this uses our own written
usagebar let's make sure PF doesn't break it on updates.
> test: add pixel tests for our custom progress implementation

- src/ws/test-channelresponse.c
glib 2.73.2 dropped the global SIGCHLD handler [1]. That causes the 
killed bridge process in test_resource_failure() to end up as a zombie,
so that `kill (pid, 0)` succeeds forever and the test hangs. So with
that version we need to wait() the bridge process ourself.
However, the previous comment is still true for older glib versions:
wait()ing the process there still does interfere with the global
handler:
GLib-WARNING: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid().
To avoid the (fatal) warning, conditionalize the waiting on new glib
versions only.
Fixes #17563
[1] https://gitlab.gnome.org/GNOME/glib/-/commit/f615eef4bafaa2f
> ws: Fix test-channelresponse for glib dropping global child watch

- .github/workflows/build-ws-container.yml
Building container images on quay.io has been broken for more than half
a year now, so stop holding our breath (and doing builds manually).
Instead, let's build the image on GitHub and push it to quay.io.
This also gets rid of the
https://github.com/cockpit-project/cockpit-container/ repository. That
was used as a quay.io build trigger, but it needed manual syncing
whenever we changed anything in the container definition (and we often
forgot to do that).
The internal CI secrets repo was updated to create a "quay.io"
environment on cockpit, similar to the one in cockpituous.
Start with a manual trigger: For now this should be run:
- When we do an upstream release, and something significant changed in
ws; this needs to wait until our cockpit-preview COPR finished
building
- When we changed …
> workflows: Add build-ws-container

- test/verify/check-kdump
- test/verify/check-metrics
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-mac
- test/verify/check-networkmanager-mtu
- test/verify/check-networkmanager-settings
- test/verify/check-networkmanager-unmanaged
- test/verify/check-selinux
Cockpit bots deprecated machine_core.constants import in b9d9b67e.
> test: stop using deprecated machine_core import

- pkg/sosreport/index.jsx
- test/verify/check-sosreport
Using "-vvv" will write DEBUG messages to stdout which will all get
trasmitted to the browser and then mostly ignored there.  With "-v",
DEBUG messages will still end up in the archive, but stdout will only
receive WARNING messages, as normal.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2107667
> sosreport: Use "-v" instead of "-vvv" for verbose logging

- .github/workflows/unit-tests.yml
For make check the base1 webpack is only required, this speeds up our
tests significantly.
> .github: always try to jumpstart node_modules

- test/common/testlib.py
PF4's "Drawer" component has a bug (or hack) to use an infinite
animation. This breaks Anaconda's pixel tests, as the waiting never
completes.
Add a flag to disable the waiting.
----
I'm pushing this into origin, so that the Anaconda team can easily test it.
> test: Add assert_pixels() API for disabling animation waiting

- test/common/run-tests
Due to sorting our tests, the expensive ones like TestMultiMachine tend
to run in parallel, which causes the number of parallel VMs to be up to
three times as high as `$TEST_JOBS`. This leads to overly long VM boot
times and timeouts [1].
Improve this by scheduling fewer of them in parallel. Introduce a notion
of "cost" to a Test object and measure it in terms of how may VMs it
will boot -- each additional VM costs an extra ½ TEST_JOBS.
Schedule tests until their total cost (instead of just their number)
hits `$TEST_JOBS`.
[1] https://github.com/cockpit-project/cockpituous/issues/506
---
I tested this locally with enabling debug loggging (the commented out basicConfig). It now behaves as expected, it lets all other tests finish first:
```
❱❱❱ test/common/run-tests -j3 --test-dir …
```
> test: Improve run-tests scheduling of multi-provision tests

- test/verify/check-examples
- webpack.config.js
Fedora-36/CentOS/RHEL 9 switched to OpenSSL 3, which does not support
the `md4` hash any more. webpack hardcodes that in a lot of places, so
monkey-patch `crypto.createHash()` to substitute sha256 for md4.
Hack to work around https://github.com/webpack/webpack/issues/13572
Cherry-picked from https://github.com/cockpit-project/starter-kit/commit/3220617fec508
This is solved in current webpack 5 versions, but we don't want to
update this old stable branch to that.
---
Seen in https://github.com/cockpit-project/bots/pull/3637 , fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3637-20220720-230754-25322310-rhel-7-9-cockpit-project-cockpit-rhel-7.9/log.html)
> [r79] Fix build in Fedora 36 tasks container

- packit.yaml
tmt got fixed to be able to run the tests from the dist-git tarball
instead of checking it out from git, and this PR enabled that:
https://src.fedoraproject.org/rpms/cockpit/pull-request/76
> packit: Drop obsolete FMF plan bumping

- pkg/systemd/services/services.jsx
A D-Bus signal subscription will get all signals from all services,
not just from the service that the client was created for.
> systemd: Don't call updateTime() for every property change ever

- tools/debian/control
- tools/debian/copyright.template
- tools/debian/source/lintian-overrides
See recent [lintian report](https://lintian.debian.org/sources/cockpit). Missing dependency spotted in issue #17587
> Some Debian packaging updates

- src/bridge/cockpitpeer.c
main() sets $USER and asserts that it succeeds, so we can rely on $USER
here.
This quiesces Coverity:
dereference: Dereferencing a pointer that might be "NULL" "user" when calling "cockpit_hex_encode".
> bridge: Assert valid user in cockpit_peer_handle()

- test/README.md
This is for validating the new tasks container in https://github.com/cockpit-project/cockpituous/pull/510
> tasks: Update README for default OS change to Fedora 36

- src/common/cockpithex.c
Dear Maintainer,
There is a coding err at ```src/common/cockpithex.c:cockpit_hex_decode```, which leads a over-size-malloc issue.
Could U please review this PR?
> cmmon: Fix memory allocation in cockpit_hex_decode()

- test/common/run-tests
- test/run
We are still getting a lot of VM boot failures on PSI, so let's reduce
the amount of parallel VMs more.
---
See e.g. [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17594-20220726-100137-69b3f677-ubuntu-stable/log.html) or [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17594-20220726-130123-69b3f677-ubuntu-stable/log.html) run (I cancelled the latter)
> test: Increase scheduling cost of provisioned VMs, speed up build

- pkg/systemd/services/timer-dialog.jsx
When using `menuAppendTo` the default state is open. That is annoying
as since you open the dialog or switch to any option that contains
TimePicker the menu is opened by default.
> systemd: Control isOpen in TimePicker

- pkg/systemd/services/timer-dialog.jsx
Change order to prefer the more-commonly-used and default choice "at specific time" instead of "after system boot".
As spotted in #17592.
> services: Swap timer order: specific & after boot

- src/bridge/cockpitcpusamples.c
- test/verify/check-metrics
Sensors are detected once and are stored in a static list.
This also adds `atk0110` sensor mentioned in #17580
> Metrics: Improve CPU temperature sensors detection

- pkg/lib/cockpit-components-table.scss
We already include the breakpoints via "global-variables" so due to the
nature of SASS we end up with duplicated --pf-global--font-path
declaration in :root {}. Before this commit:
$ grep -cr "\-\-pf-global--font-path" dist/networkmanager/*.css
dist/networkmanager/firewall.css:2
After:
$ grep -cr "\-\-pf-global--font-path" dist/networkmanager/*.css
dist/networkmanager/firewall.css:1
See also for more context:
https://github.com/cockpit-project/cockpit/issues/17556#issuecomment-1184518556
Let's hope the pixel tests agree this is a good idea.
> lib: drop duplicate patternfly-variables include

- pkg/networkmanager/networking.scss
Networking uses Cockpit's ListingTable, which already has these imports.
> networking: Remove redundant imports

- test/common/run-tests
Commit 49a7122df introduced a regression when the number of parallel
jobs was smaller than the cost of a test: These tests would never be
scheduled, and at the end the scheduler failed the "parallel_tests
should be empty" assertion.
Fix that by also scheduling the next parallel test if the number of
running tests is empty. That will cause the costly ones to run serially,
as intended.
---
Tested with
```
test/common/run-tests -j2 --test-dir test/verify/ -v TestNondestructiveExample TestExample TestMultiMachineAdd.testBasic
```
which reproduces @ptoscano 's [reported crash/problem](https://pastebin.com/Pyr1jz5K), and confirms the fix.
> test: Fix run-tests scheduling with little or no parallelism

- pkg/metrics/metrics.scss
- pkg/shell/nav.scss
- pkg/shell/shell.scss
- pkg/systemd/logs.scss
- pkg/systemd/terminal.scss
- pkg/users/users.scss
I removed as many `@import`s as I could and re-added the imports where things were broken.
I'm adding this as a draft to see what the tests (especially pixel tests) do.
> css: Remove unused PF component imports

- pkg/lib/cockpit-components-file-autocomplete.jsx
Allows setting initial value in FileAutoComplete component. This use case
is needed in c-podman to prefill ImageRunModal when editing/recreating containers.
> lib: allow setting initial value in FileAutoComplete

- doc/protocol.md
- pkg/base1/test-http.js
- src/ws/test-server.c
Noticed while I was working on the pybridge http channel. The JS unit tests don't run in our VMs, thus no-test.
> http-stream2 unit tests and doc improvements

- src/client/cockpit-client
Fedora 37 dropped webkit2gtk3 from their default desktop installation,
and only ships with webkit2gtk4.1 now. Confusingly, this is *not* GTK4,
but the GTK3 binding linked against libsoup 3.
-----
@M4rtinK, this should fix your woes. Quite possibly it'll also fix https://github.com/cockpit-project/bots/pull/3696
I tested that on a current Fedora rawhide workstation live system. Both with the default webkit2gtk4.1, and after installing webkit2gtk3 and damaging the gtk4.1 import code path.
> client: Support WebKit 4.1 API

- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-system-info
- test/verify/packagelib.py
- test/verify/storagelib.py
This actually spotted two bugs. Blocks https://github.com/cockpit-project/bots/pull/3706
- https://github.com/cockpit-project/cockpit/pull/17625
> tests: Fix for Machine.execute() enabling `set -e`

- test/verify/check-storage-mounting
- test/verify/check-storage-nfs
The tables can change layout completely "at random".  When the width
of a PID changes, for example, the Command column might wrap
differently and increase the height of the whole dialog.
> storage: Remove some pixel tests for complex tables

- pkg/kdump/config-client.js
There is no remove, and the intention is to close the watch channel.
> kdump: Use close with cockpit.file, not remove

- test/verify/check-metrics
- test/verify/check-packagekit
- test/verify/check-pages
Fixes [these failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3706-20220808-163657-549403cf-rhel-8-7-cockpit-project-cockpit/log.html) from https://github.com/cockpit-project/bots/pull/3706
> more test fixes for Machine.execute() with set -e by default

- pkg/lib/patternfly/patternfly-4-overrides.scss
Breadcrumb links should have the correct pointing hand cursor.
PatternFly requires a "to" attribute for an actual link, but we use some
funky onClick JS for navigating and override it with a className.
Therefore, instead of having a proper `<a href="...">` being rendered, we need
to override the link. This is a problem with a (correct) assumption in PF
and our (incorrect) way of not using links (but using JavaScript) for
linking.
Nevertheless, Cockpit needs to be adapted for this to work as expected.
---
Screenshot of the issue:
> pf: Fix breadcrumb link cursor

- doc/man/cockpit.conf.xml
- pkg/lib/cockpit.js
- test/verify/check-connection
We eventually want to support running cockpit-ws behind https://www.3scale.net/.
This requires two different API paths: `/api/<service>-<port>/` for HTTP
traffic, and `/wss/<service>-<port>/` for websocket connections.
cockpit.js needs to know which URL/path to contact for the websocket, so this
cannot be done with path rewriting on the server side only, or even with
multiple UrlRoot= values.
Thus introduce support for reading a `websocket-root` meta tag from the 
webserver, similar to the existing `url-root` one. Nothing sets that tag 
right now, as we are still not entirely sure how we want to configure
this. See https://github.com/cockpit-project/cockpit/pull/17473 how all 
of this fits together.
This is the only part required on the client side (which is much harder
to change and get …
> cockpit.js: Support different URL root for the websocket

- configure.ac
- doc/guide/packages.xml
- pkg/lib/manifest2po
- pkg/shell/manifest.json
- pkg/shell/superuser.jsx
- src/bridge/cockpitrouter.c
- src/session/session-utils.h
- src/session/session.c
- test/verify/check-superuser
- test/verify/check-system-terminal
Demo: https://www.youtube.com/watch?v=ET5w39M3HIw
------
Cockpit always had the ability to run arbitrary programs to gain administrative access, by adding them to a package manifest.  However, the UI would always use "sudo". Now the UI lets you select which program to use when multiple are defined in the manifests.
By default, Cockpit will still only use "sudo", so unless you actually add more programs via a manifest, there will be no visible change in the UI.
> shell: Support for alternatives to sudo

- test/verify/check-networkmanager-basic
We have an issue with the IPv6 address sometimes wrapping which seems to
happen more frequently with changes in the latest `fedora-36` image to
how the IPv6 address is chosen.
Disable this test on mobile, for now.
> test: disable NetworkManager pixel test on mobile

- test/browser/run-test.sh
Fedora-37 has been branched off
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/OLJ7BBFJEW4SDNQ2J2VTT5R4K6UV4ZQO/
Noticed this by looking at my PR and noticing that rawhide executes kpatch tests which it should not as Fedora does not have kpatch.
https://artifacts.dev.testing-farm.io/7f66bfc0-e1e4-4930-b6bb-6198dbebe35a/
> test: rawhide is now Fedora-38

- test/browser/run-test.sh
Use the same skip/naughties as Fedora-36 for Fedora-37.
Maybe we should stop doing this and explicitly add fedora-37 to our naughties/skips for packit and rawhide.
I think we might also want to stop using `fedora-development` as it's an alias to rawhide OR the beta when available which means your PR will randomly start failing as Fedora-37 is added.
> test: make Fedora-37 Fedora-36

- tools/cockpit.spec
When we moved to install branding with relative symlinks in
ad74e9ba14c9748abcfcd9b5310738796172d7ef, this piece of code
is no longer applicable as it relies on absolute paths.
> tools: Drop SUSE section for removing 3rd party branding

- test/verify/check-storage-format
- test/verify/check-storage-resize
Newer versions of xfsprogs (5.19) refuse to create XFS filesystems on
devices that are smaller than 300MB.
See cockpit-project/bots#3769.
> test: change minimum filesystem sizes to 320MB

- pkg/kdump/index.html
Introduced in af5678b0be55474ccf523 as a typo most likely.
This breaks the new Python bridge with KeyError 'base', do we need to fix it in there?
The old bridge handles it here:
```
src/bridge/cockpitpackages.c:  if (!cockpit_json_get_string (manifest, "base", NULL, &base))
```
> kdump: use correct base for translations

- src/cockpit/packages.py
When loading from a Python zipfile we used to get str instances, but
when loading from the file system we get Path like objects. This breaks
negotiate_file as it will never find files from your system as it
compares a string to a Path like object.
> python: fix loading pages from /usr and XDG_*

- test/verify/check-pages
fedora-coreos recently changed the "real name" of the root user to
"Super User".  Allow that as a valid value.
> test: allow root user to be named "Super User"

- test/verify/check-packagekit
The default of 120 seconds seems to be too short now.
https://cockpit-logs.us-east-1.linodeobjects.com/pull-17668-20220829-074839-431e6065-rhel-8-7/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-17668-20220829-074839-431e6065-rhel-8-7-distropkg/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-17668-20220829-074839-431e6065-rhel-9-1/log.html
> test: Wait a bit longer for Candlepin to start

- test/verify/check-connection
Our incoming debian-testing update has a new pam (1.4.0-13 -> 1.5.2-2)
which now supports checking the permissions of the motd files, and thus
properly elides displaying the message about how to enable cockpit for
non-administrator users.
> test: assume motd permissions work on debian-testing

- pkg/storaged/fsys-panel.jsx
- test/verify/check-storage-ignored
The label was lost in #16518 (cce897d5395b6dbface8444b35435a196507b0af),
for no apparent reason.  Let's put it back.
> storage: Show block label in filesystem panel

- HACKING.md
Add newline between special path of cockpit-ws on Debiand and disable SELinux as these two steps should be visibly separated.
> HACKING.md fix formatting

- packit.yaml
- test/README.md
- test/verify/check-packagekit
- test/verify/check-static-login
- test/verify/check-system-info
As usual, keep supporting the two most recent branched versions.
Also drop Rawhide from our cockpit-preview COPR build: We directly upload new releases to Rawhide anyway, so this is redundant.
Adjust test special cases.
This also needs some naughties first, I found [at least one new SELinux regression](https://bugzilla.redhat.com/show_bug.cgi?id=2083900) locally already.
- https://github.com/cockpit-project/bots/pull/3797
- https://github.com/cockpit-project/bots/pull/3801
- https://github.com/cockpit-project/bots/pull/3804
> packit: Drop Fedora 35, add Fedora 37; fix tests for fedora-37

- test/common/netlib.py
- test/common/packagelib.py
- test/common/testlib.py
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-examples
- test/verify/check-kdump
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-firewall
- test/verify/check-packagekit
- test/verify/check-pages
- test/verify/check-selinux
- test/verify/check-shell-keys
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-sosreport
- test/verify/check-static-login
- test/verify/check-storage-iscsi
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-nfs
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/check-system-info
- test/verify/check-system-realms
- test/verify/check-system-services
- test/verify/check-testlib
- test/verify/check-ws-bastion
Most of the `a && b` constructs were wrong for our intent, as it will
silently succeed if `a` fails, and never run `b`. This can often cause
follow-up failures which are harder to investigate.
This was solved in in https://github.com/cockpit-project/bots/pull/3706
by running all Machine.execute() commands with `set -e`.
Replace `&&` with `;` where appropriate. There are still four places in
opportunistic cleanup commands which currently use `&&` in a broken way;
but keep them until we can get an agreement how to fix them.
Use Machine.write() to write files, instead of echo commands.
Drop the now redundant `set -e` from check-connection.
---
Similar to https://github.com/cockpit-project/cockpit-machines/pull/793 and https://github.com/cockpit-project/cockpit-podman/pull/1069
> test: Robustify executed commands

- src/cockpit/channel.py
If an AsyncChannel gets `close` from the other side without having first
received `done` then the EOF will never get delivered to the reader in
the `run()` function.
Add an extra EOF on `close`, as well.
> python: send EOF on AsyncChannel close

- pkg/lib/cockpit-components-password.jsx
This allows a user of PasswordFormFields to set the password value
from the outside, instead of the value being just initialized and stored
internally inside the component.
The motivation behind this change can be found at https://github.com/cockpit-project/cockpit-machines/pull/803 , which is blocked on this PR.
> lib: Allow setting initial password for PasswordFormFields

- test/common/packagelib.py
- test/common/testlib.py
- test/verify/check-apps
- test/verify/check-connection
- test/verify/check-examples
- test/verify/check-metrics
- test/verify/check-packages
- test/verify/check-pages
- test/verify/check-selinux
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
- test/verify/check-sosreport
- test/verify/check-static-login
- test/verify/check-storage-ignored
- test/verify/check-system-realms
Since https://github.com/cockpit-project/bots/commit/e84a589781a3fa ,
SSHConnection.write() creates the target directory by itself.
---
Follow-ups from https://github.com/cockpit-project/cockpit/pull/17645#pullrequestreview-1092152421
> test: Drop obsolete mkdir -p calls

- doc/protocol.md
- pkg/base1/test-echo.js
- pkg/base1/test-http.js
- src/ws/test-server.c
Splitting this out from PR #17631 as the /mock/info stuff might be useful for @jelly and @mvollmer to adjust their parts of the unit test for py vs. C bridge differences.
> Various http stream test improvements, doc update

- pkg/kdump/config-client-suse.js
- pkg/kdump/kdump-client.js
- pkg/kdump/kdump-view.jsx
- test/verify/check-kdump
If parsing /etc/kdump.conf doesn't return usable settings, try
/etc/sysconfig/kdump which is used by SUSE distributions as the main
kdump config.
The file is in dotenv format and currently only KDUMP_SAVEDIR,
KDUMP_DUMPFORMAT and KDUMP_SSH_IDENTITY entries are used by Cockpit.
SUSE supports additional dump target types (ftp, sftp, cifs) but doesn't
support others (raw, mount). The target dialog currently supports the
common types (nfs, ssh, local).
> kdump: Add SUSE kdump config support

- tools/webpack-make
- webpack.config.js
`exclude:` matches on the complete absolute path. This broke when
cockpit was checked out into a directory (e.g. a branch worktree) that
started with "test-".
To avoid that, tighten the regular expression to only match on test-*.js
files.
Fixes #16829
> webpack: Fix regexp for unit test files

- pkg/networkmanager/interfaces.js
The NetworkManager daemon now has a standard ObjectManager at
/org/freedesktop.  By using this as the "path_namespace" in our D-Bus
watch, cockpit-bridge will recognize it immediately.
Also, register the "notify" handler before starting the watch so as to
not miss any events.
Previously, The Network page was asking cockpit-bridge to emulate an
object manager at "/" by introspecting the whole tree.  This is less
efficient, and also seems to trigger bugs in cockpit-bridge if a real
ObjectManager is detected while that introspection is going on.
Even if there is no real ObjectManager at /org/freedesktop, this
change is still correct.  In that case, cockpit-bridge will continue
to emulate one via introspection.
> networkmanager: Watch the D-Bus ObjectManager

- pkg/networkmanager/network-interface.jsx
Interestingly networkmanager's dbus API does not set a DeviceType for a
WireGuard device but sets the Driver property.
Know it shows like:
> networkmanager: show Wireguard device type

- test/common/netlib.py
They are not supposed to resolve DNS queries and thus don't need any
upstream servers.  Also, NetworkManager puts the interfaces added via
add_veth into /etc/resolv.conf on Debian, and if there are two of
these, they will forward queries to each other endlessly.  This seems
to slow down the test enough to sometimes cause timeouts elsewhere.
> test: Don't let our dnsmasq instances read /etc/resolv.conf

- .github/workflows/unit-tests.yml
- containers/unit-tests/setup.sh
`adduser` recently changed its behaviour for system users, not to create
the home directory.  We expect the home directory to be created, though
(since we build in it), so explicitly specify `--create-home`.
> unit-tests: explicitly create the home directory

- pkg/base1/test-echo.js
- pkg/base1/test-http.js
- pkg/lib/qunit-tests.js
- src/Makefile.am
- src/cockpit/channels/__init__.py
- src/cockpit/channels/http.py
This is sufficient to pass pkg/base1/test-http.js, but is still missing a lot:
*  [aiohttp](https://github.com/aio-libs/aiohttp/) would be nice, but it's an external module and we only want to use included batteries
* we might be able to poll() the `response.fileno()` for at least asynchronously reading the response data, but that still leaves the connection handshake and sending the request; all of that can block as well
* we might spawn `curl`, but that's ugly and not always installed either
* :heavy_check_mark: our best bet might be to run the whole thing in a thread
These require the hack from PR #17599 to run the py bridge interactively.
Interleaved spawn and http channel with C bridge:
```
(printf '\n{ "command": "open", "channel": "h", "payload": "http-stream2", "address": …
```
> pybridge: Add http-stream2 channel

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
So far we have only respected packagekit.exists() in the empty state
on-demand installation, but it was missing in the metrics config dialog.
Pass it on to that component as well, and disable the pmlogger switch if
packagekit is not available and pmlogger.service does not already exist.
Fixes #17693
> metrics: Disable on-demand install without PackageKit in PCP config dialog

- pkg/networkmanager/networking.scss
- pkg/shell/credentials.scss
As spotted at https://github.com/cockpit-project/cockpit/pull/17657#pullrequestreview-1086711740, we shouldn't use data-label in CSS for selectors. Doing so ties it to the language specified.
> Don't use `data-label` for selectors in CSS

- tools/git-utils.sh
Since grep 3.8, there is now a warning about egrep being deprecated and users should switch to `grep -E`.
See https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html
> tools: replace usage of deprecated egrep

- pkg/static/login.js
Rejecting CSS.supports(":is()") is the correct thing to do per https://github.com/w3c/csswg-drafts/issues/7280
Fixes #17724.
> login: Use valid selectors when testing for :is() / :where() support.

- src/ws/test-channelresponse.c
Commit 0c7793da868cc adjusted the "wait for killed bridge" behaviour for glib 2.73.2: that dropped the global GChildWatch waiting in favor of pidfds. But on mips{,64}el, glib now went back to the old behaviour, so adjust the condition.
See https://buildd.debian.org/status/fetch.php?pkg=cockpit&arch=mipsel&ver=276-1&stamp=1662541707&file=log
----
I can't say I like this hack, but I don't really have a good idea how to predict the behaviour otherwise.
I tested this on a Debian mips porter box, and it makes the test happy. I keep the build environment around for a day or so.
See https://buildd.debian.org/status/package.php?p=cockpit for an overview of all build logs (current and older)
> ws: Go back to assuming GChildWatch on mips in test-channelresponse

- pkg/static/login.html
- pkg/static/login.js
Some browsers get confused when there is some type="password" field before the username field. Re-ordering mutually exclusive parts of the login page should not have any visible impact but fixes automatic filling of credentials saved in browser's password manager.
The password field was also explicitly cleared in all auth scenarios while it should be only for conversations.
> login: Fix username/password autofill

- test/verify/check-subscriptions
In recent rhel-7-9 image refresh[1], it seems candlepin began to timeout:
+ curl -s https://services.cockpit.lan:8443/candlepin --verbose
*   Trying 10.111.112.100...
[timeout]
[1] https://github.com/cockpit-project/bots/pull/3866
> Give more time for candlepin

- src/Makefile.am
- src/cockpit/channel.py
Otherwise we never get the 'pong' that will allow us to write more data.
> python: Send expected 'ping' during flow control

- pkg/base1/test-spawn-proc.js
- src/cockpit/channels/stream.py
> python: Handle early errors during cockpit.spawn
