test/check-session

Don't just check it immediately.
Fixes #1709

test: Wait for a change in session state.

---

test/images/fedora-25
test/verify/naughty-fedora-25/4978-docker-selinux-broken-1
test/verify/naughty-fedora-25/4978-docker-selinux-broken-10
test/verify/naughty-fedora-25/4978-docker-selinux-broken-11
test/verify/naughty-fedora-25/4978-docker-selinux-broken-12
test/verify/naughty-fedora-25/4978-docker-selinux-broken-2
test/verify/naughty-fedora-25/4978-docker-selinux-broken-3
test/verify/naughty-fedora-25/4978-docker-selinux-broken-4
test/verify/naughty-fedora-25/4978-docker-selinux-broken-5
test/verify/naughty-fedora-25/4978-docker-selinux-broken-6
test/verify/naughty-fedora-25/4978-docker-selinux-broken-7
test/verify/naughty-fedora-25/4978-docker-selinux-broken-8
test/verify/naughty-fedora-25/4978-docker-selinux-broken-9

Image refresh for fedora-25

---

test/verify/check-ostree
test/verify/check-subscriptions

test: Don't test OSTree or Subscriptions on fedora-testing

---

test/verify/naughty-centos-7/5331-storaged-crash-poll-with-variant-4

test: Add another CentOS storaged crash known issue file

---

doc/guide/cockpit-dbus.xml

This makes it much clearer what they are.

guide: Add parentheses to function names in DBus documentation

---

Makefile.am
src/base1/Makefile.am
src/common/Makefile-common.am
tools/webpack-make

Like this:
```    
$ make docker
$ make clean-docker
```

Add targets for building and cleaning a specific package

---

HACKING.md

Major new changes should have video recorded of them before
the pull request is merged. This adds a description of how to
do that.

HACKING: Add doc about recording video of changes

---

src/bridge/cockpitdbuscache.c

bridge: Fix cockpitdbuscache barrier ordering

---

pkg/shell/shell.css

shell: added overflow-y, allowing sidebar to scroll

---

pkg/machines/actions.es6
pkg/machines/config.es6
pkg/machines/helpers.es6
pkg/machines/hostvmslist.jsx
pkg/machines/libvirt.es6
pkg/machines/reducers.es6
pkg/machines/services.es6

Libvirt's connection qemu:///session is added to existing qemu:///system
as a data source for the package.
The data from both sources are merged to a single list.
Due to libvirt limitation, the 'root' user has access
to qemu:///system only.

machines: Extend for qemu:///session

---

test/images/rhel-atomic
test/verify/naughty-continuous-atomic/5750-atomic-storage-reset-regressed
test/verify/naughty-rhel-atomic/5750-atomic-storage-reset-regressed

Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-2017-01-30/

Image refresh for rhel-atomic

---

test/images/continuous-atomic
test/verify/check-kdump
test/verify/naughty-continuous-atomic/5754-atomic-vulnerabilityinfo-broken

Image creation for continuous-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-2017-02-06/

Image refresh for continuous-atomic

---

test/images/fedora-testing

Image creation for fedora-testing in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-2017-02-10/

Image refresh for fedora-testing

---

pkg/lib/variables.less
pkg/selinux/manifest.json
pkg/selinux/selinux-client.es6
pkg/selinux/setroubleshoot-client.js
pkg/selinux/setroubleshoot-view.jsx
pkg/selinux/setroubleshoot.js
pkg/users/index.html
pkg/users/local.js
test/verify/check-setroubleshoot

Fixes for several bugs:
- Fix SELinux page on RHEL Atomic https://bugzilla.redhat.com/show_bug.cgi?id=1422181
- Fix list header font size https://bugzilla.redhat.com/show_bug.cgi?id=1422184
- Fix button tooltip https://bugzilla.redhat.com/show_bug.cgi?id=1365372
- Fix another button tooltip https://bugzilla.redhat.com/show_bug.cgi?id=1412036

7.3.3 fixes

---

po/Makefile.am

Now you see it, now you don't.

po: Use right slash for line continuations

---

test/images/debian-testing

Image refresh for debian-testing

---

doc/guide/packages.xml

This should help people who want to replace certain functionality
of Cockpit when shipping their own parts.

doc: Document how to replace packages and menu items

---

test/verify/naughty-fedora-25/5998-storaged-handle-format-assert

https://bugzilla.redhat.com/show_bug.cgi?id=1427832
Issue #5998

test: Ignore known issue with storaged asserting in HandleFormat

---

pkg/systemd/host.js

In tests we find that sshd is not always running, such as on
Debian where it restarts due to certain external events. In addition
the host keys may change.
So while the host key dialog is open, we refresh it every 10 seconds.

systemd: Refresh host SSH key dialog every 10 seconds

---

test/common/testlib.py

The Policy only has no state per test, the TestCase seems like
the more natural place.
Also, increase limit to five tries and clean up retry loop.
Signed-off-by: Stef Walter <stefw@redhat.com>
* Simplified the retry loop
* Use the TestCase to store number of tries
* Squashed the two commits for clarity
Replaces #6000

test: Limit retries via the TestCase itself

---

src/ws/session.c

The variable `pwd` itself is global and static, so its buffer for strings can also be static. This avoids a leak and serves the same purpose.
It doesn't look like `pwd`'s string pointers are passed to anywhere else. Even if they were, it should only lead to junk strings at worst, but not a security issue.

ws: Make buffer for session pwd static

---

pkg/shell/index.html
pkg/shell/indexes.js
pkg/shell/shell.less
pkg/shell/simple.html
pkg/shell/stub.html
pkg/shell/switcher.less
pkg/shell/variables.less
test/avocado/selenium-base.py
test/avocado/selenium-sosreport.py
test/verify/check-multi-machine
webpack.config.js

Adopt the colors and layout concepts from the new switcher design.
This is about all we can get in for this release.
This also migrates parts of the shell CSS to Less.

shell: Implement minimal part of new switcher design

---

test/verify/naughty-fedora-25/6119-storaged-udisksd-poll-with-variant

https://bugzilla.redhat.com/show_bug.cgi?id=1432743
Issue #6119

test: Add known issue for udisksd/storaged poll_with_variant() crash

---

pkg/storaged/details.js
pkg/storaged/index.html
test/verify/check-storage-mdraid

storaged: Don't allow removing of last MDRAID disk

---

test/images/centos-7

Image creation for centos-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-centos-7-2017-03-18/

Image refresh for centos-7

---

src/ws/cockpitwebservice.c

Having a single consistent prefix at the front of each message
in addition to "cockpit-ws:" isn't neccessary.

ws: Remove logname from CockpitWebService

---

pkg/machines/vmdiskstab.jsx

Bug: the Allocation/Capacity column were not rendered if some disk stats
are NaN (like in case of CDROM).
This patch provides fix.

machines: Fix displaying capacity for Disks

---

test/verify/check-connection

Use the -w argument to wait for iptables lock during testing.

test: Wait for iptables lock

---

src/bridge/askpass.c
src/common/Makefile-common.am
src/common/cockpitframe.c
src/common/cockpitframe.h
src/common/cockpitpipe.c
src/common/cockpitpipe.h
src/common/cockpitpipetransport.c

I've split this out from #6203 so we can track down where the double free issue is on Ubuntu.

common: Factor out frame parsing/reading/writing code

---

pkg/networkmanager/interfaces.js

This mostly helps the tests, but it removes a ton of race conditions from the production code, not just from the tests.
The fix to check-networking-bond is independent, but the timing seems to have changed enough to trigger the race much more reliable.

networkmanager: Only access model when it is consistent

---

pkg/lib/journal.js

lib: handle the case where systemd sends null

---

pkg/kubernetes/scripts/kube-client.js

kubernetes: Allow DN style usernames

---

test/images/fedora-atomic

Image creation for fedora-atomic in process on cockpit-8.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-atomic-2017-03-31/

Image refresh for fedora-atomic

---

src/base1/cockpit.js

If we're navigating to another URL in a window, or are closing the
window, make sure to send an explicit hint to the parent.

base1: Send hints to parent window when we navigate or close

---

test/images/rhel-7

Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-2017-04-10/

Image refresh for rhel-7

---

src/ws/cockpitwebservice.c

No code path exists to the section of code.

ws: Remove unused code

---

test/images/ipa

Image creation for ipa in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-ipa-2017-04-14/

Image refresh for ipa

---

test/images/debian-8

Image creation for debian-8 in process on cockpit-8.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-8-2017-04-19/

Image refresh for debian-8

---

test/images/centos-7
test/images/scripts/centos-7.bootstrap
test/verify/check-docker-storage

We want to test the latest released version.

test: Update centos-7 to 7.3

---

test/common/vmimages.py

This avoids pruning images visible on other branches, e.g. rhel-7.4.
To override this, pass `--branch-ignore` to vm-download.

test: Keep images from visible branches by default

---

pkg/kubernetes/styles/registry.less

kubernetes: Remove gap in projects dropdown

---

pkg/ostree/remotes.js

ostree: Handle no remotes cases

---

configure.ac
doc/protocol.md
pkg/dashboard/manifest.json.in
pkg/lib/machine-dialogs.js
pkg/lib/machines.js
pkg/shell/index-stub.js
pkg/ssh/manifest.json.in
src/base1/cockpit.js
src/bridge/bridge.c
src/bridge/cockpitfsread.c
src/bridge/cockpitrouter.c
src/bridge/cockpitrouter.h
src/bridge/stub.c
src/common/cockpitauthorize.c
src/common/cockpitauthorize.h
src/common/cockpitframe.c
src/common/test-authorize.c
src/ssh/cockpitsshoptions.c
src/ssh/cockpitsshrelay.c
src/ssh/ssh.c
src/ssh/test-sshoptions.c
src/ws/cockpitauth.c
src/ws/mock-auth-command.c
src/ws/session.c
src/ws/test-auth.c
test/common/testlib.py

We want to squash these into one when merging (with a list of commits like in https://github.com/cockpit-project/cockpit/commit/e6b48a46eeafe7e13f435cc85fbc3b4196a94452)
I left them apart for now for easier commenting and review.

7.3.5: add a few commits

---

pkg/docker/client.js
pkg/docker/containers-view.jsx
pkg/docker/details.js
pkg/docker/image.js
pkg/docker/index.html
pkg/docker/run.js
pkg/docker/util.js
test/verify/check-docker

docker: Display image names when known

---

test/verify/naughty-fedora-26/6432-dockerd-current-double-free

test: Add known issue for dockerd-current double free

---

test/verify/naughty-fedora-25/6422-nsupdate-crash-sssd
test/verify/naughty-ubuntu-1604/6422-nsupdate-crash-sssd

test: Add known issue for nsupdate crash after domain join

---

test/verify/naughty/2978-example-ignore
test/verify/naughty/3265-mdraid-not-in-sync

The files in this directory are not used anymore. Just the files
in the image specific directories.

test: Remove unused naughty directory

---

test/verify/naughty-fedora-26/6432-dockerd-current-double-free-2

test: Ignore another dockerd-current core dump

---

test/common/testlib.py

https://bugzilla.redhat.com/show_bug.cgi?id=1447854

test: Ignore SELinux messages about sm-notify

---

test/common/testinfra.py

I'm seeing this failure, and I want to find out more:
Exception: GitHub API problem: Forbidden

test: Dump output of GitHub API Problem

---

pkg/realmd/operation.html
pkg/realmd/operation.js
test/verify/check-realms

realmd: Add text when leaving a domain

---

test/verify/naughty-fedora-25/6422-nsupdate-crash-sssd-2
test/verify/naughty-ubuntu-1604/6422-nsupdate-crash-sssd
test/verify/naughty-ubuntu-1604/6422-nsupdate-crash-sssd-2

Yet another case where this crash causes problems.

test: Another crash of nsupdate on Ubuntu 16.04

---

test/common/testinfra.py

We can share caches of GitHub data between testers (like pods)
if we take care to atomically write out files.
In addition we can move the github cache into the $TEST_DATA
directory, so we can better control its location from containers.
And lastly, include the full github resource path into the file
name so that we can handle future conflicts between various
repos in the same cache.

test: Better GitHub caching

---

pkg/systemd/host.js
pkg/systemd/index.html
test/common/testlib.py
test/verify/check-shutdown-restart

systemd: Disable shutdown/reboot button for unprivileged users

---

pkg/kubernetes/scripts/kube-client.js
pkg/kubernetes/scripts/projects.js
test/verify/check-openshift

https://bugzilla.redhat.com/show_bug.cgi?id=1373418

kubernetes: Add details to invalid character messages

---

pkg/kubernetes/styles/dashboard.less

kubernetes: Fix connection dialog alignment

---

test/verify/naughty-fedora-25/6493-selinux-sosreport-relabelto

https://bugzilla.redhat.com/show_bug.cgi?id=1450110

test: Add known issue for sosreport causing SELinux issues

---

.tasks

This file produces the possible set of bot tasks to be executed in the
current repository by bots. Empty lines and commented lines are ignored
and commented lines are removed. If this file is executable it will be
run, and the output will be used as the list of tasks.
The tasks are sorted descending alphabetically and a task is chosen from
near the top of the sorted result. The task will be run in a shell by the
Cockpit bots.
Initially we just run the current github-tasks every time. This initial
commit helps the cockpit/tests container to add the necessary behavior.

Add initial .tasks file to Cockpit repository

---

bots/.gitignore
bots/README.md

These are automated bots and tools that work on Cockpit. This
includes updating operating system images, testing changes,
releasing Cockpit and more.
Bots are being migrated into this directory and documentation
will be updated as they are.
We need to add this directory to git master before following
pull reequests because they rely on it being here.

bots: Add a new bots directory

---

test/common/testinfra.py

This allows us to specify per branch what we test. Currently the
list of images in master was being applied to all branches, causing
failures.

test: Specify which branches we want to test which images on

---

test/common/testinfra.py

Let our testing infrastructure become aware of rhel-7.4 testing.

test: Add rhel-7.4 testing

---

test/common/testinfra.py

This is needed to be merged into master in order to get #6558 to pass.

test: Add the bots directory to the test $PATH

---

test/vm-download

We want to be able to keep images that are used in pull requests as well.

test: Improve image pruning logic

---

test/images/debian-stable

Image creation for debian-stable in process on falcon.
Log: http://stefw.fedorapeople.org/logs/refresh-debian-stable-2017-05-22/log

Image refresh for debian-stable

---

bots/tests-invoke

This file no longer lives in test/ directory.

bots: Fix the log.html link

---

bots/image-create
bots/image-prepare
bots/machine/__init__.py
bots/machine/cloud-init.iso
bots/machine/identity
bots/machine/network-cockpit.xml
bots/machine/testvm.py
bots/tests-invoke
test/common/test-domain-disk.xml
test/common/testvm.py

The testvm.py from master is guaranteed to work with the bots. Make sure the bots use exactly that version. 
We do this by checking out that copy when overlaying bots/ on other branches.

bots: Link testvm.py and friends into bots/

---

src/ssh/cockpitsshrelay.c

Otherwise the users home dir might get used and change the algo during ssh_connect. This was causing the ssh tests to fail in some setups.

ssh: Always set the ssh knownhosts option

---

pkg/kubernetes/scripts/projects.js

kubernetes: Set system:authenticated on anonymous projects

---

examples/kubernetes/README.md
tools/debian/copyright.template
tools/make-srpm

Images and scripts to make them reside in bots/images now, see commit
8400718.

bots: Fixup remaining mentions of test/images

---

Makefile.am
configure.ac
doc/protocol.md
pkg/dashboard/manifest.json.in
pkg/lib/machine-dialogs.js
pkg/lib/machines.js
pkg/shell/base_index.js
pkg/shell/index-stub.js
pkg/ssh/manifest.json.in
src/base1/cockpit.js
src/bridge/bridge.c
src/bridge/cockpitfsread.c
src/bridge/cockpitrouter.c
src/bridge/cockpitrouter.h
src/bridge/stub.c
src/common/cockpitauthorize.c
src/common/cockpitauthorize.h
src/common/cockpitframe.c
src/common/test-authorize.c
src/ssh/cockpitsshoptions.c
src/ssh/cockpitsshrelay.c
src/ssh/ssh.c
src/ssh/test-sshoptions.c
src/ws/cockpitauth.c
src/ws/mock-auth-command.c
src/ws/session.c
src/ws/test-auth.c
test/common/testlib.py
test/verify/check-docker
tools/semaphore-prepare

We want to backport all patches from the rhel-7.3.5 branch.

rhel-7.4 backports

---

src/ssh/cockpitsshrelay.c

The success message may be received by libssh together with the init message causing the callback to never get executed.

ssh: Hookup channel callbacks before spawning the bridge command

---

po/LINGUAS
po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/fr.po
po/hr.po
po/hu.po
po/ko.po
po/my.po
po/pa.po
po/pt.po
po/pt_BR.po
po/tr.po
po/uk.po
po/zh_CN.po

Update translations from Fedora Zanata

Update translations from Fedora Zanata

---

tools/cockpit.spec

We have docker working on the s390x platform, so enable docker support in cockpit.

enable docker support on s390x

---

pkg/lib/listing.less
pkg/shell/shell.less

Broke with #5768. Regression is in auth dialog.
I believe this should be a + not a *

shell: Auth dialog fixes

---

bots/images/ubuntu-stable

Image refresh for ubuntu-stable

Image refresh for ubuntu-stable

---

package.json

package.json: Update mustache package dependency

---

bots/images/fedora-atomic

Image refresh for fedora-atomic

Refresh image

---

test/verify/check-pages

We need to wait for the text to translate.

test: Fix a testing flake translating the login screen

---

pkg/shell/simple.html

shell: Make capitalization in the top right corner menu consitent

---

package.json

package.json: Update c3 package dependency

---

pkg/shell/manifest.json.in
po/LINGUAS
po/ja.po

This translation is ready for use on Zanata and is at 100%
translated.

po: Add Japanese translation to RHEL 7.4 branch

---

.dir-locals.el

Editor configuration should be elsewhere.

VIM rules the world!

---

tools/cockpit.spec

https://bugzilla.redhat.com/show_bug.cgi?id=1450820

tools: Use semanage instead of chcon

---

pkg/machines/components/desktopConsole.jsx
pkg/machines/machines.less

Fixes: https://github.com/cockpit-project/cockpit/issues/6940

machines: Align virt-viewer install instructions better

---

test/common/phantom-driver.js
test/common/testlib.py

These logs sometimes contain information relevant to a failure.

test: Save javascript logs on failure

---

doc/protocol.md
src/base1/test-dbus.js
src/bridge/cockpitdbusjson.c
src/bridge/cockpitrouter.c

Share D-Bus connections between channels of the same group.

D-Bus connection sharing

---

pkg/lib/cockpit-components-file-autocomplete.css
pkg/lib/cockpit-components-file-autocomplete.jsx
pkg/playground/react-demo-file-autocomplete.jsx
pkg/playground/react-patterns.html
pkg/playground/react-patterns.js

Give users a little autocomplete help when they need to
select a file from the server. We need this for upcoming
ssh keys and VM dialogs.

lib: Implement a file selecting widget

---

package.json

package.json: Update bootstrap-datepicker package dependency

---

package.json

 	package.json: Update angular package dependency 

---

.tasks
bots/issue-scan
bots/naughty-prune
bots/naughty-trigger
bots/task/__init__.py
bots/task/test-task

This is a bot which will prune out the known issues that haven't been updated in 14 days.

bots: Add naughty-prune script

---

bots/naughty/continuous-atomic/5750-atomic-storage-reset-regressed
bots/naughty/fedora-24/5750-atomic-storage-reset-regressed
bots/naughty/fedora-25/5750-atomic-storage-reset-regressed
bots/naughty/fedora-26/5750-atomic-storage-reset-regressed
bots/naughty/fedora-atomic/5750-atomic-storage-reset-regressed
bots/naughty/rhel-atomic/5750-atomic-storage-reset-regressed

Known issue which has not occurred in 41.0 days
Fedora, RHEL, Atomic: 'atomic storage reset' is broken
Fixes #5750

naughty: Close 5750: Fedora, RHEL, Atomic: 'atomic storage reset' is broken

---

package.json

Check for NPM dependency updates: requirejs

---

package.json

Check for NPM dependency updates: angular-route

---

pkg/kubernetes/standalone/src/cockpit-kube-auth/helpers/client.go

This allows GCE users to use oauth. Unfortunalty we have no way to get any info about the user. So we have to treat them as 'Unknown'. But at least they can use the interface.

kubernetes: Support oauth logins with kubernetes

---

package.json

package.json: Update angular-gettext package dependency

---

package.json

package.json: Update d3 package dependency

---

pkg/realmd/operation.html
pkg/realmd/operation.js
pkg/systemd/host.css
test/verify/check-realms

Error message now displayed at top of dialog in patternfly style.
The "more" diagnostics remain at bottom of page.
edit: moved error back to bottom as original
Fixes #3223

realmd: style error message

---

pkg/machines/vnc.html

VNC just plain doesn't work on my machine. In addition it causes
errors in the tests. This commit should fix the following issues
* ReferenceError: Can't find variable: WebUtil
* TypeError: message: novncContainer is undefined
* TypeError: toBeVisibleRow is undefined

machines: Fix VNC display exceptions

---

package.json

package.json: Update react-lite package dependency

---

tools/debian/copyright.template

Add some missing copyrights/licenses from included source code.
https://bugs.debian.org/869934

tools: Update debian/copyright

---

HACKING.md

Needed for virt-resize of XFS images

doc: add libguestfs-xfs to test dependencies

---

pkg/kubernetes/standalone/src/cockpit-kube-auth/helpers/client.go
pkg/kubernetes/standalone/src/cockpit-kube-auth/helpers/creds.go
pkg/kubernetes/standalone/src/cockpit-kube-auth/main.go
test/containers/check-kubernetes-openshift

We will need to back port the shell changes once we agree on the best way to do it.

kubernetes: Delete session tokens on logout

---

test/verify/check-journal

Fix ABRT tests on continuous-atomic

---

src/ws/cockpitcertificate.c

ws: Only add Organization field to certificate when machine-id is not blank

---

bots/images/fedora-i386

Image refresh for fedora-i386

---

src/ws/login.html

The cockpit login screen should not be listed
in search engines.

login: Instruct search engines to avoid indexing

---

bots/naughty/fedora-atomic/4001-lastlog-broken-non-root
bots/naughty/rhel-atomic/4001-lastlog-broken-non-root

Atomic: lastlog broken for non-root
Fixes #4001

naughty: Close 4001: Atomic: lastlog broken for non-root

---

pkg/dashboard/list.js

https://bugzilla.redhat.com/show_bug.cgi?id=1449887

dashboard: Use tooltip on edit server button

---

test/verify/check-setroubleshoot

test: Enable audit so we can properly test applying fixes

---

bots/task/github.py
bots/tests-data

This is a script that produces a data source about test successes, failures, skips for training and analysis.
In particular it includes information about whether a test was merged or retried and then merged, in spite of failing. This should be useful for training some sort of classification ML algorithm.
Output is in JSONL format.

bots: Test data source for machine training or analysis

---

bots/naughty/rhel-7-4/7664-machines-dialog-1
pkg/lib/machine-change-auth.html
pkg/lib/machine-dialogs.js
test/verify/check-multi-machine
test/verify/check-realms

Only show the 'Login Password' and 'Kerberos Ticket' lines if we actually have those credentials.

lib: Show the credentials we have stored correctly

---

pkg/shell/base_index.js
src/ws/login.js

Avoid setting bad values in login.js but handle bad values better in shell
https://bugzilla.redhat.com/show_bug.cgi?id=1493756

shell: Improve setting and handling of os-release

---

bots/naughty/fedora-27/7635-selinux-pmsignal

Example: https://fedorapeople.org/groups/cockpit/logs/pull-7765-20170928-114040-2f4532e8-verify-fedora-27/log.html

bots: Add another naughty variant for issue #7635

---

pkg/kubernetes/styles/topology.less

The action buttons in the sidebar were aligned strangely
in the sidebar.

kubernetes: Fix the topology view button padding

---

pkg/apps/application.css

Applications page should apply styles based in our table CSS.
fixes (#7788)

apps: Include table.css

---

test/verify/check-journal

The sleep one seems to cause confusion when pcp is causing sleep crashes at the same time.

test: Use python to trigger crashes for abrt

---

bots/task/__init__.py

This causes it to be printed in inopportune places. Instead just
place this in the config file.

bots: Don't put the github token on the git push command line

---

doc/guide/Makefile-guide.am
tools/debian/control

Cleans up some items on https://lintian.debian.org/maintainer/pkg-utopia-maintainers@lists.alioth.debian.org.html#cockpit

Small Debian packaging fixes

---

bots/tests-policy

Follow-up from PR #7808 for review comments that are unrelated to moving the code around.

tests-policy simplifications

---

src/pam-ssh-add/pam-ssh-add.c

Call initgroups() for the destination user to avoid retaining auxilliary
groups after dropping privileges.
Spotted by rpmlint:
E: missing-call-to-setgroups-before-setuid /usr/lib64/security/pam_ssh_add.so

pam-ssh-add: Properly drop auxiliary groups

---

bots/images/scripts/debian.setup

Image refresh for ubuntu-1604

---

configure.ac
tools/cockpit.spec

tools: Remove branding from configure

---

package.json
pkg/docker/docker.js
pkg/lib/cockpit-components-terminal.jsx

This should be reviewed together with https://github.com/cockpit-project/term.js/pull/1 and landed after term.js-cockpit 0.0.8 is released.

Fix terminal csp warning

---

pkg/machines/actions.es6
pkg/machines/libvirt.es6
pkg/ovirt/components/ClusterVms.jsx
pkg/ovirt/ovirtApiAccess.es6
pkg/ovirt/provider.es6
test/verify/check-ovirt

Error description for failed actions was not properly passed to
redux to be rendered for the user.
Fixes: https://github.com/cockpit-project/cockpit/issues/7896

ovirt: fix error handling for user actions

---

pkg/ovirt/components/VmOverviewColumn.jsx
pkg/ovirt/helpers.es6
pkg/ovirt/ovirt.es6

oVirt records start time of a virtual machine, so let's render it.

ovirt: Show VM start time

---

bots/images/fedora-26

Image refresh for fedora-26

---

package.json
pkg/lib/mustache.js
pkg/storaged/index.html
pkg/systemd/index.html

Older versions may have a security dependency.

Update mustache to version 2.2.1

---

bots/HACKING.md
bots/README.md

This gets us a bit better documentation for how the bots
work.

bots: Update documentation and add HACKING file

---

pkg/dashboard/manifest.json.in

shell: changed dashboard icon to fa-tachometer

---

package.json

package.json: Update kubernetes-topology-graph package dependency

---

test/verify/files/embed-cockpit.html

- Fix css and script links to use actually existing URLs. This turns
the page from "completely broken" to "mostly pleasant with a few
quirks" (but good enough for our test case).
- Declare encoding to avoid browser complaint.
- Drop the navbar menu, none of the menu items are actually working as
they all point to nonexisting files.
----
I noticed this while debugging the failed `check-embed` test case in #8069 (due to "Blocked a frame with origin "null" from accessing a cross-origin frame"). This PR doesn't fix it, but turns the page from this:
into this:
and fixes the folllowing log messages:
```
GET https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly.min.css [HTTP/2.0 404 Not Found 32ms]
GET https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly-additions.min …
```

test: Fix embed-cockpit.html

---

src/ws/cockpitcertificate.c

Chromium insists on certificates having subjectAltName.  With this the
certificate can be imported into your ~/.pki to make Chromium accept it:
openssl s_client -connect 127.0.0.1:9090 < /dev/null | \
sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/cert.pem
certutil -d sql:$HOME/.pki/nssdb -A -t "TC,C,P" -n cockpit -i /tmp/cert.pem
This does not change `create_temp_file()`, just moves it further up in
the file so that we can use it from `openssl_make_dummy_cert()`.
----
This was one approach that I tried for fixing the container/kubernetes tests for #8069. It's likely not required for it eventually, but even if I find a different approach this is still independently useful IMHO.

ws: Create self-signed certificates with subjectAltName

---

pkg/kubernetes/scripts/kube-client.js

doc https://docs.angularjs.org/api/ng/type/$rootScope.Scope#event-$destroy

kubeLoader $destroy callback fix

---

pkg/storaged/format-dialog.jsx
pkg/storaged/nfs-panel.jsx
test/verify/check-storage-nfs

storage: Checkboxes for NFS mount options

---

pkg/machines/components/infoRecord.jsx
pkg/machines/hostvmslist.jsx
pkg/machines/vmdiskstab.jsx
pkg/ovirt/components/OVirtTab.jsx

Previously InfoRecord element was in that PR https://github.com/cockpit-project/cockpit/pull/7872, but I had to move it to separate commit and even pull request, because I would use it for other details (not only detail's modal, but also in tabs). Please review @petervo @andreasn

machines: Added InfoRecord element, for nice table grouping detail information

---

pkg/kubernetes/scripts/kube-client-cockpit.js
pkg/kubernetes/scripts/kube-client.js
pkg/kubernetes/scripts/policy.js
pkg/kubernetes/scripts/projects.js
pkg/kubernetes/scripts/registry.js
po/ja.po
src/base1/test-dbus.js
src/bridge/cockpitrouter.c
test/verify/check-docker-storage
test/verify/check-journal
test/verify/check-networking-settings
test/verify/check-ostree
test/verify/check-packagekit
test/verify/check-storage-format
test/verify/check-storage-hidden
test/verify/check-storage-iscsi
test/verify/check-storage-lvm2
test/verify/check-storage-multipath
test/verify/check-storage-resize
test/verify/check-system-info

I just created a rhel-7.5 branch starting from tag 154 (what we currently ship in the [upcoming 7.5](https://bugzilla.redhat.com/show_bug.cgi?id=1470780)).

RHEL 7.5 fixes

---

src/base1/cockpit.js

Otherwise grids will continue to request data and metrics will repoen immediately after closing.

base: Remove series from grids when closing metrics

---

pkg/storaged/client.js
pkg/storaged/content-views.jsx
pkg/storaged/details.jsx
pkg/storaged/devices.js
pkg/storaged/dialog.js
pkg/storaged/format-dialog.jsx
pkg/storaged/index.html
pkg/storaged/others-panel.jsx
pkg/storaged/overview.jsx
pkg/storaged/pvol-tabs.jsx
pkg/storaged/storage-controls.jsx
pkg/storaged/storage.css
pkg/storaged/utils.js
pkg/storaged/vdo-details.jsx
pkg/storaged/vdo-monitor.py
pkg/storaged/vdos-panel.jsx
test/verify/check-storage-vdo
test/verify/storagelib.py

Video: https://www.youtube.com/watch?v=_iOYN4Y24aY

storage: Support for VDO

---

pkg/docker/containers-view.jsx
pkg/docker/docker.css
pkg/docker/util.js
test/verify/check-docker

Show problems caught by ABRT in docker overview. https://www.youtube.com/watch?v=BClYGns7boc
Options, ideas, comments?
There is one line, that I am not happy with at all (marked with `TODO`), can someone give me some good idea how to do it? (When a new problem comes, we catch it, process, but how to display it in already rendered overview without refreshing the whole site?)

Problems with containers

---

test/common/testlib.py

After each test, check for uncaught exceptions in the browser log and
fail if there are any.
---
WIP, let's first see how that actually fares with our current code. We may very well have some uncaught exceptions which we need to handle first, or tests deliberately provoke these, then we need to filter them somehow.

test: Fail tests on uncaught exceptions

---

pkg/kubernetes/scripts/images.js

Partially fixes https://bugzilla.redhat.com/show_bug.cgi?id=1512440

kubernetes: reset annotation when we update an imagestream repo

---

test/avocado/cdp.py
test/common/cdp.py
test/common/testlib.py

Refactor this a bit to make #8314 possible.

test: move CDP class out of testlib.py

---

bots/whitelist

hope it is fine that I fixed a typo in my nick

bots: Add suomiy to testing whitelist (fix typo)

---

pkg/storaged/vdos-panel.jsx

storage: Use "wipefs" also for VDO signatures

---

test/common/cdp-driver.js
test/common/cdp.py
test/common/testlib.py
test/common/testvm.py

Fix several cases where we have repetitive test logs.

test: Less verbose messages about chromium in test logs

---

test/common/test-functions.js
test/verify/check-packagekit
test/verify/check-realms
test/verify/check-terminal

See commit messages for details.

Two test cleanups

---

src/common/mock-service.c

The "receive readable fd and ensure writing fails" test in
dbus-common.js could fail when the bridge closed the CockpitPipe
associated with the fd before the test tries the write. In that case,
the bridge doesn't return a "protocol-error", but a more generic one
about the channel not existing anymore.
Keep the writable side of the fd open for a bit, so that this test
actually tests that writing to that fd fails.
I know, I know, this fixes a race with a timeout. I actually think this is the best option in this case though...

bridge: Fix fd passing test

---

pkg/apps/application-list.jsx
pkg/apps/packagekit.js

This avoids dragging them in at Cockpit installation time.

apps: Install collection metadata packages on demand

---

pkg/dashboard/list.js
pkg/docker/overview.js
pkg/lib/machine-info.es6
pkg/systemd/host.js

Initial steps for https://github.com/cockpit-project/cockpit/wiki/Feature:-Hardware-View which also provides some cleanup. Please see individual commits for details.

machine info generalization

---

pkg/storaged/test-util.js
pkg/storaged/utils.js

storage: Use the 'moment' module to format delays

---

pkg/lib/polyfills.js
pkg/machines/index.es6
pkg/machines/libvirt.es6
pkg/machines/reducers.es6
pkg/ovirt/index.es6

Contains various polyfills and hacks which are not handled
by babel (or would be not a good choice to handle it by babel).
Fixes: https://github.com/cockpit-project/cockpit/issues/8498

machines: Add polyfill.js

---

test/common/testlib.py

This causes pyflakes to fail on my machine

test: Remove unused 'signal' import

---

src/common/cockpitwebserver.c

We try to only report interesting events to the journal about
Cockpit. If a client disconnects before it has sent any bytes,
this is not an interesting event. Lets suppress this message

common: Fix erroneous 'Connection reset' messages in logs

---

test/common/cdp.py
test/common/test-functions.js
test/common/testlib.py

See individual commits. This started out with me learning about async/await keywords, but I spotted some other small things.

Some test simplifications

---

package.json

package.json: Update react-redux package dependency

---

test/common/cdp-driver.js
test/common/testlib.py

See individual commit messages and debugging in issue #8605.

Fix broken tests due to "timed out waiting for page load"

---

pkg/storaged/client.js
pkg/storaged/format-dialog.jsx
test/verify/check-storage-format

 storage: Don't offer to format unsupported filesystem types 

---

pkg/lib/polyfills.js

Not supported on IE 11.
Found in context of https://github.com/cockpit-project/cockpit/issues/8498

polyfills.js: Add Array.prototype.find

---

.tasks

https://github.com/cockpit-project/starter-kit/pull/16 adds tests, let's run them.

tasks: Scan cockpit-project/starter-kit for tests

---

pkg/lib/packagekit.es6
pkg/packagekit/mock-updates.es6
pkg/packagekit/updates.jsx

These are some prerequisites for implementing #7758 and two fixes which I noticed while working on it. Let's first confirm that this doesn't break anywhere.

packagekit: Some refactoring and fixes

---

pkg/packagekit/updates.less
webpack.config.js

This does some meaningful grouping for easier understanding and
maintaining the styles.

packagekit: Move CSS to less

---

pkg/systemd/logs.html
test/avocado/selenium-base.py

I'm starting integration of session recording to Cockpit as it was agreed on meetings.
This is just initial step to changing priority list.
Approved design: https://github.com/cockpit-project/cockpit-design/blob/master/journal/journal-with-logins.png
Demo: https://youtu.be/u80ZfozGnDo

systemd: Change log priority list

---

pkg/storaged/client.js
pkg/storaged/details.jsx
pkg/storaged/devices.js
pkg/storaged/nfs-details.jsx
pkg/storaged/nfs-panel.jsx
pkg/storaged/storage.css
test/verify/check-storage-nfs

This gets rid of the confusing "arm" button.
Fixes #8561
Fixes #8565

storage: Move NFS management into new details page

---

bots/learn/README.md

This doesn't  describe everything, but shows people where
to get started and what the intent is. A blog serious about
this will be coming soon.

bots: Add simple initial README file to learn/ directory

---

pkg/lib/patterns.js
pkg/lib/tooltip.css
pkg/packagekit/updates.less
pkg/realmd/operation.js
pkg/shell/indexes.js
pkg/storaged/storage.css
pkg/systemd/host.css
pkg/systemd/host.js
pkg/systemd/index.html
pkg/tuned/change-profile.jsx
pkg/tuned/dialog.js
pkg/tuned/link.html
test/common/test-functions.js
test/common/testlib.py
test/verify/check-tuned

Fix inconsistent tooltips on system page and menu

---

bots/tests-scan

This will soon be added to test Cockpit on the nightly composes for the
upcoming RHEL 8.

bots: Declare rhel-8 image

---

pkg/lib/polyfills.js
pkg/storaged/index.html
pkg/storaged/nfs-details.jsx
pkg/storaged/nfs-mounts.py
pkg/storaged/storage.css

Namely, how long they have been active, and one of the processes that actually use the mount.

storage: Show more details about the sessions/servies that keep NFS busy

---

test/avocado/checklogin-basic.py
test/avocado/checklogin-raw.py
test/avocado/libdisc.py

Backslash correction in string constant might be missing an r prefix.

Backslash correction in string

---

pkg/realmd/operation.js
test/verify/check-realms

See individual commits for details. These commits are preparation for PR #8956 and independent cleanups, but don't change functionality yet.

More kerberos cleanups

---

bots/whitelist

Note that she still needs to get added as a project member for test triggering to actually work, but this will remove that obstacle. Or someone gets around to finally fixing issue #8427  :-)

bots: Add Allison to bot whitelist

---

Makefile.am
configure.ac
test/common/cdp.py
test/common/tap-cdp
tools/tap-driver

On Debian, chromium is just called "chromium", so search for that
executable name in addition to "chromium-browser".
Also: list the discovered path in the output at the end of ./configure,
along with the other tools.

configure.ac: find chromium on debian

---

bots/image-refresh

bots: Put rhel-8 images into the RedHat store

---

pkg/machines/scripts/create_machine.sh

QEMU does not have SPICE enabled on all architectures. Use QMP's
`query-spice` command to detect the capability, and don't create a VM
with spice if it is not supported, as that will fail.
If supported, `query-spice` will answer with something like
{"return": {"migrated": false, "enabled": false, "mouse-mode": "client"}}
If not supported, it will look like
{"error": {"class": "CommandNotFound", "desc": "The command query-spice has not been found"}}
Also make the create_machine.sh script `set -e` and fix a whitespace error.
https://bugzilla.redhat.com/show_bug.cgi?id=1563418

machines: Auto-detect spice capability when creating a VM

---

bots/images/debian-testing
bots/images/scripts/debian.setup
bots/naughty/debian-testing/9036-apparmor-denied-libvirt-signal
test/verify/check-storage-hidden
test/verify/check-storage-lvm2
test/verify/check-storage-resize

This package was recently added to debian-testing.  Add it to our image
setup so that we can run some more of the tests there.

images: Add udisks2-lvm2 to debian-testing

---

pkg/machines/app.jsx
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/hostvmslist.jsx
pkg/ovirt/components/App.jsx
pkg/ovirt/ovirt.less

The dialog is not yet implemented for oVirt, so let's disable it.
Fixes: https://github.com/cockpit-project/cockpit/issues/8767

ovirt: disable Create VM Dialog for oVirt

---

test/verify/check-realms
test/verify/check-services

That image was dropped a while ago, and was apparently forgotten in
commit b16700bc6c.

test: Drop remaining rhel-7-4 special cases

---

test/verify/check-networking-firewall

Lets remove the unused code in this file.

test: Remove unused code in check-networking-firewall

---

containers/unit-tests/Dockerfile
tools/test-static-code

See individual commits. This refreshes the [cockpit/unit-tests](https://hub.docker.com/r/cockpit/unit-tests/tags/) containers on dockerhub. I buil and run them locally and push them to dockerhub  once they succeed.

Fix pyflakes on semaphore

---

bots/images/scripts/debian.setup
bots/images/scripts/lib/debian.bootstrap
bots/images/scripts/ubuntu-stable.bootstrap
bots/images/scripts/ubuntu-stable.install
bots/images/ubuntu-stable
test/verify/check-journal
test/verify/check-networking-other
test/verify/check-networking-team
test/verify/check-realms
test/verify/check-storage-hidden
test/verify/check-storage-lvm2
test/verify/check-storage-resize

See commit messages for details.
Fixes #9094

bots: Adjust ubuntu-stable scripts for 18.04

---

HACKING.md
README.md
configure.ac
doc/guide/cockpit-guide.xml
doc/i18n.md
doc/man/cockpit.xml
pkg/lib/packagekit.es6
pkg/realmd/README.md
pkg/shell/index.html
pkg/shell/simple.html
pkg/shell/stub.html
src/base1/cockpit.js
src/websocket/test-websocket.c
src/ws/cockpit.appdata.xml.in
test/verify/check-connection
tools/cockpit.spec
tools/debian/control

The certificate got fixed now and forced https redirect enabled.

Move cockpit-project.org URLs to https

---

.eslintrc.json
pkg/apps/packagekit.es6
pkg/kdump/kdump-client.es6
pkg/lib/packagekit.es6
pkg/machines/provider.es6
pkg/packagekit/autoupdates.jsx

This now gets into actual code changes, and these rules found some (minor) issues.

eslint fixes

---

package.json

package.json: Update @patternfly/react-console package dependency

---

pkg/systemd/init.js
pkg/systemd/services.css
pkg/systemd/services.html
test/verify/check-services
webpack.config.js

This is just a draft version of how this might work.  Needs design.
Fixes #6

systemd: Show unit relationships with other units

---

doc/guide/feature-realmd.xml
doc/man/cockpit-ws.xml
pkg/realmd/operation.js
test/verify/check-realms

realmd: Automatically retrieve IPA SSL cert for ws

---

test/README

* Fix typo in path for check-* files
* Remove line referring to testsuite-prepare
script since commit 840071 removed it

test: Some fixes in README

---

bots/whitelist

bots: Add Sharon Gratch to bot whitelist

---

bots/images/continuous-atomic
bots/images/scripts/continuous-atomic.setup
test/verify/check-journal

bots: Fix the continuous atomic image build script

---

src/bridge/test-pcp.c

This was highlighted by Coverity. However if this is risky
no need to merge it.

bridge: Fix theoretical leak in test-pcp

---

test/verify/check-openshift

The onChange() event is either not called or fully processed before
subsequent hitting "Create" button

check-kubernetes: Fix race in React code while setting elements value

---

tools/cockpit.spec

cockpit RPM spec fixes for package split

---

bots/image-download
bots/image-upload
bots/images/ubuntu-stable

Add CentOS CI image store

---

bots/tests-scan

Preparation for https://github.com/cockpit-project/cockpit/pull/9361

bots: Declare rhel-x image

---

test/avocado/selenium-sosreport.py
test/avocado/selenium_start.sh
test/avocado/seleniumlib.py
test/avocado/timeoutlib.py

Taken from PR #9178. Updating selenium itself takes much more time than I have at the moment, but let's at least salvage these fixes for the next poor soul who takes a look at these. :-)

Some selenium test fixes

---

bots/whitelist

bots: Add Sanne to bots whitelist

---

src/base1/test-file.js

We seem to get triggered after a partial write in this test
in certain cases.

base1: Fix possible race in test-file.js

---

bots/images/selenium

Image refresh for selenium

---

pkg/docker/details.js
pkg/docker/index.html
test/verify/check-docker

Closes: #5551
Signed-off-by: Katerina Koukiou <kkoukiou@redhat.com>

docker: add volumes list to container info

---

pkg/tuned/dialog.js
pkg/tuned/link.html
test/verify/check-tuned

tuned: Sensible text and tooltip on insufficient permissions

---

pkg/docker/containers-view.jsx
pkg/docker/details.js
pkg/docker/util.js
pkg/systemd/hwinfo.jsx
pkg/systemd/init.js
test/verify/check-pages

screens from several commits:
- BIOS date
- lock account datepicker
- last login account
- docker image created
- docker container create/running times
- services running since

localize and format dates with moment

---

test/verify/check-pages

test: Brazilian Portuguese locale test

---

test/verify/check-pages

The page logs out, which seems to cause this message.

test: Fix flake due to recent changes in check-pages

---

tools/libssh.supp
tools/unknown.supp

tools: Add more valgrind suppressions for Fedora 28

---

pkg/docker/details.js

Containers: Only try to toggle/show volumes if any exists

---

pkg/shell/index.html
pkg/shell/privileges.js
pkg/shell/shell.less
test/verify/check-reauthorize

This is @stefwalter's commit from #9440 and various follow-up css fixes by @garrett.

Remove ability to drop privileges from the top navigation bar

---

src/bridge/cockpitfsread.c

By using a normal CockpitPipe to retrieve data from a file descriptor we have several benefits:
* Read files that do not fit in memory and are not memory mappable
* Make use the flow control that is being implemented
* Remove some code

bridge: Use CockpitPipe to read data for fsread1 channels

---

pkg/systemd/init.js
pkg/systemd/services.html
test/verify/check-realms
test/verify/check-services

systemd: Service start and stop buttons redesign

---

test/common/testlib.py

This sometimes crashes with `UnicodeEncodeError` in Python 2 (not known
for 3), so stop depending on the locale drop the entire
decoding/encoding, just keep and write the output as bytes.
This partly reverts commit 44e0fd48caa5c88, which was not sufficient.

test: Robustify filterOutput() for non-ASCII characters

---

bots/issue-scan

This means more nice info in the logs.

bots: Run various tasks in verbose mode by default

---

pkg/playground/speed.html
pkg/playground/speed.js

This lets us use the speed page for testing.
* Adds ability to read files for a speed test
* Removes use of jQuery

playground: Rewrite the playground speed page

---

bots/images/fedora-27

Image refresh for fedora-27

---

pkg/storaged/client.js
pkg/storaged/vdo-details.jsx

So that we can load the "vdomgmt" module etc that comes with that
utility.

storage: Run vdo-monitor.py with the same Python as the vdo utility

---

pkg/packagekit/autoupdates.jsx
pkg/packagekit/updates.less

packagekit: improved automatic updates layout

---

tools/test-static-code

The TAP output here is pretty contrived, since this file
has grown. Nevertheless lets make it correct.

tools: Fix invalid TAP output in test-static-code

---

.tasks
bots/task/__init__.py
bots/tests-invoke
bots/tests-scan

Ensure that e. g. image refreshes or testvm.py changes don't break external projects. See individual commits for details.

Trigger external tests on changes to bots/

---

pkg/realmd/operation.js
test/verify/check-realms

See individual commits. [Example failure](http://fedorapeople.org/groups/cockpit/logs/pull-9580-20180705-204242-3a085a3c-verify-rhel-7-6/log.html):

IPA: Locale fixes

---

bots/tests-scan

What could possibly go wrong!!!1!! Mea culpa..

bots: Fix cockpit-podman project name in tests-scan

---

bots/tests-scan

bots: Declare rhel-7-5-distropkg test

---

Makefile.am
configure.ac
pkg/storaged/iscsi-panel.jsx
pkg/storaged/manifest.json.in
pkg/storaged/overview.jsx
pkg/storaged/vdos-panel.jsx
pkg/storaged/vgroups-panel.jsx
test/verify/check-apps
test/verify/check-packagekit
test/verify/check-sosreport
test/verify/check-storage-nfs
test/verify/check-storage-vdo
test/verify/check-system-info
tools/cockpit.spec

storage: Install VDO support on demand 

---

pkg/machines/components/vmOverviewTabLibvirt.jsx

Fixes #9679
Closes #9683 
Signed-off-by: Katerina Koukiou <kkoukiou@redhat.com>

machines: Fix CPU type is NULL

---

pkg/machines/libvirt.es6

Fixes #9680
Closes #9684
Signed-off-by: Katerina Koukiou <kkoukiou@redhat.com>

machines: Fix vcpu parameter to install_machines.sh script

---

test/verify/check-docker
tools/cockpit.spec

https://bugzilla.redhat.com/show_bug.cgi?id=1602951

tools: remove cockpit-docker from rhel-x

---

pkg/kubernetes/scripts/projects.js
pkg/kubernetes/scripts/test-projects.js
pkg/kubernetes/views/user-body.html
pkg/kubernetes/views/user-page.html
pkg/kubernetes/views/user-panel.html
test/verify/check-openshift
test/verify/kubelib.py

I split out the five "safe" commits from @stefwalter's #9530. The two other cause regressions, and need to be investigated separately.

Various fixes for OpenShift

---

bots/images/fedora-i386
bots/images/scripts/fedora-i386.bootstrap
bots/images/scripts/fedora-i386.install
bots/naughty/fedora-i386
test/common/testlib.py
test/verify/check-docker
test/verify/check-realms

bots: Move fedora-i386 image to Fedora 28

---

doc/i18n.md

I just set up a new rhel-7.6 branch and translations for it. Good opportunity to review and update the docs.

Update i18n docs

---

pkg/machines/components/diskAdd.jsx
test/verify/check-machines

Follow-up for https://github.com/cockpit-project/cockpit/pull/9166 .
Part of https://github.com/cockpit-project/cockpit/issues/9681 fix.

machines: remove colons from Add Disk dialog

---

bots/images/fedora-28

Image refresh for fedora-28

---

package.json
po/ca.po
po/cs.po
po/de.po
po/es.po
po/eu.po
po/fi.po
po/fr.po
po/hr.po
po/hu.po
po/ja.po
po/ko.po
po/my.po
po/nl.po
po/pa.po
po/pl.po
po/pt.po
po/pt_BR.po
po/tr.po
po/uk.po
po/zh_CN.po

Needed for downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1569423

Build fix and translations update

---

bots/images/scripts/lib/atomic.install

Correct mistake merged in #9796, packages that should be installed were
freshened and packages that should be freshened were installed.

bots: Fix package install in atomic install script

---

bots/naughty/rhel-atomic/9023-subscription-manager-offline

7.5 Atomic regression: subscription-manager status fails when offline
Fixes #9023

naughty: Close 9023: 7.5 Atomic regression: subscription-manager status fails when offline

---

src/ws/login.css
src/ws/login.html
src/ws/login.js
test/verify/check-login

login: suggest other browsers when browser is unsupported

---

package.json

package.json: Update react-bootstrap package dependency

---

test/verify/check-realms

https://bugzilla.redhat.com/show_bug.cgi?id=1582111 got fixed a while
ago.

test: Drop authselect hack on rhel-x

---

test/verify/check-subscriptions

test: Cleanup subscription status on rhel-atomic

---

pkg/storaged/crypto-keyslots.jsx
pkg/storaged/lvol-tabs.jsx
test/verify/check-storage-resize

Resizing a LUKSv2 volume might need a passphrase, and Cockpit should either get one from clevis or ask for one.

storage: Support resizing of LUKSv2

---

src/common/cockpitchannel.c

common: Add another debug message to aid in flow control debugging

---

bots/images/scripts/rhel-x.install
test/verify/check-sosreport
tools/cockpit.spec
tools/debian/control

Various RPM/Debian packaging cleanups

---

configure.ac
test/verify/check-openshift
test/verify/check-storage-luks

Backport some fixes from master.

Fix build and tests on rhel-7.6 branch

---

bots/images/openshift-prerelease
test/verify/check-openshift

Match docker tag to kubevirt version.

test: Kubevirt flake fix

---

configure.ac
containers/unit-tests/run.sh
src/bridge/mock-pmda.c
src/bridge/test-pcp.c
test/verify/check-kubernetes
test/verify/check-networking-basic
test/verify/check-networking-bond
test/verify/check-networking-bridge
test/verify/check-networking-mac
test/verify/check-networking-mtu
test/verify/check-networking-settings
test/verify/check-networking-team
test/verify/check-networking-unmanaged
test/verify/check-networking-vlan
test/verify/check-openshift
tools/test-static-code

Cherry-pick some fixes from master.

Fix build and tests on rhel-7.5 branch

---

bots/images/scripts/selenium.setup
bots/images/selenium
test/avocado/selenium_start.sh
test/avocado/seleniumlib.py

selenium test fixes and Firefox 3 update

---

pkg/storaged/crypto-keyslots.jsx

Just looking for the rightmost ":" to find the port is of course too
naive.

storage: Validate tang URLs and parse them properly

---

package.json

package.json: Update promise package dependency

---

pkg/storaged/crypto-keyslots.jsx
pkg/storaged/dialogx.jsx
pkg/storaged/lvol-tabs.jsx
pkg/storaged/mdraid-details.jsx
pkg/storaged/mdraids-panel.jsx
pkg/storaged/vgroup-details.jsx
pkg/storaged/vgroups-panel.jsx

 storage: Rewrite LVM2 and MDRaid dialogs in React

---

pkg/users/index.html
pkg/users/local.js

Hey @martinpitt, first of all, the updated HACKING.md works. Secondly, this should fix #10104.

accounts: Update tooltip

---

bots/images/rhel-7-6

Image refresh for rhel-7-6

---

pkg/machines/libvirt-dbus.es6
test/verify/check-machines-dbus

machines: Try connecting as superuser to system libvirt-dbus

---

test/verify/machineslib.py

* Don't fail if kvm is not available
* Don't fail when eror is "CPU is incompatible with host CPU"
There is open issue for the later: https://github.com/cockpit-project/cockpit/issues/8385

machines: adjust tests to not require nested kvm

---

bots/tests-scan

bots: Split external projects by public and non-public requirements

---

pkg/docker/containers-view.jsx
test/verify/check-docker

docker: Show selected filter in containers filter dropdown

---

package.json

package.json: Update prop-types package dependency

---

pkg/storaged/content-views.jsx
pkg/storaged/crypto-keyslots.jsx
pkg/storaged/dialogx.jsx
pkg/storaged/format-dialog.jsx
pkg/storaged/iscsi-panel.jsx
pkg/storaged/mdraid-details.jsx
pkg/storaged/mdraids-panel.jsx
pkg/storaged/nfs-details.jsx
pkg/storaged/vdos-panel.jsx
pkg/storaged/vgroup-details.jsx
pkg/storaged/vgroups-panel.jsx
test/verify/storagelib.py

storage: Rewrite NFS dialogs in React 

---

bots/task/test-policy
bots/tests-invoke
bots/tests-policy
bots/tests-scan

See individual commits. This is a blocker for welder, where we should run the tests also with chromium.

Test scenario support

---

bots/tests-scan

See https://github.com/weldr/welder-web/pull/368

bots: Run welder-web tests with chrome and firefox scenarios

---

bots/naughty/debian-testing/9704-setntp-race

Known issue which has not occurred in 22 days
timedated SetNtp race condition with systemd 239
Fixes #9704

naughty: Close 9704: timedated SetNtp race condition with systemd 239

---

bots/push-rewrite
bots/task/github.py

bots/push-rewrite: Wait for commits to appear in the API

---

bots/issue-scan

If a task has a kubernetes namepsace DNS URL, then only run inside the
relevant Kubernetes project/namespace

bots: Only run Kube namespace specific tasks in that namespace

---

bots/images/openshift-prerelease

Image refresh for openshift-prerelease

Image refresh for openshift-prerelease

---

pkg/docker/index.html
pkg/docker/storage.jsx
pkg/lib/cockpit-components-install-dialog.jsx
pkg/machines/components/vcpuModal.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/ovirt/components/vcpuModal.jsx
pkg/packagekit/updates.jsx
pkg/packagekit/updates.less
pkg/storaged/crypto-keyslots.jsx
pkg/storaged/lvol-tabs.jsx
test/common/cdp-driver.js

Fix more React warnings

---

pkg/systemd/logs.js

Hello, this fixes table formatting in ABRT reports in logs panel. Partially related to 0ca254db.

fix table formatting in ABRT log reports

---

pkg/machines/components/notification/inlineNotification.jsx
pkg/machines/components/notification/notification.jsx
pkg/machines/components/notification/notificationArea.jsx
pkg/machines/components/vcpuModal.jsx
pkg/machines/components/vmLastMessage.jsx
test/verify/machineslib.py

There are not UI changes introduced by this commit.

machines: replace Notification with Alert from patternfly-react

---

pkg/docker/containers-view.jsx
pkg/lib/cockpit-components-listing.jsx
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/hostvmslist.jsx
pkg/networkmanager/firewall.jsx
pkg/playground/jquery-patterns.html
pkg/playground/react-demo-dialog.jsx
pkg/playground/react-demo-listing.jsx
pkg/playground/react-demo-onoff.jsx
pkg/playground/react-demo-tooltip.jsx
pkg/playground/service.html
pkg/playground/speed.html
pkg/storaged/content-views.jsx
pkg/storaged/iscsi-panel.jsx
test/verify/check-pages

- Fix missing `<tbody>`s
- Fix "actions" property in Listing -- it must be a list, not an object
Add a shallow test case that ensures that the "React Patterns" page
loads and does not throw any oopses and React errors.
Also fix the `selected` property of `ListingRow`, a bug which got uncovered by this.

playground: Fix crashes and React errors

---

pkg/machines/scripts/create_machine.sh

Previously only spice support was checked, now both spice and vnc support are
quered with virsh domcapabilities.

machines: quering of graphics support should use virsh domcapabilities

---

bots/machine/testvm.py
test/common/testlib.py

This avoids looking at journal messages that happen outside of the test,
i. e. during boot, or when running a test against an already running
machine (with `--machine` and `--browser`). This avoids failing tests on
unrelated noise, and enables re-using our tests downstream.

test: Only consider journal messages from current test run

---

test/avocado/seleniumlib.py

* allow use local browser instance again via special CMD line parameter
* add possible to change port
* add possible to change URL

test: seleniumlib fixes - allow use local browser

---

test/avocado/selenium-base.py
test/avocado/selenium-docker.py
test/avocado/selenium-navigate.py
test/avocado/selenium-sosreport.py
test/avocado/selenium-storage.py
test/avocado/seleniumlib.py

remove host-app check from each function
wait for menu in log, not just current day, it sometimes fail

test: selenium - improved log handling tab, generalize host-app wait

---

pkg/machines/actions/provider-actions.es6
pkg/machines/app.jsx
pkg/machines/components/nicEdit.css
pkg/machines/components/nicEdit.jsx
pkg/machines/components/vm/vm.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/machines/constants/provider-action-types.es6
pkg/machines/hostvmslist.jsx
pkg/machines/libvirt-common.es6
pkg/machines/libvirt-dbus.es6
pkg/machines/libvirt-virsh.es6
pkg/machines/machines.less
pkg/ovirt/components/App.jsx
test/verify/check-machines-dbus

machines: Configure  Network model type

---

bots/po-refresh
bots/task/__init__.py

Update translations from Fedora Zanata

Fix msgstr detection logic

---

package.json

Update react-dom component

---

pkg/packagekit/updates.jsx
test/verify/check-packagekit

packagekit: Add tooltip for update severity

---

bots/images/candlepin

Image refresh for candlepin

---

pkg/selinux/setroubleshoot-view.jsx

SELinux: Fixes npe in setroubleshoot

---

bots/push-rewrite
bots/task/__init__.py
bots/task/github.py
bots/tests-trigger

With this, `npm-trigger`, `issue-scan`, and `npm-update` can run in an arbitrary Git checkout and will do the right thing.

bots: Get ready to run in random repositories

---

bots/po-refresh

So that this also works for other projects than Cockpit itself.

bots: Run "make update-po" instead of "make po/cockpit.pot"

---

bots/naughty/fedora-28/7635-selinux-pmlogger
bots/naughty/fedora-28/7635-selinux-pmlogger2
bots/naughty/fedora-28/7635-selinux-pmsignal
bots/naughty/fedora-29/7635-selinux-pmlogger
bots/naughty/fedora-29/7635-selinux-pmlogger2
bots/naughty/fedora-29/7635-selinux-pmsignal
bots/naughty/fedora-atomic/7635-selinux-pmsignal

naughty: Close 7635: Selinux and Pcp

---

package.json
test/common/testlib.py

package.json: Update react-dom package dependency

---

src/ws/login.js

login: require CSS flex & grid support

---

pkg/lib/cockpit-components-file-autocomplete.jsx
pkg/machines/app.jsx
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/helpers.es6
pkg/machines/machines.less
test/verify/machineslib.py

timeouted promise helper function was adjusted to call promise callbacks
even if window timeout hasn't expired yet.

machines: use patternfly-react for create vm modal dialog

---

bots/npm-update

WIP - rewrite npm-update to be easier to follow

---

bots/machine/machine_core/constants.py
test/README.md
test/verify/check-networking-basic
test/verify/check-networking-bond
test/verify/check-networking-bridge
test/verify/check-networking-mac
test/verify/check-networking-mtu
test/verify/check-networking-settings
test/verify/check-networking-team
test/verify/check-networking-unmanaged
test/verify/check-networking-vlan

Move more things away from fedora-28

---

pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

Networking: Use patternfly's modal for Add Services

---

pkg/machines/components/vmDisksTab.jsx
pkg/machines/machines.less

machines: Fix gap in Disks list header

---

pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

https://bugzilla.redhat.com/show_bug.cgi?id=1598625

Various fixes to firewall Add Services dialog

---

test/avocado/selenium-base.py
test/avocado/selenium-dashboard.py
test/avocado/selenium-docker.py
test/avocado/selenium-navigate.py
test/avocado/selenium-network.py
test/avocado/selenium-sosreport.py
test/avocado/selenium-storage.py
test/avocado/testlib_avocado/exceptions.py
test/avocado/testlib_avocado/seleniumlib.py

failing and screenhot tested with one broken test. worked well in CI, commit with failed test removed
see log: 
https://fedorapeople.org/groups/cockpit/logs/pull-10731-20181205-134141-754ff9f1-selenium-firefox/log.html

test: fix selenium error handling of libraries

---

pkg/storaged/format-dialog.jsx
pkg/storaged/fsys-tab.jsx
pkg/storaged/utils.js
test/verify/check-storage-format

storage: Validate fsys label length

---

pkg/docker/containers-view.jsx
pkg/docker/docker.css
pkg/lib/listing.less
pkg/machines/components/vmDisksTab.jsx
pkg/machines/machines.less

Addresses:
- #10676 
- #10672
- #10689 
- dark lines in items in lists-in-lists https://github.com/cockpit-project/cockpit/pull/10335#issuecomment-436326752
And a few additional issues I found along the way.

lib: list fixes and enhancements

---

.gitignore
src/bridge/Makefile.am
src/bridge/org.cockpit-project.cockpit-bridge.policy.in
tools/cockpit.spec
tools/debian/cockpit-bridge.install

This provides a nicer polkit prompt with using cockpit-desktop.
It also defines a polkit action ID, so that it's possible to have a
custom polkit policy for this.
https://bugzilla.redhat.com/show_bug.cgi?id=1651264

bridge: Add polkit action for privileged bridge

---

pkg/machines/components/vcpuModal.jsx

https://bugzilla.redhat.com/show_bug.cgi?id=1657133

machines: Fix tooltip message in vcpu modal dialog

---

pkg/storaged/format-dialog.jsx
pkg/storaged/fsys-tab.jsx
pkg/storaged/utils.js
test/verify/check-storage-iscsi
test/verify/check-storage-vdo

Video for release notes: https://www.youtube.com/watch?v=rMW5--h2omk

storage: Prefill mount options

---

pkg/lib/form-layout.less

lib: form-layout: Do not set width for relaxed elements 

---

test/verify/kubelib.py

The default "systemd" cgroup driver has been broken for 9 months now
(https://bugzilla.redhat.com/show_bug.cgi?id=1558425), so do the
official workaround and switch to the cgroupfs driver.
Add checks to make sure the node is actually healthy and coming up.

test: Fix and test k8s kubelet startup

---

pkg/docker/client.js

kubernetes pods use their own cgroup hierarchy, not the standard docker
ones. Moreover, these differ between the two cgroup drivers (systemd and
cgroupfs). Adjust the docker container ID parsing in
`update_usage_grid()` to recognize these as well.
Don't add a test case, as the graphs are a canvas which is not
introspectable.
https://bugzilla.redhat.com/show_bug.cgi?id=1525794

docker: Include kubernetes containers in CPU/memory graphs

---

bots/images/fedora-29

Image refresh for fedora-29

---

src/common/cockpitauthorize.c
src/ws/session.c

Some minor cockpit-session cleanups. Described in commit messages. Resulting from reviewing code and working on fuzzing.

Minor cockpit-session cleanups

---

Makefile.am
pkg/apps/appstream.js
pkg/docker/storage.jsx
pkg/kdump/kdump-client.js
pkg/lib/credentials.js
pkg/lib/journal.js
pkg/lib/machine-dialogs.js
pkg/machines/libvirt-common.js
pkg/realmd/operation.js
pkg/sosreport/index.js
pkg/storaged/client.js
pkg/storaged/crypto-keyslots.jsx
pkg/storaged/vdo-details.jsx
pkg/systemd/host.js
pkg/tuned/dialog.js
pkg/users/authorized-keys.js
tools/test-static-code
tools/webpack-make
webpack.config.js

Preparation for moving to a modern webpack in PR #10826. Split out to land it separately, as the webpack conversion still exposes or causes some subtle bugs in our unit tests.

Various small build system fixes

---

package.json

package.json: Update xterm package dependency

---

pkg/machines/libvirt-dbus.js

Two issues where addressed with this patch:
* Failures from the promise which is nested would never be handled. Fix
this with promise chaining.
* In case GetXmlDesc api call failed for one of the volumes the Promise.all
rejected immediately. We don't want this behavior so introduce a hack to avoid
the fail-fast behavior.

machines: Properly handle errors from promises in GET_STORAGE_VOLUMES

---

pkg/docker/console.js
pkg/storaged/block-details.jsx
pkg/storaged/client.js
pkg/storaged/content-views.jsx
pkg/storaged/details.jsx
pkg/storaged/drive-details.jsx
pkg/storaged/format-dialog.jsx
pkg/storaged/fsys-tab.jsx
pkg/storaged/lvol-tabs.jsx
pkg/storaged/mdraid-details.jsx
pkg/storaged/part-tab.jsx
pkg/storaged/pvol-tabs.jsx
pkg/storaged/storage-controls.jsx
pkg/storaged/swap-tab.jsx
pkg/storaged/test-util.js
pkg/storaged/utils.js
pkg/storaged/vgroup-details.jsx
webpack.config.js

Remaining cleanup after commit 2daea35f7248bb9932a6453a3afdf5d659887029.

Drop babel CommonJS plugin

---

pkg/kdump/config-client.es6
pkg/kdump/kdump-client.es6
pkg/kdump/kdump-view.jsx
pkg/kdump/kdump.js
pkg/kdump/test-config-client.js
test/verify/check-kdump

Backport kdump fixes to rhel-7.7

---

pkg/realmd/operation.js
test/verify/check-realms

Adjust testIpa test to check if the tooltip gets triggered by hovering
over the explamation mark.

realm: Replace title attribute with bootstrap tooltip

---

test/common/testlib.py
test/verify/check-apps

test: Allow "which: no python" when restarting/reloading

---

test/avocado/testlib_avocado/seleniumlib.py

test: chown identity file attributes in selenium library

---

pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall

firewall: hide Services table and action button if firewall is off

---

.tasks
bots/image-refresh
bots/make-checkout
bots/run-queue
bots/task/github.py
bots/tests-invoke
bots/tests-scan
bots/tests-trigger

Use AMQP queue in tests-scan

---

pkg/machines/components/vmOverviewTab.jsx
pkg/machines/components/vmOverviewTabLibvirt.jsx
po/ca.po
po/cs.po
po/da.po
po/de.po
po/es.po
po/eu.po
po/fi.po
po/fr.po
po/hr.po
po/hu.po
po/it.po
po/ja.po
po/ko.po
po/my.po
po/nl.po
po/pa.po
po/pl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/sv.po
po/tr.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

machines: remove colons from labels for consistency with other pages

---

package.json
pkg/shell/shell.less

New versions fix vulnerabilities pointed out by GitHub security alerts.

package.json: Update xterm and bootstrap dependencies

---

test/verify/check-connection
test/verify/check-kubernetes
test/verify/check-packagekit
test/verify/check-realms
test/verify/kubelib.py

test: Use assertRegex instead of assertRegexpMatches

---

pkg/lib/machine-info.js
pkg/systemd/host.js
pkg/systemd/hwinfo.jsx
test/verify/check-system-info

This fixes the various facets of issue #8807, see individual commits for details.

System/Hardware info: Fix various issues on systems without DMI support

---

bots/naughty/fedora-29/10901-ipa-getcert-crash

Known issue which has not occurred in 26 days
ipa-getcert crashes in ipa-submit
Fixes #10901

naughty: Close 10901: ipa-getcert crashes in ipa-submit

---

bots/naughty/debian-testing/9722-firewalld-bad-rule-3
bots/naughty/rhel-8-0/9722-firewalld-bad-rule
bots/naughty/rhel-8-0/9722-firewalld-bad-rule-2
bots/naughty/rhel-8-0/9722-firewalld-bad-rule-3

iptables: Bad rule (does a matching rule exist in that chain?)
Fixes #9722

naughty: Close 9722:  iptables: Bad rule (does a matching rule exist in that chain?)

---

pkg/storaged/storage-controls.jsx
test/verify/check-storage-basic

storage: Do not open dialog for non-authorized user

---

pkg/realmd/operation.html

I believe you mean "affect" as a verb here.

Fix typo in "Leave Domain" description

---

.tasks
bots/inspect-queue
bots/run-queue
bots/tests-scan

bots: Add ssl support for amqp interaction

---

HACKING.md

Let's put an end to all these "aww, semaphore fail on an extra blank
line".

HACKING: Document setting up test-static-code as pre-push hook [no-test]

---

bots/tests-scan

This is currently running on the webhook.

bots: Also check contexts with repo cli argument 

---

pkg/machines/app.jsx
pkg/machines/components/storagePools/storagePool.jsx
pkg/machines/components/storagePools/storagePoolList.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

This will allow us to see if some volume is used by some guest as a disk.

machines: Show `Used by` column for Storage Volumes

---

test/avocado/checkexample-foo.py
test/avocado/checklogin-basic.py
test/avocado/checklogin-raw.py
test/avocado/checkrealms-basic.py
test/avocado/scheduler.py
test/avocado/selenium-base.py
test/avocado/selenium-dashboard.py
test/avocado/selenium-docker.py
test/avocado/selenium-navigate.py
test/avocado/selenium-network.py
test/avocado/selenium-sosreport.py
test/avocado/selenium-storage.py
test/avocado/selenium-tuned.py
test/avocado/testlib_avocado/cockpit.py
test/avocado/testlib_avocado/exceptions.py
test/avocado/testlib_avocado/libdisc.py
test/avocado/testlib_avocado/libnetwork.py
test/avocado/testlib_avocado/seleniumlib.py
test/avocado/testlib_avocado/timeoutlib.py
test/common/cdp.py
test/common/tap.py
test/common/testlib.py
tools/test-static-code

Since we are upstreaming the selenium tests for machines I thought it is good timing to enable pep8 for whole test directory.

Enable python code style checks in whole test directory

---

bots/image-download
bots/image-refresh
bots/issue-scan
bots/run-queue
bots/task/__init__.py
bots/tests-scan

bots: Consolidate handling of internal Red Hat image store

---

pkg/lib/form-layout.less
pkg/machines/app.jsx
pkg/machines/components/aggregateStatusCards.jsx
pkg/machines/components/networks/network.jsx
pkg/machines/components/networks/networkList.jsx
pkg/machines/components/networks/networkOverviewTab.css
pkg/machines/components/networks/networkOverviewTab.jsx
pkg/machines/helpers.js
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/machines.less
test/verify/check-machines-dbus

Read-only statistics for virtual networks. This components recognizes properties: persistent, autostart, Quality of Service (bandwith) and ipv4 and ipv6 addresses with DHCP ranges and DHCP hosts.

machines: Introduce virtual networks

---

pkg/lib/cockpit-components-listing.jsx
pkg/machines/components/notification/inlineNotification.jsx
pkg/machines/components/storagePools/storagePoolOverviewTab.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/components/storagePools/storageVolumeDelete.css
pkg/machines/components/storagePools/storageVolumeDelete.jsx
pkg/machines/components/vmLastMessage.jsx
pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

- Used by column was introduced
- Volume deletion was introduced
The last patch does just some code move to sort the functions in libvirt-dbus.es6 file so as to make me happier.
Error component was introduced to serve the error notification in the UI.
This introduces some inconsistency between VMs page and Storage Pools page, because for domain errors as displayed as warnings. This I believe needs to be changed, since error notifications should probably use Alert with type error and not warning.
https://www.patternfly.org/pattern-library/communication/inline-notifications/

machines: Implement Storage Volume deletion 

---

package.json

package.json: Update bootstrap package dependency

---

package.json

package.json: Update qunit package dependency

---

src/base1/test-http.js
src/bridge/test-httpstream.c
src/bridge/test-packages.c
src/common/cockpitwebresponse.c
src/common/test-webresponse.c
src/ws/test-channelresponse.c

Factorize header tests, set X-Content-Type-Options header

---

src/common/test-webserver.c

If there is no non-loopback interface (which is common in e. g. mock
nspawn environments), leave `TestCase.hostport` as `NULL` instead of
crashing with an assertion. Skip the tests (or parts of them) which
require an external address.
Fixes #11312

common: Fix test-webserver for environments with only loopback interface

---

pkg/packagekit/autoupdates.jsx

Software Update: Improve native selects

---

test/verify/packagelib.py

- Drop machine provision from PackageCase. This was only needed for a
workaround for Ubuntu 16.04 and Debian 8.
- Backup/restore the original repositories, to avoid totally destroying
the testbed.
- Backup/restore and move away PackageKit's transaction database, as an
existing one breaks the test.
- Clean up all installed test packages.

test: Allow check-packagekit to run against existing machine

---

bots/tests-scan

bots: Declare rhel-8-1 image [no-test]

---

pkg/machines/components/networks/network.jsx
pkg/machines/components/networks/networkOverviewTab.jsx
pkg/machines/libvirt-dbus.js
test/verify/check-machines-dbus

Show Activate/Deactive button on top of network tab.
You can see the buttton at top right:
If network could not be started, show this error message:

machines: Allow configuration of virtual network's state

---

pkg/machines/components/deleteDialog.css
pkg/machines/components/deleteDialog.jsx
pkg/machines/libvirt-dbus.js
pkg/machines/libvirt-virsh.js
test/verify/machineslib.py

Previously only disks of type file were shown.

machines: show disks of type volume in VM delete dialog

---

pkg/storaged/nfs-mounts.py
test/verify/check-storage-nfs

storage: Better NFS tests, Ignore non-NFS mounts in NFS table

---

test/verify/check-machines-dbus
test/verify/check-ovirt

See https://github.com/GNOME/libxml2/commit/da35eeae5
Related to #11432, once merged #11432 needs to be rebased

tests: Expect newline from 'xmllint --xpath' output

---

test/verify/check-networking-checkpoints

test: Remove HACK for known issue #5529

---

pkg/lib/journal.js
pkg/systemd/logs.html
pkg/systemd/logs.js
test/verify/check-journal

This commit makes it possible to filter the log entries by service name (as discussed here https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/QQJ3PDPI4SMBGTJ2R6JI6PNYXOHXYJTT/ ).

systemd: Add service filter

---

pkg/machines/components/storagePools/createStoragePoolDialog.css
pkg/machines/components/storagePools/createStoragePoolDialog.jsx
pkg/machines/components/storagePools/storagePoolDelete.jsx
pkg/machines/components/storagePools/storagePoolOverviewTab.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/components/storagePools/storageVolumeDelete.jsx
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

There are also multiple enhancements in the parsing and displaying of storage pools.

machines: iSCSI pool creation support

---

src/common/cockpitwebresponse.c
src/ws/main.c

See individual commit messages for details.

Coverity scan fixes

---

bots/task/github.py

I tested this locally with a local http server which returns 502 and now and then a 200 to see if this works.

bots: Retry GitHub api requests up to 5 times upon receiving 502 [no-test]

---

pkg/users/index.html
pkg/users/users.css

Make it slightly better for people using screen readers by
converting each first cell in the rows from td to th
https://www.accessibility-developer-guide.com/examples/tables/good-example/

users: make page easier to read with a screen reader

---

test/verify/machineslib.py

When creating a new VM with PXE as installation mode, in the installation
sources one should see a list of Virtual Networks and network host
devices. For the later resources a test was missing.

machines: test that network host devices are appearing in the pxe sources

---

bots/images/rhel-7-7
bots/naughty/rhel-7/11477-selinux-ipa-submit-getattr

Image refresh for rhel-7-7

---

pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css
test/verify/check-networking-firewall

Firewall services dialog ports

---

bots/tests-scan

Log from tests-scan when triggered and which tests are triggered and
which are not and why.
Also since logging module is introduced, move error messages into that.

[no-test] bots: tests-scan log what is happening

---

bots/naughty/fedora-30/6108-pcp-pmfindprofile-crash
test/verify/check-pages

Validate that translations do not break pages and also check for used
locale and that it is valid.
Tested with both breaking translations, just like [here](https://github.com/cockpit-project/cockpit/issues/10604#issuecomment-443625840) and with breaking locale like [here](https://github.com/cockpit-project/cockpit/commit/a395a4a5155e62b24cdb8afa3697618c31282e1f)

tests: Test translations

---

bots/po-refresh
bots/task/__init__.py

Do not comment n-times again as in #11582

bots: Only comment `done` on issue when pushing branch

---

bots/images/scripts/openshift.setup
pkg/kubernetes/views/registry-dashboard-page.html

This option is deprecated in Docker.

Option -e is deprecated in docker

---

bots/images/fedora-30
bots/naughty/fedora-30/11614-selinux-denying-iscsi_tcp-module-load

Image refresh for fedora-30

---

pkg/storaged/client.js
pkg/storaged/devices.jsx
pkg/storaged/drives-panel.jsx
pkg/storaged/overview.jsx
pkg/storaged/plot.jsx
test/verify/check-storage-basic
test/verify/check-storage-scaling

For the release notes:
```
Cockpit now survives much better when there are thousands of block devices on the Storage page.
```

storage - Improve performance with many block devices

---

bots/make-checkout
bots/tests-scan

This only changes current code and does not bring any functional changes.
I should be possible to add for external projects other branches as well, which would make it possible to run tests on them.

bots: Map from project through branch to contexts [no-test]

---

pkg/lib/page.css

lib: Use inline-flex for btn-group to ensure group sticks together

---

pkg/systemd/init.js
pkg/systemd/services.css
pkg/systemd/services.html
test/verify/check-services

Backported the styled native select from #11155 and adjusted the HTML+CSS+JS accordingly.
Originally brought up in #11241.

services: Change filter dropdown to a native select

---

bots/image-prepare

As this is now our latest Fedora image.

bots: Do development build on Fedora 30

---

pkg/machines/components/storagePools/createStoragePoolDialog.jsx
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

The iscsi-direct pool, based on libiscsi is introduced to libvirt since
v4.7.
Libvirt reference: https://libvirt.org/storage.html#StorageBackendISCSIDirect
Closes #11562
Signed-off-by: Han Han <hhan@redhat.com>

machines: implement creation of iscsi-direct storage pool

---

pkg/dashboard/index.html
pkg/lib/journal.css
pkg/lib/listing.less
pkg/lib/table.css
pkg/networkmanager/index.html
pkg/shell/shell.less
pkg/storaged/fsys-panel.jsx
pkg/storaged/optional-panel.jsx
src/base1/cockpit.css

Fixing responsiveness and general layout of panel headers and their children.
Adresses #11600

lib: Fix panel header layout & mobile responsiveness

---

bots/tests-scan

We will soon add this image, so declare it to the bots so that we can
manually trigger tests on it.

bots: Declare rhel-8-0-distropkg test [no-test]

---

pkg/machines/components/diskAdd.jsx
pkg/machines/components/infoRecord.jsx
pkg/machines/components/vcpuModal.css
pkg/machines/components/vcpuModal.jsx
pkg/machines/components/vmDiskSourceCell.jsx
pkg/machines/machines.less
pkg/ovirt/components/OVirtTab.jsx
pkg/ovirt/components/infoRecord.jsx
pkg/ovirt/components/vcpuModal.jsx
test/avocado/selenium-machines-disks.py
test/verify/machineslib.py

infoRecord component was adjusted to not use table,
as well as vmDiskSourceCell which was using it.

machines: refactor vcpu dialog to use ct-form-layout

---

bots/task/github.py

Implement GitHub.url and GitHub.repo as properties in order to defer the
detection logic until such a time as when these values are actually
needed.  It was previously happening as a side-effect of merely
importing 'tasks', which is a problem because sometimes it throws an
exception.
Provide 'git config cockpit.bots.github-repo' as a convenient and
explicit way to set the upstream repository for the bots to interact
with, without having to specify it on the commandline or in an
environment variable, and without falling back to heuristics based on
the 'origin' remote.
Catch the subprocess error when 'git remote get-url origin' fails and,
instead, throw a RuntimeError with a helpful message.

bots: change github repository detection logic [no-test]

---

test/common/testlib.py

The corresponding bugs got fixed a while ago.

Drop obsolete expected messages filters

---

test/verify/check-connection

These changes were introduced in 0f3f14299

test: Do not check new changes on rhel-8-0-distropkg [no-test]

---

containers/bastion/README.md
src/ssh/cockpitsshoptions.c
src/ssh/cockpitsshrelay.c
src/ssh/test-sshbridge.c
src/ssh/test-sshoptions.c
src/ws/cockpitauth.c
src/ws/login.js
test/verify/check-multi-machine

See commit logs for details.
https://bugzilla.redhat.com/show_bug.cgi?id=1701174

Connect to unknown ssh hosts when interactive

---

pkg/lib/cockpit-components-onoff.jsx
pkg/networkmanager/index.html
pkg/networkmanager/interfaces.js
pkg/playground/jquery-patterns.html
pkg/playground/jquery-patterns.js
pkg/shell/credentials.js
pkg/shell/index.html
pkg/systemd/host.js
pkg/systemd/index.html
test/verify/check-keys
test/verify/check-networking-basic
test/verify/check-networking-bond
test/verify/check-networking-checkpoints
test/verify/check-networking-firewall
test/verify/check-networking-settings
test/verify/check-networking-team
test/verify/check-system-info

This is some preparatory work for PR #11769.

Move On/Off switches to React component

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/create-vm-dialog/pxe-helpers.js
pkg/machines/components/machinesConnectionSelector.jsx
pkg/machines/libvirt-common.js
pkg/machines/reducers.js
test/verify/machineslib.py

Rebased on top of https://github.com/cockpit-project/cockpit/pull/11772 so that we don't stall #11772 on this big PR.
However, if this one gets reviewed fast, lets merge it instead of #11772.

Refactor createVm dialog to make it simpler and fix some issues with PXE installation mode

---

bots/image-refresh
bots/machine/machine_core/constants.py
test/README.md
test/avocado/README.md
test/avocado/run-tests
test/verify/check-networking-basic
test/verify/check-networking-bond
test/verify/check-networking-bridge
test/verify/check-networking-mac
test/verify/check-networking-mtu
test/verify/check-networking-settings
test/verify/check-networking-team
test/verify/check-networking-unmanaged
test/verify/check-networking-vlan

Move default test image to fedora-30, some test/doc cleanup

---

pkg/networkmanager/firewall.jsx

firewall: Fix layout in form to add custom services

---

pkg/lib/cockpit-components-inline-notification.css
pkg/lib/cockpit-components-inline-notification.jsx
pkg/machines/app.jsx
pkg/machines/components/deleteDialog.jsx
pkg/machines/components/diskAdd.jsx
pkg/machines/components/nicEdit.jsx
pkg/machines/components/notification/inlineNotification.css
pkg/machines/components/storagePools/createStoragePoolDialog.jsx
pkg/machines/components/storagePools/storagePoolDelete.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/components/vcpuModal.jsx
pkg/machines/components/vm/bootOrderModal.jsx
pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
test/verify/check-networking-firewall
test/verify/machineslib.py

On removing a service:
On adding a custom service:

firewall: Limited error handling 

---

test/verify/machineslib.py

The first of the 3 states was not used at all so it got removed.
Also there were some redudant waits, which were removed as well.
A check that the initial state is gone waa added before checking for the
second desired state, in order to robustify the test.

tests: refactor assertVmStates method in machineslib to fix the testCreate 

---

pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css
pkg/networkmanager/utils.js
test/verify/check-networking-firewall

Splitting these into multiple commits, makes it easier to deal with:

Firewall zones

---

pkg/lib/page.css
pkg/machines/app.jsx
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/helpers.js
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/scripts/create_machine.sh
pkg/machines/scripts/install_machine.sh
test/verify/machineslib.py

Allow user to choose already existing storage volume as VM's
destination storage. This property is optional for VM's creation.

machines: Make destination storage a selectable option in VM's creation

---

bots/images/rhel-8-0

Image refresh for rhel-8-0

---

pkg/lib/form-layout.less
pkg/machines/components/storagePools/createStoragePoolDialog.jsx
pkg/machines/components/storagePools/storagePoolOverviewTab.jsx
pkg/machines/libvirt-common.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

Relevant to: https://bugzilla.redhat.com/show_bug.cgi?id=1676594

machines: add support for disk type in storage pool creation dialog

---

bots/image-refresh
bots/task/__init__.py

@marusak 
Any idea how we can test this?

bots: Fix [no-test] for tasks

---

package.json

I checked this locally and it works just fine, but tests tell us if it really works.

package.json: Update jquery package dependency

---

po/ca.po
po/cs.po
po/es.po
po/fr.po
po/ja.po
po/pl.po
po/pt_BR.po
po/sv.po
po/uk.po
po/zh_CN.po

Update translations from Fedora Zanata

[no-test] Update translations from Fedora Zanata

---

bots/task/__init__.py

---
npm-update, renamed before converting the issue to a PR
https://github.com/Gundersanne/cockpit/pull/26
image-refresh, renamed after converting the issue to a PR
https://github.com/Gundersanne/cockpit/pull/25

tasks: Fix [no-test]

---

doc/man/cockpit-ws.xml
src/bridge/cockpitpackages.c
src/bridge/test-httpstream.c
src/bridge/test-websocketstream.c
src/common/cockpitwebresponse.c
src/common/cockpitwebresponse.h
src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/test-webresponse.c
src/common/test-webserver.c
src/ws/cockpitchannelsocket.c
src/ws/cockpithandlers.c
src/ws/cockpitwebservice.c
src/ws/main.c
src/ws/test-channelresponse.c
src/ws/test-handlers.c
src/ws/test-server.c
src/ws/test-webservice.c
test/verify/check-connection

ws: Apply --for-tls-proxy transformations to all URLs

---

src/ws/main.c

Free the context after use. This isn't a big issue in practice, but
valgrind complains about it when running cockpit-ws as part of a unit
test.

ws: Fix GOptionContext memory leak

---

bots/images/fedora-testing

Image refresh for fedora-testing

[no-test] Image refresh for fedora-testing

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx

No tests were added, I can't build a fake OS tree.

machines: fix some issues with OS autodetection

---

test/avocado/checklogin-basic.py
test/avocado/checklogin-raw.py
test/avocado/run-tests
test/avocado/selenium-kdump.py
test/avocado/selenium-machines-consoles.py
test/avocado/selenium-machines-disks.py
test/avocado/selenium-machines-networks.py
test/avocado/selenium-machines-vcpu.py
test/avocado/selenium-storage.py
test/avocado/testlib_avocado/libdisc.py
test/avocado/testlib_avocado/machineslib.py
test/avocado/testlib_avocado/seleniumlib.py

test fixing cherrypicked from https://github.com/cockpit-project/cockpit/pull/11871

test: fix avocado test what causes bad behaviour

---

bots/images/debian-stable

Image refresh for debian-stable

[no-test] Image refresh for debian-stable

---

bots/images/ubuntu-stable

Image refresh for ubuntu-stable

[no-test] Image refresh for ubuntu-stable

---

src/bridge/cockpitpcpmetrics.c
src/common/test-json.c
src/common/test-transport.c
src/ssh/test-sshbridge.c

Small fixes from Coverity scan

---

bots/naughty/rhel-8/11365-lvm-vdo

rhel-8-0: LVM-VDO-LVM sandwich layout broken
Fixes #11365

naughty: Close 11365: rhel-8-0: LVM-VDO-LVM sandwich layout broken

---

bots/tests-scan

These need access to Red Hat internal resources.

bots: Run lorax' vmware and openstack tests on internal machines only

---

bots/images/rhel-8-1

Image refresh for rhel-8-1

---

pkg/machines/scripts/create_machine.sh
pkg/machines/scripts/install_machine.sh
test/verify/files/min-openssl-config.cnf
test/verify/files/mock-range-server.py
test/verify/machineslib.py
tools/debian/control

machines: Allow user to supply URL of ISO file in VM creation dialog

---

bots/tests-scan

Resurrection of #12015, due to my git push pilot error.

Enable lorax cloud tests

---

bots/naughty/rhel-7/7891-selinux-denies-virtlogd-dbus
bots/naughty/rhel-7/7891-selinux-denies-virtlogd-dbus-2
bots/naughty/rhel-8/7891-selinux-denies-virtlogd-dbus
bots/naughty/rhel-8/7891-selinux-denies-virtlogd-dbus-2

check-machines fails due to SELinux denial: virtlogd cannot access D-Bus
Fixes #7891

naughty: Close 7891: check-machines fails due to SELinux denial: virtlogd cannot access D-Bus

---

bots/tests-scan

It's been consistenly failing.
CC @atodorov

bots: Disable lorax/azure test

---

bots/image-create
bots/images/scripts/debian.setup
bots/images/scripts/fedora.setup
bots/images/scripts/lib/build-deps.sh
bots/images/scripts/rhel.setup

bots: Remove the need for a source directory in image-create

---

src/bridge/cockpitdbusinternal.c

This is basically just doing the same thing as a GUnixConnection, so use
that instead.

bridge: remove internal UnixIOStream helper class

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
test/verify/machineslib.py

Resolves: https://github.com/cockpit-project/cockpit/issues/11078
Also in the second commit, I decided to replace round() function with floor() for calculation of memory available. My reasoning is this:
- If we allow memory available to be rounded up, we may show value which exceeds actual available memory. Thus value shown in helpblock is not valid if inputted.
- Spinner in input field of memory already rounds maxValue downwards, so this will bring consistenci into value inputted by spinner vs value inputted by text input field
**The second commit is just my suggestion, I can drop it if we agree it's pointless.**
This PR is WIP so review is not needed yet.

machines: Show available space in VM create dialog

---

bots/run-queue

bots: Let run-queue interpret the github webhook events

---

test/common/testlib.py
test/verify/check-accounts
test/verify/check-dashboard
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-multi-machine
test/verify/check-multi-machine-key
test/verify/check-multi-os
test/verify/check-networking-firewall
test/verify/check-realms
test/verify/check-shutdown-restart
test/verify/check-system-info
test/verify/machineslib.py

Wait when wants to interact with the element.
Also drop redundant checks from the code.

tests: Wait until elements are enabled

---

bots/inspect-queue
bots/run-queue
bots/tests-scan

bots: Adapt to pika 1

---

pkg/machines/libvirt-virsh.js

Support parsing of all volume types, which are already supported.

machines: Fix virsh parser of volumes

---

src/bridge/test-httpstream.c
src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/test-webserver.c
src/ws/main.c

Split out from PR #12141 for easier review and landing.

Various small cleanups for TLS redirection

---

pkg/machines/components/vmOverviewTabLibvirt.jsx
pkg/machines/machines.less
test/verify/machineslib.py

Add tooltip which informs user that changes made to vcpus configuration
of running VM will take affect after shutdown.
https://bugzilla.redhat.com/show_bug.cgi?id=1720076

machines: Add tooltip next to vcpus when VM is running

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

Relevant to https://bugzilla.redhat.com/show_bug.cgi?id=1704853

machines: Disable Create VM button if virt-install command is not available

---

test/common/testlib.py

Helps in figuring out which tests are in a file without having to open
it. Use like this:
```
$./test/verify/check-setroubleshoot -l
TestSelinux.testEnforcingToggle
TestSelinux.testTroubleshootAlerts
```
Inspired by (and mostly stolen from) https://github.com/weldr/lorax/pull/737

test: Add --list option to test/check* scripts

---

bots/naughty/fedora-30/12228-selinux-mdadm-read

Known issue: #12228
Noticed in: https://209.132.184.41:8493/logs/pull-12223-20190704-071010-397e4516-verify-fedora-30/log.html

bots: Add naughty for mdadm AVC

---

pkg/lib/listing.less
pkg/lib/page.css
pkg/shell/switcher.less
pkg/users/users.css
src/base1/patternfly-overrides.less

A collection of fixes to address #12210.

Pf4ish fixups

---

bots/image-refresh

bots: Add missing test triggers for selenium image refreshes

---

pkg/apps/application.css
pkg/lib/journal.css
pkg/lib/listing.less
pkg/lib/page.css
pkg/lib/plot.css
pkg/lib/table.css
pkg/shell/shell.less
src/base1/patternfly-overrides.less

The next round of fixups to better style to PF4, round 2.
Addresses https://github.com/cockpit-project/cockpit/issues/12210.

Pf4ish fixups, round 2

---

pkg/selinux/setroubleshoot-view.jsx
test/verify/check-setroubleshoot

selinux: Make shell script really a script

---

package.json
pkg/machines/machines.less

package.json: Update patternfly-react package dependency

---

test/avocado/run-tests
test/avocado/selenium-firewalld-zones.py

tests for firewalld zones abilities, to be able to test them via various browsers

test: firewalld - zones: basic tests for selenium

---

bots/task/__init__.py

Our machines are back now.
Reverts cockpit-project/cockpit#12350

Revert "bots: Temporarily switch internal image server"

---

pkg/lib/cockpit-components-modifications.css
pkg/selinux/setroubleshoot-view.jsx
pkg/selinux/setroubleshoot.css

selinux: Move modifications above alerts

---

pkg/lib/machine-info.js
pkg/systemd/hw-detect.js
pkg/systemd/hwinfo.jsx
test/verify/check-system-info

The new module is just a patch for showing DIMM information which was previously done by Andrew Ly (commit id: ce4d260) on behalf of DELL Technologies.

Show DIMM information on hardware page

---

bots/tests-scan

bots: Always pass TEST_PROJECT to tests-invoke no.2

---

package.json

package.json: Update redux package dependency

---

src/bridge/cockpitpcpmetrics.c

Updated description: This ignores broken archives and is able to find and read compressed archives.

pcp: More robust and complete archive finding

---

pkg/storaged/dialog.jsx
pkg/storaged/storage.css

Style the inline danger warning about erasing a device.
Fixes #12452

storaged: style inline format warning

---

bots/machine/machine_core/directories.py
bots/machine/machine_core/ssh_connection.py

This reintroduces the change from PR #12427. This got reverted in #12448 as it broke the selenium tests (my bad!)
The second commit here fixes selenium.

Fix running tests in toolbox

---

pkg/systemd/service-details.jsx

If static service is active then enable stopping/restarting and
reloading.
@mvollmer does this make more sense for you?

services: Enable restarting static services

---

po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/fr.po
po/it.po
po/ja.po
po/ko.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

https://bugzilla.redhat.com/show_bug.cgi?id=1689977

po: Update translations from Zanata

---

tools/cockpit.spec

spec: Add alternative docker-ce dependency to cockpit-docker

---

pkg/machines/components/storagePools/createStoragePoolDialog.jsx
pkg/machines/components/storagePools/storagePoolOverviewTab.jsx
pkg/machines/libvirt-common.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

https://bugzilla.redhat.com/show_bug.cgi?id=1676600

machines: extend create storage pool dialog to support LVM pools

---

pkg/machines/app.jsx
pkg/machines/components/networks/createNetworkDialog.css
pkg/machines/components/networks/createNetworkDialog.jsx
pkg/machines/components/networks/networkList.jsx
pkg/machines/components/networks/utils.js
pkg/machines/helpers.js
pkg/machines/libvirt-dbus.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

https://bugzilla.redhat.com/show_bug.cgi?id=1672755

machines: Implement creation of Virtual Networks

---

pkg/machines/components/storagePools/storagePool.jsx
pkg/machines/components/storagePools/storagePoolDelete.css
pkg/machines/components/storagePools/storagePoolDelete.jsx
test/verify/check-machines-dbus

https://bugzilla.redhat.com/show_bug.cgi?id=1731865

machines: Limit pool deletion if pool/volumes are used by any VM

---

pkg/systemd/service-details.jsx
test/verify/check-services

... and only allow to reload units that support it.

Add more actions into services

---

bots/task/testmap.py

see https://github.com/weldr/lorax/pull/792

Add fedora-30/tar test context for weldr/lorax

---

HACKING.md

Current master:
https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#working-on-your-local-machine-web-server-resources
With this commit:
https://github.com/marusak/cockpit/blob/spacing_is_everything/HACKING.md#working-on-your-local-machine-web-server-resources

A very important fix :)

---

HACKING.md

Noticed on https://github.com/cockpit-project/cockpit-project.github.io/pull/271
Although I don't want to send PRs for one typo but when it is getting to the website we should fix it :)

Fix typo in HACKING

---

bots/image-refresh

Lets also make sure that these contexts are not broken by running those tests

bots: Add new contexts on image-refreshes

---

pkg/docker/docker.css
pkg/lib/cockpit-components-listing.jsx
pkg/lib/cockpit-components-modifications.css
pkg/lib/cockpit-components-modifications.jsx
pkg/lib/listing.less
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/check-networking-firewall
test/verify/check-system-info
test/verify/storagelib.py

Replace <caption> element from cockpit lists because of the following
reasons:
- it's buggy in WebKit
- it skips the a11y tree for headings
- we overload it with stuff that it isn't intended for
Fixes #12511
Related to https://bugs.webkit.org/show_bug.cgi?id=187903.

Fix issue with jumping action buttons in WebKit browsers

---

doc/guide/packages.xml
pkg/playground/manifest.json.in
pkg/playground/preloaded.html
pkg/playground/preloaded.js
pkg/shell/base_index.js
pkg/shell/index.html
pkg/shell/indexes.js
pkg/systemd/manifest.json.in
src/base1/test-http.js
test/verify/check-active-pages
test/verify/check-pages
webpack.config.js

We eventually want to preload arbitrary pages so that they can produce notifications right after login.

shell: Preload iframes based on manifests

---

pkg/lib/packagekit.js

PackageKit is sometimes installed on ostree systems, but that doesn't
mean we can install packages with it.

lib/packagekit: Don't ever use PackageKit when /usr is mounted read-only

---

bots/naughty/rhel-8/12539-libvirtd-crash-domain-destroy-altern

Noticed @ https://209.132.184.41:8493/logs/pull-12552-20190816-092727-5a34b0f7-cockpit-project-cockpit-rhel-8-1/log.html

bots: Make naughty a bit more general

---

bots/task/log.html
test/common/testlib.py

Because that's what we do manually anyway.

test: Retry every failure, not just the ones we deem flakes

---

package.json

package.json: Update uuid package dependency

---

bots/naughty/rhel-8/12057-selinux-dhclient-tmpfs

avc: denied { write } for comm="dhclient" name="NetworkManager" dev="tmpfs"
Fixes #12057

naughty: Close 12057: avc: denied { write } for comm="dhclient" name="NetworkManager" dev="tmpfs"

---

pkg/lib/cockpit-components-terminal.jsx
pkg/systemd/terminal.jsx

This method is being obsoleted, see https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

terminal: Remove componentWillUpdate method

---

bots/task/testmap.py

bots: Declare rhel-7-8 image

---

bots/task/testmap.py

bots: Add new contexts in testmap

---

bots/image-refresh

@martinpitt am I missing something or is something not correct?

bots: Add new triggers to image-refresh

---

bots/image-naughty
bots/task/test-policy
bots/tests-policy

This is a leftover from commit 534026ab4ee8 two years ago.

bots: Clean up obsolete image-naughty

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx

I noticed these two string that they are not translated.

machines: Translate strings

---

pkg/lib/cockpit-components-select.jsx
pkg/lib/cockpit-components-terminal.jsx
pkg/machines/components/consoles.jsx
pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/vmDisksTabLibvirt.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/machines/components/vnc.jsx

Most of these things are machines related. @KKoukiou can you please verify that it works correctly and that these changes make sense?

Remove obsolated componentWill... methods

---

tools/cockpituous-release

tools: Add Fedora 31 to release script

---

pkg/machines/components/aggregateStatusCards.jsx
test/verify/check-machines-dbus
test/verify/machineslib.py

machines: fix string translations in status cards

---

package.json

package.json: Update deep-equal package dependency

---

test/verify/packagelib.py

Commit 828f0788be regressed on ubuntu-1804, so revert the "wait for NM
to become online" hack there again, and go back to the old way. As
ubuntu-stable is not structurally different, use the same (old) hack on
these two, until this gets debugged properly.

test: Fix PackageKit tests on ubuntu-1804 again

---

pkg/lib/service.js
pkg/subscriptions/get_monotonic_start.py
pkg/subscriptions/insights.jsx
pkg/subscriptions/main.js
pkg/subscriptions/subscriptions-client.js
pkg/subscriptions/subscriptions-register.jsx
pkg/subscriptions/subscriptions-view.jsx
pkg/systemd/host.js
pkg/systemd/index.html
test/verify/check-subscriptions
test/verify/files/mock-insights

RHEL7 - subscriptions: Add support for Red Hat Insights

---

src/tls/test-connection.c

Set socket buffer of the ws receiving end to a small value and try to
write a large block, so that `connection_write()` runs into a `PARTIAL`
write.
----
I split this out of PR #12461. It's much less intrusive and useful to have at an early point, to make sure this does not regress.

tls: Add unit test for partial writes

---

src/tls/test-server.c

This test was brittle across different distributions, GnuTLS releases,
and architectures. We are not testing the specifics of GnuTLS here, we
just care about TLS requests failing with expired certificates. So don't
expect precise error codes at precise times, but just that the TLS
handshake or first read/write fails when expected.

tls: Robustify /server/tls/client-cert-expired test

---

package.json
pkg/lib/cockpit-components-listing.jsx
pkg/lib/listing.less
pkg/machines/components/diskAdd.jsx
pkg/machines/components/storagePools/storagePoolVolumesTab.css
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/components/storagePools/storageVolumeDelete.css
pkg/machines/components/storagePools/storageVolumeDelete.jsx
pkg/machines/components/vmDisksTab.jsx
pkg/machines/components/vmDisksTabLibvirt.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/machines/machines.less
test/verify/check-machines-dbus
test/verify/machineslib.py
webpack.config.js

Replace our custom compact tables with the Table component from PF-4 react

---

test/run

Add test/run

---

test/verify/check-docker
test/verify/check-docker-storage

See https://github.com/cockpit-project/cockpit/pull/12755

tests: Adjust tests since atomic package is present again

---

pkg/machines/components/nic.css
pkg/machines/components/nicAdd.jsx
pkg/machines/components/nicBody.jsx
pkg/machines/components/nicEdit.css
pkg/machines/components/nicEdit.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/machines/libvirt-dbus.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

Some part of dialog body is shared with "Virtual Network Interface Settings" edit dialog.
@garrett @andreasn what do you think about the design?
**When VM is running, option to persistently/non-persistently attach device is visible:**

machines: Implement adding virtual network interfaces to VM

---

.eslintrc.json
pkg/apps/application.jsx
pkg/packagekit/updates.jsx
src/ws/login.js

and fix eslint warning we have on master

Validate ref on target=_blank

---

package.json
webpack.config.js

We don't have any more angular anywhere

package.json: Drop ng-cache-loader

---

src/bridge/bridge.c
tools/glib.supp
tools/gnutls.supp
tools/polkit.supp

I was looking into our remaining valgrind suppressions, this attaches/updates bug res.

Some more valgrind suppression updates

---

pkg/networkmanager/firewall-client.js

This way the firewall page picks up any zones added at runtime through
means other than the page itself.
Fixes #12759

firewall: Listen to zones changing interface or source

---

test/verify/check-networking-firewall

Thanks to @mvollmer  for the detective work :)
---
Also triggering f31, since that has firewall > 0.7

Firewall custom services test wait zones

---

pkg/dashboard/index.html
pkg/playground/translate.html
test/verify/check-pages

This is workaround for https://github.com/cockpit-project/cockpit/issues/12840
Before this PR:
```
$ autogen && make update-po && grep -r fuzzy po/cockpit.pot | wc -l
2
```
With this PR:
```
$ autogen && make update-po && grep -r fuzzy po/cockpit.pot | wc -l
1
```
The other fuzzy string was causing problems and we could not upload it to Zanata.

Change some strings around

---

.eslintrc.json
pkg/docker/client.js
pkg/docker/containers-view.jsx
pkg/networkmanager/firewall.jsx
pkg/storaged/content-views.jsx
pkg/storaged/storage-controls.jsx

I think it is good to have this rule enabled, so I did some small tweaks in current code and we can now enforce it.

eslint: Check that elements have key prop in arrays and arrow functions

---

test/common/testlib.py

See https://bugzilla.redhat.com/show_bug.cgi?id=1753991

test: Ignore SELinux rhsmd regression on RHEL 8.1

---

test/common/testlib.py
test/verify/check-terminal

Picked from  #12579 as it was getting big.

tests: key_press tweaks

---

test/selenium/run-tests
test/selenium/selenium-machines-basic.py
test/selenium/selenium-machines-disks.py
test/selenium/selenium-machines-networks.py
test/selenium/selenium-machines-storage-pool.py
test/selenium/testlib_avocado/libdisc.py
test/selenium/testlib_avocado/machineslib.py

* Add some cases about storage pool
* 'testNetworkInfo' will not attach-interface
* Add some resource for run_test when using edge, otherwise send_keys() can not send correct string to the 'Operating System' input of creation dialog

test: Some fixes for cockpit-machines testcases

---

tools/test-static-code

We can't fix issues in bots/ from here, so we shouldn't go looking for
them.

tools: Don't run pyflakes in bots/

---

pkg/shell/base_index.js
test/verify/check-pages

a11y: Add `lang` attribute to every iframe's html tag

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/selenium/testlib_avocado/machineslib.py
test/verify/machineslib.py

All these commits where part of 12716, and where split to separate PR to ease the review.

machines: Mutliple small fixes in Create VM dialog

---

test/verify/check-networking-firewall

They are only reliable since #12806

test: Don't check Firewall rule counts on rhel-8-1-distropkg

---

src/bridge/cockpitpolkitagent.c
src/common/cockpitloopback.c

GSimpleAsyncResult got deprecated in GLib 2.46 in favor of GTask
(available since 2.36).
This will enable us to bump our glib requirement to ≥ 2.46 in the future
(otherwise building fails because of -Wdeprecated).

polkitagent, loopback: Port deprecated GSimpleAsyncResult to GTask

---

package.json

package.json: Update bootstrap-select package dependency

---

test/run
tools/make-bots

test: Prepare bots at beginning of test/run

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/create-vm-dialog/createVmDialog.less
pkg/machines/getOSList.py
pkg/machines/scripts/create_machine.sh
pkg/machines/scripts/install_machine.sh
test/verify/machineslib.py

Split some commits out of https://github.com/cockpit-project/cockpit/pull/12716

machines: Refactor Create VM dialog and allow downloading an OS media by selecting the OS name

---

pkg/storaged/client.js
pkg/storaged/storage-controls.jsx

This is simpler re change notifications.

storage: Handle permissions in the client

---

pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
pkg/networkmanager/index.html
pkg/networkmanager/networking.css
test/selenium/selenium-firewalld-zones.py
test/selenium/selenium-firewalld.py
test/verify/check-networking-firewall

release:
The firewall page was redesigned. Instead of having separate listings for services and zones, the services are now listed per zone. This aims to make the relationship between zones and services clearer.

firewall: ui restructuring

---

pkg/lib/page.css
pkg/shell/index.html
pkg/shell/shell.less
pkg/shell/switcher.less

PatternFly 4 has changed to suggest a dark menu, similar to the one we had a while back. Usability studies were cited to show that people found the navigation to be clearer when it looked a bit separate with color swaps.

nav: Adjust color to match PF4's new dark nav

---

pkg/lib/cockpit-components-table.jsx
pkg/lib/cockpit-components-table.less
pkg/lib/listing.less
pkg/machines/components/storagePools/storagePoolVolumesTab.jsx
pkg/machines/components/vmDisksTab.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/systemd/hwinfo.jsx
test/verify/check-machines-dbus
test/verify/check-system-info
test/verify/machineslib.py

Implement a parallel implementation of Listing based on PF Tables
Start moving one by one our lists to the new ListingTable.

Port our Listing component to PF4 Tables

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/machines/components/diskAdd.jsx
pkg/machines/components/vmOverviewTabLibvirt.jsx
pkg/machines/libvirt-virsh.js
pkg/machines/machines.less
pkg/machines/xmlCreator.js
po/Makefile.am
po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/fr.po
po/it.po
po/ko.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po
test/verify/check-machines-virsh
test/verify/machineslib.py
tools/cockpit.spec

RHEL 7.8 backports

---

pkg/networkmanager/manifest.json.in

Thanks in advance for fixing this minor typo.

Fix typo: inteface -> interface

---

src/tls/test-server.c

Add a test to ensure that we can't wedge the cockpit-tls server by
blocking during the handshake phase (which could even theoretically
happen by accident if a connection is dropped, for example).
This was a bug before moving to the threaded connection model.  The
lock-up eventually cleared when hitting the gnutls handshake timeout,
but 40 seconds is a long time for the server to be blocked from handling
any other incoming requests.

tls: add test for blocked TLS handshake

---

pkg/storaged/fsys-panel.jsx
pkg/storaged/nfs-details.jsx
pkg/storaged/nfs-panel.jsx
pkg/storaged/storage-controls.jsx
pkg/storaged/storage.css
test/verify/check-storage-mounting
test/verify/check-storage-nfs

storage: Utilize PF4 Progress Bar implementation for FS and NFS size bars

---

src/ws/Makefile-ws.am

This doesn't actually change anything in the packages, it just makes it easier to change the units in the future (like PR #12972)

ws: Factorize systemd units in Makefile

---

pkg/networkmanager/interfaces.js
test/selenium/selenium-firewalld.py
test/verify/check-networking-firewall

firewall: Show number of active zones on the network page

---

pkg/networkmanager/interfaces.js
tools/cockpit.spec
tools/debian/control

Fix various crashes spotted by the Selenium Edge tests.

networkmanager: Crash fixes

---

test/README.md
test/common/testlib.py
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-journal
test/verify/check-kdump
test/verify/check-networking-firewall
test/verify/check-storage-format
test/verify/check-storage-luks
test/verify/check-storage-resize
test/verify/check-system-info

tests: Adjust for new rhel-8-2 OS image

---

src/ws/login.css
src/ws/login.html

login: Move labels above inputs; fix truncation

---

pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css
test/verify/check-networking-firewall

firewall: Automatically add cockpit firewall service when activating a zone

---

test/selenium/selenium-base.py
test/selenium/selenium-firewalld.py
test/selenium/testlib_avocado/seleniumlib.py

Split out from PR #13052. These are the easy ones which should improve things a little.

Selenium test fixes

---

.eslintrc.json
pkg/apps/application-list.jsx
pkg/apps/application.jsx
pkg/docker/storage.jsx
pkg/shell/index.html
pkg/sosreport/index.html
pkg/storaged/mdraid-details.jsx
pkg/storaged/vgroup-details.jsx

When the image is purely decorative, then `alt=''` is acceptable.

a11y: Every image must have an alt attribute

---

test/selenium/selenium-tuned.py
test/selenium/testlib_avocado/seleniumlib.py

In particular this tries to address the frequent [tuned failure on Edge](https://209.132.184.41:8493/logs/pull-13064-20191031-093636-7a694ebd-cockpit-project-cockpit--fedora-30-selenium-edge/log.html#34). ([second example](https://209.132.184.41:8493/logs/pull-13074-20191031-100202-cb3ad652-cockpit-project-cockpit--fedora-30-selenium-edge/log.html)) It's not at all clear what happens there -- the dialog is clearly present in both the sceenshot and the .html.

Even more selenium fixes

---

po/cs.po

Testing https://github.com/cockpit-project/cockpituous/pull/299

Test po-refresh without old client

---

pkg/lib/cockpit-components-listing.jsx
pkg/lib/listing.less
pkg/networkmanager/firewall.jsx
test/selenium/selenium-firewalld-zones.py
test/selenium/selenium-firewalld.py
test/verify/check-networking-firewall

Firewall accessibility

---

pkg/realmd/README.md
test/verify/check-packagekit
test/verify/check-realms

See https://github.com/cockpit-project/bots/pull/208

test: Use new services image instead of candlepin and ipa

---

pkg/shell/index.html

shell: Label search input

---

examples/ocserv/manifest.json
examples/ocserv/ocserv.html

Fixes #11721
For testing see https://github.com/cockpit-project/cockpit/issues/11721#issuecomment-551011422
I tested it that it loads the page and does not oops. I see in console `occtl executable was not found` which is good indicator that cockpit api is there.

Do not use requirejs in example

---

test/common/cdp.py
test/common/chromium-cdp-driver.js
test/common/test-functions.js
test/common/testlib.py
test/verify/check-login
test/verify/check-menu
test/verify/machineslib.py

Some tests mods to prepare for Firefox testing

---

pkg/machines/components/desktopConsole.jsx
pkg/shell/index.html
pkg/shell/simple.html
pkg/systemd/logs.js

See https://developers.google.com/web/tools/lighthouse/audits/noopener

security: Add rel="noopener noreferrer" to links

---

test/selenium/selenium-machines-basic.py
test/selenium/selenium-machines-storage-pool.py
test/selenium/testlib_avocado/machineslib.py

* Change the locator of 'Storage Pool' button in machines page
* Some enhancement

Some modifications in selenium machines cases

---

pkg/networkmanager/firewall.jsx
pkg/networkmanager/networking.css

firewall: Add help for the format of source addresses

---

pkg/machines/components/nicEdit.jsx

machines: Reset EditNICComponent after closing

---

test/selenium/selenium-firewalld-zones.py
test/selenium/selenium-firewalld.py
test/selenium/selenium-hwinfo.py
test/selenium/selenium-tuned.py
test/selenium/testlib_avocado/seleniumlib.py

should help stability  and possible to run some tests, what now are not able to run directly

test: fix missing sequesnces before executing commands via machine

---

src/base1/cockpit.js
src/base1/test-spawn.js

The WebSocket protocol only allows messages up to 128K. Therefore
data larger than that size, such as file write data, or input into
processes' stdin need to be broken into smaller chunks.
Lets not rely on the caller of various cockpit.xxxx() functions
to do that. We know the places where it's necessary.
Issue #12338

base1: Break input into small blocks

---

pkg/storaged/format-dialog.jsx
pkg/storaged/fsys-tab.jsx
test/verify/check-storage-mdraid
test/verify/check-storage-mounting

UDisks2 doesn't handle them well.

storage: Disallow duplicate mount points

---

pkg/playground/react-demo-cards.jsx
pkg/playground/react-patterns.html
pkg/playground/react-patterns.js

playground: PatternFly 4 Cards

---

test/README.md
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-journal
test/verify/check-kdump
test/verify/check-packagekit
test/verify/check-services
test/verify/check-storage-format
test/verify/check-storage-luks
test/verify/check-storage-resize
test/verify/check-system-info
test/verify/machineslib.py
test/verify/packagelib.py

---
the three remaining failures should be solved by https://github.com/cockpit-project/bots/pull/259 so added blocked for that

test: Add centos-8-stream

---

pkg/systemd/reporting.jsx
test/verify/check-journal
test/verify/files/cockpit_event.conf
test/verify/files/workflow_Cockpit.xml

See commits.
Fixes https://github.com/cockpit-project/cockpit/issues/13176

Use simpler workflow for ABRT report testing (and more)

---

tools/cockpit.spec

Applying this hack really isn't optional, cockpit does not work without
it if SELinux is active. Thus remove the condition, and add the
necessary package dependencies to ensure that restorecon, semanage, and
friends are available.
Only add the new dependencies on release builds though, not on CI
builds. Our test images already have the necessary packages (otherwise
fedora-{30,31} tests would completely fail), but our images' cockpit/ws
container instances don't -- and we also don't need the %post in a
container. This hack can be dropped again once a recent selinux-policy
lands in Fedora 30, i. e. in a few weeks at most.
Drop the "fedora == 29" check, as we haven't released to Fedora 29 for a
while already, and it is EOL now.
Fixes #13183
https://bugzilla.redhat.com/show_bug.cgi?id=1777001

tools: Fix SELinux policy update hack in %post

---

test/selenium/README.md
test/selenium/run-tests

See <https://github.com/cockpit-project/bots/pull/281>.

test: Use selenium containers on services image

---

test/avocado/README.md
test/avocado/run-tests

See <https://github.com/cockpit-project/bots/pull/281>.
Cherry-picked from master commit e7dceb089b7.

[rhel-7.8] test: Use selenium containers on services image

---

test/avocado/README.md
test/avocado/run-tests

See <https://github.com/cockpit-project/bots/pull/281>.
Cherry-picked from master commit e7dceb089b7.

[rhel-8-appstream] test: Use selenium containers on services image

---

test/avocado/README.md
test/avocado/run-tests

See <https://github.com/cockpit-project/bots/pull/281>.
Cherry-picked from master commit e7dceb089b7.

[rhel-8.1] test: Use selenium containers on services image

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
pkg/storaged/fsys-tab.jsx

Covscan was complaining about these. Lets just fix it to keep it a bit happier.

No need to check if item exists when already validated

---

pkg/machines/components/vmnetworktab.jsx

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1777201

machines: Fix detach NIC button being disabled when VM is running

---

src/tls/README.md

We forgot to keep this file updated with the recent work of  running
cockpit-ws as different user, and adding client certificate
authentication.

tls: Update README

---

src/ws/cockpitauth.c
src/ws/cockpitwebservice.c

The rhost is not very useful and often wrong with proxies.

ws: Show user name in session log messages

---

src/tls/connection.c

Change commented-out debug statements into debug statments
conditionalised by domain.  We somehow missed this when adding domains.
Remove another // comment with code and replace it with a
English-language explanation of what's going on.
Remove a 'XXX' comment that suggested that perhaps a gnutls_bye() should
be added.  This was written before "bye" handling was added to the
buffer handling code.
There are absolutely no functional changes here.  It's all comments or
(in the case of debugging) disabled code.

tls: clean up comments in connection.c

---

pkg/subscriptions/insights.jsx
pkg/subscriptions/subscriptions-client.js

PackageKit is missing even more than the insights-client in a default
install.

subscriptions: Avoid PackageKit when installing insights-client

---

pkg/machines/libvirt-dbus.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

machines: Fix device selection for virtual networks

---

pkg/machines/components/nicAdd.jsx
pkg/machines/components/nicBody.jsx
pkg/machines/components/nicEdit.jsx
pkg/machines/components/vmnetworktab.jsx
pkg/machines/libvirt-common.js
pkg/machines/libvirt-dbus.js
pkg/machines/xmlCreator.js
test/verify/check-machines-dbus

machines: Enable interface type option 'bridge' for NICs

---

pkg/systemd/index.html

Fixes #13285
Screenshot after the fix:

system: Fix alignment issues in shutdown/restart dialog

---

pkg/systemd/index.html
pkg/systemd/overview-cards/configurationCard.jsx
pkg/systemd/overview-cards/configurationCard.less
src/base1/patternfly-overrides.less

Before:
After:
And with errors:

system: Fixes in Change System Time dialog

---

tools/cockpit.spec

RHEL 8.2 finally has a current SELinux policy for cockpit, see
<https://bugzilla.redhat.com/show_bug.cgi?id=1771414>. As a result, we
can finally drop the hack in `%post`, as this really shouldn't get into
an official release.

tools: Drop SELinux policy hack in cockpit.spec

---

pkg/lib/cockpit-components-privileged.jsx
pkg/systemd/hwinfo.jsx
pkg/systemd/overview-cards/configurationCard.jsx
pkg/systemd/overview.jsx
test/verify/check-login
test/verify/check-shutdown-restart
test/verify/check-system-info

This provides some groundwork and fixes the configuration card. This is the React half, I'll send a separate PR to fix the jQuery bits (that needs fixing `update_privileged()`).
Fixes React half of #13320

system: Fix privileged React UI elements

---

pkg/lib/patterns.js
pkg/realmd/operation.js
pkg/systemd/init.js
pkg/users/local.js
test/verify/check-accounts
test/verify/check-realms
test/verify/check-roles

This fixes the other half of issue #13320, for the jQuery elements.

Let update_privileged() use the disabled attribute instead of class

---

test/verify/check-login

This has similar package versions as RHEL 8.1.

test: Add expected testSELinuxRestrictedUser messages on centos-8-stream

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx
test/verify/machineslib.py

machines: Change Import VM dialog title and buttons (fixes #12614)

---

.gitignore
doc/i18n.md
po/Makefile.am
po/cs.po
po/es.po
po/uk.po
po/zanata.xml

Fixes: #13319
I did local run:
1. Updated `.pot` file: https://github.com/marusak/cockpit-weblate/commit/59ae9ad00d41a94dce7436aafac0f8d50db63847
2. Created refresh: https://github.com/marusak/cockpit/pull/24 (again, please ignore all but the last commit)
When I get ack, I'll run po-refresh.

po: Switch from Zanata to Weblate

---

HACKING.md

This is useful for validating PRs like #13376

HACKING: Document how to use locally built cockpit-ws

---

src/bridge/bridge.c
src/ws/cockpitauth.c
src/ws/cockpitwebservice.c
src/ws/cockpitwebservice.h

@martinpitt, we had been talking about this.

ws: Use XDG_SESSION_ID to identify sessions in log messages

---

src/common/cockpitwebserver.c
src/common/cockpitwebserver.h
src/common/test-webserver.c
test/verify/check-connection

Backport the new tests and fix for https://bugzilla.redhat.com/show_bug.cgi?id=1785509 from master.

common: Fix large requests with TLS

---

po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/fr.po
po/it.po
po/ja.po
po/ko.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

Translations refresh from Weblate

---

package.json
pkg/lib/page.css
pkg/systemd/overview.jsx
test/verify/check-login
test/verify/check-shutdown-restart

overview: re-implenent shutdown/restart with split button

---

pkg/systemd/graphs.less

I have been working on fixing #13287 with just CSS, but was not successful. 
Meanwhile, I did have several fixes that are good to merge regardless, so I've split them out to their own branch for merging.
Actual graph crop fixes will probably need to be fixed with JavaScript, not just CSS.

Graph page layout fixups

---

pkg/lib/cockpit-components-privileged.jsx
pkg/lib/patterns.js
pkg/machines/app.jsx
pkg/playground/test.html
pkg/playground/test.js
pkg/shell/manifest.json.in
pkg/shell/privileges.js
pkg/systemd/init.js
pkg/systemd/overview-cards/configurationCard.jsx
pkg/users/local.js
src/bridge/cockpitpeer.c
test/verify/check-realms
test/verify/check-reauthorize
test/verify/check-system-info

So that pages re-initialize themselves and pick up on the reduced
permissions.

shell: Reload everything when dropping privileges

---

pkg/systemd/graphs.js
pkg/systemd/overview-cards/usageCard.jsx
test/verify/check-metrics

Trim strings in Usage card

---

pkg/systemd/graphs.less

Otherwise graphs do not properly show up.
Fixes #13380

graphs: Include PF4 components

---

po/cs.po
po/fr.po
po/ja.po
po/ko.po
po/pl.po
po/ru.po
po/zh_CN.po

Update translations from Fedora Weblate

Update translations from Fedora Weblate

---

pkg/systemd/overview.less

overview: Don't allow the header to shrink

---

pkg/lib/listing.less
pkg/shell/shell.less
pkg/systemd/graphs.less
pkg/systemd/overview-cards/systemInformationCard.less
pkg/systemd/overview.less
pkg/systemd/services.less
src/websocket/websocketconnection.c
test/verify/check-metrics

My plan is to do a 211.1 release with these.

Backport fixes for rhel-8.2 branch

---

package.json
pkg/docker/docker.js
pkg/lib/cockpit-components-terminal.jsx
pkg/lib/console.css
pkg/machines/machines.less
pkg/systemd/terminal.jsx
test/selenium/selenium-base.py
test/verify/check-pages
test/verify/check-realms
test/verify/check-terminal

Was there a good reason that resetting would disconnect channel and create new? 
Fixes #12948

terminal: Update to xterm v4

---

pkg/storaged/content-views.jsx
pkg/storaged/lvol-tabs.jsx
pkg/storaged/swap-tab.jsx
test/verify/check-storage-lvm2

They should all be in the menu now, but got left behind.

storage: Less buttons in the content tabs

---

test/verify/check-login
test/verify/check-packagekit
test/verify/check-realms
test/verify/check-reauthorize
test/verify/check-shutdown-restart

Cockpit 211 made it onto the rhel-8-2 image now:
https://github.com/cockpit-project/bots/pull/469

test: Update rhel-8-2-distropkg special cases for cockpit 211

---

test/verify/check-packagekit
test/verify/check-realms
test/verify/check-storage-nfs
test/verify/check-storage-vdo
test/verify/packagelib.py
test/verify/storagelib.py

Split out from, and preparation for PR #13456

Various test fixes in preparation for making packagekit tests non-destructive

---

pkg/apps/application.jsx

eslint-plugin-react ≥ 7.18 complains about the wrong indentation.

apps: Fix indentation

---

pkg/apps/application.jsx

eslint-plugin-react ≥ 7.18 complains about the wrong indentation.

Fix indentation

---

po/cs.po
po/fr.po
po/ja.po
po/ko.po
po/zh_CN.po

https://bugzilla.redhat.com/show_bug.cgi?id=1754958

Update translations from Weblate

---

test/common/chromium-cdp-driver.js

PatternFly's usage of Emotion causes tons of "Refused to apply inline
style" errors, which are unfortunately hard to work around. So at least
filter them out, which will bring our test logs back from ~ 8 to ~ 1 MB
and helps developers to not get drowned in log spam.
With unminified webpacks (`--enable-debug`, what we run in CI on
fedora-30) we can reliably identify that particular bug. Without a stack
trace, just show the message once per test. We don't want to ignore it
entirely as that would hide inline styles that we accidentally bring in
from somewhere else.

test: Suppress "Refused to apply inline style" logs

---

test/common/firefox-cdp-driver.js

Similar to what commit 3784683d5bf9 did on Chromium. However, Firefox
doesn't show a stack trace for these errors even with debug symbols, so
only do the rate-limiting part. Also the message is slightly different.

test: Suppress "Refused to apply inline style" logs for Firefox

---

pkg/machines/machines.less
pkg/shell/shell.less
test/verify/check-login
test/verify/check-networking-basic
test/verify/check-services
tools/npm-release-time
tools/test-static-code

Add some missing verify tests, fix build failure with less ≥ 3.11

---

pkg/storaged/fsys-tab.jsx
pkg/storaged/lvol-tabs.jsx
pkg/storaged/storage.css

Fixes #13485
WA fro https://github.com/patternfly/patternfly-react/issues/3700
With this PR:
****
****
****
****

storage: fix bad layout of alert warnings

---

pkg/networkmanager/index.html
pkg/networkmanager/interfaces.js
pkg/networkmanager/networking.css
test/verify/check-networking-bond

Implements https://github.com/cockpit-project/cockpit/issues/842

Inline doc in networking bonds

---

test/selenium/selenium-machines-basic.py

This is just lazy way how to get logs. When I get logs, then I'll push here proper commit.

test: Wait default time for machine to reboot 

---

pkg/machines/components/deleteResource.jsx
test/verify/check-machines-dbus

Also show a spinner indicating that the operation is in progress.
Fixes #13213

machines: Disable 'Remove' button after attempting to remove a Disk/NIC

---

pkg/lib/form-layout.less

lib/forms: Remove margin from labels

---

pkg/networkmanager/firewall-client.js
pkg/networkmanager/firewall.jsx
pkg/networkmanager/interfaces.js
test/verify/check-networking-firewall

Sadly it's no longer possible the list the services as an unprivileged user. I think this got more restricted since a few months ago :/
---

firewall: Fix unprivileged version

---

test/verify/check-terminal

I ran this test a few time in a row on the same VM without any problem.

test: Mark terminal test as nondestructive

---

test/verify/check-realms
test/verify/check-storage-nfs

More nondestructive package tests

---

test/verify/check-sosreport

test: Make check-sosreport nondestructive

---

test/verify/check-machines-dbus
test/verify/machineslib.py

With this approach we are one step closer to being able to run machine
tests on a existing testbed.
Running tests as likely some are still broken.

test: Copy image into VM instead of attaching it as disk

---

test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-login
test/verify/check-networking-firewall
test/verify/check-system-info
test/verify/machineslib.py

This needs to land in lockstep with https://github.com/cockpit-project/bots/pull/569

test: Adjust for fedora-testing moving to Fedora 31

---

test/verify/check-machines-dbus
test/verify/machineslib.py

This is the first batch. There are still networking and storage related machine tests. Those will come in another batches.
It covers 15 tests from total 30 machines-dbus tests.

Make machines tests nondestructive (batch no.1)

---

test/verify/run-tests

See individual commits for details

test: Restart global machine if it stops being reachable

---

test/verify/check-packagekit

test: Robustify check-packagekit

---

test/verify/check-machines-dbus
test/verify/machineslib.py
test/verify/packagelib.py

There are only 4 tests left, all of which do `addDisk`.
Namely:
- testAddDisk
- testCreate
- testStoragePoolsCreate
- testStorageVolumesCreate

Nondestructive machines tests (no.3)

---

test/verify/check-storage-lvm2

test: debian-stable now has UDisks2 with LVM2 support

---

test/common/testlib.py
test/verify/check-metrics
test/verify/check-storage-basic
test/verify/check-storage-ignored
test/verify/check-storage-lvm2
test/verify/check-storage-partitions
test/verify/check-storage-used
test/verify/storagelib.py

Use the new RAM disk introduced in PR #13646
Also fix test failure on master that got introduced by unlucky timing (two parallel PRs)

Make some storage tests nondestructive

---

pkg/apps/application-list.jsx
pkg/apps/application.jsx

Also use PF4 icon for the refresh button and give it an aria label.

apps: Port Applications page to PF4 buttons

---

test/verify/packagelib.py

Use a dummy interface instead of relying on libvirt's default network
virbr0. This decouples this hack from the Machines tests, drops the
dependency on virbr0 being up, and stops multilating that.

test: Robustify NM online hack for Ubuntu

---

test/README.md
test/verify/check-docker
test/verify/check-docker-storage
test/verify/check-journal
test/verify/check-kdump
test/verify/check-login
test/verify/check-machines-dbus
test/verify/check-metrics
test/verify/check-multi-machine
test/verify/check-networking-bond
test/verify/check-networking-checkpoints
test/verify/check-networking-firewall
test/verify/check-packagekit
test/verify/check-pages
test/verify/check-realms
test/verify/check-setroubleshoot
test/verify/check-storage-iscsi
test/verify/check-storage-luks
test/verify/check-storage-multipath
test/verify/machineslib.py

Generalize a few test special cases that conceptually apply to all
Debian/Ubuntu images, as opposed to just particular releases of them.
-  [ ] bots: Add ubuntu-2004 image: https://github.com/cockpit-project/bots/pull/612

test: Introduce testing on ubuntu-2004

---

test/common/testlib.py
test/verify/check-storage-basic
test/verify/check-storage-ignored
test/verify/check-storage-lvm2
test/verify/check-storage-partitions
test/verify/check-storage-used
test/verify/storagelib.py

make check-storage-lvm2 nondestructive

---

pkg/lib/machines.js
pkg/machines/components/consoles.jsx
pkg/machines/components/serialConsole.jsx
pkg/machines/libvirt-common.js
pkg/networkmanager/firewall-client.js
pkg/networkmanager/interfaces.js
pkg/selinux/setroubleshoot-client.js
pkg/storaged/client.js
pkg/systemd/overview-cards/realmd-operation.js
pkg/systemd/overview-cards/serverTime.js

Cockpit should always use the maximum privileges it has.  Otherwise
actions might be rejected that are actually allowed.

all: Add { superuser: "try" } for things that might need Polkit

---

pkg/docker/containers-view.jsx
pkg/lib/plot.js
pkg/machines/libvirt-dbus.js
pkg/networkmanager/interfaces.js
test/avocado/selenium-kdump.py

rhel-7.8 backports

---

test/common/testlib.py
test/verify/check-login

Add a helper to attempt a possibly-failing login, with the given
credentials.  Use it from a few places to reduce code duplication.

tests: add a browser.try_login() helper

---

pkg/machines/libvirt-dbus.js

Commit 190071495 missed a few spots.

machines: Add missing to D-Bus calls in libvirt-dbus.js - fix missing "signatures" in commit message on merging

---

test/verify/check-machines-dbus
test/verify/machineslib.py

It needs https://github.com/cockpit-project/cockpit/pull/13696 (the cleaning of `prepareStorageDeviceOnISCSI`).

Make machine tests nondestructive

---

pkg/dashboard/dashboard.scss
pkg/lib/machine-dialogs.js
pkg/lib/machine-dialogs.scss
pkg/shell/index.html

Picked up from https://github.com/cockpit-project/cockpit/pull/13663 as unrelated changes.

Shell and dashboard tweaks

---

test/common/testlib.py
test/containers/check-bastion
test/selenium/README.md
test/verify/check-login
test/verify/check-packagekit
test/verify/check-system-info
test/verify/machineslib.py

We stopped releasing to Fedora 30 and supporting that in CI.

test: Clean up fedora-30 special cases

---

test/verify/check-login

It's not clear what exactly that is, but it's not related to cockpit.

test: Add another expected message to TestLogin.testSELinuxRestrictedUser

---

pkg/machines/components/diskAdd.jsx
pkg/machines/components/vm/vmActions.jsx
pkg/machines/reducers.js
test/verify/machineslib.py

As discovered in #13741
Lets see if these cases are all there was to it, or if there are also different places where this happens.

Machines fixes

---

test/common/testlib.py
test/verify/check-accounts
test/verify/check-kdump
test/verify/check-login
test/verify/check-loopback
test/verify/check-networking-checkpoints
test/verify/check-packagekit
test/verify/check-reauthorize
test/verify/check-storage-iscsi
test/verify/check-system-info
test/verify/machineslib.py

Test cleanups/robustifications

---

pkg/users/index.html
tools/urls-check

And also contains one trivial unrelated fix.

tools: Do not scan .svg files fro urls

---

po/zanata.xml
test/verify/check-connection
test/verify/check-docker
test/verify/check-journal
test/verify/check-kubernetes
test/verify/check-machines-virsh
test/verify/check-multi-machine
test/verify/check-packagekit
test/verify/check-storage-format
test/verify/check-storage-iscsi
test/verify/check-storage-resize
test/verify/check-system-info
test/verify/packagelib.py

Copy all the special cases of rhel-7-8.

Adjust tests for rhel-7-9

---

pkg/machines/components/desktopConsole.jsx
test/verify/machineslib.py

There is something wrong with the layout, too.  MoreInformation can't be in a `<p>`, most likely.

machines: Don't access provider for MoreInformation

---

pkg/machines/components/create-vm-dialog/createVmDialog.jsx

machines: don't ask for user password for new VM creation when the connected user is root

---

test/common/testlib.py
test/verify/check-services

Builds on top of #13751 so blocked until that lands.

Make services tests nondestructive

---

po/po2json

Do not use fuzzy translations

---

pkg/selinux/selinux-client.js
pkg/selinux/setroubleshoot-view.jsx
pkg/selinux/setroubleshoot.js
test/verify/check-setroubleshoot

The central feature here is that the SELinux page is now able to automatically apply proposed solutions for setting SELinux booleans.
It also auto-updates the System Modifications table after applying a solution.

SELinux page improvements

---

pkg/systemd/overview.jsx
pkg/systemd/overview.scss
src/bridge/Makefile.am
src/bridge/bridge.c
src/bridge/cockpitdbusinternal.h
src/bridge/cockpitdbusloginmessages.c
src/ws/session-utils.c
src/ws/session-utils.h
src/ws/session.c
test/verify/check-login

Show a banner on the overview page, at login, listing the last
successful login, as well as the number of failed logins since the last
successful login, and the last such failed login (if applicable).

systemd: show last/failed-login banner on overview page

---

pkg/selinux/setroubleshoot-view.jsx
pkg/selinux/setroubleshoot.js
pkg/selinux/setroubleshoot.scss
test/verify/check-setroubleshoot

Now there was one fix for every alert. But alert can have multiple
solutions.
No tests as I don't have a good idea how to get alert with two solutions yet and don't want to block @martinpitt with his demo.

selinux: Assign result of a fix to every solution

---

pkg/shell/shell.scss

Noticed while working on the new navigation.
If someone can point me where this is being used I'll be happy, but I could not find a single place.

shell: Remove unused #server css rules

---

test/verify/machineslib.py

Similar to testConfigureBeforeInstall()

test: Add expected message to TestMachines.testCreate

---

test/common/testlib.py
test/verify/check-accounts

Hunting down #13870 which I can't reproduce locally.

Fix check-accounts flake

---

doc/guide/listen.xml

doc: Recommend FreeBind option when listening to specific IP

---

pkg/lib/page.scss
pkg/machines/components/consoles.css
pkg/machines/components/consoles.jsx
pkg/machines/components/desktopConsole.jsx
pkg/machines/components/vm/vm.jsx
pkg/machines/components/vnc.jsx
pkg/machines/libvirt-dbus.js
pkg/machines/machines.scss
test/verify/machineslib.py

Currently it looks like this: 
<kbd>
</kbd>

machines: allow sending Ctrl-Alt-F{1,2,3..} key combinations to a VM's virtual console

---

test/verify/check-system-info

It basically already was, just needs some more robust cleanup.

test: Make TestSystemInfo.testHardwareInfo nondestructive

---

src/ws/session-utils.c

GCC bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94615
GCC throws warnings if you use strncpy() for its intended purpose and
it's difficult and ugly to #pragma them away (while getting the version
right).  Let's write some complicated and less clear code to accomplish
the relatively simple thing that we wanted to do in the first place.

session: avoid using strncpy()

---

test/verify/check-networking-bond
test/verify/check-networking-vlan
test/verify/netlib.py

tests: Make vlan and some bond tests nondestructive

---

pkg/lib/cockpit-components-logs-panel.jsx
pkg/playground/journal.html
pkg/playground/journal.jsx
pkg/playground/manifest.json.in
webpack.config.js

When limiting the log display, we want to cut off at the end, not the
start.  Ouch.

pkg: Fix cockpit-components-log-panel some

---

pkg/machines/components/nicBody.jsx

Docs team found it confusing (and I agree)
https://projects.engineering.redhat.com/browse/RHELPLAN-30164?focusedCommentId=2306960&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2306960

machine: Remove 'disabled' entry in NIC add dialog until it's implemented

---

pkg/apps/application-list.jsx
pkg/apps/application.css
tools/webpack-make

See https://bugzilla.redhat.com/show_bug.cgi?id=1796834
Although it does not generate any new strings, so maybe we don't really need anything from translators, we just may need to deliver this new version.

[7.9] Backport translations related fixes

---

test/README.md
test/verify/check-docker
test/verify/check-journal
test/verify/check-kdump
test/verify/check-login
test/verify/check-networking-firewall
test/verify/check-packagekit
test/verify/check-storage-format
test/verify/check-storage-luks
test/verify/check-storage-resize
test/verify/check-system-info
test/verify/machineslib.py

Blocked on https://github.com/cockpit-project/bots/pull/776
[1](https://logs.cockpit-project.org/logs/pull-13928-20200420-104709-0964f5ea-rhel-8-3-bots-776/log.html)

Adjust tests for rhel-8-3

---

pkg/lib/packagekit.js
test/verify/check-packagekit

The com.redhat.SubscriptionManager service is old and not always
available.

lib/packagekit: Use RHSM1 service

---

test/common/testlib.py
test/verify/check-docker
test/verify/check-login
test/verify/check-realms
test/verify/check-system-info
tools/debian/control
tools/debian/rules

They are unrelated, but each simple enough to be tested and reviewed together IMHO. Let me know if you disagree.
The test fixes come from real logs that  I looked at recently, but unfortunately I didn't keep their URLs.

Various little test and packaging fixes

---

test/README.md
test/verify/check-docker
test/verify/check-journal
test/verify/check-kdump
test/verify/check-login
test/verify/check-machines-dbus
test/verify/check-metrics
test/verify/check-multi-machine
test/verify/check-multi-machine-key
test/verify/check-networking-bond
test/verify/check-networking-checkpoints
test/verify/check-networking-firewall
test/verify/check-packagekit
test/verify/check-realms
test/verify/check-setroubleshoot
test/verify/check-storage-iscsi
test/verify/check-storage-luks
test/verify/check-storage-multipath
test/verify/check-storage-resize
test/verify/machineslib.py

The image and test were dropped two weeks ago already in
https://github.com/cockpit-project/bots/pull/671

test: Drop ubuntu-1804 special cases

---

pkg/machines/components/storagePools/createStoragePoolDialog.jsx
pkg/machines/scripts/create_machine.sh
test/verify/check-machines-dbus
test/verify/machineslib.py

machines: pass pool/volume pair in quotes in script in case it contains spaces

---

pkg/packagekit/autoupdates.jsx
test/verify/check-packagekit

https://bugzilla.redhat.com/show_bug.cgi?id=1829685

packagekit: Fix dnf-autmatic timer parsing, port to standard Promise

---

test/verify/check-pages

This replaces the final bit of selenium-navigate.py, see issue #13481

test: Make check-pages nondestructive

---

Makefile.am
pkg/playground/speed.css
pkg/playground/speed.html
pkg/playground/speed.js
src/base1/test-spawn-proc.js
src/common/cockpitchannel.c
src/common/cockpitlog.h
src/common/cockpitpipe.c
src/ws/test-server.c
test/common/tap-cdp
test/verify/check-terminal
webpack.config.js

This is some stuff that fell  out from my investigations of PR #12580

Various unit test/debugging fixes

---

pkg/users/local.js
pkg/users/users.scss
test/selenium/selenium-base.py
test/verify/check-accounts

We want to obsolete 'Account settings' from the top right menu and we need to show which user is the current one.

users: Indicate the current user

---

test/selenium/selenium-machines-storage-pool.py

We still test 8.2 on master as well and these tests don't do us any good - for example see https://github.com/cockpit-project/bots/pull/832

[rhel-8.2] test: Sync master selenium tests
