cockpit-project/cockpit

test/verify/check-system-services
This is especially visible during rhel's image refresh[1], which uses Eastern Time Zone.
[1] https://github.com/cockpit-project/bots/pull/3895
=> test: Consider browser's time zone when checking service's next run

src/Makefile.am
`make pcc` will attempt to install a symlink to cockpit-bridge.pyz in ~/.local/bin/cockpit-bridge and launch Cockpit Client on it.
=> build: add `pcc` (Python Cockpit Client) rule

tools/cockpit.spec
Similarly how we recommend cockpit-packagekit if dnf is installed, recommend cockpit-ostree if rpm-ostree is installed. That will make the package more discoverable, and provide an OOTB "Software Updates" page.
cockpit-ostree is not in RHEL 8/9 at the moment, so only generate this
dependency on non-RHEL (i.e. Fedora) for the time being.
=> tools: Recommend cockpit-ostree on OSTree systems

configure.ac, src/ssh/cockpitsshrelay.c
The new ssh_userauth_publickey_auto_get_current_identity makes it work.
=>  ssh: Use ssh_userauth_publickey_auto

pkg/metrics/metrics.jsx
I believe these mounts are for flatpak portals and are not interesting to show in our metrics page.
=> metrics: ignore flatpak revokefs-fuse

test/verify/check-networkmanager-other
=> test: Fix check-networkmanager-other to clean up after itself

.gitleaks.toml
Quiesce Red Hat's security scanner about allegedly leaking private SSH keys. These are static keys for our unit tests.
---
I got an alert email when I updated the main branch on my fork. This is apparently a fairly new thing. Unfortunately I didn't find a public documentation about it, but as a Red Hatter you can [look here](https://source.redhat.com/departments/it/it-information-security/wiki/pattern_distribution_server).
=> gitleaks: Ignore mock SSH keys

.github/workflows/differential-shellcheck.yml
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR. The beauty of differential scans is that you will get reports only about newly added defects. 
Since this repository has few shell scripts, I think you might find some value in having a shell linter. Differential ShellCheck action is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to …
=> ci(lint): Add Shell linter - Differential Shellcheck

test/browser/main.fmf
Our tests call `vgcreate`, make sure it is installed. It's not any more in the standard Fedora 37 images.
---
This should help with the [fedora-37 failures on the TF](https://artifacts.dev.testing-farm.io/d77ad533-8ef4-4a30-8a04-b0c16fe3f487/), where the storage tests fail with
bash: line 1: vgcreate: command not found
=> fmf: Add lvm2 test dependency

test/verify/check-storage-luks
It doesn't depend on clevis/tang so it should be fine on Arch.
=> test: Run TestStorageLuks.testLuks1Slots also on Arch

test/common/storagelib.py
This should get rid of non-destructive flakes like this: https://cockpit-logs.us-east-1.linodeobjects.com/pull-3947-20221007-232750-12dac395-centos-8-stream-cockpit-project-cockpit/log.html#231-2
=> test: Run partprobe on new loop devices

test/verify/check-networkmanager-checkpoints
After adding Arch Linux testing support for checkpoints, I discovered the workaround is not required anymore for Debian as well. This was supposedly fixed in NetworkManager master in 2016.
=> test: drop Debian networkmanager hack

.github/workflows/build-ws-container.yml, .github/workflows/flatpak-test.yml, .github/workflows/npm-update-pf.yml, .github/workflows/npm-update.yml, .github/workflows/reposchutz.yml, .github/workflows/unit-tests-refresh.yml, .github/workflows/unit-tests.yml, .github/workflows/urls-check.yml, .github/workflows/weblate-sync-po.yml, .github/workflows/weblate-sync-pot.yml
See the following links for more details:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.com/actions/github-script#breaking-changes-in-v5
=> GitHub actions checkout

test/verify/check-networkmanager-firewall
The pixel tests do not contain the 8765 port anymore, so this workaround can be dropped.
=> test: drop removed Dbus port workaround

src/bridge/cockpitdisksamples.c, src/cockpit/samples.py
This was added in 2015 but it seems the client never used it, as there are no plans to use it drop it.
Was added in af2d488a27b7beb7e410a673923442ead7d02ac2 
The overhead of keeping it is minimal to be fair, but seems a bit wasteful to keep things which are unused since 2015 :)
=> bridge: python: drop disk.all.ops

pkg/users/expiration-dialogs.js
In dialogs a datepicker can be cut off, so instead of appending it to the parent (the dialog) append it to document.body. More details explanation here https://www.patternfly.org/v4/components/date-picker/#datepicker 
Closes #17814
=> users: append Datepicker to document.body

test/verify/check-storage-used
Different versions of bash do tail call optimization in different scenarios, and the "Currently in use" pop-up would either show the bash process or not (depending on whether TCO was done). So let's prevent bash from doing TCO of the "sleep" call.
=> test: Prevent bash TCO when keeping a mount point busy

test/verify/check-networkmanager-checkpoints
This seems to be bugged when systemd 251 rotates journal files, see https://github.com/systemd/systemd/issues/25063.
The NetworkManager journal is shorter than 1000 lines in this test anyway, so dropping "-n 1000" has no effect on performance.
=> test: Don't use "journalctl -n -u"

test/verify/check-networkmanager-basic, test/verify/check-networkmanager-bond, test/verify/check-networkmanager-bridge, test/verify/check-networkmanager-firewall, test/verify/check-networkmanager-mtu
This extends enabled testset, something is still wrong with bond/team tests which needs more investigation.
=> Enable more Arch Linux NetworkManager tests

src/cockpit/channel.py
The Cockpit terminal uses options to set the rows and cols.
=> python: add options control command

selinux/cockpit.te
Most recent Fedora 37's pam_faillock tries to chown/chmod/etc. some state files, which requires `CAP_FOWNER`. Grant this, as it's less dangerous than `CAP_DAC_OVERRIDE`.
See https://github.com/cockpit-project/bots/pull/3974
---
I verified this on the new image in https://github.com/cockpit-project/bots/pull/3974 with `test/verify/check-static-login TestLogin.testFaillock`.
=> selinux: Allow fowner capability to cockpit-session

.github/workflows/release.yml, containers/flatpak/Makefile.am, containers/flatpak/add-release, containers/flatpak/cockpit-client.yml.in, containers/flatpak/prepare, tools/patch-metainfo
If a DOWNSTREAM_RELEASES_XML environment variable is set while calling `make install` then patch the installed metainfo for Cockpit Client to use the release history from that external file.
This allows downstream packaging of Cockpit Client (particularly the Flatpak) to maintain its own version history, now that we don't ship one for ourselves.
=> build: patch <releases> in metainfo on install

test/verify/check-testlib
In Fedora 37's Python, the skip message now contains the test name:
Relax the regular expression, we don't need to pin it down *that* precisely.
----
This got exposed by https://github.com/cockpit-project/cockpituous/pull/531 , so that [this test now fails everywhere](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17839-20221026-054748-c5ecd1ca-arch/log.html#307-2). I think this is harmless/obvious enough to fix without rolling back the tasks container. This would also happen for developers locally, so we need to fix it either way.
=> test: Relax test skip expected output

test/common/lcov.py
External projects like cockpit-podman put their files directly into dist/ but install them into a subdirectory in /usr/share/cockpit/. For example, the dist/index.js file of cockpit-podman is installed as /usr/share/cockpit/podman/index.js.
During coverage processing, we need to map back from /usr/share/cockpit/podman/index.js to dist/index.js, and at the same time need to ignore other files like /usr/share/cockpit/storage/index.js.
This used to be done via the "name" element of manifest.json, but it is less intrusive to take the name from package.json, because it is already there.
This works as long as the Makefile of the external project also looks into package.json during installation.  Projects based on the starter-kit do this.
=> test: Fall back to package.json during coverage processing

src/ws/Makefile-ws.am, test/verify/check-static-login, test/verify/check-superuser, tools/cockpit.spec
In Fedora you can install multiple architectures of a package
simultaneously. This causes a file conflict when trying to install both
the i686 and x86_64 architecture of "cockpit-tests", as they both ship
/usr/lib/cockpit-test-assets/mock-pam-conv-mod.so (and this is not a
magic multi-arch directory).
This is of no practical importance other than that rpminspect complains,
which causes a nasty red stain in gating.
Install the file into the proper PAM dir right away. This is properly
multi-arched in both Debian and Fedora, and tests then don't need to
know the exact directory any more. For people installing from upstream
this is still sufficiently guarded, as `make install` does not install
that module (only `make test-install` does).
---
This is the [rpmdeplint …
=> test: Avoid multi-arch conflict on mock-pam-conv-mod.so

test/browser/run-test.sh
This happens on packit's Fedora 37.
=> test: allowed systemd user journal corruption messages

.github/workflows/webpack-jumpstart.yml
actions/{download,upload}-artifact@v3 uses nodejs 16 as runtime instead of the deprecated nodejs 12 runtime.
Seems I forgot some as can be seen [here](https://github.com/cockpit-project/cockpit/actions/runs/3319238959), not sure about the last warning we never use `set-output` so I guess that might be the action we use doing it?
=> .github: update webpack-jumpstart actions

package.json, test/common/testlib.py
Python 3.11 changed it's unittest internals for the Outcome class and no longer calls testPartExecutor with isTest as it used too. The Outcome class now has a TestResult attribute which records failures, errors and successful tests different.
=> test: Python 3.11 compatibility

test/verify/check-storage-luks
Works locally, let's verify it here after the refresh:
https://github.com/cockpit-project/bots/pull/3998
=> test: enable clevs tang test on Arch Linux

.github/workflows/build-ws-container.yml, containers/ws/install.sh, containers/ws/release.sh
This brings back automatic releases. As we now build from pure Fedora, we cannot predict when they actually make it through bodi. But refreshing them every week is good enough in most cases (and if not, we can still trigger a manual refresh).
It's also desirable to refresh the container image regularly even if there is no new cockpit upstream release -- it can then still pick up Fedora security fixes in other packages.
=> containers/ws: Clean up and re-automate release

plans/all.fmf, plans/basic.fmf, plans/network.fmf, plans/optional.fmf, test/browser/browser.sh, test/browser/main.fmf, test/browser/run-test.sh, test/verify/check-packagekit
On the Testing Farm we can run up to 5 parallel test plans. The natural
way to split them is our existing basic/optional package split for RHEL
8, so let's start with that. This mitigates the utterly slow Fedora
Rawhide tests due to a kernel bug [1], and also should generally speed
up results. The pre-tmt setup costs are about 6 minutes on Fedora 37, 
while the actual test runtime is about 22 minutes. So we shouldn't
over-split it, but two seems beneficial enough.
Pass the plan name to test/browser/run-test.sh. This replaces the 
implicit `$test_basic`/`$test_optional` variables. Rework the  RHEL 8
skips accordingly.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2139658
Fixes #17866
---
=> fmf: Split tests into separate parallel plans

pkg/lib/patternfly/patternfly-4-overrides.scss
I'm specifically not using `:where()` here to bump up the specificity so that this will always take precedence over PF4's broken version. (So we don't have to use `!important`, in other words.)
=> pf4: Fix dark mode dropmarker in form controls

containers/unit-tests/start
The 'append' action of ArgumentParser will set an empty list as the value of the argument in the return namespace, but only the first time an argument is encountered.
Put another way: in case the argument isn't given, we get `None`, instead of `[]`.  We then go on to try to iterate over this to build the arguments to `git clone`, which doesn't work very well.
Use `default=` to make sure we always have a list.
=> containers: fix unit-tests with no submodules

pkg/lib/patternfly/patternfly-4-overrides.scss
Since new patternfly update, [this PF commit](https://github.com/patternfly/patternfly/commit/5c0c776fbe056a7829c47cdb81d59a8a190e4a84) changed the width of our Selectors all across Cockpit and [broke pixel tests.](https://github.com/cockpit-project/cockpit-machines/pull/840)
However after digging into it, it seems that there is nothing wrong with [that PF commit](https://github.com/patternfly/patternfly/commit/5c0c776fbe056a7829c47cdb81d59a8a190e4a84), but rather it only managed for our custom patternfly override to take effect, which was setting Selector's menu to `20rem`.
To me, that override doesn't seem right, as we have selectors wider that. I guess it was introduced by accident or is no longer viable.
=> Don't set max-width for Patternfly's select

plans/all.fmf, plans/basic.fmf, plans/network.fmf, plans/optional.fmf
FMF plans can inherit common properties [1]. Go back to a single plans/all.fmf (like it was until commit fe4721cdcd1), put the common properties at the top, and enumerate the three plans with their specific properties.
This will make it easier to keep the Fedora downstream dist-git in sync.
[1] https://tmt.readthedocs.io/en/latest/examples.html#inherit-plans
---
Thanks to @psss for pointing this out!
=> fmf: Factorize and merge plan files

test/verify/check-connection
A recent update in the Arch Linux refresh (curl 7.86.0) changed the error output of "connection refused" to "cannot connect to server". Instead of relying on output which might change curl already provides exit codes for connection refused. This should be less brittle for future output changes.
=> test: stop parsing curl error output

.github/workflows/release.yml
See build in https://github.com/flathub/org.cockpit_project.CockpitClient/pull/16 . This isn't sufficient to fix the release, but it was an obvious bug in the generated diff.
=> workflows: Fix date format for Flathub release

test/verify/check-system-info
In a recent PCP update pmie_check consumes a lot of CPU which interferes with waiting for idle CPU usage.
=> test: extend timeout for CPU usage going back to idle

containers/flatpak/Makefile.am, tools/patch-metainfo
The flathub appdata validation requires an <?xml?> line.
If we want one of those, we need to pass the `xml_declaration=True` kwarg to `ElementTree.write()`.
To make sure we catch issues like this for ourselves, validate the in-tree metainfo before patching it, and validate the installed copy after patching.
=> flatpak: preserve xml declaration in installed metainfo

test/browser/browser.sh, test/browser/run-test.sh
279 failed in RHEL 9 gating, due to some TF machine specific differences and a missing test dependency.
I tried to test this with a draft PR against RHEL, but tests don't run there. I asked, but I'm fairly sure about these fixes.
=> FMF: RHEL fixes

test/verify/check-storage-stratis
On Arch Linux services are not automatically started so we have to start them in tests, as the tests reboot enable them as well.
=> test: enable stratis tests on Arch Linux

tools/webpack-make
When writing the Makefile.deps, make sure we consistently refer to the fact that the manifest.json is created in the SRCDIR.  Otherwise, when doing a builddir != srcdir build, we won't consider the dependencies at all.
Fixes #17462
This was the real cause of the weird timestamp issues in #17883
=> webpack-make: include $(SRCDIR) in stampfile name

containers/unit-tests/setup.sh, src/Makefile.am
Add python3-pytest-timeout to the unit-tests container and set PYTEST_TIMEOUT=120 in the Makefile, near the `pytest` targets.
This means that the timeout will be honoured if the plugin is available (as in the unit-tests container) but will be ignored if it's not (in order to reduce dependencies for other users).
This seems to be the only approach which accomplishes that.  Putting it in the config file triggers a warning if the plugin is missing, and passing it on the commandline is a hard error in that case.
=> python: add pytest-timeout, set PYTEST_TIMEOUT=120

tools/webpack-jumpstart
This was part of #17883 but the real issue there was #17462 (fixed in #17911).
I still think the changes to `webpack-jumpstart` are worthwhile, but now that they have absolutely nothing to do with the coveragepy branch anymore, we can discuss them here, instead.
=> webpack-jumpstart --partial: delete changed webpacks instead of touching changed files

test/browser/browser.sh, test/common/testlib.py, test/image-prepare, test/verify/check-connection, test/verify/check-reauthorize, test/verify/check-static-login, test/verify/check-users, tools/arch/PKGBUILD, tools/arch/cockpit.install, tools/arch/cockpit.pam, tools/cockpit.debian.pam, tools/cockpit.pam, tools/cockpit.spec, tools/debian/cockpit-ws.postinst, tools/debian/cockpit-ws.postrm
On all operating systems, logging in as root with a username/password via SSH has been disallowed for a long time. Cockpit now also disallows it by default on new installations, but still allows it on upgrades for backwards compatibility. You can configure this in `/etc/cockpit/disallowed-users`.
=> tools: disallow root login by default

test/verify/check-system-realms
Fedora got updated in
https://github.com/cockpit-project/cockpituous/pull/532 , bringing along
updates to font rendering. This caused a lot of jitter, requiring all 
pixel tests to be re-done.
Unfortunately the jitter is completely unpredictable/unreproducible in
the Test{AD,IPA}.testQualifiedUsers join/leave dialogs, each run ends up
with a slightly different image. Disable these for now.
----
[review diff](https://github.com/cockpit-project/pixel-test-reference/compare/19b97eb573a874ef8f15b73a85e6636f7b648f07..77b25f0b21eb5082d51802180db9676c8a3b7afc)
=> test: Update pixel references to current Chromium

.gitignore, pyproject.toml, test/run
Since we dropped the Makefile rule for creating cockpit-bridge.pyz, the pybridge scenario has been broken.
Add some minimal pyproject.toml metadata required to build a wheel of the Python package.  Build this wheel on the outside, and inject it into the VM via image-customize.
Note: we no longer bother with building the C parts of the package anymore — we rely on the distro packages already present in the image.
=> test: build a wheel for the pybridge scenario

pkg/base1/test-location.js, pkg/lib/cockpit.js
The originally introduced cockpit.location.encode function incorrectly does the 0 comparison in the indexOf call, so with url_root set the encode function would always prepend the url_root. As "foo".indexOf(true) returns -1 which is truthy in JavaScript.
=> pkg: correct indexOf function call in cockpit.location.encoding

autogen.sh
autogen: Copy automake tools
Building the dist tarball in the current Fedora 37 cockpit/tasks
container now fails when running as user podman container, when using
systemd-homed:
cp: failed to preserve ownership for 'cockpit-279.39.gb4b41375f/tools/compile': Value too large for defined data type
This was due to a change in systemd 251 with mapped user IDs[1][2].
Work around this by copying the files instead of symlinking them. That
is the default behaviour anyway, and does not hurt much: git trees are 
regularly cleaned by developers anyway, and dist tarballs contain a copy
either way.
[1] https://github.com/systemd/systemd/blob/1d679b208d982bd5b8ba893981774cac5959b4b4/NEWS#L789
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2144558
=> autogen: Copy automake tools

test/common/testlib.py
This is required for cockpit-podman not check itself if /etc/cockpit/disallowed-users exists and if so sed the file.
https://github.com/cockpit-project/cockpit-podman/pull/1145
=> Disallowed users check

pkg/apps/manifest.json, pkg/base1/test-http.js, pkg/kdump/manifest.json, pkg/metrics/manifest.json, pkg/networkmanager/manifest.json, pkg/packagekit/manifest.json, pkg/pcp/manifest.json, pkg/playground/manifest.json, pkg/selinux/manifest.json, pkg/shell/manifest.json, pkg/sosreport/manifest.json, pkg/ssh/manifest.json, pkg/tuned/manifest.json, pkg/users/manifest.json, tools/cockpit.spec
Drop cockpit version requirements for versions which are > 2 years old. None of the distributions that we support on the main branch have that ancient versions even in their backport repositories. This does not change anything in practice, as the rpm/deb dependencies are a *lot* stricter already (rpm has ≥ 266, deb has ≥ source version).
Also update the "238.1.1" requirement to "239". Back then that meant "the next version after 238.1".
Fewer magic numbers!
----
https://salsa.debian.org/debian/cockpit-podman/-/merge_requests/4 triggered me to have a closer look.
=> Drop obsolete versioned dependencies

test/browser/run-test.sh
The gating test environment set's up and installs testing packages. This leaves the system in a state where there are services to restart/reboot making the kpatch test fail (as there is no continue button).
=> test: exclude Kpatch on tmt

pkg/lib/patternfly/patternfly-4-overrides.scss
To fix disabled buttons in dark mode in general, we had to change the background and contrast. To fix the buttons in modals, we also need to change the background, as otherwise the background is the same color.
=> pf, dark: Fix disabled buttons in modals

containers/ws/label-run
A rather small change that would allow either `/etc/cockpit` or `/etc/cockpit/cockpit.conf` to be mounted via volume options for the WS container.
This should not break existing container deployments, since the link creation for the `default-bastion.conf` still is done if both the directory and the file are not mounted on start.
=> Enable mounting of /etc/cockpit as volume

pkg/networkmanager/firewall-client.js, test/verify/check-networkmanager-firewall
See issue https://github.com/cockpit-project/cockpit/issues/17669.
The firewall configuration uses the `pkcheck` tool for checking the user permissions. But that tool might not be available in a minimal system.
If the `pkgcheck` test fails fallback to the usual root permission check.
Tested manually with the patched plugin.
Before applying the patch the firewall configuration could not be changed:
After applying the patch the switch is enabled and changing the value works correctly.
=> networkmanager: Improved firewall permission check

pkg/users/account-create-dialog.js, test/verify/check-users
Created a validation method for real_name field with char set of a-z A-Z 0-9 ._-
Replaced the if statement in validate function with a call to validate_real_name which includes the empty real_name check.
Results in the following:
=> #17822 - Validation of real name field

pkg/systemd/services/services.jsx
This was not possible when that toolbar was developed but now PF-react allows as to pass the filter text to the component.
This string appears only when filters count > 2, so the use of ngettext is not required when translating.
=> services: translate the filter help string in the services page

pkg/lib/menu-select-widget.scss, pkg/shell/shell-modals.jsx, pkg/systemd/overview-cards/cryptoPolicies.jsx, pkg/systemd/overview-cards/profiles-menu-dialog-body.jsx, pkg/systemd/overview.scss, pkg/tuned/dialog.jsx
- Using updated PF menus lets us drop a little bit of overrides
- Moving the scrollbar from the modal to the menu makes sense here, but it needs some fixups
=> overview: Adjust modals & select lists

pkg/base1/test-dbus-common.js, pkg/base1/test-dbus.js, pkg/base1/test-locale.js, pkg/lib/qunit-tests.js, src/cockpit/channels/dbus.py, test/pytest/test_bridge.py, test/pytest/test_browser.py, webpack.config.js
This implements "add_watch" with a path_namespace that points at a ObjectManager.  This also takes care to deliver "notify" and "meta" message before method call replies and to not reorder signals.  This is expected by the DbusProxy and DbusProxies implemented in cockpit.js.
It is an error when there is no ObjectManager at path_namespace.  The C bridge falls back to emulating an object manager via recursive introspection in this case, but we might not ever want to implement that in the Python bridge.
=> python: ObjectManager support for the dbus payload

test/verify/check-connection, test/verify/check-static-login, tools/cockpit.spec
With the disallowed-users feature we now disable root login by default in Cockpit. In RHEL 8 however, a default install can login as root over ssh with password authentication so allow this as well in Cockpit.
The /etc/cockpit/disallowed-users file is kept as then administrators can optionally easily disable root login when wanted.
@martinpitt @marusak do we want what I did? My reasoning is that it's then easier to disable if required.
=> Allow root login on RHEL 8

test/verify/check-system-realms
This fixes some tests at rhel-8-8 image refresh:
https://github.com/cockpit-project/bots/pull/4096
=> Update a list of distros which don't support realmd auto-detection

pkg/shell/base_index.js, pkg/shell/indexes.jsx
When `CockpitLang` cookie is not set (meaning the user hasn't changed language manually in the UI) we should not default to English as the UI will be in the preferred user language as parsed from Accept-Language header.
=> shell: Use correct default lang attribute

pkg/lib/cockpit-components-table.jsx, pkg/users/account-details.js, pkg/users/accounts-list.js, pkg/users/local.js, pkg/users/lock-account-dialog.js, pkg/users/logout-account-dialog.js, pkg/users/users.scss, test/verify/check-shell-multi-machine, test/verify/check-users
TODO:
- Log user out
- Lock user
The new accounts page implementation brings in more details in the accounts summary view, add suports for filtering the list of users and lastly shows information about the groups per user.
=> accounts: Use table view for accounts overview

src/cockpit/bridge.py, src/cockpit/internal_endpoints.py, src/cockpit/peer.py, src/cockpit/protocol.py, src/cockpit/router.py, src/cockpit/superuser.py, test/pytest/pseudo.py, test/pytest/test_bridge.py
This is semi-working.  Let's start discussing it.
The new `test_superuser()` case in `test/pytest/test_bridge.py` is probably a nice place to look to get an idea of what's already working here.
=> python: superuser peer bridge (--privileged mode)

pkg/lib/cockpit-components-dialog.jsx, pkg/lib/cockpit-components-install-dialog.jsx, pkg/metrics/metrics.jsx, pkg/networkmanager/firewall.jsx, pkg/packagekit/updates.jsx, pkg/playground/react-patterns.js, pkg/shell/credentials.jsx, pkg/shell/hosts_dialog.jsx, pkg/shell/superuser.jsx, pkg/systemd/overview-cards/cryptoPolicies.jsx, pkg/systemd/overview-cards/motdCard.jsx, pkg/systemd/services/service-details.jsx, pkg/systemd/services/timer-dialog.jsx, pkg/tuned/dialog.jsx, test/verify/check-packagekit, test/verify/check-users
See @garrett's review in https://github.com/cockpit-project/cockpit/pull/17214#pullrequestreview-930307611 . This makes our dialogs comply with [PatternFly form validation design](https://www.patternfly.org/v4/components/form/design-guidelines/#error-validation-on-submission).
On main they look like this:
With this PR they look like this:
Initial draft which just converts cockpit-components-dialog and a few `<ModalError>` instances.
- Builds on top of #17220 (spotted during this conversion)
=> Show dialog errors at the top

test/verify/check-system-services
Fix TestSystem.testOverview flake by only capturing the unit header as the log section can differ in layout causing flakes. We already take a full screenshot of the service overview page for succesful units.
=> test: only capture failed services header

test/common/run-tests
The later isn't supported with older Python version.
=> run-tests: using typing.List[] instead of list[]

pkg/shell/base_index.js
On `readystatechange` is not soon enough for users to notice a white flash while switching. The setting of the iframe's background color was removed in the dark theme switcher commit f259829e700f0405 while it's still needed. As we show the iframe while the content is still being rendered it will show a white flash.
=> shell: fix white flash regression by dark theme switcher

pkg/systemd/services/service-details.jsx
The On/Off button previously ran EnableUnitFiles() and Start() in parallel, with the Reload() happening right after Start(). This triggers race conditions in journalling, where the first few messages of the service start would get eaten by the reload.
Serialize these actions similar to what pkg/lib/service.js does. This is also what `systemctl enable --now` does.
Fixes #17768
=> systemd: Serialize reload and unit start/stop on Service details page

tools/debian/control
In Debian, policykit-1 0.120-4 got split into multiple smaller packages, in particular `pkexec` and `polkitd`. Cockpit can call `pkexec` and does not directly talk to `org.freedesktop.PolicyKit1`, so update the recommendation for `pkexec`. Still keep the old name as a fallback, to keep the package backportable to Debian 11 and Ubuntu.
https://bugs.debian.org/1025556
=> tools: Update Debian's policykit-1 dependency for package split

test/verify/check-static-login
Becoming superuser as SELinux restricted user now started to work in RHEL 9.2, right after C9S (commit 1589689abe7). Invert the condition, so that we now have a shrinking list of broken OSes -- that is easier to review and maintain.
---
This needs to land in lockstep with the rhel-9-2 image refresh in #4139
=> test: Adjust testSELinuxRestrictedUser for fixed SELinux in RHEL 9.2

pkg/systemd/services/services.jsx, pkg/systemd/services/timer-dialog.jsx
In our tests we have a flake where `boot_timer.timer` does not show up after it has been created. This is caused due to `loadingUnits` being `true` so when we press create we do not refresh the list again. This race condition is now resolved as we don't allow a user to create a new timer if we are still loading units.
=> systemd: disable create timer button on unit load

.github/workflows/reposchutz.yml
The podman version (3.4.4) on Ubuntu 22.04 has issues with pipes and stops before piping the full tarball over (at ~ 25M of ~ 250M). This makes the protection checks fail, which means we can't land node_modules updates. For now pin it to 20.04 until we figured out the issue on 22.04.
=> .github: run protection checks on Ubuntu 20.04

selinux/cockpit.te
Since cockpit-session has its own selinux label, executing other (differently-labelled) processes from it is considered to be a privilege boundary transition, similar to executing a setuid binary.
Because of this, `AT_SECURE` gets set in the auxiliary vector, causing the libc of the spawned process to enter "secure execution" mode.  Among other things, that causes `secure_getenv()` to return NULL, even if a particular variable is in the environment.
libsystemd uses `secure_getenv()` to look for the user's D-Bus.  If `AT_SECURE` is set, that will fail, causing `sd_bus_default_user()` to return `-ENOMEDIUM`.  This breaks the Python bridge.
The solution to this problem is to mark the state transition as `noatsecure`. That makes sense: there's no real scenario where cockpit-session attacks …
=> selinux: avoid AT_SECURE on exec from cockpit-session

pkg/lib/cockpit-components-table.jsx, pkg/users/account-details.js, pkg/users/accounts-list.js, pkg/users/local.js
Current implementation would show blank page and wait until everything was loaded. Now the overview is shown with loading state inside groups and users views. Details page shows big spinner.
=> users: Show loading state

pkg/shell/hosts.jsx, pkg/shell/shell.scss, pkg/storaged/devices.jsx, pkg/storaged/storage-controls.jsx, pkg/storaged/storage.scss
This prevents duplication and includes CSS in the correct place.
=> css: Move some CSS imports to SCSS

test/verify/check-networkmanager-basic
The zoom and range selector on the Networking metrics is only visible if PCP is running. Make sure that is the case, as
https://github.com/cockpit-project/bots/pull/4159 will disable it by default.
=> test: Fix TestNetworkingBasic.testBasic for stopped pcp

test/run, tools/webpack-jumpstart
Only build changed webpacks. This takes off some 5 minutes (and heavy CPU load) for every test from the bots.
This was already applied in commit a7dcaf554dc6 half a year ago, but reverted in commit 0b25285522 because `webpack-jumpstart --partial` did not handle node_module/ updates correctly. But commit 3a77525f8e4d6a6e fixed that, it now removes all webpacks which are affected by a node_modules/ update (usually all of them).
-----
I validated this with the most recent PF update:
```sh
git checkout c49fc4b1d544c10375f9040fb63813d0784d61ea
git commit --amend --no-edit
git cherry-pick 755d372e50395256de6914fa6a72691c57d55160
```
Now jumpstart DTRT:
```
$ tools/webpack-jumpstart --partial
FETCH    dist  [ref: tag sha-776460684e6bdf81542934525e0f9272b21c3e5a]
COPY     package-lock.json
UNPACK …
```
=> test: Speed up CI runs with our jumpstart cache

pkg/metrics/metrics.jsx, test/verify/check-metrics
The userid was not passed to `cgroupRow` which meant that the lookup of podman names did not work for the top 5 memory services. We now also test if the containers show up, this is a bit different from our service test as we are limited by busybox sh.
=> metrics: fix pod lookup in top 5 memory users

tools/debian/watch
The /releases page has become JavaScript-y recently and thus unreadable by machines. Scan the API instead and construct a download URL.
----
`curl https://github.com/cockpit-project/cockpit/releases/` is just gibberish now. I already applied this change downstream, and it works:
```
❱❱❱ uscan --report --verbose
uscan info: Found the following matching hrefs on the web page (newest first):
https://github.com/cockpit-project/cockpit/releases/download/282/cockpit-282.tar.xz (282) index=282-4 
https://github.com/cockpit-project/cockpit/releases/download/281/cockpit-281.tar.xz (281) index=281-4 
https://github.com/cockpit-project/cockpit/releases/download/280.1/cockpit-280.1.tar.xz (280.1) index=280.1-4 
[...]
uscan info: Matching target for filenamemangle: …
```
=> tools: Use GitHub API in debian/watch

test/common/run-tests, test/common/testlib.py, test/verify/check-example, test/verify/check-testlib
Decorated testcases will be marked as "TODO" and report as per the TAP specification.
The test will be counted as a fail, the individual test case run will return non-zero, and run-tests will report "not ok", but the failure will not be counted towards the total number of failures reported as part of the exit status.
This is my counter-proposal to the use of xfail in #18039
=> testlib: add a @todo decorator

pkg/lib/cockpit-components-table.jsx
=> lib: table: keys can be '0' which is falsy but still a valid key

pkg/packagekit/updates.jsx
Also bring changelog to the right of the other description items, if there is enough space.
See https://github.com/cockpit-project/cockpit/issues/17789#issuecomment-1268153359 for the design direction.
Closes #17789
Now:
Before:
=> packagekit: format changelog description

pkg/systemd/logDetails.jsx, test/common/testlib.py, test/verify/check-system-journal, test/verify/check-users
o.fd.problems does not have a ObjectManager and we might not want to create a DBusProxies object for it, which relies on emulating a ObjectManager via Introspection.
Thus, let's create the array of DBusProxy:s explicitly.
=> systemd: Avoid path_namespace watches with org.freedesktop.problems

pkg/apps/application-list.jsx, pkg/apps/application.jsx, pkg/kdump/kdump-view.jsx, pkg/lib/cockpit-components-firewalld-request.jsx, pkg/lib/page.scss, pkg/lib/patternfly/patternfly-4-overrides.scss, pkg/metrics/metrics.jsx, pkg/networkmanager/firewall.jsx, pkg/networkmanager/network-interface.jsx, pkg/networkmanager/network-main.jsx, pkg/packagekit/updates.jsx, pkg/selinux/setroubleshoot-view.jsx, pkg/sosreport/index.jsx, pkg/storaged/details.jsx, pkg/storaged/multipath.jsx, pkg/storaged/overview.jsx, pkg/systemd/hwinfo.jsx, pkg/systemd/logDetails.jsx, pkg/systemd/logs.jsx, pkg/systemd/overview.jsx, pkg/systemd/services/service.jsx, pkg/systemd/services/services.jsx, pkg/users/account-details.js
This class removes side padding in mobile view for the page section component. This is a clear patternfly override and should be treated as such, by being placed in the patternfly-overrides file.
=> all: eliminate ct-pagesection-mobile class

test/common/run-tests
In the interest of saving space, we don't log all output from successful tests.  However, it is useful to see warnings like the recently introduced one for waits that get close to their timeout.
=> test: Show lines starting with "WARNING:" for successful tests

pkg/shell/hosts_dialog.jsx, test/verify/check-shell-host-switching
When editing hosts, the dialog should reflect the 'edit' mode with the title and primary buttons correctly.
Also it should be allowed to just change the username.
Fixes #17479
=> Fix 'edit' mode for hosts

pkg/networkmanager/network-interface-members.jsx, pkg/networkmanager/networking.scss
Fix actions stretch in medium width and stop using colSpan as it breaks on mobile.
Fixes #17318
=> networkmanager: fix network interface members actions

test/common/run-tests, test/common/testlib.py
Our cockpit test specific decorators were using wildly different
implementations. Make them consistent by always adding a
`_testlib__decoratorname` attribute to the test method or class.
Introduce a `get_decorator()` helper which returns the decorator value on the 
test method or class. This avoids the custom code which iterates over the 
class'es methods and duplicates the value.
This also debundles testlib from the `fmf_metadata` library, which we
have never used so far, and don't really plan to either.
There are still two kinds of decorators now: These with arguments, like @todo,
or even the empty-argumented skipDistroPackage(); and the ones without
arguments, like @nondestructive. This is still a bit confusing, but converting
the latter is more intrusive.
=> test: Clean up decorator implementation

pkg/lib/cockpit-components-table.jsx
Arrays as dependencies in hooks are very problematic and often result in too many uneccessary re-renders. This solution simply serializes the array of row keys into a JSON string object before passing them to the useEffect deps list.
This fixes some issues with the use of the ListingTable component among which the most prominent being the 'ct-new-item' class being added > 100 times in some cases.
This fixes warnings in all pages that use ListingTable component - error: Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.%s
=> cc-table: fix infinite call of useEffect hook

test/verify/check-selinux
on RHEL, insights-client started to modify the default policy to make
itself permissive; accept that. We can't reset it with
`semanage permissive -D` as that OOMs.
---
This blocks the [rhel-8-8](https://github.com/cockpit-project/bots/pull/4178) and [rhel-9-2](https://github.com/cockpit-project/bots/pull/4226) image refreshes.
=> test: Accept insights_client_t SELinux policy

pkg/systemd/hwinfo.jsx
=> hwinfo: add missing cockpit-dark-theme import

test/verify/check-kdump, tools/debian/rules
`dh_install --fail-missing` has been deprecated for a while and got 
removed in dh compat level 12 (which we use). Use `dh_missing` instead.
We can drop the override once we move to dh compat level 13. This fixes
the warning during build:
dh_install: warning: Please use dh_missing --list-missing/--fail-missing instead
dh_install: warning: This feature will be removed in compat 12.
=> tools: Bring back missing files check in Debian packaging

test/static-code
Without "--tap", test/static-code would be silent about skipping tests.  This might cause people not to notice that they are not running the full suite.
=> test: Warn when static-code skips a test

test/verify/check-connection, test/verify/check-examples, test/verify/check-packagekit, test/verify/check-system-services
We want to be able to quickly know how many tests are skipped due to python bridge so this makes it easy to just search for 'python bridge' in test results.
For example, if I search for `python bridge` in [this log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18121-20230104-110815-da847583-fedora-36-pybridge/log.html) it shows 81 skips. There are 4 occurrences of `pybridge` but one of them is name of the scenario. And separately there is this "wedges hard" message. so all together 85 skips. There are 107 skipped tests, so 22 are skipped independently from python bridge. With this change I can just search for `python bridge` and see 85 straight away.
=> test: Use 'python bridge' when skipping tests

doc/authentication.md, selinux/cockpit.te, src/systemd/Makefile.am, src/systemd/cockpit-session.socket.in, src/systemd/cockpit-session@.service.in, src/ws/cockpitauth.c, src/ws/cockpitcreds.h, test/verify/check-connection, tools/cockpit.spec, tools/debian/cockpit-tests.install
cockpit.conf can now specify a unix socket address in the ConnectTo= field of a given authentication method.  If this is provided, and no Command= is present, then a connection will be opened to that address instead of spawning a command.                        
This is the "easy stuff" split out from #16808, and is already enough to help us with cockpit-cloud-connector.
=> ws: add support for connecting to unix sockets

test/verify/check-system-journal
It manages to pass sometimes.
For example [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18120-20230104-083837-3edbe1d8-fedora-36-pybridge/log.html#274)
=> test: TestJournal.testAbrtReport is flaky with Python

pkg/systemd/services/timer-dialog-helpers.js, pkg/systemd/services/timer-dialog.jsx, test/verify/check-system-services
Split off the minutely option https://github.com/cockpit-project/cockpit/pull/17592
---
The create timer dialog now allows to specify a minutely interval for systemd timers.
=> systemd: add minutely option to create timer modal

test/verify/check-packagekit
Test passed here https://cockpit-logs.us-east-1.linodeobjects.com/pull-18127-20230105-170902-7f10c11a-fedora-36-pybridge/log.html#113
=> test: mark testPackageKitCrash flaky on pybridge

test/common/testlib.py
Python 3.11 marks the throwing part of the line with a `^^^^^` marker of variable length. Ignore these in the pybridge scenario as long as we have ignored tracebacks there.
Fedora 37's sudo also stopped reporting non-suders to Santa's naughty list [1], adjust the error message.
[1] https://xkcd.com/838/
----
https://github.com/cockpit-project/bots/pull/4242 bumped TEST_OS_DEFAULT to fedora-37, which now causes pybridge failures [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4242-20230105-141645-5ea0d915-fedora-37-pybridge-cockpit-project-cockpit/log.html)
=> test: Update expected pybridge messages for fedora-37

test/image-prepare, test/run
This will prepare an image with the Python bridge for manual testing, in the same way as was done for the /pybridge scenario in test/run.
Simplify test/run to reflect the fact that this is now just an option to image-prepare.
=> test: add --python option to image-prepare

pkg/systemd/overview-cards/realmd.jsx, src/cockpit/channels/dbus.py, test/verify/check-system-realms
realmd's ObjectManager is on the primary manager object (`/org/freedesktop/realmd` aka. `MANAGER`), not at proxies()'s default path_namespace `/`.
The C bridge papered over this with its ObjectManager emulation, but the Python bridge does not do that.
Unfortunately testQualifiedUsers is still broken with the Python bridge, it fails later on the Services page with "interactive authentication required". This is unrelated to realmd, though.
-----
[attempt 1](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18143-20230109-102959-5a0811fe-fedora-37-pybridge/log.html#32)
=> systemd: Fix ObjectManager path for realmd, improve error logging

pkg/shell/nav.scss, test/common/test-functions.js, test/common/testlib.py, test/verify/check-networkmanager-basic, test/verify/check-users
This commit introduces a new pixel test scenario for RTL (Right to Left). This scenario keeps using English for language but changes the direction of the language to be RTL.
The reasoning behind this choice is that pixel tests take screenshots in the middle of tests execution, by dynamically adopting the theme, browser size etc for the different scenarios.
However in order to change the UI language one needs to reload the page, which effectively means losing the application state. For this reason, we would need to set the language at the very beginning of each test if we wanted to properly test RTL with a language like Hebrew.
Since this means making a whole test run in another language, we decided that we will for the time being test RTL with English. This is obviously an unrealistic …
=> tests: pixel-testing: introduce a scenario for RTL

src/cockpit/channels/dbus.py, src/cockpit/internal_endpoints.py
I am debugging the "python.error" in the log which we get on the Overview page, which is throughly unhelpful. The first commit turns this into both a JS log:
```
File "/usr/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 321, in do_call
reply = await self.bus.call_method_async(self.name, path, iface, method, signature, *args,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/systemd_ctypes/bus.py", line 382, in call_method_async
message = self.message_new_method_call(destination, path, interface, member, types, *args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/systemd_ctypes/bus.py", line 349, …
```
=> python: Fix "python.error" JS warning

src/cockpit/packages.py
We no longer build the bridge as a Python zipfile with packages included.
=> python: drop zipfile support in cockpit.packages

pkg/base1/test-dbus.js, src/cockpit/bridge.py, src/cockpit/config.py, src/cockpit/internal_endpoints.py, src/cockpit/packages.py, src/cockpit/protocol.py, test/pytest/test_browser.py, test/verify/check-shell-menu
These behave like the C bridge, except that the bridge now logs a
warning if a config key is expected to be an integer, but isn't. That
will help admins to track down why their config change is not effective.
----
- Builds on top of PR #18147
=> python: Implement /config and /environment internal bus objects

src/cockpit/channels/dbus.py, test/verify/check-storage-format, test/verify/check-superuser
This is what the C bridge does, and some parts of Cockpit rely on it.
=> pybridge: Don't timeout D-Bus method calls by default

pkg/lib/packagekit.js, pkg/packagekit/updates.jsx, test/verify/check-packagekit
This has always been racy due to the short 0.5s timeout. This often timed out    
with the Python bridge, as PackageKit isn't the fastest thing on earth. Butit's    
also not necessary at all: We already get told about property updates via the    
`notify` handler.    
So let's rework this to make the whole structure a lot simpler: Turn    
ApplyUpdates into a pure functional component, and drop its second    
watchTransaction() for packages. Let OsUpdates' watchTransaction() pick up    
`Packages` signals and all property values. This works because the initial    
`notify` event always includes the full set of properties.    
Also improve the initialization: At the beginning of an update we usually get    
`Percentage` properties from PackageKit before the first `Package` signal. If …
=> packagekit: Avoid redundant property GetAll() call on update transaction

src/cockpit/channels/dbus.py
sd_bus_call()'s timeout is in microseconds, while our API is in milliseconds. Convert the timeout appropriately.
[1] https://www.freedesktop.org/software/systemd/man/sd_bus_call.html
----
This should "accidentally" fix most PackageKit tests, [letting this run once](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18163-20230112-111112-e9b5d701-fedora-37-pybridge/log.html) . But PR #18155 fixes them in a much more elegant way, so I'll wait for that to land to avoid collisions on removing `@todoPybridge`.
=> python: Fix D-Bus timeout

containers/unit-tests/start
This *will* fail on any PR which changes package.json/rebuilds node_modules, with "Unable to find any suitable commit". That's fine, we have to bite the bullet and rebuild the webpack ourselves then. We could alternatively use `--wait`, but that would not save wallclock time, just some CPU usage.
Do the same thing as test/run, and ignore failures.
----
This broke e.g. in PR #18157 [like this](https://github.com/cockpit-project/cockpit/actions/runs/3901936824/jobs/6664384863). This is also the reason why each npm-update bot PR like PR #18414 [fails its first run](https://github.com/cockpit-project/cockpit/actions/runs/3870398368/attempts/1), and the [retry](https://github.com/cockpit-project/cockpit/actions/runs/3870398368) works after the "build jumpstart cache" workflow finishes.
=> containers: Make webpack-jumpstart --partial in unit test opportunistic

pkg/storaged/crypto-keyslots.jsx, pkg/storaged/manifest.json, test/common/packagelib.py, test/common/storagelib.py, test/verify/check-storage-luks
Outdated demo: https://www.youtube.com/watch?v=mbv-syeLHsc
------
Release note:
It is possible (and unfortunately liklely) that a system is misconfigured and can not mount filesystems during boot that rely on Clevis to unlock them. Cockpit can now fix this when adding a keyserver to a encrypted filesystem.
=> storage: Checking and fixing system config for NBDE

.gitignore, pkg/systemd/overview-cards/realmd.jsx, src/cockpit/packages.py
This provides the moral equivalent of what commit 94394128e8b6 did for    
the C bridge. However, we want to avoid parameterizing the py bridge    
with ./configure arguments, to keep it buildable with pip. Detect the    
path at runtime instead, there are only a few plausible options anyway.    
This is a temporary hack until we eliminate all `${libexecdir}` from    
manifests.    
This fixes joining an IPA domain, as it now finds    
cockpit-certificate-helper. TestIPA.testQualifiedUsers now gets much    
further, unfortunately it still fails on the remote host part of the    
test, as cockpit-ssh does not work yet.    
It also fixes the cockpit-{ssh,pcp,askpass} paths in the manifests, but as we    
don't do that routing yet, it does not fix any of the ssh/pcp tests yet.    
But it is …
=> python: Add temporary ${libexecdir} expansion in manifests

src/bridge/cockpitcpusamples.c, src/cockpit/samples.py, test/pytest/test_samples.py
For AMD CPU's a Tctl and Tccd1 sensor exists, we want to show the values from Tccd1. HWmon devices do not show up how we expect them, we expect them to show up as 1,2,3 but for k10temp it reports as 1,3 so we never showed the value of Tccd1 as it's temp3_label for me.
I'd love to add a test for the Python bridge but unsure how easy it is. I also dislike the solution a lot, maybe we can count the times we can't open a sensor and if it's more then ~ 5 we break the loop?
=> bridge: AMD CPU temperature detection

pkg/storaged/nfs-mounts.py, test/verify/check-storage-nfs
readlines() keeps the `\n` line endings, so joining the array with `\n` caused extra empty lines to be inserted between each existing line. Move to splitlines() instead, which strips the `\n` and also makes the `del` special case obsolete.
Make the integration test much more picky: Don't just assert the single line we expect to get added, but the full file. This will catch not only extra empty lines, but also accidental removals or unexpected ordering.
https://bugzilla.redhat.com/show_bug.cgi?id=2160256
=> storaged: Fix writing fstab when modifying NFS mounts

src/cockpit/peer.py, src/cockpit/router.py, src/cockpit/superuser.py, test/pytest/test_bridge.py, test/verify/check-examples, test/verify/check-metrics, test/verify/check-system-info
This is my best guess about why `TestLongRunning.testBasic` is failing.  Let's see if it helps.
=> python: Add support for freezing endpoints

src/cockpit/channels/metrics.py
A conditional in the bridge aims to return a rate of change if it has a previous value from which to calculate a change, and the value "False" otherwise.  In case there is no previous value, it would be None.
Unfortunately that was coded like
```python
if old_value:
```
instead of
```python
if old_value is not None:
```
which means that if `old_value` happened to be `0`, we would keep reporting the rate of change as "false".
It just so happens that depending on which other tests ran before the `@nondestructive` `TestCurrentMetrics.testCPU`, the amount of "nice" CPU usage may or may not be zero, causing this bug to be triggered only sometimes.
When triggered, this was causing the CPU percentage to show up as NaN%.
=> python: metrics: fix rate calculation with 0 values

pkg/base1/test-spawn-proc.js, src/cockpit/channels/stream.py, test/verify/check-sosreport
This is being used to terminate a process, like on the sosreport page.
---
Goes on top of PR #18181, mostly to avoid test change conflicts.
=> python: Implement closing of spawn channels

pkg/build, tools/webpack-make
Make sure we include the following dependencies, unconditionally, in each _INPUTS list:
- webpack-make
- package-lock.json
- webpack.config.js
We previously handled those depends from the pkg/build Makefile, but now that we're making increased used of partial jumpstarts, we need to make sure these depends also end up in the Makefile so that we don't jumpstart files from across webpack configuration changes.
=> webpack-make: include static depends in Makefile

test/verify/check-system-terminal, webpack.config.js
The python bridge doesn't know how to decompress gzip, and -ws requires HTML to be decompressed so that it can patch it while serving it to the client.
All of our .html pages are small anyway, and since we're serving them uncompressed, we may as well also have them on disk uncompressed, saving ourselves the trouble.
=> webpack.config.js: don't gzip .html pages

test/verify/check-system-journal
I can't get this to fail locally.
=> DBG - Mark TestJournal.testAbrtReportCancel as stable

pkg/packagekit/updates.jsx, src/cockpit/channels/stream.py, test/verify/check-reauthorize, test/verify/check-storage-luks
Set `prctl(SET_PDEATHSIG, SIGHUP)` for cockpit.spawn() and friends, to clean up subprocesses of the spawned process. The C bridge does that also (in cockpitpipe.c).
=> python: Clean up children of spawned processes

src/cockpit/bridge.py, src/cockpit/protocol.py, test/common/testlib.py, test/verify/check-system-info
In the Python bridge we setup a logger per module such as "cockpit.packages". By setting the COCKPIT_DEBUG environment variable we can now specify which modules we want to see logs for (comma separate values). If you want to see logging for all modules set COCKPIT_DEBUG to "all".
Setting COCKPIT_DEBUG also sets the log level to debug.
=> python: allow filtering of log messages on module names

test/common/chromium-cdp-driver.js, test/common/firefox-cdp-driver.js
But leave the code in place in case we need to switch this on again.
=> test: Don't swallow duplicate Browser messages by default

pkg/storaged/format-dialog.jsx, pkg/storaged/fsys-tab.jsx, test/common/storagelib.py, test/verify/check-storage-mounting
The "Mount configuration" dialog unmounts the filesystem, changes fstab, and then re-mounts it.  However, if neither the mountpoint nor the options would change, the last two steps would be skipped, leaving the filesystem accidentally unmounted.
This is fixed here by not optimizing empty changes.  This is what other storage dialogs also do.
=> storage: Assorted fixes, part 17

src/cockpit/channels/stream.py, test/pytest/test_transport.py, test/verify/check-system-terminal
Apply the user provided `environ` option, which makes the terminal page tests pass as now TERM is set to something sensible.
=> python: apply user provided env variables

src/cockpit/channels/stream.py
Commit e100e4d8b introduced a race condition: asyncio installs a "child    
watcher" (via pidfd) for all launched subprocesses, and expects it to be    
able to read the processes' exit code. But subprocess'es terminate()    
method *also* does that. If the process is still running, this is    
harmless (as it will just return None), but if the process terminates    
around the same time as cancelling it, it can happen that the process    
stopped in terminate(), it waits() the child and collects the exit code,    
and asyncio's child watcher then does not get it any more. This causes    
warnings like    
asyncio:child process pid <PID> exit status already read:  will report returncode 255    
We actually want to retain that; terminate()'s wait call is just for    
avoiding PID reuse …
=> python: Avoid waiting for the child in SubprocessStreamChannel.do_close()

test/verify/check-storage-vdo
See https://github.com/cockpit-project/bots/pull/4291 . I tested this locally against thew new RHEL image, and also triggered a run against the refreshed image here.
=> test: Adjust VDO tests for latest RHEL 9.2 image

pkg/base1/test-file.js, src/cockpit/channels/filesystem.py, test/verify/check-shell-keys, test/verify/check-system-info
NamedTemporaryFile always creates files with 600 permissions, thus    
making e.g. /etc/motd unreadable for users (which breaks    
TestSystemInfo.testMotd).    
Unfortunately there is no good Linux API for atomically replacing a file    
as user:    
* mkstemp() and friends create too tight permissions.    
* chowning the file after writing would be fine, but Linux has no API    
to get the current umask other than scraping it out of /proc (and    
calling umask(2) twice is a race condition and ugly).    
* open(O_TMPFILE) would be cool, but it's not supported on some    
file systems (e.g. not on overlayfs or NFS), and does not work with    
existing files [1].    
So, move to the same "Find a free file name ourselves" approach that the    
C bridge does, but use a random 6-character …
=> python: Respect umask in fsreplace1

test/verify/check-storage-lvm2, test/verify/check-storage-resize
https://github.com/storaged-project/udisks/pull/631 landed four years ago in udisks 2.8.2. Even RHEL 8 has 2.9.0.
Likewise for check-storage-lvm2, tests run fine without the extra trigger.
=> test: Drop obsolete udevadm trigger hacks

test/run
We want the tests to generate full coverage information for all pages in the /devel scenario, not just for the ones affected by a PR.
----
See e.g. [this log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18203-20230118-140114-7fa0948c-fedora-37-devel/log) from PR #18203 which touched pkg/systemd only:
```
FETCH    dist  [ref: tag sha-34d12a403e4cf029c7f5e99b8b87b3206101c331]
REMOVE   dist/systemd
WEBPACK  systemd
```
With this change, we'll go back to rebuilding everything.
=> test: Disable partial webpack jumpstart for devel scenario

test/verify/check-metrics
The test calls firewall-cmd at the beginning on arch, but it previously happened a lot that firewalld was not running. Move the starting earlier to fix that.
----
Should fix [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18183-20230118-140022-0e5ecfac-arch/log.html#67-2), which happens in every other PR right now. [another example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18206-20230119-140747-26fe7912-arch/log.html)
=> test: Fix testPmProxySettings on arch

src/Makefile.am
See https://fedoraproject.org/wiki/Changes/PortingToModernC
=> Move to gnu18 C standard, fail on old C constructs

src/cockpit/packages.py, test/pytest/test_packages.py
Implement serving po.js files based on the Accept-Language header. So far this only implements it for normal pages, for the shell we need to rewrite the currently used `/*/po.js` implementation into something else (follow up).
=> Serve po.js in the Python Bridge

pkg/systemd/logDetails.jsx, pkg/systemd/logsHelpers.js, pkg/systemd/services/service.jsx, test/browser/run-test.sh, test/verify/check-system-services
The Services page now shows journal logs for user systemd services.
---------------------------
Removes the limitation mentioned in https://github.com/cockpit-project/cockpit/commit/154da47d947eb39ebf2bed4cf6e1ecfc1623a25e:
> * Hide service logs for user services. These are available but the
LogsPanel component will need some extension for supporting it.
=> Show service logs for user services

pkg/selinux/setroubleshoot.js, test/verify/check-selinux
When cockpit.script(runCommmand) or deleting an error fails, we catch an    
"error" object. Don't try to stuff that into the `<Alert>` as-is, as it    
will make React crash with    
RuntimeError: Error: Objects are not valid as a React child (found: [object Error]).    
Convert the errors to a string first.    
That does not fix the underlying reason/race condition why applying the    
solution sometimes fails in TestSelinux.testTroubleshootAlerts, but it    
will make the failure a lot more useful both for the user and the test.    
-----
This addresses a common flake, [example 1](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18169-20230113-155342-727d20de-centos-8-stream/log.html#138), [example 2](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18169-20230113-155342-727d2 …
=> selinux: Fix React crash on API/CLI errors

pkg/packagekit/kpatch.jsx
TestSystemInfo.testBasic remove /etc/os-release, for example.
=> kpatch: Tolerate missing /etc/os-release

pkg/shell/nav.jsx
* Don't assume 'active' state of dropdown when toggling the 'interact' class.
* Call the addEventListener only on component mount, and not each time the 'active' state changes.
Fixes #18182
=> nav: fix toggling of the system dropdown

package.json, pkg/lib/cockpit-components-terminal.jsx, pkg/lib/console.css
The 'xterm-canvas-addon' is now used because the new version of the original xterm renderer is using inline styles which we block with our strict CDP. https://github.com/xtermjs/xterm.js/issues/4133
The above add on was chosen against https://www.npmjs.com/package/xterm-addon-webgl because we can't rely on webgl being enabled on users browsers.
With the usage of the renderer addon we can now remove most of the custom CSS, which is anyway not applied as many of the classnames in xterm Terminal changed.
The new xterm release was a breaking changes one and thus some of the component properties changed - therefore the c-c-terminal was adopted to the new APIs.
Fixes #18138
=> terminal: update xterm dependency and start using an add on for the canvas

test/common/testlib.py
These got addressed by recent bug fixes.
=> test: Drop obsolete pybridge expected log messages

src/cockpit/channels/filesystem.py
Or do you prefer to special case this? if `fd is None`: lala
=> python: correctly log possible None value

pkg/shell/nav.jsx
See https://github.com/cockpit-project/cockpit/issues/18182#issuecomment-1401641783
Fixes #18182
=> shell: unset 'active' state also when closing the menu by clicking on the same iframe

pkg/base1/test-dbus.js, pkg/networkmanager/firewall-client.js, pkg/networkmanager/firewall.jsx, src/cockpit/channels/dbus.py, test/common/testlib.py, test/verify/check-networkmanager-firewall
As per documentation [1], send an `owner: null` signal when a D-Bus
service does not exist. That's what the C bridge does, and at least the 
Firewall page relies on that.
[1] https://cockpit-project.org/guide/latest/cockpit-dbus.html#cockpit-dbus-onowned
=> python: Send null owner D-Bus signal for absent services

src/bridge/cockpitcpusamples.c
Commit 6b1ce057e reworked this and introduced an "unchecked return" coverity error for sscanf(). Check it, and drop the redundant suffix check.
=> bridge: Robustify temperature sensor scanning

test/common/testlib.py
That was also removed in commit 89bd6896883, but still happens occasionally. But it did *not* happen in testSessionRecordingShell but in testLogging, so move it into the block which covers the rest of the exception.
---
Fixes https://cockpit-logs.us-east-1.linodeobjects.com/pull-17992-20230125-145211-18fde629-fedora-37-pybridge/log.html#145
=> test: Put back another pybridge crash message

test/common/chromium-cdp-driver.js, test/common/firefox-cdp-driver.js
This makes the main function much less nested and simplifies the error handling. Also move to the readline API [1] instead of doing the buffering ourselves.
[1] https://nodejs.org/api/readline.html
=> test: Rewrite chromium-cdp-driver.js using async/await

src/ws/Makefile-ws.am
find-debuginfo(1) only considers executable files for debug info extraction. We installed most of our PAM libraries as executable already, but not mock-pam-conv-mod.so. That causes rpminspect to complain that a non-debug package contains debug symbols.
----
This fixes a [long-standing rpminspect failure](https://artifacts.dev.testing-farm.io/21ae9e81-96e6-4122-9ccc-d5e80c71f1b1/) that we have to waive all the time. Let's fix it properly.
Now the rpm build log shows that it finds the lib and its debug symbols:
```
/usr/bin/find-debuginfo -j8 --strict-build-id -m -i --build-id-seed 284.7.gabb9ed480.dirty-1.fc37 --unique-debug-suffix -284.7.gabb9ed480.dirty-1.fc37.x86_64 --unique-debug-src-base cockpit-284.7.gabb9ed480.dirty-1.fc37.x86_64 --run-dwz --dwz-low-mem-die-limit 10000000 …
```
=> ws: Fix rpm debug symbol extraction for mock-pam-conv-mod.so

test/common/testlib.py
This way external projects can still use a browser-layouts.json file that includes a "dark" themed variant.
=> test: Filter out "dark" layout after reading custom layouts

test/common/testlib.py
In Fedora rawhide this started to fail often with
Could not kill session: No such file or directory
This is okay -- it's an inherent TOCTOU race condition, sessions can get cleaned up during the loop. This is some late fallout from .execute() getting strict [1], it just happened to (mostly) work until now.
[1] https://github.com/cockpit-project/bots/commit/b7d0edba5d02
----
This avoids occasional failures like [this](https://artifacts.dev.testing-farm.io/b686f17b-c254-4e0a-a76f-d06304392c61/#artifacts-Fedora-Rawhide:x86_64:/plans/all/optional), or the [complete mess](https://artifacts.dev.testing-farm.io/01a177c2-f55c-4471-8102-9eb75cfef9d5/) that breaks the current [284 rawhide update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-44a632e396). Recently, all our rawhide packit tests …
=> test: Fix session cleanup for rawhide

test/image-prepare, tools/make-wheel
This is the entrypoint for building a wheel from the current checked out source tree.  It makes sure systemd_ctypes is available.
This is intended to be used as an API from various subprojects that want to test against the Python bridge.
=> build: add tools/make-wheel

src/cockpit/transports.py, test/common/testlib.py
It turns out that IOError is an extremely confusingly-named alias for OSError, and *not* an OSError where errno == EIO.  This means that our normal error handling block wasn't being hit, and we were often raising the exception instead of terminating the connection.
Thanks to @jelly for the investigation work.
=> python: fix check for EIO in Transports classes, fix cancelled D-Bus calls

pkg/systemd/overview.scss
Overview's breakpoints have been a bit fiddly for some time. This simplifies the breakpoints and makes columns either 1 (mobile) 2 (default) or 4 (large screen), purposefully avoiding the case where it has 3+1.
=> overview: Simplify card flow breakpoints

selinux/cockpit.te
https://bugzilla.redhat.com/show_bug.cgi?id=2165996
=> selinux: Allow cockpit-session to run gnome-keyring

src/cockpit/channels/filesystem.py, test/pytest/test_bridge.py
Teach check_open() about validating the `message` part of `close`, when given.
----
Leftover from https://github.com/cockpit-project/cockpit/pull/18257/commits/f128b1b3991481b4e0e1aede8c431a81fea6ddee#r1090499063
=> python: Report detailed error message when opening fsread1 channel fails

src/cockpit/channels/filesystem.py, test/pytest/test_bridge.py
Trying to list a nonexisting directory crashed the bridge. Report a    
proper channel problem instead.    
Add unit tests.    
----
This fixes the last [cockpit-machines failure](https://github.com/cockpit-project/cockpit-machines/pull/935). I ran `TestMachinesFilesystems.testBasicSystemConnection` with this fix and it passes now.
=> python: Fix fslist1 FileNotFoundError crash

pkg/lib/cockpit-po-plugin.js
This is basically all translations of plugins that live in external repos.
Fixes #18286
=> lib: cockpit-po-plugin: allow also msgids from 'src/' directory

doc/protocol.md, pkg/base1/test-stream.js, src/cockpit/channel.py, src/cockpit/channels/__init__.py, src/cockpit/channels/stream.py, src/cockpit/transports.py, test/pytest/test_transport.py, webpack.config.js
This will fix c-machine's [console test failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-935-20230203-091154-9b4701a9-fedora-37-pybridge/log.html), see https://github.com/cockpit-project/cockpit-machines/pull/935 . I locally ran all the console tests with this pybridge update, and they pass now.
=> Document and test TCP stream channel, implement it for the pybridge

test/verify/check-users
Drop the flaky part as in 3c1d86d3fe3bd1c12c the leaking watchers and inefficient calling of cockpit.spawn for every user has been improved.
In the PR which introduced this commit the python bridge test succeeded.
=> test: enable TestAccounts.testBasic on Python bridge

src/cockpit/packages.py
cockpit-certificate-helper was a poor choice, because it is shipped in cockpit-ws. That isn't a dependency of any of our packages, and in particular it is neither installed nor desired on our Fedora CoreOS image. Thus change it to "cockpit-askpass", which is shipped in the cockpit-bridge package.
---
This goes a long way towards fixing cockpit-ostree with the pybridge, see https://github.com/cockpit-project/cockpit-ostree/pull/323
=> python: Update libexecdir detection to look for a cockpit-bridge package program

containers/unit-tests/setup.sh
We are going to use it soon to cover the Python bridge.
---
See #18295 - that isn't ready yet, but I'd like to get the container update out of the way already, as it takes quite long to build in each PR.
=> containers: Add mypy to unit-tests

pkg/static/login.css
Make the background transparent, so it works in light and dark mode.
Fixes #18307
=> login: Change key verify command background

.github/workflows/release.yml
Should be https://github.com/cockpit-project/action-release/commit/88d994da62d1451c7073e26748c18413fcdf46e9
=> .github: fix extranous 'd' before commit message

.github/workflows/pybridge-c8s.yml, src/cockpit/bridge.py, src/cockpit/channel.py, src/cockpit/channels/packages.py, src/cockpit/channels/stream.py, src/cockpit/packages.py, src/cockpit/peer.py, src/cockpit/protocol.py, src/cockpit/router.py, src/cockpit/samples.py, src/cockpit/superuser.py, src/cockpit/transports.py, test/pytest/test_bridge.py, test/pytest/test_transport.py
With that, I can  run `PYTHONPATH=src python3 -m cockpit.bridge --packages` in a centos 8 container without crashing any more:
```
cockpit.packages-WARNING: Could not detect libexecdir
base1                                                         /usr/share/cockpit/base1
kdump                                                         /usr/share/cockpit/kdump
metrics                                                       /usr/share/cockpit/metrics
network                                                       /usr/share/cockpit/networkmanager
performance                                                   /usr/share/cockpit/tuned
selinux                                                       /usr/share/cockpit/selinux
shell …
```
=> python: Fixes for Python 3.6

src/cockpit/packages.py, test/pytest/test_packages.py
Split out from PR #18291, it's unrelated and a good fix in its own right.
=> python: Fix KeyError on overriding nonexisting manifest keys

pkg/networkmanager/dialogs-common.jsx, pkg/networkmanager/interfaces.js
Since NetworkManager 1.6.0 NetworkManager exposes capabilities as Dbus property if the Team feature is available.
=> networkmanager: use NetworkManager's Capabilities

test/pytest/test_code.py, test/pytest/test_packages.py
We need to divert `$XDG_DATA_HOME` as well to hide any existing ~/.local/share/cockpit/, to avoid assertion failures on on unexpected packages.
=> pytest: Fix TestPackages for environments with ~/.local/share/cockpit/

src/cockpit/channels/dbus.py
Initializing a global lock at program start is too early: At that point, systemd_ctypes has not yet initialized its own main loop. In Python 3.6 this causes tons of crashes like
RuntimeError: Task <Task pending coro=<DBusChannel.do_open.<locals>.get_ready() running at
/usr/lib64/python3.6/site-packages/cockpit/channels/dbus.py:251>
cb=[set.discard()]> got Future <Future pending> attached to a different loop
This also moves the lock from a class to an instance variable -- it's not necessary to globally order messages, doing it for a single channel is sufficient.
----
I split this out from PR #18318 , I think this causes some fallout, e.g. [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230210-093531-e2e439f3-fedora-37-pybridge/log.html#72) and …
=> python: Defer asyncio.Lock() creation for D-Bus

pkg/lib/cockpit-rsync-plugin.js
Adds the variable `RSYNC_DEVEL` for starter-kit.
`RSYNC_DEVEL` uses `~/.local/share/cockpit/` instead of `/usr/local/share/cockpit/`.
This helps for developing on a remote host.
=>  lib: Add development support for remote hosts 

doc/guide/packages.xml, pkg/packagekit/manifest.json, src/cockpit/packages.py, test/pytest/test_packages.py, test/verify/check-packagekit
These pave the way for bundling packages together with the webserver, and only showing them if the target system actually supports the corresponding functionality. For example, CoreOS does not have libvirt, so we can bundle but    
hide the "Machines" page on such systems.    
This also allows us to better handle ostree vs. packagekit -- even if a user installs cockpit-ostree on a standard RPM system, they should still see the packagekit version of "Software Updates" (see https://github.com/cockpit-project/cockpit-ostree/issues/295). This is a more flexible approach than the old static `priority` field.        
Take inspiration from systemd unit files, which support e.g. `ConditionPathExists=`. The conditions should be declarative and cheap to evaluate. Support file exists/not exists …
=> Support manifest conditions

containers/ws/Dockerfile
Blocks https://github.com/cockpit-project/bots/pull/4347. This cannot really be tested in CI, as that only updates the existing container. I have some difficulty testing this locally, as both on main and on this branch `podman build -t localhost/ws containers/ws/` fails with "RPM: error: Unable to change root directory: Operation not permitted".
I [built it on GitHub](https://github.com/cockpit-project/cockpit/actions/runs/4171076388) instead. This resulted in [tag 284](https://quay.io/repository/cockpit/ws?tab=tags). I ran `podman run -d --name cockpit-bastion -p 9999:9090 quay.io/cockpit/ws` and validated that I can log in at https://localhost:9999.
=> containers: Move ws to Fedora 37

test/verify/check-connection, test/verify/check-loopback, test/verify/check-superuser
This happens in the pybridge scenario once image-customize changes to
installing wheels into /usr/local [1]. We need while loops to cover all
installed "cockpit-bridge" commands.
[1] https://github.com/cockpit-project/bots/pull/4397
=> test: Get along with /usr/local/bin/cockpit-bridge

test/common/testlib.py, test/verify/check-apps, test/verify/check-connection, test/verify/check-examples, test/verify/check-kdump, test/verify/check-loopback, test/verify/check-metrics, test/verify/check-networkmanager-bond, test/verify/check-networkmanager-checkpoints, test/verify/check-networkmanager-firewall, test/verify/check-networkmanager-team, test/verify/check-packagekit, test/verify/check-pages, test/verify/check-reauthorize, test/verify/check-selinux, test/verify/check-sosreport, test/verify/check-static-login, test/verify/check-storage-iscsi, test/verify/check-storage-luks, test/verify/check-storage-multipath, test/verify/check-storage-nfs, test/verify/check-storage-stratis, test/verify/check-system-info, test/verify/check-system-journal, test/verify/check-system-realms, test/verify/check-system-tuned, test/verify/check-users
Add globbing support in testlib.skipImage() and add testlib.skipOstree(). This makes it easier in the future to add/remove OSes.
=> test: Factorize OS specific test skips

pkg/metrics/metrics.jsx
The missing data are between the oldest_timestamp and the oldest item in the 'hours' list, which is the end of the list not the start.
=> metrics: fix error message about missing data from PCP

src/cockpit/channel.py, src/cockpit/channels/dbus.py, src/cockpit/channels/stream.py, src/cockpit/peer.py, src/cockpit/protocol.py, src/cockpit/router.py, test/common/testlib.py, test/pytest/test_bridge.py
Let's split this out from #18292 (which looks to have gained a dependency on #18340, which itself, needs work).
Let's make sure we wind down all tasks when closing the bridge.  This is implemented in two steps, basically:
- no channel may send "close" until all of its tasks are complete
- the bridge may not exit until all channels have sent "close"
=> python: close all tasks before exiting the bridge

src/cockpit/channel.py, src/cockpit/peer.py, src/cockpit/router.py, test/verify/check-shell-active-pages
Drop the logic for keeping track of which channels belong to which groups and just call .do_kill() on every endpoint that the router knows about, with the group and host details.
That slow, but 'kill' happens fairly infrequently.
Channel now keeps track of its own group on open and implements .do_kill() by calling the .do_close() handling if the group matches. Peer simply directly passes the message on to the peer.
This let's us drop one more `@todo`.
Fixes #18244
=> python: simplify "kill" logic in router

test/verify/check-users
TestAccouts.testBasic way too big. Split it into several smaller tests. Additionally, abstract account creation dialog handling into a separate method.
Split from https://github.com/cockpit-project/cockpit/pull/18234
=> test: Refactor accounts test

src/cockpit/channels/dbus.py
For DBus interfaces that notify property invalidations (without specifying the new value) we immediately try to "Get" the new value so that we can send it to JS.  The call to do this was missing a try: to catch the BusError which might result if that Get call fails.
Catch the failure and log a debug message.
Fixes #18358
=> python: catch BusError on Properties.Get

src/cockpit/transports.py
In 95bffd540ce450792341b99d80ffc98762158c8e we implement our own "safe" signal sending logic.  In order to avoid sending signals to PIDs that may have been recycled, we carefully go out of our way to detect if the process has exited, log a message about it, and then ... send the signal anyway.
Add the obviously-missing `return` statement.
=> python: don't signal already-exited processes

src/cockpit/bridge.py
This supports asyncio.run()'s debug argument and D-Bus name owning API 
(paving the way for rewriting the unit test D-Bus mock server in
Python).
Revert the debug= bits from commit cbcd6ecc4a41, we can simplify this
again.
=> modules: update systemd_ctypes

pkg/lib/cockpit-po-plugin.js, pkg/lib/cockpit-rsync-plugin.js, tools/webpack-make.js, webpack.config.js
- Pull out the common code into init() and run() functions, which leaves the webpack/esbuild glue relatively small.
- Stop having a default export. The bundler config now explicitly needs to import the webpack or esbuild plugin.
---
This was developed in https://github.com/cockpit-project/cockpit-podman/pull/1210 , originally against cockpit-podman. I validated that generated po files are identical, and that watch mode with and without an rsync target work as expected, on all of cockpit, podman with esbuild, and podman with webpack.
=> lib: Make PO and rsync bundler plugins work for webpack and esbuild

test/browser/browser.sh
The import syntax introduced in commit 54f2fd58a364 does not work with the old node.js 10 which is still the default in RHEL 10. Install the newer version 16 instead.
I did that on all other projects (like [1]), but forgot it here.
[1] https://github.com/cockpit-project/starter-kit/pull/625
----
It's likely that this will still fail some tests, as we introduced a regression earlier on (which is why this failure slipped through), but this should turn this [complete disaster](https://artifacts.dev.testing-farm.io/ec3b56e4-1ebe-4995-be0d-a80ce1d7546b/) into "most tests work".
=> fmf: Use node.js 16 for RHEL 8 tests

pkg/users/accounts-list.js, test/verify/check-users
The default is to render it inline. However, our tests showed that the clicks were often eaten (actions dialogs not opening causing flakes). I blame this on the Table component messing up with the events, so let's unnest the actions Dropdown from the Table as a fix.
=> users: append's dropdown's menu to document body

test/verify/check-metrics, test/verify/check-networkmanager-basic, test/verify/check-pages, test/verify/check-shell-menu, test/verify/check-shell-multi-machine, test/verify/check-static-login
Prefer using `ostree_image` so we can easily add a new ostree variant for testing.
=> test: use Machine.ostree_image where possible

src/bridge/cockpitcpusamples.c, test/verify/check-metrics
Fixes: #18335
Also adds files containing critical cpu temperature so our tests catch if incorrect values are sampled.
=> Fix cpu temperature sensors detection - FIX COMMIT MESSAGE ON LANDING

tools/webpack-make.js
When changing the po plugin our webpack's should be rebuild.
=> tools: add po plugin as input for webpack-make

test/common/testlib.py
This was dropped in commit 435af1259e29d, but still happens occasionally on Fedora 37, and a lot on RHEL/CentOS 8. This should be addressed by PR #18274, but until that lands, we still need this filter.
----
[Fedora 37 example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-960-20230222-075223-9dce209d-fedora-37-pybridge/log.html#44), [c8s example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230217-121320-2cbd5f4d-centos-8-stream-pybridge/log.html#135)
=> testlib: bring back "task destroyed but pending" messages

test/browser/run-test.sh
This test fails in about 80% of runs on RHEL Testing Farm machines:
```
File "tests/test/common/cdp.py", line 298, in start
res = urllib.request.urlopen(f"http://127.0.0.1:{cdp_port}/json/list", timeout=5)
socket.timeout: timed out
```
When it tries to open `b2` (the second browser instance). Waiting longer does not help, this is thoroughly broken. As there is little to no chance to debug this in a hurry without access to the affected machines, and it does not happen on the public TF ranch nor our own CI, skip the test on RHEL.
=> fmf: Skip TestAccounts.testUserPasswords

configure.ac, packit.yaml
Actually check for the "xgettext" binary in the relevant section. xsltproc is already checked further down, conditionalized by --enable-docs. The latter is also in a different package.
See https://github.com/cockpit-project/cockpit/discussions/18408
=> configure: Fix check for xgettext

pkg/lib/esbuild-compress-plugin.js, pkg/lib/esbuild-eslint-plugin.js, pkg/lib/esbuild-stylelint-plugin.js
There are existing plugins on npmjs.com for these tasks, but they are not good enough yet. See the comments at the top for details.
With these, we now have all the tools to build Cockpit pages with https://esbuild.github.io/.
----
Taken from https://github.com/cockpit-project/cockpit-podman/pull/1210 . Once this lands, we can pull them into cockpit-podman.
=> lib: Add esbuild plugins for eslint, stylelint, and compression

pkg/base1/test-file.js, pkg/lib/qunit-tests.js, webpack.config.js
This is still incompatible with esbuild and also older nodejs versions.
----
@KKoukiou : This should help with esbuild-ifying cockpit itself. Any other trouble?
=> base1, lib: Avoid top-level await

pkg/systemd/services/service-details.jsx, pkg/systemd/services/service.jsx, pkg/systemd/services/services.jsx
Judging by the .filter() call, this had been the intention from the        
start. There is no advantage with tracking the object paths instead:        
* They are not any more unique than IDs, they are even the same for        
system and user units.        
* They require an extra LoadUnit() to compute, which we want to stop        
doing.        
* They are an internal implementation detail of systemd, which can        
change in principle.        
This is a breaking change, as it will disregard existing        
`systemd:pinnedUnits` settings from localstore. This has existed for        
less than a year (commit 065bf82d83), is not very easy to discover, and        
is not crucial, so we can hopefully get away with it.        
----
Also add some code cleanup.
The data storage for …
=> systemd/service: Track pinned units by unit name (ID), not object path; code cleanups

pkg/systemd/services/services.jsx, test/verify/check-system-services
The `locationchanged` event does not fire when the page gets first loaded, or reloaded. I.e. a bookmarked URL with a filter would still show all units, until the filter on the page or the URL got changed manually. Initialize it when showing ServicesPageBody to fix this.
Update TestServices.testServicesFiltersURLConsistency to actually check the result of the filters, and cover the "reload" case too.
=> systemd/services: Initialize filters from first URL load

test/common/testlib.py
In the last few weeks we have been getting a lot of random test failures like this:
```
File "test/verify/check-system-terminal", line 51, in testBasic
self.login_and_go("/system/terminal")
[...]
self.wait_visible("#login")
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
```
where the page was just blank, but there is no error in the journal. This happens especially often on the rhos-01 nested virt machines. As the first login after starting cockpit on demand can take longer on loaded machines, increase the timeout.
----
[recent example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18422-20230303-075148-3f6b1c8a-arch/log.html#260-2). I see this all the time, but so far I …
=> test: Increase timeout for first Cockpit login

test/verify/check-system-info
This seems to matter on rhel4edge: https://cockpit-logs.us-east-1.linodeobjects.com/pull-17888-20230302-131217-6e09dda4-rhel4edge/log.html#233
I think enabling insights-client.service is wrong, in general.  It is started by a timer, normally, and doesn't need to be enabled.  Also, there is the additional insights-client-boot.service for running it on the next boot.  So I don't know what insights-client.service is enabled for.
=> test: rhel4edge insights-client improvements

HACKING.md
This fixes https://github.com/cockpit-project/cockpit-project.github.io/pull/544
=> hacking: Wrapped URLs in `<>` to make them linkable on the website

pkg/storaged/content-views.jsx, pkg/storaged/storage-controls.jsx, pkg/storaged/storage.scss, pkg/storaged/stratis-details.jsx
Closes #18415.
Dangerous menu items, such as 'Delete', were not highlighted in a red color correctly.
I added a 'danger' property to the `tab_menu_danger_actions` array, to identify the items in `StorageMenuItem`.
Here is a screenshot:
I think this makes the separate 'danger' array redundant, since they get merged into one array later. It could simply be one array with a 'danger' property set to false/true. I'm not sure if that would break the separator line placement, but I think placing it afterwards when the array is full won't be an issue.
Please let me know what changes I should make to this PR, I'm open to trying a different approach if needed. Thanks!
=> Storage: Correctly highlight dangerous menu items in red 

test/browser/main.fmf
These images seem to have contained it until recently, but now we need to ask for it explicitly.
=> test: Install dnf-automatic into TMT images

pkg/systemd/services/busnames.js, pkg/systemd/services/service-details.jsx, pkg/systemd/services/service.jsx, pkg/systemd/services/services-list.jsx, pkg/systemd/services/services.jsx, test/verify/check-metrics, test/verify/check-networkmanager-basic, test/verify/check-pages, test/verify/check-reauthorize, test/verify/check-system-realms, test/verify/check-system-services
The services list does way too much: It loads all units, even the ones which are completely unused, and thus systemd intentionally ignores them. On top of that, it was getting all properties of all interfaces of all units plus installing proxies, so loading the page required an avalanche of (literally) thousands of D-Bus messages; and it was not even using most of the properties in the summary view.
This PR optimizes this, and drops all extended test timeouts related to the services page. Please see the individual commits for details.
---
TODO/Blockers:
Spotted flakes while working on this, which are independent:
Follow-ups for further optimization:
=> systemd/services: Avoid excessive D-Bus calls and simplify state management

test/common/testlib.py, test/verify/check-shell-host-switching, test/verify/check-shell-multi-machine, test/verify/check-superuser, test/verify/check-system-shutdown-restart
Introduce a new helper function which sets the hostname for all test machines, disables preload of pages when required and adds an Arch Linux systemd 253 / sssd related workaround. This writes all provisioned machines to /etc/hosts so DNS resolving is speedy.
=> test: add setup_provisioned_hosts helper for multi machine tests

doc/guide/cockpit-channel.xml, doc/guide/cockpit-dbus.xml, doc/guide/cockpit-file.xml, doc/guide/cockpit-spawn.xml
We want to move away from running commands on a different connected host from JavaScript. In the future we will completely block the ability to specify a different host then the current iframe's host.
=> doc: drop host option from our documentation

test/common/testlib.py, test/verify/check-shell-multi-machine, test/verify/check-static-login
In TestHostSwitching.testBasic, the auxiliary machines often fail to load software updates. This breaks the pixel test, as there is an additional icon in the main menu which also changes the column sizes.
Change setup_provisioned_hosts() to always respect the `disable_preload` argument. If necessary, we can do the `self.is_devel_build` in the caller, but it's not really relevant: We already have several explicit integration tests to check the preload functionality (e.g. TestUpdates.testBasic).
The recent commit 7663244c8c2e also overzealously moved a comment. Move it back, and adjust it for the updated situation above.
---
[example 1](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-140241-2a80128f-fedora-37/log.html), [example …
=> test: Disable preloading for release builds as well

test/common/testlib.py
Since https://github.com/sudo-project/sudo/commit/3396267 sudo also shows additional sentence in its warning:
"For security reasons, the password you type will not be visible". Update our tests to expect that.
Fixes image-refresh https://github.com/cockpit-project/bots/pull/4498
=> test: Update text of sudo warning message

pkg/networkmanager/interfaces.js, pkg/users/authorized-keys.js
Only three usages left!
- The notify/progress stuff in cockpit-components-install-dialog.jsx ; after that, we can drop it from pkg/playground/react-patterns.js
- pkg/base1/test-dbus.js: D-Bus method wants to return a tuple of values, which doesn't work as a list; needs some thinking and API work
- pkg/lib/journal.js: Slaps some custom .stream() API onto the promise, this needs a more careful look.
=> More cockpit.defer() cleanup

HACKING.md, pkg/lib/cockpit-components-firewalld-request.jsx, pkg/lib/cockpit-dark-theme.js, pkg/lib/cockpit.js, pkg/metrics/metrics.jsx, pkg/packagekit/autoupdates.jsx
It is sometimes necessary to enable more than one debug target, e.g. `dbus` and `services`. But `all` is too much of a firehose.
Check window.debugging for a substring instead of equality, similar to what the Services page did in commit 0d6166b17453.
=> pkg: Support more than one target in window.debugging

package.json
Update to 0.32.1 for Chromium 111 compatibility. We need https://github.com/cyrus-and/chrome-remote-interface/commit/58ce8a3ad541709ab3883bc379e4a1dad5acb997 so the tests work.
=> node_modules: update chrome-remote-interface to 0.32.1

pkg/systemd/services/services.jsx, test/verify/check-system-services
`this.timers` is indexed by object path, not unit ID. Fix the initialization in listUnits(). This regression was introduced in commit 0a19a39e9523 during the many rewrites.
This didn't get caught by integration tests as they only covered the `PropertiesChanged` update path, not the initial load. Add such a test, using the existing `deleteme.timer`.
----
release-blocker as this is a regression.
=> systemd/services: Fix initial loading of timers

pkg/systemd/terminal.jsx
In the future we want to isolate iframes from each other using the sandbox attribute which implies no access to document.cookie. The current setting of the cookie is copied into local storage and the cookie automatically deleted by setting the max age to 0.
=> systemd: store terminal settings in local storage

pkg/users/account-details.js, test/verify/check-users
Split from https://github.com/cockpit-project/cockpit/pull/18234 as recommended
The account's page now shows user's home directory and default shell.
=> users: Show shell and home directory in user's details page

pkg/kdump/kdump-view.jsx, pkg/kdump/kdump.js, test/verify/check-kdump
This is the start of a bigger refactor effort of the kdump page. To not make the PR have ~ 10 commits, I've decided to stop at 5 and then focus on adding inline validation. 
What is expected as follow up:
=> Kdump refactor

pkg/lib/cockpit-po-plugin.js, pkg/lib/cockpit-rsync-plugin.js
This makes working on podman a lot better as when the build fails the dist dir is not there and rsync just kill's everything and I notice it minutes later :)
=> Don't invoke our esbuild plugins when the build has errors

pkg/networkmanager/firewall.jsx, test/verify/check-networkmanager-firewall
Resolves Issue #18419 . Trying to disable the Add services/Add port primary button if nothing is chosen using props and a handler function.
=> Fix: Add services button disabled for no input

pkg/systemd/services.jsx
This does not yet exist in Python 3.6 (on RHEL 8), thus causing a warning message and the root-only fallback. Use time.clock_gettime() instead, which was introduced in Python 3.3 already.
Change the Python code to return µs instead of ns, which simplifies the calculation.
---
This was a regression from #18466, but I didn't notice because we don't show errors from passed tests. In failed tests it [looks like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18532-20230320-165624-d2a3bf0e-centos-8-stream-pybridge/log.html#302-2):
AttributeError: module 'time' has no attribute 'clock_gettime_ns'
=> systemd/services: Avoid time.clock_gettime_ns()

pkg/Makefile.am
This has caused a lot of confusing noise during build:
find: ‘../../cockpit/’: No such file or directory
Because the `find` command runs on every invocation of `make`, even when dist/ was not built yet. We only really need this for `make install`, so replace this with a procedural rule. automake would previously generate `install` calls for all files in `Makefile.deps`, or now all files in dist/, so this is still functionally equivalent.
This also avoids the hack with creating a `cockpit` symlink.
=> pkg: Update dist/ install rule to avoid `find` in dependencies

.github/workflows/weblate-sync-pot.yml, po/Makefile.am
We are going to eliminate pkg/build soon. Drop the shortcuts of calling    
various sub-Makefiles, and use the normal ./autogen.sh/make. This only    
takes an extra second and is much cleaner.    
Run the workflow in our unit-tests container, so that we don't have to    
install anything extra, and it becomes reproducible.    
-----
The [manually triggered workflow](https://github.com/cockpit-project/cockpit/actions/runs/4475684936) against this branch succeeded, and the [generated commit](https://github.com/cockpit-project/cockpit-weblate/commit/606ff0acb3a8a7c83457e13aa309ea70dce0bbd5) looks reasonable. There is some noise in the sort ordering of the location comments, presumably because of a different gettext version between the previous Ubuntu 20.04 and Debian testing, but that's …
=> workflows: Avoid pkg/build in weblate-sync-pot.yml

HACKING.md, Makefile.am, build.js, pkg/Makefile.am, pkg/lib/README, pkg/lib/patternfly/patternfly-4-cockpit.scss, src/cockpit/packages.py, test/README.md, tools/README.dist, tools/build-debian-copyright, tools/debian/copyright.template, tools/debian/source/lintian-overrides, tools/node-modules
webpack is an implementation detail and soon change to esbuild. Make the verbiage more neutral.
---
Split from PR #18447 to reduce the noise there.
=> Update documentation and comments to not be webpack specific

pkg/users/account-create-dialog.js, pkg/users/accounts-list.js, pkg/users/users.js, test/verify/check-users
UID should be a integer bigger or same than 1000. There are use cases
when user would want multiple accounts to share the same UID. In such
case, a secondary confirmation button is shown to let user know that
the account will be created with a non-unique UID. The default UID is
prefilled with the next available based on the users at /etc/passwd.
[Screencast from 2023-02-15 16-23-31.webm](https://user-images.githubusercontent.com/42733240/219077484-a985e0d9-a4cf-495c-a668-cc853d4670fd.webm)
=> Allow specifying UID during account creation

pkg/lib/serverTime.js, pkg/lib/serverTime.scss, test/verify/check-system-info
Use Patternfly elements for input elements and buttons, in a later follow up look into using FormFieldGroup's.
Closes #18496
=> lib: port the current manual NTP server dialog to PF

pkg/shell/hosts_dialog.jsx, pkg/shell/shell.scss
When adding a new SSH host for the first time, cockpit shows a modal with a line of code to verify the fingerprint. The background color in dark theme makes it almost impossible to read.
I added a condition for dark theme in the `scss`, let me know if this needs any changes!
=> shell/scss: Fix dark theme code background for new ssh host modal

pkg/lib/patternfly/patternfly-4-overrides.scss
Patternfly handles it differently we margins and I don't see the reason to override it.
This was introduced with the massive PF3 -> PF4 rewrite and is not relevant any more.
This is expected to reduce slightly the space between the Primary and Cancel buttons in modals, which aligns with how these looks on the Patternfly site.
=> patternfly-overrides: Remove obsolete/wrong overrides 

pkg/selinux/manifest.json
This was forgotten in commit d4451584e56. Clicking on the menu would try to go to /selinux/setroubleshoot, which does not exist any more. The tests didn't catch that as they directly go to /selinux instead of clicking the menu.
---
This is a pretty major regression, and it slipped into 288. I will :-1: our current F37/F38 bodhi updates, let's do a 288.1 after that.
=> selinux: Fix menu entry

pkg/lib/esbuild-cleanup-plugin.js, pkg/lib/esbuild-compress-plugin.js, pkg/lib/esbuild-eslint-plugin.js, pkg/lib/esbuild-stylelint-plugin.js
Taken out of PR #18447 with some cleanups. Most of this from @KKoukiou . Consider this approved by me, but formally someone else needs to approve.
I tested this against podman and diffed dist/ before and after, in both devel and production mode. This worked as expected. https://github.com/cockpit-project/cockpit-podman/pull/1242 tests this officially, and I rebased #18447 against that.
=> lib: esbuild plugin updates

pkg/lib/cockpit-components-dialog.jsx
The type of static_error is string, so not wrapping it in a Alert is a bug.  There is only one user of this: cockpit-components-install-dialog.
=> lib: Actually render dialog static_error as alert

test/verify/check-pages
Walk over the whole menu and ensure that we get a successful iframe loaded. This validates the fix in commit 69183a160d1 and prevents future similar regressions.
----
When reverting commit 69183a160d1, this fails on the broken "SELinux" menu entry:
```
DP: frameNavigated {"frame":{"id":"9429BA6ECDBF5E32594376005BE12B93","parentId":"7C27BA0885EB1EA4BEC062EDDCCD0DAA","loaderId":"C819EF7257AA1065644B8A9E704E20C7","name":"cockpit1:localhost/selinux/setroubleshoot","url":"http://127.0.0.2:9091/cockpit/$3d64f0cf6985cff84aae0bc59c0420c23b0daf0b0e3de96b680a130d23eae0b2/selinux/setroubleshoot.html","urlFragment":"#/","domainAndRegistry":"","securityOrigin":"http://127.0.0.2:9091","mimeType":"text/html","adFrameStatus":{"adFrameType":"none"},"secureContextType":"SecureLocalhost","crossOriginIsolated …
```
=> test: Validate all Navigation menu page entries

test/common/testlib.py, test/verify/check-connection, test/verify/check-reauthorize, test/verify/check-superuser
Unfortunately PR #18398 broke three tests and introduced a new crash as unexpected message. We didn't notice back then as that PR didn't run c8s/pybridge, only f-37/pybridge. Accept this as new baseline for now, so that we don't fail all PRs, and avoid accidentaly introducing further regressions.
Example failures: [one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18491-20230323-144756-5d101ba4-centos-8-stream-pybridge/log.html), [two](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18552-20230324-084110-5d219b81-centos-8-stream-pybridge/log.html)
I created https://issues.redhat.com/browse/COCKPIT-971 to track actually fixing this.
=> c8s/pybridge test: Skip three regressed tests and ignore new crash

pkg/lib/cockpit-rsync-plugin.js
Not returning anything causes an ugly
```
✘ [ERROR] Expected onEnd() callback in plugin "cockpitRsyncPlugin" to return an object [plugin cockpitRsyncPlugin]
```
error when there is anything wrong in the compiled source (like an ESLint error). Immediately return an empty object in the failure case instead of `undefined`.
----
This doesn't yet do anything useful in cockpit itself, but I noticed it with c-podman, and tested it against that. See https://github.com/cockpit-project/cockpit-podman/pull/1243 . But it applies to the esbuildification in PR #18447 as well (also tested with that branch)
=> lib/cockpit-rsync-plugin: Fix return value on failures

pkg/systemd/index.html
tuned/performance.js has not existed as a separate webpack for a long time. This causes an unsightly error message.
=> systemd: Drop loading of non-existing performance.js

pkg/storaged/format-dialog.jsx
This affects the bundle size noticeable. In particular this change reducer the production bundle size from 25.9 mb to 25.3 mb.
=> pkg: Use only full path imports as tree shaking is imperfect

pkg/users/account-create-dialog.js, test/verify/check-users
This add ability to specify custom home directory and custom shell for newly created users:
[Screencast from 2023-01-26 11-41-05.webm](https://user-images.githubusercontent.com/42733240/214817073-addde521-f013-4eb7-a4b0-54fb7fa5edcc.webm)
If user tries to use home directory which already exists:
I also added the listing of those user's home directory and shell into user's details page:
=> users: Allow specifying home directory and shell during account creation

build.js, pkg/lib/esbuild-common.js
There are some quite delibarate hacks there, it worths to export these so that other projects can keep in sync with cockpit more easily.
=> build: Move stylesheet processing into pkg/lib/build-common.js to enable reusing - FIX COMMIT MESSAGE ON MERGING

pkg/packagekit/updates.jsx
After the refactoring in 8b3c35aaf0c6415c071 we now call formatPackageId twice which ends up showing a lot of undefined ( undefined ).
This still has some issues where it shows undefined in the progress bar because the first events we get are DOWNLOADING and not updating so we end up calling formatPackageKid with an empty string. However this requires an update to retrigger the issue so needs a quicker development cycle? Maybe our tests? However as this fixes some uglyness let's get this in first.
=> packagekit: don't call formatPackageId on itself

build.js
webpack.config.js is not a thing any more.
=> build.js: Drop obsolete --config option

HACKING.md, README.md
The Cockpit Project is now on Matrix at #cockpit:fedoraproject.org.
=> various: replace mentions of IRC with Matrix

test/verify/check-metrics
https://github.com/cockpit-project/bots/pull/4585 updates the repo for it, and renames it to "localhost/test-busybox". Stop hardcoding the full name, and check for available images instead.
=> test: Stop hardcoding busybox container image name

HACKING.md, containers/unit-tests/setup.sh, src/Makefile.am, src/ws/test-server.c, test/pytest/test_browser.py
Commit 18576f7d18e moved them to /qunit. Adjust the pytest wrapper, documentation and example accordingly. This brings back the HTML tests in the pytest unit test run.
----
Oops! See a [recent pytest-cov run](https://github.com/cockpit-project/cockpit/actions/runs/4551701495/jobs/8026098929?pr=18577#step:4:280), there are no HTML tests.
=> test: Fix qunit test path and missing pytest-asyncio

pyproject.toml
As discussed in #18584, pytest really should not be ignoring unknown marks.  Let's make sure that gets treated as an error.
=> pyproject.toml: enable pytest --strict-markers

.github/workflows/differential-shellcheck.yml
Also, update `differential-shellcheck` to the latest version (`v4.0.2`) - https://github.com/redhat-plumbers-in-action/differential-shellcheck/releases Push events are supported since `v4.0.0`.
Fixes: https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215
This should get rid of annoying messages from the `github-code-scanning` bot.
Also, I have added the required permission for uploading SARIF reports to GitHub
=> ci: trigger differential-shellcheck workflow on push

pkg/systemd/overview-cards/configurationCard.jsx
Show multiple errors under each other instead of on the same line using standard PF components.
Old
New
=> systemd: show multiple dialog errors correctly

test/verify/check-sosreport
In Fedora rawhide, the tarball now does not contain the top-level    
directory as first entry, but an actual file like    
"sosreport-host0-mylabel-2023-04-03-yyffcgw/version.txt". Trying to join    
that with another path is going to fail. Make this more robust by only    
taking the top-level directory name from the first entry.    
---
Cockpit's TF rawhide tests recently [started to fail like this](https://artifacts.dev.testing-farm.io/f817c1df-c135-4967-aca7-dbd5acad1c40/):
```
File "/var/ARTIFACTS/work-basicp6iwkmif/plans/all/basic/discover/default-0/tests/test/verify/check-sosreport", line 110, in testBasic
raise ex
File "/var/ARTIFACTS/work-basicp6iwkmif/plans/all/basic/discover/default-0/tests/test/verify/check-sosreport", line 105, in testBasic …
```
=> test: Robustify sos tar reading

pkg/lib/cockpit-po-plugin.js
anaconda webui source code lives in ui/webui/src/ which is not covered in the current check for source files, thus making the translations not work.
=> lib: cockpit-po-plugin: make source directory a configuration option

test/verify/check-storage-stratis
The linked bugzilla [1] makes this dialog very unpredictable.
[1]  https://bugzilla.redhat.com/show_bug.cgi?id=2183084
=> tests: temporarily disable stratis add block device dialog pixel test

pkg/lib/cockpit-components-file-autocomplete.jsx, test/verify/check-pages
If FileAutoComplete input matches one entry, but is the prefix of another entry, widget should not descend into directory yet.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2097662
Quick explanation of what bug does this fix:
1. `mkdir /tmp/test; mkdir /tmp/test-1`
2. Type `/tmp/test` into FileAutoComplete
Expected result:
Listed files/directories are /tmp/test and /tmp/test-1
Actual result:
FileAutoComplete descends into /tmp/test and lists file from there
=> lib: file-autocomplete: Fix descend into directory

test/image-prepare
Give a convenient way to set environment variables via /etc/environment in the created VM.  This is particularly useful for enabling debugging.
<hr/>
For the record, this ends up set in both sessions created from ssh logins and also in the cockpit session (via `cockpit-session`)
The use of modern Python features is owing to the fact that the script only needs to run on the tasks container and our workstations, not inside of the (old) VMs themselves.
=> test: add test/image-prepare --env and --debug

pkg/lib/cockpit-components-password.jsx, pkg/users/account-create-dialog.js, test/verify/check-users
TODO:
Fixes #18391 
There are several improvements to the process of setting passwords during account creation:
- The confirmation password is validated and doesn't match, validation is done after each keystroke. This improves user experience, as the user doesn't have to click "Create" whenever they want to know if passwords match.
- Password validation is now presented as warning, since a weak password is not actually forbidden, but discouraged nevertheless.
=> accounts: Redesign password process

pkg/packagekit/updates.jsx, pkg/packagekit/updates.scss, test/verify/check-packagekit
Resolves #18581 
Software updates: Output when failing to load updates come in a single line
The updated design follows the [`<ApplyUpdates>` component](https://github.com/cockpit-project/cockpit/blob/891fb8648cb732b4fdf9b93a6e35876eb81fdea0/pkg/packagekit/updates.jsx#L593)'s design to include error logs in a `<CodeBlockCode>` in an `<Expandable>`. 
* pkg/packagekit/updates.jsx: 
* Move logs outside of `<EmptyStatePanel>`'s paragraph to an `<Expandable>` component inside a `<CodeBlockCode>` to correctly print logs on separate lines (the bug), 
* Move the *'Please reload the page after resolving the issue.'* message above the logs.
* pkg/packagekit/updates.scss:
* Add class selectors following the styles in `progress-main-view`, `.update-log` and `.update-log-content` as well as include …
=> Software Update: Fix output logs printing in one line when failing to load updates in software update page

doc/man/cockpit.conf.xml, src/ws/cockpitauth.c, test/verify/check-static-login
The current documentation of LoginTo= isn't very specific about what exactly happens with a "false" value; but it is plausible for an admin to assume that "false" would disallow logging into a remote host completely -- not merely hide the "Connect to:" field and then allowing a direct URL login anyway.
It is sometimes important to disallow direct SSH logins from the login page on publicly exposed bastion hosts, as this functionality allows unauthenticated remote users to:
- scan the internal network for existing hosts, which might otherwise not be accessible directly from the internet (Fixes #18540, https://bugzilla.redhat.com/show_bug.cgi?id=2167006)
- scan the cockpit-ws host or internal network hosts for open ports (Fixes #15077, https://bugzilla.redhat.com/show_bug.cgi?id=2018741)
So …
=> ws: Disallow direct URL logins with LoginTo=false

test/browser/run-test.sh
This should fix last failure on https://gitlab.com/redhat/centos-stream/rpms/cockpit/-/merge_requests/46
These tests run on centos-8.
=> run-tests: Fix test EXCLUDE to cover centos-8

pkg/static/login.html
Adding proper autocomplete to help password managers. Most importantly adding autocomplete="one-time-code" to stop browsers from thinking the 2fa field is the new password
https://bugzilla.redhat.com/show_bug.cgi?id=2102325
=> login: add autocomplete tags

pkg/systemd/service-details.scss
The current version is barely readable in the dark theme.
Before:
After:
=> systemd: set a different text color in the dark theme

pkg/users/authorized-keys.js, test/verify/check-shell-keys
cockpit.file().replace() creates an entirely new file with root:root    
permissions, which completely breaks a user's ~/.ssh/authorized_keys    
file when removing a key.    
Until we have a more powerful file API, use `sed -i` instead, which    
keeps file permissions of existing files. This doesn't automagically    
remove empty lines, so adjust the integration test to expect the extra    
empty line that it added a few lines up.    
Fixes #11876
=> users: Retain authorized_keys file permissions

packit.yaml
In commit 940cc5cd1 I dropped the copr_build's `post-upstream-clone:` action as it became identical to the global one, and I thought it would be inherited. But it turns out that specifying `actions:` replaces the global object entirely. That made release COPR builds fail on missing spec file.
Copy the post-upstream-clone command and add a comment why it's necessary. We'll have to keep this until
https://github.com/packit/packit-service/issues/1505 gets fixed.
----
See the recent srpm build failure from release 289: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/build/5745838/
=> packit: Re-add post-upstream-clone to copr_build

test/verify/check-networkmanager-basic
This dialog is too unstable -- each Fedora 37 refresh now seems to change the IPv6 address pattern and thus changes the column widths. We recently changed it in commit 2e9d91dc2f already, and the refresh in https://github.com/cockpit-project/bots/pull/4639 changes it again.
=> test: Skip "medium" layout for basic networking test

test/common/run-tests
Anaconda uses a different machine_class for testing as they need to spin up the machine with virt-install. For anaconda or any other project to not override run-tests or bots the class to instantiate could be discovered from the run tests if they are all the same pick that class otherwise fallback to VirtMachine.
This PR needs some testing against an anaconda PR to verify it also works in CI and not just locally.
=> test: discover machine_class dynamically from test classes

test/common/testlib.py
`timedatex.service` shuts down on inactivity. The overview page has a proxy on the systemd service object to watch for property changes, which will trigger a NoReply error on the proxy occasionally.
Adding this to dbus_error_matches_unknown() would hide actually interesting errors when a service crashes in the middle; so let's not do that, and ignore that message instead.
----
Seen [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18638-20230414-105408-16960b15-rhel-8-9/log.html#332) and it also broke the recent RHEL gating update for the same reason.
This is a rather lame change, but I don't really have a better idea.
=> test: Ignore timedatex.service disconnection messages

test/verify/check-storage-stratis
We need for Cockpit to recognize that the filesystem is mounted before deleting it so that the teardown actions can be done correctly.
=> test: Remove a race in TestStorageStratis.testAtBoot

package.json
This fixes tests with current Chromium versions.
---
Should fix [this total failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4652-20230414-230818-565f8442-centos-7-cockpit-project-cockpit-rhel-7.9/log.html) after the recent cockpit/tasks refresh.
=> package.json: Update chrome-remote-interface to 0.32

pkg/kdump/kdump-view.jsx, pkg/lib/cockpit-components-form-helper.jsx, pkg/lib/cockpit-components-password.jsx, pkg/lib/cockpit-components-shutdown.jsx, pkg/networkmanager/firewall.jsx, pkg/shell/hosts_dialog.jsx, pkg/sosreport/sosreport.jsx, pkg/storaged/dialog.jsx, pkg/systemd/overview-cards/configurationCard.jsx, pkg/systemd/overview-cards/realmd.jsx, pkg/systemd/timer-dialog.jsx, pkg/users/account-create-dialog.js, pkg/users/account-details.js, pkg/users/expiration-dialogs.js, pkg/users/group-create-dialog.js, pkg/users/password-dialogs.js, test/common/storagelib.py, test/verify/check-networkmanager-firewall, test/verify/check-users
FormGroup in PF5 abandonded the validated and helperText* properties. To make porting easier start using these as PF5 requires.
=> Port to new way of using HelperText

src/ssh/ssh.c
When receiving SIGTERM or SIGINT, give libssh a chance to clean up the connection. In particular, that will close a running `ProxyCommand` process when logging out of Cockpit.
Fixes #18310
https://bugzilla.redhat.com/show_bug.cgi?id=2185785
---
I tested this with the simplified reproducer in https://bugzilla.redhat.com/show_bug.cgi?id=2185785#c4 . This should also obsolete the known issue https://github.com/cockpit-project/bots/issues/4635 , i.e. `TestIPA.testQualifiedUsers` should now pass *without* a naughty skip. **Update**: I checked all test runs, and they all passed properly. :+1:
=> ssh: Clean up libssh connection on terminating signals

pkg/lib/patternfly/patternfly-4-overrides.scss
This override used to fix [patternfly issue](https://github.com/patternfly/patternfly-react/issues/4767
), where svg icons were sometimes missing vertical-align, and then appearing too high. 
It seems that it has been fixed in PF, and now we have opposite issue that icons appear too low:
=> lib: Remove PF override for svg's vertical-align

pkg/static/login.js
Closes #18637
Currently the login page defaults to 'light theme' when the `shell:style` is missing in the local store of browser.
This change hopefully (_testing needed opening as draft_) allows the login page to have 'auto theme' by default.
Below snippets from existing code-base already have this code pattern in place.
https://github.com/cockpit-project/cockpit/blob/137357fb85daaebcfef651ee70c148eb0805bef8/pkg/lib/cockpit-dark-theme.js#L37
https://github.com/cockpit-project/cockpit/blob/137357fb85daaebcfef651ee70c148eb0805bef8/pkg/shell/base_index.js#L212
https://github.com/cockpit-project/cockpit/blob/137357fb85daaebcfef651ee70c148eb0805bef8/pkg/shell/topnav.jsx#L61
=> static: allow 'auto' theme to be applied as default theme for login page

pkg/storaged/dialog.jsx
=> storage: fix alignment of 'Block devices' form element in 'Create stratis pool' dialog

src/cockpit/channel.py
We guard for the channel being in the closing state on incoming data and control messages for the channel, but we forgot to add this same check for .do_kill(), even thought the docs for .close() are pretty clear that no .do_*() methods should get called after .close().
Add the same check as in the other places.
This fixes a backtrace recently seen in an unrelated PR:
```
...
File "/usr/local/lib/python3.11/site-packages/cockpit/channel.py", line 150, in do_kill
self.do_close()
File "/usr/local/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 505, in do_close
for slot in self.matches:
TypeError: 'NoneType' object is not iterable
```
=> python: don't process kill messages on closing channels

build.js
They now correctly appear - at least for firefox.
=> build: fix source map generation

src/cockpit/bridge.py, src/cockpit/internal_endpoints.py, src/cockpit/peer.py, src/cockpit/protocol.py, src/cockpit/remote.py, src/cockpit/superuser.py, test/common/testlib.py, test/pytest/test_bridge.py, test/verify/check-connection, test/verify/check-reauthorize, test/verify/check-shell-host-switching, test/verify/check-shell-multi-machine, test/verify/check-shell-multi-machine-key, test/verify/check-shell-multi-os, test/verify/check-superuser, test/verify/check-system-realms, test/verify/check-system-shutdown-restart
Add support for connecting to additional hosts via ssh, using ferny.
In general, this is not working well on RHEL8 — ferny depends on the KnownHostsCommand feature of OpenSSH, which is not available on RHEL8.  Without this, we don't get access to the public key of the remote host that we're connecting to, in case the host isn't known yet, which means we can't add it to the file.
https://issues.redhat.com/browse/COCKPIT-909
=> python: initial implementation of ssh support

tools/cockpit.spec
when using grep in the post run on a new install of cockpit the output contains `grep: /etc/pam.d/cockpit: No such file or directory` which is confusing and can mislead people into thinking cockpit has failed to install, by using test if `/etc/pam.d/cockpit` doesn't exist it will be silent.
=> use test -f over grep for finding cockpit files

test/common/testlib.py, test/verify/check-connection
This leaves testBasic and testReverseProxy, which both use self.ostree_setup_ws(), and testWsPackage which removes packages. So these three are legitimately destructive.
=> test: Make most TestConnection tests nondestructive

pkg/shell/credentials.jsx, test/common/testlib.py, test/verify/check-apps, test/verify/check-connection, test/verify/check-loopback, test/verify/check-packages, test/verify/check-shell-keys, test/verify/check-ws-bastion, test/vm.install
This should help with reducing the overall test time. ATM chromium tests take between 42 and 50 minutes on an e2e machine.
----
I locally converted pretty much everything except networking and storage test. This is the first batch. For my own reference, these can be potentially converted still (but in a separate PR, this is becoming too big):
```
TestNetworkingCheckpoints.testCheckpoint    
TestNetworkingCheckpoints.testCheckpointSlowRollback    
TestNetworkingCheckpoints.testNoRollback    
TestStorageISCSI.testISCSI    
TestStorageLuks.testKeepKeys    
TestStorageLuks.testLuks    
TestStorageLuks.testLuks1Slots    
TestStorageLuks.testNoFsys    
TestStorageLuks.testReboot    
TestStorageMdRaid.testNotRemovingDisks    
TestStorageMdRaid.testRaid    
TestStorageMounting.testAtBoot …
```
=> nondestructive tests: apps, loopback, testPrivateKeys; fix testPrivateKeys flake; fix test-connection regressions

pkg/selinux/setroubleshoot-client.js
Exception objects are not directly printable, so trying to render it in    
an Alert or with `console.warn()` just results in an empty string. That    
makes debugging really hard, as there is no corresponding entry in the    
journal either.    
Use `.toString()` on the exception to render them properly. Also show    
the actual exception text in the Alert in the UI. Still keep the    
console.warn()s, so that we can do naughty matching on them.    
While at it, eliminate the unnecessary Promise wrappers, and use chaining.    
----
I'm trying to get to the bottom of [this common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18661-20230418-173000-028eaf96-centos-8-stream-pybridge/log.html#333). ([another instance](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18647-2 …
=> selinux: Fix error reporting

pkg/users/account-create-dialog.js, test/verify/check-users
The used Select component implementation is deprecated in PF5.
Port this to FormSelect as it's better fit in general (simple Selects in dialogs should use FormSelect) and make it ready for PF5.
=> users: port shell selection to FormSelect

test/verify/check-system-info
Otherwise it keeps running in later tests, and throws lots of errors into the journal which pop up as unexpected messages.
---
[example 1](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18603-20230420-094857-fcef2f24-rhel-8-9/log.html), [example 2](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18662-20230420-105608-6c24060f-rhel-8-9/log.html#122)
=> test: Reset insights-client after TestSystemInfo.testInsightsStatus

pkg/shell/nav.scss
Closes #18649 
> This CSS `height: 100%` was applied only in Dark theme
> 
> https://github.com/cockpit-project/cockpit/blob/c33285c2cad23636c5a8a86d63609f9bf7462b0e/pkg/shell/nav.scss#L360-L363
This resulted in light theme having the search menu element to be slightly off-centered
> [Screencast.from.2023-04-17.12-11-18.webm](https://user-images.githubusercontent.com/67428/232460972-633aa26b-d2e9-4d64-96dd-52eb02a672ae.webm)
This change allows that specific CSS to be applied regardless of themes, fixing the alignment of the shell search menu effectively in light theme
=> shell: fix minor CSS alignment of shell search menu independant to themes

test/verify/check-storage-hidden, test/verify/check-ws-bastion
Also fixes [this test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4680-20230420-232001-7e1dc975-rhel4edge-cockpit-project-cockpit/log.html#348-2). Completely unrelated, but let's avoid an useless CI run just for changing a commit message.
=> Mark TestStorageHidden.testHiddenSnap as nondestructive; make TestWsBastionContainer really nondestructive

pkg/apps/application.jsx, pkg/lib/patternfly/patternfly-4-overrides.scss, pkg/networkmanager/firewall.jsx, pkg/networkmanager/network-interface.jsx, pkg/storaged/details.jsx, pkg/systemd/hwinfo.jsx, pkg/systemd/logDetails.jsx, pkg/systemd/service.jsx, pkg/users/account-details.js, pkg/users/users.scss
This is still PF4 compatible.
The only noticeable change is on firewall, as now only the breadcrumbs will remain sticky and the rest of the page headers will hide on scroll. This is the desired behavior as suggested here [0]
[0] https://github.com/cockpit-project/cockpit/pull/18476#pullrequestreview-1343830115
=> Adjust Breadcrumb usage on all affected pages to match PF5 guidelines

test/image-prepare, test/verify/check-connection
Previously, that test [sometimes failed on f37](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18603-20230420-093114-fcef2f24-fedora-37-pybridge/log.html#16), and [sometimes succeeded on c8s](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18662-20230421-054212-ae04049b-centos-8-stream-pybridge/log.html), as commit 2c9b18246f2 introduced a race condition. Fix the race, and fix the test properly.
=> Fix TestConnection.testCockpitDesktop for pybridge

pkg/apps/apps.jsx, pkg/systemd/services.jsx
The current iframe path/options for ServicesPageBody is currently coming
from two different sources: `cockpit.location` and properties passed
from the parent ServicesPage element, which tracks it as React state. As
the latter is "laggy" and sometimes disagrees with cockpit.location,
this led to inconsistent states: the page sometimes "forgot" its current
location when an asynchronous state update overwrote a recently happened
cockpit.location update.
Avoid this race by consistently using cockpit.location for everything.
Keep usePageLocation() only for triggering renders when the options
change, but ignore its state.
Fixes #18465
---
This also fixes the same inconsistency on the apps page, but the other way round: As we don't have to deal with multiple nested components there, and …
=> apps, systemd/services: Use single source of truth for page location

pkg/systemd/service-details.jsx
In PF5 dropdown menus are inserted inline and they inherit the fonts from their parent element.
CardTitle has font-size: 400, resulting in the dropdown menu options to be also bold-ish.
=> services: remove dropdown from CardActions as it inherits the fonts (Split out from PF5 PR)

pkg/networkmanager/interfaces.js, pkg/storaged/client.js, pkg/storaged/content-views.jsx, pkg/storaged/crypto-keyslots.jsx, pkg/storaged/crypto-tab.jsx, pkg/storaged/format-dialog.jsx, pkg/storaged/fsys-tab.jsx, pkg/storaged/mdraid-details.jsx, pkg/storaged/utils.js, test/verify/check-storage-hidden
This sometimes runs into out of memory errors with the default VM size. Split it out into its own test class and increase memory like we do in check-storage-{luks,resize}.
----
See https://cockpit-logs.us-east-1.linodeobjects.com/pull-18662-20230421-050018-6ed1ae43-rhel-8-9/log.html#341 and https://cockpit-logs.us-east-1.linodeobjects.com/pull-18662-20230421-054212-ae04049b-debian-testing/log.html#341
After fixing OOM, the [undefined ChildConfiguration still happens](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18686-20230421-194249-fd65ffa3-centos-8-stream/log.html#348-2)
=> Fix TestStorageHidden.testHiddenLuks OOM, fix crash if block device lacks Encrypted interface

pkg/lib/ct-card.scss, pkg/systemd/service-details.jsx, pkg/systemd/service-details.scss
Use ct-card for making this card same to all other cards in cockpit.
Rely on Flex for spacing the card header elements.
=> services: adjust service details header to use less custom CSS

test/verify/check-shell-multi-machine, test/verify/check-shell-multi-machine-key, test/verify/check-superuser, test/verify/check-system-realms
These issues allow us to better track the discussion, debugging, and triaging which ones are blockers for releasing the Python bridge.
----
See https://github.com/cockpit-project/cockpit/labels/pybridge , this is now a complete list of things which we still need to work on. The https://github.com/cockpit-project/cockpit/labels/pybridge-blocker subset are the ones which we need to address until we let this lose to distros.
=> test: Link @todoPybridge to issues

test/verify/check-superuser
This provides more direct integration tests for issue #18676 than `TestIPA.testClientCertAuthentication`, where the failure is more like happenstance, and the issue is difficult to investigate.
=> test: Check cancel and logout with ongoing sudo authentication

pkg/storaged/crypto-keyslots.jsx, pkg/storaged/utils.js, test/common/storagelib.py, test/verify/check-storage-luks
For example, when adding a Clevis key to a block device that is a physical volume of the volume group that contains the root filesystem.
Fixes #18687
=> storage: When fixing NBDE, also recognize indirect root filesystems

test/verify/check-storage-used
The width of the popover is automatically fitting it's content. The content of this popover can change as it contains service names and their PIDs causing the width to change and this pixel test to fail.
Since this is quite a trivial UI, let's drop it to make our CI green again.
=> test: drop pixel testing of popover for services using storage

package.json
Nothing uses it in .eslintrc so this can be safely removed.
=> package.json: remove unused eslint-flowtype-plugin dependency

test/verify/check-superuser
Missed chance for more cleanup in commit 66f02c4dec. The helpers already switch the frame and restore it afterwards.
=> test: Drop unnecessary leave/enter page

pkg/networkmanager/interfaces.js
The watch doesn't survive a restart of the D-Bus service, let's recreate it when a new owner appears.
This didn't seem to matter much in the past since NetworkManager used to have a very incremental startup and would send out PropertiesChanged notifications for a lot of things.  It is sending less now, apparently.
=> networkmanager: Recreate the D-Bus watch when the service restarts

pkg/storaged/client.js, pkg/storaged/content-views.jsx, pkg/storaged/details.jsx, pkg/storaged/pvol-tabs.jsx, pkg/storaged/stratis-details.jsx, pkg/storaged/stratis-panel.jsx, test/verify/check-storage-stratis
Stopped pools are a generalization of locked encrypted pools introduced in newer versions of Stratis.  Now every kind of pool can be inactive, not just encrypted ones.
=> storage: Support stopped Stratis pools

test/browser/browser.sh
nodejs 20 crashes left and right, see
https://bugzilla.redhat.com/show_bug.cgi?id=2190075
Install the previous nodejs 18 for now, and update the /usr/bin/node symlink to point to 18.
----
This should fix [this rawhide crash](https://artifacts.dev.testing-farm.io/33885ddc-aae0-4f24-9d59-3b6af98e9830/) which we've been seeing since last week.
=> fmf: Force nodejs 18 on Rawhide

pkg/storaged/dialog.jsx, pkg/storaged/format-dialog.jsx, test/verify/check-storage-format
Fixes #18623.
I couldn't access the chosen filesystem type when inside `dialog_open()`, so I added a function in `dialog` to return a value based on an input tag. The footer is updated based on the filesystem type.
I also changed the condition for `mount_now` so it doesn't attempt to mount an empty filesystem.
This workaround feels a bit hacky, it might be better to implement the logic of updating the footer inside `dialog` directly. Let me know what you think!
=> storage: Only show "Format" button for empty filesystem in format modal

src/cockpit/transports.py, test/verify/check-reauthorize, test/verify/check-superuser
When closing a running subprocess, EOF its stdin first, before    
terminating it. Commit ead84ab7ba1a dropped the equivalent code for a    
socket in the _close() function. Put it back. This fixes the last two    
regressions on CentOS/RHEL 8 from moving to ferny.    
This this also the first half of properly terminating the    
sudo+cockpit-askpass process pair when the authentication dialog gets    
cancelled (issue #18676): SIGTERMing sudo does not have any effect while    
it asks for a password, but its askpass child inherits its stdin and    
thus can see EOF on it when the channel closes. This is what happens    
with the C bridge+askpass.    
----
https://issues.redhat.com/browse/COCKPIT-971
~The second half of the fix will happen in ferny. With both of these fixes, issue #18676 …
=> python: Close process stdin when closing SubprocessTransport

pkg/systemd/services-list.jsx, pkg/systemd/services.scss
When we are in timer view let the breakpoint be earlier as timers have also the previous/next trigger column.
Fixes #18011
Fixes #15928
=> services: improve alignment of last (status) column

test/verify/check-system-info, test/verify/check-system-realms
The freeipa-client package has started to conflict with systemd-timesyncd, and our Debian/Ubuntu images will therefore over time switch to running chronyd by default.  Let's prepare the tests for that by adapting themselves dynamically.
(Once they have all switched, we might go back to static determination of whether to expect chronyd, if we prefer that.)
TestIPA will inspect the image to determine whether to fake chronyd.
TestTime.testTimeServersTimesyncd will explicitly install systemd-timesyncd if necessary.
=> test: Support Debian/Ubuntu images with chronyd and no systemd-timesyncd

pkg/systemd/abrtLog.jsx, pkg/systemd/reporting.jsx
These two places were the lsat ones still using the old method.
----
@KKoukiou : FTR, I also looked at the [new PF5 select](https://patternfly-react-v5.surge.sh/components/menus/select/). but admittedly I quickly lost motivation -- that new replacement feels horribly complicated compared to the old one..
=> systemd: Consistently use CardTitle's component attribute

test/browser/browser.sh
The crash was worked around in Rawhide.
This reverts commit 9038b849c97f1713f6b38e81dcd299991d26d9af.
----
I want this to go green to confirm. If/once it does, I'll close https://bugzilla.redhat.com/show_bug.cgi?id=2190075
=> Revert "fmf: Force nodejs 18 on Rawhide"

.github/workflows/codeql.yml
CodeQL requires this to compare pull requests to the state of the base branch.
Copied the conditionals over from the differential shellcheck workflow.
=> .github: run CodeQL workflow on main as well

pkg/lib/page.scss, pkg/systemd/service.jsx, test/common/testlib.py
Sometimes we take screenshots of a whole page as part of the pixel tests and in medium screen sizes the page content often exceeds the viewport causing a scrollbar to appear. The scrollbar's height changes according to the non-displayed contents which is introducing some factor for flakiness.
For this reason let's always hide the scrollbar when pixel testing.
=> test: hide scrollbar in pixel testing

.gitmodules
Otherwise modules initialization fails with:
Cloning into '/home/kkoukiou/repos/cockpit/modules/systemd_ctypes'... fatal: remote error: /allisonkarlitskaya/systemd_ctypes is not a valid repository name
=> Remove duplicate / from submodule url

test/verify/check-storage-hidden, test/verify/check-storage-resize, test/verify/check-storage-swap, test/verify/check-storage-vdo, test/verify/check-ws-bastion
One minute often is not enough on our CI machines, the test timed out in most cases.
[example one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18758-20230508-053357-16dac345-centos-8-stream-pybridge/log.html#230-1), [example two](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18758-20230507-065718-5b53fa4a-centos-8-stream-pybridge/log.html#230).
While I was at it, I also noticed some unnecessarily complicated test skip conditions, I added a second commit to clean these up.
=> test: Allow "vdo create" to take more time; clean up test skips

src/bridge/bridge.c, src/session/session.c
cockpit-session set a tight 077 umask for extra paranoia. However, on    
OSes without pam_umask configured by default (like Debian), this causes    
all session processes to run with that umask as well. This then caused    
e.g. `cockpit.file('/etc/motd').replace()` to write motd with 0600    
permissions, making it inaccessible. (cf. issue #18033)    
The C bridge counteracted this by harcoding `umask(022)`, but that    
really does not belong there: The bridge also gets run through SSH or    
directly from ws. The Python bridge does no such thing, and we rather    
don't want to add that.    
There is no real benefit for cockpit-session to change the umask. It    
does not create any files by itself, and security related files created    
by GSSAPI or PAM modules should already do …
=> bridge, session: Drop changing umask

pkg/metrics/metrics.jsx
In Patternfly 5 popover will add a div wrapper to the trigger element unless triggerRef property is specified.
Before
After:
=> metrics: fix broken alignment in expanded hour in metrics history

test/common/testlib.py, test/verify/check-packagekit, test/verify/check-superuser
We will soon enable the Python bridge in the real packages for some distributions. Then the normal test runs will use the Python bridge, instead of having a separate `/pybridge` scenario. To unblock this, change our `@todoPybridge{,RHEL8}` decorators and the two remaining special cases to detect the Python bridge at runtime, instead of statically from the test scenario.
---
Broken out from PR #18757
=> test: Use dynamic pybridge detection instead of $TEST_SCENARIO

test/verify/check-pages
When switching between the Services detail page, Networking page, and    
the shell to inspect the doc entries, the page often gets a spurious URL    
change (`window.hashchanged` event). This is real, it's visible in the    
browser's URL bar. This is not coming from any `cockpit.location.*` call    
from inside the services page, and has resisted debugging for too many    
hours [1].    
This is a very special combination of page preloading, frame changing,    
and careful timing (changing either one makes this bug go away), and the    
fallout is minor: the services page loses its "on the details page"    
state and goes back to the service list, which wouldn't be dramatic (if    
it is even possible to get this effect manually).    
So cut off the wasted time here, and work around …
=> test: Disable preload to stabilize TestPages.testBasic

test/static-code, tools/git-hook-post-commit
Scan test/static-code for a list of extra files that need to be checked out to effectively check a given commit.
This is better than putting the list in the post-commit hook itself, because the commit hook is static: it exists in a given place on the filesystem which is usually symlinked to from the git config.  The list of files required to check each commit, on the other hand, can change with the commit in question.
Our first candidate file for the new treatment: pyproject.toml.  This is required because it contains our ruff configuration.
=> tools/git-hook-post-commit: checkout extra files

pkg/storaged/dialog.jsx, pkg/storaged/format-dialog.jsx, pkg/storaged/stratis-details.jsx, test/verify/check-storage-format, test/verify/check-storage-stratis
Fixes #18718.
I passed the `variant` from the footer buttons to the `validate` function for the mount point, so it checks the type before validating.
Let me know if this feels like a long workaround or if there is a better approach!
=> storage: Create stratis filesystem snapshot without requiring mount_point

pkg/systemd/logs.jsx, pkg/systemd/logs.scss
Filterbar is misaligned in desktop mode:
And its popover is offset in mobile:
This PR fixes both problems with two different commits.
=> Logs: align filters

pkg/apps/index.html, pkg/kdump/index.html, pkg/lib/qunit-template.html, pkg/networkmanager/firewall.html, pkg/networkmanager/index.html, pkg/packagekit/index.html, pkg/playground/index.html, pkg/playground/journal.html, pkg/playground/metrics.html, pkg/playground/notifications-receiver.html, pkg/playground/pkgs.html, pkg/playground/plot.html, pkg/playground/preloaded.html, pkg/playground/react-patterns.html, pkg/playground/service.html, pkg/playground/speed.html, pkg/playground/test.html, pkg/shell/shell.html, pkg/sosreport/index.html, pkg/static/login.html, pkg/storaged/index.html, pkg/systemd/hwinfo.html, pkg/systemd/index.html, pkg/systemd/logs.html, pkg/systemd/services.html, pkg/systemd/terminal.html, pkg/users/index.html, src/ws/test-handlers.c
This is autoinserted if needed.
=> pkg: remove redundant pf-theme-dark class from the html pages

pkg/metrics/metrics.scss
SVG polygon's coordinates have Y go downward, but in our graph we expect the time coordinate to go upward. So we always have to scaleY(-1). Changing the numbers to be aligned to 100% instead of 0% is more computational effort -- all transform()s are a single matrix multiplication, which happens anyway.
Flip them on the X direction depending on RTL and whether it's use or saturation.
This fixes the saturation graphs being the wrong way around in LTR, and flips the horizontal orientation in RTL: i.e. in RTL, usage goes to the right and saturation to the left.
----
[pixel review](https://github.com/cockpit-project/pixel-test-reference/compare/d47238b76131c2b14c00e28b67404a0d1865d662..48a69f3dc27dd7f853f2f3dd4a76c761ad899126) -- RTL is still a mess, but that's fully fixed in PR #18777
=> metrics: Fix y-flipped history polygons for saturation, and RTL orientation

test/static-code
This isn't going to work, since there's absolutely no chance that we'll ever have node_modules/ in the partial tree.  This prevents seeing
```
WARNING: skipping /static-code/test-eslint: no eslint
WARNING: skipping /static-code/test-eslint: no eslint
WARNING: skipping /static-code/test-eslint: no eslint
WARNING: skipping /static-code/test-eslint: no eslint
```
(once per commit) when rebasing or pushing.
=> test/static-code: don't do eslint in partial trees

src/cockpit/channels/stream.py, src/cockpit/transports.py
Trying to terminate our children with SIGHUP was slightly odd anyway (as the canonical signal is TERM). We did that because the C bridge does.
However, this does not work with the Python bridge on Debian/Ubuntu: its PAM stack does not reset the signal mask, and the Python bridge does not configure the signals or do any cleanups on SIGTERM either. As cockpit-session ignores SIGHUP, we ended up with ignoring SIGHUP in the user and priv bridges and all processes spawned by it.    
While that unintended inheritance of SIGHUP should be fixed, let's also try to avoid it and send SIGTERM to the bridge children on exit.
Also, this really applies to all processes that the bridge spawns: We don't want to leak any process, not just the "spawn" channel ones in particular. Thus lift the PDEATHSIG up …
=> python: Generalize subprocess cleanup, and use TERM instead of HUP

pkg/lib/patternfly/patternfly-5-overrides.scss
This looks like a lot, but it's really just this commit: df3bc8cc1327feda35ef5c93550868b24dd9bb4a. The rest should go away after the RTL branch (#18777) lands and this is rebased.
If there are any conflicts when rebasing, do a hard reset on this branch and git cherry-pick that commit.
It's really rather small and should land in the same release.
=> pf: Fix RTL for masthead, menus, and expandables

src/cockpit/peer.py, src/cockpit/superuser.py, test/pytest/mocktransport.py, test/pytest/test_peer.py
We need to cancel the .do_connect_transport() function in various situations:
- we called .close() ourselves
- we got an error or EOF on Peer stdout
- we got our "init" message on Peer stdout and are therefore connected
This non-linearity undermines our somewhat naive approach to thinking that the connection process could be done using pure async/await.
Let's repurpose our init_future future: it's now created on the Peer on initialization and, for as long as it's around, the peer is considered to be uninitialized.  It represents (approximately) the future result of the .start() function.
It can have its value filled it from exactly two places:
- when .do_close() is called [which can happen in response to many things]
- when we get the "init" message from the other side
.start() basically …
=> python: try a different approach with Peer.start()

test/common/cdp.py
Since version 113, it runs into the same problems as Firefox.
=> test: Apply Sizzle document hack also on Chromium

test/verify/check-connection
This currently works fine for local sessions, as the bridge does not launch the agent there (that's done by our pam_ssh_add). With cockpit-desktop it also works fine with the Python bridge, but not the C bridge (it sends SIGTERM, but the agent never receives it). That still needs to be debugged or worked around, but until then let's make sure that we don't regress this in the currently working scenarios.
----
See [this investigation](https://github.com/cockpit-project/cockpit/pull/18757#issuecomment-1543749060) for details. @allisonkarlitskaya and I have some ideas how to fix this. My first attempt was PR #18808, but this was a failed experiment. We have another approach in the pipe, though.
=> test: Check for leaked processes after browser logout and cockpit-desktop

src/bridge/cockpitrouter.c, test/verify/check-superuser
If a superuser rule has a label, use that as ID instead of argv[0]. That's what the Python bridge already does, and it's more robust: Labels are meant to be unique, while it's conceivable to have more than one rule for a given program name: they could run in different modes, or there could be alternatives in different paths.
----
I noticed that as part of issue #18711. That will make the test fail "better" under the Python bridge, it should now say "No authentication agent found".
[corresponding python bridge code](https://github.com/cockpit-project/cockpit/blob/68980cd34568a52bc0e2000d79ff0dd823762a87/src/cockpit/superuser.py#L153)
With this PR, `TestSuperuser.testMultipleBridgeConfig` fails more reasonably with the pybridge:
=> bridge: Prefer label as superuser rule ID

pyproject.toml, src/build_backend.py, src/cockpit/bridge.py, src/cockpit/channel.py, src/cockpit/channels/__init__.py, src/cockpit/channels/filesystem.py, src/cockpit/channels/http.py, src/cockpit/channels/metrics.py, src/cockpit/channels/stream.py, src/cockpit/config.py, src/cockpit/internal_endpoints.py, src/cockpit/misc/bootloader.py, src/cockpit/misc/print.py, src/cockpit/packages.py, src/cockpit/peer.py, src/cockpit/polyfills.py, src/cockpit/protocol.py, src/cockpit/remote.py, src/cockpit/router.py, src/cockpit/samples.py, src/cockpit/superuser.py, src/cockpit/transports.py, test/pytest/mockpeer.py, test/pytest/mocktransport.py, test/pytest/test_bridge.py, test/pytest/test_packages.py, test/pytest/test_peer.py, test/pytest/test_samples.py, test/pytest/test_transport.py
This commit is based on doing two things:
- selecting "i" rules for ruff in our `pyproject.toml`
- running `ruff check --fix .`
=> python: isort everything via ruff

pkg/systemd/logs.scss
This just got messed up from multiple layers of custom CSS.
This partially reverts https://github.com/cockpit-project/cockpit/pull/18780
=> logs: remove redundant CSS - toolbar paddings are fine

test/verify/check-metrics
TestHistoryMetrics.testNoDataFailed did not do that, which leads to unexpected SELinux denials with latest PCP.
testNoDataEnable already did it, but in a brittle way, clean this up as well.
---
This broke https://github.com/cockpit-project/bots/pull/4779, see [failed test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4779-20230517-230633-afb83d1f-fedora-testing-daily-cockpit-project-cockpit/log.html#64). Triggering this image run here as well.
=> test: Set correct SELinux context for PCP

test/verify/check-system-info
On a local undisturbed system, it takes about 12s to reconfigure chrony. It often times out on our CI machines.
----
See [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4775-20230517-070749-d90299da-fedora-38-pybridge-cockpit-project-cockpit/log.html#273-2)
=> test: Allow more time for configuring chrony

pkg/lib/cockpit-po-plugin.js, test/common/testlib.py, test/verify/check-pages, test/verify/check-system-services
Package specific translation files (e.g ./usr/share/cockpit/storaged/po.zh_CN.js.gz) do not include translations for imported components from pkg/lib.
Some reproducers for example are (switch to chinese for example as this is almost 100% translated):
- Try to add-hoc install anything (cockpit-pcp, realmd...)
- Try to reboot machine
- Try to change system time
- Try to change password for user
@martinpitt or @allisonkarlitskaya I think you were making changes to translations lately. This already landed in 8.8/9.2 so this is at least a couple of months old. I consider this PR a hack and I believe there is better solution. Do you have better idea what can be broken?
=> po: Also include pkg/lib translations

pkg/storaged/fsys-panel.jsx, pkg/storaged/stratis-details.jsx
The filesystems of a pool can not grow to fill the whole pool so let's reduce their usage bar to their maximum (combined) size.
https://issues.redhat.com/browse/COCKPIT-999
=> storage: Account for overhead in Stratis pools

test/common/testlib.py
The expected stack trace added in commit 3d789f473fd was done for RHEL 8 with Python 3.6. Newer Python on Fedora 38 capitalizes the exception message, so allow both cases.
---
See https://cockpit-logs.us-east-1.linodeobjects.com/pull-18837-20230523-144846-e3e409ee-fedora-38-pybridge/log.html#111
=> testlib: Adjust expected pybridge traceback for Fedora 38

src/cockpit/polkit.py, src/cockpit/polyfills.py, src/cockpit/superuser.py, test/verify/check-superuser
The official API for this is libpolkit-agent, which hides implementation
details like the path of the suid helper binary.  Fortunately this
happens to be the same in all our supported OSes. There have been
existing implementations like Enlightenment's polkit-efl-agent which
rely on this, and it hasn't changed in years, so this seems acceptable.
Fixes #18711
=> bridge: Add polkit responder to Python bridge

src/cockpit/bridge.py, src/cockpit/superuser.py, test/pytest/pseudo.py
ferny stopped implementing our send-stderr command, which was only used for us, so we have to implement it ourselves now, from our InteractionResponder in superuser.py.
On the plus side, we can now use interaction_client.py to send custom commands.  According to the ferny documentation, we should prefer this over sending messages for ourselves.
Note: in comparison to the old send-stderr handling inside of ferny, our new `cockpit.send-stderr` command no longer implies that the ferny interaction is complete — we need to send `ferny.end` separately.  This isn't actually required for the interaction to exit (since we'll send our "init" message very soon anyway) but is required in some situations to prevent ferny from interpreting our dropping the stderr socket as an unexpected exit.
=> python: update ferny, implement cockpit.send-stderr

pkg/storaged/part-tab.jsx, test/common/test-functions.js, test/common/testlib.py, test/verify/check-storage-basic, test/verify/check-storage-mounting, test/verify/check-storage-nfs, test/verify/check-storage-used
The tricky CSS tricks turned out to be a bit too tricky in the case where the production CSS already uses ::after or ::before pseudo elements.  Our ListingTable component uses those alot for handling the mobile layout, for example.
Let's use to most straightforward way: setting the text of an element via injected JavaScript.
This might fail when React decided to render inbetween the call to set_mock and capturing of the actual screenshot.  But the tests keep the pages quiet during pixel testing anyway, so hopefully this will not happen in practice.
Another way this might fail is that React gets confused the next time it renders after the call to set_mock because the DOM has changed too much.  This can hopefully be prevented by only replacing the text of elements, and not their children.
=> test: Don't use CSS to replace DOM elements with arbitrary text

HACKING.md, build.js, test/README.md
For a long time we've had a better way than `image-customize` for
iterating destructive tests. Split the section for
destructive/nondestructive, and use watch+rsync mode for the former.
Stop explicitly documenting running against an arbitrary running machine. This
is still way too dangerous. People can and will figure it out with the
`--machine`/`--browser` arguments, but at least stop recommending this footgun.
----
Rendered preview: https://github.com/martinpitt/cockpit/blob/doc-test-iterate/test/README.md#fast-developtest-iteration
=> test: Update "Faster iteration" documentation

test/run
It's called "daily" now since it also installs the daily UDisks2 stack.
=> test: Remove "dnf-copr" scenario name

pkg/systemd/overview-cards/cryptoPolicies.jsx, pkg/systemd/overview-cards/realmd.jsx
These declared strings are used only on one place so move them closer. The reason behind this is that if they are defined as static variables they are immediately loaded and `_()` is valuated before `cockpit.lang` is set and thus are not translated. If these strings are declared inside of a function they are evaluated only upon usage when `cockpit.lang` is set.
=> cryptoPolicy: Move strings closer to their usage

test/verify/check-shell-multi-machine
A symlink to /bin/false behaves very differently: It makes cockpit-bridge exit with 1, instead of the shell failing with "command not found" and exit code 127. To make this work on a read-only /usr on OSTree, use overlayfs to remove the file.
----
This is a prerequisite for fixing testTroubleshooting with the pybridge in PR #18864. The C bridge handles this failure mode specially, but I don't want to do this for the pybridge: `cockpit-bridge` exiting with code 1 is very much not a symptom of an uninstalled cockpit!
=> test: Test "no-cockpit" case realistically

pkg/lib/python.js
This isn't installed everywhere any more. Use `command -v`.
Also drop the long-obsolete check for `python`, all our images have Python 3 now.
-----
This helps to fix [this aarch64 failure](https://artifacts.dev.testing-farm.io/05127b37-6124-4c25-a26e-02cfddf31b27/), see https://github.com/cockpit-project/starter-kit/pull/660 . That PR now pulls in this PR, and it passed everywhere.
=> lib: Avoid `which` in python.js

src/cockpit/remote.py, test/verify/check-shell-multi-machine
Update ferny to c161ab97558. This gets us the finer-grained HostKeyError
subclasses from https://github.com/allisonkarlitskaya/ferny/pull/15 and
the better `handle_known_hosts` behaviour from
https://github.com/allisonkarlitskaya/ferny/pull/16.
Fix SshPeer to at raise `invalid-hostkey` instead of `unknown-host` for
the "changed key" case. Factorize the building of the PeerError.
TestMultiMachine.testTroubleshooting gets a little further now. It still
fails later on because of an unrelated error (UI expects `no-cockpit`,
but gets `peer-disconnected`), so keep the todo, but adjust its reason.
Fixes #18713
-----
=> pybridge: Fix handling of changed SSH host keys

pkg/lib/cockpit-components-logs-panel.jsx
For badges with only a number add a screenReaderText which indicates the content/status of the badge.
https://www.patternfly.org/v4/components/badge/#badge
=> lib: selinux: add screen reader text for badges

.github/workflows/weblate-sync-po.yml
This was forgotten in commit 89db1c68a9.
---
See [recent failure](https://github.com/cockpit-project/cockpit/actions/runs/5124751088/jobs/9217014445)
=> workflows: Fix weblate-sync-po for moved make-bots

HACKING.md
New contributors keep trying this and fail, this has become a FAQ. Explicitly point out that the given clone command is not an accident, but deliberate, and show how to work with a fork.
---
Rendered view: https://github.com/martinpitt/cockpit/blob/hacking-forks/HACKING.md
=> HACKING: Warn against cloning a fork

src/cockpit/remote.py, test/verify/check-shell-multi-machine-key
When opening a remote host channel without `user`, stop assuming the current local user name, as that overwrites any `User` field in the SSH configuration.
Instead, we need to do the opposite: for an unknown host, the UI will not set a `user` field in the channel options, but for an actual login attempt with a password it will. We need to treat them as the same channel in the `self.remotes` map. The C bridge deals with this in cockpit_router_normalize_host_params() by disregarding the `user` field if it is equal to the current user name.
This is a rather silly hack for backwards compatibility, but while we have two bridges, let's rather stay bug-for-bug compatible and clean this up in the UI only after we drop the C bridge.
There is one extra tweak: `rpartition()` returns an empty string, …
=> pybridge: Fix clobbering remote user set in SSH config

test/common/cdp.py
Since version 113, it runs into the same problems as Firefox.
Cherry-picked from commit d9426e07a261c182.
-----
See https://github.com/cockpit-project/bots/pull/4852
=> [r79] test: Apply Sizzle document hack also on Chromium

test/verify/run-tests
The imp module is slated for removal in 3.12, the current release is 3.11 so a potential next Fedora tasks container major upgrade might break.
=> test: use importlib instead of deprecated imp

test/common/lcov.py
This code only runs when coverage is enabled and gives a good indication no coverage was generated.
=> test: print message to stderr when no coverage is generated

src/ws/cockpit.appdata.xml.in
The previous screenshots don't exist any more, update to current ones (Overview and networking).
Drop the `<translation>` tag. We don't build/ship *.mo files, and don't plan to.
----
See https://appstream.debian.org/sid/main/issues/cockpit.html . This leaves the "icon" type, but I don't know what to do about that.
=> ws: Update AppStream screenshot, drop translation tag

tools/cockpit.spec
Let's start cautiosly with Rawhide. Once this got some field experience, we can lower this to 38 and replace the /pybridge scenario.
---
We don't run rawihde tests on our CI, but we have the TMT tests.
https://issues.redhat.com/browse/COCKPIT-940
=> tools: Enable Python bridge on Fedora ≥ 39

test/verify/check-networkmanager-firewall, test/verify/check-system-info, test/verify/check-system-journal
To stop using sizzle we need to stop using some of it's custom css pseudo selectors, `:first` is one of them and can in most cases be easily replaced.
=> test: don't use non-standard :first selector

test/common/pywrap
This option is not yet available in RHEL 8 and 9 (Python 3.9), which broke the FMF tests.
Commit 0d58ab9dbfd introduced that, but I landed that prematurely.
--- 
See e.g. https://artifacts.dev.testing-farm.io/a5b4ffaf-d3e8-420d-b323-2bb246e28185/ for how this fails. Sorry about that!
=> test: Drop python3 -P option

tools/debian/cockpit-ws.lintian-overrides, tools/debian/control, tools/debian/rules
Run the bridge unit pytests during package build, but with a twist:
Normally they run as part of `dh_auto_test` after building, but before
installation. But we want to make sure that we installed all files
correctly, so instead run them after install against the
debian/cockpit-bridge/ binary package tree.
Add a hack around broken pip, it always appends an extra `/local` to the
given --prefix, no matter what gets specified. See
https://bugs.debian.org/1035546
Keep the older C bridge on stable releases, in particular Debian 11 and
Ubuntu 22.04 LTS. But also still keep Ubuntu stable on the C bridge,
until testCockpitDesktop gets fixed.
Add a recommendation for openssh-client, as the bridge now uses the
ssh(1) program to connect to remote hosts.
-----
=> tools: Switch Debian devel series to Python bridge

src/build_backend.py, src/client/cockpit-beiboot, src/cockpit/beipack.py, src/cockpit/bridge.py, src/cockpit/misc/print.py, src/cockpit/superuser.py, test/pytest/test_beiboot.py, test/pytest/test_bridge.py, tools/vulture-suppressions/cockpit.py, tools/vulture-suppressions/ferny.py
This is the last missing piece from Cockpit Client beibooting — we can now run a root bridge, recursively beibooted.
=> Add support for beiboot-via-sudo

pkg/shell/shell-modals.jsx
Ctrl+Shift+J isn't supported in Epiphany or in Cockpit Client.
=> shell: recommend Ctrl+Shift+I for Javascript console

src/client/cockpit-beiboot
The existing hack was triggering the "superuser_legacy_init" code path in the C bridge, which was causing hangs when logging on on systems which have the C bridge installed.
This new approach should work better.
=> cockpit-beipack: better handling of explicit-superuser

test/static-code
a122ebdb9628f9a5cebc821 removed the ruff.toml file but did not update `test/static-code`.
=> test: unbreak the post-commit hook

src/client/cockpit-beiboot
If we get "authorize" control messages from the Peer (in spite of our attempt do disable them) then just ignore them.  This happens with old peers (such as in CentOS 7) that have the "legacy" superuser code in the bridge.
Fixes #18944
=> cockpit-beiboot: ignore unexpected "authorize"

containers/flatpak/beiboot-extra-packages, containers/flatpak/cockpit-client.yml.in, containers/flatpak/prepare
It's now possible to do
```
PYBRIDGE_ENABLE=enable containers/flatpak/install --user
```
to get a version of Cockpit Client including cockpit-beiboot.
=> flatpak: add envvar for enabling cockpit-beiboot

test/common/testlib.py
This causes several regressions: It breaks at least timeout handling, and thus naughty matching. It also does not print tracebacks any more in `--sit` mode.
This reverts commit 163555f90dc2872be715da073ae468c9b77867cf.
---
This should fix failures like [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18954-20230616-093408-e87916ce-centos-8-stream/log.html#230-2) which got introduced by prematurely landing #18954.
=> Revert "testlib: change approach for --sit and log captures"

test/common/testlib.py, test/verify/check-system-info, test/verify/conftest.py
With this in place, it's now possible to run the integration test suite via pytest with something like the following:
$ test/common/pixel-tests pull
$ test/image-prepare
$ test/common/pywrap -m pytest test/verify -n4
Note: the -n option is for specifying the level of parallelism and requires the python3-pytest-xdist plugin to be installed.
~Note also: there's currently no support for sharing machines for non-destructive tests, but I have some ideas there...~
=> Initial support for running integration tests via pytest

src/cockpit/data/__init__.py
importlib.resources is supported from Python 3.7, but only Python 3.11 contains a new enough version that non-filesystem-based loaders are supported as Traversables.
That means that all Python versions from 3.7 through 3.10 were subtly broken when running out of a beipack.  That resulted in the beibooted bridge unable to become root, for example.
Instead of playing games with imports, let's just hardcode the version we know to be working.
=> python: use importlib.resources only on Python 3.11

test/common/testlib.py, test/verify/check-static-login
If there is a busy file, this leads to the cleanup silently succeeding, and the subsequent test then failing with "directory already exists" or similar errors from trying to recursively mount/restore.
This was introduced into the initial restore_dir() implementation in commit 1dcb1a60365f5 (later generalized in commit 48fff9a683702a without particular justification).
With this change, the cleanup of the affected test now fails directly, which is easier to debug.
The main exception is restoring /home/admin -- many tests do that without stopping all admin processes first. This happens in nonDestructiveSetup(), but that runs after restoring the home dir. This is tricky to fix, so for now add an exception to continue unmounting that lazily.
---
I don't have a recent log at hand, but I …
=> test: Don't unmount restored directories lazily

pkg/lib/cockpit-components-shutdown.jsx, test/verify/check-system-shutdown-restart
PatternFly 5 changed it's onChange callback function to now always return an event as first argument.
Additionally add a basic test to test if we can set a reboot message, as testing if the message appears is hard and prone to race conditions.
---
Fixes #18966
I wonder if we have more of these issues, I'll try  to find them.
=> pkg: correctly call onChange handler

src/client/cockpit-client
WebKit2.WebsiteDataManager.get_local_storage_directory is deprecated and as this is the location of the browsers LocalStorage it doesn't seem logical to save cookies there.
---
I'm wondering if we should change this to `XDG_STATE_HOME` or `CACHE`? Either way, I never have any cookies after using cockpit client.
```
File: /home/jelle/.local/share/cockpit-client/cookies.txt   <EMPTY>
```
If I change the window location, cookies do get saved :) So hmm my Cockpit does not seem to save cookies.
BTW: webkit tells you to use `dm.get_base_data_directory` but this seems to always be None so we might as well use GLib.
=> client: save cookies in XDG_DATA_HOME

src/client/cockpit-beiboot, src/client/cockpit-client-ssh, test/verify/check-client
The flatpak Client's webkit browser is really hard to test, as it is so inaccessible. Introduce test/verify/check-client which reproduces the cockpit-{ws,client-ssh,beiboot} plumbing that cockpit-client does, and exercise a lot of login scenarios to a machine with and without cockpit-bridge.
This finds some minor bugs, mark them with FIXME and disable the check or do a workaround.
=> test: Add cockpit-client browser integration test

test/run
- Clean up run-test naughty tracking option. We always want to track naughties for CI invocations, so stop making it so dynamic through the variable.
- Factorize the image-prepare and run-tests invocations. This will make it easier to add more scenarios.
- Quote $TEST_OS.
- Make scenario cases non-exclusive. Use bash's `;;&` case operator to always fall through to the next match. This make it possible to have combined scenarios such as "pybridge-devel" or "daily-firefox". With that, we cannot use the '*)` fallback case any more, so use the $RUN_TESTS variable to determine if none of the scenarios matched.
---
Broken out from #18949 , but I'd like to test this separately to make sure I didn't screw up.
=> test: Refactor CI entry point and allow combining scenarios

test/common/netlib.py, test/image-prepare, test/verify/check-connection, test/verify/check-metrics, test/verify/check-static-login, test/verify/check-superuser, test/verify/check-system-info, test/verify/check-system-realms
https://github.com/cockpit-project/bots/pull/4886 moves our "debian-stable" image from Debian 11 to 12. Adjust the test special cases.
Also enable the FreeIPA tests on Debian, as the packages are again available in both stable and testing. TestIPA.testQualifiedUsers still fails, so keep skipping that one for now -- let's unblock the lockstep bots+cockpit PR and investigate that as a follow-up.
---
This needs to land in lockstep with https://github.com/cockpit-project/bots/pull/4886
#18978 ran the libvirt change for all other OSes.
=> test: Adjust special cases for debian-stable moving to Debian 12 "bookworm"

src/cockpit/bridge.py, test/verify/check-client, test/verify/check-connection, tools/debian/rules
This picks up the remaining issue on #18757.
https://issues.redhat.com/browse/COCKPIT-938
=> pybridge: Fix ssh-agent cleanup for setgid, enable on on current Ubuntu releases

tools/debian/rules
We intended to keep the C bridge on Debian stable (for backports) for the time being. But Debian stable recently moved from 11 (bullseye) to 12 (bookworm), so adjust the version filter.
Also drop the obsolete Ubuntu comment, as that was fixed in commit b7895b8e8e0508, and the pybridge got enabled in commit 2dce6929c1.
=> tools: Keep C bridge on Debian stable (12) for now

test/common/testlib.py
Commit 582a91fc5d199f introduced the assertion that sit() is always called with at least one machine. But that isn't true when running a test with `--machine`, which breaks debugging.
=> test: Fix sit regression with --machine

src/cockpit/channels/dbus.py, test/common/testlib.py, test/verify/check-system-services
We've had [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18656-20230419-120249-8715af15-fedora-37-pybridge/log.html#274) for ages, but it becomes more pressing now that the pybridge is in production.
=> test: Split and fix TestServices.testBasic, fix with current ruff 0.0.274

test/common/netlib.py
On slow CI machines, the networking page sometimes is still loading after 20 seconds.
---
See [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18982-20230621-213019-389e6c00-ubuntu-stable/log.html#92-2), in particular the screenshot.
=> test: Bump wait_for_iface() timeout

test/verify/check-system-services
This sometimes also times out for other status checks. Do what I should        
have done in the beginning, and apply the extended timeout to        
check_service_details() itself, not just to the common case wrapper.        
WARNING: Waiting for ph_collected_text_is("#statuses .status","Failed to startAutomatically starts")        
took 13.0 seconds, which is 86% of the timeout.        
----
Should help for [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18968-20230621-203459-0814b3d3-ubuntu-stable/log.html#335-2). I [stress-test](https://github.com/cockpit-project/cockpit/pull/18988/commits/93ab8a369eba368b70357272fabc2c69289909ea) this in the first round.
=> test: Apply TestServices extended timeout to all unit status checks

test/browser/browser.sh
This option got dropped in dnf 5, and thus this started to fail on Rawhide. Replace it with the corresponding option.
See https://bugzilla.redhat.com/show_bug.cgi?id=2216622
---
Should fix [this rawhide TF failure](https://artifacts.dev.testing-farm.io/958c5148-f22a-4a23-aa91-5e37a8f26188/). Let's see what else is wrong.
=> fmf: Replace deprecated dnf --noautoremove option

configure.ac
Giving --enable-pybridge to configure works as intended, but there will be a warning as well because it is mispelled in one place:
configure: WARNING: unrecognized options: --enable-pybridge
=> build: Fix spelling of --enable-pybridge option

.github/workflows/unit-tests-refresh.yml, containers/unit-tests/setup.sh, pyproject.toml
This spontaneously broke our CI the last time around, as ruff got upgraded and started to complain.
----
I know the latest run throws some complaints. I fixed many of them yesterday already, but we need to start ignoring this:
> RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
I'll do a [first refresh run](https://github.com/cockpit-project/cockpit/actions/runs/5348110692)  and expect this to fail. **Update**: [and it did in the right way](https://github.com/cockpit-project/cockpit/actions/runs/5348110692/jobs/9697535698#step:4:450)
=> workflows: Run pytest-cov scenario in unit-tests-refresh, fix for ruff 0.0.274

pkg/lib/esbuild-compress-plugin.js
Stop storing mtime of css in `.gz` files
to make package builds reproducible.
Without this patch, `/usr/share/cockpit/machines/index.css.gz` would vary between build.
This patch was done while working on reproducible builds for openSUSE.
=> Stop storing mtime of css

src/client/cockpit-client
There is no need to bind the socket manually, cockpit-ws is perfectly able to do that by itself.
----
I locally built and tested the flatpak, works fine. Let the tests do the rest.
=> client: Simplify cockpit-ws startup

test/common/testlib.py
Commit 8ffca5d5ee botched the fix for the case that `machines` was not provided. It's expected to be a dict, so actually fall back to a dict, not a list (as it was before commit 582a91fc5d199f). Fixes
```
File "test/verify/check-system-realms", line 96, in testQualifiedUsers
testlib.sit()
File "main/test/common/testlib.py", line 2533, in sit
for (_, machine) in (machines or []).items():
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```
---
I am really embarrassed and ashamed now.. :see_no_evil:
=> test: Fix --sit with existing machines

test/verify/check-system-realms
Debian's FreeIPA has a bug about getting confused by some imaginary "NTP service", which it tries to restore on leaving, and fails. Reported to https://bugs.debian.org/1038925
As the test checks lots of other things after leaving the domain, apply a workaround instead of handling this through a naughty.
=> test: Fix TestIPA.testQualifiedUsers for Debian

tools/arch/PKGBUILD
This is a partial sync of the PKGBUILD, as they split the cockpit package into cockpit-{storaged/packagekit} which might require some more work.
This would be nice to land to unblock https://github.com/cockpit-project/bots/pull/4930 or I revert the dropping of the deps there but they are kinda useless so let's make the build chroot smaller :)
=> tools: sync arch makedepends

src/cockpit/samples.py
This often crashes with
PermissionError: [Errno 13] Permission denied: '/var/lib/containers/storage/overlay'
There is not much that we can do about it, so ignore it. The code already tried to do that, but in Python a failure is an exception, not a falsy return value.
---
I've seen [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19009-20230625-083043-dbb55d02-debian-testing-storage/log.html#22) quite often recently, since we enable the pybridge on more OSes.
=> pybridge: Ignore OSErrors in MountSampler

test/common/testlib.py
SVG icons seems to render less pixel perfectly than the rest, but we don't want to ignore them altogether.
Fixes #19001
=> test: Allow 20 different pixels

test/verify/check-packagekit
The initial empty line in the mocked /usr/local/bin/kpatch causes execve() to fail with `ENOEXEC` "Exec format error". The shell and the C bridge paper over this by falling back to interpreting the file as a shell script, but Python's subprocess gives up at this point.
----
Fixes [TestUpdates.testKpatch](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19011-20230626-181028-a9a8fe4a-rhel-9-3-expensive/log.html#11-2) with the Python bridge. That runs only on RHEL, so we didn't see it yet. Spotted in #19011
=> test: Fix shebang in TestUpdates.testKpatch

test/verify/check-system-info
One minute is often too tight, causing timeouts.
----
See [failed test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19011-20230626-181027-a9a8fe4a-rhel-9-3-other/log.html#109)
=> test: Increase timeout for insights-client --register

test/verify/check-pages
The Python bridge does not dynamically change its locale from `Accept-Languages:`, but just defaults to the standard environment of the logged in machine.
We decided to not reimplement this in the pybridge, as that is weird, error prone, and a corner case: No other Linux command line software does that, it won't change the locale of existing running programs which got spawned before changing the language (as that's impossible), the code was making assumptions about locale names and availability, and we take very little human readable text directly from command-line programs, most of it gets interpreted, formatted, and translated in the UI.
----
Spotted in PR #19011 with [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19011-20230626-181028-a9a8fe4a-rhel-9-3-expensive/lo …
=> test: Drop locale change check from TestPages.testBasic

pkg/shell/hosts_dialog.jsx, test/verify/check-shell-multi-machine
Without handling this explicitly, a form submit event will reload the page.  This is very confusing when hitting enter in the login dialog for a remote host.
Fixes #18653
=> shell: Apply host dialogs on form submission

src/cockpit/bridge.py, test/pytest/test_bridge.py
The UI never retrieves package data from the privileged instance, so this is just a waste of time, and moreover, RAM: Currently, the bridge keeps all package files in memory. We need to fix that, but at least stop from having them twice.
=> pybridge: Don't scan packages in the --privileged bridge

tools/debian/cockpit-doc.lintian-overrides, tools/debian/cockpit-ws.lintian-overrides, tools/debian/control, tools/debian/copyright.template, tools/debian/rules
Shipping the pybridge broke reproducibility, see https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/cockpit.html
=> Debian: Fix reproducible build, some lintian updates

src/cockpit/bridge.py
Commit b7895b8e8e broke the agent spawned by the bridge. This is only exercised on our CoreOS images, for which we don't yet run pybridge tests; the other integration tests just make sure that it gets cleaned up after logout, which was still the case.
The parsing code relies on the format `SSH_AUTH_SOCK=/path`, which the shell command did not previously provide; fix that. We could also simplify the parsing instead to just read the sole path from stdout, but the `NAME=` format provides an additional assertion that we are not just reading some unrelated gibberish from the command.
On failure, clean up the terminated process to avoid the zombie sticking around.
----
See https://github.com/cockpit-project/cockpit/pull/19009#issuecomment-1608807887 -- this fixes some failures in …
=> pybridge: Fix ssh-agent launching

src/cockpit/internal_endpoints.py
lookup_config() must be called with a relative path, as otherwise joining some "/etc/.." prefix to the given value always results in the value itself, due to how path joining works. That led to trying to write the config into the nonexisting /machines.d/ directory, breaking a lot of TestMultiMachine tests on CoreOS with the Python bridge.
---
Broken out from #19009 and tested there on coreos.
=> pybridge: Fix cockpit_Machines directory lookup

test/verify/check-client
This is more robust and explicit. This also enables the test on arch, which runs the Python bridge now.
=> test: Switch check-client from "only" to a "skip" list

pkg/systemd/overview-cards/realmd.jsx, src/tls/cockpit-certificate-helper.in
Don't try to clean up IPA credentials on non-IPA domains. It's a bit of a mystery how that ever worked, as `cockpit-certificate-helper ipa cleanup` was failing reliably due to the nonexisting key file. Use the same check as when joining the domain.
For belt-and-suspenders, and also to avoid failing when the admin manually removed the certificate after joining, also robustify the helper to only remove and untrack the certificate if it actually exists.
---
Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19011-20230628-083244-bfadd600-rhel-9-3-networking/log.html). This is straight out of the "WTH??" category, how was this not a plain failure all the time? :thinking:
=> systemd, tls: Robustify cockpit-certificate-helper ipa cleanup

pkg/lib/journal.js, pkg/systemd/logsJournal.jsx, test/verify/check-system-journal
When the filter gets changed while the initial non-following journalctl
runs, that runs updateQuery with new options. That will first stop all
previous journalctls. However, that will still call the `.done()`
handler for that initial journalctl query, and happily go on with
starting the subsequent journalctl in following mode. This results in
two journalctls running at the same time, leading to duplicated entries.
To fix that, add a `stopped` flag to the returned journalctl object, and
don't start the following journalctl if it's set.
Fixes #18976
-----
This fixes the [TestJournal.testRebootAndTime() flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19009-20230628-103340-4195a080-fedora-38-other/log.html#126-2). See #18976 for the gory details. This now locally survived two …
=> systemd: Fix journalctl follow invocation race

test/verify/check-client
fedora-testing is Fedora 38 and doesn't get the Python bridge installed, which means we can't do the beiboot test with it yet.  Add `fedora-testing` to the skip list.
=> verify/check-client: skip fedora-testing also

pkg/systemd/overview-cards/cryptoPolicies.jsx, test/verify/check-system-info
This pr is related to #18790 
The wrong names were because of this line `const displayProfileText = profile => profile === "FIPS" ? profile : profile.charAt(0) + profile.slice(1, profile.length).toLowerCase();`
Because it's making words the lowercase
-  Default:sha1
- Fips:ospp
- Default:sha1
I tried to find the single condition that will make them something like these words because they are correct
- Legacy:AD-support
- Default:SHA1
- FIPS:OSPP
But could not be possible because every word has something different.
So finally added this condition that will make it correct
```
const displayProfileText = (profile) => {
return profile === "FIPS" ? profile
: profile === "LEGACY:AD-SUPPORT" ? "Legacy:AD-support"
: profile === "DEFAULT:SHA1" ? "Default:SHA1"
: profile === "FIPS:OSPP" ? profile
: …
```
=> systemd: Don't mangle crypto policy names

test/common/testlib.py, test/verify/check-superuser
The pybridge will only start a privileged bridge during startup when explicitly instructed in the "init" message.  This is now the officially correct behavior, although it differs from what the C bridge did.
Replaces #18984
=> test: Make pybridge initial superuser behavior official

src/cockpit/channels/http.py
When a socket goes down underneath a HTTP channel, depending on the
timing this could result in either a `ConnectionRefusedError` (which
http.client intercepts and wraps), or a `ConnectionResetError` (which
isn't wrapped). For the channel these should both end in the same
"terminated" error code, instead of crashing the task.
Reduce assumptions and make this robust by catching all `OSError`s.
---
This leads to [pybridge crashes in c-podman](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1322-20230703-042644-64a79ae1-fedora-38-pybridge/log.html#21), see https://github.com/cockpit-project/cockpit-podman/pull/1322
=> pybridge: Catch OSError in http channel

test/common/pixel-tests
Since there is no plain "fedora-38" anymore, for example.
=> test: Let "pixel-tests fetch" iterate over all scenarios

test/run
Bridge matches more then just networking tests but also testMultipleBridgeConfig of superuser which is also run in the expensive scenario.
I've only triggered the fedora-38 tests as this is mostly logic. This now excludes the following tests from networking:
```
TestClient.testBeibootNoBridge
TestClient.testBeibootWithBridge
TestSuperuser.testBrokenBridgeConfig
TestSuperuser.testMultipleBridgeConfig
TestSuperuser.testRemoveBridgeConfig
TestSuperuser.testSingleLabelBridgeConfig
```
=> test: don't run testMultipleBridgeConfig in networking scenario

src/client/org.cockpit_project.CockpitClient.desktop
This doesn't seem to be particularly well supported in all flatpak environments, particularly under KDE.
Fixes https://github.com/flathub/org.cockpit_project.CockpitClient/issues/29
=> client: disable DBusActivatable=true in desktop file

src/cockpit/transports.py
When creating a pty-enabled stream channel we call setsid() but depend on the shell to take control of the terminal.  fish doesn't do that, leading to an error message, rendering the Terminal page unusable if the user has fish as their default shell.
Let's call `os.login_tty()` explicitly.
Fixes #19075
=> python: use os.login_tty() on pty stream channels

pkg/lib/cockpit-components-modifications.jsx, pkg/lib/cockpit-components-table.jsx, pkg/selinux/setroubleshoot-view.jsx, pkg/shell/superuser.jsx, pkg/systemd/abrtLog.jsx
Deprecations / missing title found by making extranous `console.error` fail. Split up from https://github.com/cockpit-project/cockpit/pull/19053
=> Various PF fixes

src/common/cockpitfdpassing.c, test/verify/check-superuser
In some setups it happens that the spawned root bridge's stdin is non-blocking. Trying to call recvmsg() on it then often fails with `EAGAIN`, causing the superuser dialog to fail with "Problem becoming administrator: Cockpit-bridge: recvmsg(stdin) failed: Resource temporarily unavailable".
By default all stdio fds should be blocking. But when enabling sudo's `log_output` option, sudo splices the original stdio pipes to the log, and the stdin seen by cockpit-bridge ends up as non-blocking.
Avoid this by polling stdin until data is available. (There is no opposite to the `MSG_DONTWAIT` flag).
Fixes #17412
https://bugzilla.redhat.com/show_bug.cgi?id=2211760
=> common: handle non-blocking fd in cockpit_socket_receive_fd()

tools/debian/control
The most recent udisks2 version moved to libblockdev 3.0, which bumped its soname to libblockdev-mdraid3. udisks2 2.10 has a hard dependency to libblockdev-mdraid3, so we don't need to depend on the latter directly any more. But keep an alternative dependency for older releases.
Fixes https://bugs.debian.org/1040803
=> tools: Adjust Debian libblockdev-mdraid dependency for udisks 2.10

src/bridge/cockpitcpusamples.c, src/cockpit/samples.py, test/pytest/test_samples.py, test/verify/check-metrics
Fixes: #19055
After discussion in #19055 and on matrix we've decided to not ignore Tctl sensor as sometimes it is the only available sensor some CPUs expose in hwmon.
=> metrics: Fix CPU temperature sensor for AMD

.gitignore, pyproject.toml, src/build_backend.py, src/client/cockpit-beiboot, src/cockpit/_version.py, src/cockpit/bridge.py, src/cockpit/channels/packages.py, src/cockpit/misc/print.py, src/cockpit/packages.py, test/pytest/test_packages.py, test/verify/check-connection, test/verify/check-metrics, tools/vulture-suppressions/cockpit.py
Rework the packages loading code.  The main changes:
- we don't attempt to do checksums anymore.  This was taking a large amount of time when loading the bridge and we never implemented it properly anyway (since we weren't sending the `.checksum` fields in the manifests)
- drop all of the extra code we had for walking the paths in a particular order.  We just do (r)globs now.
- move all of the code for deciding which packages to load to a separate class.  We now load all of the manifests and evaluate them (requirements, conditionals, priorities) and only the packages that we actually intend to serve are then scanned.  The new structure also makes it easier for cockpit-beiboot to do its thing.
=> python bridge: rewrite packages.py

src/cockpit/bridge.py, test/pytest/test_bridge.py
Some OSes like current EndeavourOS have non-conformant os-release files
where URL values are not enclosed in quotes. These currently cause a
`ValueError` as splitting on `=` does not produce pairs.
To make this more robust, do the line and `=` splitting manually, and
ignore invalid lines. Only parse the actual value with shlex, to benefit
from unquoting and unescaping.
Fixes #19095
=> pybridge: Robustify parsing of os-release

test/verify/check-client, tools/cockpit.spec
After this, we can remove the fedora-38/pybridge scenario.
=> tools: Enable Python bridge on Fedora 38

tools/debian/control
The latest libblockdev-mdraid package does not depend on `mdraid` any more. That is okay, as it comes with some initrd and boot baggage, so we don't want to force it upon every cockpit user either. Trying to create an md array without mdadm installed gives a clear error message:
Error creating RAID array: The 'mdadm' utility is not available
So just add a Suggests for it.
Thanks to Michael Biebl for pointing this out!
=> tools: Suggest mdadm for cockpit-storaged

containers/ws/README.md
Fixes #19094
---
Rendered view: https://github.com/martinpitt/cockpit/tree/ws-runlabel-doc/containers/ws
=> containers: Document showing the "RUN" label command

test/browser/main.fmf, test/browser/run-test.sh, test/common/netlib.py, test/common/packagelib.py, test/common/storagelib.py, test/verify/check-connection, test/verify/check-metrics, test/verify/check-packagekit, test/verify/check-static-login, test/verify/check-storage-format, test/verify/check-storage-iscsi, test/verify/check-storage-mounting, test/verify/check-storage-msdos, test/verify/check-storage-nfs, test/verify/check-storage-raid1, test/verify/check-storage-unused, test/verify/check-system-info, test/verify/check-system-realms
This makes them nicer to develop/debug, faster to run, and we can run some in FMF.
Some spot-checks of the /storage scenario:
-  [main/f38](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19100-20230717-043759-accf9f88-fedora-38-storage/log): [642s on rhos-01-18, 46 parallel tests, 16 serial tests: 0: 71s, 1: 70s, 2: 75s, 3: 100s, 4: 71s, 5: 72s, 6: 81s, 7: 108s]
- [main/f38](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19085-20230710-072336-bd849f48-fedora-38-storage/log): [684s on 4-ci-srv-06, 46 parallel tests, 16 serial tests: 0: 78s, 1: 91s, 2: 88s, 3: 124s, 4: 78s, 5: 78s, 6: 90s, 7: 121s]
- [here/f38](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19102-20230717-084620-ce2cce7a-fedora-38-storage/log): [560s on rhos-01-8, 29 parallel tests, 33 serial tests: 0: …
=> test: Make some storage tests nondestructive

pkg/kdump/kdump-view.jsx, test/verify/check-kdump
Otherwise tooltip is not accessible
=> kdump: Test configuration button should use ariaDisabled

pkg/sosreport/sosreport.jsx, test/common/testlib.py, test/verify/check-sosreport, test/verify/check-system-info
If `sos report` fails, we can get an empty message in `error`. That will lead to not showing the error in the dialog at all (as it's falsy), even if errorDetail was set. Fix that by adding a generic fallback title.
Also log the full error for easier debugging. 
----
I noticed this while investigating the [current sos rawhide failure](https://bugzilla.redhat.com/show_bug.cgi?id=2223526). This looks really unfriendly -- you click "Report", the dialog flickers and nothing happens. Now it shows the error properly:
=> sosreport: Add fallback error message, fix testInsightsClient failure on rhel4edge

pkg/storaged/client.js, pkg/storaged/crypto-keyslots.jsx, pkg/storaged/fsys-tab.jsx, pkg/storaged/utils.js, test/verify/check-storage-mounting
util-linux accepts them and treats them like having mount options "defaults". Do the same instead of crashing on an undefined `.opts.v`.
As this is done three times in the code, introduce an utility function for it.
Rename testFirstMount() (which had a confusing name) to testFstabOptions(), and add reproducer there. Also strengthen the initial test to actually validate that the `x-foo` and `nofail` options appear in the UI.
Fixes #18406
=> storaged: Fix crash on fstab lines without mntopts

pkg/systemd/kernelopt.sh, src/ws/mock-kdc, src/ws/mock-pipes/exit127, test/static-code
We have plenty more shellcheck issues, but after fixing the missing shebang I thought it would be good to at least fix all shellcheck error's reported by `shellcheck -S error`. And shown by https://github.com/cockpit-project/cockpit/security/code-scanning?query=is%3Aopen+branch%3Amain+tool%3Ashellcheck++
=> Fix all shellcheck errors

test/verify/check-system-info
The asset tag should be available on x86_64 if product_serial is set.
Need to figure out if this does what it tells in ARM.
Should cover https://cockpit-logs.us-east-1.linodeobjects.com/pull-19111-20230720-115822-2f073721-fedora-38-devel/Coverage/pkg/systemd/overview-cards/systemInformationCard.jsx.gcov.html
=> test: add coverage for asset tag

pkg/systemd/overview-cards/systemInformationCard.jsx, pkg/systemd/overview.jsx
Triggered by PR #19118, trying to clean up the last bits of https://cockpit-logs.us-east-1.linodeobjects.com/pull-19118-20230720-180012-952e0fa8-fedora-38-devel/Coverage/pkg/systemd/overview-cards/systemInformationCard.jsx.gcov.html
=> SystemInformationCard cleanups

pkg/base1/test-browser-storage.js, pkg/base1/test-dbus-common.js, pkg/base1/test-dbus.js, pkg/base1/test-user.js, pkg/lib/serverTime.js, pkg/networkmanager/dialogs-common.jsx, pkg/networkmanager/network-interface-members.jsx, pkg/networkmanager/network-interface.jsx, pkg/packagekit/autoupdates.jsx, pkg/shell/machines/test-machines.js, pkg/shell/superuser.jsx, pkg/systemd/abrtLog.jsx, pkg/systemd/overview-cards/motdCard.jsx, pkg/systemd/terminal.jsx, test/common/testlib.py, test/pytest/test_bridge.py, test/pytest/test_browser.py
Some Friday evening doodling and cleanups. I at least found some bugs, too :grin: 
Most of the remaining jQuery promise API is hard to convert: They use `.stream()` or other Cockpit specific API, and that isn't compatible with Promise API. That should be fixed, but that requires actual thining :grin:
=> jQuery promise cleanup, convert some tests to async functions

pkg/static/login.html, pkg/static/login.js, test/verify/check-static-login
Currently we have two two identical id's which is not allowed.
QuerySelectorAll Does not like it :) https://cockpit-logs.us-east-1.linodeobjects.com/pull-18896-20230724-085434-ad7df50c-fedora-coreos/log.html#172-2
=> static: use a unique id for the bypass browser check

pkg/users/account-details.js, pkg/users/shell-dialog.js, pkg/users/users.js, test/verify/check-users
On Fedora a normal user can change it's own shell only through `lchsh` while other distributions do package `chsh` a setuid binary. As a compromise allow changing of the shell only for the Administrator and use `usermod` for changing the users shell which should be available on all supported systems by default.
---
Administrators can now change a users shell via the user account page.
=> users: allow administrators to change the user shell

test/verify/check-system-info
Test that setting the pretty hostname changes the hostname as well and the validation. This was not covered before in our tests.
Should cover:
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19120-20230722-055749-01048432-fedora-38-devel/Coverage/pkg/systemd/overview-cards/configurationCard.jsx.gcov.html
=> test: add verification for changing the pretty hostname

test/verify/check-networkmanager-basic
Also strenghten the IPv4 assertions.
=> test: Check configuring manual IPv6 address

src/client/org.cockpit_project.CockpitClient.metainfo.xml
The server does not need cockpit installed any more since the beiboot functionality.
----
Thanks @briansmith0 for pointing out!
=> flatpak: Update description

pkg/base1/test-dbus.js, src/cockpit/channels/dbus.py
Enlarge the scope of OSError interception to also comprise the "custom address" case.
----
Spotted in https://github.com/rhinstaller/anaconda/pull/4978
=> pybridge: Fix crash when connecting to nonexisting D-Bus address

test/common/lcov.py
This is more something for the future, as Anaconda can't bump `test/common` yet as we have moved to PF5.
=> test: handle Anaconda's master branch for coverage

test/common/test-functions.js, test/verify/check-metrics
This was a test PR, this would be a step towards doing our own `:contains` implementation. First get all our projects working correctly with `document.querySelector` and then in the future see if we can do a `:contains` implementation.
---
Just a test PR, to see if we really only need sizzle for `:contains`.
Failing tests on `fedora-coreos`, blocked on https://github.com/patternfly/patternfly-react/issues/9399
=> Only use Sizzle when required

packit.yaml, plans/all.fmf, plans/podman.fmf
This ensures that changes to the Python bridge don't break podman.
----
This introduces reverse dependency testing on the upstream level. Details and experiments are in https://github.com/cockpit-project/cockpit/pull/19117 -- especially with a commit that [breaks the bridge](https://github.com/cockpit-project/cockpit/commit/fb163e5cf2bf4430828fff04a0e168aec4d96032), and the [revdeps run](https://artifacts.dev.testing-farm.io/6925a99f-9f98-4e01-ba12-87c7b8960fc3/) installs c-ws from the PR packit COPR and c-podman from the main-builds COPR, and the podman tests fail as expected on the "KABOOM".
This particular test could be optimized, and only run on changes to src/ (bridge or ws), as these are the only things that actually affect cockpit-podman. There is a mechanism to do that with …
=> fmf: Run cockpit-podman tests on current Fedora

tools/debian/cockpit-ws.lintian-overrides
As of groff 1.23.0 "an-trap" macro was renamed to "an-input-trap". This change is already present in debian-testing.
However, xsltproc which we use to generate manpages still uses the old macro, since it runs on Fedora 38 docbook.
=> Add "macro 'an-trap' not defined" warning to lintian overrides

test/browser/main.fmf
tmt implicitly installs the packages for the primary (packit generated) COPR, but not the ones for all the other test plans. This led to cockpit-system and friends not being installed when running cockpit as reverse depedency gating test in PRs of other projects.
Do what we already do in c-podman etc. and declare our own dependencies properly. They were dropped in commit 9877d5163352, but the reason is obsolete: TF will now go out of its way to upgrade/downgrade packages to the versions in the COPR, and even validate their versions.
----
This broke running our tests in [udisks](https://artifacts.dev.testing-farm.io/cfb8d90b-c0d6-4df5-8c57-7ebefb0ce0e4/) and [selinux-policy](https://artifacts.dev.testing-farm.io/c7acd1f2-3616-4c8b-b2a5-58e009506030/). I validated that this works in …
=> fmf: Declare our own dependencies

test/verify/check-storage-mounting
testNeverAuto uses LUKS, uses memory hard PBKDF. We already have a separate class TestStorageMountingLUKS which is provisioned with more memory. Therefore move testNeverAuto to prevent flaky test runs, which fail with "Failed to add passphrase: Cannot allocate memory".
=> test: Move testNeverAuto under TestStorageMountingLUKS

test/verify/check-networkmanager-firewall
This is moderately complex, and newer PatternFly breaks the horizontal arrangement of the radio button blocks.
---
See https://github.com/cockpit-project/cockpit/pull/19138#issuecomment-1659789528 and the next comment -- I want to land this *before* resuming #19138, as this regression wasn't previously spotted by pixel tests. The RTL dialog shows a spacing error -- let's sort this out with all the checkbox/radio button fixes in #19138, and just capture the status quo for now.
I ran it 4 times locally, seems stable.
[new pixels view](https://github.com/cockpit-project/pixel-test-reference/compare/968cdc99848df96cd8806932c745c2dd220846bd..ccf0d43bb2e80cf9eb1ac3729e9304bcefd6a317)
=> test: Add pixel test for firewall "Add zone" dialog

src/cockpit/channel.py, src/cockpit/channels/packages.py, src/cockpit/internal_endpoints.py, test/pytest/mocktransport.py, test/pytest/test_bridge.py
Make a minor change to allow `Bridge()` to be instantiated without an active event loop, allowing some nice cleanups in the unit tests.
=> make Bridge init non-async

test/common/run-tests, test/common/testlib.py, test/verify/check-testlib
In our testlib we refer to these tests as destructive and non-destructive which makes reading the test code rather confusing as it talks about serial and parallel tests.
=> test: rename parallel/serial tests to (non)destructive tests

pkg/storaged/mdraid-details.jsx, test/common/storagelib.py, test/verify/check-storage-mdraid
mdadm uses a bitmap for arrays that are larger than 100GiB, and not having a bitmap is a warning.
=> storage: Tell people that big mdraids really should have a bitmap

src/ws/Makefile-ws.am
This was causing cockpit-tests to ship an empty directory. The tests don't even use that, but write the file into /etc. This gets in the way of Debian's remaining usrmerge migration, so just get rid of it.
https://bugs.debian.org/1043322
=> ws: Drop empty cockpit.service.d directory

pkg/storaged/client.js, pkg/storaged/crypto-keyslots.jsx, pkg/storaged/storage-controls.jsx, pkg/storaged/stratis-details.jsx, pkg/storaged/stratis-panel.jsx, pkg/storaged/stratis-utils.js, test/verify/check-storage-stratis
Demo: https://youtu.be/HFCzWqqRXHQ
----------------------
In addition to a passphrase (or instead of it), a Stratis pool can now use Tang server for encryption.
=> storage: Tang keyserver and passphrase management for Stratis

pkg/storaged/client.js, pkg/storaged/stratis-details.jsx, test/common/storagelib.py, test/verify/check-storage-stratis
This requires moving to "r5" of the D-Bus API.
------------------
Encrypted caches are a new feature in Stratis 3.5, and now you can use it also from Cockpit.
=> storage: Allow adding cache to encrypted pools

src/cockpit/channels/filesystem.py, test/pytest/mocktransport.py, test/pytest/test_bridge.py
It's not really conceptually clear that we should send 'ready' on channels that don't expect to receive data, so we haven't done it until now.
Unfortunately, `Channel.ready()` is also the place we thaw the receive side of the channel, so those channels were never being thawed.  The only place this matters for is flow control: pong messages will be received and queued, but never delivered, causing the channel to stall out after the window is filled for the first time.
Let's send 'ready' everywhere.  That fixes the flow control issue.  It's what the C bridge does as well.
Adjust our generic channel test case to make sure we always get the 'ready' message.  Also move our uses of the low-level `.send_open()` for the `fsread1` and `fslist1` channels to use `.check_open()` (which waits for the …
=> filesystem: send 'ready' on fsread1 and fslist1

test/common/testlib.py, test/verify/ruff.toml
As this effects `testlib` let's run one full test run, but not all distro's that seems a bit excessive.
=> Fix new auto enabled ruff rules

pkg/systemd/overview.scss
PF dropped pf-v5-global--FontFamily--redhat--monospace since https://github.com/patternfly/patternfly/commit/4ec21e34fc3
=> Remove unused css id #machine_id

test/verify/check-networkmanager-basic
Same as the pixel test above, every image refresh the ipv6 address changes and the new image has a different width.
For example: https://github.com/cockpit-project/bots/pull/5126
=> test: ignore mobile layout network interfaces

pkg/metrics/metrics.jsx
Fixes #19000 - Make CPU, RAM & Disk utilisation progress bars show as warning when >= 80%.
The screenshot shows the CPU on my machine whilst transcoding video.
=> 19000 metrics and colours

test/verify/check-storage-stratis
Trying to unlock with a wrong passphrase sometimes takes longer than the default 15s.
---
I've seen [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19223-20230823-021435-5329e45c-rhel-9-3-storage/log.html#53-2) twice in a row this morning.
=> test: Increase timeout for stratis pool unlocking

pkg/kdump/kdump-view.jsx, pkg/kdump/kdump.scss, pkg/lib/cockpit-components-dialog.jsx, test/verify/check-kdump
This adds message showing a location where user can verify whetever crash was successful:
- Local filesystem: "To verify whether the crash was successful check /var/crash location for kernel crash dump(vmcore)."
- SSH: "To verify whether the crash was successful check /var/crash location at skobyda@myserver.com for kernel crash dump(vmcore)"
- -NFS: "To verify whether the crash was successful check /var/crash location at myserver.com:/export/cores for kernel crash dump(vmcore)."
Closes https://issues.redhat.com/browse/RHELPLAN-125375
Closes https://bugzilla.redhat.com/show_bug.cgi?id=2097440
=> kdump: Show message in 'Test configuration' to verify the crash

src/bridge/cockpitdisksamples.c
Commit 4de70d60cb5 forgot to remove it. This fixes the "variable 'num_ops' set but not used" warning.
=> bridge: Drop unused num_ops in disk samples

.github/workflows/codeql.yml
This still has plenty of issues but I think it's time to start scanning
* Tons of false positives in test/ which are used from Python
* kdump needs some major re-factoring to make it more sane. I've fixed the state issues in a branch but I think it's more worthwhile to fix it in general
* Some interesting related issues which require investigation.
=> .github: scan JavaScript code with codeql

packit.yaml
Too late for today's releases, we'll have to do the F39 commit/build/bodhi manually, but for the next time..
=> packit: Add Fedora 39, drop Fedora 37

tools/debian/clean, tools/debian/source/options
Building the binary and running the tests creates tmp/wheel and .pytest_cache/, which are considered as unrepresentable source changes. Let dh_clean remove them before building a source package.
Moreover, running the unit tests changes the "dev@cockpit-project.org" in src/ssh/mock_rsa_key.pub to the local user@hostname. Our tests don't explicitly do that, this smells like some libssh bug/weirdness. Until this is investigated, just ignore the changes in that file for building a source package.
https://bugs.debian.org/1044095
=> tools: Fix building Debian source package after binary build

HACKING.md, src/cockpit/misc/print.py
Explain the COCKPIT_DEBUG environment variable.
=> HACKING: Add a section about Python bridge and debugging

test/common/run-tests
When a naughty appears in a different distribution mark it as failure with a reason that it is known somewhere else.
=> test: show a known naughty as a failure

pkg/lib/dialogs.jsx
Returns true if a dialog is currently active. This change fixes keyboard input in navigator ([PR)](https://github.com/KKoukiou/cockpit-navigator/pull/88)
=> Add isActive property in dialogs object

pkg/storaged/client.js, pkg/storaged/content-views.jsx, pkg/storaged/drives-panel.jsx, pkg/storaged/iscsi-panel.jsx, pkg/storaged/mdraid-details.jsx, pkg/storaged/mdraids-panel.jsx, pkg/storaged/nfs-details.jsx, pkg/storaged/others-panel.jsx, pkg/storaged/stratis-details.jsx, pkg/storaged/stratis-panel.jsx, pkg/storaged/things-panel.jsx, pkg/storaged/vdos-panel.jsx, pkg/storaged/vgroup-details.jsx, pkg/storaged/vgroups-panel.jsx
- Expose the content row producers, and generalize "is_partition" etc to "options" for the content row producers, so that we can add more overview specific tuning options later.
- Expose side panel row and action providers, and add "options" for later tuning.
- Expose top-level content actions, such as "Create logical volume"
This allows us to use those functions from new UI elements, and it is best to make them global as early as possible so that future changes to the actual code in those functions doesn't lead to constant merge conflicts while the new UI is slowly brewing.
=> storage: Make some functions global in preparation for UI redesign

pkg/storaged/client.js, pkg/storaged/lvol-tabs.jsx, pkg/storaged/storage-controls.jsx, pkg/storaged/stratis-details.jsx, pkg/storaged/warnings.jsx, test/verify/check-storage-stratis
Demo: https://youtu.be/IvwnqFjhMXw
--------------
Cockpit can now grow logical volumes that are used as block devices in a Stratis pool. Also, if a Stratis block device grows for any reason, Cockpit will notify you about this and can extend the pool to use all of it.
=> storage: Grow Stratis blockdevs

containers/ws/Dockerfile
37 will soon be EOL.
---
This can't be covered by our CI, as that runs offline. I locally built the container image:
make -f containers/Makefile.am srcdir=$(pwd) ws-container
then copied it to a FCOS VM:
podman save quay.io/cockpit/ws:latest | ssh c podman load -
started it in FCOS:
podman container runlabel INSTALL cockpit/ws
podman container runlabel RUN cockpit/ws
and get a working cockpit.
=> containers/ws: Move to Fedora 38

pkg/lib/patternfly/patternfly-5-overrides.scss
Workaround for https://github.com/patternfly/patternfly/issues/5865
Closes https://github.com/cockpit-project/cockpit-machines/issues/1188
PF's Dropdown is being hidden by a PF's Card
=> lib: Fix a dropdown being hidden by a card

pkg/storaged/storage-controls.jsx, pkg/storaged/storage.scss
So this partially contributes to #19241
How it looks without plain:
How it looked before:
----
I am not entirely sure why plain was working like that in light mode? but the dark mode was correct (no background/border).
Also the side effect of this change is now that it is using the proper width / slimmer profile as shown by patternfly docs.
=> storage: StorageBarMenu dropdown should not always be plain

test/README.md, test/verify/check-kdump, test/verify/check-system-info
Fedora 39 now has a default crashkernel= kernel option, so that
kdump.service can start by default. Now only old Fedoras are left, so
invert the condition to become simpler and eventually empty.
---
This blocks https://github.com/cockpit-project/bots/pull/5171 . I locally validated that TestKdump.testBasic works against fedora-39 with this fix, but as there are lots of other failures, I don't want to trigger a fedora-39 run here. I'll do that in the bots PR.
=> test: Invert "no crashkernel= by default" expectation in kdump test; fix testCPUSecurityMitigationsEnable on fedora-39

pkg/lib/cockpit-components-form-helper.jsx
As per patternfly guidelines [1], validation text (which is main use of FormHelper) should not have an icon
[1] https://www.patternfly.org/components/forms/form/design-guidelines/#errors-and-validation
=> lib: Don't show icon unless 'icon' prop is passed

test/common/testlib.py
The cause of this is unclear, but this keeps breaking random tests and thus causes unnecessary pain/retries. Until we investigate this bug, let's shut it up.
See issue #19235
=> test: Ignore "invalid non-UTF8 @data passed" message

test/common/storagelib.py
Doing that messes up the kernel's mount state, and eventually mounts the new /boot *on top of* the old /boot and /boot/efi. This results in /boot/efi not being umountable any more, and hanging forever during shutdown on waiting for boot-efi.mount to finish stopping.
---
This blocks https://github.com/cockpit-project/bots/pull/5171
=> test: Don't encrypt/move the EFI partition in encrypt_root

pkg/lib/table.css, pkg/storaged/crypto-panel.jsx, pkg/storaged/fsys-panel.jsx, pkg/storaged/nfs-panel.jsx
So in PF5 the row is already getting the proper clickable and added hover styles, the only override that seems to be cockpit specific is the hover color/background-color.
I wonder if the remaining change in `table.css` change should be inside `patternfly-5-overrides.scss` instead?
=> storage: Cleanup for table clickable rows

doc/man/cockpit-bridge.xml, src/cockpit/bridge.py, src/cockpit/packages.py, test/verify/check-connection
It was defined in argparse, but entirely ignored, so that it started the
protocol. Also add it to the manpage.
This also unbreaks the regular cockpit/ws container builds, as they use
--version to define the tag.
Add an integration test which exercises all non-protocol options.
Fixes #19233
----
See https://quay.io/repository/cockpit/ws?tab=tags , this stopped updating since we moved Fedora 38 to the pybridge.
=> pybridge: Implement cockpit-bridge --version; some small cleanups

pkg/lib/cockpit-components-modifications.jsx
Resolves #19057 .  Added support of clearTimeOut function to re-render the copy icon in case of switching tabs in selinux automation script.
=> selinux: Remove copied checkmark when switching SELinux modifications tab

test/verify/check-selinux
`semanage` needs a lot of memory, and with 768 MiB the VM often runs into low ram and kswapd rampage especially on RHEL 8. Increase to default RAM size to fix that.
The original reason for reducing the memory was the static "packing" of parallelized tests by run-tests, but since it introduced the concept of "cost" that isn't necessary any more.
---
This fixes [this common failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5160-20230828-082610-2aeb7781-centos-8-stream-pybridge-other-cockpit-project-cockpit/log.html#73-2)
=> test: Increase TestSELinux VM memory

pkg/apps/application-list.jsx, pkg/apps/application.scss
The refresh progress bar does not really reserve any space, I took a brief look at the PF4 version on my RPI so I am not sure if the expectation is just a plain progress bar, so let me know if it doesnt make any sense.
Looks like this:
Tried to avoid changing the other usage significantly.
Closes #19062
=> apps: Fix application progress bar

pkg/networkmanager/bond.jsx, pkg/networkmanager/bridge.jsx, pkg/networkmanager/dialogs-common.jsx, pkg/networkmanager/team.jsx, pkg/networkmanager/vlan.jsx, test/verify/check-networkmanager-bond, test/verify/check-networkmanager-bridge, test/verify/check-networkmanager-mac, test/verify/check-networkmanager-team, test/verify/check-networkmanager-vlan
Based on @garrett's suggestions [here](https://github.com/cockpit-project/cockpit/pull/19024#issuecomment-1621328633).
> Is this a create dialog? Then it should say "Create VPN", not "Save". In edit mode, it should say "Save", however.
> The title "WireGuard settings" should either be "Create WireGuard VPN" or "Edit WireGuard VPN", based on the mode of the modal.
And [here](https://github.com/cockpit-project/cockpit/pull/19024#issuecomment-1667738465).
> Can you add more than one WireGuard VPN? (It doesn't look like it. It's "WireGuard settings" here with a "Save" button. It's not settings though? Shouldn't it be "Add WireGuard VPN"? With an "Add" button?
This needed to be a separate PR as the code/issue is shared between the other interface Dialogs.
~For the time being, create dialogs …
=> network: distinguish create and edit dialogs

test/run
This scenario installs updates-testing updates before running the tests to offer a "nightly" scenario and to replace the fedora-testing image which is tested every X days.
Added `no-test` as it doesn't feel like it's required to test all images, just one run should be fine.
=> test: include an Fedora updates-testing scenario

pkg/networkmanager/ip-settings.jsx
changing the `value` attribute of React input elements to null changes it from controlled to uncontrolled, which leads to React logging errors in the browser console.
This fixes errors of the form:
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen...
Fixes these:
=> networking: don't pass null to input elements

test/common/link-patterns.json
Capturing VM's xml and logs was implemented in [1], now it's time to also include the in our link-patterns.
[1] https://github.com/cockpit-project/cockpit-machines/pull/1158
=> test: Add VM's XML and VM's log into link-patterns

tools/debian/rules
Similarly to commit 584cdfb6a0, remove the installed cockpit-beiboot from the temporary install tree for arch-indep builds. That file was added in commit fb673e0a7.
---
This made [all builds of release 300 fail](https://buildd.debian.org/status/package.php?p=cockpit) yesterday, like [this](https://buildd.debian.org/status/fetch.php?pkg=cockpit&arch=amd64&ver=300-1&stamp=1694026722&file=log):
```
dh_missing: warning: usr/lib/cockpit/cockpit-beiboot exists in debian/tmp but is not installed to anywhere 
dh_missing: error: missing files, aborting
```
Our CI does not do it that way, so won't detect this.
=> tools: Fix "only arch all" Debian build

pkg/apps/application-list.jsx, pkg/apps/manifest.json, test/common/packagelib.py, test/common/testlib.py, test/verify/check-apps
With only looking at aos-release's `ID` field, we are missing out a lot of derivatives, such as CentOS Stream, Rocky, or Debian-likes. Consider ID_LIKE as well to fix that.
E.g. on Ubuntu, `ID_LIKE` is "debian", on CentOS it's "rhel fedora", on Rocky Linux it's "rhel centos fedora".
Use that to clean up the manifest map, as Ubuntu and RHEL are now redundant.
---
Spotted in https://github.com/cockpit-project/cockpit/pull/19281#discussion_r1315723556
=> apps: Consider ID_LIKE for mapping AppStream data packages

test/common/testlib.py, test/verify/check-shell-multi-os
fcb73df1cb56 added this message back in 2019 but the specific error code that we receive from the Python bridge is now different, as we can see in new failures:
```
/base1/fonts/patternfly.woff: external channel failed: protocol-error
```
Instead of trying to figure out how to make the Python bridge return exactly the same error code in this situation, let's just expand the pattern.
=> test: Add another another expected restart message

.github/workflows/unit-tests-refresh.yml, .github/workflows/unit-tests.yml, Makefile.am, configure.ac, containers/flatpak/Makefile.am, containers/flatpak/prepare, containers/unit-tests/Dockerfile, pkg/Makefile.am, src/Makefile.am, src/bridge/Makefile.am, src/ws/Makefile-ws.am, test/verify/check-system-realms, tools/arch/PKGBUILD, tools/cockpit.spec, tools/debian/rules
Replace --enable-pybridge with --enable-old-bridge, and flip the logic. That way, it will slowly disappear as old distro releases become unsupported. This also means that builders from upstream now get the Python bridge by default.
Keep the unit tests running with the C bridge for the time being, to exercise it with multiple architectures/compilers/valgrind.
https://issues.redhat.com/browse/COCKPIT-1037
=> build: Make Python bridge the default

test/verify/check-storage-resize
UDisks2 now reads filesystem sizes from udev, which seems to sometimes need an extra trigger.
=> test: Explicitly trigger udev after resizing ext4

.github/workflows/nightly.yml
This tests Cockpit nightly with `updates-testing` enabled.
=> .github: add nightly testing scenario

.github/workflows/nightly.yml
See #19298 and individual commit messages. I'll trigger manual runs against this branch.
=> Fix nightly runs

test/common/testlib.py, test/verify/check-metrics, test/verify/check-system-info
Scrolling might trigger a tooltip (or popup) and thus we should wait for their animation to be over after scrolling.
This fixes the TestStorageUsed-testUsed-popover-medium flake in #19268 for me.
=> test: Wait for tooltips after scrolling stuff into view

tools/arch/PKGBUILD
Apparently the `wheel` group is not present any more in latest Arch's build environment, so the auto-detection now falls back to "root".
---
This fixes the image refresh in https://github.com/cockpit-project/bots/pull/5233 .
@jelly: I noticed that our upstream and the [downstream](https://gitlab.archlinux.org/archlinux/packaging/packages/cockpit/-/tree/main?ref_type=heads) packaging have diverted quite a bit. Most importantly, the [PAM file](https://gitlab.archlinux.org/archlinux/packaging/packages/cockpit/-/blob/main/cockpit.pam?ref_type=heads) is missing
```
auth       required     pam_listfile.so item=user sense=deny file=/etc/cockpit/disallowed-users onerr=succeed
```
But also PKGBUILD has quite a lot of differences. E.g. Arch split off cockpit-packagekit and cockpit-storaged, which …
=> tools: Explicitly set admin group on arch

test/common/testlib.py, test/verify/check-metrics
Previously, we were only waiting after switching to mobile, but the layout changes seem to be problematic in general for the metrics tests.
So let's just add a general mechanism for waiting a bit after a layout change and use it for those tests.
This will hopefully allow us to not skip "mobile" and "rtl" with the second pixel test.
=> test: Wait after layout change for some metrics pixels

test/common/testlib.py
See #18355
New stacktrace:
```
Exception ignored in: <coroutine object DBusChannel.setup_path_watch.<locals>.handler at 0x7f7d488612c0>
File "/usr/lib/python3.9/site-packages/cockpit/channels/dbus.py", line 435, in handler
self.send_message(notify=notify)
File "/usr/lib64/python3.9/asyncio/locks.py", line 20, in __aexit__
self.release()
File "/usr/lib64/python3.9/asyncio/locks.py", line 144, in release
self._wake_up_first()
File "/usr/lib64/python3.9/asyncio/locks.py", line 161, in _wake_up_first
fut.set_result(True)
File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
self._check_closed()
File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
raise RuntimeError('Event loop is closed')
RuntimeError: Event …
```
=> test: allow journal message to a known pybridge error

test/verify/check-metrics
The test previously assumed that running two CPU intense processes would always be scheduled on separate CPU cores. But this isn't actually the case: Linux switches back and forth between doing that, and scheduling them on the same core, probably trying to idle the second core for power saving.
So it happens that the "max" core CPU usage stays reliably > 90%. To accomodate both scheduling cases, reduce the total usage from 90% to 70% and adjust the checked limits accordingly.
----
Fixes https://cockpit-logs.us-east-1.linodeobjects.com/pull-19279-20230911-031641-bad736fd-fedora-38-firefox-other/log.html#176
=> test: Fix TestMultiCPU.testCPUUsage for different scheduling

tools/debian/cockpit-bridge.install, tools/debian/rules
By now we have enough faith in it that we can drop the special case. This only leaves the C bridge for RHEL/CentOS 8, which will be branched off and thus disappear in about half a year.
Invoking pytests on Ubuntu 22.04 requires a special case for the old pytest version unfortunately, but this will go away in ~ 9 months.
=> tools: Enable the Python bridge on stable Debian/Ubuntu

test/verify/check-networkmanager-bond
The pixel test fails very often on some unstable rendering noise of the help icon.
Fixes #19311
See the issue for example log URLs.
=> test: Ignore help icon in bond dialog

tools/cockpit.spec
Fedora packaging policy demands python3-devel [1]. RHEL 8 has multiple
Python versions available, and depending on the python3 binary can
possibly select the non-default one from a module (such as Python
3.11). Ensure that we build against 3.6 by requiring python3-devel
instead.
https://issues.redhat.com/browse/RHEL-2215
https://issues.redhat.com/browse/RHEL-2218
[1] https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_buildrequire_python3_devel
=> tools: BuildRequires: python3-devel

test/verify/check-connection, tools/arch/PKGBUILD, tools/arch/cockpit.install
Upstream split cockpit-storaged/cockpit-packagekit into a new package and has an alternative approach for disallowing root login.
=> tools: sync Arch Linux upstream packaging changes

pkg/networkmanager/dialogs-common.jsx, pkg/networkmanager/interfaces.js, pkg/networkmanager/network-interface.jsx, pkg/networkmanager/network-main.jsx, pkg/networkmanager/wireguard.jsx, pkg/networkmanager/wireguard.scss, test/run, test/verify/check-networkmanager-wireguard
TODO: 
Follow-ups:
The Networking page can now create and edit [WireGuard VPN](https://www.wireguard.com/) connections.
_Many thanks to [Subho Ghosh](https://github.com/subhoghoshX) for adding this feature as part of his [Google Summer of Code](https://summerofcode.withgoogle.com/) project! and thanks to [Gil Obradors](https://github.com/gil-obradors) for his initial work._
=> networking: Add support for WireGuard

test/ARCHITECTURE.md, test/README.md, test/run
I hope it's not to long :smile: 
A nicely rendered document can be viewed [here](https://github.com/jelly/cockpit/blob/test-architecture-doc/test/ARCHITECTURE.md)
=> test: add a document describing Cockpit's test Architecture

pkg/shell/superuser.jsx, test/verify/check-superuser
When closing the dialog via the cross icon also cancel the superuser proxy. Otherwise the switch to administrative access button will stay hidden.
Closes #19288
=> shell: handle closing dialog the same as cancel

pkg/lib/patternfly/patternfly-5-overrides.scss
Not sure if the right approach, but closes #19241
I am able to replicate this both in chromium and firefox based browsers, and it is not limited on networking only.
Gonna show just a few screenshots from dark mode:
Firefox Before:
Firefox After:
-----
Chrome Before:
Chrome After:
Light mode also works as expected:
Chrome After:
Firefox After:
=> lib: Workaround FormSelect background-color

pkg/apps/application-list.jsx, test/verify/check-apps
Commit 7bbf9168ac33 introduced a major bug: If the OS in os-release was
not found in the iteration, get_config() would return the whole map
instead of the default value. That crashed the page with
`TypeError: names.forEach is not a function`.
This is awkward to do correctly with .find(), especially due to
modifying `val` as a side effect; iterate over `os_list` the good old
`for` way instead.
This was hidden by the test's manifest override leaving
`appstream_config_packages` intact, so it was always taken from the real
underlying OS. Override it as well.
---
Broken out from PR #19281, as this is a release-blocker, and the former needs some more work.
=> apps: Fix reading AppStream metadata config

test/verify/check-networkmanager-other
Normally, deleting a device with "ip link del" will also cause the NetworkManager connections settings to disappear. But in the right circumstances, NetworkManager seems to bring the device back to live instead of dropping its settings. This would break the test on the next run in the same VM.
Avoid this by deleting the tun0 settings explicitly during test cleanup.
=> test: Better cleanup for TestNetworkingOther

pkg/systemd/overview-cards/realmd.jsx
This should fix the flake investigated in  #19294.
=> realmd: Don't initialize proxy twice during page load

Makefile.am, tools/cockpit.spec
The Python bridge is now default enabled in 14c07d70878621640c2d2f and this also removed cockpit_enable_python in favour of explicitly enabling the old bridge. As RHEL 8 ships the old bridge by default we need to toggle this for the pybridge scenario.
This needs a change in bots and then an image refresh most likely to get the pybridge scenario back on track for RHEL-8
https://github.com/cockpit-project/bots/pull/5256
With this spec change we get in bots
```
[jelle@toolbox rhel-8-revive-pybridge]$ cat tools/cockpit.spec  | rpmspec -D "rhel 8" -D 'version 0' -D 'enable_old_bridge 0' --buildrequires --query /dev/stdin | sed 's/.*/"&"/' | tr '\n' ' '
warning: Macro expanded in comment on line 28: %{version}.
warning: line 439: Possible unexpanded macro in: Requires: (selinux-policy >= …
```
=> Makefile.am: cockpit_enable_python was dropped

test/verify/check-connection
The test initially expects no loaded cockpit-wsinstance-https*.service instances. However, TestConnection.testHttpsInstanceDoS produces loads of failed instances, so if testHttpsInstanceDoS ran first on the same VM, testUnitLifecycle failed that initial condition.
Robustify testUnitLifecycle to reset all failed units initially. Also reset them at the end of testHttpsInstanceDoS to avoid littering.
=> test: Clean up failed units in TestConnection.testUnitLifecycle

test/common/storagelib.py, test/common/testlib.py
We did this already for content_tab_wait_in_info, but now all activity inside content tabs is retried. This should make the tests more robust when those tabs are closed unexpectedly.
=> test: More general retrying for Storage content tabs

src/cockpit/bridge.py, test/verify/check-connection
A Bridgeconfig does not serialise to JSON by default.
Closes: #19319
Alternatively we pass `json.dumps(cls=Config())`
=> cockpit: add to_json() method to BridgeConfig

pkg/metrics/metrics.jsx, test/verify/check-metrics
I just want to get a first pass on this, I am trying to abide by the NetworkManager, albeit I am not sure how expensive the full blown NetworkManagerModel is.
Also please disregard `rowWrapperIface` for now, I didn't bother to really fix, just stitched it together so it would still pass tests.
So I have a few questions that need addressing and I am willing to do the fixes afterward:
1) Is asking the networkmanager really necessary?
Even though some interfaces are unmanaged, I tried by hand and cockpit can indeed show some information related to them such as:
The only exception would be loopback, I guess?
Bit afraid to figure out what that disable toggle would attempt to do in this case.
2) Loopback should not get a link, right?
I believe the right choice here would be to move the check …
=> Metrics: Link to network interface

pkg/networkmanager/interfaces.js, pkg/networkmanager/network-interface.jsx, test/verify/check-metrics
The user can't normally even navigate to such a device, but it is
possible to construct a URL for them, of course. Specifically, the
Metrics page now links to "lo".
=> networking: Don't let the user manage loopback devices

src/cockpit/packages.py, src/cockpit/peer.py, src/cockpit/superuser.py, test/verify/check-superuser
ae5ce0a331f0 introduced a bug in the code that handled the case where the `any` superuser bridge was requested: previously, the code would set `self.current` to the name of the selected peer, but after the change, it would get set to `any` instead.  Fix that up by using the name of the peer as the value for `self.current`.
This allows us to simplify the condition for checking if the running bridge ought to be shut down when reloading packages.  The current logic reads that we should shutdown the current bridge "if there's any bridge which has our name" (which is very likely, in case nothing changed).  We need to change that to `not any`, but we can also write it a bit differently to make it even clearer what's going on.
Thanks to Jelle for the testcase.
=> cockpit.superuser: prevent 'any' from being set

test/common/testlib.py
Audit type=1405 is a "changes to booleans" event thus not a violation.
https://github.com/torvalds/linux/blob/master/include/uapi/linux/audit.h#L131C41-L131C60
=> test: add avc type=1405

pkg/networkmanager/firewall-client.js, test/verify/check-networkmanager-firewall
Trying to understand [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19334-20230915-080244-14eb9df1-fedora-38-networking/log.html#20), I can't get it locally.
=> Robustify/fix TestFirewall.testNetworkingPage, add firewall debug messages

package.json, pkg/lib/cockpit-po-plugin.js
This changes API a bit.
Also enable PO file validation. This gets tripped up by weblate's `#~` disabled items, which sometimes start with a `|`. Filter them out first.
---
I diffed the generated `dist/*/po*.js` between current main and this, they are identical. I also tested this with starter-kit, see https://github.com/cockpit-project/starter-kit/pull/705
=> package.json: Update to gettext-parser 7

packit.yaml, pkg/metrics/metrics.jsx, pkg/shell/superuser.jsx, pkg/storaged/content-views.jsx, pkg/storaged/stratis-details.jsx, pkg/systemd/overview-cards/realmd.jsx, test/common/packagelib.py, test/common/testlib.py, test/verify/check-client, test/verify/check-connection, test/verify/check-metrics, test/verify/check-networkmanager-other, test/verify/check-shell-multi-os, test/verify/check-storage-resize, test/verify/check-superuser, test/verify/check-system-info, test/verify/check-system-realms, test/verify/check-system-services, tools/cockpit.spec
We have a bunch of Python bridge regressions that we need to fix for RHEL 9.3.z. To get this started, I created a [rhel-9.3](https://github.com/cockpit-project/cockpit/tree/rhel-9.3) stable branch straight from the 300.1 tag, and cherry-picked an initial set of integration test fixes.
This also contains the BuildRequires fix (see https://issues.redhat.com/browse/RHEL-2215), and two safe bug fixes on the Storage and Metrics pages.
After this lands, I'll send some more intrusive changes, and two of the issues aren't even fixed yet (I also still need to file Jira tickets).
=> Backport test and some safe code fixes to rhel-9.3

pkg/playground/speed.html, pkg/playground/speed.js, src/cockpit/channel.py, src/cockpit/transports.py, test/pytest/test_bridge.py, test/verify/check-connection
This fixes a bridge crash
'SubprocessStreamChannel' object has no attribute '_last_ping'
when resume_writing() is called before the initial ping arrived.
Fixes #19323
----
That fixes the crash, but it's only half of the story. The new test case still fails with a too short file size:
```
File "/var/home/martin/upstream/cockpit/file-upload/test/verify/check-connection", line 831, in testFlowControlUpload
self.assertEqual(m.execute("stat -c %s /tmp/spawninput").strip(), 65536000)
AssertionError: '52494336' != 65536000
```
Then again, with the C bridge (rhel-8-9) it's even worse: it fails sometimes with
```
File "/var/home/martin/upstream/cockpit/file-upload/test/verify/check-connection", line 827, in testFlowControlUpload
b.wait_text_not("#speed", "")
``` …
=> Fix large file uploads through cockpit.spawn()

doc/guide/cockpit-session.xml
`cockpit.user` is a simple function that will return a Promise. It's not an event object, and trying to add an event listener to it fails:
Uncaught TypeError: cockpit.user.addEventListener is not a function
There's also no reason to do this: The user of the current session *never* changes. The only thing to wait for is for the value to become available, which is what the promise does.
Thanks to Ivan Devat for finding and reporting this.
=> doc: Drop wrong cockpit.user.onchanged()

test/browser/browser.sh, test/browser/main.fmf
Previous TF versions ignored the unavailable cockpit-tests test dependency, but now it (rightfully) fails on that. Install the package dynamically for non-RHEL 8 for now, until we drop support for RHEL 8 from our main branch.
Drop cockpit-tests for the storage plan, we don't need it there.
----
Sort out https://gitlab.com/redhat/centos-stream/rpms/cockpit/-/merge_requests/64 , tests were running successfully there against this branch.
=> fmf: Fix installation of cockpit-tests

src/client/cockpit-client, src/cockpit/beiboot.py, test/verify/check-client
The old cockpit-client-ssh was able to do that, but when we switched the
Client to cockpit-beiboot in commit 20937da2ed8, "host:port" connect
addresses broke.
=> pybridge: Add port parsing to cockpit-beiboot

test/common/testlib.py, test/verify/check-metrics, test/verify/check-storage-partitions
There is no "mobile" scenario anymore, we test the mobile layout via changing the layout during regular testing.
=> test: Remove obsolete skipMobile decorator

pkg/networkmanager/interfaces.js, pkg/networkmanager/wireguard.jsx, test/verify/check-networkmanager-wireguard
Though the original issue #19384 used wg-quick to configure wireguard, I was unable to reproduce the issue with it, unless I created a brand new connection which seems unnecessary as the tests already had a profile configured. Using `sed` to edit wg keyfile and reproduce should be equivalent.
Other wireguard properties `endpoint` and `listen-port` are either optional or have a default value, so the /network page shouldn't break if they're not set. Missing or invalid `public-key` is equivalent to no peer, so it shouldn't break /network page as well.
fixes #19384
=> networking: fix page crash when wg properties go missing

pkg/lib/cockpit-po-plugin.js, pkg/shell/index.html, src/cockpit/packages.py, test/pytest/test_packages.py
Split the po files into po.$lang.js and po.manifest.$lang.js so the shell can only serve the translated manifests. As previously the shell loaded it's own translations via globbing for the Python bridge we need to explicitly load the po.js file.
Closes #18224
=> shell: python: load translations via manifest.js

pkg/lib/cockpit-po-plugin.js
This regression was introduced by 89781bacb1027817b8e0cf07, where we used to check for `subdir` being undefined and correctly join paths. Subdirs are unset for plugins which leads to the out_dir being set to `/po.en.js`.
=> lib: handle `subdir` being an undefined

pkg/apps/application-list.jsx, test/verify/check-apps
Broken out from PR #19281, as this is an embarassing crash/regression.
=> apps: Fix crash with nonexisting /etc/os-release

.github/workflows/flatpak-test.yml, containers/flatpak/test/test-browser, containers/flatpak/test/test-browser-login-ssh.js, containers/flatpak/test/test-lib.js, selinux/HACKING.md, selinux/cockpit.te, src/cockpit/beiboot.py, src/cockpit/packages.py, test/common/testlib.py, test/verify/check-client
These are the relatively harmless parts from #19401, split out to get them out of the way.
=> beiboot preparation fixes

pkg/storaged/content-views.jsx, pkg/storaged/part-tab.jsx, pkg/storaged/resize.jsx, pkg/storaged/warnings.jsx, test/verify/check-storage-partitions
Demo: https://www.youtube.com/watch?v=rZ2ZExzkIto
Cockpit can now also resize partitions, including their content such as filesystems or LUKS containers.
=> storage: Partition resizing

pkg/lib/cockpit-components-modifications.jsx, test/verify/check-selinux
With the upcoming kdump Ansible integration we won't have a command to run as in the SELinux integration and we to promote Ansible usage.
=> lib: make Ansible role the first tab

pkg/networkmanager/ip-settings.jsx, test/verify/check-networkmanager-settings
Fixes https://github.com/cockpit-project/cockpit/issues/19211
=> networkmanager: Use TrashIcon instead of MinusIcon for field groups, and text-based add buttons instead of PlusIcon

test/verify/check-networkmanager-firewall
The output format of `--get-active-zones` zone names changed from `public` to `public (default)`. Adjust the name parsing to only consider the first word.
---
This fixes the [TestFirewall.testFirewallPage failure](https://artifacts.dev.testing-farm.io/c6d2ace9-688b-4f16-ad4b-e510162b3452/) that we started to see on Rawhide, and will soon see on the other releases.
=> test: Fix firewall-cmd output parsing for firewalld 2.0.1

src/cockpit/peer.py, src/cockpit/transports.py, test/pytest/test_peer.py, test/verify/check-client
A SubprocessTransport may die soon after starting without draining its
stdin. This can e.g. happen with "connection refused" and similar
networking errors when running `ssh`.
Trying to write to the process is then likely to trigger a
`BrokenPipeError`. This messes up proper error handling, as the error
usually gets read from the process'es err and exit code.
At this point "exited" signal didn't arrive yet, so ignore the
BrokenPipeError abort in the Peer, and defer error reporting to the
process exit handler.
---
Beiboot is broken [in an interesting way on ubuntu-2204](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19401-20230928-054506-d7f3fa3e-ubuntu-2204-other/log.html#161). It also happens on [fedora-39](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19401-20230928-085641- …
=> pybridge: Avoid BrokenPipeError crash of SubprocessTransport.write()

pkg/storaged/dialog.jsx, pkg/storaged/format-dialog.jsx, pkg/storaged/fsys-tab.jsx, pkg/storaged/stratis-details.jsx, pkg/storaged/utils.js, test/verify/check-storage-mounting
Demo: https://www.youtube.com/watch?v=tnf3Wl--Duw
=> storage: Don't allow mounting over other mounted filesystems

test/common/testlib.py
Until now, we were mapping values of characters to their browser's keycodes values [1]. This however is incorrect, since to get a value of character, we use Python's 'ord' function, which returns character's Unicode value.
In some cases, these values are different. For example, a value for newline key has keycode '13' in browser [1], but Python's 'ord' will give us value of '10' [2].
[1] https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
[2] https://python-reference.readthedocs.io/en/latest/docs/str/ASCII.html
=> test: Follow ASCII chart instead of browser's keycodes

pkg/kdump/kdump-view.jsx
Test crashing the kernel is shown as an option while it requires admin privileges to work.
Related: #19431
=> kdump: disable test configuration button for non-admin

pkg/lib/get-timesync-backend.py
Extend list of root directories to parse with new entry: '/lib'. On most systems this is just a symlink to '/usr/bin' and everything works as expected, but it may not be the case for custom distributions, i.e. ones created using Yocto.
Extending the list fixes problems with Time Management tab on such systems.
=> pkg/lib/get-timesync-backend.py: Add '/lib' to root directories list

test/verify/check-networkmanager-firewall
Commit 90abd41cd3 only fixed testFirewallPage(). But the counting fix also needs to be applied to testNetworkingPage().
----
This will fix the image refreshes of arch, fedora-39, and 1/3 of debian-testing.
=> test: Adjust TestFirewall.testNetworkingPage for firewalld 2.0.1

pkg/kdump/config-client.js, pkg/kdump/test-config-client.js, test/verify/check-kdump
When an administrator clears core_collector setting and we save a new configuration the core_collector value is set to `makedumpfile` without arguments. This is an invalid setting for kdump and not what the kdump.conf man page recommends as default setting.
The downside of hardcoding the default recommendation is that it may change over time, so this change includes a test to validate that when absent we re-set the default value.
=> kdump: always set kdump.conf defaults

.github/workflows/trigger-anaconda.yml
We want to make sure to not break Anaconda with changes which affect it, i.e. the bridge or the Storage page. As Anaconda's tests are "special" (require booting boot.iso, can't run in tmt/Testing Farm), we need to run them in Cockpit's CI.
Add a workflow which runs if the PR affects Anaconda (changes to the bridge or Storage page), polls the packit COPR until it has the current PR version available, and then test-triggers a "cockpit PR" scenario.
https://issues.redhat.com/browse/COCKPIT-1064
----
This got tested in #19459 with a demo commit that touches src/bridge, and got anaconda triggered. In *this* PR, anaconda should not be triggered, and the workflow succeed quickly with determining "not affected".
=> workflows: Trigger anaconda test on bridge/storaged changes

pkg/apps/application-list.jsx, pkg/lib/packagekit.js, test/verify/check-apps
Fixes #18454
Empty state:
Alert with already installed applications:
=> apps: Warn if appstream data package is missing

test/pytest/test_peer.py
The static `time.sleep(0.1)` was racy: On slow architectures like Debian mips [1] it repeatedly fails, and it even sometimes fails on GitHub actions.
Keep writing until the transport closes, so that we are guaranteed to eventually run into a BrokenPipeError.
Fixes #19469
[1] https://buildd.debian.org/status/logs.php?pkg=cockpit&ver=302-1&arch=mips64el
------
Failures on GitHub: [example 1](https://github.com/cockpit-project/cockpit/actions/runs/6495367925/job/17640184094?pr=19281), [example 2](https://github.com/cockpit-project/cockpit/actions/runs/6479245087/job/17592403347?pr=19459#step:5:223)
=> test: Fix pytest race in test_spawn_broken_pipe()

pkg/networkmanager/ip-settings.jsx, pkg/networkmanager/network-interface.jsx, test/verify/check-networkmanager-basic, test/verify/check-networkmanager-settings
=> Disable unsupported IPv4/IPv6 methods for wireguard

pkg/storaged/crypto-keyslots.jsx, pkg/storaged/lvol-tabs.jsx
Skip the check whether the resize has failed because of a wrong passphrase; this will never be the case for logical volumes without a block device.
Also, disable the "Grow" button when there is not enough space, just like for regular logical volumes.
=> storage: Robustify thin pool resizing

pkg/shell/superuser.jsx
During superuser initialization it can happen that `superuser_proxy.Bridges` does not exist yet. This made the shell crash with
TypeError: Cannot read properties of undefined (reading 'length')
---
Spotted in https://github.com/cockpit-project/cockpit-ostree/pull/437 , see that for details. There may be an underlying bug/race condition in the bridge here, but it doesn't hurt to make the shell code robust against that. I tested cockpit-ostree against that fix 10 times (it previously crashed after two or three), and it seems stable now.
=> shell: Fix crash on uninitialized superuser proxy Bridges

doc/guide/Makefile-guide.am
This silences a grep warning about a stray \ before ".
Silences:
```
[jelle@t14s][~/projects/cockpit/main]%make check-guide
if grep -n -r 'name=\"id' doc/guide/html >&2; then \
echo "Unexpected generated id in the documentation" >&2; \
exit 1; \
fi
grep: warning: stray \ before "
```
=> doc: don't escape " when not required

test/common/testlib.py
`timeout()` was incorrectly typed as a string while it's an int.
=> testlib: fix some of our testlib typing

test/common/netlib.py, test/common/packagelib.py, test/common/storagelib.py, test/verify/check-packagekit
ruff 0.1 rightfully starts to complain about these. Done with `ruff check --fix`.
---
This "spontaneously" broke main, the tox test now [fails on this](https://github.com/martinpitt/cockpit/actions/runs/6543807297/job/17769038320?pr=19#step:5:18).
=> test: Replace .format() with f-strings

pkg/lib/cockpit-components-modifications.jsx, pkg/packagekit/updates.jsx, pkg/shell/hosts.jsx, pkg/users/accounts-list.js, test/common/testlib.py
First wave of fixes after #19053
----
=> React warning fixes

test/common/testlib.py
=> test: Drop obsolete null props ignore

pkg/lib/serverTime.js, pkg/networkmanager/dialogs-common.jsx, pkg/networkmanager/wireguard.jsx, pkg/packagekit/kpatch.jsx, pkg/shell/hosts_dialog.jsx, pkg/sosreport/sosreport.jsx, pkg/users/account-logs-panel.jsx, pkg/users/users.js, test/common/chromium-cdp-driver.js, test/common/firefox-cdp-driver.js, test/common/packagelib.py, test/common/testlib.py, test/verify/check-sosreport
This gets rid of two more error ignores, and also addresses failures like [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19507-20231019-203931-1115978c-centos-8-stream-pybridge-other/log.html) and [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19507-20231019-203931-1115978c-rhel-8-9-distropkg-expensive/log.html) to not just show an useless empty "> error: ".
=> More console.error() cleanup

configure.ac, src/bridge/Makefile.am, src/common/cockpitunixsignal.c, src/session/session-utils.c, src/session/session-utils.h, src/tls/Makefile-tls.am, src/tls/cockpit-certificate-ensure.c, src/tls/connection.c, src/tls/socket-io.c
Fix a couple of things to allow building on musl based systems:
- musl doesn't define `SIGCLD` but only `SIGCHLD` => ifdef it as done for other signals
- `src/session/session-utils.c` uses `_PATH_LASTLOG` but doesn't include `<paths.h>` where it's defined (on musl and glibc)
- musl doesn't provide `fts_{open,read,close}` itself and needs to link against an external fts library 
- musl doesn't provide `argp_{parse,error}` itself and needs to link against an external argp library
- the last 4 patches just fix warnings about including `<xyz.h>` instead of `<sys/xyz.h>` so the build on musl systems is warning-free
=> Allow building on systems using musl C library

pkg/lib/patternfly/_fonts.scss
This fixes a discussed issue[1] where Patternfly's default monospace font gets incorrectly calculated as Red Hat Mono Light, which as 2 degrees thinner/lighter than medium.
Updating our overrides weight values to the ones used by Red Hat Mono[2] pagckage should fix the issue,
[1] https://github.com/cockpit-project/cockpit-machines/pull/1178#issuecomment-1686225290
[2] https://fontsource.org/fonts/red-hat-mono
=> lib: Update RedHatMono weight properties

test/verify/check-system-services
Stop pretending that we can accurately predict the next `OnBoot` timer in TestServices.testTimerSession. It is very much *not* "now + 200 minutes", but "200 minutes after the current VM booted" (which may be long-running in Testing Farm or our CI machinery). As this is a neverending race condition in evenings, and we don't test the accuracy of systemd here, relax the check to just ensure that it happens today or tomorrow.
---
Fixes flakes like [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19518-20231023-202301-3eac2136-fedora-38-other/log.html#144-2) or [this](https://artifacts.dev.testing-farm.io/29ff6859-a09d-458e-9dc2-3d5c1075b8f6/)
=> test: Relax boot timer check in TestServices.testTimerSession

pkg/kdump/kdump-view.jsx, pkg/lib/cockpit-components-inline-notification.jsx, pkg/lib/cockpit-components-table.jsx, test/common/storagelib.py, test/verify/check-kdump, test/verify/check-shell-keys, test/verify/check-storage-mdraid, test/verify/check-storage-mounting, test/verify/check-storage-msdos, test/verify/check-storage-partitions, test/verify/check-storage-used, test/verify/check-system-info, test/verify/check-system-services, test/verify/check-users
`<Tr>` always needs to be wrapped into a `<Tbody>`.
Clean up the unnecessary special cases and handle them uniformly.
Adjust the tests to fix the selectors, they previously relied on the
buggy behaviour.
----
Split out from PR #19509, this is already a very intrusive fix which should land separately.
=> lib: Fix ListingTable nesting for non-expandable rows

pkg/storaged/resize.jsx
This is always the right thing to do, since Cockpit will first resize the block device (which is a logical volume or partition) and then resize the content to match.  This will cover the case where the block device resizing ended up with something different from what we asked for.
=> storage: Always resize filesystems and LUKS to the maximum possible

test/verify/check-storage-stratis
Also handle the case where the `--help` command fails, which is happening on RHEL 8 with stratis v2.
That was missing from commit 118d89a84a.
---
Fixes https://cockpit-logs.us-east-1.linodeobjects.com/pull-19527-20231025-171100-5b8a565c-fedora-38-storage/log.html#65-2
=> test: Define stop_type_opt in TestStorageStratisNBDE

pkg/storaged/crypto-keyslots.jsx, pkg/storaged/dialog.jsx, test/common/testlib.py, test/verify/check-storage-luks, test/verify/check-storage-lvm2, test/verify/check-storage-used
We have the following cases  in main:
[storage](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19509-20231023-195002-28ebf951-fedora-38-devel-storage/log.html#18):
expensive/networking already got fixed in #19520:
/other is okay.
Builds on top of:
=> Fix DOM nesting on the Storage page dialogs, enable DOM nesting errors

test/verify/check-kdump
https://bodhi.fedoraproject.org/updates/FEDORA-2023-93fab3be92 disables the kdump/crashkernel configuration by default, so we need to go back to explicitly enabling it on Fedora 39 as well.
Unify this process on all Fedora versions, and use `kdumpctl` instead of messing around with `grubby`.
---
This blocks https://github.com/cockpit-project/bots/pull/5442 . I'm triggering an extra fedora-39/expensive@bots#5442 test run against that image. This PR needs to land in lockstep with the image refresh.
=> test: Enable kdump on Fedora 39

src/cockpit/packages.py, test/pytest/test_packages.py
Make several fixes to our handling of the `Accept-Language:` header:
- we used to crash if `q=` contained invalid values due to an unchecked cast with `float()`.  Catch that error and ignore the entry in that case.
- our handling of English was incorrect.  We would look for and fail to find po.en.js, and move on to the next item in the list.  That means if the user listed English first, followed by another language which we did support, they'd see Cockpit in that other language, which is unexpected.  This is a regression introduced by f4be9066c9.  Now we drop all items that sort after English.
- our handling of fallbacks (ie: 'de' from 'de-de') was incorrect. RFC4647 §3.4 says that a "Lookup" should consider items in the order they're found, stripping each item down to its base form, …
=> packages: fix up parse_accept_language()

pkg/storaged/dialog.jsx, test/verify/check-storage-partitions
Instead of always putting zero at the far left.
The previous code was written for a older version of the slider that could be restricted, and would not allow the user to slide below the minimum. Patternfly sliders can not be restricted in this way and will allow the user to slide the knob into every position. Thus, we need to make the far left the minimum to avoid confusion.
=> storage: Put the minimum of a slider at the far left

test/README.md, test/verify/check-connection, test/verify/check-metrics, test/verify/check-system-info, test/verify/check-system-services
This prepares our tests for moving to rhel-8-10.
=> test: Generalize RHEL 8 special cases

pkg/lib/cockpit-components-password.jsx
This isn't documented anywhere on https://www.patternfly.org/components/icon/, no other instance uses it, and React complains about it:
> React does not recognize the `noVerticalAlig` prop on a DOM element.
We don't cover that bit in Cockpit's tests, but cockpit-machines does.
=> lib: Drop unknown noVerticalAlign property from HelpIcon

test/static-code, tools/webpack-make.js
We want to lint all our JavaScript code, this would trip over tools/webpack-make.js as it's a shell script. Ignorning it still gives an eslint warning so this has to be converted to a proper JavaScript file.
=> test: apply eslint to .js files as well

test/run
It does not exist any more in Fedora 39.
Fixes #19539
=> test: Drop updates-testing-modular repo

test/run
In Fedora-39 the dnf weak dependencies behaviour changed to install them by default which leads to podman's tests having
packagekit/networkmanager and storaged installed. This is unwanted so explicitly disable it.
=> test: don't install weak dependencies for updatest-testing scenario

test/browser/browser.sh
TF runs add the Fedora tag repository with `priority=9`. This breaks
upstream reverse dependency tests, as that repository will then win over
our "main builds" COPR and thus run tests against mismatching
cockpit-* rpms.
Counter the hack by dropping the tag repo priority and
upgrading all cockpit packages.
-----
This is similar to https://github.com/cockpit-project/cockpit-podman/commit/5ab52df9dd43461eae90aa7103fee7513809cf1e . This should hopefully improve/fix https://github.com/fedora-selinux/selinux-policy/pull/1870 or at least make it easier to investigate.
=> fmf: Hack around Testing Farm's tag-repository priority

pkg/lib/cockpit-components-password.jsx, pkg/lib/cockpit-components-password.scss, test/verify/check-users
- Adds show/hide feature
- Adds a minimum to a progress bar
- Changes width of a progress bar
- Shows message indicating the strength of the password
Fixes https://github.com/cockpit-project/cockpit/issues/19199
[Screencast from 2023-08-22 14-30-21.webm](https://github.com/cockpit-project/cockpit/assets/42733240/231f89ec-04b4-474e-adb1-95b405f5e778)
=> lib: Improve password fields

test/browser/browser.sh
Commit fb4faa31c5 was not sufficient: The problem wasn't the tag repository, but that current Fedora rawhide has a 303-2 rebuild of cockpit which is formally newer than our 303-1.<git stamp> revisions from our main-builds COPR.
If the env has a main-builds COPR (for reverse dependency tests), we always want to install the latest version from that. So give it the highest priority (uninutitively, lower priority wins), and use `distro-sync` to up- or downgrade the packages as necessary.
----
This can be seen in https://github.com/fedora-selinux/selinux-policy/pull/1913 . Yesterday's fix helped for F39, but [rawhide](https://artifacts.dev.testing-farm.io/5035c7e8-507d-40fe-8a79-648bb2c1473d) still installed the wrong version (303-2). I tested this on a reserved TF machine and also in a …
=> fmf: Fix prioritization of our main-builds COPR

test/verify/check-storage-stratis
The `--capture-key`, despite its documentation, is very insistent on
reading the password from the tty. In stratis-cli 3.6.0 it also changed
behaviour to expect the password twice. Move to the `--capture-key`
option which behaves as intended.
As this is non-trivial, and could change again in the future, factor it
into a helper function.
See https://bugzilla.redhat.com/show_bug.cgi?id=2246923
---
Triggering an extra run against updates-testing to cover both "old" and "new" case.
=> test: Use `stratis key set --keyfile-path`

test/browser/browser.sh
Commit 7ab102a5512e inexplicably slipped in a `:` which is not actually part of the downloaded file name. This breaks the globbing.
----
See most recent failure in https://github.com/fedora-selinux/selinux-policy/pull/1913 . I can't say anything else than "sorry!" and "no idea".. I did test the commands in a container, not sure where it went wrong.
/me draws a penalty card ♣️
=> fmf: Fix COPR yum repo globbing

pyproject.toml, src/client/cockpit-client, test/static-code, tools/build-debian-copyright
This covers e.g. src/client/cockpit-client or tools/urls-check, and also some helpers in pkg, which are not executable files, but have a shebang.
https://issues.redhat.com/browse/COCKPIT-1038
=> test: Run mypy on Python scripts

test/browser/browser.sh, test/verify/check-system-info
These plans are not meant to have cockpit-packagekit installed. That isn't in the test dependency list, but dnf installs "missing" weak dependencies on upgrades by default, which is undesired: The packagekit page gets preloaded and thus influences the test outcome, particularly when it is an old version (as happens during downstream gating).
So remove the package again if it got installed for plans other than "optional" (which is the one that actually tests packagekit).
Fixes https://gitlab.com/redhat/centos-stream/rpms/cockpit/-/merge_requests/68
---
See the link, this breaks the downstream release. I ran the tests against this branch to confirm that it fixes it.
This is essentially the same approach as in e.g. https://github.com/cockpit-project/cockpit-machines/commit/430b819a042452d881b …
=> fmf: Uninstall cockpit-packagekit for basic and network plans

pkg/packagekit/updates.jsx, test/common/testlib.py, test/verify/check-storage-stratis
First commit: Fixes #19519
Second commit: Fixes [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5491-20231102-225811-c7f9961e-fedora-39-firefox-expensive-cockpit-project-cockpit/log.html#62) / [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19560-20231102-215908-c4080709-fedora-39-firefox-expensive/log.html#62) unexpected message
Third commit: Replace https://github.com/cockpit-project/bots/issues/5469 . See https://bugzilla.redhat.com/show_bug.cgi?id=2246920 for details. The more important part of the test comes afterwards, and it covers a much more serious regression in stratis 3.6.0 which was fixed in 3.6.1. That will work in updates-testing. Not sure if 3.6.0 is on any image right now, tests will tell -- if so, I'll have to add another temporary naughty.
=> Address failures/flakes of the day

test/verify/check-storage-stratis
If TestStorageStratis.testBasic failed at a point when stratis filesystems were mounted, the `pool stop` and `pool destroy` commands would both fail, with "low-level ioctl error due to nix error" [sic] and "filesystems remaining on pool" respectively. This also prevented the loop devices from being cleaned up.
This broke the subsequent tests very hard, so that retries and testCLI would all fail.
---
Cleans up [this mess](https://artifacts.dev.testing-farm.io/692e36ad-9682-43de-a9f8-ef745752cec7/). I have some trouble with reproducing the initial failure, but the effect can be simulated easily:
```diff
--- test/verify/check-storage-stratis
+++ test/verify/check-storage-stratis
@@ -267,6 +267,7 @@ class TestStorageStratis(storagelib.StorageCase): …
```
=> test: Properly clean up after stratis test failures

test/common/storagelib.py
Making a (virtual) disk suddenly disappear into thin air sometimes trips up the Storage page's usage graphs, and PCP complains about
direct: instance name lookup failed: disk.dev.write_bytes.3: Unknown or illegal instance identifier
This is expected, ignore these errors.
Fixes #19568
=> test: Ignore PCP name lookup failure after disk removal

test/verify/check-storage-used
It is not clear what exactly keeps /dev/sda1 busy when the kernel tries to read the new partition table. It can't be the artificial processes and services started by the test itself since unmounting and locking have already succeeded at that point.
This bug happens only in quite specific conditions, and can't be expected to ever get fixed. So let's do what every user would do as well: Retry the dialog.
=> test: Retry after UDisks2 timeout in TestStorageUsed.testUsed

test/pytest/test_peer.py
On old Python versions, we can get the process-exited callback from the child watcher at the time of registration, without a return to the mainloop.  That means that for very fast-exiting processes, we might never get a chance to write to them to observe a EPIPE error.
Add a synchronization point so that we can prevent the process from exiting until after we've finished spawning it (and registering the watch).
Closes #19586
=> test: fix more test_spawn_broken_pipe races

test/common/chromium-cdp-driver.js, test/common/firefox-cdp-driver.js, test/common/testlib.py
Commit 8284618023 dropped all explicit "wait for page load" calls (fka. `expect_load()`) in favor of allowing page loads during wait commands. This is better in almost all cases, but it created a race condition on the login page in tests which logged out and back in. In particular, this can happen:
1. Test calls `Browser.logout()`.
2. That destroys a lot of execution contexts from the session, and creates a new one for the login page. It waits until the `#login` field becomes visible.
3. Test starts a new session by calling `Browser.open()`  usually via `Browser.login_and_go()`. This results in a `Page.navigate()` CDP call. Sometimes this takes a while.
4. `Browser.try_login()` fills in the login form. In *most cases*, the `wait: ph_is_present("#login")` command runs into the page load …
=> test: Wait for a page load in Browser.open()

pkg/storaged/content-views.jsx, pkg/storaged/dialog.jsx, pkg/storaged/format-dialog.jsx, pkg/storaged/fsys-tab.jsx, pkg/storaged/mdraid-details.jsx, pkg/storaged/resize.jsx, pkg/storaged/stratis-details.jsx, pkg/storaged/vdo-details.jsx, pkg/storaged/vgroup-details.jsx, test/common/storagelib.py, test/verify/check-storage-used
We want the user to cancel and start over.
=> storage: Disable "Apply" in Teardown dialogs after error

test/verify/check-system-services
In our CI the testLogs sometimes does not get a `START` and then fails. From the failed log it looks like this is due to journal being rotated. The user test case already sleeps to let journalctl settle so now we unify this approach.
Nov 08 13:13:09 ubuntu systemd[1]: Started test.service - Test Service.
Nov 08 13:13:09 ubuntu test-service[2427]: START
Nov 08 13:13:09 ubuntu systemd-journald[271]: Received client request to rotate journal.
Nov 08 13:19:51 ubuntu systemd-journald[271]: Received client request to rotate journal.
Nov 08 13:19:52 ubuntu test-service[2480]: START
Nov 08 13:19:57 ubuntu test-service[2480]: WORKING
=> test: wait for journal to rotate in testLogs

pkg/lib/cockpit-components-password.jsx
The tests type so fast that we end up running enough pwscore processes
in parallel that we run out of file descriptors.
=> lib: Debounce password quality checking during typing

src/cockpit/beiboot.py, src/cockpit/polkit.py, src/cockpit/remote.py, src/cockpit/superuser.py, test/pytest/test_beiboot.py
This has some breaking API changes, so make adjustments as necessary.
=> vendor: update to the latest version of ferny

test/verify/check-sosreport
It is not known if this fixes this [flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19591-20231108-145704-9e140ba1-fedora-38-other/log.html) as I couldn't reproduce that in CI or locally.
=> TestSoS: use testlib helper for privilege escalation

test/common/git-utils.sh
This prevents test failures on transient issues like
> fatal: unable to access 'https://github.com/cockpit-project/bots/':
> Failed to connect to github.com port 443 after 129563 ms:
> Couldn't connect to server
---
[example failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5529-20231109-225250-c6b08028-ubuntu-stable-networking-cockpit-project-cockpit/log.html)
Tested failure case with `GITHUB_BASE=foo/bar test/common/make-bots`.
=> test: Retry `git fetch` in git-utils.sh

pkg/lib/dialogs.jsx, test/verify/check-system-info
With human user/browser interaction there can only ever be one Modal dialog at a time. However, our tests/CDP driver does not have that restriction, tests can happily click on main page buttons while a dialog is open.
This can lead to situations where a test opens a dialog, and then opens a second one (which will overwrite `WithDialogs.Dialog.dialog` with the new component) without waiting for the first one to close. Then when the first dialog handler finally calls `.close()`, it will unexpectedly close the *second* dialog instead.
These races are a pain to debug [1]. Make them obvious with an error message which shows both the old and the new dialog element. As our tests now fail on console.errors(), that will detect/prevent similar race conditions in our tests.
[1] …
=> lib: Add error message when showing multiple Dialogs

pkg/lib/cockpit-components-file-autocomplete.jsx
In podman we want to validate if the hostPath is correct, as this component returns an empty string on error and also as default state meaning we can't determine easily from an application.
This should not break our API.
=> lib: provide an optional error callback for validation

test/verify/check-superuser
This fixed a security issue where a username could contain a path separator so now it uses an uid instead.
=> test: sudo stores an uid instead of a username since 1.9.15

test/verify/check-superuser
Use restore_dir instead of restoring four different files.
=> test: simplify restoring /var/lib/sudo/lectured

test/common/testlib.py
Tests like TestStorageUsed.testTeardownRetry run processes that keep a
scsi_debug block device mount busy. If they fail on some assertion in
the middle, the generic storage cleanup (umount, rmmod scsi_debug)
fails, and the following tests get broken. Add an `fuser` kill loop to
prevent that.
Also show all stdout output from these commands. We don't need it
returned in the code, it's more useful for developers in the test
output.
----
Fixes [this failure](https://artifacts.dev.testing-farm.io/42f44dfe-807e-4534-a817-dc5bb843e245/) from https://github.com/storaged-project/udisks/pull/1212 . I validated this with adding an `assert False` in the middle of `TestStorageUsed.testTeardownRetry` and ensuring that the test can be run multiple times.
=> test: Kill processes that keep scsi_debug mounts busy

test/verify/check-system-info
This test barely makes it within the default 10 minutes timeout. From what I see most of the time is spent by waiting for multiple reboots of the machine.
Locally this took almost 7 minutes to run so for CI we can bump this timeout to 20 minutes.
=> tests: increase timeout on testCPUSecurityMitigationsEnable

test/verify/check-metrics, test/verify/check-packagekit, test/verify/check-system-realms
This needs to go in lockstep with https://github.com/cockpit-project/bots/pull/4885 . There's lots of red here for the changes which don't work on main (sorry, some are incompatible), I triggered them on `@bots#4885`.
=> Adjust tests for services image refresh

pkg/lib/dialogs.jsx
useState() setters are async. c-podman and navigator call `Dialogs.close(); Dialogs.show(...)` in direct succession. In that case, Dialogs.show() does not yet see the updated `null` value for `dialog` and logs the error, which fails the test.
To avoid that, use a ref for "is the dialog open", which is synchronous.
----
Spotted in https://github.com/cockpit-project/cockpit-navigator/pull/156 and https://github.com/cockpit-project/cockpit-podman/pull/1484 .
=> lib: Fix race condition in "double dialog" error check

test/verify/check-system-realms
In most cases this is fast, but quite often Samba takes annoyingly long to answer. Make the timeout consistent and enforce this with helper functions.
----
Since yesterday's services image update, this test and related ones now [flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19611-20231115-213214-175ae070-fedora-39-firefox-networking/log.html#34) [annoyingly often](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=3&repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-system-realms+TestAD.testClientCertAuthentication) :+1:
=> test: Factorize and fix timeout for contacting domain

.github/workflows/trigger-anaconda.yml, test/common/testlib.py
https://github.com/cockpit-project/bots/pull/5569 changed the allowlist from a GitHub team to a hardcoded Python list, so we don't need the cockpituous token privilege with its `read:org` any more.
---
I also piggy-backed a fix for [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19625-20231119-093440-3a5a8a8f-rhel-8-10-distropkg-other/log.html#58)
=> workflows: Drop COCKPITUOUS_TOKEN from trigger-anaconda.yml, update Anaconda trigger for -webui split

pkg/Makefile.am, tools/cockpit.spec
The most recent PCP Fedora rawhide update [1] stopped building pcp on ix86 for Fedora ≥ 40 and RHEL ≥ 10. Follow suit and disable building the PCP bridge and the cockpit-package there.
[1] https://bodhi.fedoraproject.org/updates/FEDORA-2023-cf7eccd442
[2] https://src.fedoraproject.org/rpms/pcp/c/fc70568e935f8f4c88937cbe8fc17db9995ae7d5?branch=rawhide
---
Failed build example: https://dashboard.packit.dev/results/copr-builds/1163610
=> tools: Drop cockpit-pcp on ix86 on recent Fedora/RHEL

pkg/kdump/kdump-view.jsx
This is hardcoded over three times in the Javascript code.
=> kdump: use a constant for the default crash location

src/cockpit/beiboot.py, src/cockpit/bridge.py, src/cockpit/channel.py, src/cockpit/channels/dbus.py, src/cockpit/channels/filesystem.py, src/cockpit/channels/http.py, src/cockpit/channels/metrics.py, src/cockpit/channels/packages.py, src/cockpit/jsonutil.py, src/cockpit/peer.py, src/cockpit/protocol.py, src/cockpit/remote.py, src/cockpit/router.py, src/cockpit/superuser.py, test/pytest/test_peer.py
Remove the general purpose mechanism for sending JSON-formatted messages from the protocol level, leaving only the mechanism for sending control messages.  Non-control JSON-formatted messages (such as those used for D-Bus replies) are now handled at the channel level and treated as normal data, subject to flow control.  This removes one of the main interaction points between endpoints and the router.
Add a pair of functions to jsonutil which define the exact way in which we intend to handle keyword args when building control messages.  We make a clear distinction between data which is meant to be handled "verbatim" and data which is meant to be subject to processing rules
(our '_' to '-' replacements, etc).
Start using the new jsonutil functions for all control message handling. That …
=> bridge: Improve handling of control messages

test/verify/check-static-login
The type and class are separate fields with systemd ≥ 255, not part of `Service:` any more. Adjust the check to get along with both formats.
---
Fixes the [rawhide failure](https://artifacts.dev.testing-farm.io/c51b7e96-c58d-4006-8efb-48660ddc6b74/) that started to happen yesterday.
=> test: Adjust testClientCertAuthentication to changed loginctl 255 output format

pkg/packagekit/autoupdates.jsx, pkg/packagekit/kpatch.jsx, test/verify/check-packagekit
dnf 4.15 introduced a `reboot` option for automatic updates at last
[1][2]. This is available in all current Fedoras and RHEL 9.3+, but not
yet in RHEL 8. On systems which support it (i.e. which have a `reboot=`
option in automatic.conf), set that to "when-needed" instead of the
unit drop-in hack. Remove the latter to clean up on upgrades; that will
only have an effect if the admin disables and re-enables automatic
updates, but that's better than nothing.
Fixes https://issues.redhat.com/browse/RHEL-16392
[1] https://github.com/rpm-software-management/dnf/blob/master/doc/automatic.rst#commands-section
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1491190
----
I tested this interactively on a real F39 machine with lots of pending updates (including a kernel), waited for the timer to …
=> packagekit: Use dnf-automatic reboot option if available

test/verify/check-packagekit
Grab the candlepin server's CA and install it both into rhsm and the general system (for `curl`). This tests subscription-manager more realistically, without having to yell "insecure" all the time.
Also simplify and robustify the waiting loop. Previously, the loop could just end with 200 failures, and the test would go on. Now it will timeout. Also lower the 6 minute timeout to the default 2 minute -- starting up candlepin only takes a few seconds on our current image.
---
I started to look at this while investigating https://github.com/cockpit-project/bots/issues/5551 . Turns out it's orthogonal to that, but this is a nice improvement anyway.
=> test: Use proper TLS CA for subscription-manager

test/common/testlib.py, test/verify/check-shell-host-switching, test/verify/check-shell-multi-machine
This was copy'd twice in Cockpit tests and will also come in useful in the cockpit-machines multi machine tests.
=> test: re-use admin ssh key setup across machines

src/cockpit/bridge.py
Since we explicitly track endpoints and send .do_close() to all of them on EOF, we no longer need this hack.
=> bridge: remove a hack to cancel prompts on EOF

test/verify/check-metrics
Later Grafana versions [1] fixed the page crash on "Failed to fetch plugins from catalog", and just log it to the console now. That will make the "wait for false" loop timeout and eventually fail. If that happens, then all is actually well.
[1] https://github.com/cockpit-project/bots/pull/5601
----
I tested this with the new services image from above PR, and it works well. I do this to avoid a lockstep update and lots of failing tests. After the new services image has landed, I'll try to drop the hack.
=> test: Adjust hack in TestGrafanaClient for non-crashing page

test/verify/check-metrics
With the latest service refresh [1] Grafana now handles being offline correctly.
[1] https://github.com/cockpit-project/bots/pull/5601
=> test: Drop plugin update check crash hack

test/common/storagelib.py
The test was already regularly scratching the ceiling with its hair, but with the recent RHEL package updates [1] it's finally bumping its head.
Raise the ceiling higher.
[1] https://github.com/cockpit-project/bots/pull/5627
---
See [failure log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5627-20231202-084403-de479f47-rhel-8-10-distropkg-storage-cockpit-project-cockpit/log.html#17-2), [second failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5627-20231202-084400-de479f47-rhel-8-10-storage-cockpit-project-cockpit/log.html). `/` is at 99% usage at this time, so it can't even get the few KB to install the rpms.
I triggered an additional rhel-8-10 storage run against the refresh PR.
=> test: Increase encrypted root partition size

test/browser/main.fmf
`TestStorageswap.test` checks swap usage, which we get from the "direct" metrics source, i.e. from PCP. This doesn't fail for cockpit's own PRs as these TF runs install all built cockpit RPMs. But it's missing for cross-project test runs.
Fixes #19683
=> fmf: Add missing cockpit-pcp test dep for /optional plan

pkg/storaged/utils.js
According to the btrfs-filesystem man page the maximum allowable length shall be less than 256 chars.
https://man.archlinux.org/man/core/btrfs-progs/btrfs-filesystem.8.en#label
=> storaged: add max btrfs label size

test/common/testlib.py
Commit 747e7c23b713 renamed send_message() to send_json(). Relax the pattern to get along with either (so that this also works for older cockpit versions in e.g. cockpit-machines tests).
----
This is one of our top flakes right now, e.g. https://cockpit-logs.us-east-1.linodeobjects.com/pull-1342-20231207-082302-4456d97b-rhel-9-4/log.html or https://cockpit-logs.us-east-1.linodeobjects.com/pull-1341-20231207-054951-a901376e-rhel-9-4/log.html#38
This mostly seems to affect c-machines these days, so after this lands I'll update test/common there to haul in the fix.
=> test: Adjust method name in #18355 message ignoring

containers/flatpak/test/test-browser, test/common/lcov.py, test/common/testlib.py, test/verify/check-metrics, test/verify/check-packagekit, test/verify/check-pages, test/verify/check-system-info
When the CPU is busy, the "Usage" card shows a warning icon next to the
progress bar meter, which shifts the layout.
Fixes #19614
---
Addresses [this pixel flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231116-012752-9da92292-fedora-39-updates-testing/pixeldiff.html#TestSystemInfo-testBasic-overview), plus some more cleanups.
=> test: Fix "busy CPU" pixel flake on overview page

src/cockpit/protocol.py, src/cockpit/router.py, test/common/testlib.py, test/pytest/mockpeer.py
When the bridge shuts down in an orderly fashion from an EOF on stdin, we signal the endpoints to exit, wait for them to do so, and only close the connection after that's done.
When the connection closes suddenly, such as from a BrokenPipeError, we don't do this waiting around.  The result is that the endpoints are never signalled to clean themselves up, and (crucially) we don't wait for them to do so.
Let's move the communicate() method from the protocol level to the router so that we can make it aware of endpoints.  Then we make two changes:
- if we didn't already call eof_received() then make sure it happens on disconnect of the transport.  This is what is responsible for asking the endpoints to close.
- from the end of communicate(), unconditionally wait for all endpoints to have …
=> bridge: try harder to ensure Endpoints exited

test/common/testlib.py
Commit c7c54d4ba12c9ab fixed that.
Fixes #18386
---
FYI @allisonkarlitskaya
=> test: Drop "Task was destroyed but it is pending" ignored traceback

test/verify/check-storage-lvm2, test/verify/check-storage-nfs
The latter is always present, even for rows that have no real usage displayed, just to get the spacing right.
Closes #19705
=> test: Wait for real usage, not just a element with a ".usage-bar" class

src/cockpit/packages.py, test/verify/check-connection
https://issues.redhat.com/browse/RHEL-18520
---
Now it looks pretty much like the old one:
```
❱❱❱ cpy --packages
apps                 Applications                             /var/home/martin/.local/share/cockpit/apps
base1                                                         /var/home/martin/.local/share/cockpit/base1
metrics                                                       /var/home/martin/.local/share/cockpit/metrics
playground           Development                              /var/home/martin/.local/share/cockpit/playground
selinux              SELinux                                  /var/home/martin/.local/share/cockpit/selinux
shell                                                         /var/home/martin/.local/share/cockpit/shell
sosreport            Diagnostic reports …
```
=> bridge: Add back menu/tool names to `cockpit-bridge --packages`

src/cockpit/packages.py, test/pytest/test_packages.py
We removed support for `.min.` filenames because we thought that nobody was using it anymore, but there are still external packages that make use of it.
Add it back again, by replacing our `.gz` stripping with a more general-purpose regular expression.
Add a bit of debugging output and a test case to make sure we handle the combinations properly.
Fixes https://issues.redhat.com/browse/RHEL-18861
=> bridge: Add back support for x.min.js files

test/verify/check-storage-mounting
Make testMountingHelp more re-usable by using one variable for the filesystem card header identifier.
I've copied these tests into `test/verify/check-storage-btrfs` https://github.com/cockpit-project/cockpit/pull/19690 but not be duplicate. So this is one step in the right direction. I think what we want to do is introduce `_testMountingHelp(self, fs)` and then call it for btrfs and ext4. This will be done in the btrfs PR, but to not make the diff huge let's already reduce some copy pasting here
=> test: storaged: use a variable for "ext4 filesystem"

pkg/storaged/storage.scss
The palette black color is grey and causes a white flash when hovering over the storage devices in dark theme.
Closes #19706
=> storaged: set a dark hover background on mobile

src/cockpit/samples.py, test/verify/check-networkmanager-wireguard
See https://github.com/cockpit-project/bots/pull/5432 for details, especially around the device mapper change [debug info](https://github.com/cockpit-project/bots/pull/5432#issuecomment-1849471326).
=> bridge: Fix disk sample ignoring of device-mapper; adjust TestWireGuard for Ubuntu 23.04

test/common/testlib.py, test/verify/check-client, test/verify/check-metrics, test/verify/check-packagekit, test/verify/check-storage-mounting, test/verify/check-storage-used, test/verify/check-system-info, test/verify/check-system-realms, test/verify/check-system-services
We have some more z-stream updates to do. Resuscitate this branch first to bring CI back to green. These are *only* clean backported test fixes, code changes will happen after this. This needs an updated naughty pattern from https://github.com/cockpit-project/bots/pull/5667 to "fix" the [NBDE test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19734-20231212-091957-c17189f9-rhel-9-3-storage/log.html)
=> revive rhel-9.3 branch

containers/ws/README.md, doc/guide/packages.xml
Fixes #19720 
Fixes #19701 
[ws doc preview](https://github.com/martinpitt/cockpit/blob/doc-updates/containers/ws/README.md#privileged-ws-container)
After this lands, copy the README to https://quay.io/repository/cockpit/ws
=> doc updates: cockpit/ws additional parameters, package loading lookups

pkg/apps/application-list.jsx, pkg/apps/manifest.json, pkg/lib/cockpit-po-plugin.js, pkg/shell/index.html, src/client/cockpit-client, src/cockpit/packages.py, test/pytest/test_packages.py, test/verify/check-apps, test/verify/check-connection
- https://issues.redhat.com/browse/RHEL-18989
- https://issues.redhat.com/browse/RHEL-19005
- https://issues.redhat.com/browse/RHEL-19004
Plus a few prerequisites and "nice to have" other fixes.
=> [rhel-9.3] backport fixes

test/browser/run-test.sh
This test started to fail yesterday and corrupt the VM. The dialog fails (for an unknown reason), `vgroup0` stays busy and becomes unremovable.
This doesn't happen in a local `tmt` run, in TF runs against cockpit itself (just in cross-project tests), nor in our fedora-rawhide CI image, and we currently don't get enough debug/journal information to say what's going on.
Skip the test on rawhide for the time being, so that we can improve our test machinery and investigate this without causing failure and noise to stratis, selinux, and udisks.
=> fmf: Skip TestStorageLvm2.testRaidRepair on Rawhide

pkg/networkmanager/network-interface.jsx, test/common/netlib.py, test/verify/check-networkmanager-basic
Most UI elements are already disabled/not editable, just these two were left.
Thanks to @g-pape for the initial patch!
Fixes #19242
=> networking: Disable interface On/off and MAC editing when unprivileged, fix network test failures on ubuntu-stable

pkg/lib/hooks.js, pkg/users/account-details.js, pkg/users/users.js, pkg/users/utils.js, test/verify/check-pages
The hashed passwords is sensitive data, and it gets copied around in the
browser a lot. This isn't a data leak or security issue, as a malicious
page already has the privilege to read it by itself at any time, and
browsers isolate websites pretty well. However, let's be careful.
We only need /etc/shadow for two reasons:
- Determine if an account is locked. Let's drop the file format
assumption and use `passwd -S`, just as the details page already
does. Use `get_locked()` from utils.js, and rework the code to get
along with it being async.
- Watch the file to get notified about account changes (locked, expiry,
etc.). But we only need the event, not the actual data. So install a
simple no-read file watch for this.
Also avoid reading utmp, as we don't look at its contents.
Thanks to …
=> users: Avoid reading /etc/shadow

test/verify/check-users
First commit fixes the [TestAccounts.testUserPasswords](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=7&test=test%2Fverify%2Fcheck-users+TestAccounts.testUserPasswords) that I've seen fail in #19751 a lot [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19751-20231218-082519-95729ab6-arch-other/log.html#171-2).
The second commit fixes this failure, which I've seen somewhere on CI, but I didn't keep the URL. But I do get it locally rather easily:
```
File "/var/home/martin/upstream/cockpit/main/test/verify/check-users", line 419, in testUserPasswords
createUser(
File "/var/home/martin/upstream/cockpit/main/test/verify/check-users", line 106, in createUser …
```
=> tests: Fix check-users races

test/common/testlib.py, test/verify/check-users
TestAccounts creates and recycles UIDs a lot, with different user names.
This can lead to failures: testFirst creating user testA, then
cleaning it up, then testSecond creates testB with the same UID, and all
of a sudden logind thinks that the running session of testB belongs to
testA (literally the user name, not just the UID).
logind caches this in /run/systemd/users/, and I haven't found a way to
wean it off that cache. So delete all uid cache files in between tests.
Move from `restart` to `stop`, as otherwise the new logind will rewrite
the files; and we don't have to explicitly start it as it gets D-Bus
activated.
Move the restarting until after stopping the remaining user@ services,
as otherwise there are still legitimate processes around from the
to-be-removed user.
----
See my …
=> test: Drop logind user ID cache

pkg/lib/timeformat.js, test/common/storagelib.py, test/common/testlib.py, test/verify/check-storage-lvm2, test/verify/check-storage-mounting, test/verify/check-storage-used
The index.js import ceases to work with date-fns 3.0.0. This also works with our current version 2.30.
---
See https://github.com/cockpit-project/cockpit-ostree/pull/477 -- we need to land this, bump the cockpit lib in ostree, and then can go ahead with that date-fns bump. This will also proactively fix the date-fns version bump in cockpit itself (which likely will happen in the next days).
=> lib: Make date-fns/locale import compatible with 3.0; test improvements
