- pkg/lib/html2po.js
- pkg/static/login.html
This fixes translatability and avoids brittle handling of the leading/trailing spaces.
---
This brings back the fix in PR #19746 from @NeftaliYagua , with an additional validation commit.
> static: Avoid leading/trailing space on browser check message

- pkg/packagekit/updates.jsx
- test/common/packagelib.py
https://cve.mitre.org/ is currently transitioning over to https://www.cve.org/ this change is just to reflect this, as support for the old site will likely be dropped eventually
> Packagekit: Update CVE link to go to the new site

- src/ssh/test-sshbridge.c
libssh 0.10.6 made host name parsing stricter. `some_host` is not a valid general host name, and is rejected with the latest version.
---
This should fix the COPR build failure in rawhide, f39, and https://github.com/cockpit-project/bots/pull/5729
> ssh: Use valid host name in test-sshbridge

- doc/anaconda.md
- pkg/storaged/anaconda.jsx
- pkg/storaged/block/create-pages.jsx
- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/block/other.jsx
- pkg/storaged/client.js
- pkg/storaged/dialog.jsx
- pkg/storaged/drive/drive.jsx
- pkg/storaged/filesystem/filesystem.jsx
- pkg/storaged/filesystem/mounting-dialog.jsx
- pkg/storaged/filesystem/utils.jsx
- pkg/storaged/lvm2/volume-group.jsx
- pkg/storaged/mdraid/mdraid.jsx
- pkg/storaged/nfs/nfs.jsx
- pkg/storaged/overview/overview.jsx
- pkg/storaged/pages.jsx
- pkg/storaged/stratis/filesystem.jsx
- pkg/storaged/stratis/pool.jsx
- pkg/storaged/stratis/stopped-pool.jsx
- pkg/storaged/stratis/utils.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-anaconda
Anaconda code: https://github.com/mvollmer/anaconda-webui/tree/cockpit-storage
Demo: https://www.youtube.com/watch?v=x3KfKJhBxD0
Next steps after this PR:
- Discourage the user from actually mounting new filesystems by only offering "Format only" in the format dialog.
> storage: Anaconda mode

- test/verify/check-selinux
The most recent RHEL 9.4 cloud images added the "rhc" package. This currently contains a hack to locally modify the SELinux policy [1], so we need to ignore this.
At least we can drop the insights_client hack, it was fixed properly in https://bugzilla.redhat.com/show_bug.cgi?id=2226684
[1] https://issues.redhat.com/browse/RHEL-20352
---
this blocks https://github.com/cockpit-project/bots/pull/5724
> test: Expect rhcd_t SELinux modification on RHEL

- test/verify/check-system-realms
Commit 800c89f93ffa fixed this for check-static-login already. Debian testing now got systemd 255 and ran into this changed output format as well.
---
Blocks https://github.com/cockpit-project/bots/pull/5732
> test: Adjust TestIPA.testClientCertAuthentication to changed loginctl  255 output format

- test/common/testlib.py
When no files exist in the directory the existing code would try to use the * as a file:
kkoukiou@o2:~/k$ for f in *; do echo $f; done
*
Instead let's list the files with `ls` to avoid this corner case as this breaks anaconda tests.
> tests: don't crash if no users exist when cleaning up login sessions

- test/browser/run-test.sh
- test/verify/check-storage-lvm2
It still fails way too often. Bring back the skip, and add the bug reference.
----
Over night we got lots of failure notifications in https://github.com/stratis-storage/stratisd/pull/3516 , https://github.com/fedora-selinux/selinux-policy/pull/1842,  https://github.com/storaged-project/udisks/pull/1234, and more where this still [causes](https://artifacts.dev.testing-farm.io/8fe07679-65c2-44a1-953f-1580e8316e3f/) [a mess](https://artifacts.dev.testing-farm.io/25b570cf-922a-4b03-ab7a-5be24c30ec85/).
> fmf: Re-disable TestStorageLvm2.testRaidRepair on rawhide

- test/verify/check-users
On loading the page, the "Disallow interactive password" checkbox is initially disabled, with a `null` value which shows up as [-]. Wait until it is initialized before taking the pixel test.
Fixes #19787
> test: Wait until #account-locked gets initialized

- test/verify/check-packagekit
This test often fails because the "Reboot scheduled" message does not reliably appear in dnf-automatic-install.service's journal. The scheduled reboot still works, though.
Robustify this by replacing the journal scraping with a direct check for a scheduled reboot. Newer systemd versions offer `shutdown --show` for this, which exits with 1 and prints "No scheduled shutdown", or exits with 0 and prints "Reboot scheduled for <date>...".
On RHEL8 we already have the `/run/nologin` check, which tests this enough. (Also, RHEL 8 support will drop in less than a month, so not important any more).
Drop the obsolete "Shutdown" absence check from the case where no shutdown should be scheduled. Recent systemd says "Reboot" (so this was a no-op), and checking for an absent /run/nologin is sufficient. …
> test: Robustify scheduled reboot check in TestAutoUpdates.testWithAvailableUpdates

- pkg/storaged/filesystem/filesystem.jsx
- pkg/storaged/filesystem/utils.jsx
- pkg/storaged/stratis/filesystem.jsx
In the btrfs PR this logic was copied over again and then refactored in a function. As this was conflictly I pulled it apart as it already is useful for Cockpit itself.
> storaged: refactor mount point text code into a common function

- src/common/cockpitjsonprint.c
- src/common/test-jsonfds.c
We only ever use them to store data. Recent Linux kernels now encourage explicitly declaring whether a memfd is supposed to be executable [1]. This avoids an unsightly warning at boot:
> login: [   85.637785] cockpit-tls[1176]: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set
Older kernel releases don't know about that flag yet, so add some ifdeffery and runtime fallback. We need to support building for a new distro/include files, but running on an older kernel.
[1] https://lwn.net/Articles/918106/
---
You can see this with `bots/vm-run fedora-39`
> common: Mark our memfds as non-executable

- doc/guide/cert-authentication.xml
- src/session/client-certificate.c
- test/verify/check-static-login
- test/verify/check-system-realms
- tools/cockpit.spec
- tools/debian/control
All our supported distros have a newer version: Ubuntu 22.04 LTS has 2.6.3, Debian stable has 2.8.2, RHEL 8/9 have 2.9.3. So we can finally drop support for the unsafe `FindByCertificate()` call which doesn't validate certificates against the CA.
> session: Drop support for sssd < 2.6.1

- test/verify/check-reauthorize
We'll hopefully be able to back this out soon.
> test: workaround an old (and very common) flake

- pkg/lib/cockpit.js
I am still trying to understand how this would help, opening PR to demonstrate how we can do this.
Looks like this:
> cockpit.js: Add debugging marking for translated strings

- pkg/storaged/partitions/partition.jsx
- test/verify/check-storage-partitions
Demo: https://www.youtube.com/watch?v=QlOEko76glg
This is intended to fulfill the "Cockpit can make biosboot and EFI system partitions" requirement. For a EFI system partition, one also needs to set the right mount point and format it with VFAT, but Anaconda doesn't make that clear at all currently.
> storage: Show partition types symbolically and allow editing

- test/verify/check-storage-lvm2
The name shows up in a pixel test, and we need it to always be the same.
> test: Use explicit name for TestStorageLvm2 loopback device

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/filesystem/utils.jsx
- pkg/storaged/stratis/pool.jsx
- test/verify/check-storage-anaconda
Demo: https://www.youtube.com/watch?v=Vtte11k6aQM
> storage: Don't offer to mount while formatting in Anaconda mode

- pkg/storaged/block/create-pages.jsx
- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/btrfs/device.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/btrfs/utils.jsx
- pkg/storaged/btrfs/volume.jsx
- pkg/storaged/client.js
- pkg/storaged/dialog.jsx
- pkg/storaged/filesystem/mismounting.jsx
- pkg/storaged/filesystem/mounting-dialog.jsx
- pkg/storaged/filesystem/utils.jsx
- pkg/storaged/overview/overview.jsx
- pkg/storaged/utils.js
- test/browser/browser.sh
- test/common/storagelib.py
- test/verify/check-storage-basic
- test/verify/check-storage-btrfs
- test/verify/check-storage-scaling
- tools/cockpit.spec
- tools/debian/control
This PR introduces the viewing of a btrfs "volume" with devices and subvolumes. To deliver a small initial version this is basically a readonly implementation except for mounting/unmounting subvolumes and setting the volume label.
The design is based upon LVM so what ever show is:
```
-> btrfs subvolume
-> btrfs volume (the filesystem)
-> btrfs device (backing storage)
-> block device
```
Multi device btrfs volumes should be shown as well but they lack information on the type of configuration RAID1, JBOD, whatever btrfs supports.
Quick demo https://youtu.be/x0kLxTyUXok
Overview:
Volume detail page;
Subvolume page:
We still have to shell out for a few operations instead of using UDisks notable ones are:
Not in order of importance!
Comments from @garrett  show a label that says "default" …
> Btrfs introduction PR

- pkg/storaged/pages.jsx
Whether or not a page is the last one was wrong. The test needs to use the sorted array, of course.
> storage: Fix border calculations for page tables

- pkg/storaged/client.js
It is only a warning when one of the "btrfs" invocations terminates unsuccessfully, and the loop continues with the next volume.
Some failures are expected when polling happens concurrently with removing subvolumes or volumes.
> storage: Robustify btrfs polling

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/block/resize.jsx
- pkg/storaged/swap/swap.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-swap
---
Cockpit can now format block devices as swap and will maintain a fstab entry for them.
> storage: Allow creation of swap and maintain fstab entries

- pkg/storaged/btrfs/volume.jsx
- test/common/storagelib.py
- test/verify/check-storage-btrfs
The parse_subvol_from_options function wants the whole options string, not individual options.
> storage: Fix listing of btrfs subvols in fstab

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/btrfs/utils.jsx
- pkg/storaged/client.js
- pkg/storaged/filesystem/mounting-dialog.jsx
- pkg/storaged/stratis/filesystem.jsx
- pkg/storaged/stratis/pool.jsx
- test/verify/check-storage-btrfs
Support creating and optionally mounting subvolumes. Subvolumes can only be created when any parent in the tree is mounted.
> Btrfs subvolume creation

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.js
- pkg/kdump/kdump.scss
- pkg/lib/cockpit-components-privileged.jsx
- test/verify/check-kdump
- Remove service status, use Alert instead for situations when service is failed / not installed / kernelcrash parameter is not set
- 'Test configuration' should use danger variant button
- Show target location on the card
- Reorganize content of kdump card 
- Add title to kdump card 
With SSH:
With NFS:
Designs are available here https://github.com/cockpit-project/cockpit/discussions/19203#discussion-5527715
> Kdump page improvements

- src/cockpit/beiboot.py
- src/cockpit/channel.py
- src/cockpit/channels/packages.py
- src/cockpit/channels/stream.py
- src/cockpit/jsonutil.py
- src/cockpit/packages.py
- src/cockpit/peer.py
- src/cockpit/protocol.py
- src/cockpit/remote.py
- src/cockpit/router.py
- test/pytest/mocktransport.py
We pass around an awful lot of JsonObject and JsonDocument throughout the bridge, which can be a problem sometimes, because you often get messages like:
> error: Argument "headers" has incompatible type "dict[str, str]"; expected "JsonDocument"  [arg-type]
> note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
> note: Consider using "Mapping" instead, which is covariant in the value type
when trying to pass something which seems like it should be a perfectly valid JsonObject.
The issue here is that the object time we're passing has a more specific type (in this case, it only accepts string values), and we don't know that the function we're passing it to doesn't intend to write to it. Mapping solves this by being read-only, which allows for …
> jsonutil: reorganize our Json* type names

- test/verify/check-storage-swap
The test teardown will remove /dev/sda and then we have a dangling device mapper. The next test in the same VM can fail, probably when it uses swap. This happens reliably in the testing farm on fedora-rawhide.
> test: Clean up encrypted swap as well

- pkg/storaged/btrfs/volume.jsx
- test/verify/check-storage-btrfs
We always assume fstab_subvol to be truthy while when fstab contains a btrfs mount without a subvol option it is not and we should just show the root subvolume.
In an ideal case we would call GetDefaultSubvolume when the filesystem is mounted and then show the subvolume name instead. I'll leave this for a follow up.
@mvollmer what do you think of ^, I believe this is correct.
---
I would like to merge this as is, as this blocks the btrfs filesystem creation at the moment.
> storaged: btrfs: don't break on a btrfs mount without subvol

- tools/debian/cockpit-ws.install
- tools/debian/rules
This will install the PAM modules into /usr once pam.pc switches over.
https://bugs.debian.org/1061198
----
This takes @mbiebl 's patch from https://salsa.debian.org/utopia-team/cockpit/-/merge_requests/1 , I want to run it through CI for all our supported Debian and Ubuntu releases.
> tools: Rely on pam.pc to get pam's libdir in Debian packaging

- pkg/shell/hosts.jsx
- pkg/shell/nav.scss
"Introducing a minor update:
Changes: Improved caret transition in the document, accessible through .
View the modifications : 
https://github.com/cockpit-project/cockpit/assets/106718914/efe6945f-0bdf-42d6-bf81-e4c2112478be
Previous version  : 
https://github.com/cockpit-project/cockpit/assets/106718914/5098e445-23d8-4531-8aac-d71249965999
> shell: Animate host switcher caret

- doc/protocol.md
- src/cockpit/channel.py
- src/cockpit/channels/__init__.py
- src/cockpit/channels/filesystem.py
- src/cockpit/jsonutil.py
- src/cockpit/misc/print.py
- test/pytest/test_bridge.py
- test/pytest/test_packages.py
- tools/vulture-suppressions/cockpit.py
Left for follow-ups:
- what to do about the case where `path` is a directory which gains/loses read/search permission while we're watching it
- add support for reporting symlink target attributes (possibly without monitoring for changes)
- maybe some kind of `file(1)`-flavour content identification attribute, mime type sniffing, etc.  gio has this.
> New fsinfo channel

- doc/protocol.md
- src/cockpit/channels/filesystem.py
- test/pytest/test_bridge.py
cockpit-navigator needs this for the case of "/bin is a symlink to /usr/bin, but what icon should I use for it?".
This helps us find out what "/usr/bin" is, without needing additional queries.
Note: the approach here is not the first one I considered, which was to report the target-info directly on the entry in question.  I avoided doing that because:
- conceptually, this information doesn't belong to the directory entry in question, and since we don't update it on changes, it's a bit awkward having it in the `entries` dict (where absolutely everything else is kept absolutely up to date)
- in the case of symlinks to the same directory (which is a common case in our "stress test" cases of `/usr/bin` and `/usr/lib64`) reporting the information for each item that links to an entry that we're …
> Add target tracking to fsinfo

- test/common/testlib.py
- test/verify/check-sosreport
Cockpit-navigator wants to include download support and requires the same code to be run so let's make this re-usable.
See: https://github.com/cockpit-project/cockpit-navigator/pull/175
> test: add allow_download helper for Browser class

- pkg/storaged/storage-controls.jsx
Disabled items can't be interacted with so showing the red danger color is not so important and as it's not a disabled color it confuses users.
> storaged: when a menu item is disabled don't show a warning color

- pkg/storaged/client.js
I have a test for that at https://github.com/rhinstaller/anaconda-webui/pull/72
> storage: pass configured swap partition in the cockpit_mount_points

- doc/protocol.md
- src/cockpit/channels/filesystem.py
- test/pytest/test_bridge.py
- `fnmatch` is now called `entries`, because setting this attribute will get you an item called `entries` added to your attributes
- you can now also request all entries by adding `entries` to `attrs`
- similarly, `targets` is now requested by adding `targets` to `attrs` with the idea that if we want to support different update methodologies in the future we are free to choose which one, and if we want to give the user control, we can add a `targets` option back again, at that point.
The general gist of these changes are making it easier to consume the API.  Both existing APIs (cockpit.print and the fsinfo client-side being developed in cockpit-navigator) support passing attributes as positional arguments, but require kwargs/object for extra options.  That turns something like:
```
cpf …
```
> fsinfo channel: tweak a couple of options

- pkg/systemd/reporting.jsx
1. a flex-gap of 0.5 rem added between the spinner and text
2. fixed the error not clearing when the report button is re-clicked, now it first becomes "Waiting to start" same as the other options before cycling through the other checks for errors.
Fixes #19059
> systemd: Fix spinner gap

- doc/protocol.md
- pkg/base1/test-external.js
- src/bridge/cockpitfsread.c
- src/bridge/cockpitfsread.h
- src/bridge/test-fs.c
- src/cockpit/channels/filesystem.py
- src/ws/cockpitchannelresponse.c
- test/pytest/mocktransport.py
- test/pytest/test_bridge.py
Cockpit navigator and SOS report offer a file download option, downloading a file in the browser shows the download speed but no estimation of how long it takes. This is due to the lack of the Content-Length header which could be added via the external channel options however the `fsread1` channel already has all the information.
The `fsread1` channel now emits a `size-hint` in the ready message which cockpit-ws picks up and adds a Content-Length header. The header is only included for the binary channel mode.
Closes: #19861
> ws: Support Content-Length in the fsread1 channel

- pkg/apps/watch-appstream.py
- test/verify/check-apps
The most recent Rawhide appstream-data package moved the data files into /usr/share/swcatalog/ [1] for AppStream 1.0 compatibility.
Look there as well, and cover both directories in our integration tests.
Fixes #19902
[1] https://src.fedoraproject.org/rpms/appstream-data/c/13eeac9635c3b
> apps: Search in /usr/share/swcatalog

- pkg/base1/test-external.js
Get rid of the bash wrapping and invoke stat directly, make the request synchronous.
> base1: simplify the Content-Length test

- src/cockpit/channel.py
- src/cockpit/peer.py
- src/cockpit/protocol.py
- src/cockpit/remote.py
- src/cockpit/router.py
- src/cockpit/transports.py
- test/static-code
This enables `mypy --strict` on a handful of files.  This was all fairly straight-forward.
In general, we need to proceed from the bottom of the dependency tree upwards.  That means that the next targets are:
- config
- packages
- router
- channel
- all the channels 
- peer
- bridge
We're stuck on config because systemd_ctypes dbus stuff isn't `--strict` friendly.  We're stuck on router because the 'freeze' mechanism is pretty evil from a types perspective and I kind of want to get rid of it anyway.
Let's get these "easy" ones in now.
> various cleanups for typing stuff

- pkg/storaged/client.js
The device names should be always unique, the mount points / device types are not. An example is swap, where the user is allowed to configure multiple swap partitions. For this reason, let's make the keys of the cockpit_mount_points storage object have the device paths as keys.
> storaged: anaconda: invert the keys/values in the cockpit_mount_points object

- test/common/storagelib.py
- test/verify/check-storage-btrfs
When we have a multi device setup we want to not allow formatting of btrfs devices as this breaks multi disk setups. We had a test for this but it was only in testBasic, since we do allow formatting of a single btrfs filesystem device now the test was wrongly removed and should have been moved to testMultiDevice.
> test: add device is in use test for formatting btrfs

- src/common/cockpitwebserver.c
- src/tls/httpredirect.c
- src/tls/test-server.c
...we don't need them for GET and for HEAD they're forbidden (and the new curl version complains).  Just never send them.
Hopefully this helps with https://github.com/cockpit-project/bots/pull/5861
> Remove bodies from HTTP 301 redirects

- test/verify/check-users
Arch seems to want to use /usr/bin/bash as the path to the default shell.  Accept it as a valid alternative.
Hopefully this helps with https://github.com/cockpit-project/bots/pull/5861
> test: accept /usr/bin/bash as valid path

- test/common/cdp.py
This is not longer required according to https://issues.chromium.org/issues/40527919 on linux.
Sending this with the hope that it will fix some recent crashes we see in anaconda: https://cockpit-logs.us-east-1.linodeobjects.com/pull-152-20240206-142606-4d5a14ae-fedora-rawhide-boot/log.html#28-1
> cdp: remove disable-gpu flag from headless Chrome

- pkg/storaged/pages.jsx
Several users have reported a broken storage page as their browser was too old, technically we don't support such old browsers but as enough users complain and using sort() doesn't drastically complicated the code use that for now instead.
Fixes: #19848
> storaged: stop using Array.prototype.toSorted for now

- pkg/lib/cockpit-components-truncate.jsx
- pkg/lib/cockpit-components-truncate.scss
- pkg/storaged/pages.jsx
- pkg/storaged/storage.scss
- test/verify/check-storage-basic
And redo indentation magic. Now also tables without icons will show indentations, and the Truncate element will get a correct width on indented columns.
Thanks a lot to MohdMohsin97 for the initial version of this!
Fixes #19767
> storage: Allow truncation of ID column

- pkg/lib/cockpit-components-context-menu.jsx
- pkg/lib/cockpit-components-terminal.jsx
The navigator copied the contextmenu implementation while it can be easily made re-usable by allowing passing children.
This allows us to drop:
https://github.com/cockpit-project/cockpit-navigator/blob/main/src/context-menu.jsx and scss file.
> pkg: make contextmenu component standalone & re-usable

- test/common/lcov.py
This naturally happens in PRs that don't make changes to JavaScript files.
Lcov 1 was fine with empty outputs, but lcov 2 needs to be explicity told to tolerate them.
This PR is its own test case. It doesn't have changes to JavaScript.
> test: Allow empty coverage info for the diff

- pkg/storaged/block/format-dialog.jsx
- test/verify/check-storage-luks
The code would take a shortcut when creating a new partition of type "empty", but that is wrong since there might be encryption options that should not be ignored.
Also, lock the encryption in more cases, for consistency.
> storage: Don't ignore encryption for new empty partitions

- selinux/cockpit.fc
With the 1f76e522a ("Rename all /var/run file context entries to /run") selinux-policy commit, all /var/run file context entries moved to /run and the equivalency was inverted. Subsequently, changes in cockpit.fc need to be done, too, in a similar manner.
> selinux: Cover migration to /run

- HACKING.md
We've seen contributors close their PRs after each review and open a new one. Don't do that.
---
FTR, I also updated https://github.com/cockpit-project/cockpit/wiki/Workflow to current reality.
> HACKING: Keep your PR!

- pkg/storaged/mdraid/mdraid-disk.jsx
- pkg/storaged/mdraid/mdraid.jsx
It is not fully reliably, unfortunately, and sometimes doesn't turn True after starting the array.
> storage: Don't use o.fd.UDisk2.MDRaid.Running property

- pkg/users/account-details.js
- pkg/users/users.js
The accounts page is still wildly inefficient it averages: ~3777 ms and now 3359 ms. However that is just done with 5 test refreshes, not scientific at all :-)
useInit still has a problem that `{ read: false }` does read from disk. Basically what happens:
- first file.watch() invocation does an fsread1 to obtain the tag
- as side-effect it also reads the content and returns
- so we end up with now two invocations of getLogins (which is a fairly expensive function) as it calls `passwd -S` for every account.
Update: while reading the man page of passwd, we want `passwd --all -S`. That should fix O(n) calls. I'll handle that in an updated PR.
For a "clean" VM we call `passwd -S` 94 times!
> Users account fixes

- .github/workflows/build-ws-container.yml
- .github/workflows/codeql.yml
- .github/workflows/dependabot.yml
- .github/workflows/differential-shellcheck.yml
- .github/workflows/flatpak-test.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/reposchutz.yml
- .github/workflows/unit-tests-refresh.yml
- .github/workflows/unit-tests.yml
- .github/workflows/urls-check.yml
- .github/workflows/weblate-sync-po.yml
- .github/workflows/weblate-sync-pot.yml
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20.
See for example: https://github.com/cockpit-project/cockpit/actions/runs/7812167902
> .github: update workflow checkout actions to v4

- pkg/users/users.js
Sometimes for longer names lastlog inserts a tab for example for `systemd-timesync`. This causes `passwd -S` to be unable to look up the account name.
> users: handle tab's in lastlog output

- pkg/users/users.js
We called `passwd -S` 92 times! Now with `--all` it's still called twice due to the `getLogins` calls but it's already an O(n) removal improvement so \o/
Note: we might want to investigate getting rid of the `date -d` calls and replace it with one invocation? That's maybe something for a follow up.
```
before
3168 ms
3110 ms
3645 ms
5221 ms
3733 ms
-----
after the previous accounts cleanup PR
2999 ms
4445 ms
2882 ms
3801 ms
2669 ms
-------
This PR :)
790 ms
550 ms
531 ms
561 ms
440 ms
```
> Accounts page loading performance improvements

- .github/workflows/release.yml
This was added by 09fe9eeef99bee9fe6026be19f6c724ec155db5f which needed it for `xml.etree.ElementTree.indent` but the `ubuntu-latest` GitHub Actions image has gained Python 3.10 since then, so this is now superfluous.  Drop it.
Supersedes (hopefully) #19980.
> workflows: stop using actions/setup-python

- pkg/storaged/dialog.jsx
- test/verify/check-storage-partitions
Now the text and unit inputs stay constant when the user changes the other, and the slider moves accordingly. Previously, the slider would remain in place and the text input would change when the user changed the unit input.
I believe this is more natural: When people interact with the text and unit input, they very like start inputting the number and then they adjust the unit to what that number should be interpreted in.  In the old behavior, changing the unit would change the text so that the resulting value would still be the same. (Changing the unit from GB to MB would multiply the text by 1000.)
This was however masked by a bug: the text input did not actually change, although the SizeSLider component would pretend that it had. For example, when the unit was "GB", and the user typed …
> storage: Improve behavior of size slider text and unit inputs

- pkg/lib/patternfly/patternfly-5-overrides.scss
A lot of our dialogs include parts which are not under our control (such as VM or container names), which can be long. Also, the title templates themselves may get longer in some translations.
Revert PF's `no-wrap` whitespace option (which partially hides the title in conjunction with `overflow: hidden`) to `normal`.
---
This generalizes https://github.com/cockpit-project/cockpit-machines/pull/1439 . I applied this override locally to c-machines and confirmed that it still fixes the dialogs.
> pf5: Don't hide long dialog titles

- src/common/cockpitwebresponse.c
- src/common/cockpitwebresponse.h
- src/common/test-webresponse.c
- test/common/testlib.py
- test/verify/check-connection
- test/verify/check-static-login
Commit 96335a440c15859 introduced a crash: Requesting any HTTP method
other than "GET" or "HEAD" segfaulted cockpit_web_response_error() as
`self->method` is NULL. That could happen because
cockpit_web_response_set_method()` refused to set unsupported ones.
Improve the /web-response/head test to set the "HEAD" method right away
with `cockpit_web_response_new()`, instead of overwriting setup()'s
"GET" default.
That was the only consumer of `cockpit_web_response_set_method()`. This
method is rather dubious, as the method should only be set in the
constructor. So eliminate it and move the check into the constructor.
Keep the provided method value also for unknown ones.
Change the critical to a warning, as it's not an internal program error.
Fixes #19997
----
After this lands, we also need to …
> common: Fix crash with unsupported HTTP methods

- HACKING.md
The C bridge is the old bridge, new developers should run the unit tests with the Python bridge.
> HACKING.md: default to running test-server with Python bridge

- pkg/storaged/block/format-dialog.jsx
- test/verify/check-storage-partitions
The rest of the storage stack rounds the size down to full MiBs, but it is better to round them to the nearest MiB for small partitions. So let's instruct the size slider to do that.  Resizing partitions already did that, so this change also makes creation consistent with resizing in this regard.
For example, rounding to nearest will result in a 1 MiB partition when the user asks for a 1 MB one, instead of the smallest possibe one.
> storage: Explicitly round sizes for new partitions

- pkg/storaged/block/create-pages.jsx
- pkg/storaged/btrfs/device.jsx
- pkg/storaged/btrfs/filesystem.jsx
- pkg/storaged/btrfs/volume.jsx
- test/verify/check-storage-btrfs
- test/verify/check-storage-mounting
> Single device btrfs filesystem presentation

- pkg/storaged/partitions/partition.jsx
- test/verify/check-storage-anaconda
We still want to show all the details individually, and not hide that the EFI system partition is a vfat filesystem, but we want people to see the special partition types in the overview.
https://bugzilla.redhat.com/show_bug.cgi?id=2263972
> storage: Include special partition types in table rows

- pkg/kdump/kdump-client.js
This is an shim for Object.assign
---
BTW: shall we also drop `cockpit.extend` ?
> kdump: stop using obsolete cockpit.extend

- pkg/systemd/overview-cards/insights-poll-hack.sh
Insights-client produces a long backtrace in the journal when it tries to log a warning or error to a closed stdout. This has started to hapen recently and causes our tests to fail due to the unexpected journal messages.
> systemd: Prevent insights-client crash when stdout is closed

- test/common/storagelib.py
The kernel in ubuntu-2204 has started to require this, while others don't seem to care.
> test: Make our loopback device partitionable

- test/common/storagelib.py
The kernel in ubuntu-2204 has started to require this, while others don't seem to care.
Cherry-picked from main commit 2aebbbf2c
> [r8] test: Make our loopback device partitionable

- HACKING.md
- src/ws/test-server.c
Our default bridge is the Python bridge so test-server should by default use the Python bridge.
> ws: switch the default bridge to the Python bridge

- pkg/kdump/manifest.json
- pkg/networkmanager/bond.jsx
- pkg/networkmanager/manifest.json
- pkg/packagekit/manifest.json
- pkg/storaged/manifest.json
- pkg/systemd/manifest.json
- pkg/systemd/overview-cards/cryptoPolicies.jsx
- pkg/users/manifest.json
One issue: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/configuring-automated-unlocking-using-a-tang-key-in-the-web-console_system-management-using-the-rhel-8-web-console has no equivalent in RHEL 9.
> pkg: update documentation links to rhel-9

- pkg/Makefile.am
- pkg/lib/README
- pkg/lib/cockpit-po-plugin.js
We've switched over to ESBuild from Webpack one year ago and all our projects switched over as well. This was the last Webpack plugin we still had in our Git repository.
---
Let's discuss if this is the way we want to go.
> lib: drop webpack support in cockpit-po-plugin

- test/verify/check-pages
b10e0d9988fa84d6be43dec2e5d22f249ec7861b broke our CI as links are changed to RHEL-9.
Sorry :sob: 
Fixes #20040
Fixes #20041
> test: loosen documentation link checks

- packit.yaml
- test/README.md
- test/browser/run-test.sh
- test/image-prepare
- tools/cockpit.spec
This was only a thing on RHEL 8, which we don't support on this branch any more.
> Drop cockpit-appstream split

- test/verify/check-metrics
The currentMetrics are our internal metrics and not the PCP metrics. This started to fail because the pmlogger service is now disabled by default in our debian/ubuntu images.
> test: currentMetrics don't need to wait on pcp

- test/common/pixel-tests
Without stripping the / getting the pixel tests from a full log.html url fails silently.
> test: also strip the / from log.html

- test/verify/check-storage-lvm2
The TestStorageLvm2.testLvm pool page pixel test flakes due to not waiting on sizes to "settle". Instead of waiting on a hardcoded value mock the values so in the future we won't have issues when a thin pool is allocated bigger or smaller by default.
Closes: #20053
---
Pixel changes https://cockpit-logs.us-east-1.linodeobjects.com/pull-20068-20240221-104351-68c22789-fedora-39-storage/log.html
> test: ignore usage bar in lvm pixel tests

- pkg/storaged/filesystem/mounting-dialog.jsx
- pkg/storaged/filesystem/utils.jsx
- test/verify/check-storage-anaconda
- test/verify/check-storage-mounting
By giving a empty mount point to the "Mount configuration" dialog.
The code was already all there, we just have to allow the empty string in the input field.
> storage: Allow removing of fstab entries

- test/verify/check-connection
It seems a newer openssl shows the CN has CN=domain instead of adding spaces in between.
```
depth=0 C=US, O=e026698ab23a4de0b89f3889fcddc9a7, CN=fedora-40-127-0-0-2-2201
verify error:num=20:unable to get local issuer certificate
```
> test: adjust regex matching for newer openssl

- test/verify/check-storage-mdraid
So that a given device in /dev always has the same serial.
Fixes #19765
> test: Add Qemu disks sequentially in TestStorageMdRaid

- test/verify/check-metrics
Ubuntu 2204 currently seems to need at least two samples to produce a graph.
> test: Wait for two samples in TestHistoryMetrics.testNoDataEnable

- pkg/lib/cockpit-components-dialog.jsx
We need this information in Anaconda, to properly show backdrops.
Relevant to: rhbz#2264015
> lib: anounce modals being opened and closed

- test/verify/check-storage-btrfs
On debian-stable in CI tests can fail with `umount: /mnt: target is busy` presumbly btrfs is still "busy" creating a subvolume so waiting is required.
> test: btrfs: umount in a busy loop

- test/common/testlib.py
After our round of {kill,terminate}-session, logind sessions often end
up in "closing" state, and neither their leader process nor their cgroup
actually exist any more. To avoid error messages and timeouts in the
following poll/wait loop, restart logind to mop up these closing
sessions.
Note that we still keep the other restart after stopping user@*
services, as that may again cause orphaned sessions.
Fixes #19972
-----
See #19972 for the debugging notes. I tested this in https://github.com/cockpit-project/cockpit-podman/pull/1582 with 6 parallel 3x affected runs, and it *never* failed session cleanup.
> test: Clean up "closing" sessions before polling them

- src/Makefile.am
This previously broke distro package builds when they happened with the `cockpit-bridge` package installed:
```
Processing ./tmp/wheel/cockpit-0-py3-none-any.whl
Installing collected packages: cockpit
Attempting uninstall: cockpit
Found existing installation: cockpit 311
ERROR: Cannot uninstall cockpit 311, RECORD file not found. Hint: The package was installed by debian.
```
This is a `pip` bug (https://github.com/pypa/pip/issues/3063), work around it with `--ignore-installed`.
----
See https://github.com/cockpit-project/cockpit/issues/19343#issuecomment-1965154956 ff. for how this failed. I verified that this works fine now.
> build: Force `pip install` to not check for already installed module

- test/verify/check-storage-lvm2
We see frquent timeouts here in TF. Let's hope the test is just slow in TF and doesn't hang completely.
> test: Wait longer for deletion of LVM2 raid volumes

- test/verify/check-packagekit
Debian-stable / RHEL-9-4 has packagekit 1.2.6, RHEL-8-10 has 1.4.2. So nothing in CI should still require this check.
> test: drop packagekit 1.2.4 version check

- pkg/lib/esbuild-common.js
A fix has been comitted to PatternFly react one year ago.
https://github.com/patternfly/patternfly-react/pull/8864
> lib: remove PatternFly workaround for DataList's

- pkg/storaged/mdraid/mdraid.jsx
- pkg/storaged/pages.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-anaconda
They were probably hidden earlier because there was no easy way to
enumerate their members without a block device for the mdraid
itself. But we can pretty easily make the should_ignore function work
with the o.fd.UDisks2.MDRaid path directly.
https://bugzilla.redhat.com/show_bug.cgi?id=2265241
> storage: Show stopped mdraids in Anaconda mode

- pkg/users/utils.js
This doesn't fix anything but might might help uncover our TestAccounts.testBasic flake where the locked checkbox is shown as null instead of unchecked.
> users: log exceptions for obtaining locked status

- test/common/chromium-cdp-driver.js
React discourages rendering directly to `document.body` as its children might be manipulated by other third-party scripts. We used to render to body directly in machines, but currently this is no longer true and all our pages should also render to a <div> inside <body>.
> test: allow direct rendering to body warnings

- src/appstream/org.cockpit-project.cockpit-networkmanager.metainfo.xml.in
While it is pkg/networkmanager, its manifest declares its name to be "network". Fixes the link on the Apps page.
Fixes #20127
---
I verified that the other files are correct.
> appstream: Fix launchable for Networking

- test/common/chromium-cdp-driver.js
> test: drop unsafe inline warnings

- pkg/users/account-details.js
> users: Disable "locked" checkbox when no info is available

- pkg/systemd/logs.jsx
- pkg/systemd/logsJournal.jsx
The source of the truth should be `currentIdentifiers` as defined in `logs.jsx`.
`logsJournal.jsx` had separate object to keep the same information and
than this `currentIdentifiers` was being synced. This was not ideal
solution which might fail when there are multiple updates at the same
time as well as it might not trigger update correctly when just editing
set object.
This commit only uses one source of the truth and uses updater callback
to make sure the list is always correctly updated.
> logs: Do not use duplicate object to keep state

- tools/cockpit.spec
these are changes required to for the opensuse testing image, we currently do not package `python3-tox-current-env` nor `pyproject-rpm-macros` so until both of those are packaged we can not run the pytest suit. This may change in the future but for now the simplest solution is not installing those dependencies.
> don't try and install pytest requirements on suse for now

- test/README.md
- test/common/packagelib.py
- test/common/run-tests
- test/common/testlib.py
- test/verify/check-packagekit
That doesn't work any more, RHEL 8 testing now happens on the `rhel-8` branch.
----
This is primarily an excuse to work out our shiny new job-runner CI.
> test: Drop rhel-8* from supported OSes, fix for ruff 0.3.1 (fixes failing "tox" test)

- pkg/apps/watch-appstream.py
Thanks to Fabian Vogt @Vogtinator for pointing out!
See https://github.com/cockpit-project/cockpit/issues/19902#issuecomment-1987334718
> apps: Add missing AppStream metadata paths

- test/verify/check-metrics
podman 5 regressed user containers if there is no default route [1].
While that is being sorted out, add a fake interface with a default
route for our offline tests, to unbreak upstream podman PRs testing.
Same hack as in https://github.com/cockpit-project/cockpit-podman/commit/cecb2cc6e8f2
[1] https://github.com/containers/podman/issues/21896
------
See [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6050-20240309-073607-686c9e16-fedora-40-other-cockpit-project-cockpit/log.html) in https://github.com/cockpit-project/bots/pull/6050
I  trigger a fedora-40/other@bots#6050 run, but due to a bug in our new infra it will be reported as "fedora-40" (see pilot board).
> test: Add fake default route to work around podman 5 regression

- pyproject.toml
Lacking a proper requirements.txt file, we're at the mercy of whatever
got randomly uploaded to pypy last night, and we've been seeing a lot of
breaks lately.
We already run our ruff/mypy/etc. stuff as part of our unit tests
workflow, so let's stop running it in venv.  The idea is that we should
pass against the current version of the tasks container (which will
probably shift at some point to being our pinned version of the tasks
container).
While we're at it, drop Python 3.7 (which the world seems to have
collectively decided to stop caring about) and add Python 3.13 (which
has been in Fedora 39 for a while already).  Note: we do *not* drop
Python 3.6 — although it is no longer an officially supported release,
it's used in RHEL 7 and RHEL 8 and Fedora intends to keep packaging it.
> pyproject.toml: stop linting in venvs

- tools/Makefile-tools.am
- tools/apparmor.d/cockpit-desktop
- tools/debian/cockpit-ws.install
- tools/debian/cockpit-ws.postinst
Ubuntu 24.04 LTS restricts user name spaces by default. Add an AppArmor profile for cockpit-desktop to allow it. This is a no-op for older releases.
See https://launchpad.net/bugs/2046477 for details.
----
Blocks https://github.com/cockpit-project/bots/pull/6048
> tools: Add AppArmor profile for cockpit-desktop

- src/cockpit/protocol.py
We cleaned up our act in the Python bridge about never sending null for 'host' or 'group', by ensuring that we directly forward messages.  We might still get these `null` values from outside, though.
Just accept `null` as a valid value for these fields.  It's the default value anyway.
https://bugzilla.redhat.com/show_bug.cgi?id=2267376
> bridge: accept `null` for host/group on kill

- .github/workflows/urls-check.yml
- tools/urls-check
Commit bc7e2bf38f8f729 was wrong: This workflow only doesn't need any permissions if all URLs are valid. But if not, then it wants to update/create an issue to notify us about that.
---
Fixes [this failure](https://github.com/cockpit-project/cockpit/actions/runs/8266231191/job/22613728485) which [started to happen 3 weeks ago](https://github.com/cockpit-project/cockpit/actions/workflows/urls-check.yml).
> workflows: Allow urls-check to write issues

- .cockpit-ci/container
- .github/workflows/unit-tests.yml
>  workflows: run unit-tests in the correct container 

- test/common/testlib.py
- test/verify/check-shell-multi-machine
- test/verify/check-superuser
- test/verify/check-system-services
- test/verify/check-users
Our click function already calls `wait_visible` so there is no need to wait twice.
> test: don't wait_visible when we click

- test/verify/check-static-login
- tools/arch/PKGBUILD
- tools/arch/cockpit.pam
- tools/cockpit.debian.pam
- tools/cockpit.pam
This should be in "account" (aka. "denied access"), not "auth" (aka. "provided wrong credentials"). Thanks to Stephen Gallagher for pointing out!
Adjust testPamAccess accordingly, which now shows the corresponding message.
---
Side issue in https://bugzilla.redhat.com/show_bug.cgi?id=2269361
> tools: Fix pam_listfile PAM stage

- pkg/lib/cockpit-components-dynamic-list.jsx
Deleting the items leaves an "undefined" entry, while splicing the removes them from the list. In the old situation the two lists would get out of sync and a user would never be able to complete the Create container dialog because an invalid state was left.
---
See https://github.com/cockpit-project/cockpit-podman/issues/1622#issuecomment-1999610172
> lib: keep validationFailed in sync with the list state

- pkg/users/authorized-keys-panel.js
- test/verify/check-shell-keys
This dropdown did not work, it is only supposed to show on mobile and like our other deprecated dropdown replacements it can replaced with our own KebabDropdown. In the introduction PR of the KebabDropdown this wasn't done as it seemed non-trivial to port due to the state used.
Additionally this now adds a test to verify the dropdown works.
> users: port authorized keys mobile dropdown to a KebabDropdown

- test/common/storagelib.py
- test/verify/check-storage-scaling
See https://github.com/cockpit-project/bots/pull/6101 . I locally verified that the [two failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6101-5605b494-20240318-225526-fedora-40-storage-cockpit-project-cockpit/log.html) now pass with these fixes. I'll trigger a separate run against that bots image, but we won't be able to look at the logs right now (but still get correct pass/fail status).
> Adjust tests for Fedora 40 introducing /var subvolume

- pkg/storaged/btrfs/subvolume.jsx
The local variable is called "mounted".  The code was using "is_mounted", which is a function, and thus always true.
> storage: Fix "is mounted" check for subvolume size column

- pkg/lib/cockpit.js
We no longer need to fallback to browser specific visbilitychange events all browsers support them now for at least 3 years (Safari only in 2021).
---
sidenote: `document.hidden = "hidden"` does absolutely nothing, writing to it doesn't cause an oops but as the property is readonly it doesn't do anything. Shall we just drop that as well?
Basically dropping hiddenHint from this closure.
> lib: all browsers now support visibilitychange

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/filesystem/mounting-dialog.jsx
- pkg/storaged/stratis/filesystem.jsx
- pkg/storaged/stratis/pool.jsx
The default is now determined by at_boot_input. Previously, btrfs subvolumes would be created with "local" instead of the desired "nofail" default.
> storage: Make initial "at_boot" values consistent

- .github/workflows/tasks-container-update.yml
Instead, use test/common/make-bots directly. The Makefile only exists after running autogen.sh, and we really don't need to do that just to get the bots.
> ci: Don't use "make" in tasks-container-update

- test/run
- test/vm.daily
- test/vm.updates-testing
Re-run the new `download-package-sets.sh` script introduced in [1] to ensure that they match the installed package versions after updating them to the COPRs or updates-testing.
[1] https://github.com/cockpit-project/bots/pull/6110
Fixes #20184
> test: Re-download package sets for daily/updates-testing scenarios

- src/cockpit/beiboot.py
- test/verify/check-client
After all SSH authentication attemps fail, e.g. entering the wrong
password three times, ferny throws an InteractionError. Merely exiting
cockpit-beiboot gets interpreted as "Internal error" which is unfriendly.
Ferny recognizes the most common errors, like DNS resolution and and
authentication failure. Use that API to convert them to proper cockpit
protocol error codes, so that they get presented and translated properly.
---
Two commits split out from PR #19401
> pybridge: Improve beiboot error reporting for fatal login failures

- test/common/packagelib.py
Recent versions of repo-add will not write any files in this case, which will cause pacman to fail later on.
Instead, create the "testrepo" repo already during setup, and put a single package in it.
> test: Don't create a empty pacman repo

- test/run
The "expensive" and "storage" scenarios both take 14 minutes, while "other" takes 21 and "networking" only 10.
"TestKerberos" really belongs to the same group as TestIPA and TestAD, and TestConnection is at least moderately related to "networking".
This balances the test scenarios better.
---
See a typical recent test run: [expensive](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20206-34a34996-20240320-142318-fedora-39-expensive/log.html) (14 mins), [networking](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20206-34a34996-20240320-142319-fedora-39-networking/log.html) (10 mins), [other](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20206-34a34996-20240320-142318-fedora-39-other/log.html) (21 mins), [storage](https://cockpit-logs.us-east-1.linodeobjects.com/pull-202 …
> test: Move TestAD and TestConnection to the "networking" scenario

- test/verify/check-metrics
This workaround exists since the introduction of the metrics page in commit b2dac1a51b6bc8968 in 2020 with no clear reason why loading metrics takes a while on Debian and Ubuntu.
> test: drop ubuntu/debian workaround for pcp metrics

- doc/protocol.md
- pkg/systemd/overview-cards/motdCard.jsx
- pkg/users/authorized-keys.js
- src/cockpit/channels/filesystem.py
- test/pytest/test_bridge.py
- test/verify/check-shell-keys
- test/verify/check-system-info
This provides an API to stop the bridge from vandalizing permissions
with `cockpit.file.replace()`. The worst impact was with writing ssh
keys which we hacked around [1], but it hits other places like changing
/etc/motd (#19905).
When an expected tag is provided, copy owner and permissions from the
existing file. This still isn't perfect (it's e.g. missing ACLs or
customized SELinux context), but much less broken than the status quo.
Note that we can't use `shutil.copystat()` for this -- it does *not*
copy owner (which we need), but copies access/modification times (which
we don't want). The tag collision detection together with the previous
commit of inclusing permissions into the tag will ensure that the
permissions don't change in between creating, writing, and renaming the
updated …
> bridge: Copy file permissions in fsreplace1 with expected tag

- pkg/storaged/client.js
So that btrfs subvolumes do not get the "newly created" animation on every page load.
> storage: Wait for the initial btrfs poll

- pkg/lib/cockpit-components-privileged.jsx
- test/verify/check-shell-multi-machine-key
This is preparation work for landing the porting of cockpit.user() to the Promise API https://github.com/cockpit-project/cockpit/pull/18589
Maybe we can land 18589 then after the release so we have some time to stabilise possible fallout.
> User promises cleanup

- pkg/lib/cockpit-components-plot.jsx
The SvgPlot component forces a re-render when the size of its outer
"div" has changed. This requires that this outer div settles on a
stable size.
However, some browsers can optionally add noise to the result of
getBoundingClientRect, which causes a constant re-rendering of the
plots since the "div" never seems to settle.
Thus, we tolerate the noise and only re-render when the size has
changed significantly.
Fixes #20171
> lib: Avoid infinite layout measurements in plots

- Makefile.am
So that test/browser/browser.sh can find it when it runs from a source tarball during Fedora package gating.
> build: Put .cockpit-ci into source tarballs

- pkg/sosreport/sosreport.jsx
- test/verify/check-sosreport
Files in /var/tmp/ are controllable by any user. In particular, an unprivileged user could create an sosreport* file containing a `'` and a shell command, which would then run with root privileges when the admin Cockpit user tried to delete the report.
Use the `cockpit.file()` API instead, which entirely avoids shell. The main motivation for using shell and the glob was to ensure that the auxiliary files like *.gpg and *.sha256 get cleaned up -- do that explicitly (which is much safer anyway), and let our tests make sure that we don't leave files behind.
https://bugzilla.redhat.com/show_bug.cgi?id=2271614 https://bugzilla.redhat.com/show_bug.cgi?id=2271815
-----
[Cockpit 270](https://cockpit-project.org/blog/cockpit-270.html) introduced a possible local privilege escalation vulnerability …
> sosreport: Fix command injection with crafted report names [CVE-2024-2947]

- pkg/lib/cockpit.js
- pkg/lib/hooks.js
- pkg/shell/hosts.jsx
- pkg/shell/indexes.jsx
If I understood it correctly, we completely want to drop `cockpit.defer`. This seems a bit tricky in the other cases like the DBusClient and cockpit.http, but seems doable for `cockpit.file` as a start :)
We now return a proper Promise instead of an `function`. So this requires some code fixing as with `useEffect` in 1f5724d4e9a707b65279f49fa1bced2dae877f34 and ofcourse we can't use `.done()` or `.fail()`.
I want to land this tomorrow after the release and then on Thursday cockpit-lib-update runs and I can deal with the potential fallout in podman, machines, .etc.
> lib: port cockpit.user to use standard promises

- pkg/sosreport/sosreport.jsx
- test/verify/check-sosreport
Files in /var/tmp/ are controllable by any user. In particular, an unprivileged user could create an sosreport* file containing a `'` and a shell command, which would then run with root privileges when the admin Cockpit user tried to delete the report.
Use the `cockpit.file()` API instead, which entirely avoids shell. The main motivation for using shell and the glob was to ensure that the auxiliary files like *.gpg and *.sha256 get cleaned up -- do that explicitly (which is much safer anyway), and let our tests make sure that we don't leave files behind.
https://bugzilla.redhat.com/show_bug.cgi?id=2271614 https://bugzilla.redhat.com/show_bug.cgi?id=2271815
Cherry-picked from main commit 9c4cc9b6df632082538b5
> [rhel-8] sosreport: Fix command injection with crafted report names [CVE-2024-2947]

- test/common/storagelib.py
- test/verify/check-storage-mounting
Newer versions of the things involved in mountin seem to give much better error messages and we can be very specific. The old much more generic error message is treated as an afterthought.
> test: Also allow modern "mount" error message

- .github/workflows/release.yml
- tools/release
This is a new script for building Cockpit releases.  It essentially does what we do now, except:
- we use the container version specified in our .cockpit-ci/container file
- we download everything with a single invocation of `git clone`, which downloads all the required submodules, but only does a shallow fetch
- we run the build process entirely offline, inside of its own container
The new script is meant to be more accessible to anyone who may be interested in running it, including outside of GitHub, and is written in a way that attempts to convince its reader that nothing tricky is going on.  It should always produce a byte-for-byte identical release as the official one.  It acts as a convenient way to verify the reproducibility and validity of a Cockpit release, and also as an …
> tools: add 'release' script

- pkg/networkmanager/network-interface-members.jsx
- pkg/shell/nav.scss
- pkg/shell/topnav.jsx
- pkg/systemd/overview.jsx
- test/verify/check-apps
- test/verify/check-pages
- test/verify/check-shell-menu
This moves us away from all deprecated Dropdown usages in Cockpit, and it requires a slight pixel test change:
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20223-b1e6ffe7-20240402-105419-fedora-39-other/log.html
> networkmanager: systemd: port to non-deprecated Dropdown

- pkg/lib/cockpit-components-dropdown.jsx
In some cases (like in c-machines), the dropdowns are rendered in an unstable environment like a dynamic list. Then their identity can change easily, and they lose their internally tracked open state. Add `isOpen`/`setIsOpen` attributes to provide an optional external state management.
----
I've tested this on cockpit-machines and it seems to fix `testDetachDisk()`. https://github.com/cockpit-project/cockpit-machines/pull/1539 validates it on our CI.
> lib: Add optional external open state to KebabDropdown

- pkg/networkmanager/dialogs-common.jsx
- pkg/packagekit/updates.jsx
- pkg/shell/failures.jsx
- pkg/shell/hosts_dialog.jsx
- pkg/storaged/lvm2/block-logical-volume.jsx
- pkg/systemd/abrtLog.jsx
- pkg/systemd/overview-cards/configurationCard.jsx
- pkg/systemd/services.jsx
- pkg/systemd/timer-dialog.jsx
`oxlint` a Rust implementation of `eslint` finds more issues for the `jsx-no-useless-fragment` eslint react rule. The Rust implementation is not feature complete yet so we can't yet switch over.
https://oxc-project.github.io/blog/2023-12-12-announcing-oxlint.html
> pkg: fix fragments should contain more then one child

- test/verify/check-system-info
The current and newly proposed Fedora 39 images have machine IDs whose rendered text lengths differ enough that the former breaks across two lines, while the latter fits into one. Avoid that by setting a fixed ID and include it in the pixel comparison.
Move the reading of the real machine ID downwards next to the UI assertion.
---
See https://github.com/cockpit-project/bots/pull/6184#issuecomment-2042101862 - fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6184-e9417cad-20240405-225930-fedora-39-other-cockpit-project-cockpit/log.html#76) on image refresh.
> test: Use fixed machine ID for pixel test

- test/verify/check-packagekit
Calling `b.reload()` right before `b.login_and_go()` is not only pointless (as the latter always uses an explicit open()`), it also introduces a race condition. At least with Firefox it is asynchronous, and the login attempt then partially goes into the old page.
Besides, the `MachineCase.login_and_go()` wrapper takes care of starting cockpit, i.e. everything necessary for the first login after booting. Use it everywhere.
---
[number 2 on the weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=7&repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-packagekit+TestUpdates.testTracer). Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20267-1caa76e0-20240408-082455-fedora-39-firefox-expensive/log.html#21)
> test: Fix login page flake in TestUpdates.testTracer

- src/cockpit/channel.py
- src/cockpit/channels/filesystem.py
- src/cockpit/channels/http.py
- src/cockpit/channels/metrics.py
- src/cockpit/channels/packages.py
- src/cockpit/channels/stream.py
- src/cockpit/jsonutil.py
- src/cockpit/protocol.py
- src/cockpit/router.py
- test/pytest/test_bridge.py
Here's some assorted cleanups and improvements that will help with #20160.  Let's merge these first, since they're not directly related (and are big enough that they might cause regressions in their own right).
> bridge: assorted channel-related goodies

- pkg/systemd/logsHelpers.js
Array.prototype.push supports giving it multiple arguments so making it a list of and de-structuring is unrequired.
> systemd: remove useless spread and list

- .github/workflows/release.yml
Just like the "reposchutz" and "dependabot" workflows, run "release" on ubuntu 20.04. Podman in 22.04 creates truncated tarballs when streaming them through stdout.
----
This broke the release, the 315 tarballs were only ~ 200 to 300 kB and truncated.
> workflows: Run release on Ubuntu 20.04

- .eslintrc.json
- package.json
- pkg/lib/cockpit.d.ts
- pkg/lib/hooks.ts
- test/static-code
- tsconfig.json
I want to use typescript in an upcoming test page in the playground.  Let's lay some foundations.
I ported `hooks.js` to typescript because:
- I use it from my page
- it wasn't too hard
- proof of concept to make sure nothing breaks
I didn't port `cockpit.js` because:
- that's gonna be a lot of work
In any case, if everything is working correctly, this shouldn't actually change anything.
For the record:
```
31M	node_modules/typescript
548K	node_modules/@types
32M	total
```
The `@types` includes are fairly harmless, but I'm a bit more worried about adding typescript itself.  That's a ~7% increase in the size of our `node_modules`.  We could alternatively use the version of typescript available in Fedora and make sure to install it somewhere (tasks container, dev depenency during package …
> Experimental typescript support

- .github/dependabot.yml
react and react-dom need to be kept in sync.
> dependabot: Group react packages

- test/common/lcov.py
Our current predicate for whether we report coverage on a file or not is "not in node_modules, and name ends in .js/x".  Add .ts and .tsx to that as well.
> test: lcov: add coverage for ts/x files

- pkg/lib/cockpit.d.ts
- pkg/lib/cockpit.js
Add and type-hint a new cockpit.assert() function which throws an error if the given predicate is not true.
Fixes #20298 
followup: add qunit tests.  This requires a bit of `.ts` hackery in our `qunit-test` file, and I don't want to block this feature.
> base1: add cockpit.assert()

- pkg/lib/cockpit-components-dropdown.jsx
This probably makes no difference since onSelect is probably only called when isOpen is true anyway. But this is more explicit and follows the example code more closely.
> lib: Close Dropdown after selection instead of toggling it

- pkg/lib/cockpit.d.ts
Specify exactly which superuser options we support so language server users see warnings for wrong options in their editor.
> lib: the channel superuser option takes "try" or "require"

- doc/protocol.md
- pkg/kdump/test-config-client.js
- pkg/lib/cockpit-upload-helper.ts
- pkg/lib/cockpit.d.ts
- pkg/lib/index.d.ts
- pkg/playground/react-demo-file-upload.tsx
- pkg/playground/react-patterns.html
- pkg/playground/react-patterns.js
- src/cockpit/channel.py
- src/cockpit/channels/filesystem.py
- test/common/testlib.py
- test/pytest/test_bridge.py
- test/verify/check-pages
- tools/vulture-suppressions/testlib.py
- add a flow control mechanism to the bridge (sending 'ack' control messages to confirm that data was received)
- add a helper api (`upload()`) to `pkg/lib` to allow uploading large amounts of data (from a `ReadableStream`) using flow control, with progress reporting
This is my take on #20160
> flow control for file uploads

- test/verify/check-metrics
`journalctl` recently updated its precise behavior wrt. matching
`--since` and `--until` against journal files, see [1]. This caused the
displayed log window for the "load" spike event to shift from the
earlier "Created slice cockpittest.slice" to the later
"load-hog.service" region, so that the old expected strings don't match
any more.
Update the expected strings for load-hog.service -- this actually makes
sense as this is the "load" spike event, so it feels like earlier
systemd versions got this wrong. Skip the test on more old OSes.
This will stop skipping this test as a naughty match for
https://github.com/cockpit-project/bots/issues/5106 -- this is
established behaviour now.
Fixes #20302
[1] https://github.com/systemd/systemd/issues/28746
----
Note that the changed test invalidates …
> test: Update journal check in TestHistoryMetrics.testEvents to current systemd

- src/cockpit/channels/filesystem.py
...this got merged in parallel to the ruff work, so it slipped through the cracks.
I included this in #20322 but it seems we will have some more discussion there first.
> bridge: fix a `(a and b) or c` case

- test/verify/check-metrics
Don't remove the /var/log/pcp/pmlogger directory itself, just its content, like we do in all other tests. Latest pcp version fails to start up if the directory isn't present. This is a regression [1], but also there's no need to be that demanding.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2275408
Fixes #20327
> test: Less aggressive pmlogger log cleaning in TestGrafanaClient

- test/verify/check-client
- test/verify/check-connection
They affect the other OSes, so testing/landing them separately.
Blocks #20321
> tests: two adjustments for CentOS 10 compatibility

- test/README.md
- test/common/storagelib.py
- test/verify/check-connection
- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-checkpoints
- test/verify/check-networkmanager-settings
- test/verify/check-networkmanager-team
- test/verify/check-networkmanager-wireguard
- test/verify/check-storage-vdo
- test/vm.install
> Enable CentOS Stream 10 tests

- tools/cockpit.spec
`kdumpctl` moved from the kexec-tools to the kdump-utils package in Fedora Rawhide, and the former does not require the latter. To make sure we get the one we want, depend on the program path directly.
https://bugzilla.redhat.com/show_bug.cgi?id=2275385
> tools: Depend on kdumpctl binary

- doc/guide/cockpit-util.xml
- files.js
- pkg/base1/test-format.js
- pkg/base1/test-format.ts
- pkg/lib/cockpit.d.ts
- pkg/lib/cockpit.js
- pkg/lib/qunit-tests.ts
- pkg/storaged/dialog.jsx
- pkg/storaged/test-util.js
- pkg/storaged/utils.js
- move a very specific API (`cockpit.get_byte_units()`) with a single user (`storaged`) into that user (along with its unit tests), and simplify it a bit
- add a new API style for our number formatting APIs that removes many of the existing warts
- port `test-format` to TypeScript
> Clean up and type number formatting APIs

- test/static-code
After mypy (addressed in #20342) the slowest thing in test/static-code is... JSON validation.  This is caused by the fact that `json.tool` doesn't support multiple filenames, so we have to invoke it separately for every single JSON file (and we have many).
Replace that with a small script which runs in a single Python invocation and improves the output by printing the name of the file containing the failure (which `json.tool` doesn't do).
> test/static-code: speed up JSON validation

- .eslintrc.json
- pkg/storaged/dialog.jsx
This rule is not part of the standard ESLint recommends set but is useful and can be auto-fixed.
> eslint: enable no-useless-fragment rule by default

- pkg/storaged/client.js
eMMC devices can have "boot" sub-devices which should be excluded from multipath considerations, just like partitions.
Fixes #20250
> storage: Exclude eMMC "boot" non-partitions from multipath logic

- pkg/lib/patternfly/patternfly-5-overrides.scss
Fixes cropping and highlighting, in two separate commits; one in PF overrides (the cropping) and the highlighting (in nav, as a switcher in a menu is only used in nav and PF doesn't have any examples of this, so it's a local change).
> shell: Session menu toggle fixes

- test/common/testlib.py
- test/verify/check-superuser
- test/verify/check-system-terminal
`TestTerminal.testBasic` and `TestSuperuser.testBasic` both often fail with an unexpected message like
> /system/overview.js: truncated data in external channel
This is just a matter of timing, and can happen in a similar manner as "external channel failed: terminated". Add this to allow_restart_journal_messages() and call that in both tests, as they both call `Browser.relogin()` and thus interrupt anything that's currently going on in the session.
---
It's one of the main offenders on the [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7) (with lots of example links). I also ran into it a lot in PR #19132 ([log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19132-cb7e27fd-20240425-065620-rhel-9-5-expensive/log …
> test: Fix unexpected "truncated data in external channel" messages

- pkg/shell/topnav.jsx
- test/verify/check-shell-menu
We have had PF regressions in the session menu and it doesn't hurt to also test the help menu.
Pixel changes: https://cockpit-logs.us-east-1.linodeobjects.com/pull-20371-076a3250-20240425-142139-fedora-39-other/log.html
> test: add pixel tests for the help and session menu

- test/verify/check-selinux
Fallout from moving TEST_OS_DEFAULT to Fedora 40. RHEL 8, 9 does not yet know about this SELinux flag, so ignore it in the comparison.
Closes: #20396
> test: Adjust for new selinuxuser_execmod flag on Fedora 40

- doc/protocol.md
- pkg/lib/cockpit-upload-helper.ts
- pkg/playground/react-demo-file-upload.tsx
- src/cockpit/channel.py
- src/cockpit/channels/filesystem.py
- src/cockpit/channels/http.py
- test/pytest/test_bridge.py
Plus some associated cleanups.
Not in this PR: sending the `size` attribute from `cockpit.file().replace()` — the way we handle iterating over string data (which may contain non-ascii characters) makes this quite difficult at present.
> Add a `size` hint attribute for `fsreplace1`

- test/verify/check-selinux
semanage in Fedora 40 eats a lot more ram leading to memory allocation issues. Bumping it to 600 is not enough, bumping it to 650 MB leaves ~ 40/60 MiB of memory left according to `top`.
/sbin/load_policy:  Can't load policy:  Cannot allocate memory
> test: bump ansible machine memory size

- configure.ac
- src/session/Makefile-session.am
- src/systemd/Makefile.am
- src/systemd/cockpit-session.socket
- src/systemd/cockpit-wsinstance-http.service.in
- src/systemd/cockpit-wsinstance-http.socket.in
- src/systemd/cockpit-wsinstance-https-factory.socket.in
- src/systemd/cockpit-wsinstance-https@.service.in
- src/systemd/cockpit-wsinstance-https@.socket.in
- src/systemd/cockpit.service.in
- tools/arch/PKGBUILD
- tools/cockpit.spec
- tools/debian/rules
All distributions use the same value anyway, and this paves the way for unifying them further with moving to systemd-sysusers.
We never test the upstream default of running them as root, so it might not even work and we also don't want to support/encourage that.
----
Broken out of #20365 and fixed. I want to test/land this separately, as it's quite intrusive.
@travier FYI
This release drops the `./configure` options for customizing the two system users of cockpit's web server:
`--with-cockpit-user`, `--with-cockpit-group`, `--with-cockpit-ws-instance-user`, and `--with-cockpit-ws-instance-user`. All supported distributions use the same name anyway. We don't test, support, or recommend running the web server as root, which so far has been the default with `./configure; make; make install`. …
> build: Remove cockpit(-ws-instance) user/group config option

- test/common/cdp.py
In Cockpit-files we download using `window.open` which Chromium sometimes blocks depending on how long the browser was open, the session was active or other unknown heuristics. To stop the tests from flaking disable popup blocking in general as this also allows a Developer to now run `TestFiles.testDownload` as a separate test without getting window.open blocked.
---
This sadly can't be achieve via CDP so requires a big hammer :( This should fix the two top flakes in Files:
https://cockpit-logs.us-east-1.linodeobjects.com/pull-425-13a6056a-20240501-204215-fedora-rawhide/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-389-0acab15d-20240422-204056-fedora-40/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-389-0acab15d-20240422-204056-fedora-40/log.html
> test: disable popup blocking for Cockpit-files

- test/verify/check-metrics
The mobile pixel test is way too flaky (> 50% failure rate on our CI). scrollIntoViewIfNeeded() somehow misplaces the menu bar. This isn't a real problem, an interactive Firefox/Chromium works fine.
Nobody has figured this out in two weeks, earlier attempts at fixing that (commits e700960 and 790b377) also weren't effective. Figuring this out is too much effort for too little benefit, and this flake breaks every PR. So disable the mobile pixel test.
Fixes #20338
> test: Drop mobile pixel tests in TestHistoryMetrics.testEvents

- pkg/storaged/mdraid/mdraid.jsx
- test/verify/check-storage-mdraid
A mdraid can have different consistency policies, and "bitmap" is only one of them. We should only tell people to add a bitmap when the policy is "resync".
UDisks2 and Cockpit don't understand consistency policy at all, so we do the bare minimum here to detect a journal.
Fixes #20381
> storage: Don't warn about missing bitmap when MDRAID has a journal

- pkg/systemd/timer-dialog.jsx
- test/verify/check-system-services
- tools/vulture_suppressions/testlib.py
When setting the time of a repeated timer with the mouse, this triggered both `onChange()` and `setOpen()` at the same time, both of which calling `setRepeatPatterns()`. Due to the async/deferred nature of React, these both worked on old data, so that the first callback was effectively ignored, and created timers ended up with the default "00:00" time. Fix that with a functional state update.
Also replace the weird JSON stringify/parse cycle with a spread, like all the other callbacks already did -- the only purpose of that was to copy the list.
This didn't happen when setting the time with the keyboard, because the dropdown wasn't opened then. So change TestTimers() to set the "Friday" repeat time with the mouse (keep the Monday one with the keyboard, to cover both cases). As we only …
> systemd: Fix state handling with creating repeating timers

- test/verify/check-kdump
- tools/cockpit.spec
Most of cockpit-system works fine without kdump functionality, and the kdump page fails gracefully without it ("Kdump service is not installed" alert). As recommends are installed by default, this is the right dependency level.
kdump does not currently exist on RHEL/CentOS 10 [1], so skip the test there.
[1] https://issues.redhat.com/browse/RHEL-35567
---
Blocks https://github.com/cockpit-project/bots/pull/6280 . I'm not triggering the new image tests here, as there are almost surely other regressions, and I don't want to land this red.
> tools: Lower kdumpctl dependency to Recommends on RHEL

- test/common/testlib.py
- test/verify/check-session
Despite multiple attempts/claims at fixing this, logind still often has empty "State: closing" sessions after logout, without any processes in it [1]. Our generic nondestructive test cleanup in testlib's terminate_sessions() has a workaround for this (restarting logind). Do the same in this test.
Only do this when waiting for the session to go away; starting new sessions should work fine.
Fixes #20379
[1] https://github.com/systemd/systemd/issues/26744
----
I could reproduces this rather well locally. Now it has survived two parallel loops of
for i in `seq 20`; do TEST_OS=arch test/verify/check-session -s $RUNC || break; done
> test: Fix handling of "closing" sessions in TestSession.testBasic

- HACKING.md
- doc/guide/https.xml
- pkg/networkmanager/dialogs-common.jsx
- test/browser/browser.sh
- test/browser/run-test.sh
- test/common/storagelib.py
- test/common/testlib.py
- test/verify/check-client
- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-networkmanager-settings
- test/verify/check-networkmanager-wireguard
- test/verify/check-packagekit
- test/verify/check-shell-multi-os
- test/verify/check-static-login
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
- test/verify/check-system-info
- test/verify/check-system-services
I accidentally [broke main](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20425-d3594a54-20240507-104057-debian-stable-other/log.html#49-2) with https://github.com/cockpit-project/bots/pull/6348 , sorry about that!
> test: Move TestMultiOSDirect from centos-8-stream to rhel-8-10, drop CentOS 8 special cases

- test/verify/check-shell-multi-os
https://github.com/cockpit-project/bots/pull/6348 removed the image already. Oops!
Cherry-picked from main commit 99e656ca5428
> [rhel-8] test: Move TestMultiOSDirect from centos-8-stream to rhel-8-10

- src/systemd/Makefile.am
- src/systemd/sysusers.d/cockpit-wsinstance.conf
- tools/arch/PKGBUILD
- tools/arch/cockpit-wsinstance.sysuser.conf
- tools/cockpit.spec
- tools/debian/cockpit-ws.install
- tools/debian/cockpit-ws.postinst
- tools/debian/cockpit-ws.postrm
- tools/debian/rules
This was originally proposed and discussed extensively in @travier 's PR #20365. However, all of a sudden  I'm not allowed to push into @travier's branch any more:
```
To github.com:travier/cockpit.git
! [remote rejected]     HEAD -> main-sysuserconfig (permission denied)
error: failed to push some refs to 'github.com:travier/cockpit.git'
```
So cloning the PR from my fork.
> systemd: Use systemd-sysusers to create cockpit-wsinstance user

- pkg/packagekit/kpatch.jsx
- test/common/testlib.py
- test/verify/check-system-services
Most of our tests don't bother logging out at the end, they rely on our generic nondestructive setup. But this causes some noise when using `restore_dir()` and friends, e.g. in TestApps.testBasic:
```
+ rm -rf /usr/share/metainfo; mv /var/lib/cockpittest/_usr_share_metainfo /usr/share/metainfo
+ mv /var/lib/cockpittest/_var_lib_PackageKit_transactions.db /var/lib/PackageKit/transactions.db
> warning: can't remove watch: Invalid argument
can't add watch for <ctypes.c_char_Array_20 object at 0x7f9aed107750>: Permission denied
File "<string>", line 445, in <module>
File "<string>", line 442, in watch_db
[...]
File "<string>", line 148, in watch_directory
PermissionError: [Errno 13] Permission denied: '/usr/share/metainfo'
```
As the tests themselves call …
> test: Terminate sessions before restoring files/directories

- pkg/lib/cockpit-components-table.jsx
As requested by this warning:
Th: Table headers must have an accessible name. If the Th is
intended to be visually empty, pass in screenReaderText. If the Th
contains only non-text, interactive content such as a checkbox or
expand toggle, pass in an aria-label.
> pkg/lib: Give empty "Th" elements a aria-label attribute

- pkg/storaged/pages.jsx
> storage: Give empty "Th" elements a aria-label attribute

- test/common/packagelib.py
- test/verify/check-packagekit
DNF 5 changed the systemd timers for dnf-automatic, this commit does not make Cockpit compatible with the new timers and configuration but unbreaks the current TF rawhide tests.
Related: #20260
> test: don't fail tests on DNF5

- .github/workflows/trigger-anaconda.yml
Rawhide was missing python3, and I am not sure what else is happening
in Rawhide and it just feels like unnecessary pain to use Rawhide to
run this workflow.
> workflows: Use Fedora 40 to trigger Anaconda

- pkg/packagekit/autoupdates.jsx
- test/common/packagelib.py
- test/verify/check-packagekit
Fixes #20260
---
We don't run our tests on the `fedora-rawhide` image, and anyway our current bots image is too old (it still defaults to dnf4), see https://github.com/cockpit-project/bots/issues/6393 . But I prepared and updated an image locally, and `TEST_OS=fedora-rawhide test/verify/check-packagekit` succeeds.
> packagekit: support dnf5-plugin-automatic

- pkg/users/account-details.js
- pkg/users/users.js
- pkg/users/utils.js
This follows up on the lastlog2 pr's to implement support for lastlog2. Lastlog2 slightly differs in behaviour from lastlog. Lastlog2 only prints user's who have already had entries in the lastlog2 database. Not having an entry is already treated as never logged in which matches the current behaviour
> users: Support for watching lastlog2 and wtpmdb on overview page

- doc/guide/https.xml
`connection_is_to_localhost()` specifically checks for `INADDR_LOOPBACK` (and the equivalent IPv6 addresses).
Fixes #20496
> guide: Fix TLS localhost exception

- test/verify/check-system-info
/usr/share/crypto-policies/policies/modules/SHA1.pmod went away (deliberately) in the latest crypto-policies CentOS 10 update.
Also drop the obsolete RHEL 8 special case, we don't test/support RHEL 8 from main any more.
----
Needs to land in lockstep with https://github.com/cockpit-project/bots/pull/6420 . Running the test against that refresh.
> test: RHEL 10 dropped SHA1 crypto policy module

- plans/all.fmf
- test/browser/browser.sh
- test/browser/main.fmf
- test/browser/run-test.sh
The "basic" vs. "optional" package split was only a RHEL 8 thing, and was removed in commit 429b3c28. Also the test plans are very imbalanced: basic takes 14 mins, network only 4.5 mins, and optional about 30 mins.
Reorganize them to split the storage tests in two plans (`storage-{basic,extra}`) and merge the others into a `main`.
As we now have to enumerate test class names explicitly, this cleans up the `EXCLUDES` list quite a bit: We can drop the parts where we skipped all tests of a class, and instead just not mention the class in `TESTS`.
---
I also added a fix for the current rawhide breakage.
Fixes #20520
> fmf: Reorganize and rebalance tests, fix rawhide TF scsi_admin breakage

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/block/resize.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/filesystem/mounting-dialog.jsx
- pkg/storaged/fsys-is-empty.sh
- pkg/storaged/legacy-vdo/legacy-vdo.jsx
- pkg/storaged/lvm2/block-logical-volume.jsx
- pkg/storaged/lvm2/volume-group.jsx
- pkg/storaged/mdraid/mdraid.jsx
- pkg/storaged/partitions/format-disk-dialog.jsx
- pkg/storaged/partitions/partition.jsx
- pkg/storaged/stratis/filesystem.jsx
- pkg/storaged/stratis/pool.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-anaconda
- test/verify/check-storage-btrfs
- test/verify/check-storage-lvm2
- test/verify/check-storage-swap
- test/verify/check-storage-unrecognized
But only in Anaconda mode.
Demo: https://youtu.be/EYU2jzDI0gk
------
When using Cockpit to configure storage manually during installation with Anaconda, one normally only operates on empty filesystems. You might create a couple of partitions with filesystems and then change your mind and delete those partitions again, maybe to create them in a slightly different way. These are all pretty harmless operations since no actual data gets deleted.
However, there might also be filesystems present that have not been created during installation. They might contain other operating systems and old, valueable files. In order to protect against deleting these by accident, Cockpit now checks whether a filesystem contains actual files before deleting it, and asks for extra confirmation if it does.
> storage: Confirmation before erasing non-empty filesystems

- pkg/lib/cockpit.d.ts
- pkg/metrics/metrics.jsx
- pkg/packagekit/updates.jsx
- pkg/systemd/overview-cards/cryptoPolicies.jsx
- pkg/systemd/overview-cards/lastLogin.jsx
- pkg/systemd/overview-cards/shutdownStatus.jsx
- pkg/systemd/overview.jsx
- pkg/users/accounts-list.js
Plus a small bug fix:
To
And now we close the Reboot dropdown after clicking on a dropdown item.
> First pass `tsc --checkJs true` run

- doc/guide/cockpit-session.xml
- pkg/base1/test-user.js
- pkg/lib/cockpit.d.ts
- pkg/lib/cockpit.js
- pkg/playground/test.html
- pkg/playground/test.js
- src/cockpit/internal_endpoints.py
- test/verify/check-pages
Cockpit files now obtains this via `id` while it is available in the bridge via `struct_passwd`.
> lib: add gid field to UserInfo

- tools/debian/cockpit-ws.install
- tools/debian/cockpit-ws.postinst
- tools/debian/rules
Commit 5659be39388b introduced an AppArmor profile for Ubuntu 24.04. However, loading that fails in Debian, as even unstable still has AppArmor 3.x, and that profile requires 4.x. This causes apparmor.service to fail to start after a reboot.
```
Installing new version of config file /etc/pam.d/cockpit ...
AppArmor parser error for /etc/apparmor.d/cockpit-desktop in profile /etc/apparmor.d/cockpit-desktop at line 1: Could not open 'abi/4.0': No such file or directory
```
This was hidden before because the postinst ignored `apparmor_parser` errors: Refine the condition and make these fatal instead, so that we immediately spot bugs in CI.
Conditionally install the AppArmor profile, and add transition code to remove the profile when upgrading from a broken version. …
> tools: Conditionally install AppArmor profile in Debian/Ubuntu

- pkg/lib/cockpit.js
cockpit.js can be bundled with users which don't depend on the latest-and-greatest bridge version, so we have to deal with the case where this field isn't present.
Let's not bother mentioning that in the type annotations — things will catch up eventually.  The actual access to this properly is causing Oopses today, though, so it needs to be fixed.
> cockpit.js: make access to Gid field conditional

- test/browser/browser.sh
- test/browser/main.fmf
This package does not exist any more in RHEL 10 (but still in CentOS 10 stream, which is why the test passes there). Install it dynamically for Fedora instead.
---
This made the RHEL 10 release fail for 317.
> fmf: Drop NetworkManager-team test dependency

- tools/cockpit.spec
The pcp i686 regression now affects CentOS/RHEL 9 as well, causing unit test crashes/build hangs. But CentOS/RHEL don't even publish i686 packages, so building them is entirely in vain.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2284431
> tools: Drop i686 build on CentOS/RHEL 9 as well

- src/cockpit/channels/filesystem.py
- test/pytest/test_bridge.py
The logic in fsinfo for reporting information on symlink targets is meant to report 'targets' iff the information isn't already reported elsewhere.  That's mostly done by checking if the symlink target contains a "/" anywhere in it and matching it against our effective fnmatch.
There are two cases that weren't considered, however: '.' and '..'. Those don't have a "/", so in the case where fnmatch is `*` (the default) they will never be reported (since `listdir()` doesn't return them and inotify doesn't report on those names).  In the case where fnmatch is something that doesn't match `.` and `..` then they will both always be reported.
Both cases are wrong.  '.' should never be reported: we already report those attributes on the toplevel, so why deliver a second copy? '..' should always …
> bridge: report target info for '..' on fsinfo

- pkg/lib/utils.jsx
More precisely check if a key is defined -- specifying `false` in the manifest should count as a match. This didn't affect Apps and Storage, but it does affect Machines:
https://github.com/cockpit-project/cockpit-machines/pull/1671
> lib: Accept `false` values in manifest configuration

- tools/debian/cockpit-ws.postinst
- tools/debian/control
Debian's /etc/nsswitch.conf doesn't include "passwd: systemd" by default, which breaks services with `DynamicUser=yes`. So we can't use that in Debian unconditionally yet (Ubuntu does set it up).
Go back to the static `adduser` call in that case.
---
This works everywhere else, but we didn't see that in our debian-testing tests as that image has a pre-existing `cockpit-ws` user from the pre-installed 311 version. The next image refresh won't have that any more, though. This was spotted by [autopkgtest](https://ci.debian.net/packages/c/cockpit/testing/amd64/47370887/). I tested this in a local VM with cleaned up static user, and committed it to Debian: https://salsa.debian.org/utopia-team/cockpit/-/commit/285b75cfb93
> tools: Bring back static cockpit-ws system user creation on Debian

- pkg/lib/cockpit-components-shutdown.jsx
The `error` state is a string, and rendered as such. Don't set it to an
error object when `shutdown` fails with an error, as that crashes the
page with "Objects are not valid as a React child".
Consistently use `.toString()` like we do in most other places.
Fixes #20547
> lib: Fix ShutdownModal error type on `shutdown` errors

- test/verify/check-metrics
On RHEL/CentOS 10 this often times out or hits the roof:
> Waiting for !ph_is_present("#pcp-settings-modal:first-child") took 28.5 seconds, which is 94% of the timeout.
Increase the timeout. While that's somewhat absurd, it's not our problem/bug, and dialogs with a spinner are often expected to take long to apply settings.
---
See https://github.com/cockpit-project/bots/pull/6474
Fixes [flake from the weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=7&repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-metrics+TestGrafanaClient.testBasic)
> test: Bump PCP config dialog timeout

- test/verify/check-system-tuned
This fixes the tuned [rawhide failures](https://artifacts.dev.testing-farm.io/a1d98007-75db-4903-b753-a7c9d0f91fe9/) that recently started to make our and selinux-policy's tests red.
Noe that they will still fail due to ABRT #20559, but TestTuned* should succeed now.
> test: tuned 2.23 fixes

- pkg/shell/indexes.jsx
- test/common/testlib.py
- test/verify/check-shell-host-switching
- test/verify/check-shell-menu
We don't want the skiplinks to *actually* change the URL -- they will go
from e.g. `/system` to `/cockpit/@localhost/shell/index.html#content`.
This causes a page reload, breaks the focusing, and is also not an URL
which we actually want to expose. Fix this by stopping event
progression.
Also remove the `return false` -- event handlers don't return anything.
Introduce a `TestMenu.testKeyboardNavigation` -- skip links and tabbing
was previously not tested at all.
[1] https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#the_event_listener_callback
----
Preparation for #20553 -- let's first test skiplinks before we change them.
> shell: Fix and test skip links

- test/common/testlib.py
- test/verify/check-pages
- test/verify/check-selinux
- test/verify/check-shell-active-pages
- test/verify/check-shell-host-switching
- test/verify/check-shell-keys
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-storage-partitions
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-system-terminal
> test: Clean up keyboard input API

- pkg/lib/cockpit-components-context-menu.tsx
- pkg/lib/cockpit-components-form-helper.tsx
- tsconfig.json
In Typescript when you say
interface iface {
prop?: string;
}
it means that the `iface` type can have an optional property `prop` present, and if it is present it must be a string *or* `undefined`.  The reason for that is that given an instance `x` of type `iface`, if you say `x.prop` then the result of that will be `undefined` if the property is missing, so in some sense the ideas of "missing" and "`undefined`" are semi-fungible.
This idea that a property can be present but defined to `undefined` is incompatible with our definition of JsonObject, which doesn't permit `undefined` to appear as a value in JSON documents, and has gotten us into a lot of trouble in the past, trying to create types to describe things that the bridge sends to us, in cases where a field may or may not be …
> typescript: enable --exactOptionalPropertyTypes

- pkg/users/users.js
- tools/debian/control
If `lastlog` is not installed, and neither is `lastlog2`, `getLogins()` ran into an uncaught "not-found" exception due to the spawn failure. The page then never finished loading.
Move the lastlog call closer to where the output is parsed, and handle failure.
----
Spotted in https://github.com/cockpit-project/bots/pull/6491 . This makes the tests mostly work (other than of course the actual "last login" checks)
> users: Fix crash on nonexisting lastlog

- test/mypy-deps
- test/static-code
We hardcode a check for systemd_ctypes, ferny, and beiboot in test/static-code and skip running mypy if they're not checked out, but that doesn't make sense for the other projects which use this script.
Move the configuration to a separate file, so each package can provide their own.  If no file is present, there are no dependencies: this is expected to be the normal case for starter-kit-based projects.
> test/static-code: make mypy deps configurable

- test/verify/check-metrics
podman 5.x trickles into more and more images, and and that point we just accept defeat. The issue still exists in current 5.1 and is tricky to "fix", see discussion on bugzilla.
Adjust the URL, as the upstream issue is closed.
---
Blocks https://github.com/cockpit-project/bots/pull/6501 , I trigger an extra run against that refreshed image.
> test: Widen pasta hack for newer podman versions

- test/run
There's a new firehose of SELinux violations in these distros. They are just too messy, ungated, and we can't keep up with reporting all the issues any more.
Fixes #20542
----
See the issue and its tons of duplicates, plus the centos-10 refresh. I give up, and the rest of the team is even less keen on piloting. 🏳️
> test: Stop failing on SELinux messages in rawhide and CentOS 10

- tools/arch/PKGBUILD
glib2 has been split up into glib2-devel since 2.80.3-2.
https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/FLUDH7DXL5CJNZPX4NAWKQO2QJF3PZCD/
> tools: arch: add glib2-devel as makedependency

- pkg/users/users.js
- test/common/testlib.py
- test/verify/check-system-journal
- test/verify/check-users
Spotted by https://github.com/cockpit-project/bots/pull/6491 . The [failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6491-b6cc24bb-20240612-091310-debian-testing-other-cockpit-project-cockpit/log.html)  pass for me locally now and also [in CI](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20579-6e46779f-20240612-145132-debian-testing-other-bots%236491/log.html).
~This still has a TODO item, the `passwd -S --all` fallback is a bit tricky to do here. See [failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20579-6e46779f-20240612-145019-rhel-9-5-other/log.html)~ Fixed.
> lastlog2 fixes

- pkg/lib/cockpit-components-password.jsx
Importing it via the global barrel file means we import the CSS of all patternfly components. This won't reduce our bundle for now as PatternFly table and other components still import via `@patternfly/react-core`.
> lib: import Flex from the Flex directory

- test/verify/check-connection
On latest Debian testing this started to fail with
Your account has expired; please contact your system administrator.
We don't actually need/want a PAM session for these commands. Replace these with `runuser`, which is easier to use anyway.
---
This blocks https://github.com/cockpit-project/bots/pull/6491 . I locally confirmed that [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6491-275efd40-20240617-131426-debian-testing-networking-cockpit-project-cockpit/log.html) is fixed. I trigger an additional run here to validate.
> test: Avoid `su` to system users

- tools/debian/cockpit-ws.postinst
- tools/debian/control
- tools/debian/tests/control
- tools/debian/tests/smoke
Depend on libnss-systemd to ensure that the "cockpit-ws" dynamic user can be resolved. With that we don't need to create a static system user any more.
Adjust the autopkgtest workaround to create that user instead, and add a bug reference. Restrict the hack to running inside of a container, as it works fine on the host.
Taken from downstream:
https://salsa.debian.org/utopia-team/cockpit/-/commit/f9e34e9b6ea4630
https://salsa.debian.org/utopia-team/cockpit/-/commit/87d81351f0f3eb6
https://salsa.debian.org/utopia-team/cockpit/-/commit/7ad393cee5a212d
> debian: Enable DynamicUser for cockpit-ws

- pkg/lib/patternfly/patternfly-5-overrides.scss
- pkg/systemd/reporting.jsx
> Fix outdated/redirected urls

- containers/flatpak/prepare
This will result in cockpit-files being included the next time we sync up with flathub (in the release workflow).
> flatpak: add cockpit-files to packages list

- test/verify/check-metrics
The latest Grafana version in the services refresh [1] replaced all human readable and sensible CSS classes with unpredictable junk like "css-140ea9t". So stop relying on the classes and just ensure that the "Load average" panel contains "minute" and any floating point number. This works with both the current and the new image.
[1] https://github.com/cockpit-project/bots/pull/6483
> test: Drop Grafana selector class names

- test/verify/check-metrics
The latest Grafana version in the services refresh [1] replaced all human readable and sensible CSS classes with unpredictable junk like "css-140ea9t". So stop relying on the classes and just ensure that the "Load average" panel contains "minute" and any floating point number. This works with both the current and the new image.
[1] https://github.com/cockpit-project/bots/pull/6483
Cherry-picked from main commit f004e993ae56.
> [r8] test: Drop Grafana selector class names

- src/cockpit/channels/filesystem.py
We call `self._watch.close()` and then set `self._watch = None` which means that if the function gets called twice we crash.  Those crashes have been showing up with increasing frequency in cockpit-files, so let's fix them.
Proper type annotations on this class would have forbidden this code in the first place, so let's add them now.
I've known about this issue for a while but I've put off fixing it because we should probably sort out why .do_close() gets called twice in the first place.  Let's fix this anyway, though, since it's causing annoying failures in the meantime.
> bridge: fix multiple close in fswatch1

- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/client.js
- test/verify/check-storage-btrfs
This PR identifies snapshots and lists them under the subvolume in a separate card.
Open questions:
---
Snapshot origin is shown in snapshot detail view
> List btrfs snapshots separately in the subvolume detail page

- files.js
- pkg/base1/test-fsinfo.ts
- pkg/lib/event.ts
- pkg/lib/fsinfo.ts
- tsconfig.json
This is almost exactly what's in Cockpit Files today.  I made a few small adjustments around the `loading` parameter (to make it easier to test) and I made the `close` event return the message so we can query the problem code (which is important for throwing exceptions from the async interface).
> Add `fsinfo` client library and QUnit tests

- plans/files.fmf
Cockpit-files is the only user of fsinfo so far, so testing if it Cockpit pull requests do not break Cockpit-files main is beneficial for the Cockpit project.
---
Not entirely sure if this is just it, as we have no test separation in cockpit-files like podman but this seems correct?
```
[jelle@t14s][~/projects/cockpit-files]%toolbox enter rhel-developer-toolbox-latest
[jelle@⬢ rhel-developer-toolbox-latest][~/projects/cockpit-files]%tmt
Found 1 test: /test/browser.
Found 1 plan: /plans/all.
Found 0 stories.
```
It would be good to only trigger this on src/cockpit and pkg/lib changes but I am not sure if fmf can support that.
> plans: add cockpit-files reverse dependency testing

- pkg/lib/cockpit-components-context-menu.tsx
f9b01663060c changed the popdown behaviour of the context menu.
Before that commit, the previous code was wrong.  It was:
const wasOutside = !(event.target.contains === root.current);
if (wasOutside)
setVisible(false);
but because `event.target.contains` is a function, the comparison was always false and wasOutside would always be true.  This meant that any left click would always pop the menu down.
The replacement code was:
const wasOutside = !event.target.contains(root.current);
which at least looks like it does something meaningful.  Unfortunately this is also wrong, but in the other direction: this means that the menu will only pop down if it's not contained inside of the item you've clicked on.  If you click on a large top-level <div> (ie: something which effectively contains "most …
> pkg/lib: fix context menu component popdown

- .gitignore
- containers/ws/cockpit-auth-ssh-key
- pkg/base1/test-http.js
- pkg/lib/cockpit.js
- pkg/storaged/crypto/luksmeta-monitor-hack.py
- src/build_backend.py
- src/cockpit/channel.py
- src/cockpit/channels/filesystem.py
- src/cockpit/channels/http.py
- src/cockpit/channels/metrics.py
- src/cockpit/channels/packages.py
- src/cockpit/channels/trivial.py
- src/cockpit/misc/print.py
- src/ws/test-server.c
- test/common/cdp.py
- test/common/run-tests
- test/common/testlib.py
- test/pytest/pseudo.py
- test/verify/files/mock-faf-server.py
- test/verify/files/mock-insights
- tools/build-debian-copyright
> bridge: Fix text channels with split UTF8 chars across frames

- tools/cockpit.spec
pcp got broken over three weeks ago on i686, with no solution in sight: https://bugzilla.redhat.com/show_bug.cgi?id=2284431
So drop our package there to unblock distro upgrades. This already happened downstream in
https://bodhi.fedoraproject.org/updates/FEDORA-2024-7f96e33d91
> tools: Disable cockpit-pcp on Fedora 39 on i686

- pkg/lib/cockpit-components-dropdown.tsx
- pkg/lib/cockpit-dark-theme.ts
- pkg/lib/cockpit.d.ts
- pkg/lib/pam_user_parser.ts
- pkg/lib/utils.tsx
... mostly stuff used by Cockpit Files.
This was all fairly trivial.  In `utils.tsx` most of the changes are adjusting the newer language features rather than adding typing.
> pkg/lib: Port various components to TypeScript

- pkg/lib/cockpit.d.ts
- pkg/lib/cockpit.js
- pkg/lib/dialogs.tsx
- pkg/shell/active-pages-modal.jsx
- pkg/shell/credentials.jsx
- pkg/shell/shell-modals.jsx
- pkg/shell/topnav.jsx
- simplify the implementation of `<WithDialogs/>`/`useDialogs()` by dropping the `await Dialogs.show()` mode and replacing it with a simpler `await Dialogs.run()`.  Port it to TypeScript.
- add `cockpit.transport` to the stub, making a very minor change to `cockpit.js` (on a path that should be essentially dead code).
> new async `Dialogs` interface, add `transport` to `cockpit.d.ts`

- pkg/lib/cockpit-components-context-menu.tsx
In f9b01663060c and d599d625e149 we've been trying to fix this code to make the `wasOutside` check "more correct".  The problem is that we actually always depended on it being broken.
The original version of the code before we started making changes would always close the menu on any click at all (because the comparison was broken).  This is actually the behaviour we need, because otherwise nothing will close the menu when we click on an item inside of it.
This is all sort of unfortunate, but let's just put it back to the way it effectively was by removing all of this `wasOutside` logic entirely. That means we're going to pop-down when the user clicks on a divider, but otherwise we have no way to tell the difference between dividers or other menu items (without making this all …
> pkg/lib: remove wasOutside check from context menu

- test/vm.updates-testing
https://bodhi.fedoraproject.org/updates/FEDORA-2024-d70dfd026e lands the kexec-tools split into Fedora 40. This temporarily breaks our "updates-testing" scenario as nothing installs kdump-utils into our image, and then the built rpms fail to install as /usr/bin/kdumpctl isn't available -- and `rpm -i` won't install it by itself.
Install it manually for now. This can be reverted after the next fedora-40 image refresh that includes that bodhi update.
Fixes #20660
> test: Adjust to kdump-utils split in Fedora 40

- files.js
- pkg/base1/test-timeformat.ts
- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/serverTime.js
- pkg/lib/timeformat.ts
- pkg/packagekit/history.jsx
- pkg/packagekit/updates.jsx
- pkg/storaged/crypto/encryption.jsx
- pkg/systemd/overview-cards/systemInformationCard.jsx
- pkg/systemd/timer-dialog.jsx
- pkg/users/account-details.js
- pkg/users/account-logs-panel.jsx
- pkg/users/accounts-list.js
- pkg/users/expiration-dialogs.js
- test/pytest/test_browser.py
This is a prerequisite for #20653 and also fixes an important bug.
> Type-annotate and unit-test timeformat, fix off-by-one day in parseShortDate()

- test/common/testlib.py
systemd recently dropped creating /home via tmpfiles [1]. Thus in the Anaconda environment there is no /home any more, which tripped up our nondestructive setup.
Also rename `home_dirs` to `initial_home_dirs` to clarify its purpose.
[1] https://src.fedoraproject.org/rpms/systemd/c/a76669ee222fc
----
See https://github.com/cockpit-project/bots/pull/6544 and [these lovely failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6544-c740e50f-20240625-081141-fedora-rawhide-boot-rhinstaller-anaconda-webui/log.html)
> test: Tolerate absent /home

- package.json
- pkg/lib/hooks.ts
- pkg/lib/notifications.js
- pkg/storaged/client.js
> node_modules: switch from deep_equal to dequal

- test/common/testlib.py
It's not NoneType. anaconda-webui sets a different class, and mypy complains:
> test/anacondalib.py:38: error: Incompatible types in assignment (expression has type "type[VirtInstallMachine]", variable has type "None")  [assignment]
---
Found as part of https://github.com/rhinstaller/anaconda-webui/pull/322 -- I locally applied the change and mypy is happy now.
> test: Fix type of MachineCase.machine_class

- test/static-code
This is wasteful to do outside of Cockpit and leads to us needing types installed for everything in pkg/lib which is .ts and unused in the project itself. (like deep-equal for example)
---
This ofcourse doesn't fix cockpit-files... because we import `hooks.ts`. But if someone ports the terminal component to typescript then CI in cockpit-files should not fail because we lack the types for xterm.js.
```
not ok 10 /static-code/test-typescript
```
> test: don't type check pkg/lib outside of cockpit

- pkg/base1/test-timeformat.ts
- pkg/lib/cockpit-components-shutdown.jsx
- pkg/lib/serverTime.js
- pkg/lib/timeformat.ts
- test/verify/check-system-shutdown-restart
PatternFly's DatePicker's textual date input defaults to ISO format
(YYYY-MM-DD), for a good reason: it's unambiguous, and localized date
input is really hard and brittle.
This is also broken for e.g. en-UK: British date format is DD/MM/YY,
while US date format is MM/DD/YY, but we don't have UI to switch between
English countries.
It was also broken for the manual time setting dialog, where the initial
formatting of the date resulted in a format that the dialog didn't
accept.
So give up, and use the default (i.e. ISO) format and parser. Also drop
the custom time/date format function in serverTime.js, and use our
standard `timeformat.dateTime()` (which has the same output format).
Fixes #19091
[1] https://www.patternfly.org/components/date-and-time/date-picker
-----
It previously looked …
> lib: Always use ISO format for date picker manual input

- pkg/base1/test-file.js
- pkg/lib/cockpit.js
- test/verify/check-users
> Use fsinfo for cockpit.file.watch()

- pkg/lib/cockpit.d.ts
These things take optional arguments to change their behaviour.
There is another issue in the binding that will be more difficult to fix: our non-standard promise type supports multiple arguments to the .then() callback.  We can't describe that using the `Promise` API which we've subclassed.  We leave that alone for now.
> cockpit.d.ts: fix some `cockpit.file()` annotations

- pkg/base1/test-timeformat.ts
- pkg/lib/timeformat.ts
- pkg/packagekit/updates.jsx
- pkg/sosreport/sosreport.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/test-util.js
- pkg/storaged/utils.js
- pkg/systemd/overview-cards/systemInformationCard.jsx
- test/verify/check-storage-mounting
- test/verify/check-storage-nfs
- test/verify/check-system-info
For technical reasons this also does some minor grammar changes on the  "Uptime" on the overview:
and in the "process/services which keep a block device busy". Before:
After:
See the commit descriptions for details, and the corresponding pixel ref changes.
Fixes #20653
Note: this does *not* yet drop date-fns from package.json. I'll do that as a follow-up after this lands, as node_module rebuilds bitrot in hours.
> Drop date-fns usage

- pkg/sosreport/get_report_dir.py
- pkg/sosreport/sosreport.jsx
- test/verify/check-sosreport
Debian/Ubuntu's sosreport package set `tmp-dir = "/tmp"` in the default
sos.conf. Our page previously hardcoded /var/tmp, thus it never showed any
existing report. This was hidden because our tests completely overwrote
sos.conf.
Fix this by reading the report directory from sos.conf. Update the test to only
selectively add our config options to the existing sos.conf instead of
completley stomping over it.
Factorize the test setup code to avoid duplication.
Fixes #19617
> sosreport: Read report directory from sos config

- test/common/run-tests
Often we debug a flake by running it multiple times in a row, to make this easier to do in CI `run-tests` can now supports `--amplify` which accepts the number of times the specified tests are repeated.
---
Tested locally, works nicely!
For example:
```
./test/common/run-tests --test-dir test/verify/ --amplify 5  TestConnection.testXdgConfig
```
> test: introduce `run-tests --amplify` for debugging

- test/verify/check-storage-anaconda
In our tests the format dialog opens while /mnt is still mounted, so ensure it is really unmounted before trying to create a partition table.
> test: wait till /mnt is properly unmounted

- test/verify/check-pages
This test flakes 27% of the time on Arch, as the test does wait until the DOM actually contains JSON data but only until the element is visible and another render might be needed to shown the actual JSON data.
---
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20686-bc16cfe9-20240701-160329-arch-expensive/log.html#40-2
Silly mistake by past me!
> test: wait till some json appears

- test/verify/check-system-info
It can take a few renders until the percentage is exactly bigger or equal to the new expected value.
---
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20671-cb251b6c-20240629-061927-centos-10-other/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20017-1db13b92-20240627-175830-centos-10-other/log.html
> Centos 10 timeout flakes

- .gitignore
- test/static-code
- tsconfig.json
Having `checkLib: false` in `tsconfig.conf` is a bad idea: it means that if we want to check `.d.ts` files, we need a separate invocation of the typescript compiler to do that.  It also means that `.d.ts` files won't be checked in your editor by default.  Our workaround for this in `test/static-code` only checks `cockpit.d.ts`, and we'll soon have other declaration files.
We've been using `checkLib: false` as a crutch to avoid reporting errors against `node_modules/`.  The relevant TypeScript issue is still unaddressed: https://github.com/microsoft/TypeScript/issues/30511
Modify `test/static-code` to only report errors if errors were found on something outside of node_modules, but in that case, report all errors. We do this with two invocations of `tsc`, to keep things simple, but we'll …
> test/static-code: tweak Typescript config again

- test/browser/browser.sh
- test/verify/check-system-journal
reportd has been orphaned for some time and got retired from Fedora rawhide. Stop trying to install it on Fedora > 40 in tmt.
Also flip the OS selection to a positive list, as that's small and will eventually shrink into nothingness.
[1] https://src.fedoraproject.org/rpms/reportd
----
See [recent rawhide failures](https://artifacts.dev.testing-farm.io/1800839a-98a3-49b3-ba64-07ad606f01db/). This is urgent as it also breaks external project tests like https://github.com/fedora-selinux/selinux-policy/pull/2209
> test: Restrict ABRT/reportd tests to Fedora 39/40

- src/pam-ssh-add/pam-ssh-add.c
- test/verify/check-session
Some distributions like Debian 12, or possibly some administrators enable pam_env's deprecated `user_readenv` option [1]. The user session can change the `$SSH_AGENT_PID`, so that it can pass an arbitrary pid to `pam_sm_close_session()`. This is a local authenticated DoS.
Avoid this by storing the agent pid in a global variable. The cockpit-session process stays around for the entire session time, so we don't need to put the pid into the PAM data.
It can also happen that the user session's ssh-agent gets killed, and some other process later on recycles the PID. Temporarily drop privileges to the target user so that we at least don't kill anyone else's process.
Add an integration test which checks that changing the env variable works, pointing it to a different process doesn't kill that, …
> pam-ssh-add: Fix insecure killing of session ssh-agent [CVE-2024-6126]

- pkg/systemd/overview-cards/ssh-list-host-keys.sh
Arch Linux compiles openssh with the default flags which now disables DSA keygen and thus listing / parsing now errors out.
Fix for https://github.com/cockpit-project/bots/pull/6570
---
Honestly a bit annoying that `ssh-keyscan` just errors out, maybe we should drop showing DSA keys in the future for older operating systems.
---
Side note: `ssh-keygen -l` can now read from stdin since [openssh 7.2](https://www.openssh.com/txt/release-7.2) and the ssh on RHEL 8 is new enough!
So: `ssh-add -L | ssh-keygen -l -f -` now works, but I didn't feel like removing tempfiles everywhere also as we invoke `ssh-keygen` for md5 and sha256.
> systemd: openssh 9.8 disabled DSA by default

- pkg/lib/cockpit.js
- test/browser/main.fmf
Commit 00d7e1dcac2a moved `cockpit.file().watch()` to use the `fsinfo` channel. But this is only available with cockpit-bridge >= 310. This breaks e.g. cockpit-podman which is supported on Debian stable, but also bundles cockpit.js via cockpit's pkg/lib.
Add back the fswatch1 implementation as a fallback if fsinfo is not supported.
----
This will unblock https://github.com/cockpit-project/cockpit-podman/pull/1779 . I tested it locally and it works fine. I triggered a test run against this PR in the podman PR, and it succeeded.
> cockpit.js: Add fsinfo fallback to fswatch1

- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-pages
- test/verify/check-static-login
- test/verify/check-storage-swap
- test/vm.updates-testing
- tools/debian/rules
See https://github.com/cockpit-project/bots/pull/6579
I locally went through all the failures and confirmed that they are working against the new image. I also triggered tests against that updated bots image, and they all passed.
> Adjust for dropping pcp and sssd from debian-testing

- pkg/systemd/overview-cards/ssh-list-host-keys.sh
Since OpenSSH 9.8 DSA support is not compiled in by default and since OpenSSH 7.0 DSA is already deprecated and not recommended. Don't show it anymore on the SSH host key dialog.
> systemd: don't show dsa host keys

- pkg/base1/test-timeformat.ts
- pkg/lib/serverTime.js
- pkg/lib/timeformat.ts
In commit 846552219 I got rid of the `ServerTime.format()` wrapper, and missed the `timeZone: "UTC"` option. This resulted in the Overview's "System time:" being wrong.
Bring this back, but as that is generally useful, introduce a `timeformat.dateTimeUTC()` helper and add a unit test.
Fixes #20710
> lib: Fix server time

- test/verify/check-client
We are introducing python3-pcp as new cockpit dependency in newer images for a Python implementation of the PCP channel. As this is a gradual rollout, handle python3-pcp being absent.
> test: handle optionally installed python3-pcp in beiboot test

- src/bridge/test-pcp-archives.c
- src/bridge/test-pcp.c
- src/ssh/test-sshbridge.c
json-glib dropped support [1] for single quote encapsulation of string values in JSON strings.
[1] https://gitlab.gnome.org/GNOME/json-glib/-/commit/c79df16fd2301f3448245387be56e69e390327f3
> unit-tests: fix json strings

- doc/protocol.md
- pkg/metrics/metrics.jsx
I can be convinced to change the protocol but not now while I am rewriting this into Python :)
```
[jelle@t14s][~/projects/cockpit/main]%cpf open metrics1 source="/tmp/disk" metrics='[{"name":"network.interface.total.bytes","derive":"rate","omit-instances":["lo"]}]
' limit=5  : wait | G_MESSAGES_DEBUG=none ./cockpit-pcp | /usr/bin/cat
36
{ "command": "init", "version": 1 }36
{"command":"ready","channel":"ch1"}188
ch1
{"timestamp":1597663539413,"now":1720517012231,"interval":1000,"metrics":[{"name":"network.interface.total.bytes","derive":"rate","instances":[],"units":"byte","semantics":"counter"}]}10
ch1
[[[]]]228
ch1
{"timestamp":1597663540413,"now":1720517012231,"interval":1000,"metrics":[{"name":"network.interface.total.bytes","derive":"rate","instances":["lo","eth0","eth1","virbr0","vi …
```
> Omit instances historical metrics

- test/verify/check-metrics
We are introducing python3-pcp as new cockpit dependency in newer images for a Python implementation of the PCP channel. As this is a gradual rollout, handle python3-pcp being absent.
---
https://github.com/cockpit-project/bots/pull/6586
> test: handle optionally installed python3-pcp in metrics test

- tsconfig.json
Our TypeScript config is setup to check our code that will be bundled and run in the browser.  It shouldn't be running on esbuild plugins that are run inside of node, and we never intended for it to. Unfortunately, we mix our esbuild plugins into pkg/lib/ alongside browser-based code, so it gets lumped in.
Add some excludes.  Fortunately, we don't have to copy this to other projects (like Cockpit Files) because they only check `src/*` in the first place (and only include files in other directories if they are explicitly imported).
> tsconfig.json: don't typecheck esbuild plugins

- test/common/testlib.py
- test/verify/check-system-info
On the recent Fedora 40 image refresh [1] the "admin" user has a past
login, which unexpectedly appears in the Health card as "Last logged in".
As that data is too unpredictable, wipe the lastlog database first.
[1] https://github.com/cockpit-project/bots/pull/6605
----
Plus a flake fix for [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6605-f678fe28-20240711-050210-fedora-40-devel-cockpit-project-cockpit/log.html), which is also on the weather report.
> test: Wipe lastlog db for TestSystemInfo.testBasic pixel test

- pkg/lib/cockpit.d.ts
For projects that import TypeScript modules from pkg/lib which reach into the _internal/ directory, all of those files get included in the compilation.  For projects that only import `'cockpit'`, though, the TypeScript compiler files our `cockpit.d.ts` and stops there.
Add a reference to tell it to pull in everything that `cockpit.js` imports.  This is needed to get the type declarations of the `.ts` files in `_internal/` — particularly the `window` augmentations in `common.ts`.
I tested manually making this change to cockpit-project/starter-kit#917 and it fixed the issues there.
> pkg/lib: add reference from cockpit.d.ts to cockpit.js

- pkg/apps/manifest.json
The apps content-security-policy allows more the our default policy which is unneeded as images are loaded via `fsread1` and thus the same origin.
---
Before
```
// default-src 'self'; connect-src wss://127.0.0.2:9091 'self'; form-action 'self'; base-uri 'self'; object-src 'none'; font-src 'self' data:; img-src *; block-all-mixed-content
```
After
```
// default-src 'self'; connect-src wss://127.0.0.2:9091 'self'; form-action 'self'; base-uri 'self'; object-src 'none'; font-src 'self' data:; img-src 'self' data:; block-all-mixed-content
```
> apps: drop custom content-security-policy

- test/verify/check-system-info
So this was legal? :exploding_head:  well ruff now detects this which is great!
> test: unexpected whitespace after decorator

- pyproject.toml
- test/pytest/conftest.py
- test/pytest/test_bridge.py
- test/pytest/test_peer.py
- test/pytest/test_transport.py
We've been long-ignoring a block of warnings at the bottom of our pytest output, mostly about various asyncio-related deprecations and churn.
Let's clean that up — it's distracting, and it makes it easier to miss legitimate issues when they arise.
> clean up pytest warning messages

- pkg/lib/cockpit-components-empty-state.jsx
- pkg/lib/cockpit.d.ts
- pkg/metrics/metrics.jsx
- pkg/networkmanager/networkmanager.jsx
- pkg/systemd/logsJournal.jsx
- pkg/systemd/service-details.jsx
- pkg/users/accounts-list.js
- test/verify/check-system-services
- test/verify/check-users
This changes the EmptyStatePanel action to a link by default, retaining the primary button where the action is almost always guaranteed to be clicked (starting networkmanager for example).
Adds an action to the user/groups emptystate:
Makes the logs `load earlier data` show a spinner after clicking:
[Screencast from 2024-07-15 16-30-12.webm](https://github.com/user-attachments/assets/65f1a8df-af09-44b6-8c6b-04025ce40939)
And further cleans up API usage, and a small typing improvement.
Empty state now shows a link
No logs found now shows:
> Allow EmptyStatePanel actions to be of a different variant

- pkg/lib/cockpit-components-inline-notification.tsx
These properties have a default setting so are not required.
---
Headsup this current change will affect all cockpit-lib updates tomorrow. See https://github.com/cockpit-project/cockpit-files/pull/659
> lib: isInline and isLiveRegion are wrongly typed

- test/common/testlib.py
- test/verify/check-pages
This isn't specific to CheckPages - any test which logs out relatively quickly
after logging in (and preloading the updates page) may run into this.
In particular, this happens quite often in TestAD.testUnqualifiedUsers.
----
This fixes this common failure:
- https://cockpit-logs.us-east-1.linodeobjects.com/pull-20772-0c309400-20240718-032729-fedora-39-networking/log.html#56
- https://cockpit-logs.us-east-1.linodeobjects.com/pull-20772-0c309400-20240718-032731-fedora-40-firefox-networking/log.html#56
That's the one and only unexpected message on the [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7).
> test: Generalize tracer failure message on logout

- test/verify/check-metrics
The current service image refresh [1] brings a new Grafana which changes the panel containers from `<div>` to `<section>`. Accept both.
Note: There is also a nested `<button>` with the same `data-testid` attribute, so we have to specify the tag name.
[1] https://github.com/cockpit-project/bots/pull/6644
> test: Allow different panel HTML elements in Grafana

- pkg/kdump/kdump-view.jsx
- test/verify/check-kdump
These should help with #20779 and the current [TestKdumpNFSAnsible crash](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7&test=test%2Fverify%2Fcheck-kdump+TestKdumpNFSAnsible.testBasic#).
> kdump fixes

- test/verify/check-metrics
The current service image refresh [1] brings a new Grafana which changes the panel containers from `<div>` to `<section>`. Accept both.
Note: There is also a nested `<button>` with the same `data-testid` attribute, so we have to specify the tag name.
[1] https://github.com/cockpit-project/bots/pull/6644
Cherry-picked from main commit ba7dc925050755
> [r8] test: Allow different panel HTML elements in Grafana

- test/common/testlib.py
The stricter checks introduced in commit 0b215006ec don't yet work on older cockpit Shell versions on debian-stable and ubuntu-2204. There the class is still called `.pf-c-modal-box__title`, and so the selectors don't match.
This also isn't important for this helper function. Leave the detailled dialog checks to TestSuperuser and pixel tests, and go back to just ensuring that the expected title text is somewhere in the dialog.
---
This fixes/unblocks https://github.com/cockpit-project/cockpit-machines/pull/1733
> test: Re-relax the `{become,drop}_superuser()` checks

- .github/workflows/unit-tests.yml
- test/common/testlib.py
- test/static-code
This unblocks https://github.com/cockpit-project/starter-kit/pull/937 . I validated that introducing a type error into starter-kit proper still fails as expected, but it's clean/passes with the lib update in that PR. I also validated that introducing a type error into cockpit's pkg/lib still fails.
While at it, I also fixed this:
```
❱❱❱ test/static-code 
not ok 6 /static-code/test-mypy
```
> test/static-code: Ignore pkg/lib for non-Cockpit projects; Ignore `machine.image_file` type check failure

- pkg/lib/patternfly/patternfly-5-overrides.scss
- pkg/metrics/metrics.scss
- pkg/shell/nav.scss
- pkg/systemd/overview.scss
- pkg/systemd/terminal.scss
We're supposed to have CSS related to the top level at the top anyway, but SASS is getting picky about it.
I've fixed the issues in the code, and this makes the SASS compiler happy with our SCSS.
This *shouldn't* change anything.
The warning from SASS was:
> ▲ [WARNING] Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in `& {}`.
> css: Shuffle some code around to make SASS happy

- doc/guide/authentication.xml
- pkg/shell/hosts.jsx
- pkg/shell/indexes.jsx
- pkg/shell/manifest.json
- pkg/shell/nav.scss
- test/common/testlib.py
- test/verify/check-shell-host-switching
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
- test/verify/check-static-login
Connecting to multiple remote machines within one Cockpit session and
executing arbitrary JavaScript from them means that connecting to an
untrustworthy machine can do arbitrary damage to *all other* connected
machines. [1][2][3]
For many years, nobody has found a solution how to isolate the per-host
iframes from one another with still being authenticated "enough" to get
reliably mapped to a particular session and remote host, and it's
currently deemed impossible.
To avoid this, gradually phase out the shell's host switcher. Start with
disabling the host switcher in current development releases (Fedora,
RHEL 10, Debian testing, Arch, and so on), but keep it enabled in stable
long-term supported releases (RHEL 9, Debian 12, Ubuntu 22.04/24.04
LTS). Use our manifest `config` mechanism for …
> shell: Deprecate host switcher in current OS releases

- pkg/systemd/logDetails.jsx
- pkg/systemd/logs.jsx
- pkg/systemd/logs.scss
This is what the fix looks like:
(The labels are now properly aligned.)
> Logs : Fix label alignment

- pkg/shell/manifest.json
- test/common/testlib.py
We don't want to change behavior for released OSes.
> shell: Enable host switcher also on Fedora 40

- pkg/base1/test-http.js
- pkg/systemd/terminal.jsx
- src/cockpit/channel.py
- src/ws/test-server.c
- test/verify/check-system-terminal
Terminals are not defined/required to be UTF-8 only. Sometimes people
cat binary data to the terminal, or possibly files in other encodings.
These cannot be sent through `TEXT` websocket channels, and will also
trigger the additional checks from commit 1b15dcb94fe834.
Use a binary channel to avoid all that. XTerm.js gets along with this
just fine, and it ignores invalid data.
With this you can now even `cat /bin/true` and get something moderately
sensible, instead of no output at all.
Fixes #20791
> systemd: Use binary channel for Terminal

- configure.ac
- doc/guide/authentication.xml
- doc/man/cockpit.conf.xml
- pkg/shell/indexes.jsx
- pkg/shell/manifest.json
- src/ws/cockpitchannelresponse.c
- src/ws/cockpithandlers.c
- test/common/testlib.py
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine-key
- tools/cockpit.spec
- tools/debian/rules
We will want to refer to that setting in more places than the shell, so it's good to be prepared for that. At least the login page will also need it.
The default for the setting is now a ./configure option, with a default default of "host switcher is off".
> hosts: Use a cockpit.conf option to disable the host switcher

- test/common/test-functions.js
webdriver's and BiDi's functions for preloading a script only supports declaring and calling a function. This can't define globals.
So do what sizzle does and put the helper functions on the `window` global object. 
Drop the long-obsolete jQuery comment.
---
https://github.com/cockpit-project/bots/pull/6688 already landed for not breaking naughty patterns.
This is a prerequisite for #20832
> test: Put test-functions.js helpers on window object

- test/common/testlib.py
- test/verify/check-client
- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-ws-bastion
With the webdriver and BiDi APIs you have to set the "bad SSL certificate" policy at the browser instantiation time, and can't switch at runtime (not even through the CDP protocol).
We don't have any "real" browser test for denying a bad SSL certificate -- `check-connectinon` does that with `curl`, and otherwise we are not testing how browsers configure SSL trust. So just implicitly ignore bad SSL certificates.
This is formally an API break, but no external project uses that API.
---
Plus a few random test cleanups which I came across in #20832.
This is a prerequisite for #20832.
The advantage of this: Once we port this over to bidi, we can enable all the skipped TestConnection for firefox, as that works there as well. The CDP command never did.
> test: Make ignore_ssl_certificate_errors() implicit; some small test fixes

- test/verify/files/mock-insights
This forwards various updates to `mock-insights` as done in subscription-manager-cockpit, where it is stressed/used a bit more; in particular, the changes come from:
- https://github.com/candlepin/subscription-manager-cockpit/pull/66 (one commit)
- https://github.com/candlepin/subscription-manager-cockpit/pull/72 (all the commits)
This should hopefully avoid failures in case `insights-client` (or better, insights-core) switches the default value of `legacy_upload` from true to false; no ETA planned for that, although that's what we are trying to work on.
See the message of each commit for longer explanations.
> tests: updates of mock-insights from subscription-manager-cockpit

- pkg/shell/hosts.jsx
- pkg/shell/indexes.jsx
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-os
- test/verify/check-superuser
- test/verify/check-system-realms
- test/verify/check-system-shutdown-restart
Cockpit should either not connect to remote machines at all, or trust the user to do it right.  Also, the better place to explain the security implications of connecting to remote hosts is when actually connecting.
> shell: Remove the "half-off" mode of the host switcher

- test/verify/check-packagekit
Improve the registration using subscription-manager to setup things better, and switch to SCA (which will be the only option soon).
First, ensure that subscription-manager is configured so that the package manager can properly receive content from the repositories of the self-deployed Candlepin. This should have been done in the past, and it will be critical for switching to SCA for testing: in SCA mode, all the content of the organization is available by default, and some repositories are also automatically enabled. This means:
- installing the GPG key for RPM packages
- setting the `baseurl` in `rhsm.conf`
Second, set the server details using `subscription-manager config` during the test setup, so it matches more what is the recommended procedure, and it makes the registration command …
> test: improve subscription-manager handling & registration

- containers/flatpak/prepare
The machine told me so! See
https://github.com/flathub/org.cockpit_project.CockpitClient/pull/45
> flatpak: Drop default-branch property from manifest

- test/verify/check-kdump
See https://github.com/cockpit-project/bots/pull/6706 and the discussions with the kdump maintainer. This fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6706-f3e62d04-20240808-042120-fedora-40-firefox-expensive-cockpit-project-cockpit/log.html).
- commit 5b3ec7b3ecc01a2a3b : merely waiting longer for the initrd to build [fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20850-5b3ec7b3-20240808-120154-fedora-40-expensive-bots%236706/log.html)
- commit 3409fca02e59995f1f0 : rebuilding initrd with verbosity [still fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20850-3409fca0-20240808-125857-fedora-40-expensive-bots%236706/log.html)
- commit dad395a43e88c4: Increase RAM for kdump machine from 1024 to 1280 MiB: [better, but still …
> Fix TestKdumpNFSAnsible with current Fedora 40

- pkg/shell/hosts_dialog.jsx
Passing more than one child to ClipboardCopy seems to introduce them, let's just pass a single string.
> shell: Avoid spurious commas in ssh-keyscan command example

- src/cockpit/channel.py
- src/cockpit/transports.py
- test/pytest/test_transport.py
The standard Python asyncio Transport classes protect their caller from having to deal with exceptions when calling .write().  In case an exception does occur, they capture it and close the transport, passing the exception on to the connection_lost() handler.  This makes it a lot easier to interact with the transport: because OS-level errors are handled out of band, protocols don't have to consider that any write might fail.
Our Transport classes do the same thing, but there's an important difference: the standard library defers the call to .connection_lost(), but our transports invoke it immediately.
This creates a weird scenario whereby your connection_lost() handler can get called in the middle of your connection_made() handler, if you should happen to do a .write() there which fails. …
> bridge: call connection_lost "soon"

- test/common/testlib.py
- test/common/webdriver_bidi.py
- test/verify/check-connection
- test/verify/check-selinux
- test/verify/check-shell-multi-machine-key
- test/verify/check-system-realms
- test/verify/check-system-terminal
This will fix https://github.com/cockpit-project/cockpit-ostree/pull/679 and https://github.com/cockpit-project/cockpit-machines/pull/1761
> BiDi follow-ups

- pkg/lib/cockpit-components-terminal.jsx
On initializing the page there can be a short time window when the
terminal's CSS cell size is already set, but the parent element's
`client{Width,Height}` are still zero. In that case,
`calculateDimensions()` returned a negative rows/cols, which caused a
bridge crash:
```
fcntl.ioctl(self._pty_fd, termios.TIOCSWINSZ, struct.pack('2H4x', size.rows, size.cols))
struct.error: 'H' format requires 0 <= number <= 65535
```
Avoid that by checking the parent sizes and falling back to the explicit
state while any of the values is still uninitialized.
----
[This test fails all the time now](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-b5a98be3-20240812-013044-fedora-40-daily/log.html#153),  since end of last week. Probably triggered by #20841 , but that was just accidental. let's find …
> lib: Fix race condition in Terminal size calculation

- test/browser/run-test.sh
Although we've generally tried to keep our "not on rhel8" decorators around for when we get tests working there again in our CI (via beiboot), running on testing farm will probably never come back, since we can't install RPMs there anymore.
Drop the special-casing for it — it's dead code and likely to forever remain that way.
> tmt: drop special-casing for RHEL 8

- test/common/testlib.py
- test/common/webdriver_bidi.py
This PR is a bit lame, but I don't want to forget about it. I was originally trying something else -- Chromium [supports sending CDP commands directly through the BiDi protocol](https://github.com/GoogleChromeLabs/chromium-bidi?tab=readme-ov-file#bidi), which is cool -- until you try to use it. Some commands work fine, but some like `Emulation.setUserAgentOverride` just fail with "wasn't found" :cry: 
For posterity:
```diff
diff --git test/common/testlib.py test/common/testlib.py
index 1390fdb53..e8ae98c46 100644
--- test/common/testlib.py
+++ test/common/testlib.py
@@ -313,22 +313,19 @@ class Browser:
self.bidi_thread.join()
self.valid = False
-    def bidi(self, method: str, **params: Any) -> webdriver_bidi.JsonObject:
+    def bidi(self, method_name: str, **params: Any) -> …
```
> Two CDP fixes

- build.js
- pyproject.toml
- test/common/lcov.py
- test/common/testlib.py
- test/common/webdriver_bidi.py
- test/pytest/test_browser.py
This was part of #20731 (inspired by @martinpitt's coverage-related comments there), but that PR got too big, so let's land these separately.
We need to figure out if we want this included in the overall coverage picture, and if so, find a way to make it happen.  That probably looks something like an extra `test_browser` run from `run-tests` if we're in coverage mode.  It's a bit of a weird fit, but I guess that's part of figuring out if we want to do this or not...
> add coverage output for qunit tests

- pkg/packagekit/updates.jsx
- test/README.md
- test/browser/main.fmf
- test/common/storagelib.py
- test/image-prepare
- test/ostree.install
- test/verify/check-connection
- test/verify/check-networkmanager-settings
- test/verify/check-networkmanager-wireguard
- test/verify/check-packagekit
- test/verify/check-shell-multi-machine
- test/verify/check-ws-bastion
The package was just dropped from RHEL 10 [1], see https://issues.redhat.com/browse/RHELBLD-15667
[1] https://gitlab.com/redhat/centos-stream/rpms/tracer/-/commit/513b244618e63630
Also drop obsolete rhel4edge special cases.
----
This needs to land in lockstep with https://github.com/cockpit-project/bots/pull/6739
> test: Drop tracer support from CentOS/RHEL 10

- pkg/base1/test-file.js
- pkg/lib/cockpit.d.ts
- pkg/lib/cockpit.js
- pkg/users/authorized-keys.js
We call iterate_data() on whatever the user passed to us, but this function will make zero callbacks if the string is empty.  That's a problem, because the fsreplace1 channel interprets this as a request to delete the file.
If we have an empty string, then send the empty string to make sure we end up with an empty file.  Also treat the `null` case more explicitly (and add a type annotation for it: we missed that before).
Add a test case too.
> cockpit.js: fix cockpit.file().replace('')

- pkg/static/login.js
- src/ws/cockpitauth.c
- src/ws/cockpitauth.h
- src/ws/cockpithandlers.c
- test/verify/check-embed
unless allowed by cockpit.conf.
If the login page is loaded and a valid session cookie is already available, then we are about to log into a second host from the same browser session, and both logins will have access to each others cookies. This should only be allowed when AllowMultiHost is true. If it is not true, the login page immediately redirects to the session for the existing cookie.
Information about session cookies is not available to login.js, so cockpit-ws helps out by exposing which ones are present, without exposing the cookies themselves.
> login: Prevent multiple logins in a single browser session

- packit.yaml
Testing Farm does not yet have a Fedora 41 image.
Also move the Fedora aarch64 run to the latest stable. Right now this will go back to Fedora 40 instead of 41, so that we don't lose ARM testing.
----
We have F41 enabled in other projects, we'll notice when it starts working.
> packit: Temporarily disable Fedora 41 tests

- test/common/testlib.py
`Browser.input_text()` is not generally meant for non-ASCII characters (that's `Browser.key()`). But a newline is such a common case that it's worth handling it speciallly.
This was originally introduced in commit d3632786a1602b5 but I missed that in the BiDi conversion in commit 0ec830da3dbda7.
---
This will fix https://github.com/cockpit-project/cockpit-files/pull/509
> test: Re-teach Browser.input_text() about \n

- test/common/testlib.py
- test/common/webdriver_bidi.py
Addresses a late comment from @mvollmer in https://github.com/cockpit-project/cockpit/pull/20832#pullrequestreview-2234962385
> test: support Arch Linux's chromium binary name in BiDi, Don't change context in WebdriverBidi.restore_context()

- src/systemd/cockpit-ws-user.service
cockpit-ws-user.service does nothing except calling `true`, so it does not have any actual dependencies. Drop the implicit `basic.target` dependency so that the running unit can be shut down cleanly.
Previously, this caused a dependency loop, which systemd resolved in an unhappy way:
> basic.target: Job cockpit-ws-user.service/stop deleted to break ordering cycle starting with basic.target/stop
> basic.target: Found dependency on basic.target/stop
> basic.target: Found dependency on sockets.target/stop
> basic.target: Found dependency on cockpit-wsinstance-https-factory.socket/stop
> basic.target: Found ordering cycle on cockpit-ws-user.service/stop
Fixes #20914
> systemd: Relax cockpit-ws-user.service dependencies

- pkg/lib/cockpit.d.ts
The callback can also return `null` to delete the file.
---
This will unblock https://github.com/cockpit-project/cockpit-files/pull/714
> lib: Fix cockpit.file().modify() annotation

- pkg/base1/test-file.js
Add some extra tests to make sure that `null` returned from a modify() callback will result in a deleted file whereas "" will result in an empty file.
> pkg: add qunit tests for modify() "" vs null

- test/common/testlib.py
cockpit-podman uses this. Conceptually this is strange, as mouses don't have a "context menu" button -- they have a right button (aka `btn=2`). But this does not work with `ph_mouse()`, so translate it to a right click.
---
no-test, as we don't use "contextmenu" anywhere in the cockpit tests. But we do in c-files, and this will unblock https://github.com/cockpit-project/cockpit-files/pull/714 . I tested this change locally, and it fixes the tests.
I also updated https://github.com/cockpit-project/cockpit-files/pull/714 to pull in this PR, to get a test run.
> test: Implement "contextmenu" mouse event for BiDi

- test/verify/check-session
The man page says:
user_envfile=filename
Indicate an alternative .pam_environment file to override the
default. The syntax is the same as for
/etc/security/pam_env.conf. The filename is relative to the user
home directory. This can be useful when different services need
different environments.
The Debians also accept the "VAR=VALUE" syntax, but the Fedoras and RHELs seem to behave erratically with it.
> test: Use documented syntax for pam_env

- packit.yaml
Testing Farm has a working image now.
Partially reverts commit e0012e909
> packit: Re-enable Fedora 41

- test/verify/check-kdump
We have a better theory now of how kdump works and especially what crashkernel means, and increasing the physical RAM of a machine is not expected to help with growing initramfs sizes.
It _did_ help, for mysterious reasons, but not totally reliably. So let's revert this, save some RAM, and wait for a real fix.
See https://bugzilla.redhat.com/show_bug.cgi?id=2305968
This reverts commit 3fb39bbb91a64a92dbd8073a168bbfab737dc856.
> Revert "test: Increase RAM for TestKdumpNFS machine"

- src/build_backend.py
We use os.walk() to list files on the filesystem which may be interesting for including in our sdist, wheel, and beipack.  This returns the list of a files in a non-deterministic order.
Before we add the files to the sdist or the wheel (which the beipack is built from), make sure to sort the list.
Issue originally discovered by Martin in https://github.com/cockpit-project/cockpit/pull/20939
I verified the fix using disorderfs.
> src/build_backend: sort file list for archives

- src/cockpit/channels/metrics.py
The same should be done for `metrics`, use `get_objv` but this was a drive by fix :)
FYI: Type is Python 3.9 only, are we that modern already? :sweat_smile:
> Metrics use json helper

- test/verify/check-storage-luks
Stop hardcoding the interface name and detect it dynamically. More OSes (rhel-10-0 right now) are switching to systemd interface naming.
----
This will fix the cockpit failure in https://github.com/cockpit-project/bots/pull/6796
> test: Determine TestStorageNBDE tang iface dynamically

- test/common/testlib.py
We are currently transitioning ubuntu-stable from 24.04 to 24.10 [1], we need to handle `MachineCase.multihost_enabled` depending on which actual Ubuntu version the currently booted ubuntu-stable has. Otherwise we'll end up in a web of PR cross-dependencies.
[1] https://github.com/cockpit-project/bots/pull/6799
---
I copied this to cockpit-machines and a build with the 21.10 version of ubuntu-stable, and it makes the test pass.
> test: Temporarily make self.multihost_enabled dynamic for ubuntu-stable

- HACKING.md
- build.js
- pyproject.toml
- test/common/js_coverage.py
- test/pytest/conftest.py
- test/pytest/test_browser.py
- tools/vulture_suppressions/testlib.py
You can now do something like this:
```
$ pytest -k test_browser
$ test/common/coverage.py -m '*/fsinfo.ts' /tmp/pytest-of-lis/pytest-current/coveragecurrent/*
```
and get results like this:
```
pkg/lib/cockpit/fsinfo.ts:33:49-33:63 json_merge
▼ from here
33         const updated = is_json_dict(current) ? { ...current } : { };
▲ to here
pkg/lib/cockpit/fsinfo.ts:36:33-38:14 json_merge
▼ from here
36             if (value === null) {
37                 delete updated[key];
38             } else {
▲ to here
```
Since we also use the same approach for collecting data for integration tests (Profiler.takePreciseCoverage), we could easily add support there as well.
> qunit: add support for precise coverage reporting

- test/verify/check-static-login
coreutils with systemd session support and the latest fix [1] show the service name instead of the session type in `who`. Adjust the test to accept either.
Also see https://bugzilla.redhat.com/show_bug.cgi?id=2307847
[1] https://git.savannah.gnu.org/cgit/gnulib.git/commit/?id=43f7f428a1665950233557bd97611bd5e996b5cb
----
I locally tested https://bodhi.fedoraproject.org/updates/FEDORA-2024-17516d6499 in a rawhide image, and it passes now. It's not yet visible in a compose, but Testing Farm is using the tag repo, so there's actually a chance that this passes now (I don't know how aggressively it `dnf update`'s)
> test: Adjust TestLogin.testBasic for current coreutils

- pkg/packagekit/updates.jsx
Manual testing has found that the package data these days is probably formatted and only contains urls.
> packagekit: drop bugs/cve_urls workaround

- test/verify/check-users
Mysteriously on Fedora-41 this test flakes and fails showing an image of the users page wich makes it seem `b.go()` failed. Work around this flake by directly opening the users page.
---
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20947-89446677-20240827-131830-fedora-41-other/log.html#142
https://cockpit-logs.us-east-1.linodeobjects.com/pull-6790-ab78a2e9-20240826-100045-fedora-41-other-cockpit-project-cockpit/log.html#142
> test: navigate to the admin page directly

- test/verify/check-pages
The file component apparently has some state issues when we first set it and then drop privileges. This can be easily reproduced on fedora-coreos by inserting a sleep()
```
b.set_file_autocomplete_val()
import time
time.sleep(5)
b.drop_superuser()
```
Workaround the flake by first dropping privileges and then selecting the directory.
---
This occurs ~ 30% on coreos.
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20950-60f3a41a-20240829-111721-fedora-coreos-expensive/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-6805-b81a66de-20240828-124745-fedora-coreos-expensive-cockpit-project-cockpit/log.html#39
> test: drop privileges and then try to upload to /root

- src/common/cockpitwebresponse.c
- src/common/cockpitwebresponse.h
- src/common/test-webresponse.c
- src/ws/cockpitauth.c
- src/ws/cockpithandlers.c
- src/ws/test-auth.c
- test/verify/check-static-login
- test/verify/check-system-realms
If we fail a login attempt in response to receiving a
```json
{ "command": "init", "problem", "..." }
```
control message from the session program, then return the message in full as the result text for the /login page.
This makes use of an until-now dead code path in cockpithandlers that pretty-prints and sets JSON data as the body of the GET /cockpit/login result if it's returned from cockpit_auth_login_finish().  Previously we were returning a fancy fail.html-formatted page which the XHR request in login.js was simply ignoring.
Going forward, this will allow us to forward more interesting errors to the login page.
Adjust the auth tests to expect the response blob in the cases where it's relevant instead of always expecting NULL on the error path.
> ws: use the failing "init" message as /login result

- pkg/storaged/client.js
- test/verify/check-storage-btrfs
Podman btrfs subvolumes are an implementation detail of podman and not interesting for a Cockpit user in the storage page.
Closes: #20912
> storaged: filter podman btrfs subvolumes

- test/verify/check-users
Instead of logging in, loading the users page and then switching the url to the account detail page directly browse to the detail page.
Follow up of 5868d8812b6f58fad6a5c6476ea57accf73ee3d1
> test: navigate to the correct page directly

- pkg/selinux/setroubleshoot-view.jsx
This property has been removed from PatternFly 6 with as reasoning that a label should always convey the value when the checked state is true and should not change based on the selection state.
https://github.com/patternfly/patternfly/issues/6347
Relates: #20973
> selinux: remove deprecated labelOff property of a Switch

- pkg/storaged/stratis/create-dialog.jsx
- pkg/storaged/stratis/filesystem.jsx
- pkg/storaged/stratis/pool.jsx
- test/common/storagelib.py
- test/verify/check-storage-stratis
Instead of the "Managed filesystem sizes" concept. This makes Cockpit
easier to discover when you know the real Stratis concepts and exposes
its full capabilities.
Demo: https://youtu.be/E1zqhAowus8 
Longer exploration: https://youtu.be/1W6QPNPwT7Q
> storage: Expose Stratis virtual filesystem sizes

- test/verify/check-storage-anaconda
losetup cannot clean up an active mdadm array when the test fails so always clean it up when needed.
---
Now the test can at least be retried safely.
> test: stop active mdadm array when test fails

- HACKING.md
Make the session pages section easier to follow by telling the user to build the pages before giving the address to see the changes. Also, divide the section with subheaders to make it more ovbious to install the Cockpit server before trying to build and connect.
> HACKING.md: Clarify installation

- pkg/lib/patternfly/patternfly-5-overrides.scss
- pkg/systemd/overview.scss
- test/verify/check-metrics
This drops a tiny part of our overrides.
> Drop old pf overrides :broom: 

- test/browser/browser.sh
- test/verify/check-metrics
- test/verify/check-system-journal
We longer test on Fedora-39, as we test on 40 and 41.
> test: drop Fedora-39 from tests

- pkg/lib/service.js
- test/common/webdriver_bidi.py
- test/verify/check-metrics
Latest Grafana started to use zone.js [1], which completely replaces the
global `Promise` class with a custom implementation. This doesn't
serialize well through WebDriver, and completely breaks the
`awaitPromise` mode of script evaluation. In other words, this breaks
all our `Browser.wait*()` methods.
So rewrite the Grafana part of `TestGrafanaClient` to use Python-level
polling, and use the old JS-layer mouse click emulation (as the HTML
Element result from `ph_find_scroll_into_view()` also isn't accessible).
See https://github.com/cockpit-project/bots/pull/6838
[1] https://github.com/angular/zone.js
---
Plus a few small fixes.
> test: Rewrite TestGrafanaClient without relying on Promise

- src/cockpit/channels/metrics.py
The work in progress PCP implementation uses similar copy of this function and uncovered an issue when `{ "derive": "rate" }` is passed. Compared to the C implementation it would return [False, False, 1.0] instead of [False, 1.0, 1.0]. As last_timestamp had to change from 0 to something truthy.
This check was in essence unneeded as `x - 0` is always safe. As the PCP Python port drops this condition, drop it here as well.
> cockpit: metrics: remove unneeded last_timestamp check

- src/bridge/Makefile.am
- src/bridge/pmlogconf/cockpit
- tools/cockpit.spec
- tools/debian/cockpit-pcp.install
The pmlogconf file for Cockpit contained all the metrics we required on the metrics page but got out of sync for a while now.
The default metrics PCP seems to collect are in
/var/lib/pcp/config/pmlogger/config.default which contains all the metrics we request.
---
Important to note that this seems to come from the `pcp` package so we need to check for this and `python3-pcp` on the metrics page. (pcp is also needed for pmlogger ofcourse)
> bridge: stop installing our custom PCP log configuration

- test/verify/check-connection
I see this on every test run:
WARNING: Waiting for ph_is_visible(".curtains-ct") took 59.0 seconds, which is 98% of the timeout.
The time it takes for the health check to fail seems to be pretty consistent, so this isn't really a flake. But still, we shouldn't cut it this close, I'd say.
> test: Wait longer for health check to fail

- pkg/lib/cockpit/_internal/transport.ts
Control messages are logged in the other if conditional and with this patch we log:
transport.ts:29 recv text message: 2:2!3 [[675520512.0]]
Instead of:
transport.ts:29 recv text message: null [[675520512.0]]
> lib: cockpit: log channel instead of control

- .github/workflows/flatpak-test.yml
- containers/flatpak/Makefile.am
- containers/flatpak/prepare
The new Sdk drops the old appstream-util command for favour of appstreamcli, so move to using it to validate our files.
Fixes https://github.com/flathub/org.cockpit_project.CockpitClient/issues/46
> flatpak: bump GNOME depend to 47

- doc/anaconda.md
- doc/branding.md
- doc/login.md
- doc/protocol.md
- doc/urls.md
Replace tabs with spaces, and use proper Markdown verbatim syntax.
Mark the JSON and CSS code blocks as such for proper syntax highlighting and inline editor validation, and fix the various comma and quoting errors.
----
Rendered views:
- https://github.com/martinpitt/cockpit/blob/doc-formatting/doc/anaconda.md
- https://github.com/martinpitt/cockpit/blob/doc-formatting/doc/branding.md
- https://github.com/martinpitt/cockpit/blob/doc-formatting/doc/login.md
- https://github.com/martinpitt/cockpit/blob/doc-formatting/doc/protocol.md
- https://github.com/martinpitt/cockpit/blob/doc-formatting/doc/urls.md
> doc: Fix formatting

- containers/flatpak/test/test-browser-login-ssh.js
- doc/authentication.md
- pkg/static/login.js
- src/cockpit/beiboot.py
- test/browser/run-test.sh
- test/verify/check-client
- test/verify/check-static-login
In order to use cockpit-beiboot as cockpit-ssh replacement from the "normal" (not Client mode) login page, it needs to consider the given username and password. It also needs to properly handle "unknown host key" prompts.
This paves the way for completely replacing cockpit-ssh with cockpit.beiboot. See https://issues.redhat.com/browse/COCKPIT-954 and #19441.
> beiboot: feature parity with cockpit-ssh

- src/ws/cockpitchannelresponse.c
- test/verify/check-shell-multi-machine
When AllowMultiHost is false, cockpit-ws will reject all GET requests that would load from a non-localhost bridge.
> ws: Conditionally block channel requests to remote hosts

- pkg/pcp/manifest.json
- pyproject.toml
- src/cockpit/channels/__init__.py
- src/cockpit/channels/pcp.py
- test/browser/main.fmf
- test/common/testlib.py
- test/pytest/test_bridge.py
- test/pytest/test_pcp.py
- test/verify/check-connection
- test/verify/check-metrics
- tools/arch/PKGBUILD
Current ToDo's
---
Follow ups, I'd suggest tackling:
> cockpit: Implement PCP metrics channel in the Python bridge

- containers/ws/README.md
- containers/ws/cockpit-auth-ssh-key
- test/verify/check-ws-bastion
This PR adds the ability to set host-specific ssh keys via env-var in the cockpit-ws container.
Users can pass environment variables in the format of `COCKPIT_SSH_KEY_PATH_{HOSTNAME}`, where `HOSTNAME` is the hostname used in the `Connect to` field of the cockpit login page, and cockpit will use the configured key to login to the host. If no host-specific key is set, it falls back to using the `COCKPIT_SSH_KEY_PATH` environment variable.
I still need to make a unit test, but I wanted to ask for suggestions as to the best route. The [cockpit bastion test](https://github.com/cockpit-project/cockpit/blob/f071d8cd2a20b309dae72392a7a49223d2aaa3c1/test/verify/check-ws-bastion#L162-L219) could be replicated, or it could be refactored to test host-specific keys. I wasn't sure what the best …
> containers/ws: Support host-specific ssh keys

- test/verify/check-networkmanager-basic
This is emitted by the C bridge which is no longer in use.
---
Should go green, but let's see :crossed_fingers:
> test: drop cockpit-pcp specific journal allow

- HACKING.md
- doc/protocol.md
- pkg/lib/cockpit-components-file-autocomplete.jsx
- src/cockpit/channels/filesystem.py
- test/verify/check-shell-keys
> Deprecate fslist1 channel

- .github/workflows/codeql.yml
- doc/guide/feature-machines.xml
- selinux/cockpit.te
- src/common/preload-temp-home.c
- tools/arch/PKGBUILD
Cleanup after #19441. In particular, drop the dependency in the Arch packaging.
> Drop remaining libssh references

- containers/ws/README.md
- containers/ws/cockpit-auth-ssh-key
- containers/ws/install.sh
- test/ostree.install
- test/verify/check-ws-bastion
This provides similar functionality as the Client, so that the ws
bastion container can connect to machines which don't have any Cockpit
packages installed.
Install cockpit-system and cockpit-networkmanager into the container for
now. We'll likely expand this in the future, but let's start small.
https://issues.redhat.com/browse/COCKPIT-954
---
The [quay.io/cockpit/ws](https://quay.io/repository/cockpit/ws)  container provides Cockpit's web server in environments such as Kubernetes or [Fedora CoreOS](https://fedoraproject.org/coreos/). It connects to a destination machine via `ssh`.
Similarly to what the [Cockpit Client flatpak](https://flathub.org/apps/org.cockpit_project.CockpitClient) supports [since release 295](https://cockpit-project.org/blog/cockpit-295.html), that container can …
> containers/ws: Enable beibooting and install standard cockpit pages

- pkg/lib/cockpit-components-table.scss
Was fixed in https://github.com/patternfly/patternfly/pull/4529
Testing in:
> lib: drop nested table PatternFly workaround

- pkg/networkmanager/ip-settings.jsx
This was introduced in 234a6672af, where the IpSettingsDialog got ported to React and PF4. This now started to flake on ubuntu-stable, where the dialog is closed in the tests just after it was opened.
---
Amplified here, and it does fail a ton :) https://github.com/cockpit-project/cockpit/pull/20692
I accidentally fixed up this `preventDefault` and then it didn't reproduce anymore in commit https://github.com/cockpit-project/cockpit/pull/20692/commits/5828f45aece9ed878231b459c033e0266807b1e2
> networkmanager: drop preventDefault code

- pkg/storaged/btrfs/btrfs-tool.py
- pkg/storaged/btrfs/filesystem.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/btrfs/volume.jsx
- pkg/storaged/client.js
- pkg/storaged/crypto/actions.jsx
- pkg/storaged/dialog.jsx
- pkg/storaged/filesystem/mismounting.jsx
- pkg/storaged/utils.js
- test/verify/check-storage-anaconda
- test/verify/check-storage-btrfs
- test/verify/check-storage-luks
This reduces the roundtrips and allows us to maintain "temporary" mount points for btrfs filesystems that are not otherwise mounted.
The process will be shutdown when the cockpit session is closed by cockpit-ws, so we get reliable cleanup.
Fixes #20855
Demo: https://youtu.be/aNsdXtHnUUM
Anaconda demo: https://youtu.be/EM-qqogOt6g
> storage: Reimplement btrfs polling with benefits

- test/verify/check-system-realms
x0.cockpit.lan is the name of the local machine, but specifying it with login_and_go will navigate to it as a remote host, using a URL like
https://127.0.0.2:9091/@x0.cockpit.lan
This is not needed since the test only wants the session on localhost, and doesn't care what happens inside the session. It would be harmless except that Cockpit might spontaneously open the "Add host" dialog for "x0.cockpit.lan", which will make the session menu inaccessible for the subsequent logout. (Only on Firefox, Chrome manages to open it anyway.)
> test: Don't explicitly go to x0.cockpit.lan in TestIPA

- pkg/Makefile.am
- pkg/metrics/metrics.jsx
- pkg/pcp/manifest.json
- src/cockpit/channels/pcp.py
- test/common/testlib.py
- test/verify/check-client
- test/verify/check-metrics
- tools/arch/PKGBUILD
- tools/cockpit.spec
- tools/debian/cockpit-pcp.install
- tools/debian/control
- tools/debian/rules
Throwing this at CI, this still needs:
* Obsoletes/replaces of cockpit-pcp?
* Drop pkg/Makefile.am changes as they go in #20000
> Cockpit pcp python follow up

- test/common/testlib.py
The new Shell will not render the ".curtains-ct" element at all when it shouldn't be shown.
> test: Prepare for Shell rewrite

- test/verify/check-client
- test/verify/check-metrics
All our rpm based images should have python3-pcp by now.
> test: pcp: remove conditionals for python3-pcp

- pkg/lib/cockpit-components-file-autocomplete.jsx
- test/verify/check-shell-keys
This reverts commit 03fcd561ac30f716cca945d844bd93ad6b33363a.
The "fsinfo" channel does not work on rhel-8-10.
> Revert "lib: Port cockpit-components-file-autocomplete.jsx to fsinfo"

- tools/debian/rules
This line was introduced in 112ce31a06de and we can just as well remove it again.
> tools/debian/rules: remove unnecessary variable

- pkg/metrics/metrics.jsx
- src/cockpit/samples.py
use `mount.total` and `mount.used` from internal metrics instead of parsing `df` output.
> metrics: collect disk usage from internal metrics

- pkg/storaged/dialog.jsx
- pkg/storaged/stratis/pool.jsx
- test/verify/check-storage-stratis
Clean up the dialog changes from commit 236ffd3fb612 as per [1]:
- Visually merge both options into "Stratis filesystem" and avoid extra top-level labels.
- Point out that the sizes are Stratis specific, as it doesn't say anywhere else in the dialog.
- Remove redundant "virtual filesystem" words in the options
- Avoid "Manage", pretty much all of Cockpit is "managing" something.
[1] https://github.com/cockpit-project/cockpit/pull/21039#issuecomment-2373963643
----
The default dialog now looks like this:
The checkbox separation is a bit awkward -- that's a result from them now being two separate components, instead of a single  group. I tried for about half an hour to mess around with the CSS, but I can't even find the knob which does the flex component spacing. The more obvious ones are …
> storaged: Adjust stratis fs limits layout in creation dialog

- tools/debian/control
The cockpit-pcp replacement really happened in cockpit-bridge, not the "cockpit" metapackage. The latter isn't always installed.
It's the users page in cockpit-system which reads lastlog2, not the bridge, so move the Suggests: accordingly.
---
I already did these changes downstream in Debian while packaging 326.
> debian: Fix cockpit-pcp and lastlog2 relations

- pkg/sosreport/sosreport.jsx
This makes it work when downloading from a remote machine.
No default will be provided by Cockpit itself, unlike with cockpit.channel() etc.
> sosreport: Explicitly specify "host" in download channel options

- pkg/Makefile.am
- tools/debian/cockpit-bridge.lintian-overrides
- tools/debian/cockpit-networkmanager.lintian-overrides
- tools/debian/cockpit-packagekit.lintian-overrides
- tools/debian/cockpit-sosreport.lintian-overrides
- tools/debian/cockpit-storaged.lintian-overrides
- tools/debian/cockpit-system.lintian-overrides
- tools/debian/cockpit-tests.lintian-overrides
- tools/debian/cockpit-ws.lintian-overrides
- tools/debian/cockpit.lintian-overrides
- tools/debian/copyright.template
- tools/debian/rules
[Current Debian builds](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21103-0f79b0ea-20241010-101123-debian-testing-other/log) (search for "lintian --fail") have two screenfuls of lintian messages. This fixes most of them.
The remaining ones are
> I: cockpit-tests: arch-dep-package-has-big-usr-share 18085kB 100%
> I: cockpit-system: ored-depends-on-obsolete-package Recommends: policykit-1 => polkitd and optionally pkexec
> I: cockpit-doc: possible-documentation-but-no-doc-base-registration
which are harmless. The second one is intended, as that's just an alternate dependency for backports. But it's a good reminder to clean it up some day.
> Fix LICENSE.txt installation and most Debian lintian messages

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
With the switch to the python PCP implementation the metrics page no longer needs to re-login to load the new pcp manifest. The Python bridge will re-attempt import the PCP module and then load metrics as expected with one minor issue that uninstalling python3-pcp keeps the PCP module in memory.
> metrics: remove re-login requirement for loading PCP metrics

- containers/ws/install.sh
- pkg/apps/manifest.json
- test/ostree.install
- test/verify/check-apps
- test/verify/check-ws-bastion
Kdump, Networking, SELinux, Storaged, and Software Updates are all fine
and useful for beiboot mode. Apps doesn't, but that's hidden by the
manifest condition.
---
Plus two fixes for the Applications page.
Aside from boosting the ws container, this is also a prerequisite for https://issues.redhat.com/browse/COCKPIT-1178.
> containers/ws: Install our other Cockpit pages

- pkg/shell/frames.jsx
- pkg/shell/state.jsx
- test/verify/check-pages
- test/verify/check-shell-menu
- test/verify/check-shell-multi-machine
> shell: Use the "load" event instead of polling to catch ready frames

- pkg/static/login.js
- test/verify/check-loopback
When directly logging into a remote host without cockpit installed, the login page showed an unhelpful and untranslatable fatal error message:
> Authentication failed: no-cockpit: [Errno 2] No such file or directory
This also left the user with nothing actionable other than reloading the page.
Handle the "no-cockpit" problem code and show a proper error message. Use the exact same one as in the shell's host switcher, to avoid introducing another similar translatable string. This also goes back to the login form, to either choose another host, or reattempt the login after installing cockpit on the target.
---
Spotted in #21121. In that PR we'll most probably refine that error message.
Screenshot on main:
Screenshot with this PR -- I deliberately left it at German to see that it gets …
> static: Handle no-cockpit error

- pkg/lib/superuser.js
- pkg/systemd/superuser-alert.jsx
- test/verify/check-superuser
When a user configures shell.override.json to disable superuser bridges (`{ "bridges": [] }`), then the banner in the overview is just inactionable noise. Hide it then.
Fixes #21134
> systemd: Hide "limited access mode" banner without superuser bridges

- pkg/static/login.js
- src/cockpit/beiboot.py
- src/cockpit/bridge.py
- src/ws/cockpitauth.c
- test/verify/check-loopback
- test/verify/check-shell-multi-machine
We recently eliminated all on-demand installations of cockpit-* packages in beiboot mode, which prevents accidentally moving from a beiboot to a distro package scenario.
This means we can now carefully open up the beiboot feature for distro packages. However, we need to be careful here: While we can reasonably assume an ever-green flatpak and cockpit/ws container, distro packages may be arbitrarily old, and hence incompatible with APIs from newer OSes. So start small and only allow connecting to the same target OS as the host. This should already cover a lot of use cases in homogenous environments.
Note that this only applies to direct logins (bastion host). The code path for the (deprecated) host switcher is completely different and doesn't support beiboot at all.
Drop the `no-cockpit` …
> beiboot: Enable beiboot feature for distro packages for same OS

- doc/protocol.md
- src/cockpit/channel.py
- src/cockpit/channels/stream.py
- test/pytest/test_bridge.py
Add the spawned PID to the channel's "ready" message. This will be
useful for #21021
----
~The first commit is unrelated for this PR, but you'll need it for the demo below. But having "once" event handlers is generally useful, so let's already stop typescript to yell at us about that.~
@ashley-cui you can test it with this demo, that'll show the pid when opening the terminal, and it goes away when you control-d it.
```diff
diff --git pkg/systemd/terminal.jsx pkg/systemd/terminal.jsx
index 03ada383b..31de7e757 100644
--- pkg/systemd/terminal.jsx
+++ pkg/systemd/terminal.jsx
@@ -27,7 +27,7 @@ const _ = cockpit.gettext;
*/
class UserTerminal extends React.Component {
createChannel(user) {
-            return cockpit.channel({
+            const ch = cockpit.channel({
payload: "stream", …
```
> bridge: Report PID for a spawn stream channel

- pkg/lib/service.js
- pkg/systemd/overview-cards/tuned-dialog.jsx
The TunedPerformanceProfile component was keeping a DBus connection open to tuned, and was closing and reopening it whenever something might have changed that requires it.
This happened asynchronously with the rest of the code that was using this DBus connection, and would frequently cause that code to fail with "disconnected" errors.
Also, the TunedDialog was itself causing changes that require a new DBus connection (namely starting the tuned.service), but was always working with the one that was originally passed into it via its properties.
Let's straighten this all out:
- Polling for the button state will open its own dedicated DBUs connection and close it when polling is done.  There is no need to keep a DBus connection open for the whole Cockpit session.
- The tuned.service is …
> systemd: Don't open and close tuned DBus connections asynchronously

- .github/dependabot.yml
- package.json
sass 1.80 (and 2.x) introduces tons of "@import rules are deprecated". These are unfixable on our side due to PatternFly using them extensively.
We don't need any new sass features, so stick to 1.79.x. Explicitly not ignore 3.x (which will drop @import) to get a reminder in the future to try and clean this up again.
Fixes #21151
> package.json: Revert to sass 1.79

- src/common/cockpitwebresponse.c
Commit 7c22f854d11c9821f7d introduced a resource leak: cockpit_web_response_error_with_body() now receives a constant "reason" as argument, but in some cases shadows that with a locally allocated string. The latter never got freed.
Rename the variable and ensure it gets cleaned up at the end of the function.
Spotted by Coverity.
> common: Fix memory leak in cockpit_web_response_error_with_body()

- pkg/static/login.html
- pkg/static/login.js
- pkg/static/login.scss
- src/cockpit/beiboot.py
- test/verify/check-client
- test/verify/check-loopback
- test/verify/check-shell-multi-machine
- test/verify/check-static-login
- test/verify/check-system-realms
- test/verify/check-ws-bastion
This makes it conformant to the current PF design.
Bring the DOM structure closer to current PF5's alert, and
adjust/simplify CSS accordingly. Thanks Garrett for working this out!
Also tighten the error message checks in the tests, in particular for
check-ws-bastion.
Rework the "no-cockpit" message: Telling the user which OSes are
supported is nice at some level, but doesn't help operationally when
they want to connect to *that* server. Thus, suggest to install
cockpit-system, which is the recommended way out of this error.
----
Reproducer for showing the banner on login page (do this in a test VM):
```
printf '[Session]\nBanner = /tmp/banner\n' | sudo tee -a /etc/cockpit/cockpit.conf
printf 'Hello from my laptop\nsecond line\n' > /tmp/banner
sudo systemctl stop cockpit
sudo setenforce 0 …
```
> login: Split alert into title/description

- test/verify/check-static-login
During the course of disabling/replacing Y2038 unsafe APIs, Debian recently disabled utmp support in systemd. coreutil's `who` hasn't yet been updated to read logind's database <https://bugs.debian.org/1085643>, which broke TestLogin.testBasic.
Just ask `loginctl` about the sessions directly. This is unfortunately a bit more involved, as we are interested in the session type, and that's not part of the list view. So we need to query `show-session`.
---
Blocks https://github.com/cockpit-project/bots/pull/7033
> test: Replace `who` with `loginctl` in TestLogin

- test/verify/check-storage-luks
- test/verify/check-storage-mounting
- test/verify/check-storage-swap
RHEL 8.10's cryptsetup uses too much memory
(https://issues.redhat.com/browse/RHEL-8258). So the LUKS tests are too flaky in RHEL 8. Skip them, like in check-storage-resize.
---
See [failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7042-173353ea-20241028-102339-rhel-8-10-ws-container-storage-cockpit-project-cockpit/log.html) from https://github.com/cockpit-project/bots/pull/7042 .
> test: Skip more LUKS tests on rhel-8-10

- test/verify/check-metrics
- test/verify/check-pages
https://github.com/cockpit-project/bots/pull/7045 added python3-pcp to our rhel-8-10 image.
Re-add the RHEL 8 check to TestHistoryMetrics.testEvents, and the redis module treatment. Both of these were cleaned up earlier.
> test: Enable history metrics tests on RHEL 8

- test/verify/check-metrics
https://github.com/cockpit-project/bots/pull/7045 added python3-pcp to the rhel-8-10 image.
Cherry-picked from main commits 70ec634259f6e and 99d648bd86f4458.
---
Fixes [this fallout](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7045-71b1a964-20241029-124303-rhel-8-10-other-cockpit-project-cockpit-rhel-8/log.html#55-2). I landed the bots PR already to avoid a criss-cross block, and with that we now have python3-pcp on all images.
> [rhel8] test: handle installed python3-pcp in metrics test

- pkg/lib/lastlog2.py
- pkg/lib/logins.ts
- pkg/systemd/overview-cards/lastLogin.jsx
- pkg/users/users.js
- test/verify/check-users
Latest debian testing dropped support for the old wtmp/lastlog stack. Other distributions will follow soon.
Blocks https://github.com/cockpit-project/bots/pull/7033
The extra debian-testing/{other,expensive}@bots#7033 tests here prove that this works.
> systemd: Add lastlog2 support for "last login" health card item

- test/verify/check-networkmanager-bond
- test/verify/check-networkmanager-mac
- test/verify/check-networkmanager-mtu
- test/verify/check-networkmanager-settings
Fedora 40 often runs into OOM conditions with 256 MiB. This breaks booting if the OOM killer shoots an unlucky process.
We don't need to be *that* scrimpy with handing out RAM -- a default destructive test gets a VM with 1152 MiB RAM, so the two provisioned ones together are still under that limit.
Fixes #21165
---
Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7049-2a2ac73f-20241030-085356-fedora-40-updates-testing-cockpit-project-cockpit/log.html#88), which has plagued us for some time now, see the issue.
Besides the usual /networking scenario, I'll also start a "full" scenario here, plus an /updates-testing, to prove that this works.
> test: Increase DHCP machine RAM for network tests

- test/image-prepare
https://github.com/cockpit-project/bots/pull/7046 added the ws container to our fedora-40 image. So now `test/image-prepare --container` does not need to download anything from the internet any more.
The other use case of `create_machine()` for fedora-coreos preparation has always been offline already.
Disable networking for these builds to ensure it stays that way and builds are reproducible.
> test: Make ostree/ws container preparation run offline

- HACKING.md
- doc/guide/cockpit-session.xml
- test/README.md
Rendered view: 
- https://github.com/martinpitt/cockpit/blob/docs/test/README.md
- https://github.com/martinpitt/cockpit/blob/docs/HACKING.md
Rendered cockpit.permission documentation:
The weird font in the description list happens to all our lists, that just happens in a local doc build. It looks correct in the [public guide](https://cockpit-project.org/guide/latest/cockpit-login.html), and we'll soon replace this with markdown or asciidoc anyway.
> Various documentation updates

- pkg/storaged/btrfs/subvolume.jsx
- test/common/testlib.py
- test/verify/check-storage-btrfs
- test/verify/check-storage-mounting
Showing this as "/" confuses users as they might think it is the root partition and official btrfs terminology names it "top-level".
https://btrfs.readthedocs.io/en/latest/Subvolumes.html
Relates: #19920
---
> storaged: btrfs: show btrfs filesystem "root" subvolume as "top-level"

- src/tls/cockpit-certificate-helper.in
On embedded devices such as a RPI storage is more fragile and power loss can happen more frequently.
> tls: force write certificates to disk

- tools/cockpit.spec
Thanks to @hroncok who sent this to Fedora: https://src.fedoraproject.org/rpms/cockpit/pull-request/300# There the build was tested, and it still ran our pytests fine. Of course the packit/copr builds here will validate it as well.
> spec: Drop unneeded build dependency on tox and pytest-cov

- pkg/lib/esbuild-common.js
To aid our effort to move away from SASS to pure CSS explicitly restrict the esbuild SASS plugin to only take SASS files. Every Cockpit project can now slowly convert SASS files to CSS where possible.
> lib: restrict SASS plugin to scss files

- test/verify/check-static-login
There are four remaining. I looked into them a little bit, but they are really hard.
> Two rhel-8 ws container scenario fixes

- src/ws/cockpitauth.c
- test/verify/check-connection
Don't kill a `--local-session` on timeout, i.e. after the browser
disconnects. While it would be possible to restart the process if a
binary is given, it's impossible to do so with `-`, i.e. talking to
stdin/out.
Spotted in https://github.com/rhinstaller/anaconda-webui/pull/485#issuecomment-2436805547
> ws: Disable session timeout for --local-session

- src/ws/cockpit-desktop.in
RHEL 10 does not ship Firefox as RPM any more, and will instead use a flatpak. For now, check for/run the IDs of the official upstream Mozilla Firefox on flathub and the RHEL flatpak [1].
Surprisingly, `flatpak run` works fine inside our little network namespace.
https://issues.redhat.com/browse/RHEL-65847
[1] https://catalog.redhat.com/search?gs&q=firefox-flatpak
----
cockpit-desktop: Add firefox profile to hide privacy bar/tab and bookmarks
This makes the cockpit-desktop experience a bit more tasteful with
Firefox -- avoid the second broken tab (with the privacy note, which you can't
open anyway as this is an isolated network namespace), and disable data
submission to avoid the privacy hint notification bar.
Also disable the bookmark toolbar. It doesn't appear by default with the …
> cockpit-desktop: Support Firefox flatpak

- pkg/lib/cockpit-components-typeahead-select.tsx
The "isDisabled" in the props needs to remain optional, otherwise every user has to provide it. The default value in the function does nothing for this.
The real problem was assigning that to MenuToggleProps, but there the default value will make sure that isDisabled is not undefined anymore.
> lib: Fix TypeScript error in TypeaheadSelect correctly

- pkg/lib/pam_user_parser.ts
Add return types for functions in `pam_user_parser.ts` that are needed to port `permissions.jsx` in cockpit files.
> lib: pam_user_parser.ts add return types

- .github/dependabot.yml
- package.json
I accidentally landed that, sorry.
Fix the syntax error in the dependabot configuration, that should prevent further updates.
This reverts commit 182dac465b994483b286f798857b2a76acd83279.
> Revert "Bump sass from 1.79.6 to 1.80.6"

- test/common/lcov.py
The test for whether pkg/lib should be excluded or not depends on how the source repo was cloned, and will see "cockpit" in CI.
> test: Fix coverage report for pkg/lib

- pkg/lib/cockpit.js
- pkg/lib/python.ts
Add exception type to handle cases when spawned python script exits with error.
> lib: python.ts add exception type

- test/common/testlib.py
- test/ws-container.install
Fedora CoreOS has been rebased on Fedora 41 which brings in Python 3.13 build rpm's while our WS container uses Python 3.12 and thus we aren't testing main.
> test: apply a workaround for Fedora-CoreOS rebased on Fedora 41

- .eslintrc.json
This is fine, TypeScript will check them correctly.  And it is very useful for global functions, at least.  And we allow functions to be used before their definitions in JavaScript files.
> build: Allow TS functions to be used before their definition

- pkg/lib/cockpit.js
The modern equivalent of this API is `Promise.resolve` and `Promise.reject`.
---
Haven't found any users in our projects
> lib: cockpit: remove cockpit.resolve/cockpit.reject()

- pkg/systemd/terminal.jsx
- pkg/systemd/terminal.scss
- test/verify/check-system-terminal
Allow opening of a path from a URL option, path=path. If the terminal is busy, then warn the user and prompt them to continue.
WIP: changing to a path that does not exist should result in an alert, but there's some css magic that's preventing the alert from showing, and I can't figure out what it is. Also needs tests, but thought I would draft it for feedback so far :relieved: 
Prerequisites:
> systemd: Open path in terminal

- pkg/base1/test-dbus.js
- src/cockpit/config.py
- test/verify/check-connection
If there is a syntax error in cockpit.conf, the bridge previously
crashed with e.g. a `configparser.MissingSectionHeaderError`.
Intercept that, log a warning instead, and ignore the config file
instead.
https://bugzilla.redhat.com/show_bug.cgi?id=2324979
> bridge: Fix crash on invalid cockpit.conf

- src/common/cockpitwebresponse.c
- src/common/test-webresponse.c
Fixes: https://github.com/cockpit-project/cockpit/issues/21216
I do not trust myself to test this on a codebase I'm unfamiliar with and test cases for `HEAD` requests might need to be updated if there are any.
> common: Do not add a body for chunked HEAD request

- pkg/lib/cockpit-connect-ssh.tsx
- pkg/shell/hosts_dialog.jsx
Why: The login close button was previously styled like a link, but it should have been styled as a secondary button. I have updated the styling to make the close button look like a proper button.
Resolves: #21160
> shell: style login close button as secondary button

- pkg/shell/state.jsx
- test/verify/check-shell-menu
Due to a missing else we never allowed a user to change the default landing page.
> shell: allow changing the default landing page

- pkg/systemd/overview-cards/cryptoPolicies.jsx
- test/verify/check-system-info
See commit logs for details.
https://issues.redhat.com/browse/COCKPIT-1185
Testing:
- All our current "main" bots images still have `fips-mode-setup`, so this PR shouldn't cause any regressions.
- The [rhel-10-0 refresh](https://github.com/cockpit-project/bots/pull/7095) brings the announced FIPS mode setup changes (which fail the tests) and doesn't regress anything else. [test against that image succeeded here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21264-dae0b2f7-20241115-095043-rhel-10-0-other-bots%237095/log.html)
- The [centos-10 refresh](https://github.com/cockpit-project/bots/pull/7091) also brings the FIPS changes, and its kernel doesn't oops with FIPS -- but it regresses PCP, so tests will still not go green. However, `TestSystemInfo.testCryptoPolicies` and …
> RHEL 10 FIPS adjustments

- doc/guide/Makefile-guide.am
- doc/guide/cockpit-guide.xml
- doc/guide/multi-host.xml
- doc/man/cockpit.conf.xml
- pkg/shell/hosts.jsx
- pkg/shell/hosts_dialog.jsx
- pkg/shell/shell.jsx
- pkg/shell/state.jsx
- test/common/testlib.py
- test/verify/check-shell-host-switching
- test/verify/check-shell-multi-machine
- test/verify/check-shell-multi-machine-key
- test/verify/check-shell-multi-os
- test/verify/check-superuser
- test/verify/check-system-realms
- test/verify/check-system-shutdown-restart
Connecting to multiple hosts in a single Cockpit session allows all these hosts to access each other freely. Eventually Cockpit will not allow multiple connections, but in the mean time, we want to educate people better.
This warning can be disabled by including the following in `/etc/cockpit/cockpit.conf`:
```
[Session] 
WarnBeforeConnecting=false
```
-----------------------
Demo: https://youtu.be/Un6k3DiukOg
> Shell: Extra warnings when connecting to remote hosts

- pkg/lib/cockpit-components-terminal.jsx
- test/common/testlib.py
- test/verify/check-system-terminal
Pressing Ctrl+Space in the terminal was previously considered a major insult and killed the session. Both the "externally visible" representation in JS as a string (a null byte) as well as the actual bytes sent to the websocket (0xA0) are broken and useless. The latter caused a session disconnect due to invalid UTF-8 data, and the former makes it impossible to properly work around this issue (which would be to send [0xC2, 0xA0] to the web socket).
So the best thing that we can do is to ignore invalid keys (which show up as NUL).
Fixes #21213
---
See https://github.com/cockpit-project/cockpit/issues/21213#issuecomment-2482208738 for the gory details and my debugging notes.
> lib: Ignore invalid input keys in Terminal

- test/common/test-functions.js
Add a `querySelectorAll()` variant which can transparently pierce and traverse shadow DOMs without having to know their structure (i.e. doing selectors piece-wise and iterating on their `.shadowRoot` attribute).
As this is more expensive than standard querySelector()`, only  use it if the page actually contains any shadow root.
This makes it a lot more convenient to write tests for pages which use web components, like https://patternflyelements.org.
----
https://github.com/cockpit-project/starter-kit/pull/1028 makes use of that.
TODO:
> test: Add support for querying shadow DOM

- selinux/cockpit.te
- src/common/cockpitframe.c
- src/common/test-frame.c
- src/session/client-certificate.c
- src/session/session-utils.c
- src/session/session-utils.h
- src/session/session.c
- src/systemd/cockpit-session@.service.in
- src/ws/Makefile-ws.am
- src/ws/mock-auth-command.c
- test/verify/check-connection
- test/verify/check-system-realms
Broken out from #16808. But that requires a few more rounds of review and has ideas for more cleanups. These are the cockpit-session JSON parser (which is a bit finnicky, but got reviewed a few rounds already), plus a few extra commits which I believe are not problematic. Let's get them out of the way.
> Preparations for launching cockpit-session via unix socket activation

- pkg/kdump/kdump-view.jsx
- pkg/lib/cockpit-components-modifications.jsx
on SLE/Opensuse microos, we use `transactional-update` to automatically set the required kernel arguments like Fedora. I need to confirm how we want to enable this on system via ansible. on its own this is safe to merge.
> add instructions to enable kdump on microos systems

- pkg/systemd/manifest.json
- pkg/systemd/terminal.jsx
- test/verify/check-system-terminal
- Fix error messages
- Mark path as a terminal capability in manifest
Fixes: https://github.com/cockpit-project/cockpit/issues/21281
> systemd: Open path in terminal followup fixes

- containers/ws/install.sh
- src/ws/cockpitauth.c
- src/ws/test-auth.c
- test/verify/check-connection
- test/ws-container.install
See individual commits for details. This was another tiny lose thread in #16808 which upon pulling [brought down the whole edifice](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16808-ac0f93c2-20241120-085141-rhel-8-10-ws-container-networking/log.html). The cockpit-session removal from the container reproduces this situation.
> ws: Fix reported error if the authentication process is not available; containers/ws: Drop cockpit-session

- test/verify/check-metrics
That version changes the interpretation of existing data somewhat, and thus events slightly move around. Make the assertions flexible enough to work with old and new versions.
There was not much science in the original assertions anyway -- I simply recorded some stuff and then pinned down the status quo.
We can make this stricter again once all supported OSes have PCP ≥ 6.3.2 (but that'll be a few years).
Addresses the non-pixel parts of #21237
---
That unblocks https://github.com/cockpit-project/bots/pull/7091 but not yet the nightly failures. See that issue for the plan.
> test: Add enough TestHistoryMetrics.testEvents wiggle room for PCP 6.3.2

- .gitignore
- src/systemd/Makefile.am
- src/systemd/cockpit-session-socket-user.service
- src/systemd/cockpit-session.socket
- src/systemd/cockpit-wsinstance-http.service.in
- src/systemd/cockpit-wsinstance-http.socket
- src/systemd/cockpit-wsinstance-https-factory.socket
- src/systemd/cockpit-wsinstance-https@.service.in
- src/systemd/cockpit-wsinstance-https@.socket
- src/systemd/cockpit-wsinstance-socket-user.service
- src/systemd/cockpit.service.in
- src/systemd/sysusers.d/cockpit-wsinstance.conf
- src/tls/README.md
- test/verify/check-connection
- tools/cockpit.spec
- tools/debian/cockpit-ws.install
- tools/debian/cockpit-ws.postinst
- tools/debian/rules
Switch over to systemd allocating user IDs for us dynamically, dropping our static users.
We create these users dynamically:
- `cockpit-session-socket` is the group owner of `/run/cockpit/session`
- `cockpit-wsinstance-socket` is the group owner of all sockets in `/run/cockpit/wsinstance/`
- `cockpit-tls` gets its own user
- `cockpit-wsinstance-http{,s@}.service` each get a user.  In this case, I think the separate https instances even each get a separate user.
This is a bit complicated due to https://github.com/systemd/systemd/issues/23067
> use DynamicUser=yes for all cockpit components

- test/verify/check-metrics
The #var-host id is gone, but the "dataid ... link text" stays.
> test: Adapt to new Grafana

- doc/guide/packages.xml
The Python bridge is already the default bridge in our project and the C bridge was removed in 7c7ab45e3f2d4bd11a4e5c6.
> doc: enable python bridge related package documentation

- test/verify/check-metrics
The #var-host id is gone, but the "dataid ... link text" stays.
Cherry-picked from main commit 9d83a1c16a2ea8708.
---
Unblocks https://github.com/cockpit-project/bots/pull/7114
> [rhel-8] test: Adapt to new Grafana

- src/systemd/cockpit-wsinstance-http.service.in
- src/systemd/cockpit-wsinstance-https@.service.in
- src/systemd/cockpit.service.in
Now that cockpit-ws does not directly fork cockpit-session, and sessions
run in their own service/cgroup, we can heavily lock down our webserver
(which is the weakest component in Cockpit). It only needs to talk to
cockpit-tls over stdin/out and cockpit-session over the Unix socket,
and call SSH for remote host support (so we can't lock down networking
completely).
`DynamicUser=` already implies the biggest restrictions, such as
`ProtectSystem=full`, `ProtectHome`, `PrivateTmp`, and more. We can even
work with `ProtectSystem=strict` (i.e. everything being read-only except
the service's /run directory and tmp dir).
Fixes #21299
https://issues.redhat.com/browse/COCKPIT-1206
> systemd: Lock down cockpit-ws and -tls

- pkg/lib/cockpit.js
Commit 132300e09cc45cbd was premature, subscription-manager still uses that [1]. Put it back, but in terms of the standard Promise API.
Add a deprecation warning.
[1] https://github.com/candlepin/subscription-manager-cockpit/pull/84
> cockpit.js: Put back cockpit.{resolve,reject}

- selinux/cockpit.fc
- selinux/cockpit_ws_selinux.8cockpit
This script has nothing to do with cockpit-ws, so stop putting it into the same security domain. We don't need to introduce a new one, just use the standard `shell_exec_t`. It's just a short-lived helper script with no user input, this doesn't justify its own policy.
This may also help with certain configurations where `hostname` wants to read /proc.
https://bugzilla.redhat.com/show_bug.cgi?id=2274774
> selinux: Move update-motd out of cockpit_ws_t

- test/common/testlib.py
`start_machine_troubleshoot` has `password` defined as an optional argument so should `add_machine`.
> test: correct add_machine password argument typing

- test/common/testlib.py
Check if the browser is running and has cockpit loaded, i.e. our various
ph_*() test-functions.js are actually available and thus we can call
`Browser.is_visible()` and friends. That may not be the case when
Cockpit hasn't been opened yet and thus the browser is still showing a
blank page, or has e.g. Grafana opened.
This is what `Browser.assert_no_oops()` actually needs to check, as on
non-Cockpit pages this doesn't make sense.
This will also help cockpit-machines to replace its incorrect usage of
the just removed `Browser.valid` flag with something useful.
----
This will help with cleaning up the very messy `testAddDiskNFS` failures [here](https://artifacts.dev.testing-farm.io/ec5d4610-4ba1-456d-9971-c6c7d471a1ff/) and [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1927-0c2 …
> test: Add Browser.have_test_api()

- test/common/storagelib.py
- test/verify/check-storage-btrfs
- test/verify/check-storage-mounting
- test/verify/check-storage-nfs
- test/verify/check-storage-stratis
Don't ignore unmount failures. That just leads to failures later on, like not being able to remove `scsi_debug`. This will make the tests fail closer to the real problem, during the umount.
---
By-product from investigating [this](https://artifacts.dev.testing-farm.io/5fb0024f-2538-47dd-bdc3-75a20a30847d/) and [this](https://artifacts.dev.testing-farm.io/8b6926b5-fbaf-4a23-8e6c-01741079c29c/) error, which happens rather often recently. That bug is a much bigger story, see #21355. But this is a good (and now independent) robustification.
> test: Factorize and robustify mount point cleanup

- test/common/testlib.py
- test/verify/check-connection
- test/verify/check-packagekit
- test/verify/check-storage-luks
- test/verify/check-storage-stratis
- test/verify/check-superuser
- test/verify/check-system-info
- test/verify/check-system-journal
- test/verify/check-system-realms
- test/verify/check-system-services
- test/verify/check-system-shutdown-restart
- test/verify/check-system-terminal
This avoids having to explicitly call `allow_restart_messages()`.
Fixes #18424
> test: Add MachineCase reboot wrappers

- containers/ws/Dockerfile
With the /ws-container scenario we now have an actually *good* way of validating this in CI :partying_face: 
However, as Knuth said "I have only proven this correct, not tested it", so I still want to test this manually next week. Thus draft for now.
> containers/ws: Move to Fedora 41

- pkg/lib/cockpit.js
Firefox used to give a different value depending on the location hash when using `window.location.hash` and `window.location.href` with for example `#abc%21abc`. This is now fixed and in all browsers the following is always true:
window.location.hash.slice(1) == window.location.href.split('#')[1]
Which proves this is now fixed in Firefox.
---
Split off from https://github.com/cockpit-project/cockpit/pull/21276
> lib: cockpit: drop old Mozilla window.location.hash hack

- pkg/storaged/iscsi/session.jsx
- test/typecheck
Let's typecheck JavaScript! With the typecheck script we can also run it on JavaScript and filter out all errors we get and error by error remove them. As for example in this PR, spotted a silly typo :)
One issue is that running with `--javascript` and then without busts the cache, so maybe we just always want to run with `--javascript` as that should probably work filtering based on file and error list.
> Typecheck javascript

- pkg/storaged/btrfs/btrfs-tool.py
- test/verify/check-storage-btrfs
This should prevent other parts of the system noticing this mount and keeping it busy or being able to read data from it.
https://issues.redhat.com/browse/COCKPIT-1210
Fixes #21355
> storaged: Use a private mount for "btrfs-tool do"

- build.js
- pkg/lib/cockpit.d.ts
- pkg/networkmanager/firewall.jsx
- pkg/playground/index.js
- pkg/shell/idle.jsx
- pkg/shell/machines/machines.js
- pkg/shell/router.jsx
- pkg/storaged/utils.js
- pkg/systemd/services.jsx
- test/common/typecheck
- tsconfig.json
> build: Move to es2021, fix some typing problems

- doc/guide/feature-systemd.xml
- doc/guide/privileges.xml
Doubled checked in the polkit repo, it doesn't look like /etc/polkit-1.rules.d/ exists. I am assuming this is just a typo.
> Incorrect polkit rules paths

- tools/cockpit.spec
- tools/debian/control
This makes more sense, as there is an actual file conflict on upgrade: cockpit-session.{socket,service} moved from -tests to -ws in commit 4dd6685e540 (release 330).
https://bugs.debian.org/1089220
---
Also see [failing installability test in Fedora](https://artifacts.dev.testing-farm.io/bd1bfa0d-52eb-4ab2-aea5-97f085f4b544/)
> tools: Move cockpit-tests conflict to cockpit-ws

- test/common/typecheck
Support a new flag `--stats` which shows the occurrences of ignored TypeScript errors in JavaScript files. This is useful for slowly removing errors from the ignore list.
> test: typecheck: output stats of TS errors for JavaScript files

- .github/dependabot.yml
We don't want sass 1.82 etc. either. Judging by the release history there won't be any 1.79.x any more, and we don't need them either.
Closes #21404
> dependabot: Ignore all sass 1.x versions

- pkg/users/account-logs-panel.jsx
- src/session/session.c
- test/verify/check-static-login
- test/verify/check-users
Call `last` with `--fullnames` to avoid truncating values (like IPv6
addresses). We don't rely on a "nicely" (argh) formatted ASCII table
with fixed column widths, but parse the structure.
Flesh out TestAccounts.testAccountLogs to actually test some values on
the page. It was almost empty before. Like in the previous commit, we
can afford to hardcode the expected IPv6 "from" address.
Fixes #21383
> users: Fix truncated "From" in account logs

- pkg/playground/plot.html
- pkg/playground/plot.js
- src/cockpit/channels/metrics.py
- test/verify/check-pages
The metrics for the networking and storage pages didn't show anything since we switched to the Python implementation. There was no integration test for internalmetrics so this regressed without us noticing as these graphs can also take data from PCP (archive or direct).
Fixes: #19627
> cockpit: send `now` along with the internalmetrics meta

- test/common/testlib.py
- test/common/webdriver_bidi.py
- test/verify/check-pages
- test/verify/check-shell-host-switching
- test/verify/check-shell-keys
BiDi mouse events work fine on the top-level document (i.e. not in frames). So let's use them to test the shell.
> test: Use real mouse events with Chromium in the shell

- test/verify/check-metrics
In the medium layout, the bottom panel sometimes has an extra white
background line (padding). This is random and unpredictable (probably
rounding noise?). That panel only contains a single standard button, so
is not very interesting.
We can't use `ignore=` for that, as the difference is the snapshot
height, not the pixel contents. So instead, temporarily hide the whole
bottom panel for the snapshot.
Fixes #21422
> test: Ignore bottom panel in TestHistoryMetrics.testEvents pixel test

- containers/ws/README.md
- containers/ws/label-run
- test/verify/check-ws-bastion
In unprivileged mode, support  to an already running SSH agent
for sharing SSH private keys.
Thanks to Anton Engelhardt <engelhardt.anton@gmail.com> for the idea and
initial implementation sketch!
Fixes #21170
For SSH key authentication, the [cockpit/ws container](https://quay.io/repository/cockpit/ws) has supported bind-mounting private SSH keys into the container for a long time. That mode is appropriate for server system containers or deploying in e.g. Kubernetes.
For desktop use cases similar to [Cockpit Client](https://github.com/flathub/org.cockpit_project.CockpitClient) it is preferable to instead run the ws container as your own user, and share your user session's [SSH agent](https://linux.die.net/man/1/ssh-agent). This provides a more comfortable login experience as you don't …
> containers/ws: Support using an external SSH agent

- src/tls/cockpit-certificate-helper.in
- test/verify/check-connection
Inspired from #21069, thanks to @jmlemetayer for pointing out!
Note that we also *could* go the other way and automatically rebuild the certificate on any such error. I'm not a big fan of that, but can be convinced  -- opinions?
> tls: Certificate error robustification

- src/ws/cockpithandlers.c
- test/verify/check-connection
Fixes #17401
----
This replaces #17404 (our oldest PR!).
> ws: Prevent search engine indexing with robots.txt

- pkg/storaged/pages.jsx
Let's use the same trick as with the table: Don't put the navigation handler on the whole card, but on all its children that should navigate, and exclude the menu button.
Fixes #19897
> storage: Don't navigate when clicking on the mobile kebab

- containers/ws/install.sh
dnf5 changed `--installroot` behaviour that it now only considers the repositories in the root instead of the host. This broke the container build.
Unfortunately my fix for that [1] got lost in a git pilot failure, mea culpa!
[1] https://github.com/cockpit-project/cockpit/pull/21360#issuecomment-2511242349
----
See https://github.com/cockpit-project/cockpit/actions/workflows/build-ws-container.yml  - after that lands, I'll do a hack to fix the container build for 331, as it now builds from the latest tag instead of main.
Tested locally with `podman build -t localhost/ws containers/ws`
> containers/ws: Fix build on Fedora 41

- pkg/metrics/metrics.jsx
- test/verify/check-metrics
Show a boot as an metric event in the historical metrics overview. A boot is likely to cause a high CPU/memory spikes so it is interesting for a system administrator to be aware of them. We obtain the boot information from systemd as `last` is deprecated and not all distros use lastlog2 while `journalctl` is freely available.
Closes: #15983
---
> metrics: show system boots in metrics

- containers/ws/install.sh
This currently contains 84 MB of dead weight (repository indexes). That made the container balloon from 57 to 116 MB.
---
Not super important, but for me it's a matter of pride! See https://quay.io/repository/cockpit/ws?tab=tags
Verified with `podman build -t localhost/ws containers/ws/`, and
```
quay.io/cockpit/ws                 329.1       496397eface4  2 weeks ago         147 MB
quay.io/cockpit/ws                 331         bba2e19b4d7b  54 minutes ago      233 MB
localhost/ws                       latest      4e1c0fdfff34  About a minute ago  145 MB
```
Note that `podman images` shows uncompressed size, whereas `podman pull` and the quay.io page show compressed.
> containers/ws: Clean /var/cache/libdnf5

- pkg/lib/cockpit-components-select.scss
- pkg/lib/cockpit-components-simple-select.tsx
- pkg/lib/cockpit-components-typeahead-select.tsx
Needed to replace the deprecated select in cockpit-machines.
> lib: Support headers with SimpleSelect

- src/ws/cockpithandlers.c
Nothing uses this, and advertising this information before login makes it easier to do mass scanning for old OS releases with security vulnerabilities.
https://issues.redhat.com/browse/COCKPIT-1084
> ws: don't send os-release to login page

- test/verify/check-system-info
In TestSystemInfo.testInconsistentCryptoPolicy, `fips-mode-setup --disable` also rebuilds the initrd. In recent Fedora 41 updates, this now takes seveal minutes, so bump the timeout just like in the previous case when enabling FIPS.
Fixes #21484
I triggered an [extra /daily run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21494-0b4c66fb-20250108-050717-fedora-41-daily-other/log.html) to prove that this works (it runs 3x affected)
> test: Allow longer reboot time with fips-mode-setup --disable

- .github/workflows/dependabot.yml
- .github/workflows/release.yml
- .github/workflows/reposchutz.yml
20.04 will soon be EOL. "ubuntu-latest" is 24.04 now with a newer podman.
---
These workflows are hard to test in "proper" PRs (`on: pull_request_target` and needing a tag), so I tested them on my fork. I pushed this branch to my fork's main and tagged a 999 release, which [succeeded](https://github.com/martinpitt/cockpit/actions/runs/12664608480/job/35293008663) (the "source" part anyway -- of course flathub etc. fails, as it doesn't have credentials).
I also created https://github.com/martinpitt/cockpit/pull/23 that runs reposchutz, and it fails in the expected way. I.e. the build and tar diffing worked fine, and it fails with the expected package.json diff.
> workflows: Move release and node-modules workflows from Ubuntu 20.04 to 24.04

- .github/workflows/build-ws-container.yml
- .github/workflows/codeql.yml
- .github/workflows/nightly.yml
- .github/workflows/trigger-anaconda.yml
- .github/workflows/unit-tests.yml
See individual commits for details. Most of these are self-validating, and I'm just taking my chance on the ws container build one. I'll run it after landing and do a follow-up in the unlikely case that it breaks.
This leaves the flatpak-test, but that does fail on Ubuntu 24.04. It's on the pilot board, I'll look at that separately.
> workflows: Move away from pinned old Ubuntu 22.04 release

- .github/workflows/unit-tests.yml
- src/ws/cockpithandlers.c
Just saw this on my machine, and it breaks `tools/make-sysext`:
```
src/ws/cockpithandlers.c: In function ‘build_environment’:
src/ws/cockpithandlers.c:351:8: error: unused variable ‘i’ [-Werror=unused-variable]
351 |   gint i;
|        ^
src/ws/cockpithandlers.c:350:15: error: unused variable ‘osr’ [-Werror=unused-variable]
350 |   JsonObject *osr;
|               ^~~
src/ws/cockpithandlers.c:348:16: error: unused variable ‘value’ [-Werror=unused-variable]
348 |   const gchar *value;
|                ^~~~~
cc1: all warnings being treated as errors
CC       src/common/libcockpit_common_a-cockpittemplate.o
make[1]: *** [Makefile:3353: src/ws/libcockpit_ws_a-cockpithandlers.o] Error 1
```
> Fix build warnings

- pkg/shell/shell.scss
- pkg/static/login.js
- test/verify/check-connection
Don't cut off the last character from brand names if they are enclosed
in quotes.
https://issues.redhat.com/browse/COCKPIT-1219
https://issues.redhat.com/browse/RHEL-72582
---
What an embarrassing bug... :see_no_evil:
> login: Fix quote removal in brand name

- .gitignore
- test/common/netlib.py
- test/verify/check-connection
This the part 1 of https://github.com/cockpit-project/cockpit/pull/21335#pullrequestreview-2467200934
These are the "boring" bits that don't fit anywhere else
Let us know if you need anymore changes. Hope you had a good break!
> Tumbleweed testing part 1

- pkg/static/login.js
- test/ws-container.install
Commit d76cadd59009 moved the ws container to Fedora 41, so the hack is
obsolete. Moreover, it is detrimental as PRs don't run against modified
bridge code any more.
This reverts commit 8ea9eaccf9edad86df76bfb142941ff3f1b0fd9f.
> Revert "test: apply a workaround for Fedora-CoreOS rebased on Fedora 41"

- .gitignore
- doc/guide/cockpit-manifest.xml
- pkg/shell/index.html
> manifest related cleanups

- pkg/base1/test-locale.js
- pkg/shell/index.html
- src/cockpit/packages.py
- test/pytest/test_packages.py
Pages don't (shouldn't) care about manifest translations when including
`manifests.js` -- they usually do that to query for a package's
existence or some feature flags.
Only the Shell cares about the translations. So drop translations from
`manifests.js`, and support a new `manifests-i18n.js` which only the
shell uses.
This isolates translations from different pages from another.
Concretely, subscription-manager-cockpit and our systemd page both
translate "$0 important hit" differently, and even to different data
types (in s-m it results in an array, in systemd in a normal string).
This caused a page crash, and also wrong strings, as s-m's translations
are really not expected to be used on the Overview page.
This also speeds up the loading of frames, as they now don't have to go
through …
> bridge: Drop translations from manifests.js, introduce m-i18n.js

- pkg/storaged/btrfs/btrfs-tool.py
- pkg/storaged/utils.js
- tools/cockpit.spec
- tools/debian/cockpit-storage.postinst
This shouldn't be on persistent storage -- after a reboot all the mounts are gone, so the database should not survive that either.
Use `os.path.join()` for a slightly more regular and cleaner path building.
Opportunistically clean up the /var dir on package upgrades, in a careful way that will keep any existing leaked mounts there. This may interfere with running remote sessions (without upgrading cockpit-ws), so they will treat the /var mounts as custom external ones for the rest of their lives. That's acceptable, though.
> storaged: Move /var/lib/cockpit/btrfs to /run

- test/common/testlib.py
- test/verify/files/mock-insights
Ruff 0.8.3 enables a new preview rule RUF051 `if-key-in-dict-del`, preferring `.pop()` over a conditional check plus a separate del statement.
> test: follow RUF051 recommendations

- pkg/storaged/btrfs/btrfs-tool.py
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/client.js
In Anaconda mode, Cockpit mounts a btrfs filesystem to list its subvolumes. Now these mounts are private to the process that does the listing, just like the mounts for making changes already are.
Since the mounts are no longer shared, we don't need to maintain a database of their users.
> storage: Use private mounts for btrs polling

- pkg/static/login.js
- src/cockpit/beiboot.py
- src/cockpit/osinfo.py
- test/verify/check-shell-multi-machine
Previously we only allowed beibooting to the same target OS as the host.
But we know which OSes Cockpit works on -- exactly the ones which we
have in CI. So check the remote OS against a list of known supported
ones.
Building that supported list isn't quite easy, though: It *roughly*
corresponds to our bots/lib/testmap.py, but not quite -- e.g.
"debian-stable" is "Debian 12" right now. So for the time being, keep
that list static. We'll have to update it for each new OS that we
support, but our integration tests will tell us.
In the future we might be doing something clever, like automatically
collecting `os-release` files from all our supported images in bots, and
use that to auto-build `osinfo.py`.
Enable the "incompatible future OS version" check for Debian/Arch as
well, by appending a …
> login: Beibooting to all supported OSes

- package.json
- pkg/storaged/crypto/tang.jsx
- tools/build-debian-copyright
This allows us to drop the two pure JavaScript implementations of SHA-1 and SHA-256. These native Web Crypto API is available as baseline and allows us to easily switch over to SHA-512 without adding a new dependency.
> Switch to the Web Crypto API for generating SHA checksums

- test/vm.install
The referenced issue is no longer an issue and we already disable tuned in bots when we create the image.
> test: drop duplicate tuned disabling

- test/verify/check-metrics
passt got fixed in [1] to get along with multiple network interfaces and no default routes.
[1] https://bodhi.fedoraproject.org/updates/FEDORA-2024-4632bfa865
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2277954
---
Commit message copied from abcb4b1ea8e4c358c783efa4f2f3c45c8a580753 in cockpit-podman so this should be fixed in Cockpit as well.
> test: Drop dummy interface

- pkg/playground/test.html
- pkg/playground/test.js
- src/cockpit/channels/filesystem.py
- test/verify/check-pages
For the Cockpit Files editor fsreplace1 is used to write new content to an existing file. If an administrator has set a custom selinux context to such a file, for example a config file shared into a container the SELinux context is not kept which leads to unexpected behaviour.
Closes: #21505
> cockpit: retain SELinux context if file exists

- pkg/Makefile.am
Fixes #19406
----
Before:
```
$ touch po/de.po; make
make  all-am
make[1]: Entering directory '/var/home/martin/upstream/cockpit/main'
make[1]: Leaving directory '/var/home/martin/upstream/cockpit/main'
```
Now:
```
make  all-am
make[1]: Entering directory '/var/home/martin/upstream/cockpit/main'
BUNDLE   dist
12:03:23: Build finished
COPY     dist/static/fonts/RedHatText-Regular.woff2 → doc/guide/html/
COPY     dist/static/fonts/RedHatText-Medium.woff2 → doc/guide/html/
GEN      doc/guide/html/index.html
make[1]: Leaving directory '/var/home/martin/upstream/cockpit/main'
```
> build: Let `make` rebuild the bundle on PO changes

- test/browser/run-test.sh
- test/verify/check-static-login
In issue #20700 this leads to some SELinux trouble that prevents cleaning up logind sessions. This is a more customized setup that isn't reproducible yet, but this at least ensures that "standard" NFS home directories work as expected.
Skip it in tmt, as it only tests our own SELinux policy, and would require a new test dependency.
> test: Check NFS home directory

- test/README.md
The `test/README.md` docs missed information on how to actually login
using the web interface. This adds the current userpass `admin:foobar`
to the README.
Future improvement could be to add this to the outputted message as
well.
> Docs: Add userpass for VM web login

- test/common/testlib.py
We can only access data_ref and data_now after checking that the coordinates are in bounds for both.
> test: Don't access out-of-bounds pixels

- test/common/testlib.py
ruff 0.9.3 includes RUF047 by default now which complains about useless else statements.
> test: remove empty else clause

- pkg/users/accounts-list.js
Current users page lists the users in a table together with a column for actions. However, the table header doesn't include the last actions column and instead shows the table header line ending preemptively.
As we likely don't want a visibly named column for the actions this will instead visually just extend the line so it is consistent while also adding a screen reader friendly text to indicate what the column is portraying.
This does mean we need to include
`@patternfly/patternfly/patternfly-addons.css` in the PatternFly CSS import.
---
This line seems only to occur on Chrome and not Firefox, but definitely a bug
PR applied:
> users: Add screen reader accessible column

- configure.ac
There is a bug in the version of autotools in leap 15.6. It can be tested in the following way
1. on leap 15.6 run autoreconf on the cockpit source code
2. run `./configure`
3. syntax error
after a few seconds the configure script exists with
```
./configure: line 4783: syntax error near unexpected token `pidfd_getpid'
./configure: line 4783: `    pidfd_getpid'
```
The fix was found by @Nykseli
> fix: configure.ac for leap15.6

- tools/cockpit.spec
- tools/debian/control
This hasn't been necessary since the switch to the Python bridge.
> tools: Drop obsolete glib-networking dependency of bridge

- containers/ws/install.sh
This brings the ws container closer to the Client flatpak. In beiboot mode, Files works everywhere including RHEL 8 [1].
[1] https://github.com/cockpit-project/cockpit-files/pull/917
---
Tested locally with
```
podman build -t localhost/ws containers/ws
podman run -d --name cockpit-bastion -p 9999:9090 localhost/ws
```
and then logging into `host.containers.internal` (i.e. my laptop) on https://localhost:9999.
The [cockpit/ws container](https://quay.io/repository/cockpit/ws) now includes [cockpit-files](https://github.com/cockpit-project/cockpit-files/). When you log into a remote machine that does not have any cockpit packages installed (package-less mode), the "Files" page is now available.
> containers/ws: Include cockpit-files

- .cockpit-ci/container
The quay repository was removed as it's been stale for over a year.
---
Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-7367-5491fe30-20250129-104918-rhel-8-10-cockpit-project-cockpit-rhel-8/log.html)
> .cockpit-ci: Move tasks container to ghcr.io

- test/image-prepare
- test/verify/check-bots-api
- test/verify/check-connection
- test/verify/check-metrics
- test/verify/check-packagekit
- test/verify/check-static-login
- test/verify/check-system-info
Preparation for #21559. As this potentially affects other OSes, let's regression-test here.
> Various test fixes for bootc image

- selinux/cockpit.te
- test/bootc.install
- test/image-prepare
- test/verify/check-shell-multi-machine-key
We want to test deploying cockpit rpms in bootc images. This will prevent hiccups like https://github.com/cockpit-project/cockpit/issues/21201 in the future and also test a lot of OS subsystems.
The centos-9-bootc bots image includes its own deployment container image, so we can easily derive an image with our locally built RPMs included.
https://issues.redhat.com/browse/COCKPIT-1237
----
Note that I only cover/trigger `centos-9-bootc/{networking,other,expensive}` here. /storage requires adding cockpit-storaged, udisks, etc., which we skip on fedora-coreos as well. Managing storage isn't the most important thing on a bootc system, so I'll left that for a follow-up.
Prerequisites/split out work:
> test: Add bootc image

- pkg/lib/cockpit-components-dynamic-list.jsx
Existing callers in podman/machines used it like that:
<DynamicListForm ... itemcomponent={ <PublishPort />} />
But from a conceptual as well as type-check perspective this is nonsense: This is a totally invalid object as it does not get any (required) properties. It needlessly runs initialization, and can never actually get rendered. Running typechecker on this rightfully complained about
> src/ImageRunModal.jsx(1062,51): error TS2740:
> Type '{}' is missing the following properties from type '{ id: any; item: any; ...
Change this to specify the type, so that it can be instantiated properly with `React.createElement()`.
Existing callers in podman/machines have to be changed to
<DynamicListForm ... itemcomponent={PublishPort} />
----
We don't use this component anywhere in cockpit, thus …
> lib: Make DynamicListForm.itemcomponent a component type instead of instance

- Makefile.am
- src/Makefile.am
In build environments where a different python is required to the one on the host (in our case, yocto), the makefile needs to support an external python3 location.
We were running into issues where our build host used python 3.11, but the yocto version was 3.10, so the files were going into the wrong dist-packages folder.
In our case, adding the following line to our yocto recipe for cockpit (with this fix) now works as required:
```bb
EXTRA_OEMAKE += "PYTHON3=${STAGING_BINDIR_NATIVE}/python3-native/python3"
```
> Allow external python to be used in make

- pkg/base1/test-http.js
Since QUnit 2.21 a deprecation warning is shown when a test takes longer then 3 seconds and has no timeout set.
---
See https://qunitjs.com/api/config/testTimeout/
> base1: fix deprecated qunit long test without a timeout

- doc/guide/cockpit-http.xml
- doc/protocol.md
- pkg/base1/test-dbus.js
- pkg/base1/test-echo.js
- pkg/base1/test-http.js
- pkg/base1/test-stream.js
- pkg/lib/qunit-tests.ts
- src/ws/test-server.c
- test/common/pixel-tests
- test/run
As we only have the Python bridge now, we can drop the dynamic special
casese and C bridge fallbacks from the unit tests.
Drop the fencing and HTTP connection sharing tests -- we haven't missed
these features in years, so it's unlikely we'll bring them back.
However, do keep `skipWithPybridge` for now -- the D-Bus tests still
need to be adjusted or the Python bridge fixed, and that makes them easy
to grep.
> base1: Clean up pybridge special cases

- test/verify/check-system-info
Our pixel test mechanism can ignore certain HTML elements by id/class by measuring them before the take a screenshot. If the text is not fully loaded yet the measured html element is 0x0 and if it is loaded when taking a screenshot the pixel test fails.
---
Maybe instead we should first take a screenshot and then collect the ignored pixels? Let's discuss, that might be racy as well.
> test: wait for tuned-button to show text

- test/verify/check-storage-btrfs
This [part](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21389-0c41f814-20250109-101243-fedora-41-devel/Coverage/pkg/storaged/btrfs/device.jsx.gcov.html) was never covered in our tests.
Simply click through and verify it shows the data we expect.
> test: cover the btrfs device card in our tests

- pkg/users/account-details.js
- pkg/users/accounts-list.js
- test/verify/check-users
For the current logged in user, Cockpit already has a logout button to cleanly log out a user. Deleting the current user is neither user friendly and nothing we accidentally want a user to do.
> users: disable deleting/logging out current logged in account

- .github/workflows/docker-mirors.yml
We recently changed our services VM image setup to pull the grafana container image from a quay.io mirror [1] to circumvent pull rate limits. This isn't so temporary after all [2], there now seems to be no day of week or time of day when it works inside of the Red Hat VPN.
So dust off our old machinery for that [3].
[1] https://github.com/cockpit-project/bots/commit/ead7a20fb1ac61 [2] https://github.com/cockpit-project/bots/pull/7384 [3] https://github.com/cockpit-project/bots/blob/cb89c6e5cf47cef3/.github/workflows/daily.yml
https://github.com/cockpit-project/bots/blob/cb89c6e5cf47/sync-quay
----
Unfortunately this cannot be tested from a PR, as both `cron:` and `on_schedule:` workflows have to exist on main. I pieced this together from existing code (the referenced ones above plus …
> workflows: Regularly mirror docker.io/bitnami/grafana

- packit.yaml
The cloud images are missing [1] and not even COPR works.
Also move the s390x build from -development (which is 42 now, which doesn't work) to -latest-stable (which is 41), same as for the -aarch64 build.
[1] https://pagure.io/fedora-infrastructure/issue/12389
----
Sorry for jumping too fast here. We have to *release* to Fedora 42 already, but apparently there's no way to *test* there yet. I keep underestimating how much manual work still goes into opening a new release..
> packit: Re-disable Fedora 42

- src/tls/cockpit-certificate-helper.in
These are rejected as "too weak" by the "FUTURE" crypto policy. Let the tools decide about appropriate defaults rather.
Thanks to Renaud Métrich for finding this!
https://issues.redhat.com/browse/RHEL-78645
> tls: Stop hardcoding 2048 bit RSA key length

- test/common/webdriver_bidi.py
We use a `self.last_id` field to issue unique IDs for each async request we send to the browser, but only increment the ID after we get a successful reply.  That breaks in situations where we get no reply, or an exception occurs.
Sample the ID at the start and increment it immediately before `await`ing anything.
> test/common: don't reuse webdriver ids on exceptions

- test/common/webdriver_bidi.py
Firefox 135 enabled async BiDi event dispatching [1]. This causes some regression where sometimes input events never get a response [2], which often breaks e.g. cockpit-podman's `testFailingPodmanService`.
Re-disable async events for the time being to stabilize tests, until this gets debugged and fixed properly.
Fixes https://github.com/cockpit-project/cockpit-podman/issues/1999
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1922077
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1947402
----
I ran the podman test umteen times in a loop (in the latest tasks container with Firefox 135), and it seems stable now.
> test: Re-disable Firefox BiDi async events

- pkg/networkmanager/bond.jsx
- test/verify/check-networkmanager-bond
- allow setting also for balance-tlb / balance-alb modes
- read the current value
- remove when not set (it can't be set to an empty string)
- remove when switching to a non compatible mode
This fixes #21528
Patch tested on top of version 323 (~EL 9.5)
> networkmanager: fix primary bond option

- test/common/webdriver_bidi.py
Enable BiDi logs to stdout (`browser.dom.window.dump.enabled`) and set
the default log level to "Warn" [1]. This doesn't result in any extra
log noise, but gives us a an easy to find knob how to turn logging to 11
(like for https://bugzilla.mozilla.org/show_bug.cgi?id=1947402). It took
several days and back-and-forth with upstream to figure this out.
[1] https://firefox-source-docs.mozilla.org/remote/Prefs.html
> test: Configure Firefox BiDi logging

- src/cockpit/superuser.py
- src/ws/cockpitwebservice.c
- test/verify/check-static-login
ws stores the login password during the "explicit-superuser" init phase, so that the session can get administrative privileges automatically. This happens by noninteractively authorizing to the superuser bridge.
However, it does not make sense to try this more than once: If e.g. sudo or pkexec has another question, then that means something like "password is wrong", or "user must change their password", or "need 2FA token". It never makes sense to answer follow-up questions with *the same* password. It will never satisfy any of the above cases. Moreover, it causes repeated sudo/pkexec/etc. failures in the system logs, and can even lead to completely locking the user account if pam_faillock(8) is configured.
https://issues.redhat.com/browse/RHEL-32834
This PR fixes the problem in two …
> Only authorize once in noninteractive superuser responder

- test/common/testlib.py
- test/verify/check-superuser
> testlib: Workaround mysterious disappearing buttons

- containers/flatpak/install
Flathub already mirrors our screenshots to https://dl.flathub.org/media. Tell flatpak builder to rewrite the manifests to actually point to the mirror. This fixes the recent `appstream-external-screenshot-url` error.
Fixes #21643
> flatpak: Enable screenshots URL mirror

- pkg/systemd/terminal.jsx
While debugging an oops in Firefox with the Files testsuite, running it with a development build uncovered a situation where `onNavigate` is called with `user` being unset.
Initialising the eventListener after `setState` should remedy this.
> systemd: initialise eventlistener after user is available

- test/common/testlib.py
Don't silently ignore failing CDP commands. If they fail, their return value has an `error` field.
On success, just return the result, not the whole reply. There is only one place where we use it anyway (collecting coverage results).
---
This would have saved me some headache this morning with https://github.com/cockpit-project/cockpit-files/pull/973 . Now, if the command fails, it looks like this:
```
INFO:bidi.command:CDP ← '{"id": 0, "method": "Network.emulateNetworkConditions", "params": {"uploadThroughput": 50000}}'
INFO:bidi.command:CDP → {'id': 0, 'error': {'code': -32602, 'message': 'Invalid parameters', 'data': 'Failed to deserialize params.downloadThroughput - BINDINGS: mandatory field missing at position 28'}}
File …
```
> test: Fail on cdp_command() errors

- test/verify/check-storage-lvm2
Mocking the usage numbers is not reliable. The page renders (and undoes the mocking) at the wrong time.
Fixes #21639
> test: Unmount LVM2 thin volume before pixel test

- test/verify/check-selinux
The "zebra_write_config" boolean is no longer available in RHEL 10.
> test: Use daemons instead of zebras to test SELinux alerts

- pkg/lib/cockpit.js
Disambiguate the "http done" message: It was previously shown once for "client finished sending the request" (`done` channel message), and again for "request arrived and was successful". Show a more detailed message in both cases, and also include teh request method and path to disambiguate multiple parallel queries.
---
I noticed that while debugging podman in https://github.com/cockpit-project/cockpit-podman/pull/2024.
> lib: Improve http channel debug messages

- test/common/testlib.py
In general, per Liskov, it's not permitted to modify the signature of a function when overriding it.  Our MachineCase.setUp() override does this by adding a restrict= parameter.  That's strictly OK, since it adds a default value for that argument so there's no situation where a call to .setUp() on the base class would not also work with the overridden method.
Unfortunately, it does create a problem further down the line.  Since we add this parameter, it means (again, per Liskov) that all of our many subclasses (packagelib, netlib, storagelib, plus individual test cases) need to add it to, and none of them do that.  That's hindering our attempt to make this code strictly type-checked with mypy.
It looks like this was only ever used from the previous version of cockpit-composer, so let's …
> testlib: remove support for setUp(restrict=) kwarg

- pyproject.toml
- test/common/packagelib.py
Useful when working on integration tests and wanting to quickly see the required types for `createPackage`.
> test: type packagelib in strict mode

- .github/workflows/trigger-anaconda.yml
Upgrading the container from Fedora 40 -> 41 seems to have changed `dnf info` output. If multiple copr builds are available the `dnf info` query now returns:
```
[jelle@toolbx main]$ dnf info --refresh --repo='copr:*cockpit*' cockpit-bridge | awk '/^Release/ { split($3, v, "."); print substr(v[2], 0, 14)}' 2>/dev/null
Updating and loading repositories:
Copr repo for cockpit-project-cockpit- 100% |  12.5 KiB/s |   1.5 KiB |  00m00s
Repositories loaded.
20250307123226
20250310153201
```
This breaks as previously it expected on stamp and one stamp only. Switching to `repoquery` gives us the benefit that we don't need awk to match on `Release` but still doesn't help us with the limiting issues so a `tail` is still required.
---
Example where it is broken atm: …
> workflows: adjust stamp checking for dnf 5

- pkg/lib/patternfly/patternfly-5-overrides.scss
It seems Firefox fixed their longstanding bug, which caused the workaround in PatternFly (who adopted it from us) to no longer be relevant. I adjusted our own workaround, but it didn't apply as PatternFly also (at some point in time) changed the DOM so the selector no longer matched.
We'll want to communicate this with PF to get PF6 fixed. Possibly even PF5 too, as it apparently changed in Firefox recently, and therefore newer versions of Firefox will "break" the expected layout without addressing it in PF directly (or with a workaround in codebases).
Fixes #21671
> Consistently adjust the padding for all form selects

- test/browser/browser.sh
Robustify the amazon-ec2-utils workaround: Fedora 42 images don't seem to have /dev/nvme* any more, so don't fail on
> Failed to open the device '/dev/nvme*': No such device
Same fix as https://github.com/cockpit-project/cockpit-machines/commit/dcdf4988e4beb7
---
This broke https://github.com/fedora-selinux/selinux-policy/pull/2594 recently.
> tmt: Don't fail if /dev/nvme* does not exist

- pkg/lib/cockpit.js
Commit cdcef6bd2e259 improved debug messagse of `cockpit.http`. However, the `else` code path runs not only on success, but also if `resp` is false-y (i.e. the initial `null`), which can happen when the request fails before any response is received. Fix the crash on trying to read `null.status`.
---
See https://github.com/cockpit-project/cockpit-podman/pull/2047, it broke [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-2047-59010a46-20250312-092659-arch/log.html). no-test here as we don't use the http channel anywhere in cockpit. But I applied this to c-podman and it fixes the crash.
> lib: Fix http debug message crash

- packit.yaml
This has worked for some time, and is enabled in all our other projects, we just forgot about it here.
> packit: Enable fedora-42 test

- doc/protocol.md
The actual fsinfo implementation renamed user -> owner and modified -> mtime.
Closes: #21704
> doc: update fsinfo protocol documentation

- tools/debian/rules
Commit 5d70a2ae53b4ab moved cockpit-bridge to "Architecture: all", so we cannot run the package pytest in `dh_install-arch` any more as the package isn't build there. Move it to `-indep` instead.
Taken from downstream:
https://salsa.debian.org/utopia-team/cockpit/-/commit/6587a3326
---
This broke the Debian release: https://buildd.debian.org/status/logs.php?pkg=cockpit&ver=335-1 We don't cover that in our CI as we build all binary packages together, not separately per arch as the buildds do.
> tools: Fix Debian --build={all,any} FTBFS

- .github/workflows/trigger-anaconda.yml
The shell echo does not emit newlines making `tail` return the whole line while we want the last field.
```
[jelle@toolbx cockpit]$ echo $out  | awk '{ split($NF, v, "."); print substr(v[2], 0, 14)}'
+ awk '{ split($NF, v, "."); print substr(v[2], 0, 14)}'
+ echo cockpit-bridge 1.20250317122026634830.pr21719.9.g24dcebd11.fc41 cockpit-bridge 1.20250317131220797557.pr21719.9.g3a52e099d.fc41
20250317131220
```
> workflows: obtain the last field and not line of dnf output

- pkg/storaged/mdraid/create-dialog.jsx
- test/verify/check-storage-anaconda
- test/verify/check-storage-mdraid
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2352953
> storage: Use mdraid metadata version 1.0 when in Anaconda mode

- pkg/storaged/block/format-dialog.jsx
- test/verify/check-storage-anaconda
The Format dialog does remember the passphrase used to unlock a device in the "Reuse existing encryption" scenario, via the call to unlock_with_type.
However, later on it would erroneously call "remember_passphrase" with "undefined" during "maybe_mount", which would delete the previously remembered passphrase.  We avoid that now.
> storage: Fix passphrase remembering with "Reuse encryption"

- test/verify/check-storage-smart
fixes: #21728
Libblockdev changed how SmartFailing property is set. Now it is less strict with when a disk is considered as failing.
https://github.com/storaged-project/libblockdev/pull/1097
> tests: adapt disk assessment check

- pkg/lib/cockpit-components-file-autocomplete.jsx
Within the constructor for `FileAutoComplete` it was calling
`this.onPathChange`, but as the component wasn't running this was
never executed. Instead React complained in console about it being a
no-operation call.
In short, you cannot call `this.setState` in the constructor as the
component isn't mounted. So to fix this I just moved the call to the
`componentDidMount()`
> lib: Fix `FileAutoComplete` setState calls

- pkg/lib/patternfly/patternfly-6-overrides.scss
The PF Switch didn't have any changes to their multiplier variable which
meant that the rtl layout didn't look great.
Tracked upstream and note added in the code to indicate this.
https://github.com/patternfly/patternfly/issues/7414
> lib: Adjusted PF Switch for `rtl`

- src/tls/cockpit-certificate-helper.in
- test/verify/check-connection
`-config` replaces the entire default config with the given one. But the
default config is important in particular for setting the default key
size, in conjunction with crypto-policies.
Use `-addext` instead, which is additive and also much easier to use.
Thanks to Renaud Métrich for finding this, and to Clemens Lang for
pointing out `-addext`!
Note that this will still not *actually* respect crypto-policies in
current distro releases due to
https://issues.redhat.com/browse/RHEL-81724 and
https://bugzilla.redhat.com/show_bug.cgi?id=2349857, but it's a
prerequisite.
https://issues.redhat.com/browse/RHEL-81728
> tls: Stop ignoring default OpenSSL config

- .stylelintrc.json
- pkg/static/login.scss
This is supposed to look the same as the current login page so far. The goal was to port to CSS variables, especially with color, and sometimes with the padding.
I use a lot of custom variables, but started to drag in the PatternFly 6 tokens.
Most of the variables are used, but some, like the border radius, are not really used yet (but will be soon). And I added legacy ones for PF5-style roundedness for the time being.
I also needed to refactor a bit of the code to make it make more sense in places too, so variables could be used more effectively.
This makes it a bit of a mess. Apologies in advance.
Ideally, this should pass the pixel tests. If it doesn't, it might be close enough. (I may have shifted some colors a little here or there.) Let's see.
This is likely the bulk of the work to …
> login: Refactor to use variables and have more maintainable CSS

- pkg/packagekit/autoupdates.jsx
- pkg/packagekit/updates.jsx
- pkg/packagekit/utils.tsx
- test/browser/run-test.sh
- test/verify/check-packagekit
RHEL 10 removed tracer [1], and replaced it with a dnf4 backport of
`dnf needs-restarting`. This unfortunately does not have a
machine-readable API [2], so call it three times for "services", "manual
processes", and "needs reboot" and populate `restartPackages` with that.
This is not yet implemented for dnf5, but Fedora still has tracer, so
keep prefering tracer if it's available.
[1] https://issues.redhat.com/browse/RHELBLD-15667
[2] https://issues.redhat.com/browse/RHEL-56139
https://issues.redhat.com/browse/COCKPIT-1164
----
> packagekit: Add support for dnf needs-restarting

- pkg/kdump/kdump-view.jsx
- pkg/kdump/kdump.scss
- pkg/networkmanager/firewall-switch.jsx
- pkg/networkmanager/networking.scss
Fixes helper texts from this:
to this:
Similarly for the kdump switch and I kept the behavior where switch isn't present when kdump is unavailable on the system.
> pf6: use switch label instead of helper text

- test/verify/check-metrics
In our test infra the test flakes as we don't want on the toolbar to be rendered and thus we screenshot without the "Today" / "Graph visibility" dropdowns.
> test: Wait until toolbar is rendered before taking a screenshot

- pkg/shell/failures.tsx
Update early failure page to match new grid layout for iframes.
Relates-to: #21651
> failures: Update grid of early failure page

- pkg/storaged/mdraid/create-dialog.jsx
- test/verify/check-storage-anaconda
- test/verify/check-storage-mdraid
parted does not recognize mdraid format 1.0 on GPT tables,
so the cure was worse than the fix. Instead, anaconda will forbit
putting /boot on mdraid for the time being.
See https://bugzilla.redhat.com/show_bug.cgi?id=2355346
This reverts commit 5e0a4e48a0df9c46bf70a900d5951630eefa340f.
> Revert "storage: Use mdraid metadata version 1.0 when in Anaconda mode"

- src/tls/cockpit-certificate-helper.in
This had no deeper reason -- c-c-helper was introduced in commit 1cd8af0f5fdf copying it from the old cockpitcertificate.c. There it was introduced in commit eb1fc2028c as a mere typo/copy pasta due to the already inconsistent spacing in the existing CA parameters.
---
Leftover from https://github.com/cockpit-project/cockpit/pull/21773#pullrequestreview-2716855351
> tls: Fix inconsistent spaces in self-signed SSL certificate

- pkg/users/users.js
Morning! Just a small one, in cases where only root exists (otherwise it runs off the last uid it finds) the system will only grab login definitions from /etc/login.defs, this updates the behavior to also check against /usr/etc/login.defs if it's not overwritten
> pkg/user: Retrieve login def from /usr/etc/login.defs if exists

- pkg/shell/nav.scss
With the new font I accidentally set the boldness to be too bold. We can
default to just normal header bold and it'll look much better.
Before and after
Relates-to: #21651
> shell: Change hostname boldness

- pkg/lib/patternfly/patternfly-6-overrides.scss
With our migration to PF6 we noticed that there is an alignment issue
within PF Tables when it comes to expand button and the select checkbox
itself. They were aligned with the text in the bottom rather than in the
middle.
This fix changes the padding so that it all aligns as good as possible.
Two upstream issues created:
- https://github.com/patternfly/patternfly/issues/7423
- https://github.com/patternfly/patternfly/issues/7424
With the fixes:
Without the fixes:
--- 
As well as for normal (not compacted) table
With the fixes:
Without the fixes:
Relates-to: #21651
> patternfly: Override expand and select for tables

- pkg/lib/patternfly/_fonts.scss
- pkg/lib/patternfly/patternfly-6-cockpit.scss
There are scenarios such as running tests for a plugin with a stable cockpit-shell/ws.
Since those may be older, for now we should include the old fonts to make sure that the plugins.
This allows plugins to still utilize the Red Hat fonts when testing plugins on or before Cockpit v336.
Within cockpit-podman the tests are run for the plugin on a stable host cockpit host. But if you load in the latest changes from cockpit for your plugin you wouldn't otherwise be able to load the fonts correctly as the latest changes didn't provide our older way of loading Red Hat fonts but only included our new ones - which has a different directory structure.
This should help develop plugins at least until our next release containing PF6 is published.
> fonts: Load in the older fonts as a backup

- test/verify/check-storage-stratis
Between the stratis version in Fedora 41 and the one in updates-testing (3.8.0) the usage numbers aren't stable so mock them instead as we aren't interested in asserting stratis FS usage sizes.
---
This addresses https://github.com/cockpit-project/cockpit/issues/21782
> test: mock stratis usage numbers

- pkg/storaged/client.js
- pkg/storaged/stratis/stopped-pool.jsx
- pkg/storaged/stratis/stratis3-start-pool.py
- pkg/storaged/utils.js
- test/verify/check-storage-stratis
Stratis 3.8 has introduced V2 metadata for pools, and those pools need to be started with the R8 StartPool method. Let's hack our way to success.
- We need to use the "r8" revision of the D-Bus API to identify stopped V2 pools, but we can't unconditionally switch over to it since we still need to support older Stratises.
- Conditionally using r8 when available and falling back to r6 makes sense, but might turn into a bit of work.
- So the plan is to look into the r8 StoppedPools property to figure out whether a given pool needs the r8 StartPool method, and then use it.
- The r8 StartPool method takes a filehandle for delivering the passphrase (just like the r6 SetKey method), so we need a little Python helper to invoke it.
Also, StoppedPools has a "name" attribute now, which we should use …
> storage: Stratis 3.8 emergency fixes

- files.js
- pkg/shell/images/cockpit-icon-gray.svg
- pkg/shell/shell-modals.tsx
- pkg/shell/shell.scss
- test/verify/check-shell-menu
Should take care of the last few pf-v5 items inside of shell.scss while also giving us the about modal back to how it was before.
To make the svg work in both dark and light mode I've introduced a gray svg variant that uses `#A3A3A3`.
Ideally, if we could modify this during build-time that would be best, but that involves figuring out image manipulation with scss and I have no experience with that. So instead this introduces a new file for the purpose instead.
Light mode
Dark mode
Relates-to: #21651
> shell: Update about modal to PF6

- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-6-overrides.scss
- pkg/shell/nav.scss
- pkg/shell/shell.scss
Fixes include:
- Host switcher
- Navbar
- Stripe across the top
- Expand content area (when content area is set to ct page fill)
- Adjusts spacing between multiple plain cards (to add a little more space)
> shell: Improve PF6 styling

- test/verify/check-storage-anaconda
- test/verify/check-storage-stratis
Stratis was removed from archlinux, see:
https://github.com/cockpit-project/bots/issues/7624
> tests: skip stratis tests on archlinux

- pkg/storaged/btrfs/btrfs-tool.py
- pkg/storaged/client.js
Fixes #20852
The 'btrfs filesystem show' command works even for unmounted filesystems, but btrfs-tool.py skips the filesystem if it's not mounted. Therefore, we can run the command whether the filesystem is mounted or not to find its usage.
> storaged: Show correct usage for unmounted btrfs filesystems

- test/verify/files/mock-insights
* Card ID: CCT-722
Added a test with /host_exists API endpoint. This change ensures compatibility with the updated insights-client which uses the new /host_exists endpoint for checking whether the host is registered.
(cherry picked from commit [3a1b3f9](https://github.com/candlepin/subscription-manager-cockpit/commit/3a1b3f9416942679c506e0a835627f1e37ab16b6))
> test: mock-insights should have /host_exists endpoint

- test/verify/check-storage-stratis
[COCKPIT-1267](https://issues.redhat.com/browse/COCKPIT-1267)
The alert can not happen with V2 pools.
> test: Use a V1 pool in TestStorageStratis.testAlert

- pkg/storaged/btrfs/btrfs-tool.py
- pkg/storaged/client.js
- test/verify/check-storage-anaconda
Previously, if btrfs-tool would encounter a btrfs device that fails to mount that would kill the monitor and the whole storage page would fail to initialize.
Now, a failure to mount is expected and returned in the results of monitoring.  The error will be permanently recorded and no further mount attempts are made until Cockpit is reloaded.
An example for a failed mount is a multi-device btrfs filesystem that has too many devices missing at the time of mounting.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2358267
> storage: Allow btrfs mounts to fail while monitoring

- .github/dependabot.yml
- package.json
We ignored PF6 before as we didn't want to update it through dependabot.
Now with us using PF6 this is no longer necessary so we can instead just
change this to major version changes not being of interest to us for
dependabot stuff.
I also improved the reason for why we lock React major version updates.
Previously Sass was locked to a specific version and dependabot was
given instructions to ignore any updates to Sass. As we now support both
`@use` and `@forward` with no more `@import`s present in our own
codebase as well as the Patternfly codebase we can safely bump this.
> Dependabot changes and Sass bump

- doc/guide/cockpit-file.xml
- doc/protocol.md
- src/cockpit/channels/filesystem.py
- test/pytest/test_bridge.py
This is a regression from our port of the bridge from C to Python. The C bridge had a limit and as fsread1 is not blocking implemented this prevents issues of accidentally reading /dev/zero or /dev/sda which will fill up ram endlessly.
---
See 7c7ab45e3f2d4bd11a4e5c6716cbd645735dd694 and DEFAULT_MAX_READ_SIZE
> bridge: re-introduce the max_read_size limit

- pkg/lib/cockpit.d.ts
We provide four overloads for the file() function, two are for when syntax should be not be set and thus should use `never` and not `undefined`.
> lib: use `never` for incompatible options

- test/verify/check-shell-keys
For some layouts the dialog is not fully rendered when taking a screenshot. This occurred before in files and cockpit so we apply the same double screenshot workaround.
Example: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-827553b6-20250415-013220-fedora-41-daily/pixeldiff.html#TestKeys-testPrivateKeys-ssh-keys-dialog-medium
> test: workaround testPrivateKeys pixel test flake

- doc/man/cockpit.conf.xml
- src/websocket/websocketserver.c
- test/verify/check-connection
References #21738 #21727 
Changes the default matching behavior of cockpit `Origin` configuration to use fnmatch instead of string comparison, allowing for the use of wildcards and standard glob matching.
> ws: Support globs in configured origins

- doc/guide/cockpit-session.xml
- pkg/lib/cockpit.d.ts
- pkg/lib/cockpit.js
Let's soft deprecate cockpit.user() and teach our users about the existing alternative with a fallback option. The TypeScript shenanigans sparked this ;-)
> cockpit.user() deprecation

- doc/protocol.md
- pkg/base1/test-file.ts
- pkg/playground/test.html
- pkg/playground/test.js
- src/cockpit/channels/filesystem.py
- src/cockpit/jsonutil.py
- test/pytest/test_bridge.py
- test/verify/check-pages
Cockpit-files wants to support uploading or creating a file owned by the current directory which might be different from the logged in user.
For example as superuser uploading a database into `/var/lib/postgresql` which would be owned by `postgres` and the database file should receive the same permissions.
Leftovers:
> cockpit: support setting owner/group in fsreplace1

- pkg/shell/index.html
When using a reverse proxy with an UrlRoot browsers load the favicon from the root which would be a 404 or load the wrong favicon. We can work around this by explicitly loading the favicon from the static directory similar to how we load branding.css
Closes: #20580
> shell: Load favicon explicitly from static

- test/verify/check-selinux
The part that needs the audit-rules package, which is no longer available on RHEL.
> test: Skip part of TestSelinux.testTroubleshootAlerts on rhel-10

- test/verify/check-selinux
CentOS still has the audit-rules packages, it isn't installed anymore by default.
> test: Skip part of TestSelinux.testTroubleshootAlerts also on centos-10

- test/verify/check-static-login
- test/verify/check-users
It's the new name for ChallengeResponseAuthentication and the 50-redhat.conf file in Fedora 42 uses that spelling. This matters when fedora-coreos moves to F42 in https://github.com/cockpit-project/bots/pull/7636
> test: Allow KbdInteractiveAuthentication in sshd_config as well

- doc/guide/cockpit-dbus.xml
- pkg/lib/cockpit.js
In the long run our plan is to change how users consume cocpit's API probably like fsinfo
```
import { fsinfo } from 'cockpit/fsinfo'
```
So everything we have on our global cockpit object isn't helping and these two methods aren't used or useful.
> Deprecate more cockpit object functions

- test/verify/check-storage-stratis
Fedora 41 and updates-testing are back in sync.  The pixel changes were caused by the differences between the V1 and V2 metadata format, and it is not expected that this format will change again any time soon.
This reverts commit 30524ec9551e1aa5bb8bea0f3a927312ab8a54b6.
> Revert "test: mock stratis usage numbers"

- test/verify/check-metrics
- test/verify/check-pages
- test/verify/check-static-login
- test/verify/check-storage-swap
- test/verify/check-system-realms
https://github.com/cockpit-project/bots/pull/7732 brought back the packages.
> test: Re-enable FreeIPA, sssd, and pcp tests on debian-testing

- pkg/storaged/storage-anaconda.scss
Without this fix, the content area has a grey gap at the bottom. With this fix, the height works as intended.
Before:
After:
> storage: Fix gap in Anaconda mode

- pkg/lib/patternfly/patternfly-6-overrides.scss
Upstream issue filed @ https://github.com/patternfly/patternfly/issues/7440
Affects Anaconda too; PR for a local Anaconda workaround @ https://github.com/rhinstaller/anaconda-webui/pull/765 (merged already)
Bugzilla issue (filed against Anaconda): https://bugzilla.redhat.com/show_bug.cgi?id=2357172
This affects all PatternFly projects, especially when there are several actions in a modal and the buttons have long text (which may be caused by languages), and especially on smaller-width modals.
> pf: Don't clip modal content when content would otherwise overflow

- pkg/storaged/btrfs/device.jsx
- pkg/storaged/lvm2/physical-volume.jsx
- pkg/storaged/mdraid/mdraid-disk.jsx
- pkg/storaged/pages.jsx
- pkg/storaged/storage.scss
- pkg/storaged/stratis/blockdev.jsx
- test/common/storagelib.py
- test/common/testlib.py
- test/verify/check-storage-resize
The Storage application of Cockpit is driven by a big tree of "storage objects" and the user navigates this tree mainly by selecting representations of these objects in lists.
The page for a storage object contains links back to its direct and indirect parents (in a breadcrumb trail), and a table that lists its children with a short description. There are also tables that list storage objects that are related to the current object in other ad-hoc ways, like the physical volumes of a volume groups, or the snapshots of a btrfs subvolume.
Currently, selecting a child from such a list in a table is done by clicking anywhere on the whole row. The row has a hover animation to indicate this.
However, a row also has a kebab dropdown with actions related to the storage object represented by that …
> storage: Navigate via explicit links in tables

- pkg/lib/superuser.js
Now "superuser" is a proper EventSource and we can use it with our "useEvent" hook in TypeScript.
> lib: Help TS infer a better type for "superuser"

- .github/workflows/release.yml
With this we should now automatically get flathub PRs created
automatically without us having to click it manually.
`gh` CLI is available in GitHub workflows in general and can be used
without issues.
> release: Automatically create flathub PR

- pkg/systemd/overview-cards/healthCard.tsx
- pkg/systemd/overview-cards/smart-status.jsx
- test/verify/check-storage-smart
Shows entry in Health card on the overview page about failing disks. Clicking on the warning redirects to the storage page where failing disk is highlighted with the same danger icon.
> Add SMART status to overview page

- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-6-overrides.scss
- pkg/networkmanager/networking.scss
- pkg/shell/hosts_dialog.jsx
Verified that this works on tables located on accounts page, account detail, metrics and hw info page. Also crosschecked with fedora-coreos where this issue was discovered.
The `@media screen ...` condition in css is not required and wouldn't work correctly on the metrics page in network interfaces card. To work around this the css selector specifically targets `::before` pseudo element which is only present once the table switches to the mobile layout.
> patternfly: override font-weight table header in mobile layout

- test/pytest/test_bridge.py
Latest Ubuntu is moving to Rust coreutils [1] and as intermediate step renamed the original coreutils to gnu-coreutils [2] and thus /usr/bin/cat is now an alternatives link to "gnucat". This broke our `test_channel[SubprocessStreamChannel]` test which assumes that running `cat` will actually be an executable which is named "cat".
Relax this by accepting a "cat" suffix.
[1] https://discourse.ubuntu.com/t/carefully-but-purposefully-oxidising-ubuntu/56995
[2] https://launchpad.net/ubuntu/+source/coreutils/9.5-1ubuntu2
----
This should fix the [Ubuntu questing build failure](https://launchpad.net/ubuntu/+source/cockpit/338-1/+build/30716158), see the [detailed log](https://launchpadlibrarian.net/793929803/buildlog_ubuntu-questing-amd64.cockpit_338-1_BUILDING.txt.gz).
> test: Relax "cat" executable assumption for current Ubuntu

- .github/workflows/build-ws-container.yml
- containers/ws/release.sh
This PR implements multi-platform images for the `ws` container as requested in #17569. It is inspired by both the implementation and review comments of #17935, but excludes changes in the documentation or unrelated scripts (I do support those changes, but assume it is better to handle those in a separate PR).
I wish to highlight the following changes:
> [!WARNING]  
> The section below is outdated.
<details>
- Multi-platform images are build by Docker Buildx for `linux/amd64` and `linux/arm64` by default
- ~Due to the differences of syntax of commands required to build multi-platform images between Podman and Docker, the script is no longer compatible with Podman. If support for Podman is required, I will have to rewrite some commands and this will likely result in a more complex script …
> Provide cockpit/ws image for arm64

- src/cockpit/osinfo.py
Debian 13 goes into release freeze, and its os-release now has a proper VERSION_ID.
---
This should fix https://github.com/cockpit-project/bots/pull/7795
> bridge: Support packageless session on Debian 13 "trixie"

- src/cockpit/channels/filesystem.py
- test/pytest/test_bridge.py
For cockpit-files it is useful to know if the current watched directory or for example a text file is editable for the current user. Doing this based on the existing file permissions doesn't take ACL's into account.
The `access` syscall only handles one access check (read/write/execute) per call making it rather inefficient to check for multiple scenario's, so that's why there are separate attrs depending on what the user want so in worst case we only add 1 extra syscall.
As Python does not support AT_EMPTY_PATH there is a workaround to read the file from /proc/self this is only required for reading the access bits of the current watched directory.
Closes: #21596
> cockpit: support access attributes in fsinfo

- .github/workflows/build-ws-container.yml
After #21969 was merged we started getting build failures. This relates
to the login not getting any environment variables due to the
environment for the job not being set. So since we have no context, no
variables are provided.
To fix this we just repeat the environment to this step as well.
Github-action: https://github.com/cockpit-project/cockpit/actions/runs/15167058371/job/42647647203
> ci: Add quay.io environment to build ws container

- .github/workflows/release.yml
This should now work with automatic flathub PR creation. Though we'll
see if it actually has permissions or not to create PRs in different
repos. We might need a different type of token.
> flathub: Add `GH_TOKEN` for auto-PR creation

- .github/workflows/build-ws-container.yml
Publishing happens in a separate "manifest" step so we won't need quay login credentials there.
> github: drop quay secrets in build step

- pkg/networkmanager/network-interface-members.jsx
- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/btrfs/subvolume.jsx
- pkg/storaged/overview/overview.jsx
- pkg/systemd/logs.jsx
- test/verify/check-storage-iscsi
Some typos, some extra spacing, and wrong usage. These are all comments
from Weblate that I'm addressing.
> i18n: Fix translation strings

- pkg/storaged/crypto/keyslots.jsx
- pkg/storaged/lvm2/volume-group.jsx
- pkg/storaged/utils.js
- test/common/storagelib.py
- test/verify/check-storage-luks
- test/verify/check-storage-lvm2
Because that might break the next boot.
Fixes #20815
> storage: Warn when renaming the volume group that contains the root filesystem

- examples/long-running-process/index.js
- pkg/lib/long-running-process.js
- test/verify/check-examples
When I was creating a module for cockpit that used the LongRunningProcess Example I found that while debugging the module I made there wasn't a way to reset the process without going to the terminal (with the proper command) to reset the process if it failed.
So, I created a way and thought I would share it.
> examples/long-running-process: Add reset

- test/common/make-bots
External projects like anaconda-webui, which maintain their own node-cache repository, need to set GITHUB_BASE to their project for git-utils to work as expected.
However, for shared repositories like 'bots', GITHUB_BASE should not be allowed to get overriden.
> infra: test/common/make-bots: override GITHUB_BASE

- pkg/storaged/crypto/keyslots.jsx
It needs a Tbody and isCompact is not a thing.
> storaged: Fix CryptKeyslots Table usage

- .github/workflows/release.yml
Adds extra arguments to the `gh pr create` so it selects from which
project's fork's branch to which remote to create the PR for.
> flatpak: Extra GH arguments

- test/common/netlib.py
- test/verify/check-metrics
On RHEL-10-1 we OOM the machine when running the Grafana client tests bumping the memory requirements showed there was barely enough free memory on 512 MB
```
free -m
total        used        free      shared  buff/cache   available
Mem:             744         499         105           2         245         245
```
---
This aims to solve [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-22065-1b7ae186-20250603-180251-rhel-10-1-other/log.html).
Draft for now as I assume we need to discuss the memory adjustments a bit :)
> test: disable packagekit pre-loading in expensive tests

- pkg/lib/cockpit/fsinfo.ts
Follow up from 6ffaa9cdfd4e40d764470cfe570fe4e4bae0d97c
---
Woops :sweat_smile:
> cockpit: fsinfo: add missing access types

- test/pytest/test_samples.py
> pytest: ignore mount sampler in unit tests

- package.json
- pkg/lib/cockpit-components-password.tsx
This is used in Cockpit machines so is useful to have typed. The only notable change is converting `passwordStrength` from `undefined | number`, or as the code claims possibly a string to a number with a default value of -1. When `passwordStrength` is -1 the strength meter is not shown.
> lib: type cockpit-components-password

- test/verify/check-storage-vdo
> Test VDO support on RHEL 10

- test/pytest/test_bridge.py
Ubuntu 25.04 is moving to Rust coreutils. This was already addressed in commit c2a96d076f9d285718 where `cat` resolved to `gnucat`, but now it moved further to actual Rust coreutils by default. So give up on /proc/pid/exe, and instead read and assert the command line.
This fixes the build failure:
https://launchpad.net/ubuntu/+source/cockpit/341.1-1/+build/30965169
---
See the [build log](https://launchpadlibrarian.net/801954259/buildlog_ubuntu-questing-amd64.cockpit_341.1-1_BUILDING.txt.gz). I could reproduce this in a Ubuntu questing toolbox, and it works now.
> test: Relax "cat" executable assumption further

- test/verify/check-ws-bastion
passt 0^20250507.geea8a76-1.fc42 → 0^20250611.g0293c6f-1.fc42 has a regression: Starting containers without a running logind session fails.
Avoid that by enabling lingering. Then we also get a proper XDG_RUNTIME_DIR, which is cleaner anyway.
---
Blocks/fixes https://github.com/cockpit-project/bots/pull/7938. no-test, as TestWsBastionContainer only runs on fcos anyway.
Not naughtying, I have a gut feeling that this bugzilla will become a wontfix..
I [triggered a run against the refresh](https://cockpit-logs.us-east-1.linodeobjects.com/pull-22156-ca805d7a-20250701-075658-fedora-coreos-other-bots%237938/log.html) and it passed.
> test: Fix TestWsBastionContainer for current passt version

- .cockpit-ci/container
While the tag still exists, `podman pull` now fails with "manifest unknown". move to 2024-03-18, which seems to work.
[1] https://github.com/cockpit-project/cockpituous/pkgs/container/tasks/191826427?tag=2024-03-16
----
Should fix https://github.com/cockpit-project/bots/pull/7942
> [r8] cockpit-ci: Move tasks container to 2024-03-18

- src/bridge/askpass.c
- src/bridge/cockpitrouter.c
- src/ws/cockpitwebservice.c
- test/verify/check-static-login
This backports PR #21617 to RHEL 8, with translating the conceptual Python changes to the C bridge.
https://issues.redhat.com/browse/RHEL-96193
> [rhel8] Only hand out the saved password to authorize messages once

- pkg/apps/application-list.jsx
- pkg/apps/application.scss
- test/verify/check-apps
With this we fix the alignment of applications to remove the centering
and instead change the alignment of the app icons themselves. This will
improve the mobile layout as well and ensure that the text, icon, and
button for installing/removing is all aligned correctly.
Fixes: #21878
Before:
After:
> apps: Fix alignment of application list

- pkg/kdump/config-client-suse.js
- pkg/kdump/config-client.js
- pkg/kdump/kdump-view.jsx
- test/verify/check-kdump
Because of sysconfig/kdump only having a flat `KDUMP_SAVEDIR` field, we can't pull back out the `Directory` field since it's concatenated to one path, so instead we should just let it run off only the `Export` field
> kdump: Remove nfs directory when using sysconfig configuration style

- pkg/lib/patternfly/patternfly-6-overrides.scss
We had a bit too much spacing between cards that caused issues with
storage mobile-view. Reverting this to how we had it before.
This also removes the border between cards for the storage page
and instead only keeps them for the table-style of cards we have between
storage types.
Future improvements would be to
- Remove usage of Card for Storage page sections or embrace it fully
- Remove usage of Card for mobile-view rows and instead use Table or
Data list component
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2366666
> storage: Fix section spacing

- test/common/testlib.py
- test/verify/check-metrics
TestHistoryMetrics.testEvents has been flaking in our CI with some flaking pixels in the rounded corners of the alert and card. Since this is a larger image it makes sense to bump the accpetable flakyness level for this test alone.
> test: make pixel tolerance configurable in pixel tests

- .github/workflows/build-ws-container.yml
The previous command checked out the latest tag across *all* branches, but that's wrong -- it currently catches 310.5 from the rhel-8 branch. We want to get the latest tag on main.
---
This is what broke the workflow a few days ago: https://github.com/cockpit-project/cockpit/actions/workflows/build-ws-container.yml
I [ran the workflow manually on this branch](https://github.com/cockpit-project/cockpit/actions/runs/16108853626/job/45448896749), it correctly checked out 341.1 and succeeded.
> workflows: Fix latest tag checkout in build-ws-container

- test/verify/check-system-services
It does at least on Ubuntu 22.04. This was lazy. Fix this by introducing our own static test service.
Fixes #22158
---
[example log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-22113-ba3257c4-20250701-072009-ubuntu-2204-other/log.html), also high on the weather report.
> test: Stop assuming user systemd-exit.service never runs

- pkg/lib/journal.css
- pkg/lib/page.scss
- pkg/systemd/logs.jsx
- pkg/systemd/logs.scss
- pkg/systemd/services.scss
- pkg/users/accounts-list.js
- pkg/users/users.scss
I found a lot of little issues and have been working on them on the side over the past few days.
Each fix is separated into a separate commit. None are really related to each other, but each is rather small and I thought they should go into a clean-up PR. We can split it apart if necessary, or keep them each as separate commits in this PR and land them together.
> PatternFly 6 fixes

- packit.yaml
- test/verify/check-storage-mdraid
- test/verify/check-system-realms
Mixing scsi_debug and loop does strange things on CentOS 9 aarch64
Testing Farm instances, and the SCSI disk doesn't get detected properly
as part of the array.
This papers over a bug, but we are testing the Cockpit logic here, not
weird low-level kernel bugs. See #22143 for debug information.
---
Fixes the C9S aarch64 failures, see #22143 for debugging details.
> test: Use loop devices in TestStorageMdRaid on C9S/aarch64

- pkg/lib/journal.css
Truncating long log lines at the end for æsthetical reasons is detrimental: The most interesting information is often at the end, and there is no way to see the full log.
This was already introduced in the initial commit 87325b96bc3.
Fixes #21892
----
No wraps and looks like this:
> lib: Wrap journal log lines

- test/verify/check-metrics
Wait until both the graph and the toolbar are fully rendered after each layout change.
Fixes #22189
----
Locally it is stable now. I could reproduce the bug locally before. On CI it [still fails](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22204-17a02789-20250714-131232-fedora-42-other-5/log.html), but at least less than before.
> test: Stabilize TestHistoryMetrics.testEvents pixel test

- test/run
- test/vm.systemd-main
The systemd project maintains its own repository of `main` builds on OBS (Open Build Service). Testing against this repository allows us to catch regressions before a major systemd release or test out new features included in `main`.
---
* `b.reload()` now logs out our logged in user on the hardware details page.
* > warn: failed to connect to session bus: [Errno 123] sd_bus_default_user: No medium found
* Stopping 'systemd-logind.service', but its triggering units are still active:
systemd-logind-varlink.socket
* Failed to set time: Requested to set the clock to time before build time, refusing.
> test: support testing against systemd's main repository

- pkg/systemd/overview-cards/tuned-dialog.jsx
Currently if tuned isn't installed there is no message under `Performance Profile`
This is due to the type juggling of `oldServiceState.current != tunedService.state` juggling `null` and `undefined`
Instead we should be strictly checking the typing so we can be sure `update()` has been called at least once so we can show "Tuned is not available" to the user
> systemd: ensure update() is called at least once for tuned-dialog

- test/browser/browser.sh
- test/vm.install
Recent shadow-utils broke rootless containers [1][2]. This is under heavy debate, but until then unbreak our tests by restoring the working configuration and re-adding subuids to our admin user.
Fixes #2203
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2382662
[2] https://issues.redhat.com/browse/RHEL-103765
----
This is the same hack as in https://github.com/cockpit-project/cockpit-podman/pull/2205 and https://github.com/cockpit-project/cockpit-podman/pull/2209 . Cockpit's tests also  use podman, this unbreaks https://github.com/cockpit-project/bots/pull/8042
> test: Restore subuids to unbreak rootless podman

- doc/protocol.md
- pkg/static/login.js
- src/common/Makefile-common.am
- src/session/session.c
- test/verify/check-static-login
When trying to log in with a shell that does not understand `exit 71`
(our litmus test for "reasonable shell"), this was previously really
hard to understand/debug: The journal did not show anything bad other
than that the session only lasted a blink of an eye, and the login page
just said "permission denied".
Log a proper warning to the journal that explains what happens.
Let the login page show "Unsupported shell. Check the journal for
details." We are past authentication at this point, so we can afford
giving away that piece of information.
Fixes #20741
----
Looks like this now:
That screenshot reveals that we broke the background in the alert. I'll check if I can fix that quickly.
And the journal says
```
cockpit-session[18957]: cockpit-session: User admin shell (/bin/false) does not …
```
> login: Improve error message for unsupported shells

- test/verify/check-apps
- test/verify/check-packagekit
The generalized hack in commit 2c299e56f2d0 fixed most PackageKit tests on arch. The only exception is TestUpdates.testBasic, which fails because apparently the alpm PackageKit backend does not support cancelling. We may refine that test in the future.
`TestApps.testBasic()` also works in principle (locally and in some CI runs), but is very unstable in CI. Keep this skipped for now.
> test: Enable most PackageKit tests on arch

- test/common/storagelib.py
- test/image-prepare
- test/verify/check-pages
- test/verify/check-storage-anaconda
- test/verify/check-storage-btrfs
- test/verify/check-storage-format
- test/verify/check-storage-hidden
- test/verify/check-storage-luks
- test/verify/check-storage-mdraid
- test/verify/check-storage-mounting
- test/verify/check-storage-msdos
- test/verify/check-storage-nfs
- test/verify/check-storage-partitions
- test/verify/check-storage-resize
- test/verify/check-storage-stratis
- test/verify/check-storage-used
We previously had a wild organically grown mix of test mount directories like `/mnt/`, `/foo1`, `/run/foo`, `/mounts` etc., which are problematic:
* Using top-level directories does not work on a read-only root file system (ostree, bootc)
* /mnt (and /home) is a symlink to /var/... on OSTree, which breaks test expectations.
* Tests leave these directories behind, breaking re-runs and reproducibility.
Replace all of these with a consistent `self.mnt_dir`, which gets cleaned up for nondestructive tests.
The heavy lifting of this patch was done by Cursor and Claude AI.
---
This is a prerequisite for enabling storage tests on our centos-9-bootc image as well as in TF (see PR #22256)
This changes pixels, so let's land after #22252
> test: Refactor mount directories in storage tests

- test/verify/check-metrics
Since commit 109357f6ba62542, our centos-9-bootc test now *does* have cockpit-storaged, so adjust the special case similar to what that commit already did to TestPages.testMenuSearch.
Do the disabling of the Storage page in a "/usr/ is read-only" friendly way.
---
Fixes [this regression](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22264-80860d34-20250730-134703-centos-9-bootc-other/log.html#29).
> test: Fix TestCurrentMetrics.testDiskIO on bootc images

- test/verify/check-networkmanager-wireguard
Starting this test with limited memory runs into dnf-restart memory issues on RHEL-10-1 which flakes around ~ 20% of the time.
---
See also 7da43690498ded402dcc0928d5c6aafeac21d949
> test: disable preloading of packagekit for Wireguard test

- test/verify/check-metrics
To eventually support VSOCK for running commands in the virtual machine we can no longer use SSHConnection to establish an administrator ssh session. Additionally SSHConnection can be refactored without breaking our tests nor do we rely on `m.ssh_port` or other machine properties.
There are two separate methods required to run commands, one `run_as_admin` which returns the exit code and waits on the command to complete. For `podman run -d` we need the command to "detach" and for that we have to start the command as an unit and inspect if it runs successfully ourself.
> test: use systemd-run for running podman as admin user

- pkg/lib/cockpit.d.ts
With these changes, my https://github.com/martinpitt/cockpit-podman/tree/typing branch is happy :grin:
> cockpit.js: Consistently type `superuser` channel options, add missing cockpit.http().close() to type definitions

- plans/all.fmf
- test/browser/main.fmf
- test/browser/run-test.sh
- test/common/testlib.py
- test/verify/check-storage-anaconda
- test/verify/check-storage-iscsi
- test/verify/check-storage-luks
- test/verify/check-storage-multipath
- test/verify/check-storage-stratis
- test/verify/check-storage-vdo
Final bit of https://issues.redhat.com/browse/COCKPIT-1214
I'll also check how well [centos-9-bootc/storage](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22270-3b9adbd7-20250801-123916-centos-9-bootc-storage/log.html) works on our CI.
> tmt: Enable extra storage tests on image mode, and storage scenario in our CI

- pkg/lib/patternfly/patternfly-6-overrides.scss
Within plain PF cards where we have elements with visible borders near
the start or end of the card it has a chance to crop the border. For
most components this happens when we don't use the card body itself,
such as when we have a table within a card and don't want the spacing
from the card body.
To fix this we just remove the border radius so that it will be pretty
much like normal.
Fixes: https://issues.redhat.com/browse/RHEL-97183
> css: Fix table row border in cards

- pkg/storaged/dialog.jsx
- test/common/storagelib.py
- test/verify/check-storage-stratis
Stop using `:contains()` for selecting a member of a compound device. This fixes a common flake where `add_loopback_disk()` creates e.g. /dev/loop1 and /dev/loop10, and trying to select the former becomes an ambiguous selector.
To make that robust, add a `data-space-name` attribute to each list item. Use that as the `key` as well, to get an actually sensible name (like "/dev/loop1") instead of some object hash gibberish.
It would be really nice to use these in the actual DataListCheck `id` attribute, but IDs like `/dev/loop0-row-checkbox` work poorly -- so keep the object hash for these.
Spell out the device name in `TestStorageStratisReboot.testPoolResize` to work with the strict selection.
---
This fixes our top flake on the [weather …
> test: Make "select-space" selectors precise

- .github/workflows/release.yml
Should be possible to use a custom token as is described in other
repos.
Related-to: https://github.com/flathub/org.cockpit_project.CockpitClient/pull/65#issuecomment-3162124090
> ci: Use custom token for Flathub PR creation

- pkg/systemd/logs.jsx
Within logs you could sometimes get a race condition or unexpected
behaviour that caused the identifiers to be `undefined` and us calling
`Array.prototype.include()` on it which causes a `TypeError`. Fixing
this as best we can (for now) we can initialize it to an empty array
instead.
I have yet to be able to reproduce this issue, so instead this commit
mitigates the issue as best as possible in hopes it also fixed the issue.
Related-to: #22311
> logs: Initialize identifiers as empty array

- pkg/lib/patternfly/patternfly-6-overrides.scss
This removes a bunch of overrides that no longer seem to serve a
purpose. Tests will indicate otherwise.
Todo
> css: Remove Patternfly overrides

- pkg/base1/test-path.ts
- pkg/lib/cockpit-path.ts
Just like `basename /home` returns `home` our JavaScript implementation should do the same.
> lib: basename: /home translates into home

- tools/cockpit.spec
Currently within Copr on our `@cockpit/cockpit-preview` we have releases
for EPEL 9 and 10. Both of which require `subscription-manager` to be
installed.
However, this isn't guaranteed to be RHEL or CentOS Linux as we also
have non-subscription related CentOS Linux itself, we also have the
CentOS forks Alma Linux and Rocky Linux in which neither can provide
`subscription-manager`.
Demoting this from `Requires` to `Recommends` should help with
installing EPEL releases from @cockpit/cockpit-preview` within Alma and
Rocky distributions.
Related-to: https://discussion.fedoraproject.org/t/3249/2
> copr: Set subscription-manager as weak dep

- .github/workflows/release.yml
With `gh` it does not allow us to use `GITHUB_TOKEN` and `GH_TOKEN` at
the same time. For some reason this isn't explained in the docs and
instead there is an issue on GH CLI repo that recommends just setting
`GITHUB_TOKEN` itself instead.
Fingers crossed, otherwise there is another solution to try where we can
explicitly use `--with-token` argument but we'd have to provide it
through stdin.
Related-to: https://github.com/cli/cli/issues/2922
Related-to: https://github.com/FreeTubeApp/FreeTube/blob/865a4a2ab0b61062d36a223cd52f966f9a0d4306/.github/workflows/flatpak.yml#L119-L121
Related-to: https://cli.github.com/manual/gh_auth_login
> ci: Use `GITHUB_TOKEN` instead of `GH_TOKEN`

- src/cockpit/osinfo.py
Corresponding to our current test map.
---
This fixes [these failures](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-8161-f8e502d7-20250826-050334-fedora-43-expensive-cockpit-project-cockpit/log.html) from https://github.com/cockpit-project/bots/pull/8161
> bridge: Support Fedora 43 for beibooting, drop 40

- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-6-overrides.scss
- pkg/networkmanager/mtu.jsx
- pkg/networkmanager/networking.scss
Since 2 years ago there has been an override to make the Patternfly
radio and checkbox components aligned correctly. This is no longer
necessary and instead causes alignment issues with PF6 styling.
Removing these overrides will save headaches later on instead of trying
to come up with a fix for it that we don't need.
> css: Revert checkbox radio override

- pkg/lib/page.scss
- pkg/lib/patternfly/patternfly-6-overrides.scss
- pkg/shell/hosts.tsx
- test/common/test-functions.js
- test/verify/check-shell-host-switching
**TL;DR:** 
- We set `display: none` to `hidden` DOM elements which caused animations to not function properly
- Animations slowed down to 25% to make the issue easier to spot:
[video of the selected tab not working](https://github.com/user-attachments/assets/c78cabfe-da3d-4d6e-a5f6-b1b73acdf48b)
<details>
<summary>css: Remove `display: none` from `[hidden]`</summary>
This was a valid change back in the day due to the way `hidden` DOM
elements were being used and handled by the browser. It is still a
normal syntax for indicating that an element is not being displayed (but
still rendered), but there is no elements from Patternfly or otherwise
that should be popping in or being rendered weirdly anymore.
All relevant bugs were fixed in Patternfly v4 and v5.
One of the main benefits of …
> css: Fix Tab selection not showing

- pkg/lib/cockpit.js
- pkg/storaged/client.js
- pkg/storaged/pages.jsx
- pkg/storaged/stratis/create-dialog.jsx
- pkg/storaged/stratis/pool.jsx
- pkg/storaged/stratis/stopped-pool.jsx
- pkg/storaged/stratis/stratis3-start-pool.py
- test/verify/check-storage-stratis
Demo: https://www.youtube.com/watch?v=VUSnt6fLTwk
Screenshot of new "Encryption tokens" card:
> storage: Full support for Stratis V2 pools

- pkg/networkmanager/firewall.jsx
Within the actions column for services added to a zone there was no
`aria-label` nor screenreader text added. This is now added and matches
other areas where Actions are being used.
Fixes the PF console log output that says:
> Th: Table headers must have an accessible name. If the Th is intended
> to be visually empty, pass in screenReaderText. If the Th contains
> only non-text, interactive content such as a checkbox or expand toggle,
> pass in an aria-label.
> firewall: Add screenreader text for Actions column

- test/verify/check-storage-smart
udisks 2.10.x only gets selected bug fixes [1], it does not (and probably will not) get the SMART mocking. That's only for the next minor release. 2.10.90 is the first beta which should work.
[1] https://github.com/storaged-project/udisks/commits/2.10.x-branch/
---
Fixes https://github.com/cockpit-project/bots/pull/8199
> test: Fix udisks version comparison

- test/browser/browser.sh
- test/vm.install
This was fixed in Fedora-41 and CentOS/RHEL 10.
> test: drop RHEL 10 container firewall workaround

- pkg/storaged/block/format-dialog.jsx
- pkg/storaged/dialog.jsx
When fields fail validation, the first of them is scrolled into view. Additionally, when the encryption fields of the Format dialog are revealed, they are scrolled into view.
https://bugzilla.redhat.com/show_bug.cgi?id=2264540
Demo: https://www.youtube.com/watch?v=POn3lDoPJOc
> storage: Scroll dialog fields into view as needed

- test/verify/check-storage-unused
- test/verify/check-storage-used
The block device isn't immediately read for use after parted. We need to wait for it to be present *and* scanned by udev, otherwise mkfs/cryptsetup reject it.
Fixes 75% test failure on our CI.
----
That's our worst [weather report cloud provider](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7&test=test%2Fverify%2Fcheck-storage-unused+TestStorageUnused.testUnused):
[example log](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-20060-e56e3023-20250904-094416-debian-testing-storage/log.html)
> test: Fix race condition in TestStorageU{,nu}sed.testUnused

- pkg/storaged/storage-anaconda.scss
Fix an edge case where the dropdown menus for modifying partitions get hidden under certain conditions[1]. This fixes a blocker for Fedora 43[2].
Opening as a different PR as #22381 would depend on changes on upstream Patternfly and #22413 can't be merged yet[3].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2388785
[2]: https://pagure.io/fedora-qa/blocker-review/issue/1873
[3]:  https://github.com/cockpit-project/cockpit/pull/22413#pullrequestreview-3200622748
Resolves: INSTALLER-4272
> storage: anaconda: dropdown menus hidden behind non-scrollable content

- test/common/testlib.py
- tools/cockpit.spec
- tools/debian/control
Fixes #21602
The packaging tweaks are too small to warrant their own PR, but piggy-backing here is fine.
> testlib: Fix compatibility with current pytest; some small packaging tweaks

- pkg/packagekit/updates.jsx
- pkg/packagekit/updates.scss
Adds a few CSS rules and modifies the styling a bit to ensure that we
get truncated text for packages that have long package names and also
get a consistent width of the progress bar so nothing moves around.
Should make the experience much easier and the switch is now functional.
Fixes: https://github.com/cockpit-project/cockpit/issues/22415
> packagekit: Consistent update width

- test/common/testlib.py
The default 10 seconds seem to be too tight, especially for the ubuntu-2204 and ubuntu-2404 images.
> test: Increase timeout of Browser.open

- files.js
- pkg/base1/test-http.js
- pkg/playground/manifest.json
- pkg/playground/packagemanager.html
- pkg/playground/packagemanager.tsx
- test/common/packagelib.py
- test/verify/check-packagekit
- test/verify/check-storage-nfs
Test various install dialog scenarios in a controlled environment in preparation for supporting and verifying our dnf5daemon backend implementation.
> playground: add test page for the install dialog

- package.json
- pkg/networkmanager/interfaces.js
- pkg/networkmanager/ip-settings.jsx
- pkg/networkmanager/network-interface.jsx
- pkg/networkmanager/utils.js
- pkg/networkmanager/wireguard.jsx
- test/verify/check-networkmanager-basic
- test/verify/check-networkmanager-wireguard
replace the following endpoints:
`ipv{4, 6}.addresses` -> `ipv{4, 6}.address-data` + `ipv{4, 6}.gateway`
`ipv{4, 6}.routes` -> `ipv{4, 6}.route-data`
`ipv{4, 6}.dns` -> `ipv{4, 6}.dns-data`
---
The `ipv{4, 6}.gateway` property no longer supports setting multiple gateways and only allows to set one. With the `addresses` endpoint this used to be an array of `(address, prefix, gateway)` and network manager [would pick first non-zero gateway](https://bugzilla.gnome.org/show_bug.cgi?id=682946#c6).
> networkmanager: replace deprecated API endpoints

- pkg/sosreport/sosreport.jsx
The default limit of `fsread` is 16MB to prevent JavaScript code to accidentally read too much data and eat up memory. The sosreport uses a raw channel and a clickable link so the data transfer is handled by the browser without concerns of JavaScript memory usage.
Since Cockpit 337 the bridge supports setting `max_read_size` to -1 which bypasses any size limitations.
https://issues.redhat.com/browse/RHEL-115165
https://issues.redhat.com/browse/RHEL-115185
---
> sosreport: don't limit sos report download size

- pkg/lib/_internal/dnf5daemon.ts
- pkg/lib/_internal/packagekit.ts
- pkg/lib/_internal/packagemanager-abstract.ts
- pkg/lib/cockpit-components-install-dialog.jsx
- pkg/lib/cockpit.d.ts
- pkg/lib/packagekit.js
- pkg/lib/packagemanager.ts
- pkg/metrics/metrics.jsx
- pkg/networkmanager/dialogs-common.jsx
- pkg/storaged/lvm2/create-logical-volume-dialog.jsx
- pkg/systemd/overview-cards/realmd.jsx
- test/common/packagelib.py
- test/verify/check-metrics
- test/verify/check-packagekit
- test/verify/check-system-realms
- tools/cockpit.spec
Some things left for discussion:
Depends on:
cockpit-packagekit page will now prefer dnf5daemon for these parts, but it won't depend on dnf5daemon-server. This is kinda akward
```
pkg/packagekit/autoupdates.jsx:import { install_dialog } from "cockpit-components-install-dialog.jsx";
pkg/packagekit/kpatch.jsx:import { install_dialog } from "cockpit-components-install-dialog.jsx";
```
PackageKit by default seems to enable `allow_erasing`, while dnf5daemon does not.
```
[root@fedora-43-127-0-0-2-2201 ~]# pkcon install breaking-software                                                                                          17:05:51 [45/62]
Resolving                               [=========================]
Finished                                [                         ] (0%)
The following …
```
> dnf5daemon support in cockpit install dialog

- test/pytest/test_transport.py
For some reason, `cat` is getting spawned in a way that results in it ignoring SIGINT when run inside of a pbuilder on debian-testing.  I'm sure there's a realllly interesting reason for that but Martin has politely suggested that I "pick my battles" on this one, and that sounds good enough to me.
> pytest: use SIGTERM instead of SIGINT

- test/verify/check-metrics
valkey has split packages in Fedora to include two more packages:
- valkey-rdma
- valkey-tls
These need to be removed as well.
Related-to: https://github.com/cockpit-project/bots/pull/8308
> test: Add extra valkey packages to remove

- doc/guide/packages.xml
- pyproject.toml
- src/cockpit/beiboot.py
- src/cockpit/packages.py
- test/pytest/test_beiboot.py
- test/pytest/test_packages.py
Extend the manifest conditions to support alternatives like
{"any": [{"path-exists": "…/packagekit.service"}, {"path-exists": "…/dnfdaemon.service"}]}
---
Initial submission with "no-test" -- I'm sure there will be some changes during review, and we don't use this anywhere yet, only covered in unit tests.
[Package manifests](https://cockpit-project.org/guide/latest/packages.html#package-manifest) can have a list of conditions. Cockpit will only consider the package if *all* conditions are met. This release introduces an operator for alternative checks in a condition, for example
```json
"conditions": [
{"any": [{"path-exists": "…/packagekit.service"}, {"path-exists": "…/dnfdaemon.service"}]}
]
```
That condition will be true if at least one of its subconditions matches.
> bridge: Support disjunctive manifest conditions
